### ISSUE TITLE
There are no files and this repo created 2 minutes ago. All the best

### ISSUE THREAD

**Issue by ayushere** [checkra1n/BugTracker#1]

**Comment by Siguza** [comment]
Yes CHILL the hell out, we got a release to figure out.

**Comment by ayushere** [comment]
Yeh man! just excited for the release :P:P All the best for talk.

**Comment by Siguza** [comment]
The talk is given by qwerty though, not any of the rest of us.

**Comment by ayushere** [comment]
Convey Please. 🍡
