### ISSUE TITLE
Chechra1n disables itself

### ISSUE THREAD

**Issue by warning726** [checkra1n/BugTracker#1003]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 8
2. On what version of iOS is it?
13.3.1
3. What version of checkra1n are you using? GUI or CLI?
GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB type C

**What are the steps to reproduce the issue?**
1. Shutdown or reboot
2. 
3.
...

**What do you expect, and what is happening instead?**
When i Shutdown or reboot the device, the checkra1n app disables itself, cydia doesn‘t start and my tweaks are disabled. Then i have to plug my iPhone again to my mac and i have to enter the device to DFU mode to enable checkra1n and my tweaks. PLEASE FIXX IT. BECAUSE ITS NERVOUS TO PLUG  THE IPHONE EVERYTIME TO MAC TO ENABLE CHECKRA1N AGAIN!!! :( :( :(

**Does the issue also occur if you enable Safe Mode?**
No

**Any other info, error logs, screenshots, ...?**

**Comment by m1stadev** [comment]
checkra1n is a semi-tethered jailbreak, which means that every time you reboot, you need to jailbreak again. it’s supposed to do that lol

**Comment by ann0see** [comment]
If you don’t like to connect your phone to your PC/Mac just buy a ra1nbox or a banana pi zero.

**Comment by warning726** [comment]
thanks for your comments. Its nerveous to activate checkra1n everytime, but I want to enjoy the jailbreak.
