### ISSUE TITLE
Device wouldn’t charge, had to reboot in order to work again

### ISSUE THREAD

**Issue by alexPNG** [checkra1n/BugTracker#1004]
**Tell us about your setup:**

1. What iDevice are you using?
iPhone X, GSM.

2. On what version of iOS is it?
iOS 13.3

3. What version of checkra1n are you using? GUI or CLI?
Latest version for CLI Linux x64.

4. What is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu.

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple USB cord.

**What are the steps to reproduce the issue?**
1. I can’t provide steps to reproduce the issue. Had been jailbroken for a while with the same tweaks, no new tweaks nor updated tweaks for the past week.
...

**What do you expect, and what is happening instead?**
After being jailbroken for over a week, out of nowhere, the device wouldn’t charge. It would make the charging animation and sound, but stop charging after a few seconds. Had to reboot my device in order to work. This was a first case for me, but decided to report it anyways in case it might affect other users. Have been using checkra1n since the Linux release.

**Does the issue also occur if you enable Safe Mode?**
Yes. Only a reboot seemed to do the trick.

**Any other info, error logs, screenshots, ...?**
No kernel panics nor crash reports were found when the issue appeared.

**Comment by ann0see** [comment]
Are you sure it’s not due to a dirty lightning connector or a damaged cable?

**Comment by alexPNG** [comment]
Found the issue. It was just a coincidence that it worked in a non-jailbroken state. It was not related to the jailbreak. False positive, closing this issue.
