### ISSUE TITLE
My iPad Air(A1474) cannot jailbreak

### ISSUE THREAD

**Issue by CN-Mark-Zhang** [checkra1n/BugTracker#1016]
When I tried to jailbreak my iPad Air(runs on iOS 12.4.4) on Ubuntu 19.10 by checkra1n 0.9.8.2,it will stop on step "Right After Trigger".I try to turn on "safe mode" and option -v. But after that, I can't open it, even by press "power+volume on" button. Now, I can only use iTunes to recover it! This problem was same on my friend's iPhone 5S and his iPad mini 2.

**Comment by igor3k** [comment]
Hey checkra1n team, help for us what are fuuu## , how i must have jailbreak 
Ios 12.4.4
iPhone 5s

**Comment by Siguza** [comment]
Duplicate of #984.

**Comment by manexmane21** [comment]
Hi, what is checkra1n suitable for iPad Air (A1474) and what is BIAPAS. Thank you
