### ISSUE TITLE
checkra1n is a grey do not enter symbol

### ISSUE THREAD

**Issue by Sparky32771** [checkra1n/BugTracker#1019]
**Tell us about your setup:**
1. What iDevice are you using?        iPhone 8+
2. On what version of iOS is it?        12.4
3. What version of checkra1n are you using? GUI or CLI?     ?
4. What is your host system (OS version? Hackintosh? VM? etc.)?  Mac Pro Tower iOS: 10.5.8

**What do you expect, and what is happening instead?**
checkra1n is a grey "Do Not Enter" symbol....
ERROR: "You can not open the application checkra1n because it is not supported on this architexture."

![IMG_5938](https://user-images.githubusercontent.com/61945098/76167909-aa3ac180-6140-11ea-8a58-ec7cc7b28feb.jpg)

**Comment by woachk** [comment]
Hello,

We currently do not support versions older than Mac OS X 10.9. 
We also support only the x86_64 architecture for macOS, ppc/ppc64/i386/arm64e aren't supported.
