### ISSUE TITLE
stuck on check if device is ready

### ISSUE THREAD

**Issue by Abbasm234** [checkra1n/BugTracker#102]
**What device + iOS version are you on?**
iPhone X iOS 13.2.2

**What checkra1n version are you using?**
beta .9
**What are the steps to reproduce the issue?**
1. after entering dfu mode via app
2. using MAC OS high Sierra on VM Machine
3.
...

**What do you expect, and what is happening instead?**
Jailbreak my iphone

**Any other info, error logs, screenshots, ...?**
![111](https://user-images.githubusercontent.com/17214222/68549486-dc961580-0411-11ea-8a7f-b26cc14c06c2.PNG)

**Comment by JustTriinn** [comment]
They explained on twitter you cant use VMs without remapping some controllers

**Comment by nullpixel** [comment]
checkra1n does not support most virtual machines.
