### ISSUE TITLE
iPhone 7 boot without jailbreak

### ISSUE THREAD

**Issue by Bonfra04** [checkra1n/BugTracker#1020]
first time doing a jailbreak. using debian 10.
when i run checkra1n the application detect the phone, put it into recovery mode, succesfully detect DFU mode and start booting. when the iphone boot and ask me for the password the application on the computer still shows "booting...". I unlock the phone and no application is installed. the application still shows "booting..." and the cable is stil connected. I've tried in safe mode and also waited abount 30 minute but nothing.

PS. sorry for horrible grammar... i'm italian XD

**Comment by ann0see** [comment]
Maybe try to jailbreak via an other PC or OS?

**Comment by Bonfra04** [comment]
i own only another windows pc but checkra1n is only form mac/linux

**Comment by ann0see** [comment]
You can try bootra1n on the other pc

**Comment by Bonfra04** [comment]
all done thanks!
getting random error 77 even without passcode but with a few try it works!
