### ISSUE TITLE
Feature request: Power down the system from webra1n

### ISSUE THREAD

**Issue by Sundheden** [checkra1n/BugTracker#1027]
Just tried running webra1n on my suuuuper old orange pi zero, and it works like a charm! 

Will most likely be able to sell my old Macbook since this is now working!

Set it up as headless, starting webra1n after boot, but I realize, as soon as I'm done applying the jailbreak to my phone, I have to SSH in to shut it down properly.

I assume this use case is the most common one in regards to webra1n, and since it's required to run as root, we should be able to have a nifty little "exit and power off" feature the webra1n interface? Maybe with another launch switch to allow the option, like --allowpoweroff for example, adding a lil button to the interface.

**Comment by DanyL** [comment]
Hi @Sundheden,
I'm glad you find webra1n useful.

We re-enabled the quit button in webra1n and added a confirmation message to make sure the user is aware of the implications of quitting checkra1n from the web interface.

It'll be available on our next release and by chaining additional commands in bash (which would get executed after quitting checkra1n) you'll be able to shutdown the device cleanly right after (i.e `./checkra1n.app/Contents/MacOS/checkra1n -w 0.0.0.0 4141; shutdown 0`).

**Comment by Siguza** [comment]
checkra1n 0.10.1 should fix this.
