### ISSUE TITLE
Fix for iPhone 5s any model[MAC ONLY]

### ISSUE THREAD

**Issue by BugOClock** [checkra1n/BugTracker#1029]
1. Download checkra1n 0.9.2
2. Open terminal and cd to the folder where you extracted it to.
3. cd into the `checkra1n.app/Contents/Mac`
4. Type the following into terminal:
`sudo ./checkra1n_gui - `
Make sure iPhone is in DFU
5. Profit.
This is for people who don't know, if you did please no hate comments.

**Comment by 141** [comment]
There's no linux 0.9.2 and no mac emulator or hackintosh work for my computers.
Please send me a mac for this to be a fix :P

**Comment by Siguza** [comment]
Gonna mark this as duplicate of #984.
