### ISSUE TITLE
Jailbreak for iPhone 5c

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#1032]
Hello!
I just need some advice about jailbreaking a iPhone 5c, sadly it is on 10.3.3 and not in the 12.3-13.3 ratio.
Could someone help me with this since I'm doing a project with this phone.

Cheers!!

**Comment by ann0see** [comment]
I don’t think the 5c will ever be supported since there are other jailbreaks like Yalu, https://totally-not.spyware.lol Phoenix etc.

**Comment by quilenle** [comment]
iPhone 5C is a 32-bit architecture chip, but the checkra1n only supports the 64-bit architecture chip (5S to X).

**Comment by Siguza** [comment]
As per issue #1, support for 32-bit devices is not planned.
