### ISSUE TITLE
13.3.1

### ISSUE THREAD

**Issue by lkfete** [checkra1n/BugTracker#1038]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using? GUI or CLI?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by deshnawysameh** [comment]
i did every thing to can jailbreak any way i have i phone 8 pluse 64g with ios 13.3.1my pc now is laptop samsung windows 10  i am usuing program 3utools and tryed with many program take scripts online i think i did every to can learn by my self to do it <  also i can go to any one here make it for me in 5 mint thanks dear for your time

**Comment by Siguza** [comment]
Why are you commenting on a closed issue, and an empty one no less? Create a new one and fill out the template, please?

**Comment by deshnawysameh** [comment]
i need to jailbreak my phone by my self
