### ISSUE TITLE
check_snapshot_error_code: General

### ISSUE THREAD

**Issue by Todologo** [checkra1n/BugTracker#1045]
**Tell us about your setup:**
1. What iDevice are you using? Iphone 6s Plus
2. On what version of iOS is it? 13.3.1
3. What version of checkra1n are you using? GUI or CLI? 0.9.8.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Linux Ubuntu. DualBoot Windows.
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? hub?)? Apple/3rd party cable.

**What are the steps to reproduce the issue?**
1. I Jailbraik/Done
2. Bypass iOS 13. - 13.3.1/ReSpring (Using IcloudBypass FRPFILE.COM
3.Open checkra1n2 on the Iphone/Click Cydia,Click Install Cydia: check_snapshot_error_code: General. And At the bottom it sais Exit, I click it and it closes the app. 
...

**What do you expect, and what is happening instead?** It should Install Cydia, But its not doing it. 

**Does the issue also occur if you enable Safe Mode?** Yes, I used SafeMode Also. 

**Any other info, error logs, screenshots, ...?** Not for now.

**Comment by Siguza** [comment]
iCloud bypass isn't supported.
