### ISSUE TITLE
Boot hangs-only Safe Mode booting possible

### ISSUE THREAD

**Issue by forkys-nl** [checkra1n/BugTracker#1047]
**Tell us about your setup:**
1. What iDevice are you using? Iphone SE
2. On what version of iOS is it? 13.3
3. What version of checkra1n are you using? GUI or CLI? Linux Mint + Bootra1n
4. What is your host system (OS version? Hackintosh? VM? etc.)? Linux Mint
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB cable

**What are the steps to reproduce the issue?**
1. run checkra1n as SU
Connect phone
Default Options
2. Entered Recovery Mode OK
Entered DFU Mode OK
3. Booting - hangs on Apple Logo
sometimes: USBMUX error -92

...

**What do you expect, and what is happening instead?**
To arrive in a Jailbroken State- instead Boot process hangs : progress bar on Laptop hangs, Apple Logo frozen on iPhone.

**Does the issue also occur if you enable Safe Mode?**
No

**Any other info, error logs, screenshots, ...?**
Password disabled. Did disable all installed tweaks in iTunes Pro (except for SafeMode and Pro itself)- no result. Also installed USBMUXD ( and Snapd) in Linux Mint - no result.  Same results when using Bootra1n.

**Comment by Siguza** [comment]
If it works in Safe Mode, checkra1n itself it working and it's probably a tweak respring-looping you.
