### ISSUE TITLE
checkra1n loader app not appearing immediately after jailbreaking

### ISSUE THREAD

**Issue by kyondev** [checkra1n/BugTracker#1051]
**Tell us about your setup:**
1. iPhone 6
2. iOS 12.4
3. beta 0.9.8.2, GUI
4. MacBook Air (13-inch, 2017), macOS Catalina 10.15.3
5. Apple Lightning to USB-A cable, included USB-A port

**What are the steps to reproduce the issue?**
1. Jailbreak
2. Helplessly search for checkra1n Loader app

**What do you expect, and what is happening instead?**
I expect the checkra1n Loader app to show up immediately on my home screen after jailbreaking but I instead have to wait a while (30 - 60 secs I guess). 

**Does the issue also occur if you enable Safe Mode?**
Don't know.

**Any other info, error logs, screenshots, ...?**
Since I already have been jailbroken before with checkra1n and have reordered the checkra1n Loader app into my jailbreak folder it always appears in there (Doing a root file system restore doesn't change that fact)

**Comment by eglacias** [comment]
That is the case for my iPhone 6s Plus iOS 12.4 as well, I assume that’s just how this thing behaves and not a bug. There’s a possibility something is still being messed with in the system  after the springboard appears to be loaded , where it’s  icon shouldn’t appear until it’s actually capable of being run?

**Comment by kyondev** [comment]
Here is a little [explanation](https://github.com/checkra1n/BugTracker/issues/1052#issuecomment-599319034) about the loader in an other (actually not an) issue I posted that should help understand but I'd still wait on an official answer.

**Comment by eglacias** [comment]
Thanks, yes got all that.  By the way, what you posted in that link is the official answer, that’s the man! I guess this issue should be closed now eh?

**Comment by kyondev** [comment]
Oh I meant I am waiting for an official answer in _this_ thread here. Maybe there is more we do not know.

**Comment by nullpixel** [comment]
not a bug, it’s just whilst the uicache is updating
