### ISSUE TITLE
[Suggestion] Show Restore System always

### ISSUE THREAD

**Issue by kyondev** [checkra1n/BugTracker#1052]
Show the "Restore System" button always without the need to have Cydia (or in the future another package manger) installed before or just make the whole "troubleshoot" section show always without having to install a package manager beforehand.

**Comment by m1stadev** [comment]
There wouldn't really be any real(?) use to this, since the filesystem is stock before Cydia is installed. Unless, you're suggesting that it'd be used in the off chance you don't have any package manager installed (in which case you can just use snappy)

**Comment by kyondev** [comment]
How can the filesystem be stock if the loader is installed as a system app? And the jailbreak for sure modifies a few other files too.

The use cases I can think of:
- package manager is not installed (like you said)
- you accidentally jailbroke
- you want to revert changes but have no internet connection
- you switch from a different jailbreak and want to be sure everything is stock again.

Because for some reason that option is tied to having Cydia installed and only then works properly when Cydia is installed properly.

And I think it is better having that option always there cause someone will somehow mess up and then having an option that is independent from a package manager would be great.

**Comment by eglacias** [comment]
Sounds logical to me. Surely the system is not stock at that point. Also, a failed package manager install would probably leave a half modified system.

**Comment by ann0see** [comment]
Maybe the checkra1n loader app just runs from RAM (since it’s gone in unjailbroken state). So the filesystem is untouched.

**Comment by Siguza** [comment]
Precisely this.  
The checkra1n loader app runs from a ramdisk, as does SSH and everything else bundled in checkra1n. Until you install Cydia, the rootFS remains readonly.  

Also, unless you manually renamed the APFS snapshot, a simple reboot should revert automatically. If you did manually rename it, log in over SSH and run `snappy -o`, then reboot.

I'm gonna close this as "no action required", since the restore system option would be a nop in the case you're describing.

**Comment by kyondev** [comment]
Thanks than everyone for clarifying the issue for me and helping me understand how checkra1n works a little.
