### ISSUE TITLE
Problem with iCloud on ios 12.4.5 with the ipod touch 6g

### ISSUE THREAD

**Issue by RaphaelDBS20** [checkra1n/BugTracker#1054]
since version 0.9.8.1 of checkra1n, every time I re-jailbreak and restart it to end the jailbreak and re-jailbreak my ipod touch 6g on ios 12.4.5 asks for my iCloud password and secure icloud accounts with two-factor authentication, it asks for a 6-digit code to another one of my apple devices

I'm using an iPod Touch 6g under ios 12.4.5 with checkra1n 0.9.8.2 in GUI mode. i'm using a usb-c port to jailbreak my ipod touch 6g with the official apple cable. i'm using linux to jailbreak my ipod touch 6g, more exactly a debian. i haven't tested a safe mode pass to see if this can fix the problem. 

Thank you checkra1n team and I hope this problem will be fixed soon.

**Comment by Siguza** [comment]
Known bug with 0.9.8(.x), should be fixed in the next release.

**Comment by Siguza** [comment]
Should be fixed in checkra1n 0.10.1.
