### ISSUE TITLE
 Make this jailbreak completely off line, don’t want to have to go online to install Cydia! 

### ISSUE THREAD

**Issue by eglacias** [checkra1n/BugTracker#1055]
If I’m off-line it just says fails to fetch boot strap, or am I correct that this is actually already scheduled to be fixed in some future release?

 even if I have to download the Cydia install files once, somewhere, even on my computer, and then have the jailbreak read them from there, or read them from my Linux boot stick, or anything but having to phone home to jailbreak my phone I considered essential, otherwise we are essentially locked out of a jail break whenever somebody’s web server goes down

**Comment by marleyqp** [comment]
It would be nice but why would that be necessary if you want to install tweaks?

**Comment by eglacias** [comment]
We can use batchomatic to install all tweaks and settings off-line. It is the best way to install your tweaks anyway and requires no Internet connection.

**Comment by eglacias** [comment]
It does bring up a single other point: filza or it’s equivalent with its install feature needs to be included in the jailbreak app!  The free version of that app can be included

**Comment by Siguza** [comment]
We're not bundling arbitrary 3rd party software that we don't have to.  
If you want a homebrew solution, you get a root shell. Use that.  
See #45 for how to make the rootFS r/w permanently.
