### ISSUE TITLE
Cydia doesn’t get removed when restoring filesystem

### ISSUE THREAD

**Issue by Contonion** [checkra1n/BugTracker#106]
**What device + iOS version are you on?**
12.4 iPhone 6S

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. Restore Rootfs and Cydia is still there
...

**What do you expect, and what is happening instead?**
Cydia to be gone all the way instead of a blank icon

**Any other info, error logs, screenshots, ...?**
Thanks for all your work!

**Comment by Lonegwadiwaitor** [comment]
I believe I saw this in the FAQ somewhere, it's already known about. You could rejailbreak and delete /Applications/Cydia.app yourself then run uicache probably

**Comment by nullpixel** [comment]
This is in the FAQ: cydia is removed, but the icon is not.
