### ISSUE TITLE
Don't work on Osx Mavericks 10.9.5

### ISSUE THREAD

**Issue by AdolfoPD** [checkra1n/BugTracker#1063]
Freeze on half process.

**Comment by qwertyuiop1011** [comment]
Can you give more details or use the bug format? I don’t know what the problem is but I would probably guess.
1. Your using a unsupported device or iOS version.
2. Your running on a virtual machine.

**Comment by AdolfoPD** [comment]
Hi!

I’m using IOS 13.2.3 and real machine no VM!



Sds,

Adolfo P. Damaceno, MBA-MIT, ITIL-F, MCP, SFC
Adolfopd@Yahoo.com.br  
(+5511) 9-7266-1936

**Comment by Siguza** [comment]
Please file a new ticket and full out the "bug report" template.
