### ISSUE TITLE
Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)

### ISSUE THREAD

**Issue by ja1lbreaker** [checkra1n/BugTracker#1067]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 5s
2. On what version of iOS is it? 12.4
3. What version of checkra1n are you using? GUI or CLI? GUI beta 0.9.8.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? macOS Catalina 10.15.2
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? 3rd party lighting cable

**What are the steps to reproduce the issue?**
1. Opening checkra1n
2. Running through the standard procedures
3. Before the phone boots back up it comes up with the error code -20
...

**What do you expect, and what is happening instead?**
I expect that that checkra1n to go through smoothly without errors instead it gives me this error.

**Does the issue also occur if you enable Safe Mode?**
Yes, it does.

**Any other info, error logs, screenshots, ...?**
I have jailbroken with previous versions of checkrain before and have jailbroken with unc0ver. With unc0ver I restored rootfs and I am still getting error -20.

**Comment by ja1lbreaker** [comment]
Same error with checkra1n beta 0.9.8

**Comment by ja1lbreaker** [comment]
Fixed this by using [checkrain 0.9.7](https://checkra.in/releases/0.9.7-beta).

**Comment by Siguza** [comment]
Duplicate of #984.

**Comment by Rcnauj78** [comment]
hi, any solution for iOS 12.0, iPhone 7?
(same error with all releases)

**Comment by Siguza** [comment]
@Rcnauj78 lowest iOS version that is officially supported is 12.3.
