### ISSUE TITLE
Getting kernel ASLR slide?

### ISSUE THREAD

**Issue by jorgschulze73** [checkra1n/BugTracker#1070]
Hello, does checkra1n implement any shortcut to get the kernel ASLR slide? I already tried to have a look at `task_info`, but considering there's no `hsp4` patch either, I was not surprised when I didn't find anything.
I know there's plenty of ways to calculate it, but really didn't want to start hardcoding offsets of kernel structures etc and was hoping for a quicker solution.

**Comment by Siguza** [comment]
We have true tfp0, not hsp4:

```c
uint64_t get_kslide(void)
{
    task_t tfp0;
    kern_return_t ret = task_for_pid(mach_task_self(), 0, &tfp0);
    if(ret != KERN_SUCCESS) return 0;
    task_dyld_info_data_t info;
    uint32_t count = TASK_DYLD_INFO_COUNT;
    ret = task_info(tfp0, TASK_DYLD_INFO, (task_info_t)&info, &count);
    if(ret != KERN_SUCCESS) return 0;
    return info.all_image_info_size;
}
```

And make sure you have the `task_for_pid-allow` entitlement.
