### ISSUE TITLE
Disable KPP?

### ISSUE THREAD

**Issue by jorgschulze73** [checkra1n/BugTracker#1074]
Hello, I would like to experiment making some small patches in kernel, but all the memory pages I'm trying to touch have protection `---`; I tried to set them to `RW-` in order to make my changes usin `mach_vm_protect` (passing the kernel task port), but it fails every time with `(os/kern) protection failure` so my assumption is that KPP/KRTT is still active. If that's the case, is there a way to disable it entirely (maybe with some unknown boot parameter)?
Thank you in advance, really appreciate your work :)

**Comment by Siguza** [comment]
So we _do_ leave KPP/KTRR enabled, and there is an issue that tracks the disabling of kernel security features: #168.

However what you're seeing is something entirely different. XNU does not create VM entries to reflect its own binary, it only creates raw page table entries and the huge `---` section you're seeing. Disabling KPP/KTRR would not change that.
