### ISSUE TITLE
iphone stuck on the page Hello

### ISSUE THREAD

**Issue by peyou01** [checkra1n/BugTracker#1075]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using? GUI or CLI?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by peyou01** [comment]
Hello
after jailbreacking iphone X Ios 13.3.1 with Checkra1n, under linux Ubuntu , the device is blocked on the first page "Hello" , no way to do anything from there.. thnaks for your help

**Comment by littlelailo** [comment]
Go through the Setup process first before installing the jailbreak. If the device is iCloud locked and you can't do that, then this is your problem, we don't support iCloud locked devices.
