### ISSUE TITLE
launchctl reboot userspace makes the device fully reboot to an unjailbroken state

### ISSUE THREAD

**Issue by clarityzzz** [checkra1n/BugTracker#1076]
**Tell us about your setup:**
1. What iDevice are you using? iPhone X
2. On what version of iOS is it? 13.4
3. What version of checkra1n are you using? GUI or CLI? 0.9.9 Beta GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)? Not Applicable
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Not Applicable

**What are the steps to reproduce the issue?**
1. Open a terminal or ssh into the device as root
2. Type 'launchctl reboot userspace'
3. Observe results.
...

**What do you expect, and what is happening instead?**
Expected result is a full userland reboot (even launchd), keeping the kernel untouched, mimicking OSX. What happens is that the device reboots and gets unjailbroken.

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**
Probably a Substrate issue.
Works fine on unc0ver 4.3.x with substitute.

**Comment by sbingner** [comment]
Fixed it - it should get into whatever the next release is

**Comment by clarityzzz** [comment]
@sbingner Just tried 0.10.0 and Substrate seems to be working fine after the userspace reboot! The local ssh server stops working, though.

**Comment by Siguza** [comment]
I feel like this stems from the same issue as #1160.  
I'll mark this issue as fixed though.
