### ISSUE TITLE
from 0.9.8 to 0.9.8.2 problem on loader, error on INSTALLING CYDIA

### ISSUE THREAD

**Issue by rncebm** [checkra1n/BugTracker#1077]
from 0.9.8 to 0.9.8.2 problem on loader, error on INSTALLING CYDIA

kindly fix the problem, the best VERSION of checkra1n is 0.9.7 & 0.9.6, after JAILBREAK load the LOADER, NO PROBLEM on INSTALLING CYDIA, BUT there is only 1 problem AFTER iCloud Bypass, then use again 0.9.7 to reload ios, it will NOT CONTINUE to finished the iOS, So i use again 0.9.6 to finished the phone after DOWNGRADE.

kindly FIX the BUG/PROBLEM, thank you very much.

br

RNC_EBM

**Comment by AMDBartek** [comment]
You make sense don't.

**Comment by Siguza** [comment]
iCloud bypass = not supported.
