### ISSUE TITLE
Error code -27

### ISSUE THREAD

**Issue by Willianbt** [checkra1n/BugTracker#108]
Hello!
I have a problem, giving error code 27. The following message appears during jailbreak installation: "Error report - Request for Permission".

Help me

Iphone 7 GSM
iOs 13.1.3

**Comment by Lonegwadiwaitor** [comment]
Have you made sure to click the 'Trust this Computer?' box on your iPhone?

**Comment by Willianbt** [comment]
No, it's not showing up to me hahaha

**Comment by Willianbt** [comment]
YES, trust this computer

**Comment by Lonegwadiwaitor** [comment]
Just to confirm, works now?

**Comment by Willianbt** [comment]
no, now it's in error code -31

**Comment by Lonegwadiwaitor** [comment]
Are you on a Hackintosh or an actual Mac?

**Comment by Willianbt** [comment]
Hackintosh

**Comment by nullpixel** [comment]
Dupe of #9, hackintoshes are not supported technically.
