### ISSUE TITLE
iphone 8, cellular data , sms , calls dosn't works

### ISSUE THREAD

**Issue by carc2000** [checkra1n/BugTracker#1086]
When i had did jailbreak and bypass iclod activetion, cellular data , sms , calls dosn't woks,
i opened terminal from linux (ubuntu 18.04) after did jailbreak open connection SSH with my iphone for copy on my desktop this files : 

/var/root/library/lockdown/data_ark.plist
/var/containers/data/system/com.apple.mobileactivationd/library/internal/data_ark.plist 
/var/containers/data/system/com.apple.mobileactivationd/library/activation_records/activation_record.plist

but did't work, i did restoy my iphone whit itunes, after finished data connection dosen't work more.

please everybody can help me for fix them

**Comment by eglacias** [comment]
iCloud bypass does exactly what you’re describing. You will not get a cellular signal anymore. This has nothing to do with this jailbreak, but the fact that there is no true iCloud bypass yet, it just deletes some system files that render your phone and a half usable state

**Comment by Siguza** [comment]
iCloud bypass isn't supported.

**Comment by carc2000** [comment]
> iCloud bypass does exactly what you’re describing. You will not get a cellular signal anymore. This has nothing to do with this jailbreak, but the fact that there is no true iCloud bypass yet, it just deletes some system files that render your phone and a half usable state

Can you help me for fix there pleas?

@eglacias

**Comment by eglacias** [comment]
There is no fix, this (nor any) iCloud bypass simply does not work, it is broken as described
