### ISSUE TITLE
Wallpaper freezes 

### ISSUE THREAD

**Issue by patrickawsomeness1** [checkra1n/BugTracker#109]
**What device + iOS version are you on?**

iPhone 7 iOS 13.2.2
**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1.changing wallpaper in jailbreak state
2.
3.
...

**What do you expect, and what is happening instead?**
Idk

**Any other info, error logs, screenshots, ...?**
No

**Comment by ssant96** [comment]
I had the same issue here but it fixed by itself when I changed wallpaper in non jailbroken state.

**Comment by nullpixel** [comment]
Dupe of #84
