### ISSUE TITLE
where can i download checkra1n 0.10.0 beta for LINUX

### ISSUE THREAD

**Issue by rncebm** [checkra1n/BugTracker#1099]
where can i download checkra1n 0.10.0 beta for LINUX ?

i need official link, thank you very much.

best regard

RNC_EBM

**Comment by Siguza** [comment]
Nowhere. 0.10.0 wasn't a proper release, it was only seeded to testers and we still don't link to it on our website.  
There are a number of issues with it, and once those are fixed, we will do a proper release with a Linux version.

**Comment by rncebm** [comment]
Im a cellphone technician sir, i also need to test it sir, can u give the
link for linux sir, thank you sir
