### ISSUE TITLE
Checkra1n on iPhone show No internet connect then close

### ISSUE THREAD

**Issue by qyouqme** [checkra1n/BugTracker#11]
**What device + iOS version are you on?**
iPhone 6s+iOS 13.2.2

**What are the steps to reproduce the issue?**
1.
2.
3.
...

**What do you expect, and what is happening instead?**
Run Checkra1n app on iPhone

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Hi, do you have a Chinese iPhone?

**Comment by qyouqme** [comment]
> Hi, do you have a Chinese iPhone?

Yes.

**Comment by nullpixel** [comment]
Hi, I've closed this issue as a duplicate of #3.
