### ISSUE TITLE
checkra1n jumps over bootstrap upload

### ISSUE THREAD

**Issue by memorycannibal** [checkra1n/BugTracker#1100]
**Tell us about your setup:**
1. What iDevice are you using?
 iPad mini 2
2. On what version of iOS is it?
  12.3.1
3. What version of checkra1n are you using, and GUI or CLI?
  every, from 0.9.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
    macOS High Sierra 10.13.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
   USB-A
**What are the steps to reproduce the issue?**
1.  plug in ipad
2. step by step from UI instructions
...

**What do you expect, and what is happening instead?**
   ez pz jailbreak

**Does the issue also occur if you enable Safe Mode?**
   Sry about my engl at first.
   I had successfull jailbrake by 0.9.5, but then i tryed to renaming Setup.app , my home button stop working. After restart, I have no more success jailbreaks 
   Right now i have some strange thing on almost all versions of checkra1n, include 0.10.0. Then program types "booting", i have checkra1n logo with text :"booting.  Right after, it changes on default boot logo , and after 10 seconds, program saying that she is uploading bootstrap, but ipad is already on activation screen.

**Any other info, error logs, screenshots, ...?**
https://www.youtube.com/watch?v=I_nwF9jU9SY   i made a little video

tnx.

**Comment by Siguza** [comment]
Note that we don't support iCloud lock bypasses.

And normally the bootstrap upload happens _after_ you unlock the device, so I see no issue there. If your device is rejecting connection because it's not unlocked though, I'm afraid I can't help you with that.
