### ISSUE TITLE
checkra1n 0.10.0 A7 issue Status

### ISSUE THREAD

**Issue by CanerKaraca23** [checkra1n/BugTracker#1102]
Is there any "right before trigger" error on A7 this version? I can't wait to jailbreak my iPhone 5s with checkra1n. Version 0.9.6 is running on A7 but cannot be used on bootra1n. I don't have mac.

(This is not a bug report just question for other A7 users)

**Comment by FDeghy** [comment]
we are waiting for new version (0.10.0) of checkra1n... 
waiting..........

**Comment by libf-de** [comment]
The 0.10.0 beta worked fine on my iPad mini 2. It threw an error message but jailbroke just fine.

**Comment by ghost** [comment]
Okay, for me, i have plug in and plug on my cable and it work, iOS 12.4.1 iPhone 5s Checkra1n 0.10.1
