### ISSUE TITLE
Unistall cydia without restore

### ISSUE THREAD

**Issue by MrRoboto420** [checkra1n/BugTracker#1108]
Is it possible to be able to downloads apps from cydia and then be able to uninstall cydia without restoring and still be able to use cydia apps??(Maybe in a future update of checkra1n)

**Comment by steven30303** [comment]
Open cydia --> installed --> cydia installer --> modify --> remove --> confirm
should do the job altough i have not tested this cuz i see no need for this

**Comment by Siguza** [comment]
This is not related to checkra1n.  
Also you can do this via SSH and `apt`/`apt-get`.
