### ISSUE TITLE
Cydia Tweaks Not Installing

### ISSUE THREAD

**Issue by Steave0982** [checkra1n/BugTracker#111]
**What device + iOS version are you on?**
Iphone X / IOS 13.2.2

**What checkra1n version are you using?**
Beta 0.9.1

**What are the steps to reproduce the issue?**
1. Attempt to install a tweak
2. Respring

...

**What do you expect, and what is happening instead?**
I expect my tweak to install and to start working. 

When the tweak is installed, it says its installed in cydia but is doesn't show in settings, nor does the tweak actually work

**Any other info, error logs, screenshots, ...?**
N/A

**Comment by natewall824** [comment]
I am having the same issue on the same phone and version, so if you find anything out let me know.

**Comment by Shadowedstalker** [comment]
Have you installed PreferenceLoader from http://rpetri.ch/repo?

This also can be due to a source conflict within Cydia (as was my issue) I deleted the sources and added them back one by one until I found the problem. (XEN)

**Comment by natewall824** [comment]
I have installed the preference loader from rpetri, but I will try removing basically all my sources. I have a lot of sources previously installed for some reason. I did previously remove a good bit of sources, but I haven't removed the one you said. (XEN)

**Comment by natewall824** [comment]
I also do not know if this is an issue, but the checkra1n substrate repo is empty.

**Comment by Shadowedstalker** [comment]
I can "almost guarantee" it's a source issue. As I had the same issue Checkra1n empty and no settings. If you have Xen installed remove it.

**Comment by Shadowedstalker** [comment]
After I removed that source Checkra1n showed and PreferenceLoader took affect.

**Comment by natewall824** [comment]
I have removed like every extra source (besides the main sources), and it still has not fixed.

**Comment by Shadowedstalker** [comment]
Ok, now "system restore" and rejailbreak. install Cydia and check sources.

**Comment by Shadowedstalker** [comment]
Any luck?

**Comment by natewall824** [comment]
It finally worked thanks for your help!

**Comment by Shadowedstalker** [comment]
Glad I could help.

**Comment by natewall824** [comment]
After stuff showed up, I downloaded Cydia substrate, and it crashed my Cydia, and I have rebooted and reinstalled Cydia. However, it still crashes. Any ideas on what to do now?

**Comment by Shadowedstalker** [comment]
ssh into the device. Go to var/mobile/library/cydia/ delete metadata.cb0. Cydia will open again. reinstall the tweaks.

Pain I know but it does work. My take time, but it works.

**Comment by natewall824** [comment]
I don't know how to ssh into the device tbh.

**Comment by Shadowedstalker** [comment]
well I can help you there as well.

Connect the device to your mac. open terminal. enter ssh root@yourIP (on the phone go to wifi click info and get your ip.)

if it asks you a question type yes.

the default password is alpine.

once you see it say your device name ~root type cd /
cd var/mobile/Library/Cydia/

ls (you should see metadata.cb0)

rm metadata.cb0

exit

Now open Cydia.

**Comment by Shadowedstalker** [comment]
There's another way if you have issues. 

Open ignition.fun

Install FilzaEscaped

Go to var/mobile/library/cydia/metadata.cb0 and delete metadata.cb0

Open cydia, and boom! It's fixed

This is much more easier if you don't know how to SSH into your phone.

Credit: Vlaampie

**Comment by natewall824** [comment]
For some reason, I can not access the website for ignition, and it won't let me download apps. 

Also, I have tried to ssh, but when I do the iproxy 2222 22 it gives me a lot of @@@@.

**Comment by Shadowedstalker** [comment]
OK Don't iproxy. just ssh@root. If you still get the @@@@ Host Warning@@@

type ssh-kengen -R your ip.

**Comment by Shadowedstalker** [comment]
You have to jailbreak and have cydia installed so that Open SSH is installed

**Comment by Shadowedstalker** [comment]
https://ignition.fun/

**Comment by natewall824** [comment]
I dont know my ip, and the ignition is slow today

**Comment by Shadowedstalker** [comment]
![IMG_E0836](https://user-images.githubusercontent.com/41554466/68715504-28f76780-0570-11ea-9c5f-8270467eb86f.JPG)
![Uploading IMG_E0837.JPG…]()

**Comment by Shadowedstalker** [comment]
![IMG_E0837](https://user-images.githubusercontent.com/41554466/68715566-504e3480-0570-11ea-9cc6-1aa09267940a.JPG)

**Comment by natewall824** [comment]
So I typed in my ip address with it, and it says that command is not found.

**Comment by natewall824** [comment]
Scratch that I just need a root# now.

**Comment by Shadowedstalker** [comment]
ssh root@192.168.X.X

**Comment by natewall824** [comment]
I did that now what?

**Comment by Shadowedstalker** [comment]
if it says device name ~root.

type cd /
cd var/
cd mobile/
cd library/
cd cydia
rm metadata.cb0

**Comment by natewall824** [comment]
Which filza did you download? I finally got ignition to work but none of the filza apps are working.

**Comment by Shadowedstalker** [comment]
I did not, that was info I reposted from another user. but what you are looking for is Filzaecsaped. It's a modded non-jailbreak version of Filza.

**Comment by Shadowedstalker** [comment]
Were you successful?

**Comment by natewall824** [comment]
I was not able to get it working.

**Comment by Shadowedstalker** [comment]
you weren't able to SSH or gt filazescaped?

**Comment by natewall824** [comment]
Yeah the SSH was not working and I can’t download the filza. I think I’m going to have to try to do SSH again.

**Comment by Shadowedstalker** [comment]
if you need more help with sshing let me know I can see what I can do.

**Comment by natewall824** [comment]
> if you need more help with sshing let me know I can see what I can do.

So when I ssh root@(my ip), it does not do anything. The next line is blank.

**Comment by Shadowedstalker** [comment]
Can you send a screenshot?

**Comment by Shadowedstalker** [comment]
It should ask password, though you won't see it type out.

**Comment by natewall824** [comment]
![Screen Shot 2019-11-13 at 2 04 09 PM](https://user-images.githubusercontent.com/36255347/68799888-9cf04900-061e-11ea-8310-33446dca9961.png)

**Comment by natewall824** [comment]
![Screen Shot 2019-11-13 at 2 04 09 PM](https://user-images.githubusercontent.com/36255347/68799952-c5784300-061e-11ea-956f-07efacf588a7.png)

**Comment by Shadowedstalker** [comment]
So it just hangs there?

**Comment by natewall824** [comment]
It eventually says operation timed out

**Comment by Shadowedstalker** [comment]
You still have your phone jailbroken and Cydia is still installed correct?

**Comment by natewall824** [comment]
Cydia won't open, but as far as I know, it is installed. I restored system and redownloaded checkra1n, and then installed Cydia, but it does not open after.

**Comment by Shadowedstalker** [comment]
OK, force close terminal disconnect the phone from the mac and reconnect open terminal and try again.

**Comment by natewall824** [comment]
The new version of checkra1n gives an option to go into safe mode, so I am currently trying that.

**Comment by Shadowedstalker** [comment]
Good Luck, though Safe Mode shouldn't work for that.

The next SSH line should read
root@IP's password: you should see a key symbol.

**Comment by natewall824** [comment]
So I forced closed terminal and tried it again. It did not work.

**Comment by natewall824** [comment]
I have gotten the root password thing before, so I don't know why it's not working.

**Comment by Shadowedstalker** [comment]
Let's try this do a "system restore" (don't worry about the left over icons.) Once that is done rejailbreak install Cydia. Don't open it.

open terminal
type ssh-keygen -R yourIP hit enter
type ssh root@yourIP hit enter
answer yes hit enter
Default password alpine

**Comment by natewall824** [comment]
I get a command now found when I type ssh-kengen

**Comment by Shadowedstalker** [comment]
Keygen

**Comment by natewall824** [comment]
lol my bad, also when I type ssh@rootip it does the same thing command not found. Is it ssh root@ip ?

**Comment by Shadowedstalker** [comment]
Yes. Sorry, I am in so many issue attempting to fix I miss typed that ssh root@IP

**Comment by Shadowedstalker** [comment]
I fixed the above comment, sorry about that.

**Comment by natewall824** [comment]
Okay so I entered in the password what now lol

**Comment by Shadowedstalker** [comment]
cd /var/mobile/library/cydia/
rm metadata.cb0

**Comment by natewall824** [comment]
So I went step by step (from your earlier message) and it says I do not have a library. When I go to type in cd library/ it gives me no such file or directory.

**Comment by Shadowedstalker** [comment]
cd /
ls
cd var/
ls
cd mobile/
ls
cd library/
ls 
cd cydia/

the ls inbetween allow you to see the directories.

**Comment by Shadowedstalker** [comment]
You may still be in var/root, not root.

**Comment by natewall824** [comment]
If I am how would I know and how would I get out lol. Thanks so much for all your help.

**Comment by Shadowedstalker** [comment]
Also it may read Library/ and Cydia/ with Caps.

Type cd / hit enter it should read / root not ~root.

**Comment by natewall824** [comment]
My thing says root#

**Comment by Shadowedstalker** [comment]
hit ls (lower case LS), do you see a bunch of directories or just Library and Media?

**Comment by natewall824** [comment]
I see a bunch of directories

**Comment by Shadowedstalker** [comment]
ok, good,

cd var/
cd mobile/
cd Library/
cd Cydia/

**Comment by Shadowedstalker** [comment]
If it tells you no directory type ls and look

**Comment by natewall824** [comment]
We good now I finally got into cydia

**Comment by Shadowedstalker** [comment]
rm metadata.cb0

**Comment by natewall824** [comment]
So after that what should I do?

**Comment by Shadowedstalker** [comment]
type exit
close terminal, open cydia.

**Comment by natewall824** [comment]
It finally fixed!!!! It is offering an update for Bourne-Again SHell, you think it would be okay to download? Lol I am so thankful for your help man.

**Comment by Shadowedstalker** [comment]
it's fine.I have updated everything it says.

**Comment by Shadowedstalker** [comment]
That's why we are here, to help each other. I have been helping people since the release of Checkra1n. Now if you run into someone that has that problem you might just be able to help them.

**Comment by natewall824** [comment]
Thanks for real, I will do the same for others.

**Comment by Shadowedstalker** [comment]
One more think I suggest is install NewTerm 2 (a mobile terminal) in case you have issues with downloaded tweaks not showing on the springboard. you can open it and type uicache it rebuilds the cache and will show the app icons.

**Comment by littlelailo** [comment]
Closing this as it seems like the bug got fixed. This also wasn't checkra1n but cydia related
