### ISSUE TITLE
Timeout while breaking iPhone 5s with ios12.4

### ISSUE THREAD

**Issue by doct0r3** [checkra1n/BugTracker#1110]
iPhone 5s with iOS 12.4.5. Using linux on pc,Checkra1n 0.9.8. Task time out while running check m8 tigger stage.I ve tried the cli and gui version but have the same issue

**Comment by The-SamminAter** [comment]
Same thing is happening on my iPhone 5s, on both iOS 12.4 and 12.4.4.
Have tried on Linux and macOS, Linux doesn't work at all, macOS fails at the trigger stage.
@maoliaoiwanna I suggest you remove the iOS 12.4.5 in this issue's name, as the iOS version doesn't seem to matter.

**Comment by doct0r3** [comment]
> Same thing is happening on my iPhone 5s, on both iOS 12.4 and 12.4.4.
> Have tried on Linux and macOS, Linux doesn't work at all, macOS fails at the trigger stage.
> @maoliaoiwanna I suggest you remove the iOS 12.4.5 in this issue's name, as the iOS version doesn't seem to matter.

Now I have downgraded my iPhone 5s to 12.4.4,and the same issue continues........Someone told me that checkra1n will work on Mac,so maybe later I will try it

**Comment by arjansimon** [comment]
same here, tried it multiple times.. didn't work. after that I tried my iPad and that worked. then my iPhone 5 again and that didn't work again.. then my iPhone 8 Plus and that worked just fine again. Then I tried my iPhone 5 again and nope.. failed again..

**Comment by Siguza** [comment]
Duplicate of #984.
