### ISSUE TITLE
Boot loop

### ISSUE THREAD

**Issue by vaanuvaa** [checkra1n/BugTracker#1114]
**Tell us about your setup:**
1. What iDevice are you using? Iphone x
2. On what version of iOS is it? Ios 13.3.1
3. What version of checkra1n are you using, and GUI or CLI? 0.9.8.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Xubuntu 18.4
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple original cable.

**What are the steps to reproduce the issue?**
1.  Can’t go safe mode.
2. 
3.
...

**What do you expect, and what is happening instead?**
After i try to open a iso file with filza, phone froze and reboot into normal mode

**Does the issue also occur if you enable Safe Mode?**
Safe mode not working.. when i go to safe mode. Again device restart into normal mode

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Are you using the "Safe Mode" checkbox in checkra1n?

**Comment by vaanuvaa** [comment]
> Are you using the "Safe Mode" checkbox in checkra1n?


I don’t know which safe mode! But it came with checkra1n.

**Comment by goulibaseiy** [comment]
Didn't solve the problem till now? Connect iPhone to computer, launch EelPhone iOS System Repair on computer, choose standard mode to fix iPhone boot loop, keep connection during the whole process, it's the mode to fix iPhone system problem without losing data.

**Comment by nergzd723** [comment]
> > Are you using the "Safe Mode" checkbox in checkra1n?
> 
> I don’t know which safe mode! But it came with checkra1n.

Please use Safe mode option, if it doesn't work, restore with iTunes.

**Comment by vaanuvaa** [comment]
Already restored

**Comment by Siguza** [comment]
Gonna close as non-reproducible then. :/
