### ISSUE TITLE
Any springboard enabled tweak crashes springboard

### ISSUE THREAD

**Issue by slickpads** [checkra1n/BugTracker#112]
**What device + iOS version are you on?**
I am on iOS 13.1.2

**What checkra1n version are you using?**
The first release
**What are the steps to reproduce the issue?**
1.Cylinder, snowboard or any customization app is installed (I will use cylinder)
2.when going into the settings and enabling cylinder.
3.going to home screen and swiping right or left instantly crashes spring board and puts into safe mode.
...

**What do you expect, and what is happening instead?**
I expect cylinder to change my swiping animations like it’s supposed to

**Any other info, error logs, screenshots, ...?**No

**Comment by NoisyFlake** [comment]
This is not a checkra1n problem, the developer simply has to update the tweak for iOS 13.

**Comment by nullpixel** [comment]
as per above:

> This is not a checkra1n problem, the developer simply has to update the tweak for iOS 13.
