### ISSUE TITLE
iphone stopped working 

### ISSUE THREAD

**Issue by azooox27** [checkra1n/BugTracker#1122]
iphone x gsm ios 13.4 stopped working after using checkrain 0.9.8.2 (untested devices enabled)

**Comment by ghost** [comment]
I would like to help you but need some more information. Please see https://github.com/checkra1n/BugTracker/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Siguza** [comment]
0.9.8.2 doesn't support 13.4.
