### ISSUE TITLE
Checkra1n 0.9.9 and 0.10.0 are missing kernel data in task_dyld_info for pid 0

### ISSUE THREAD

**Issue by pwmoore** [checkra1n/BugTracker#1124]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7, 8
2. On what version of iOS is it? 13.4
3. What version of checkra1n are you using, and GUI or CLI? 0.9.9, 0.10.0
4. What is your host system (OS version? Hackintosh? VM? etc.)? macOS 10.15.2
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-C

**What are the steps to reproduce the issue?**
1. Jailbreak device with checkra1n
2. Attempt to obtain task_dyld_info for kernel task (either with jbctl or via task_info())
3. task_dyld_info structure just returns 0 for both all_image_info_addr and all_image_info_size for the kernel task.
4. jbctl reports similar outcome

**What do you expect, and what is happening instead?**
I expect task_info() to be able to provide kernel data info in the dyld_info structure.

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
n/a

I realize these are beta and unsupported versions, but wanted to give you guys a heads up that it's an issue so it could be fixed before the next release. I am able to successfully get tfp0.

**Comment by ghost** [comment]
> **Tell us about your setup:**
> 
> 1. What iDevice are you using? iPhone 7, 8
> 2. On what version of iOS is it? 13.4
> 3. What version of checkra1n are you using, and GUI or CLI? 0.9.9, 0.10.0
> 4. What is your host system (OS version? Hackintosh? VM? etc.)? macOS 10.15.2
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-C
> 
> **What are the steps to reproduce the issue?**
> 
> 1. Jailbreak device with checkra1n
> 2. Attempt to obtain task_dyld_info for kernel task (either with jbctl or via task_info())
> 3. task_dyld_info structure just returns 0 for both all_image_info_addr and all_image_info_size for the kernel task.
> 4. jbctl reports similar outcome
> 
> **What do you expect, and what is happening instead?**
> I expect task_info() to be able to provide kernel data info in the dyld_info structure.
> 
> **Does the issue also occur if you enable Safe Mode?**
> Yes
> 
> **Any other info, error logs, screenshots, ...?**
> n/a
> 
> I realize these are beta and unsupported versions, but wanted to give you guys a heads up that it's an issue so it could be fixed before the next release. I am able to successfully get tfp0.

**Comment by Siguza** [comment]
This is actually an issue with 13.4 rather than the checkra1n versions you mentioned, but we're aware of the issue and have fixed it internally.

We're just holding off on a new release (and don't link either 0.9.9 or 0.10.0 on the website) because there are some unresolved issues that makes checkra1n never work on certain devices.

**Comment by pwmoore** [comment]
That sounds good! Looking forward to the next release :)

**Comment by Siguza** [comment]
Should be fixed in checkra1n 0.10.1.
