### ISSUE TITLE
Apps crashing 

### ISSUE THREAD

**Issue by my-name-is-nheo** [checkra1n/BugTracker#1126]
**Tell us about your setup:**
1. What iDevice are you using? iphone 8 Plus
2. On what version of iOS is it? 13.3.1
3. What version of checkra1n are you using, and GUI or CLI? 0.9.8.2 Beta
4. What is your host system (OS version? Hackintosh? VM? etc.)? cataline 10.15.2
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?Apple cord

**What are the steps to reproduce the issue?**
1. jailbreak 
2. open any app
3.
...

**What do you expect, and what is happening instead?**
expected to run nice and smoothly, but some apps crashing and closing. 

**Does the issue also occur if you enable Safe Mode?**
no it does not

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
If it doesn't happen in Safe Mode, it's gonna be some tweak. There are plenty of resources on how to debug this, if you need assistance I'll direct you at either the [jailbreak subreddit](https://reddit.com/r/jailbreak) or the [jailbreaking Discord](https://discord.gg/jb).
