### ISSUE TITLE
GUI cut.

### ISSUE THREAD

**Issue by bill88t** [checkra1n/BugTracker#1128]
**Tell us about your setup:**
1. Elementary OS
3. 0.9.8.2 but this was present from 0.9.8

**What are the steps to reproduce the issue?**
1. Install Checkra1n
2. Open the GUI

**What do you expect, and what is happening instead?**
The buttons are outside the window making them imposible to click. (Screenie attached)
Also the window does not allow scaling

![Screenshot from 2020-04-02 17-51-23](https://user-images.githubusercontent.com/21365918/78269532-630ed900-7512-11ea-98df-0adbf3295f59.png)

**Comment by bill88t** [comment]
However, whenever I launch checkra1n with the --gui argument it opens properly.
the menu entry however only contains the command "checkra1n". Shouldn't it be "sudo checkra1n --gui"?

**Comment by nikias** [comment]
@bill88t  can you edit the file `/usr/share/applications/checkra1n.desktop` (you need root privileges to do that, so use `sudo`) and modify the line
```
Exec=checkra1n
```
to say
```
Exec=checkra1n --gui
```
And make sure to save the file. Then launch it again from your desktop. I wonder if this will make it work?

**Comment by bill88t** [comment]
Already did that. With this edit the checkra1n app opens correctly. Shouldn't this be the default menu entry then?

**Comment by nikias** [comment]
Thanks. I guess we will change it then. The checkra1n code determines automatically if a GUI should be used based on the fact if it was launched from a terminal or not. But this doesn't explain that in one case it looks scaled while in the other case it seems to work. Can you post a screenshot with the working GUI for reference?

**Comment by bill88t** [comment]
Sure, 
![Screenshot from 2020-04-07 12-06-38](https://user-images.githubusercontent.com/21365918/78651101-8b0e8b80-78c8-11ea-986d-37d7502e5255.png)
This is now with the menu entry being set as "sudo checkra1n --gui", I ran the jb a few times, it works just as good as in the tui. I can confirm that the "checkra1n --gui" works aswell, but just for safety I prefer adding the sudo in the mix.

**Comment by Siguza** [comment]
Should be fixed in 0.10.1.

**Comment by nergzd723** [comment]
Still an issue in Wayland, see #1193 , but is fixed and working in X11.
