### ISSUE TITLE
Iphone 8 Plus on IOS 13.4 cannot jailbreak

### ISSUE THREAD

**Issue by nickbze** [checkra1n/BugTracker#1135]
**Tell us about your setup:**
1. What iDevice are you using?  Iphone 8 Plus GSM 64GB
2. On what version of iOS is it? 13.4
3. What version of checkra1n are you using, and GUI or CLI?  Beta Version 0.10.0  GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?  MacOS Catalina 10.15.4
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB A

**What are the steps to reproduce the issue?**
1. after checkrain showing Booting Message
2. The Iphone 8 Plus stuck at Apple Logo
3. After three minute, an error message saying jailbreak fail, error-20
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
![1](https://user-images.githubusercontent.com/63136924/78418393-f6bad500-75f8-11ea-8019-7e3ad030e8fe.JPG)
![2](https://user-images.githubusercontent.com/63136924/78418394-f91d2f00-75f8-11ea-9677-8f4a9aa0c6d7.JPG)
![3](https://user-images.githubusercontent.com/63136924/78418398-fae6f280-75f8-11ea-92b9-802f151ebba7.JPG)
![4](https://user-images.githubusercontent.com/63136924/78418399-fcb0b600-75f8-11ea-9977-03863a9cbd44.JPG)
![5](https://user-images.githubusercontent.com/63136924/78418400-fe7a7980-75f8-11ea-812e-1fb8becb47ba.JPG)
![6](https://user-images.githubusercontent.com/63136924/78418401-00443d00-75f9-11ea-8fd9-b48c49bf7210.JPG)
![7](https://user-images.githubusercontent.com/63136924/78418402-020e0080-75f9-11ea-85a3-543906793265.JPG)

**Comment by nickbze** [comment]
Update, The Iphone 8 Plus can be Jailbreak with Version 0.9.9.  the step will be following:

First open the Version 0.10.0, continued normally until the iphone went into DFU mode, closed the Checkrain 0.10.0, then lauch the Version 0.9.9, and do the jailbreak.

I just mine done..Thanks

**Comment by Chibibowa** [comment]
> Update, The Iphone 8 Plus can be Jailbreak with Version 0.9.9. the step will be following:
> 
> First open the Version 0.10.0, continued normally until the iphone went into DFU mode, closed the Checkrain 0.10.0, then lauch the Version 0.9.9, and do the jailbreak.
> 
> I just mine done..Thanks

Please help me out, when do you drop the software ? Because after DFU is initiated, checkra1n automatically jailbreaks the device. Or you don't press start and enter DFU either way ? Can you clarify this process to me ? 

I also have this problem on my 8 Plus and I'm glad i'm not the only one.

(You can add me to Discord if you want, Chibibowa#1337) :)

EDIT: Your trick worked !

BTW, here is the original video I made when it didn't work: https://www.youtube.com/watch?v=Wdn0kjgQjBs

**Comment by qaddodi** [comment]
> Update, The Iphone 8 Plus can be Jailbreak with Version 0.9.9. the step will be following:
> 
> First open the Version 0.10.0, continued normally until the iphone went into DFU mode, closed the Checkrain 0.10.0, then lauch the Version 0.9.9, and do the jailbreak.
> 
> I just mine done..Thanks

I cannot find version 0.9.9! Also, if you enter DFU mode on 0.10, and open 0.9.9, it won't "start". Would you just do it through CLI?

**Comment by jotaSe1507** [comment]
> 
> 
> > Update, The Iphone 8 Plus can be Jailbreak with Version 0.9.9. the step will be following:
> > First open the Version 0.10.0, continued normally until the iphone went into DFU mode, closed the Checkrain 0.10.0, then lauch the Version 0.9.9, and do the jailbreak.
> > I just mine done..Thanks
> 
> Please help me out, when do you drop the software ? Because after DFU is initiated, checkra1n automatically jailbreaks the device. Or you don't press start and enter DFU either way ? Can you clarify this process to me ?
> 
> I also have this problem on my 8 Plus and I'm glad i'm not the only one.
> 
> (You can add me to Discord if you want, Chibibowa#1337) :)
> 
> EDIT: Your trick worked !
> 
> BTW, here is the original video I made when it didn't work: https://www.youtube.com/watch?v=Wdn0kjgQjBs

can you help me to do the trick? i added you in discord

**Comment by qaddodi** [comment]
I just jailbroke using 0.9.9
You can download through here: http://www.mediafire.com/file/g53i0vujpvesdce/checkra1n_beta_0.9.9.dmg/file
Download then 
Step 1 - open terminal
Step 2 - cd into the checkra1n directory then into Contents -> MacOS/
Step 3 - ./checkra1n -s -c -e 'serial=3'
Step 4 - connect your device using USB A not USB C
Step 5 - go into DFU mode by volume up -> volume down -> hold side -once black-> hold side+volume down (5s) -> release volume down, keep side (5s) -> voila
Step 6 - wait... it will tell you Error -20 but keeps going
Step 7 - device will boot, and you will have Checkra1n icon on the home screen

Let me know if it works!

**Comment by nickbze** [comment]
I been spend about four days, going thought a lot of videos and try and error, been flashing this iphone 8 plus about 12 Times,  it were jailreak at 13.3.1, and downgrade to 13.2.3, then forgot to charging it untill the battery drain out. After charging, stuck on boot logo and keep restart. Therefor i had to force to update it to 13.4.0, but it keep failed to be jailbreak by checkrain 0.10.0, until i realized the trick for downgrade process, using a lower version of checkrain, i found the checkrain 0.9.9., and voila, it works...

**Comment by RoanneGrech** [comment]
i have the ipad air. It has ios 12.4.5 installed and it is giving me the same error. I tried installing 0.9.9 but nothing

**Comment by minhnh94** [comment]
> I just jailbroke using 0.9.9
> You can download through here: http://www.mediafire.com/file/g53i0vujpvesdce/checkra1n_beta_0.9.9.dmg/file
> Download then
> Step 1 - open terminal
> Step 2 - cd into the checkra1n directory then into Contents -> MacOS/
> Step 3 - ./checkra1n -s -c -e 'serial=3'
> Step 4 - connect your device using USB A not USB C
> Step 5 - go into DFU mode by volume up -> volume down -> hold side -once black-> hold side+volume down (5s) -> release volume down, keep side (5s) -> voila
> Step 6 - wait... it will tell you Error -20 but keeps going
> Step 7 - device will boot, and you will have Checkra1n icon on the home screen
> 
> Let me know if it works!

work without fail thank you !

**Comment by Siguza** [comment]
We managed to track down and fix the bug. Release should happen in the near future.

**Comment by minhnh94** [comment]
13.4.1 rolled out, tried with 0.9.9, sometimes bootloop happened, sometimes jb successfully but wifi not working haptic not working.

**Comment by Siguza** [comment]
Fixed in checkra1n 0.10.1.
