### ISSUE TITLE
Can't receive EXC_SYSCALL exceptions

### ISSUE THREAD

**Issue by jorgschulze73** [checkra1n/BugTracker#1137]
Hello, it's a couple of days that I've been trying to intercept `EXC_SYSCALL` exceptions with no luck: I created an exception handler (the same I use to intercept `EXC_BREAKPOINT` exceptions, for example), set the correct exception masks (`EXC_MASK_SYSCALL | EXC_MASK_MACH_SYSCALL`), and everything as usual, but I never receive any matching mach message. Obligatory pointing out that the same code works for other kinds of exceptions (by changing the masks accordingly).

Is there something I'm missing, or this is simply not how it's supposed to work?

**Comment by Siguza** [comment]
XNU barely supports that. You get `EXC_SYSCALL` only on unimplemented mach traps, and `EXC_MACH_SYSCALL` never.
