### ISSUE TITLE
ipad os 13.4 did soft reset and checkra1n utility is gone but Cydia n apps still there, Cydia is crashing. Pls help

### ISSUE THREAD

**Issue by martinrboats** [checkra1n/BugTracker#1142]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using, and GUI or CLI?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by martinrboats** [comment]
Running ipad os 13.4
checkra1n loader 1.0.1 (1)
Problem is that somethings wrong with my macbook and I'm stuck now. 
Please help

**Comment by nergzd723** [comment]
Rejailbreak it, checkra1n is tethered and will disappear after each reboot.

**Comment by martinrboats** [comment]
> Rejailbreak it, checkra1n is tethered and will disappear after each reboot.

Thanks. Since I don't have access to a laptop now can it be run directly on my phone or ipad?

**Comment by nergzd723** [comment]
> > Rejailbreak it, checkra1n is tethered and will disappear after each reboot.
> 
> Thanks. Since I don't have access to a laptop now can it be run directly on my phone or ipad?

Good question! It is possible to run it on rooted Android device if it supports proper USB host features, and AFAIK it will be possible in future to run checkra1n on iDevices.

**Comment by Siguza** [comment]
Nope, you can't run it on the device itself, since that device needs to be in DFU mode.

On a separate note, running on other jailbroken devices is unlikely to work in the future because the Synopsys OTG 2 controller is really bad in host mode, and has so far proven unable to execute checkm8 properly.

**Comment by martinrboats** [comment]
> > > Rejailbreak it, checkra1n is tethered and will disappear after each reboot.
> 
> > 
> 
> > Thanks. Since I don't have access to a laptop now can it be run directly on my phone or ipad?
> 
> 
> 
> Good question! It is possible to run it on rooted Android device if it supports proper USB host features, and AFAIK it will be possible in future to run checkra1n on iDevices.

Unfortunately I'll to wait for my laptop now 😭. Also one quick question: once I rejailbreak my iPhone n ipad, the tweaks which are already installed n its settings will be intact right?.I won't have to redo anything there?

**Comment by martinrboats** [comment]
Yeh i hope so that we will be able to run it directly on idevices in the future.😊
