### ISSUE TITLE
Asking the devs: What's holding the next checkra1n release?

### ISSUE THREAD

**Issue by UnderEu** [checkra1n/BugTracker#1145]
I wish the developers of this tool answer that, if possible: What's missing or what's holding the release of the next version of checkra1n - the one with 13.4 support, to be specific?

Despite some amount of people who's bricking their devices by using some experimental tool because they cannot wait for a proper release or begging for stupid ETAs, I'm holding up wise and patient for this one 😉

**Comment by Siguza** [comment]
Issue #1135. PongoOS never comes up on a range of devices.

We managed to track down and fix the bug today though, so unless we encounter any fatal flaws during testing, a new release should be out within 24h. Gonna mark this as "unreleased". ;)

**Comment by UnderEu** [comment]
> Issue #1135. PongoOS never comes up on a range of devices.
> 
> We managed to track down and fix the bug today though, so unless we encounter any fatal flaws during testing, a new release should be out within 24h. Gonna mark this as "unreleased". ;)

That's good news!
Keep up with the tests and hope everything goes well, guys :)

**Comment by woachk** [comment]
Release is up. :)
