### ISSUE TITLE
Iphone completely blank Hard Brick. Cannot enter DFU mode or recovery

### ISSUE THREAD

**Issue by anikrish23411599** [checkra1n/BugTracker#1153]
**Tell us about your setup:**
1. What iDevice are you using? Iphone 8
2. On what version of iOS is it? 13.3.1
3. What version of checkra1n are you using? The latest from your website
4. What is your host system (OS version? Hackintosh? VM? etc.)? Mac
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB C 

**What are the steps to reproduce the issue?**
1. COnnect
2. Enter into DFU mode
3.Iphone goes blank 
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**
Cant enable safe mode

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
What do you mean by "blank"? Like all white? The screen should be off in that state...

**Comment by hongsolo9** [comment]
@anikrish23411599 silly question did you connect iphone to iTunes for hard recovery? 4 secs (Power button + Home button), let go of the power button while holding the Home button for 10 secs. If you are connected via USB to iTunes, iTunes will prompt you.

**Comment by nergzd723** [comment]
@anikrish23411599 , AFAIK checkra1n can't modify BootROM in any way, so DFU can't break. In fact, I don't know any tool that can modify BootROM.

If you meant that the screen is black in DFU mode, then it's completely normal, just wait for process to finish.

**Comment by anikrish23411599** [comment]
Hi guys. Sorry for the delay. So I had no DFU mode or download mode. The computer did not recognize my phone. What I did was leave it to discharge over night and plugged it back on the socket with a different USB and then finally signs of life.(The battery was full when I tried to jailbreak) All data intact but right after I did perform a jailbreak which worked perfectly.

**Comment by Siguza** [comment]
Alright, I guess I can only close this as "non-reproducible" then...
