### ISSUE TITLE
iOS 12.4.6 Support

### ISSUE THREAD

**Issue by CanerKaraca23** [checkra1n/BugTracker#1159]
0.10.1 update's "what's news" doesn't says added iOS 12.4.6 support. It's probably working but I don't know. I didn't used 0.10.1 version.

**Comment by tye-mustafa** [comment]
Its not working on ios 12.4.6

**Comment by ntkernel** [comment]
it works on my device. ios 12.4.6 iphone 6(7,2)

**Comment by Siguza** [comment]
The thing with 12.4.x is that it's already inside the range of 12.3-13.x that we support, so it's kinda "nothing new under the sun".  
And I just checked, iOS 12.4.6 already works on the very first release, checkra1n 0.9.

So I suppose I'll close this as "no action needed"?
