### ISSUE TITLE
Stuck on "Checking if device is ready"

### ISSUE THREAD

**Issue by Muirey03** [checkra1n/BugTracker#116]
I am using an iPhone 8 (GSM) and a hackintosh (not a VM).

I manually put the device into DFU mode then start up checkra1n 0.9.1 (tested on 0.9 too). Checkra1n is able to detect the device is in DFU mode, but gets stuck on "Checking if device is ready" after pressing "Start".

Any help is appreciated.

**Comment by FloppiTuna** [comment]
Hmm, are you using the front USB port(s)? I tried on the back ones and it started to work for me.

**Comment by Muirey03** [comment]
Edit: It worked after using a real mac (albeit a very old one) instead of a hackintosh.

**Comment by littlelailo** [comment]
Yeah we don't support hackintoshes
