### ISSUE TITLE
Rebooting the userspace causes the loader app to disappear.

### ISSUE THREAD

**Issue by m1stadev** [checkra1n/BugTracker#1160]
**Tell us about your setup:**
1. iPhone 8 Plus
2. iOS 13.4
3. checkra1n 0.10.1
4. macOS 10.14.6 on a real Mac
5. USB-A cable

**What are the steps to reproduce the issue?**
1. Jailbreak with checkra1n 0.10.1
2. Confirm the loader app is still on the homescreen
3. Reboot the user space

**What do you expect, and what is happening instead?**
I expect the loader app to still be on the homescreen, but it isn’t.

**Does the issue also occur if you enable Safe Mode?**
Yes.

**Any other info, error logs, screenshots, ...?**
A uicache doesn’t make the loader app return, nor does an ldrestart.

**Comment by sbingner** [comment]
Fixed internally - it'll work on the next release

**Comment by Siguza** [comment]
(For tracking purposes, I'd like to keep this open until the fix is actually released.)

**Comment by Siguza** [comment]
Referencing this here (https://github.com/checkra1n/BugTracker/issues/1076#issuecomment-603969156):

> Just tried 0.10.0 and Substrate seems to be working fine after the userspace reboot! The local ssh server stops working, though.

**Comment by opa334** [comment]
As a temporary workaround until the fix is out, running `uicache -a` seems to make it reappear for me

**Comment by Siguza** [comment]
Should be fixed in 0.10.2.

**Comment by cptmedic** [comment]
It appears I am also having this on the latest release on the website
