### ISSUE TITLE
Stuck on Booting

### ISSUE THREAD

**Issue by kaloody99** [checkra1n/BugTracker#1162]
Checkra1n beta 0.10.1 on Linux Ubuntu when jailbreak stuck on booting and rebooting it self and show USBMUX Error 79 My device is iPad Air 2 running iPadOS 13.4.1.

**Comment by jarboer** [comment]
I am having the same issue on the same device on iOS 13.4.1

Yet it worked on my iPhone 6s on iOS 13.3 using the same cable. I was also able to get it to jailbreak once while in save mode

**Comment by kaloody99** [comment]
So still have the same problem

**Comment by samdh90** [comment]
I can also confirm this on my air2 as well. I get stuck with the last line item of:

KPF: Found task_conversion_eval

This is running iOS 13.4.1 on Ubuntu 19.10 as the PC’s HOST. 

Thank you

**Comment by caly8464** [comment]
> I can also confirm this on my air2 as well. I get stuck with the last line item of:
> 
> KPF: Found task_conversion_eval
> 
> This is running iOS 13.4.1 on Ubuntu 19.10 as the PC’s HOST.
> 
> Thank you

The same error on iOS 13.4 on Mac Mojave.

**Comment by nergzd723** [comment]
My air 2 on 13.4.1 works fine. Try using different ports, and search kernel logs for any USB or checkra1n errors.

**Comment by minju25** [comment]
same problem on my ipad mini 4 running 13.4.1

**Comment by Siguza** [comment]
Duplicate of #1168.

**Comment by jferlar** [comment]
Options and unselect 'Dark Blockchain'.
Back ans Start.
Have fun!
