### ISSUE TITLE
Iphone 5s ios 12.4.6

### ISSUE THREAD

**Issue by tye-mustafa** [checkra1n/BugTracker#1165]
**Tell us about your setup:**
1. What iDevice are you using?
Iphone 5S Global
2. On what version of iOS is it?
12.4.6
3. What version of checkra1n are you using?
0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Live Ubuntu 18.04 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple USBA
**What are the steps to reproduce the issue?**
1. Start checkrain
2. Plug device into system
3. Followed the normal procedure 
4. Got stucked into same bug as 12.4.5 ios has on .9 checkrain version. Never goes beyond “real bug setup” screen

**What do you expect, and what is happening instead?**
Should jailbreak, it isnt working

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
![B401505F-FEB4-40D2-8258-E5EB0D399D07](https://user-images.githubusercontent.com/26303106/78853265-e1e6a300-7a37-11ea-87c9-b8ed0c5035ea.jpeg)

**Comment by doct0r3** [comment]
My iPhone 5s with the iOS 12.4.4 also has the same issue.....I have tried the cli and gui on debain 7 and on my android phone with arm64......but fail on checkm8 tigger stage with “DFU sync upload failed and error code-1

**Comment by DSchndr** [comment]
Workaround: Wait some time or run dmesg in a terminal and check if you've got a segfault, then unplug the device and immediatly plug it back in.

Phone turns on, goes into pongoos and does the expected black magic after that.

**Comment by tye-mustafa** [comment]
> Workaround: Wait some time or run dmesg in a terminal and check if you've got a segfault, then unplug the device and immediatly plug it back in.
> 
> 
> 
> Phone turns on, goes into pongoos and does the expected black magic after that.

This isn’t segfault, and after unplug and replugging even in mili sec show me DFUsyncUpload Failed : -1

**Comment by DSchndr** [comment]
Wierd, try ubuntu 19.10
I get DFUsyncUpload Failed after replugging but everything seems to work just fine after that

**Comment by zoomer555** [comment]
Mine displays "checkmate!" after dfusyncupload failed on the cli but still not jailbroken lol

**Comment by doct0r3** [comment]
> Mine displays "checkmate!" after dfusyncupload failed on the cli but still not jailbroken lol

meme too,it said checkmate and after rebooting i can’t see Checkra1n..😂

**Comment by tye-mustafa** [comment]
> Wierd, try ubuntu 19.10
> 
> I get DFUsyncUpload Failed after replugging but everything seems to work just fine after that

i have tried this method on 19.10, The problem still exists.

**Comment by chiragvshroff** [comment]
on the latest checkra1n 5s is working when it says right before trigger you need to unplug and plug your cable on the phone side and it jailbreaks

**Comment by Siguza** [comment]
Marking this as duplicate of #1169.
