### ISSUE TITLE
Bootstrap Error 2 when attempting to install Cydia

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#117]
**What device + iOS version are you on?**
12.4 + iPhone 6

**What checkra1n version are you using?**
0.91 beta

**What are the steps to reproduce the issue?**
1. Open checkra1n app
2. Try to install Cydia
3.
...

**What do you expect, and what is happening instead?**
I expected Cydia to install.

**Any other info, error logs, screenshots, ...?**
https://imgur.com/a/cm5MtDd

**Comment by nullpixel** [comment]
You're already jailbroken with unc0ver or chimera.
