### ISSUE TITLE
checkra1n usbfs error on A7 devices

### ISSUE THREAD

**Issue by nergzd723** [checkra1n/BugTracker#1171]
**Tell us about your setup:**
1. What iDevice are you using?
iPad mini 2
2. On what version of iOS is it?
12.4.3
3. What version of checkra1n are you using?
0.10.1 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu 18.04
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Original USBA to Lightning
**What are the steps to reproduce the issue?**
1. Run the jailbreak
2. See lots of usbfs errors
3. Cry because jailbreak won't be applied except device will be manually reconnected after watchdog fires.
...

**What do you expect, and what is happening instead?**
Get a checkra1n jailbreak, get freeze on Right before trigger

**Does the issue also occur if you enable Safe Mode?**
In fact, even PongoOS doesn't boot, so yes.

**Any other info, error logs, screenshots, ...?**
usbfs: USBDEVFS_CONTROL failed cmd checkra1n rqt 128 rq 6 len 192 ret -110

Lots of these errors in /dev/kmsg

Then kernel watchdog freeze the task because it can't schedule tasks more than 120 seconds.

**Comment by AMDBartek** [comment]
I can confirm that this is an issue in checkra1n 0.10.1.

As @nergzd723 said the jailbreak will succeed after replugging the A7 device when it's frozen on "Right before trigger (this is the real bug setup)".

**Comment by nergzd723** [comment]
duplicate of #1169
