### ISSUE TITLE
iphone 6 gsm hanging on hello screen and home but dosnot work after jaill

### ISSUE THREAD

**Issue by reyadkhalil** [checkra1n/BugTracker#1175]
**Tell us about your setup:**
1. What iDevice are you using? iphone 6 gsm
2. On what version of iOS is it? 12.4.6
3. What version of checkra1n are you using? checkra1n 0.10.1 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)? MacOs 10.12.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? usb charger

**What are the steps to reproduce the issue?**
Step 1:
First, you need to, download the latest checkra1n jailbreak version from the official website.

Step 2:
In step two, you need to download this software, before you do that, we did not develop this iCloud unlock free tool. All the credit goes to the developers of this tool. You can follow these two guys on twitter (@CrazyMind90 & @ajBboCydia) to support them for developing this fantastic software.

Step 3:
Now you need to install the downloaded software named iCloudBypassCA in your macOS. If your system prevents installing it, go to your system preferences and allow it to be installed.

iCloudBypassCA - icloud unlock free tool
Step 4:
After installing iCloudBypassCA on your computer, now you need to install the checkra1n jailbreak on your iCloud locked device, follow the installation step above, or follow the checkra1n jailbreak tutorial if you don’t know how to install it on your device.

Step 5:
When checkra1n is done, open the iCloudBypassCA tool, it’s the one-click tool to bypass activation lock. Thanks to its developers @CrazyMind90 and @AJBboCydia. On this software, you’ll see a button Move iCloud to Trash, press it, and process to iCloud unlock device will start.

iCloudBypassCA - bypass activation lock free tool
When the process is done, check your device it’ll be unlocked through iCloud bypass with checkra1n.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by nergzd723** [comment]
Seems like a bug in iCloudBypassCA, not in checkra1n.

**Comment by crazymind90** [comment]
iCloudBypassCA supports 12.4 - 13.2

**Comment by Siguza** [comment]
iCloud bypass isn't supported.
