### ISSUE TITLE
check_snapshot_error_code: General

### ISSUE THREAD

**Issue by joelnedev** [checkra1n/BugTracker#1177]
**Tell us about your setup:**
1. What iDevice are you using?
iPad Generation 5, wifi only
2. On what version of iOS is it?
ios 13.4 beta
3. What version of checkra1n are you using?
0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
github.com/foxlet/bootra1n
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
lightning to usb 2.0 port
**What are the steps to reproduce the issue?**
1.  Jailbreak
2.  open app
3. click cydia, install
**What do you expect, and what is happening instead?**
I expect it to install Cydia, but it does not

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
If any additional information is required, let me know and I'd be happy to provide it

**Comment by Baker19788** [comment]
I have the same problem on iphone 5s

**Comment by joelnedev** [comment]
I retried last night and it worked fine. Maybe you should keep your phone plugged in while it's getting cydia?
