### ISSUE TITLE
iPhone X stuck on Passcode screen after rejailbreaking

### ISSUE THREAD

**Issue by Gute31** [checkra1n/BugTracker#118]
**What device + iOS version are you on?**
iPhone X iOS 13.2.2

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. after rejailbreaking and booting in jailbreak mode
2. after enter the passcode
3. the iPhone stuck on the passcode screen
4. in normal mode i have no issue
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by woachk** [comment]
Did you install tweaks?

**Comment by Gute31** [comment]
yes but no lockscreen tweak

**Comment by littlelailo** [comment]
I believe this is an issue with a tweak which doesn't expect a locked device and because of that the springboard is hanging (I assume it wants to open a file that's encrypted with the user passcode).

**Comment by Gute31** [comment]
what can i do now? i have try to boot in safe mode but it don't work.

**Comment by littlelailo** [comment]
Either disable substrate over ssh or wait till we have a build that lets you enter safe mode with the volume buttons

**Comment by bermudalocket** [comment]
Having the same issue. It hangs after I enter the last digit and eventually resprings. Tried booting into safe mode by killing SpringBoard (which worked) but had the same result.

EDIT: fixed after forcing a hard crash (`killall -15 SpringBoard`) and letting data recovery run. Could just be a coincidence. YMMV. Wouldn't suggest anyone do this if you don't know how to pull yourself back if shit goes south.

**Comment by Gute31** [comment]
Yeah exactly the same issue, after entering the last digit it stuck.

How have you do the „hard crash“?

**Comment by littlelailo** [comment]
Connect via iproxy and ssh into the device then run killall -15 SpringBoard (this just describes how you do the "hard crash" idk if it resolves the issue for you)

**Comment by Gute31** [comment]
sorry i don't now how to do this, its not my mac, i just borow for jailbreak

**Comment by Gute31** [comment]
Ok with the 0.9.2 update the issue is resolved. Thanks

**Comment by littlelailo** [comment]
Ok then I'll close this now
