### ISSUE TITLE
iPad Mini 4 iOS 13.4.1 -20 Error

### ISSUE THREAD

**Issue by blueberrywaffie** [checkra1n/BugTracker#1180]
**Tell us about your setup:**

1. What iDevice are you using?
iPad Mini 4

2. On what version of iOS is it?
iOS 13.4.1

3. What version of checkra1n are you using?
beta 0.10.1

4. What is your host system (OS version? Hackintosh? VM? etc.)?
macOS Catalina 10.15.1 (19B88)

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-C dongle to lighting cable, however tried a few runs using a 2015 MacBook to have just a lightning cable between the mac and iPad but got the exact same result

USB-C Dongle being used
bestbuy.com/site/apple-usb-type-c-digital-av-multiport-adapter-white/5596800.p?skuId=5596800&ref=212&loc=1&ref=212&loc=1&gclid=CjwKCAjwssD0BRBIEiwA-JP5rBUfmBik_ltAA08D5Vj_4d9fTSxPA5B-aArBLeUapBpb5USyrdTPURoCZrAQAvD_BwE&gclsrc=aw.ds

**What are the steps to reproduce the issue?**
1. Connect iPad
2. Follow on screen instructions (enter recovery mode, enter DFU mode, begin jailbreaking)
3. Wait, around 10-15 seconds later and see the -20 error on Mac
...

**What do you expect, and what is happening instead?**
Successful jailbreak

Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
When running this, my iPad does get to the boot screen, and has checkrain text printed to the screen. It gets to the part where "KPF: Found task_conversion_eval"  is printed to the screen 4 times, it hangs there for a while, then the error shows up on my mac. Waiting a few moments longer, a lot of text is printed out to the screen, it goes by quickly so I cant read it, then the iPad reboots to stock.

I did have one run that seemed to indicate success at first. It printed "KPF: Found task_conversion_eval"  four times, hung, got the -20 error on mac, then back on the iPad it printed out the usual before finally printing out "Booting..." (this to me looked like what it prints on my iPhone when successful and was significantly less text than the runs mentioned above), then the iPad rebooted to stock.

Also side note, I bought this iPad used, and as far as I know it as never been jailbroken. I have restored it to iOS 13.4.1 using my Mac before I ever tried to use checkrain on it.

Will update this with any screen shots I can get if anyone would like.

**Comment by blueberrywaffie** [comment]
Wanting to update this for anyone having a similar issue, just found beta 0.10.0 on reddit, this post, downloaded and ran normally, worked first try.

https://www.reddit.com/r/checkra1n/comments/fr9ndt/checkra1n_0100_ios_134/

**Comment by d4d0z7** [comment]
> Wanting to update anyone having a similar issue, just found beta 0.10.0 on reddit, this post, downloaded and ran normally, worked first try.
> 
> https://www.reddit.com/r/checkra1n/comments/fr9ndt/checkra1n_0100_ios_134/

And that's for iPadOS 13.4.1 or iPadOS 13.4 cause checkra1n 0.10.0 is not supported for iPadOS 13.4.1?! 
![Screenshot 2020-04-10 at 16 35 54](https://user-images.githubusercontent.com/48334223/78998728-80165e00-7b49-11ea-8653-a181f585790b.png)

**Comment by blueberrywaffie** [comment]
> > Wanting to update anyone having a similar issue, just found beta 0.10.0 on reddit, this post, downloaded and ran normally, worked first try.
> > https://www.reddit.com/r/checkra1n/comments/fr9ndt/checkra1n_0100_ios_134/
> 
> And that's for iPadOS 13.4.1 or iPadOS 13.4 cause checkra1n 0.10.0 is not supported for iPadOS 13.4.1?!
> ![Screenshot 2020-04-10 at 16 35 54](https://user-images.githubusercontent.com/48334223/78998728-80165e00-7b49-11ea-8653-a181f585790b.png)

Go into "Options" and check the "Allow untested iOS/iPadOS/tvOS versions" option, then it will let you

**Comment by Siguza** [comment]
Marking as dupe of #1168.
