### ISSUE TITLE
No handler for keyserver scheme 'https' error

### ISSUE THREAD

**Issue by jeremiahspy** [checkra1n/BugTracker#1181]
**Tell us about your setup:**
1. What iDevice are you using? Iphone5s
2. On what version of iOS is it? 12.4.5
3. What version of checkra1n are you using? The Latest 0.10.1 beta 
4. What is your host system (OS version? Hackintosh? VM? etc.)? Dell intel laptop/xubuntu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple usb lighting cable

**What are the steps to reproduce the issue?**
1. Add the checkra1n repo. Add our APT repo: echo "deb https://assets.checkra.in/debian /" | sudo tee -a /etc/apt/sources.list
2. The next line of code. sudo apt-key adv --fetch-keys https://assets.checkra.in/debian/archive.key
3. Then I get this error right after that:
Executing: /tmp/tmp.knothajitV/gpg.1.sh --fetch-keys
https://assets.checkra.in/debian/archive.key
gpgkeys: protocol `https' not supported
gpg: no handler for keyserver scheme `https'
gpg: WARNING: unable to fetch URI https://assets.checkra.in/debian/archive.key: keyserver error

**What do you expect, and what is happening instead?**
The problem might be this version of linux as Xubuntu, that is fully updated just does not work with checkra1n's repo. Is there  more tested version of linux that's known to work? 

**Does the issue also occur if you enable Safe Mode?**
I did not try it in safe mode but I did restart my computer a lot. I will try it on safe mode next if I can/and it works I will try to update this post.

**Any other info, error logs, screenshots, ...?**
well I am a bit confused on what line of code works to start the checkra1n app, if I can get the repo to install. In the past I have used. 1. cd Desktop 2. chmod +x checkra1n 3. sudo ./checkra1n
these 3 steps work great for me but this start up code has change a few times and now does not seem to work with the usb method i also have

**Comment by nergzd723** [comment]
Install gnupg-curl and the issue will be resolved. And what's your X/Ubuntu version? If it's 16.xx, then it does come with GPG that doesn't support https.

**Comment by ch0chi** [comment]
I had the same issue when attempting to add the key. However, it appeared to be an issue with my DNS. I had set my DNS to:
```
nameserver 127.0.0.1
nameserver 1.1.1.1
```
I was able to fix the issue by temporarily removing the 127.0.0.1 entry and restarting the network.
