### ISSUE TITLE
IPAD AIR 2- iPadOS 13.4.1  ERROR  -71 , -79

### ISSUE THREAD

**Issue by jorevi25** [checkra1n/BugTracker#1182]
**Tell us about your setup:**
1. What iDevice are you using?
IPAD AIR 2(WIFI)

2. On what version of iOS is it?
iPadOS 13.4.1

3. What version of checkra1n are you using?
checkra1n 0.10.1 beta

4. What is your host system (OS version? Hackintosh? VM? etc.)?
IPAD (iPadOS 13.4.1)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? 
ORIGINAL APPLE USB 

**Does the issue also occur if you enable Safe Mode?**
YES

**Any other info, error logs, screenshots, ...?**

![TT](https://user-images.githubusercontent.com/54463833/78970708-f5e1e180-7ad7-11ea-8f97-034f11feb9f6.png)
![UU](https://user-images.githubusercontent.com/54463833/78970717-fb3f2c00-7ad7-11ea-8c61-5f9b0d74e029.png)

**Comment by nergzd723** [comment]
See #1168

**Comment by jorevi25** [comment]
> 
> 
> See #1168

Thank you  very  much,  problem  fixed  using  Checkra1n .10.0

**Comment by Siguza** [comment]
Marking as duplicate.
