### ISSUE TITLE
Haptic button issues fix 

### ISSUE THREAD

**Issue by over40fb** [checkra1n/BugTracker#1183]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 7 
2. On what version of iOS is it?
13.3 
3. What version of checkra1n are you using?
0.98
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C?  Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

Look at the picture. I have disabled the Cercube with ICleaner: 

![4439E5FA-C299-4E63-9623-598B8C43AC33](https://user-images.githubusercontent.com/57912093/78979811-e5a02580-7b1c-11ea-87b5-a9cfc8d58e99.jpeg)

**Comment by Dimensiz** [comment]
I disable it and it works 100% without affect Cercube functions, I have and iPhone 7 with iOS 13.4 

**Comment by Siguza** [comment]
Alright, thanks for the info, I guess?
