### ISSUE TITLE
Stuck at Initializing AIC2

### ISSUE THREAD

**Issue by Engylizium** [checkra1n/BugTracker#1184]
1. iPhone 8
2. 13.3
3. 0.9.8.2
4. mac os Catalina 10.15.3
5. Original Apple USB-A - Lightning cable

Can't say if it can be reproduced, but this is how I got stuck:
1. Phone turned off because of empty battery
2. Charged to about 20%
3. Decided to Checkra1n it
4. Everything was as always until Checkra1n logo appearance and that's where I stuck

**What do you expect, and what is happening instead?**
Usual jailbreaking process. Got non responsive phone

**Does the issue also occur if you enable Safe Mode?**
Don't know, my phone is just froze, now I'm waiting for it to turn off by itself

**Any other info, error logs, screenshots, ...?**
Checkra1n app gave me -20 error and then stuck too
![photo_2020-04-10 12 34 31](https://user-images.githubusercontent.com/22287855/78981815-70871d00-7b29-11ea-8cf5-0316905d9991.jpeg)

**Comment by Engylizium** [comment]
Rebooted phone successfully with (Volume Up, Volume Up, Side Button) - I forgot about this method
So, I installed new version of Checkra1n an jailbroke my device without any troubles now
This was strange issue tho

**Comment by Siguza** [comment]
Well if 0.10.1 works, I'm just gonna mark this as fixed...
