### ISSUE TITLE
Checkra1n 0.10.1 not working on iPad devices

### ISSUE THREAD

**Issue by andreprawira** [checkra1n/BugTracker#1186]
**Tell us about your setup:**
1. iPad mini 4
2. iOS 13.4 & 13.4.1
3. 0.10.1
4. latest Ubuntu, bootra1n, checkn1x
5. Connected my device with 3 different certified apple cables

**What are the steps to reproduce the issue?**
1. Boot up checkn1x, bootra1n, plain latest Ubuntu and downloaded checkra1n manually
2. Connect the device
3. Tick and untick all the boxes in the option
4. Enter DFU mode, and the result is always "**usbmux error error code -79**"
5. Put device straight from OS to DFU mode then execute sudo ./checkra1n -c -v -V -s right on terminal same error
...

**What do you expect, and what is happening instead?**
Expecting jailbreak done succesfully, instead i got usbmux error

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
I have created a [thread](https://www.reddit.com/r/checkra1n/comments/fy0jyi/helpusbmux_error_error_code_79/) on checkra1n subreddit, turns out people with iPad regardless its mini or air are experiencing the exact same problem. Also the iPad that I have is fresh restored (no medias/settings in it)

**Comment by d4d0z7** [comment]
I can confirm that. 

Waiting for an update (hopefully).

**Comment by ImpetuousRacer** [comment]
Same issue here on same device and OS versions.

**Comment by nergzd723** [comment]
See #1168

**Comment by jtash** [comment]
Similar problem with iPad Air 2, gives error -20 with and without safe mode

**Comment by Siguza** [comment]
Marking as dupe of #1168.
