### ISSUE TITLE
Checkra1n 0.10.1 not working on iPad Mini (Global)

### ISSUE THREAD

**Issue by rkswatian** [checkra1n/BugTracker#1187]
**Tell us about your setup:**
1. Ipad Mini (Global)
2. 9.3.5
3. Checkra1n 0.10.1 & others
4. Latest Kali Linux bootra1n,  checkn1x
5. Connected my device with 3 different certified apple cables

**What are the steps to reproduce the issue?**
1. Boot up checkn1x, bootra1n, plain latest Kali Linux and downloaded checkra1n manually
2. Connect the device
3. error ( Device not supported ) 
...

**What do you expect, and what is happening instead?**
Expecting Support Ipad Mini (Global) Devices

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by nergzd723** [comment]
iPad mini 1 is not supported by checkra1n because of old iOS version. And 32bitness too.

**Comment by rkswatian** [comment]
iPad mini 1 is not supported by checkra1n because of old iOS version. And 32bitness too.

there is any chance for support ( Ipad Mini ( Global ) IOS 9.3.5???

**Comment by nergzd723** [comment]
> iPad mini 1 is not supported by checkra1n because of old iOS version. And 32bitness too.
> 
> there is any chance for support ( Ipad Mini ( Global ) IOS 9.3.5???

Nope, devs aren't supporting old rusty stuff. You have other jailbreak solutions on 9.3.5, don't you?

**Comment by rkswatian** [comment]
> > iPad mini 1 is not supported by checkra1n because of old iOS version. And 32bitness too.
> > there is any chance for support ( Ipad Mini ( Global ) IOS 9.3.5???
> 
> Nope, devs aren't supporting old rusty stuff. You have other jailbreak solutions on 9.3.5, don't you?

actually i bought this Ipad in 2014 as a 2nd hand device and after some months of using i decide to update it to new ios.. when i update it ... its locked with icloud, since than i tried so many ways to unlock it but i never succeed .. i thought Checkra1n will be my last option but isn't.. 
its still icloud locked.. and i dont know what to do or how unlock it.. anyway thank you soo much for your reply and time.. take care

**Comment by Siguza** [comment]
See #1, we won't support 32bit devices.
