### ISSUE TITLE
Checkra1n not working on any iPad Mini 4 with 13.4 or 13.4.1

### ISSUE THREAD

**Issue by ImpetuousRacer** [checkra1n/BugTracker#1188]
**Tell us about your setup:**
1. What iDevice are you using? 
iPad Mini 4 Cellular (have 2)

2. On what version of iOS is it? 
13.4 or 13.4.1

3. What version of checkra1n are you using? 
0.10.1

4. What is your host system (OS version? Hackintosh? VM? etc.)?
Tried using bootra1n, checkn1x, rainb0x using arm64, and Linux Mint 19.3

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Tried using OEM Apple cable and also Anker Powerline 3 USB-A cable directly connected to computer.

**What are the steps to reproduce the issue?**
1.  When trying to jailbreak, always receive "USBMUX error (Error code: -79)" at end.
2.  Appears people with Mac receive error -20 on this particular device.
3.
...

**What do you expect, and what is happening instead?**
Expect jailbreak process to not give error and see checkra1n app on iPad

**Does the issue also occur if you enable Safe Mode?**
Tried safe mode, verbose mode, verbose mode + unsupported version, verbose + safe mode

**Any other info, error logs, screenshots, ...?**
Process starts then seems to hang at the fourth instance of "KPF: Found task_conversion_eval", then after about 40 seconds, it scrolls through rest of process, reboots, then gives error.

Did a complete clean restore to 13.4 and also 13.4.1 still same error on each.
Also tried putting device into DFU and putting device straight from OS to DFU mode then execute sudo ./checkra1n -c -v -V -s right on terminal same error.

Verified cable and setup works 
-checkra1n 0.10.1 works correctly on iPad Mini 4 on 13.3.1
-checkra1n working perfectly on iPhone 6S Plus on 13.4.1

It appears this is effecting iPad Mini 4 and iPad Air 2 - believing this may be A8/A8X specific?

**Comment by d4d0z7** [comment]
Great, apparently we have to wait for the next update or pre release. ☺️

**Comment by chelo801** [comment]
hola el problema con el ipad mini 4 era el cable??? me pasa lo mismo y
tambien me tira error 77 y 79

**Comment by ImpetuousRacer** [comment]
> hola el problema con el ipad mini 4 era el cable??? me pasa lo mismo y
> tambien me tira error 77 y 79

No es el cable. Es el jailbreak en sí mismo el que causa el problema.

**Comment by chelo801** [comment]
cual seria la solucion, sabes si soporte la Ipad A1822 àra hacer el checkra1n??

**Comment by ImpetuousRacer** [comment]
> cual seria la solucion, sabes si soporte la Ipad A1822 àra hacer el checkra1n??

Se supone que es compatible pero no funciona. Por lo tanto, por qué estamos publicando el error aquí. Pinche Cabron.

**Comment by chelo801** [comment]
usted todavia no pudo solucionar?

**Comment by ImpetuousRacer** [comment]
> usted todavia no pudo solucionar?

no

**Comment by chelo801** [comment]
anoche probe en un mini 4 y tampoco pude hacerla andar, es lo unico hasta ahora que me hace renegar

**Comment by ImpetuousRacer** [comment]
> anoche probe en un mini 4 y tampoco pude hacerla andar, es lo unico hasta ahora que me hace renegar

Tenemos que esperar a que los desarrolladores actualicen el jailbreak para solucionar el problema. No hay otra manera en este momento.

**Comment by nergzd723** [comment]
Seems like a common issue on A8 devices on iOS 13.4.x, see #1168

**Comment by blueberrywaffie** [comment]
I was having the -20 issue for my iPad Mini 4, I downloaded beta 0.10.0, checked the Allow untested ios versions check in options, and it worked first try no issues

I found beta 0.10.0 here
https://www.reddit.com/r/checkra1n/comments/fr9ndt/checkra1n_0100_ios_134/

**Comment by Siguza** [comment]
Marking as duplicate of #1168.

**Comment by hold20100** [comment]
testeado que no funciona el jailbreak en ipad mini 4 con ios 13.4 me pasa igual y he hecho varios dispositivos y salen a la primera pero en el ipad mini 4 no
