### ISSUE TITLE
iPad air 2 error -20

### ISSUE THREAD

**Issue by taha-16** [checkra1n/BugTracker#1192]
**Tell us about your setup:**
1. What iDevice are you using? iPad Air 2
2. On what version of iOS is it?13.4.1
3. What version of checkra1n are you using?0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?Mac OS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?USB-A

**What are the steps to reproduce the issue?**
1. open checkra1n
2. start jailbreak process 
3.Timed out waiting bootstrap upload
...

**What do you expect, and what is happening instead?**
expecting 100% jailbroken
what is happening : i get this (Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)

**Does the issue also occur if you enable Safe Mode?**
the iPad recently restored

**Any other info, error logs, screenshots, ...?**
![Screen Shot 2020-04-11 at 6 00 19 AM](https://user-images.githubusercontent.com/63487973/79035827-f8b50300-7bb9-11ea-8dc1-bcdb484e8e72.png)

**Comment by steliosaa** [comment]
Duplicate:
Check here for answers
https://github.com/checkra1n/BugTracker/issues/1168
