### ISSUE TITLE
A7 Device, Right before Triggered, 0.10.1

### ISSUE THREAD

**Issue by zurabi97** [checkra1n/BugTracker#1195]
**Tell us about your setup:**
1. What iDevice are you using?
iPad Mini 3.
2. On what version of iOS is it?
iOS 12.4.6
3. What version of checkra1n are you using?
Linux version 0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu 18.04.4 LTS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple lightning cable (original), connected directly to pc usb port.

**What are the steps to reproduce the issue?**
1. Opening Terminal
2. Typing sudo checkra1n
3. Following on screen instructions.
4. Stuck on "Right Before Triggered"
...

**What do you expect, and what is happening instead?**
Expecting to successfully jailbreak the device, but nothing happens.

**Does the issue also occur if you enable Safe Mode?**
Yes.

**Any other info, error logs, screenshots, ...?**

Kernel: [370112177] INFO: task checkrain:998 blocked for more than 122 seconds

Also tried Bootra1n, has the same issues

**Comment by nergzd723** [comment]
See #1169

**Comment by zurabi97** [comment]
> See #1169 

Thank you, that's worked!
