### ISSUE TITLE
Reboot device and disappear checkra1n

### ISSUE THREAD

**Issue by RodrigoCobo** [checkra1n/BugTracker#120]
**What device + iOS version are you on?**
iPhone 6s iOS 13.2

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. Install according to program tutorial
2. Open checkra1n app and install Cydia
3. Reboot the device manually 
4. checkra1n app disappears and Cydia doesn’t open.

**Comment by littlelailo** [comment]
This is a semi-tether jailbreak, which means that after you rebooted you need to jailbreak again using your pc
