### ISSUE TITLE
iPad 3 simcard jeilbreak problem

### ISSUE THREAD

**Issue by megagokhan** [checkra1n/BugTracker#1200]
![IMG20200410194607](https://user-images.githubusercontent.com/63543311/79068031-7701ca00-7ccc-11ea-8a15-222f37165dfc.jpg) 4
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by comical-cookie** [comment]
Your ipad and ios version are not compatible and likely never will be, there are other jailbreak options available to you though

**Comment by nergzd723** [comment]
32 bit will never be supported. You have Phoenix for 9.3.5 and 9.3.6

**Comment by megagokhan** [comment]
I don't know the username and password.
