### ISSUE TITLE
iPad Air 2：Error Report - Request for Permission

### ISSUE THREAD

**Issue by nenhall** [checkra1n/BugTracker#1201]
**Tell us about your setup:**
1. What iDevice are you using?
iPad Air 2 (Cellular) 

2. On what version of iOS is it?
iPadOS 13.4.1

3. What version of checkra1n are you using?
checkra1n 0.10.1 beta

4. What is your host system (OS version? Hackintosh? VM? etc.)?
macOS 10.15.4

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-C

**What are the steps to reproduce the issue?**
1. checkra1n click options: selected(safe model 、Verbose boot  and dark Blockchain)
2. success enter recovery model and DFU model
3. click start： Booting...
4. failed: Error Report - Request for Permission
...

**What do you expect, and what is happening instead?**
i want success jailbreak,but is failed,
failed detail:
`Error Report - Request for Permission
Unfortunately, an error has occured during installation of the jailbreak. With your permission, the error can be sent back to us so we can investigate this further. we only send the error code and the device's CPU type. No trackable or other personal information will be sent. Click Yes to send it or No to ignore it.`

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
<img width="584" alt="WeChat1058a32a138a0277f80e41afc6b1a94b" src="https://user-images.githubusercontent.com/19990465/79070896-15ad1b80-7d0b-11ea-87a5-eaa86000b4a9.png">
![IMG_1757](https://user-images.githubusercontent.com/19990465/79070905-23fb3780-7d0b-11ea-85ad-38d3217ecbf3.JPG)

**Comment by tecnomur** [comment]
For me too. Exactly the same.

**Comment by nergzd723** [comment]
See #1168
