### ISSUE TITLE
Stuck in this is real bug setup stage

### ISSUE THREAD

**Issue by V3R1XT0** [checkra1n/BugTracker#1203]
**Tell us about your setup:**
1. What iDevice are you using? Ipad air a1474
2. On what version of iOS is it? 12.4.6
3. What version of checkra1n are you using? 0.10.1
4. What is your host system (OS version?  Hackintosh? VM? etc.)? Linux 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Original apple lightning cabt

**What are the steps to reproduce the issue?**
1. Stuck in this is real bug setup
2. 
3.
...

**What do you expect, and what is happening instead?**
   #Fixing that (according your site This version Will fix the a7 issue but i think that not fixed..plz fixed that)
**Does the issue also occur if you enable Safe Mode?**

Yes

**Any other info, error logs, screenshots, ...?**
![FE3DC82E-1C9B-4CEF-95A8-E530FCFF1DDC](https://user-images.githubusercontent.com/31089183/79075820-b4894600-7d12-11ea-9e1c-5ca7552768f2.jpeg)
![Uploading EFCB5DBC-69D7-4146-BF50-54ABADD33C47.jpeg…]()

**Comment by nergzd723** [comment]
see #1169
