### ISSUE TITLE
Error 79

### ISSUE THREAD

**Issue by QasimQ23** [checkra1n/BugTracker#1204]
**Tell us about your setup:**
1. What iDevice are you using? iPad mini 4
2. On what version of iOS is it?13.4.1
3. What version of checkra1n are you using?0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? Ubuntu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Tried apple and third party cable

**What are the steps to reproduce the issue?**
1. Device says booting for a while then always error 79 usbmx
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**yes

**Any other info, error logs, screenshots, ...?**

**Comment by drkhalid** [comment]
Use MX Linux instead of Ubuntu, 
and install from the repo do not download it, 
and tick the first box in the options.

**Comment by nergzd723** [comment]
Known issue on 13.4.1, see #1168
