### ISSUE TITLE
Sorry, iPhone 11 (iOS 13.4.1) is not supported. ECID: 0x12504a217a802e

### ISSUE THREAD

**Issue by teshome2** [checkra1n/BugTracker#1206]
**Tell us about your setup:**
1. What iDevice are you using?iphone 11
2. On what version of iOS is it?13.4.1
3. What version of checkra1n are you using?newest
4. What is your host system (OS version? Hackintosh? VM? etc.)?os
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?USB

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

that the download is not supported for my iphone ios 13.4.1 eventhough it's supposed too?
**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
See #1. A12 and up are not vulnerable.

**Comment by teshome2** [comment]
Wtf are u saying

**Comment by Siguza** [comment]
I'm saying the thing that powers this jailbreak does not exist on your phone, so it cannot be supported.

**Comment by teshome2** [comment]
ok thanks
