### ISSUE TITLE
Error Code -77 with bootra1n 0.10.1 on iOS 13.4.1 with iPhone X

### ISSUE THREAD

**Issue by tinoposts** [checkra1n/BugTracker#1214]
Help, it says “maybe run as root?” and I’m using bootra1n because I having Windows. I tried using a different cable but it didn’t work.

**Comment by tinoposts** [comment]
Okay now I reran bootra1n, now it says error -77. Is it the cable I’m using?

**Comment by demhademha** [comment]
We need to know what iOS version and bootra1n version your using

**Comment by tinoposts** [comment]
My bad, I’m using iOS 13.4.1 and the bootra1n version is 0.10.1

**Comment by demhademha** [comment]
Try changing ports

**Comment by tinoposts** [comment]
Never mind, got it working. Somehow my either resetting Location and Privacy or disabling my password got it working.
