### ISSUE TITLE
Bootlooping after restarting and rejailbreaking

### ISSUE THREAD

**Issue by mrichardist** [checkra1n/BugTracker#122]
**What device + iOS version are you on?**
iPhone X on iOS 13.1.2

**What checkra1n version are you using?**
Beta 0.9
**What are the steps to reproduce the issue?**
1. Restart device
2. Place device into dfu mode 
3. Jailbreak with checkra1n
...

**What do you expect, and what is happening instead?**
The device to not bootloop while jailbreaking but it has bootlooped anyway

**Any other info, error logs, screenshots, ...?**
The device only bootloops when trying to jailbreak. On stock iOS it starts up completely fine without any issues. I suspect it could be a tweak incompatibility, if so how would I be able to remove tweaks as I can't access the device when it's in a jailbroken state.

**Comment by littlelailo** [comment]
What do you mean with bootlooping. Is it just black or is it constantly restarting?

**Comment by mrichardist** [comment]
Constantly restarting about 5 times and then it'll go back into stock ios

**Comment by n3oney** [comment]
@mrichardist try [this](https://www.reddit.com/r/jailbreak/comments/ducjw9/tutorial_how_to_enter_safe_mode_and_remove_bad/) out.

**Comment by mrichardist** [comment]
OOo thanks so much, will give it a try

**Comment by mrichardist** [comment]
Thanks for the help everyone, I really appreciate it. Enjoy the rest of your day :)

**Comment by JustTriinn** [comment]
thx, this worked
