### ISSUE TITLE
Checkra1n icon appears late

### ISSUE THREAD

**Issue by tye-mustafa** [checkra1n/BugTracker#1221]
**Tell us about your setup:**
1. What iDevice are you using?
**Iphone 5s**
2. On what version of iOS is it?
**12.4.6**
3. What version of checkra1n are you using?
**0.10.1**
4. What is your host system (OS version? Hackintosh? VM? etc.)?
**Checkn1x 1.0.4 USB live** https://asineth.gq/checkn1x
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
**Apple Usb-A**
**What are the steps to reproduce the issue?**
-  Jailbreak through checkn1x
-  After starting the phone upon successful jailbreak, the icon of  checkrain appears 2 mint late when the phones starts

...

**What do you expect, and what is happening instead?**
The icon of checkrain should appear right after jailbreak or at least a loading app icon should appear,
Problem causes the user to think the jailbreak isn’t successful.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Not tested

**Any other info, error logs, screenshots, ...?**
Nope. Tested this thing 4 times, same delay always.

**Comment by chiragvshroff** [comment]
bruhh have some patience

**Comment by PanhaSom** [comment]
Good

**Comment by Siguza** [comment]
Should be fixed in 0.10.2.
