### ISSUE TITLE
Cydia is not stable

### ISSUE THREAD

**Issue by NguyenDanh** [checkra1n/BugTracker#1224]
I installed the checkrain ver 0.10.1 and cydia ver 1.1.32 b23. The problem is this cydia version is not stable and I can't install any tweak. Every time I try to install tweak, the cydia will break out to the main screen. 
So, I hope the dev team help me and the community downgrade cydia version to 1.1.25 because this is the most stable version. 
Thanks.

**Comment by mamakok** [comment]
> I installed the checkrain ver 0.10.1 and cydia ver 1.1.32 b23. The problem is this cydia version is not stable and I can't install any tweak. Every time I try to install tweak, the cydia will break out to the main screen.
> So, I hope the dev team help me and the community downgrade cydia version to 1.1.25 because this is the most stable version.
> Thanks.

**Comment by Siguza** [comment]
Do you get any crash logs? If so, could you share them?

**Comment by NguyenDanh** [comment]
@Siguza  no, I can't install any tweak so I can not get the crash log. 
But after resetting my device and re-jb with checkrain, everything is ok now. You can close the Q&A.
Thanks.
