### ISSUE TITLE
iPad Air 2 (Cellular) IOS 13.4

### ISSUE THREAD

**Issue by suleysheikh42** [checkra1n/BugTracker#1226]
Hi,

Checkra1n does not work for iPad Air 2 (Cellular) iOS 13.4 its always says error 20

![Bildschirmfoto 2020-04-16 um 10 45 34](https://user-images.githubusercontent.com/63780110/79435182-a0be3800-7fcf-11ea-97c4-260861189188.png)
![Bildschirmfoto 2020-04-16 um 10 45 45](https://user-images.githubusercontent.com/63780110/79435220-aae03680-7fcf-11ea-9544-03fcea36af78.png)

**Comment by Upgrade1871** [comment]
Have this issue as well, on cellular and wifi iPad air 2

**Comment by Siguza** [comment]
Duplicate of #1168.
