### ISSUE TITLE
Checkra1n and Cydia crash

### ISSUE THREAD

**Issue by tfb1997** [checkra1n/BugTracker#1236]
**Tell us about your setup:**
1. Iphone 7
2. Ios 13.4
3. 0.10.0
4. MacOS 10.11.6 and Windows 10
5. USB A Cable

**What are the steps to reproduce the issue?**
1. instal Checkra1n 
2. Instal Jailbreak
3.Instal Cydia
4. restart Iphone

And now the problem that nothing works. The Checkra1n App is not anymore on the device and Cyda crash. No installed things from Cydia Works anymore.
After rejailbreaking it works but after restart is the same problem.
Can you help me ?

**Comment by bineinkevin** [comment]
When you restart your phone then it’s normal that your Jailbreak isn’t working anymore until you rejailbreak. That’s how checkra1n is

**Comment by jagboy88** [comment]
> When you restart your phone then it’s normal that your Jailbreak isn’t working anymore until you rejailbreak. That’s how checkra1n is

Yea that's all jailbreaks lol

**Comment by Siguza** [comment]
That's how a tethered jailbreak works.
