### ISSUE TITLE
Can't get into DFU mode to re-enabble jailbreak

### ISSUE THREAD

**Issue by brwajumaa** [checkra1n/BugTracker#1237]
**Tell us about your setup:**
1. What iDevice are you using?
5s
2. On what version of iOS is it?
12.4.6
3. What version of checkra1n are you using?
0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu-20.04
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A

after i get success jailbreak i reboot my device and now i can't get into DFU mode it was reboot and get back to recovery mode.

**Comment by 141** [comment]
Did you try a hard reboot first?

**Comment by brwajumaa** [comment]
> Did you try a hard reboot first?

i don't know what is hard reboot but if you mean Power button + Home button? yes many times

**Comment by 141** [comment]
Hold both of the buttons until you see the apple logo, then release. If that doesn't work, did you completely power off the device?

**Comment by brwajumaa** [comment]
> Hold both of the buttons until you see the apple logo, then release. If that doesn't work, did you completely power off the device?

yes i did it both, even i restore my device and **same issue**

**Comment by Siguza** [comment]
If you're unable to enter DFU mode, then we can't help you.
