### ISSUE TITLE
Randomly restart

### ISSUE THREAD

**Issue by ShadyWhite** [checkra1n/BugTracker#1238]
**Tell us about your setup:**
1. What iDevice are you using? iPhone X
2. On what version of iOS is it? 13.4.1
3. What version of checkra1n are you using? 0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? Linux（checkn1x）
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A

**What are the steps to reproduce the issue?**
It is Randomly when I unlock my phone，bioprotect pops up to restart with face ID correction.

**What do you expect, and what is happening instead?**
Expecting fix.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Currently no.

**Any other info, error logs, screenshots, ...?**
No,sorry.

**Comment by Siguza** [comment]
What do you mean by "restart with face ID correction"?
