### ISSUE TITLE
i can't install the loader after downgrade from 13.4.1 to 13.2.3 

### ISSUE THREAD

**Issue by el3wdy** [checkra1n/BugTracker#1239]
**Tell us about your setup:**
**1. What iDevice are you using?**
iPad Pro (10.5-inch, Cellular)
2. On what version of iOS is it?
13.2.3
3. What version of checkra1n are you using?
0.10.1

**4. What is your host system (OS version? Hackintosh? VM? etc.)?**
both [VM - Windows 10]
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple
**What are the steps to reproduce the issue?**
1. restore 13.4.1 then i jailbreak it.
2. install apps manager - file manager - succession
3.i downgrade the ipad to 13.2.3.
4. i jailbreak again by checkra1n 0.10.1 cos i can't boot my ipad with other versions.
5. i got this message even i don't have any downloaded updates & i blocked by ‎DNSCloak.

**What do you expect, and what is happening instead?**
i expect to can make jailbreak and install cydia but i got the error message.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**
No

**Comment by demhademha** [comment]
vms  don’t tend to work, try using a different host os

**Comment by el3wdy** [comment]
> vms  don’t tend to work, try using a different host os 

Like what?

**Comment by Siguza** [comment]
Downgrades don't work like that. You're just patching part of your file system into a broken state.
