### ISSUE TITLE
iPhone 5 10.3.3

### ISSUE THREAD

**Issue by MaeIsGroovy** [checkra1n/BugTracker#125]
**What device + iOS version are you on?**
iPhone 5 (Global), 10.3.3

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. Plug in iPhone 5
2. Open Checkra1n
3.
...

**What do you expect, and what is happening instead?**
I expected the tool to recognise and let me jailbreak the iPhone 5, instead it is reporting the iPhone is unsupported. However the checkra.in website doesn't show it as being unsupported

**Any other info, error logs, screenshots, ...?**

**Comment by littlelailo** [comment]
32 bit devices are unsupported, see #1
