### ISSUE TITLE
Iphone 6s 12.4.1 trying to fix iTunes sync after icloudbypass & I've screwed everything up HELP.PLZ

### ISSUE THREAD

**Issue by AzZyOfficial** [checkra1n/BugTracker#1254]
HI, 
 Ios icloudbypass  Developers i need a little help of yours 
i have the iphone 6s 16GB with ios 12.4.1 I bypass this device 5 months Ago using these tools checkra1n 0.9.7 +  iCloudbypassCA on Ra1nusb
my device was Working Perfectly Expect iTunes Sync So today i see the Update of itunes sync fix for 13.xx i think used these tool on my device which is ios 12.4.1 installed 

what i did to my Device  Explain step by step
i have one more  Extra phone i decided to  bypass it with latest version of ios 13.4.1 i used  GSM Solution method and i successfully  bypass it +itunes fix Expect Bootloop so i did  re-jailbreak device is in working condition now 

Now What i was thinking to fix my 2nd  iphone s6 ios 12.4.1  itunes sync fix 
i thought maybe this method will helpfull too for ios 12.4.1
 But i was Wrong!
SO 
First i just Jailbreak my Device with latest version of checkra1n 0.10.1 via Ra1nusb
  run iCloudBypasser by GSM Solution
i selected Option 4 which is itunes Fix all commends runs 
now i tried to connect to itunes but sync is not fix i feel Sad well then i see another Video Which is the Cellular fix  + sim Fix with SliverV4_Windows by Apple tech 752 i jail break it again with checkra1n 0.10.1 
and try to FIX i click on dump files its gave me a ERROR then i just Randomly click Bypass iDevice of  SliverV4_Windows TOOL  by Apple tech 752
after some Seconds little window popup bypass Done the phone was working fine.. then i just close everything and think about to install Appsync via 3utools when i connect its shows your devices is not jailbreak but i already did jailbreak my device then i google it how to install 3utools appsync then i got this link http://www.3u.com/tutorial/articles/h... 
i follow all Steps while installing this tweak Apple File Conduit "2" (iOS 11+, a..i also Read the description Compatible with iOS 7 to 13. then i install it then i press Restart SpringBoard  it will keep Spinning for very log then i just Force Shutdown my Device by pressing power button and then i turn it on its stuck on APPLE LOGO one times its blink then again apple logo Appear h full Stuck  then i was thinking i recently bypass my other Extra iphone  13.4.1 its do the same but after Re-jailbreak it willl turn of so i Re-jailbreak my Device with 0.10.1 its stuck on Booting then it gave me a Error 
then i just try to connect to 3utool its keep showing connecting......nothing happen
then i decide to re-jail break with other versions 
i used checkra1n 0.9.2  jailbreak successful but still stuck on Apple Logo 
the same with checkra1n 0.9.6,  0.9.7 , 0.9.8.2 all these Checkra1n Successfully jail-breaking My device Expect checkra1n 0.10.1.. but on 1st time i use this to jailbreak it jailbreak my device now its not but other version are doing!

so now i m trying to catch my mistake i think when i use  SliverV4_Windows TOOL  by Apple tech 752 i should not click Bypass iDevice the reason i m thinking maybe that bypass method Replace my iOS 12.4.1 files to 13.4.1 bypass method that's why i m getting apple logo bootloop stuck if this is true then Why not going ahead after i Re-jail-breaking 
and about tweak install it is Compatible with it so its not that tweak Reason 
 maybe i m wrong i don't know just thinking in my head 

i know the solution the Solution is restore my but i don't want to restore and hang with iOS 13.4.1 when battery ran-out again n again re-jailbreak to turn on u know that .. well  12.4.1 is batter i was very happy no need to re-jailbreak i was happy but now i need HELP

**Comment by demhademha** [comment]
Bypassing iCloud isn’t a valid support request
