### ISSUE TITLE
iOS GameGuardian Repo Crash On my iOS 13 device

### ISSUE THREAD

**Issue by boswe23** [checkra1n/BugTracker#1272]
**Tell us about your setup:**
1. I am using a iPad 7 gen 128GB
2. I am on version 13.3.1
3. I am on version 0.9.8.2 on Checkra1n Jailbreak
4. My host system is on windows ten but I use Linux on it to do the checkra1n jaibreak.
5. I am connecting my apple devices to the laptop with a Apple usb charger cord.

**What are the steps to reproduce the issue?**
1. You want to go into cydia and add this repo: http://aquawu.github.io/igg/.
2. Then after you add the repo, you guys want to install igameguardian.
3. Then it should crash on your iOS device 
4. The Repo is no good because the repo is a iOS 12 repo, so it crashes on iOS 13 jailbroken devices.
...

**What do you expect, and what is happening instead?**
I expect that the repo should never be added to cydia , so other people won’t have the same problem I had before. I fix the issue myself. It was a easy fix but requires lots of wifi. I found out why it crashed on me , it could of been my wifi because it was really trashy before or it could be because cydia had a iOS 12 repo. Also I might know why it crash I think because I download a iOS 12 tweak on my iOS 13 device. I forget to probably read where it says not compatible with iOS 13 devices, and that could why it crash too.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
It put me on stuck on a apple boot logo, but good thing I made like two backups. It doesn’t take me to safe mode just takes me to stuck at Apple bootlogo. To fix the issues just don’t add the repo and install the tweak, and I had to use dr.ifone to fix my iPad to recover the system. It was pretty easy to recover just took some time , that’s all.

**Any other info, error logs, screenshots, ...?**
I think the repo is trash for iOS 13 devices. I also wish they made a new version of iOS gameguardian, or another load of cheat engines for jailbroken iOS 13 devices. That would be nice for me. I also wish there actually was a new cheat engine , because they only have GameGemiOS on iOS 13 and I want some more cheat engine for games on iOS 13. I want the cheat engine for iOS 13 to be a app to install inside a of cydia on my iOS 13 device. Also wish the developer of Ifile would fix it Ifile for jailbroken iOS 13 devices. I also installed Ifile before and when I open the app it crashes on my too.

**Comment by Siguza** [comment]
It's not our job to police repos for software that does or does not work on specific versions.  
You should submit the request to the repo maintainer instead, and ask that their tweaks require iOS 12 as a dependency.

**Comment by boswe23** [comment]
> It's not our job to police repos for software that does or does not work on specific versions.
> You should submit the request to the repo maintainer instead, and ask that their tweaks require iOS 12 as a dependency.

So you mean contact the developer of igameGuardian.

**Comment by Siguza** [comment]
Either that, or the repo maintainer (if those are not the same person).
