### ISSUE TITLE
STILL not working (A7)

### ISSUE THREAD

**Issue by zoomer555** [checkra1n/BugTracker#1277]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 5s
2. On what version of iOS is it? 12.4.4
3. What version of checkra1n are you using? 0.9.8-0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? linux
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Aftermarket usb-a cable.

**What are the steps to reproduce the issue?**
1. Put device to DFU mode
2. Unplug then replug USB cable (suggested workaround)
3. Phone just reboots and shows usbmux error 79
... 
If i don't use the workaround it just displays DFUSYNCUPLOAD FAILED -1 and the phone just reboots normally.

**What do you expect, and what is happening instead?**
I expect a jailbroken device and still doesn't work, doesn't even display checkra1n code in the phone, just reboots.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?** i have tried multiple cables, pc and multiple linux versions, also, in all my tries, the code execution never appeared in the phone ever since. I made an issue here weeks ago, the workaround i was suggested with never worked, i have tried 100+ times in all linux versions.

**Comment by zoomer555** [comment]
I have tried even in ra1nusb (0.9.7) just gives error -31 and -20

**Comment by Siguza** [comment]
Duplicate of #1169.

**Comment by zoomer555** [comment]
That workaround didn't work for me, my device just reboots. No pongoOS
