### ISSUE TITLE
iOS doesn't have Internet Connection anymore while still being connected to WIFI or LTE/4G

### ISSUE THREAD

**Issue by tanner02** [checkra1n/BugTracker#1279]
**Tell us about your setup:**
1. What iDevice are you using?
_iPhone 8 Plus_
2. On what version of iOS is it?
_13.4.1_
3. What version of checkra1n are you using?
_0.10.1_
4. What is your host system (OS version? Hackintosh? VM? etc.)?
_Macintosh on MacOS 10.14.6_
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
_Apple Lightning to USB-A trough Thunderbolt/USB-C to USB-A Adapter_

**What are the steps to reproduce the issue?**
1. Wait till its 8:30PM - 9:30PM i guess...

**What do you expect, and what is happening instead?**
Expected: _The device not loosing Internet Connection in that timespan._
Instead: _The device does not have any internet connection anymore after that timespan. Apps, as well as the whole System is not able to access the internet even after a Respring, reconnecting WIFI and/or Cellular Data. A restart fixes the problem until next day, same timespan._
**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
Happened again before writing this Issue, in Safe mode at ~ 9:32PM
Also, I still can get Notification Banners from Apps such as Discord, but the app/s itself can't connect to the Internet

**Comment by tanner02** [comment]
Update:
So, for the first time, it happened **again** after 2 hours.

**Comment by tanner02** [comment]
It happens randomly now, doesn't have to be in that timespan anymore.

**Comment by skurrrr** [comment]
Apparently the issue still persist in Stock iOS. Without being jailbroken. I’ll close this issue now because the issue isn’t related with Checkra1n anymore (or wasn’t).

**Comment by tanner02** [comment]
Apparently the issue still persist in Stock iOS. Without being jailbroken. I’ll close this issue now because the issue isn’t related with Checkra1n anymore (or wasn’t).

**Comment by jzarca01** [comment]
I had the issue with my ipX 13.5 (4G randomly stopped working but switching to 3G was ok)
Started fresh and jailbroke again on 14.3 (using checkra1n 0.12.2) and I still have the same issue

For now the only way I found is to reboot my device twice

@Siguza is there any way I can provide a useful log ?

**Comment by ldarcos** [comment]
Same issue for me (iPhone X 14.7.1). I jailbroke with the last checkra1n, everything was fine and these problems started 1 day later. I left checkra1n but the problems persist. 
My iMac can't connect to the iPhone (tab is shown, but blank).

http is working (all the app that connect to the internet to consume data are working), but any app base on a browser can't connect to internet. if I restart the phone, it works to load one web page, and nothing more.
