### ISSUE TITLE
Run uicache while restoring file system

### ISSUE THREAD

**Issue by camschmottlach03** [checkra1n/BugTracker#128]
When I use the restore option, the blank Cydia icon remains on the home screen and is not able to be deleted. By running uicache while restoring, it may help get rid of the icon.

**Comment by Armin-kho** [comment]
I have the same issue!
since the device is unjailbreaked I am not able to SSH into my device to run uicache in order to remove blanked cydia icon.

**Comment by sbingner** [comment]
This is already on the roadmap but was not deemed a requirement for 0.9.0
