### ISSUE TITLE
Clock app crashes springboard

### ISSUE THREAD

**Issue by cpugeek1999** [checkra1n/BugTracker#1285]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7 Plus
2. On what version of iOS is it? 13.4.1
3. What version of checkra1n are you using? .10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? MacOS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple usb type A

**What are the steps to reproduce the issue?**
1. Open Clock App in jail broken state 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
no

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Given the fact this doesn't happen in Safe Mode, this sounds very much like a tweak.
