### ISSUE TITLE
Lost Home button use

### ISSUE THREAD

**Issue by FlailsAlot** [checkra1n/BugTracker#1289]
<!--  
DO NOT USE THIS TEMPLATE FOR BUG REPORTS!

IF YOU DO, THEY WILL BE CLOSED AND MARKED AS INVALID!

--After completing jailbreak on both iPhone 8+ and iPhone SE I could use the home button combined with lock button to take a screen shot but not to open screen unlock

**Comment by dpgvan** [comment]
Seeing the same issue on iPad Air 2. Installed checkra1n 0.10.1 beta on an Apple ID locked device. Please let me know if there's any further info I can provide.

**Comment by Siguza** [comment]
That's the effects of an iCloud lock, and we won't do anything about that.
