### ISSUE TITLE
iMessage not receiving texts

### ISSUE THREAD

**Issue by evanknapke** [checkra1n/BugTracker#129]
**What device + iOS version are you on?**
iPhone 8, iOS 13.2.2

**What checkra1n version are you using?**
0.9.1

**What are the steps to reproduce the issue?**
1. Have someone text the device from another iPhone

**What do you expect, and what is happening instead?**
I expect to get iMessages when sent to me. However, when someone sends a text, I get it on my Mac, but nothing appears on the iPhone. I can see that the person has "read" the message, I can see that the person is typing, and I can send iMessages just fine. However, _most_ message coming to me, I do not ever receive.

**Comment by n3oney** [comment]
Can't reproduce on iPhone 6s iOS 13.2.2

**Comment by nullpixel** [comment]
Can’t reproduce this on an iPhone X on 13.1.2. Do you have any tweaks installed?

**Comment by evanknapke** [comment]
> Can’t reproduce this on an iPhone X on 13.1.2. Do you have any tweaks installed?

I have installed very few tweaks, and they were all confirmed working. Issues began off and on since I jailbroke. Issues do not persist when in unjailbroken state.

Here is my tweak list:
7-zip (POSIX): 16.02-1
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 0.7 Transitional (apt-key): 1:0
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BetterCCXI: 1.6.0-2
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-1
bzip2: 1.0.6-1
CA Certs: 0.0.2
CCModules: 1.4-3
CCSupport: 1.2.1
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cydia Installer: 1.1.32 b22
Cydia Substrate: 0.9.7100 b3
Cydia Translations: 1.1.32 b1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
Essential: 0-1
file: 5.35-2
Filza File Manager: 3.6.4
Find Utilities: 4.6.0-2
Flame: 1.3
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
iCleaner: 7.7.5
ImLyingDownDamnit: 1.4
iOS Firmware: 13.2.2
iPhone Firmware (/sbin): 0-1
KSBA: 1.3.5-1
libcolorpicker: 1.6.4
libidn2: 6.1.2-1
libplist: 2.0.0-2
libSparkAppList: 1.0.3
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
OpenSSH: 7.9p1-3
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
PreferenceLoader: 2.2.4 beta1
Profile Directory: 0-1
PullToRespring: 1.2
readline: 8.0-1
RealCC: 1.0.2
sed: 4.5-1
shell-cmds: 118-8
Snappy: 1.2
Substrate Safe Mode: 0.9.6003
SwipeForMore: 1.1.10
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TetherMe for iOS 8+: 1.2.3 arm64e-1
UIKit Tools: 1.1.15-2
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
wget: 1.19.5-2
XZ Utils: 5.2.4-4
zip: 2.32-1

**Comment by littlelailo** [comment]
Can you replicate it with safe mode enabled?

**Comment by nullpixel** [comment]
Closing this issue through a lack of response, I will reopen it if you can still reproduce
