### ISSUE TITLE
I have a -79 error when activating the jailbreak.

### ISSUE THREAD

**Issue by iH7San** [checkra1n/BugTracker#1293]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone7p ( A10 )
2. On what version of iOS is it?
ios13.3.1
3. What version of checkra1n are you using?
checkra1n 0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Use Windows (checkn1x)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
usb-a

**What are the steps to reproduce the issue?**
1.
2.
3.

**What do you expect, and what is happening instead?**
 That the jailbreak is activated on my device.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
No

**Any other info, error logs, screenshots, ...?**

**Comment by faisalali129** [comment]
Try to change the lighting cable, It might solve the problem
