### ISSUE TITLE
iPad Pro iOS 13.3.1 not booting into DFU mode

### ISSUE THREAD

**Issue by beastlyhaz** [checkra1n/BugTracker#1308]
**Tell us about your setup:**
1. What iDevice are you using? iPad Pro 9.7"
2. On what version of iOS is it? 13.3.1
3. What version of checkra1n are you using? beta 0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? macOS Catalina 10.15.4
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple USB-C to lightning cable

**What are the steps to reproduce the issue?**
1. Click start and device goes into recovery mode
2. Click next
3. Click start and follow steps to put device in DFU mode
4. Device boots back up into recovery mode

**What do you expect, and what is happening instead?**
I have successfully put my device into DFU mode and applied the jailbreak many times before using an apple USB-A to lighting cable and USB-C hub before, however, when I use an Apple USB-C to lighting cable the device doesn't boot into DFU mode. It just boots back up into recovery mode

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
<img width="477" alt="Screen Shot 2020-05-03 at 2 53 16 pm" src="https://user-images.githubusercontent.com/41460934/80899028-4dc5de00-8d4e-11ea-9ff8-c01fbe50c457.png">

**Comment by tallytarik** [comment]
Just wanted to say thank you for mentioning the USB-C to Lightning cable in your issue!

I was wondering why my iPhone 7 wasn't entering DFU mode despite my 20 attempts. I was using the same cable.

I tried with a USB-A lightning cable to a USB-A > C adapter, and it worked straight away.

It seems like there's some problem with USB-C to Lightning cables?

**Comment by Siguza** [comment]
Yep, Apple's USB-C to lightning cables are known to not work. See #1 for more info.  
Marking as wontfix since we can't do anything about that.
