### ISSUE TITLE
Checkrain iOS 13.4.1 : RIP

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#1310]
Firstly, I'm so sorry if it's partially a bump of other issues.

**Tell us about your setup:**
1. What iDevice are you using?
iPhone 7 (GSM) aka iPhone9,3

2. On what version of iOS is it?
iOS 13.4.1

3. What version of checkra1n are you using?
checkra1n 0.10.1 beta
Installed trough the Checkra1n repo.
https://checkra.in/linux

4. What is your host system (OS version? Hackintosh? VM? etc.)?
KDE neon (x64) dual boot with Windows 10.
I always launch gui Checkra1n as root with 
$ sudo su
\# checkra1n --gui
Also tried bootra1n and other Linux distros like MX Linux.
(Anyway, VMs of (Linux or macOS) wouldn't work in Virtualbox because the Lightning connection hangs while applying jailbreak. Also when rebooting iOS.)

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A 3rd party cable on USB 2.0 / 3.0 port of my PC.
(My Apple Lighting cable is in trash since it's broken.)

**What are the steps to reproduce the issue?**
1. Try to jailbreak for the first time. 
2. See it works perfectly ("All done" appear in Checkra1n app).
3. Install "incompatible tweaks" (or just reboot the iPhone without jailbreak ???).
4. Close the device and restart (or reinstall) Checkra1n app.
5. Rejailbreak it normally with Checkra1n.
6. See it seems to works. Then it reboot to unjailbroken.
7. Try to wipe the iPhone completly from settings app.
8. See it doesn't remove the jailbreak nor Cydia tweaks.
9. Try to jailbreak with Safe Mode option of Checkra1n app, &or try pressing sound + button when you see Apple logo. 
10. The jailbreak doesn't work and you get a USBMUX error :
     (code -79 or -92 depending on the previous step). 

**What do you expect, and what is happening instead?**
I would expect the device not crashing after jailbreak.
I would expect to not get the USBMUX error when trying to jailbreak as Safe Mode or when pressing the + volume button.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes. Without Safe Mode, it will crash when loading Cydia, tweak or Checkra1n app from Springboard. With Safe Mode or + button, it will crash directly after jailbreak.

**Any other info, error logs, screenshots, ...?**

A good fix would be to have an option to restore the rootfs directly from the Linux / macOS Checkra1n app.

USBMUX errors while jailbreaking as SafeMode &or while pressing + button :
USBMUX Error (Error code: -79)
USBMUX Error (Error code: -92)

Anoter error that always appear before jailbreaking :
This text appear just before the green " - [*]: some text here" lines in terminal.
(checkra1n:3641): Pango-WARNING **: 20:35:21.610: Invalid UTF-8 string passed to pango_layout_set_text()

A good fix for another bug I didn't described previously :
Bug : 
Checkra1n macOS / Linux app need to be rebooted because it can only be used only one time.
Fix : 
Automatically reboot Checkra1n app after jailbreak.

**Comment by ghost** [comment]
For anyone having kind of same issue than me, by that I means that the iDevice reboot after a  successful jailbreak, and that you can't repair it, there's only one way to fix it :
Wipe the iDevice in iTunes

**Comment by tanner02** [comment]
>Checkra1n macOS / Linux app need to be rebooted because it can only be used only one time.
1. Thats a known issue 
2. It only happens on Linux afaik. Not MacOS.

**Comment by nergzd723** [comment]
You really shouldn't get USBMUX error while entering Safe Mode, Safe mode just passes some arguments to PongoOS command line, so it must work. Seems like a bug.

**Comment by ghost** [comment]
After I wiped and reinstalled Checkra1n on my iPhone, it works fine.
So surely I won't get USBMUX errors, I don't know.

**Comment by demhademha** [comment]
If the issue is  fixed please close the  issue
