### ISSUE TITLE
Checkra1n continiously failing, getting phone stuck in recovery mode

### ISSUE THREAD

**Issue by rosegayming** [checkra1n/BugTracker#1312]
1. What iDevice are you using?
iPhone 8+, firmware iPhone 10,5
2. On what version of iOS is it?
13.3.1-13.4.1
3. What version of checkra1n are you using?
Used 0.9.8 pre 13.4 and 0.1.0 13.4 and later
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Macbook air early 2014, macOS 10.12.6. bootra1n, and pop!_OS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Official Apple USB-A to lighting, generic 3rd party, and Amazon Basics cable

**What are the steps to reproduce the issue?**
1. Attempt to jailbreak 
2. Fails
...

**What do you expect, and what is happening instead?**
Jailbreak succeeding

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by nergzd723** [comment]
Is it stuck in DFU or is it stuck in Recovery?(recovery mode is when the iTunes logo shown on screen)

**Comment by rosegayming** [comment]
It was recovery mode but since I made this issue, I did find a fix in fully wiping the device and restoring from itunes.
