### ISSUE TITLE
Stuck - Right before trigger - iPhone 5S on iOS 12.4.6

### ISSUE THREAD

**Issue by lasantharanjana** [checkra1n/BugTracker#1313]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. iPhone 5S A1533 - iCloud locked.
2. 12.4.6
3. 0.10.1 Beta
4. Ubuntu 18.04.4 LTS - CLI & GUI both
5. USB-A Apple cable

**What do you expect, and what is happening instead?**
The screen is stuck at 'Right before trigger'

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes. I have tried using "Safe Mode".

**Any other info, error logs, screenshots, ...?**

![Screenshot from 2020-05-05 16-34-11](https://user-images.githubusercontent.com/27633117/81103973-72c57700-8f2f-11ea-8f52-6cf0d917fb78.png)

![Screenshot from 2020-05-05 10-22-26](https://user-images.githubusercontent.com/27633117/81103981-748f3a80-8f2f-11ea-914e-7856b4b2bd38.png)

**Comment by rly907** [comment]
Unplug the usb and plug it back in super fast. fixed my iPad witch had the same problem.

After you unplug and plug back it will say Booting...
That is when it fixed mine

**Comment by nergzd723** [comment]
See #1169

**Comment by king112233** [comment]
> **Tell us about your setup:**
> 
> 1. What iDevice are you using?
> 2. On what version of iOS is it?
> 3. What version of checkra1n are you using?
> 4. What is your host system (OS version? Hackintosh? VM? etc.)?
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
> 
> **What are the steps to reproduce the issue?**
> 
> 1. iPhone 5S A1533 - iCloud locked.
> 2. 12.4.6
> 3. 0.10.1 Beta
> 4. Ubuntu 18.04.4 LTS - CLI & GUI both
> 5. USB-A Apple cable
> 
> **What do you expect, and what is happening instead?**
> The screen is stuck at 'Right before trigger'
> 
> **Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
> Yes. I have tried using "Safe Mode".
> 
> **Any other info, error logs, screenshots, ...?**
> 
> ![Screenshot from 2020-05-05 16-34-11](https://user-images.githubusercontent.com/27633117/81103973-72c57700-8f2f-11ea-8f52-6cf0d917fb78.png)
> 
> ![Screenshot from 2020-05-05 10-22-26](https://user-images.githubusercontent.com/27633117/81103981-748f3a80-8f2f-11ea-914e-7856b4b2bd38.png)

**Comment by lasantharanjana** [comment]
This is sorted. This should be updated as a duplicate.
