### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by cyxl** [checkra1n/BugTracker#1316]
**Tell us about your setup:**
1. What iDevice are you using?7
2. On what version of iOS is it?13.4.1
3. What version of checkra1n are you using?Linux_84_64 
4. What is your host system (OS version? Hackintosh? VM? etc.)?VM with ubuntu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?Lightning cable by apple

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**
It should work

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Havent tryied

**Any other info, error logs, screenshots, ...?**
Yes it says that this device was not put in recoverymode

**Comment by nergzd723** [comment]
Vm's are not supported.

**Comment by Siguza** [comment]
I'm assuming your host is Windows, which doesn't support USB passthrough.
