### ISSUE TITLE
Commcenter freeze and crash after user space reboot

### ISSUE THREAD

**Issue by ceedveed** [checkra1n/BugTracker#1319]
**Tell us about your setup:**
1. What iDevice are you using? iPhone X
2. On what version of iOS is it? 13.3.1
3. What version of checkra1n are you using? 0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? Hackintosh
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Official Apple USB A to lightning cable

**What are the steps to reproduce the issue?**
1. User space reboot by using UserSpaceRebootModule
2. Get on a call.
3. Varies each time, but after 5-30 minutes, audio will continuously beep and freeze phone until Commcenter crashes as reported by Cr4shed, which ends the audio beeping and phone call.
4. Also with or without an active call, LTE data cannot be received.
5. Fixing requires a reboot (off then on) and rejailbreak.
...

**What do you expect, and what is happening instead?**
I expect a normal call, but call drops, audio beeps, and phone freezes until Commcenter crashes and restarts. Also expect LTE data to work, but no data works.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Did not try yet.

**Any other info, error logs, screenshots, ...?**
Kern Bypass not used (activated). Using ldrestart instead of user space rebooting does not result in any issue with phone calls or cellular data.

**Comment by Siguza** [comment]
Could you drop us a crash log?

**Comment by ceedveed** [comment]
[text.txt](https://github.com/checkra1n/BugTracker/files/4638095/text.txt)

**Comment by ceedveed** [comment]
This issue does not occur with 0.10.2.
