### ISSUE TITLE
iphone 7 plus tweaks don't work and won't show in settings and given suggestions don't work

### ISSUE THREAD

**Issue by dorianbush** [checkra1n/BugTracker#132]
**What device + iOS version are you on?**

**What checkra1n version are you using?**

**What are the steps to reproduce the issue?**
1.
2.
3.
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by Shadowedstalker** [comment]
This also can be due to a source conflict within Cydia (as was my issue) I deleted the sources and added them back one by one until I found the problem. (XEN)

**Comment by littlelailo** [comment]
Closing this because it's a dub of #134
