### ISSUE TITLE
Sorry, iPhone 11 is not supported. ECID: 0xa209c3c29802e

### ISSUE THREAD

**Issue by avtaritet** [checkra1n/BugTracker#1324]
when trying to jailbreak iphone 11 i am getting this error. could you plz help me on that

**Comment by ghost** [comment]
believe it or not the reason you see this is because checkra1n doesn't support iphone 11

**Comment by minecrafthello** [comment]
iPhone 11 is not supported with checkra1n. You cannot jailbreak with checkra1n with an iPhone 11

**Comment by demhademha** [comment]
Please close this issue

**Comment by SarKaa** [comment]
I'm shocked, it must be a bug in checkra1n, they can't do that. 
But seriously, maybe try reading the error message before copy and pasting it into a github issue
