### ISSUE TITLE
iPad mini 3 12.4.6 Home button not responsive + more

### ISSUE THREAD

**Issue by RedGeminiPA** [checkra1n/BugTracker#1326]
**Tell us about your setup:**
1. What iDevice are you using? iPad mini 3

2. On what version of iOS is it? 12.4.6

3. What version of checkra1n are you using? 10.1

4. What is your host system (OS version? Hackintosh? VM? etc.)? 2019 MacBook Pro 13" 10.15.4

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Original Apple Lightning through Apple USB-A/HDMI adapter. Apple Lightning to USB-C cable does NOT work for this. 

**What are the steps to reproduce the issue?**
Every "successful" jailbreak has same result

**What do you expect, and what is happening instead?**
Reboots to "Hello" screen after jailbreak. Home button unresponsive. If I reboot untethered, it jumps straight to home screen (fresh restore prior to jailbreak), no setup, apps are unresponsive except FaceTime. Home button still unresponsive. Home button works, as it works for DFU mode, and works as it should when factory restored. If it goes to sleep, home button does wake it up.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by innernet** [comment]
I encountered the same problem on my iPad Air. The version of iOS is also 12.4.6.

**Comment by Siguza** [comment]
Sounds like iCloud lock.

**Comment by RedGeminiPA** [comment]
It does have iCloud lock. I've run Checkm8, too. No difference. 

I haven't found anything saying iCloud activation lock makes a difference. That's supposed to be what the Ckeckra1n and Checkm8 combo is for.

**Comment by Siguza** [comment]
In one of the latest 12.4.x versions, Apple improved iCloud lock enforcement, in the exact way you're describing: home button and springboard icons would no longer work when unactivated.

Gonna close this as "not checkra1n's fault".

**Comment by RedGeminiPA** [comment]
So, only resort is to roll back iOS? Which version seems to work best?

**Comment by RedGeminiPA** [comment]
Can you suggest a version to roll iOS back to that isn’t problematic?
