### ISSUE TITLE
Can’t install tweaks

### ISSUE THREAD

**Issue by kash29** [checkra1n/BugTracker#1340]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone X 
2. On what version of iOS is it?
iOS 13.4.1
3. What version of checkra1n are you using?
Beta 0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? MacOS Catalina 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple original USB-C cable directly from the Mac to iPhone 

**What are the steps to reproduce the issue?**
1. Installing a tweak
2. 
3.
...

**What do you expect, and what is happening instead?** the repo is offline

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?** yes

**Any other info, error logs, screenshots, ...?**
![FA72B001-E62F-4EE1-BC7E-0B63BB1B5A0F](https://user-images.githubusercontent.com/65214342/81645445-355d5f80-93ef-11ea-9236-00d807212668.png)

**Comment by demhademha** [comment]
Wait a bit until the repo comes back online

**Comment by Siguza** [comment]
That's a networking issue. Not checkra1n's fault.
