### ISSUE TITLE
Battery usage

### ISSUE THREAD

**Issue by x007sunny** [checkra1n/BugTracker#1341]
Hi guys. Will you please fix the battery usage display. I’ve tried everything and still cannot see the battery usage display. iPhone X iOS 13.4.1 :(

**Comment by oyeanu** [comment]
me too

**Comment by SarKaa** [comment]
search online for a package called "powerloghelperdfix" that fixed it for me
edit: found the reddit release post:
https://www.reddit.com/r/jailbreak/comments/dxd5kk/release_powerloghelperdfix_block_code_injection/

**Comment by x007sunny** [comment]
When I said I’ve tried everything, I mean everything. Still doesn’t work. Also tried choicy. Also doesn’t work. Must be iPhone X issue.

**Comment by Siguza** [comment]
Tested on 13.5 beta 4 here with some tweaks installed, can't reproduce the issue.

You should find the tweak that's responsible for crashing `powerlogHelperd` and report this to the author instead.
