### ISSUE TITLE
-20 error

### ISSUE THREAD

**Issue by RainbowOfGalaxy** [checkra1n/BugTracker#1342]
Im using ipad air 2 ios 13.4.1 checkra1n 10.1
Usb A cable and its saying request permission ita saying -20 error and im using macbook only macbook

**Comment by oyeanu** [comment]
run in cli mood or disable passcode

**Comment by RainbowOfGalaxy** [comment]
what is cli mod

**Comment by RainbowOfGalaxy** [comment]
What is cli mod

**Comment by RainbowOfGalaxy** [comment]
> run in cli mood or disable passcode

ı doesent have password

**Comment by xsslize** [comment]
> What is cli mod

Command-line interface

**Comment by berrouanmohammed** [comment]
I have the same problem too with ipad air 2 ios 13.4.1 checkra1n 10.1, i used cli mode and got the same -20 error, even with the safe mode it doesn't work thanks

**Comment by RainbowOfGalaxy** [comment]
İ have the same error

**Comment by qiuyi21** [comment]
The same here. The screen display as following picture:
![IMG_1062](https://user-images.githubusercontent.com/3156921/81834724-eb51b680-9573-11ea-8079-a3e08661a7ad.jpg)

**Comment by berrouanmohammed** [comment]
> I have the same problem too with ipad air 2 ios 13.4.1 checkra1n 10.1, i used cli mode and got the same -20 error, even with the safe mode it doesn't work thanks

Finally i jailbroken my ipad air 2 ios 13.4.1 with checkra1n 0.9.9, but after bypassing icloud appstore wont sign in and that another problem that i should find a solution for, thanks

**Comment by RainbowOfGalaxy** [comment]
i know your solition

**Comment by berrouanmohammed** [comment]
> i know your solition

What is the solution ?  I need it

**Comment by RainbowOfGalaxy** [comment]
Factory mode reset the ipad and install the restore first backup from 3uTools

**Comment by RainbowOfGalaxy** [comment]
> The same here. The screen display as following picture:
> ![IMG_1062](https://user-images.githubusercontent.com/3156921/81834724-eb51b680-9573-11ea-8079-a3e08661a7ad.jpg)

How to run in cli mod

**Comment by yras245** [comment]
> > The same here. The screen display as following picture:
> > ![IMG_1062](https://user-images.githubusercontent.com/3156921/81834724-eb51b680-9573-11ea-8079-a3e08661a7ad.jpg)
> 
> How to run in cli mod

If you use Mac OS you need to find checkrain app in apps folder and right click on checkrain app and click show contents and find checkrain file in Contents/MacOS and double click on it

but cli mod not helped me(


(sorry for bad english)

**Comment by yras245** [comment]
Try jailbreaking with checkra1n 0.9.9 
[checkra1n beta 0.9.9.dmg.zip](https://github.com/checkra1n/BugTracker/files/4628845/checkra1n.beta.0.9.9.dmg.zip)

**Comment by Siguza** [comment]
Duplicate of #1168.
