### ISSUE TITLE
iPhone 7 iOS 13.4.1 failing to go into DFU mode

### ISSUE THREAD

**Issue by saintjewell** [checkra1n/BugTracker#1347]
I am attempting to Jailbreak my iPhone with your program, but I seem to be running into some trouble when asked to put phone in DFU mode. Please help.

**Comment by asdfugil** [comment]
what cable do you use?

**Comment by saintjewell** [comment]
Usb-C to lightning cable

**Comment by saintjewell** [comment]
Iphone connected to mac when prompted, but to no avail.

**Comment by Siguza** [comment]
Apple's USB-C-to-Lightning cables have proven to not work for some reason. See #1 for more information.
