### ISSUE TITLE
iPhone 6s gets stuck on boot command at startup

### ISSUE THREAD

**Issue by slickpads** [checkra1n/BugTracker#135]
**What device + iOS version are you on?**
13.1.2

**What checkra1n version are you using?**
latest version
**What are the steps to reproduce the issue?**
1.download a respring animation, install it through cydia
2.try to respring
3.boom you fucked your device.now it wont boot
...

**What do you expect, and what is happening instead?**
I expect the animation to play and everything fine but when I boot from checkrein it gets stuck on the boot command at startup and I can't do shit about it and can only normally use my device unjailbroken

**Any other info, error logs, screenshots, ...?**
no

**Comment by nullpixel** [comment]
did you install a tweak?

**Comment by neptune-jailbreak** [comment]
Same with me. iPhone X, same iOS version, same steps to reproduce the issue, and I can only boot my device unjailbroken by force resetting the phone on the "Booting" command. I run the checkra1n app on my mac and it work's until the Booting stages, then it waits 30 seconds and says All Done but my device is still on the booting phase.

**Comment by neptune-jailbreak** [comment]
Please provide a solution or someway to uninstall bad tweaks.

**Comment by nullpixel** [comment]
There will be an update in the future (most likely within a day or so) which will allow you to boot into safe mode to remove bad tweaks. Please look out for it.
