### ISSUE TITLE
Broke my phones ability to boot altogether

### ISSUE THREAD

**Issue by SarKaa** [checkra1n/BugTracker#1351]
**Tell us about your setup:**
1. What iDevice are you using?
iphone 7 plus
2. On what version of iOS is it? 13.3.1
3. What version of checkra1n are you using? 0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? linux
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? official apple cable

**What are the steps to reproduce the issue?**
1. boot, doesn't boot

**What do you expect, and what is happening instead?**
My phone to boot, or at least boot when unjailbroken 

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**
I have had errors like this before, but most are from tweaks, which i fix by using the safe mode option and icleaner. Before, some tweaks broke the ability to ldrestart, hence jailbreaking with tweaks enabled. This time, I performed a normal ldrestart, which got stuck in a bootloop. Fine this has happened before, and didn't affect me, but this one kept going. When it finally stopped when I hard reset, my phone got stuck on the apple logo, and would occasionally go black for a split second, as if it was retrying the boot procedure, but would then hang at the boot screen again. I put it in recovery, and even updated the firmware through itunes, but that didn't fix it. Finally I had to restore my phone altogether, which was not ideal, but it worked. 

my tweaklist:
applist
com.a3tweaks.flipswitch
com.captinc.batchomatic
com.creaturecoding.libcspreferences
com.creaturecoding.shuffle
com.creaturesurvive.libcscolorpicker
com.demy076.dismissanywhere
com.dpkg.cappd
com.dpkg.statusbarxs
com.exoticswingset.truthfulfolders
com.giorgioiavicoli.passby
com.hackyouriphone.iconrepo
com.hackyouriphone.spotilife
com.ichitaso.powerselector11
com.icraze.bettersettingsfix
com.jailbreak365.safeccmodules
com.johncoates.flex3
com.kingpuffdaddi.control-center.ccvpn
com.laughingquoll.prefixui
com.linusyang.appinst
com.lpane.browserdefault
com.macciti.lotus
com.midnightchips.bettersettings
com.modmyi.libswift4
com.muirey03.libimagepicker
com.muirey03.libmryipc
com.opa334.ccsupport
com.rpetrich.rocketbootstrap
com.spark.libpackageinfo
com.spark.libsparkapplist
com.spark.nolowpowerautolock
com.spark.snowboard
com.spark.snowboard.respringextension
com.spark.snowboardapplication
com.tigisoftware.filza
com.twickd.spdxs
com.twickd.t0mi.applerespringprogress
com.zx02.frame
curl
cydia-lists
jp.akusio.backgrounderaction13
jp.akusio.milkyway2
libactivator
libnghttp2-14
libssh2
libssl1.1.1
me.nepeta.libcolorpicker
mktbypass
mterminal
net.angelxwind.appsyncunified
openssh
p7zip
preferenceloader
ru.rejail.assistability13
ru.rejail.autotouch
ru.rejail.betternetpremium
ru.rejail.bioprotectxs
ru.rejail.floatingdockplus13
ru.rejail.flow
ru.rejail.icleanerpro
ru.rejail.kalm
ru.rejail.limneosos
ru.rejail.localiapstore
ru.rejail.prysm
ru.rejail.scribb
ru.rejail.voicechangerx
ru.rejail.xeonbeta
ru.rj.nougat
sedfix
unrar
unzip
ws.hbang.common
xyz.willy.zebra
zip

**Comment by SarKaa** [comment]
This just happened again, after I tried to put my phone in safe mode over ssh. I think that might have been the problem, because the same happened. It isn't easy restoring your phone,please someone find out

**Comment by tingalvin** [comment]
I had this issue with the GUI. it says enter recovery mode fail, and then after unable to boot. had to DFU restore, tried again same issue.
downloaded the file and running from terminal with sudo worked..

**Comment by SarKaa** [comment]
> I had this issue with the GUI. it says enter recovery mode fail, and then after unable to boot. had to DFU restore, tried again same issue.
> downloaded the file and running from terminal with sudo worked..

No it wasn't while jailbreaking, it was when I tried to put my phone in safe mode over ssh using activator. I was just looking around and recently found out about activator's command line options. When I used the safe mode option, I had to restore. At first I didn't know it was the safe mode command that caused it, but when it happened the next day, I was certain that was the reason

**Comment by SarKaa** [comment]
Happened again, 3rd day in a row I have had to restore my iphone

**Comment by Siguza** [comment]
Sounds like one of your tweaks is breaking something on disk.

**Comment by SarKaa** [comment]
> Sounds like one of your tweaks is breaking something on disk.

Thanks for replying, 
Are there any tweaks that are known to break disks, because most of these tweaks I have had used for years, and on different jailbreaks too, but I've never had this problem before

Also this happens any time I do anything that restarts springboard. The three times I had this issue, I ldrestarted. resprung into safe mode, and resprung normally respectively

**Comment by SarKaa** [comment]
So I was reading a post in Reddit that was completely irrelevant to this, but it was about icleaner pro. Could disabling any launch daemons from there cause this

**Comment by SarKaa** [comment]
Nah man this happened again, this time all tweaks were disabled in icleaner, and I tried ldrestarting from terminal, same thing happened again

**Comment by Siguza** [comment]
I had a closer look at your tweak list, and what is suspiciously missing is Substrate... so either your list is incomplete, or you're doing something very weird.

**Comment by SarKaa** [comment]
> I had a closer look at your tweak list, and what is suspiciously missing is Substrate... so either your list is incomplete, or you're doing something very weird.

Oh yeah didn’t see that
But I think that’s because this is from batchomatic, which only makes a list of tweaks that batchomatic itself doesn’t require

Edit: I can definitely confirm that Cydia substrate, substrate safe mode, preference loader, or any other essential packages were all installed

**Comment by SarKaa** [comment]
If you want the whole list

```
7-zip (POSIX): 16.02-1
Activator: 1.9.13~beta9
Alderis Color Picker: 1.0
AppList: 1.5.16
AppSync Unified: 74.0
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assistability13 Rus: 0.0.1-1
Assuan: 2.5.1-1
AutoTouch: 6.1.2k
BackgrounderAction2 for CCSupport: 0.1.4
Base Structure: 1-5
BatchInstall - Online: 2020.05.15-15.47.10
Batchomatic: 4.3.1
Berkeley DB: 6.2.32-1
Betternet++: 1.0.1.4
BetterSettings: 0.1.3
BigBoss Icon Set: 1.0
BioProtect XS (iOS 12/13) Rus: 4.4-49
Bourne-Again SHell: 5.0.3-2
BrowserDefault: 1.9.9
bzip2: 1.0.6-1
CA Certs: 0.0.2
Cappd: 1.0.3
CCModules: 1.5-1
CCSupport: 1.2.2
CCVPN: 1.0.4
Cephei: 1.15
Compactor: 1.0.2
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cydia Installer: 1.1.33
Cydia Lists: 0.1
Cydia Substrate: 0.9.7101
Cydia Translations: 1.1.32~b1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
DismissAnywhere: 1.4
file: 5.35-2
Filza File Manager: 3.7.2
Find Utilities: 4.6.0-2
Flame: 1.3
Flex 3: 3~EarlyAccess4
Flipswitch: 1.0.16~beta7
FloatingDockPlus13 Rus: 1.1.7
Flow Rus: 1.1.4
Frame: 2.1.1
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
HYI Repo Icons: 8.0.4
iCleaner Pro: 7.8.2
iOS Firmware: 13.4.1
iPhone Firmware (/sbin): 0-1
Kalm Rus: 1.3.4
KSBA: 1.3.5-1
Launch Daemon Controller: 23-1
libbulletin: 0.1-153
libCSColorPicker: 1.0.3
libCSPreferences: 1.3.5
libidn2: 6.1.2-1
libimagepicker: 1.0.4
libMRYIPC: 1.0
libplist: 2.0.0-2
libSparkAppList: 1.0.8
libsparkcolourpicker: 1.0.0
libswift4: 4.2.1-2
libtasn1: 4.13-1
libunistring: 0.9.10-1
Limneosos: 2.0.2
Link Identity Editor: 2:2.1.2+g5420cb5-1
LocalIAPStore: 1.4-2
Lotus: 1.0
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
MilkyWay2: 0.2.0-alpha
MTerminal: 1.4-6
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1+20181013-1
New GNU Portable Threads: 1.6-1
NoLowPowerAutoLock [Public]: 0.0.3
Nougat: 1.0.1
OpenSSH: 8.1-1
OpenSSL 1.0 Libraries: 1.0.2s-1
OpenSSL 1.1.1 Libraries: 1.1.1c-1
p11-kit: 0.23.12-1
PassBy: 1.8.3
powerlogHelperdFix: 1.0
PowerSelector (iOS 11 & 12): 1.2.1
PreferenceLoader: 2.2.4
PrefixUI: 1.2.6
Profile Directory: 0-1
Prysm: 1.7.5
readline: 8.0-1
RocketBootstrap: 1.0.9
Scorpion: 1.1k
Scribble: 1.5-1k
sed: 4.5-1
shell-cmds: 118-8
shuffle: 1.1.4
Shy Page Dots XS: 0.2
SmartBattery Rus: 2.7-1
SmartNetwork Rus: 1.0.7-1
Snappy: 1.3.0
SnowBoard: 1.2.94~Beta2
Spotilife: 1.1a
StatusBarXS: 1.2
Substrate Safe Mode: 0.9.6003
System Info: 2.0.0-1
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TruthfulFolders: 1.1
UIKit Tools: 1.1.15-2
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
VoiceChanger XS Rus: 2.2-51
wget: 1.19.5-2
XZ Utils: 5.2.4-4
Zebra: 1.1.4
zip: 2.32-1
```

**Comment by SarKaa** [comment]
I have reenabled all the launch daemons in icleaner, and tommorow, if the problem still persists, I will get back to you 
Also, in icleaner, one of the disabled daemons was the safe Daemon. Do you think it could have been from that 
Edit at 11:50 bst, I think it’s safe to say, so far so good, I have successfully restoring without a boot loop, but I’m still not certain the problems gone,

**Comment by SarKaa** [comment]
I can confirm that I can respring normally, respring into safe mode, and I haven’t tested ldrestart, but things seem to be fixed
Exactly what I did:
Removed rejail tweaks, and replaced them with mainrepo, which is more trusted, and frankly, in English
Re enabled all launch daemons in iCleaner

**Comment by SarKaa** [comment]
Just a point to note, as well as disabling the safe daemons and installing the cracked tweaks from a better repo, turns out the last time I restored, I forgot to install icon renamed from Ryan petrich, which might have had a difference

**Comment by Siguza** [comment]
So one way or another, this is caused by 3rd party software.
You can absolutely break your system by disabling certain daemons, starting with SpringBoard.  
And disabling tweaks in iCleaner is only helps so much. Many packages have installation scripts, and whatever those do isn't magically undone when you disable the tweak.

All in all, sounds like a trash pirate repo broke your OS. :|

**Comment by SarKaa** [comment]
> So one way or another, this is caused by 3rd party software.
> You can absolutely break your system by disabling certain daemons, starting with SpringBoard.
> And disabling tweaks in iCleaner is only helps so much. Many packages have installation scripts, and whatever those do isn't magically undone when you disable the tweak.
> 
> All in all, sounds like a trash pirate repo broke your OS. :|

Thanks for your help, really appreciated, but you can't blame the repo, because it can be one of three things
The repo
Icon renamer
Or disabling the wrong daemons in icleaner
But yes your right, it is most likely the repo

**Comment by SarKaa** [comment]
Hey help this issue came back, when I tried ldrestarting, my phone froze again

**Comment by SarKaa** [comment]
so it wasnt the repo that was the problem, but please help, This is the 5th time this has happened
PLease can you re-open the issue

**Comment by SarKaa** [comment]
Oh just a note, that I had re-installed the mario kart bypass recently, which was one of my suspects before, but still not sure what the problem could be

**Comment by SarKaa** [comment]
So what I am doing is installing my tweaks two by two, and then ldrestarting after every installation
Hopefully this can find the problem

**Comment by SarKaa** [comment]
I can confirm that the following tweaks work:
Activator
Floatingdockplus13
Nougat
Prysm
Frame
Milkyway2
assistability13
autotouch
snowboard (and lotus theme)
betternet++
bettersettings 
bioprotect XS 
browserdefault
ccmodules
dismissanywhere
compactor
flex 3 
flow
icleaner
localiapstore
mterminal
kalm
nolowpowerautolock
passby
powerloghelperdfix
scribble
scorpion
shuffle
shy page dots xs
smart network
smart battery
contact sync
system info
spotilife
statusbarxs
truthful folders
voicechanger xs
appsync unified
xeon (beta)
Strange, I just ldrestarted with all of these tweaks, and its normal
Something very weird is going on, as the ldrestart now works, and no tweaks are interfering
Does changing the hosts file make a device unbootable, because for the last 4 times I restored, i installed the preferences with batchomatic, but this time, I installed the hosts file as well, which might make a difference

**Comment by SarKaa** [comment]
Wait I found something
Turns out recently, I had renamed my root folder in /var to root_orig, and replaced it with a symlink to /var/mobile, because SSH always went to root when I wanted it to go to mobile
Could this have affected the boot procedure, because this happened at exactly the right time, and I didn't realise that was the problem, and kept doing it after restoring, and now that I haven't done it, I can ldrestart fine

**Comment by Siguza** [comment]
Look, I'm not your general help and support. Also stop writing me emails when you already have a ticket on here.

And yes, messing with the system like that will absolutely break things. If you wanna go to mobile, just why does it not occur to you to log in as mobile over SSH?!

As for the OS breaking, come on, you can debug that! Install a few tweaks, do an ldrestart, install a few more, do another one, etc. until your OS breaks. Then you can single out the cause.

I'm locking this though, because it's undeniably off-topic.
