### ISSUE TITLE
So has anyone succeeded in jailbreaking a 13.4.1 device? 

### ISSUE THREAD

**Issue by 0u0u0** [checkra1n/BugTracker#1355]
If so, what is your device model?

**Comment by Siguza** [comment]
Can personally confirm iPhone9,3 works.

**Comment by SarKaa** [comment]
Yes same here

> Can personally confirm iPhone9,3 works.

**Comment by luizaleixo** [comment]
I have an iPhone 8 plus that I can successfully run 3 sideloaded apps after checkrain 0.10.1 in 13.4.1 despite it does hang a while at the end of jailbreaking process. I don't have cydia ... nor checkrain loader... just the three apps are running flawlessly..

**Comment by 0u0u0** [comment]
Thank you for your feedback.
