### ISSUE TITLE
iPhone 7 jailbreak works but Cydia can't install packages

### ISSUE THREAD

**Issue by algonquinsnodgrass** [checkra1n/BugTracker#136]
**What device + iOS version are you on?**
iPhone 7 iOS 12.4

**What checkra1n version are you using?**
0.9, 0.9.1
**What are the steps to reproduce the issue?**
1. Jailbreak
2. Attempt to install package through Cydia
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**
Device was previously jailbroken by unc0ver, so tweaks are already installed but device behaves as if tweak injection is off. Cydia also gives an error when trying to install any package. Seems like Cydia has read only access to filesystem.
![IMG_0360](https://user-images.githubusercontent.com/57604395/68552521-8909d480-03dd-11ea-8fbf-b942c3c524aa.png)

**Comment by nullpixel** [comment]
checkra1n does not support jailbreaking on top of an already jailbroken device. To use things like Cydia, we recommend using your previous tool to unjailbreak.
