### ISSUE TITLE
Jailbroken but not help

### ISSUE THREAD

**Issue by FrogHoTT** [checkra1n/BugTracker#1360]
**Tell us about your setup:**
1. What iDevice are you using? 6s
2. On what version of iOS is it? 13.4.1
3. What version of checkra1n are you using? Newest version 
4. What is your host system (OS version? Hackintosh? VM? etc.)? Linux 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple

**What are the steps to reproduce the issue?**
1. App cake says I am jailbroken 
2. Reinstalled 
3.
...
![CF398A88-6B10-4D7B-9A46-B92D5DB1F598](https://user-images.githubusercontent.com/35989304/82137648-db81de80-97ce-11ea-877a-2615cad1f34d.png)

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by SarKaa** [comment]
Install appsync unified, otherwise it shouldn't make a difference to appcake

**Comment by FrogHoTT** [comment]
Already tired to from that link and nothing happened.. where can I get the ipa link

**Comment by Siguza** [comment]
Jesus Christ, that is not a checkra1n issue.
