### ISSUE TITLE
ggggg

### ISSUE THREAD

**Issue by nooh2030** [checkra1n/BugTracker#1361]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by hidekiyamamoto** [comment]
ISSUE TITLE : Home button not working aside from waking device screen.
What iDevice are you using? iPhone 6s
On what version of iOS is it? 13.4.1
What version of checkra1n are you using? 0.10.1
What is your host system (OS version? Hackintosh? VM? etc.)? Live linux
How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Usb cable is not an issue, it's stable and i could do it on ios 12.somethings just a while before upgrading.

What are the steps to reproduce the issue?
1. Complete and legit itunes restore 13.4.1 - after restore the home button works 100%. I COULD go on with setup, but let's say i dont - no wifi setup, no language setup - nothing.
2. Checkra1n with no problem ---> All Done
3. ssh works - tested - i know, seems like checkra1n is done with it BUT
3. ISSUE is now

What do you expect, and what is happening instead?
I would expect to be able to use the home button to preceed with the setup or other things, like bring up the "more network settings" menu.
Instead
The home button only works for waking the device up. The screen says, hit home button to setup, but nothing happen when i click the home button.

Does the issue also occur if you tick "Safe Mode" in the checkra1n options? Yes

More info : I tried to complete and legit itune restore and do it all again 4 times, the third with safe usb. - I was able to use checkra1n - no problem - with 12.3 or 12.something in this same device.

**Comment by mattp12** [comment]
amazing
