### ISSUE TITLE
Home button works only for waking device screen

### ISSUE THREAD

**Issue by hidekiyamamoto** [checkra1n/BugTracker#1362]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 6s
2. On what version of iOS is it? 13.4.1
3. What version of checkra1n are you using? 0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? Live Ubuntu linux 20
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A / 3rd Party - NO HUB

**What are the steps to reproduce the issue?**
1. Complete and legit itunes restore 13.4.1 - after restore the home button works 100%. I COULD go on with setup, but let's say i dont - no wifi setup, no language setup - nothing.
2. Checkra1n with no problem ---> All Done
3. ssh works - tested - i know, seems like checkra1n is done with it BUT
4. ISSUE IS NOW

**What do you expect, and what is happening instead?**
I would expect to be able to use the home button to preceed with the setup or other things, like bring up the "more network settings" menu.
Instead
The home button only works for waking the device up. The screen says, hit home button to setup, but nothing happen when i click the home button.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
I tried to complete and legit itune restore and do it all again 4 times, the third with safe usb. - I was able to use checkra1n - no problem - with 12.3 or 12.something in this same device few minutes before.

**Comment by SarKaa** [comment]
Restore again, but don't jailbreak, set up your phone, and then jailbreak

**Comment by hidekiyamamoto** [comment]
it's ok this way - thanks, could be helpful to write somewhere before the jb to ensure having the phone setup.
Thanks!!!
