### ISSUE TITLE
error code -77

### ISSUE THREAD

**Issue by justinsoon** [checkra1n/BugTracker#1366]
Hello, I am trying to jailbreak my ipad 6th gen. 13.4.1 I am getting USB error which I tried to switch out the cable. I also am getting error code -77

**Comment by justinsoon** [comment]
Error code -78 as well

**Comment by kanenas3** [comment]
Error code -78 for iPad Air 2 LTE. Tried both MacOS and Ra1nUSB

**Comment by Arthur2012** [comment]
> Hello, I am trying to jailbreak my ipad 6th gen. 13.4.1 I am getting USB error which I tried to switch out the cable. I also am getting error code -77

Error code -77 was resolved on my phone, see [https://github.com/checkra1n/BugTracker/issues/908](url)

**Comment by jacobecret** [comment]
Are you using a vm?

**Comment by jacobecret** [comment]
This happens occasionally if your lightning cable is loose in the phone dock connector. Make sure to put it on a stable surface and dont move it around as much as you can help it.

**Comment by justinsoon** [comment]
Solved. Had to restart checkra1n OS everytime it failed. Used a genuine apple cable. Disabled passcode on iPad.
