### ISSUE TITLE
Cydia won’t show the ‘Return to Cydia’ button. 

### ISSUE THREAD

**Issue by samoht9277** [checkra1n/BugTracker#137]
**What device + iOS version are you on?**
13.2.2

**What checkra1n version are you using?**
0.9.1

**What are the steps to reproduce the issue?**
1. add/delete any cydia repo 
2. when added/ deleted, it won’t show the return to cydia button 
3. instead, i had to press the cancel button and then, the repo actually adds/ deleted
...

**What do you expect, and what is happening instead?**

i expect that the return to cydia button appears once a repo is added/ deleted 

**Any other info, error logs, screenshots, ...?**
no, but i can tell when it stopped adding/ deleting the repo, because it stops saying that something is being downloaded.

**Comment by littlelailo** [comment]
Closing this because it's an issue related to cydia and not to checkra1n
