### ISSUE TITLE
Loader not showing up

### ISSUE THREAD

**Issue by lukasmwerner** [checkra1n/BugTracker#1370]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7 (Global)
2. On what version of iOS is it? 13.4.1
3. What version of checkra1n are you using? 0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? Macbook Air 2017 Catalina
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple 1st party USB cable

**What are the steps to reproduce the issue?**
1. Run jailbreak

**What do you expect, and what is happening instead?**
App not showing up on spring board.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
The app is on the phone, at /var/binpack/loader.app, ldrestart doesn't exist nor does open. and doing a uicache --all doesnt work.

**Comment by jacobecret** [comment]
okay, so. run checkra1n again. but dont put your phone in dfu, plug it into your computer make sure you run checkra1n in cli "checkra1n -c" and it should detect your phone, load the boot strap, and the app should show up. Let me know what happens.

**Comment by jacobecret** [comment]
also you might have to remove passcode, faceid, touchid. Find my iphone is also a common reason it doesnt work, you might also have to turn that off, you can reenable it after.

**Comment by lukasmwerner** [comment]
No go, the phone booted. After a few seconds it switched to the last springboard page but no app there.

**Comment by lukasmwerner** [comment]
Should i delete the app folder? I do have ssh access

**Comment by jacobecret** [comment]
> Should i delete the app folder? I do have ssh access

delete the app cache, and try again. You shouldnt be having this issue, this isnt a super common problem

**Comment by jacobecret** [comment]
you can also try running cli in verbose boot, "checkra1n -c -v"

**Comment by QcSamuel** [comment]
did you run uicache --all as root ?

**Comment by lukasmwerner** [comment]
I'll close the issue as there is another jailbreak available that seems to work.
