### ISSUE TITLE
iPad pro 10.5" unable to use after bypass iCloud

### ISSUE THREAD

**Issue by Small-potatos** [checkra1n/BugTracker#1371]
**Tell us about your setup:**
1. What iDevice are you using?
Ipad pro 10.5inch
2. On what version of iOS is it?
The OS is 13.4.1
3. What version of checkra1n are you using?
0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Mac catalina 10.15.4 (19E287)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
connecting using USB-A directly to mac book pro 15 inch late 2013

**What are the steps to reproduce the issue?**
1. CheckRa1n is successful
2. Home button does not respond
3. Power button works but when press and hold to shut down, the shutdown appears for less than 1 second and automatically disappears.
...

**What do you expect, and what is happening instead?**
I expect home button to work. Power button will function normally if press and hold to show shutdown option.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
I have not tick safe mode option in checkra1n option.

**Any other info, error logs, screenshots, ...?**
the power button when press and hold works if I take screen shot and press share with air drop. After restart, it enters the main home screen. When I try to press any of the apps, nothing responds. Home button does not work either.

**Comment by cderivan** [comment]
lol :D reset and do it again bro :D

**Comment by Siguza** [comment]
That's because Apple designed it that way.

**Comment by gaplan** [comment]
same Error to me

**Comment by Siguza** [comment]
See #1, at the bottom.
