### ISSUE TITLE
Is there a way to increase the timeout?

### ISSUE THREAD

**Issue by pendowski** [checkra1n/BugTracker#1372]
I tried GUI and terminal modes and they always end up with an error about timeout while uploading, even in Safe Mode.

The thing is that the screen on the iPhone says Booting and after 15-20 seconds it (re)boots, but at that point, the tool gave up with the timeout.

iPhone 8 Plus with iOS 13.4.1 but I think I had a similar problem with one of the previous jailbreaks, not sure what I did there, possibly were lucky with a shorter reboot or started with a clean(er) device.

**Comment by Siguza** [comment]
So, the timeout is 90 seconds, which should be by far enough for the device to boot.  
But there are multiple layers to this:

1. If the device has been previously jailbroken with the same version of checkra1n, the bootstrap should still be on the device, and everything should work as expected even if bootstrap upload fails.
2. Even if the GUI times out on bootstrap upload, it will actually still upload one to any device that connects at any point and is in "bootstrap receiving mode".
3. Currently a freshly booted device will be in USB restricted mode in most cases, which prevents bootstrap upload until the device is unlocked. The upcoming release changes this.

**Comment by Siguza** [comment]
Alright, checkra1n 0.10.2 is out. Marking this as fixed.

**Comment by bachelorbob** [comment]
Marking 'fixed' was premature.

I cannot get my iOS 13.5.1 re-jailbroken due to extremely long re-boot.  Checkra1n needs a checkbox option for 'Unlimited/No timeout'.
