### ISSUE TITLE
Unable to Jailbreak and Wifi gets disabled

### ISSUE THREAD

**Issue by madcable** [checkra1n/BugTracker#1373]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7
2. On what version of iOS is it? iOS 13.4.1
3. What version of checkra1n are you using? 0.10.1 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)? mac Catalina
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB

**What are the steps to reproduce the issue?**
1. I installed the 0.10.1 beta checkra1n. default "allow untested ios/ipados/tvos versions" and "Dark Blockchain" under options
2. Start > went to DFU mode. it completes within 2 minutes
3. Phone reboots wifi disabled.
...

**What do you expect, and what is happening instead?**
wifi disabled

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes tried with safe mode. wifi gets disabled.

**Any other info, error logs, screenshots, ...?**
Yes wifi disabled screenshot attached.
![JPEG_20200520_222322](https://user-images.githubusercontent.com/65670034/82463608-9f60bd80-9aef-11ea-97cc-bc1d9e7387a6.jpg)
reseted network settings
airplane mode
reboot phone. 
still disabled

**Comment by Spedemix** [comment]
For the broken wifi you could try the following:

Enable cellular and open one of your app store apps. After that wifi shoud work and you can close the cellular. Oh and ofc you'll need your main sim card for that.

**Comment by madcable** [comment]
> For the broken wifi you could try the following:
> 
> Enable cellular and open one of your app store apps. After that wifi shoud work and you can close the cellular. Oh and ofc you'll need your main sim card for that.

Dumb me why didn't I think of that.
Give me 8 hours. I'll test it out and update. Left the phone at home and I'm at work at the moment.

**Comment by madcable** [comment]
THANK YOU A MILLION! wifi works!
