### ISSUE TITLE
stuck on right before trigger

### ISSUE THREAD

**Issue by BiK-RuM** [checkra1n/BugTracker#1375]
**Tell us about your setup:**
1. What iDevice are you using?
...iphone 5s 
2. On what version of iOS is it?
....12.4.4
3. What version of checkra1n are you using?
....0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
....ubuntu linux
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
...USB-A Apple original

**What are the steps to reproduce the issue?**
1. try to jailbrak again

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by maxii26** [comment]
same here

**Comment by nergzd723** [comment]
See #1169
