### ISSUE TITLE
STUCK IN DFU MODE HELP

### ISSUE THREAD

**Issue by MrBufferfish** [checkra1n/BugTracker#1378]
**Tell us about your setup:**
1. What iDevice are you using? gen 5 ipad
2. On what version of iOS is it? 13.4.1
3. What version of checkra1n are you using? I used the bootra1n one
4. What is your host system (OS version? Hackintosh? VM? etc.)? Not shure
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? usnb

**What are the steps to reproduce the issue?**
1. Starting jailbreak and not letting go of the home button
2. 
3.
...

**What do you expect, and what is happening instead?**
IM STUCK IN DFU MODE

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Dont know becasue i cant access ipad

**Any other info, error logs, screenshots, ...?**

**Comment by ghost** [comment]
To get out of DFU mode you have to press and hold the home and power button at the same time for about 15 seconds or until it turn on.

**Comment by Siguza** [comment]
This isn't an issue with checkra1n.
