### ISSUE TITLE
Jailbreak bypass detection in kernel level.

### ISSUE THREAD

**Issue by pooyair** [checkra1n/BugTracker#1379]
First of all thank you for all great work. currently only one feature is missing with checkrain that is jailbreak bypass detection on kernel level enhancement. i apprecitate if you can add them to your firmware. i was looking to install streaks and streaks workout using appcake although it's installed but it can't be start up and it will closed on startup.
here are some tweaks although these works with most of the app but still they don't work with streaks and streaks workout app:
Shad0w
https://github.com/jjolano/shadow

KernBypass
https://github.com/akusio/KernBypass-Public

Liberty Lite

**Comment by demhademha** [comment]
Sorry, that won’t be walked on

**Comment by Siguza** [comment]
This is not planned, at least for the time being.  
We do plan to patch out kernel integrity checks in the future though, and allow 3rd parties to implement this (currently this could be done via a custom PongoOS module).
