### ISSUE TITLE
Error 21 and half dead chckra1n 0.10.1

### ISSUE THREAD

**Issue by Kingistel** [checkra1n/BugTracker#1380]
1. What iDevice are you using?
apple iphone 5s
2. On what version of iOS is it?
12.4.5
3. What version of checkra1n are you using?
0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
ubuntu 20.04 kde plasma
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
usb-a => lightning

**What are the steps to reproduce the issue?**
1. start jailbreak
2. enter recovery mode - dfu
3. error -21
4. crash

**What do you expect, and what is happening instead?**
I'm waiting for jailbreak, but I'm getting an error.
**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
No

Okay, now checkra1n just dies, where can I get version 0.9.8.2 for linux? She was working super.
![errora](https://user-images.githubusercontent.com/64025073/82676305-db5e6480-9c4e-11ea-8401-175afe82b58a.png)

**Comment by nergzd723** [comment]
See #1169
