### ISSUE TITLE
USB error      Error Code: -77)

### ISSUE THREAD

**Issue by Keth56** [checkra1n/BugTracker#1381]
iPhone 8 plus iOS 13.4.1

**Comment by yunusnass** [comment]
iPhone 7 plus iOS 13.4.1 same eror

**Comment by yunusnass** [comment]
pls help

**Comment by 4soobs** [comment]
> 
> 
> iPhone 8 plus iOS 13.4.1

How can anyone help you without any information whatsoever? Where is the steps you have tried, have you tried in safe mode, etc.? Delete this issue and create a new one with a template.

**Comment by Siguza** [comment]
Y'all haven't even specified your host OS or checkra1n version. Open a new ticket & fill out the template.
