### ISSUE TITLE
Whoops the device couldn't enter DFU mode

### ISSUE THREAD

**Issue by Nuke11Proof** [checkra1n/BugTracker#1382]
Yesterday I was receiving error -31 with my Apple TV 4 13.3

Today I cannot even do the simple part.... when im pressing MENU + PLAY / PAUSE the program hang up and receive couldn't enter in DFU mode...

Thanks

**Comment by liu-congcong** [comment]
the same issue on my iPad6.

**Comment by Siguza** [comment]
That's not an issue with checkra1n. If you're unable to enter DFU mode, then I'm afraid we can't help you.
