### ISSUE TITLE
iPad mini 2: Jailbreak + Bypass is successful and then nothing works

### ISSUE THREAD

**Issue by futurecardesigner** [checkra1n/BugTracker#1384]
**Tell us about your setup:**
1. What iDevice are you using?

2014 iPad mini 2, Cellular 32GB version (no SIM card)

2. On what version of iOS is it?

12.4.6

3. What version of checkra1n are you using?

The latest one, 0.10.1

4. What is your host system (OS version? Hackintosh? VM? etc.)?

2011 Mac mini on High Sierra 10.13.6

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

Apple Lightning Cable

**What are the steps to reproduce the issue?**
1. Checkra1n process leads to 'all done' screen
2. Open Checkm8; device is successfully bypassed and goes to inactive-home-button stage
3. Power off and power on device to get to jailbroken home screen
4. Checkra1n loader is on second page: it wll either appear as loader or checkra1n with the logo
5. I wait about 5 minutes (or no time at all, it doesn't matter) and the loader never opens. I click it and nothing happens

Note: For some reason, the only app that will open is Facetime. I have absolutely no clue why but I would really appreciate some help here as I am at my wit's end. I have tried safe mode, then safe mode with verbose boot, but nothing works.
...

**What do you expect, and what is happening instead?**
I expect the loader to open so that I can install Cydia .Nothing happens when i click the loader.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
 Yep.

**Any other info, error logs, screenshots, ...?**
See note above

**Comment by Siguza** [comment]
See bottom of #1.
