### ISSUE TITLE
 Not working with uncover five installed first 

### ISSUE THREAD

**Issue by eglacias** [checkra1n/BugTracker#1385]
iOS 12 4.1, iPhone 6s Plus, checkn1x Linux usb sticK over usb cable. pc boot for checkrain 0.10.2

latest version of uncover requires restore rootfs to run, but then check rain will do the jailbreak but is still in essentially safe mode without saying anything about it. I’m guessing there’s some different version of substrate or substitute used by uncover five. 

 I used to be able to install mobile substrate to kick it out of safe mode but it doesn’t work anymore

**Comment by eglacias** [comment]
Almost every single post above mine is spam. I guess it’s time to start a new forum?

I have verified that check rain only jailbreaks in safe mode if run after uncover 5. Uncover is using substitute, check rain is using substrate, and Cydia throws up an error  and will not let me switch.

**Comment by Siguza** [comment]
Just to clarify, are you trying to run checkra1n with the unc0ver bootstrap installed?

**Comment by eglacias** [comment]
I don’t even know what you mean by that.  Uncover is fully working and installed first as it used to be suggested, then I do have to restore root with uncover in order to get checkrain to work out of "safe" mode.  I will double check right now. Essentially neither substitute nor substrate will run with checkrain

**Comment by eglacias** [comment]
Just a triple verify  I tried again with the latest version of uncover : check rain uses substrate, uncover uses substitute. Uninstalling substitute uninstalls just about every tweak that I have on my phone.

I assume these two very popular jailbreaks will be mutually exclusive, which is terribly unfortunate considering they are both essential, one for on device, the other just in case I get unsigned while I am off-line ,

 During these times when someone is trying to destroy all of civilization, I do not want to have to go online which is necessary to restore route FS and reinstall check rain. I have two identical devices. One of them I keep on check rain so that no matter what happens I can use my phone as a piece of hardware which will start up jailbroken without having to “phone home“

**Comment by eglacias** [comment]
Since, being the author, you know what you’re talking about and I don’t (: , let me know if there’s anything I can do to test or to help. I have two identical 6splus  except for my main one is on 12.4.1 ( The other one on 12.4 I run with an older version of uncover which uses substrate, there all I have to do is reinstall substrate to kick check rain out of safe mode ) so I am willing to test anything you suggest!

**Comment by eglacias** [comment]
I’ve also always wondered why half of my control center icons disappear with check rain and show up again with uncover.  I guess I’ll have to put that in a new issue

**Comment by Siguza** [comment]
I'm sorry, mixing checkra1n and unc0ver is not supported.  
It may be possible to get things to work, but you'll have to do that yourself.
