### ISSUE TITLE
arm build is not updated for 0.10.2

### ISSUE THREAD

**Issue by peterlobster** [checkra1n/BugTracker#1386]
0.10.2 SHA256
![0.10.2 SHA256](https://user-images.githubusercontent.com/38382145/82763211-a436b180-9e0e-11ea-9e7b-7d4dba9babe5.png)
0.10.1 SHA256
![0.10.1](https://user-images.githubusercontent.com/38382145/82763213-a6007500-9e0e-11ea-9907-a4f5ee7fa389.png)
0.10.1 arm build was put under 0.10.2.

**Comment by Siguza** [comment]
Thanks for reporting this, I'll ping the people working on that end.  
In the meantime, here's a direct link to the correct build:

https://assets.checkra.in/downloads/linux/cli/arm/dde0ee4255403a427636bb76e09e409487f8be128af4b7d89fac78548bd5b35a/checkra1n

**Comment by Siguza** [comment]
Alright, should be fixed.
