### ISSUE TITLE
Error Code -20 iOS 13.5

### ISSUE THREAD

**Issue by jhn09** [checkra1n/BugTracker#1402]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 8 Plus
2. On what version of iOS is it?
13.5 I just updated it.
3. What version of checkra1n are you using?
0.10.2 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOS 10.13.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A

**What are the steps to reproduce the issue?**
1. Following the setup to the Jailbreak

**What do you expect, and what is happening instead?**
I expected the phone to be jailbroken. It worked on a previous version of iOS 13.4.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Safe Mode doesn't show up - still returns back to "normal" without jailbreak.

**Any other info, error logs, screenshots, ...?**

**Comment by demhademha** [comment]
How did you update to 13.5
1. Did you resore rootFS first
2. Did you use OTA or iTunes

**Comment by jhn09** [comment]
I used OTA.

**Comment by demhademha** [comment]
Did you restore rootFS first?

**Comment by jhn09** [comment]
No, was that required? If that messed with my ability to jailbreak I can
restore from my backup to before the jailbreak if that’s necessary.

**Comment by demhademha** [comment]
Yes

**Comment by jhn09** [comment]
Looks like it worked restoring my phone. So in case I need update my phone
again, what are the steps I need to take to make sure it doesn't happen
again?

**Comment by demhademha** [comment]
You need to restore rootFS first
Also that your done, I’d close the issue

**Comment by jhn09** [comment]
Thanks, will close it.
