### ISSUE TITLE
Jailbreak completes but does’t jailbreak

### ISSUE THREAD

**Issue by jghkhjguy** [checkra1n/BugTracker#1409]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
**What are the steps to reproduce the issue?**
1. Install kernel level jailbreak bypass
2. Reset all setting in settings 
3. Try to jailbreak
...

**What do you expect, and what is happening instead?**should boot into jailbreak but continues booting just without jailbreak

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?** yes

**Any other info, error logs, screenshots, ...?**

**Comment by k2zgkqb34o** [comment]
1.  iPhone 7 (A1660)
2.  iOS 13.5
3.  checkra1n 0.10.2
4. macos catalina 10.15.4
5. USB-A Apple cable
Installing checkra1n jailbreak by following instructions. At the end get "Done" message, then iphone reboot and stuck at "hello" screen. Also note - iphone has baseband issue and after jailbreak it start heat.

**Comment by demhademha** [comment]
Setup your device first

**Comment by k2zgkqb34o** [comment]
This is not possible because iPhone is not a GSM network and cannot be activated.

**Comment by demhademha** [comment]
We can’t do anything until your device is set up

**Comment by Siguza** [comment]
Device activation is unrelated to checkra1n. You can SSH into an unactivated device, but that's about it.
