### ISSUE TITLE
Gg

### ISSUE THREAD

**Issue by Mosas123** [checkra1n/BugTracker#141]

**Comment by natewarter** [comment]
Shut the fuck up and stop wasting the devs time. This is for bugs/ issues.

**Comment by Mosas123** [comment]
> Shut the fuck up and stop wasting the devs time. This is for bugs/ issues.

![488C7235-FF89-4840-8CA4-B3E3A712BBB2](https://user-images.githubusercontent.com/36996758/68553974-65ea1f80-03f3-11ea-9aac-0637abe3e143.png)
 
And u know wtf this means stupid hoe 

Free form

**Comment by natewarter** [comment]
Fucking towelheaded piece of shit

**Comment by Graphiar** [comment]
You’re a fucking moron. Please get off Github. Support will come when it comes. Leave the devs alone.
