### ISSUE TITLE
Feature suggestion: Allow running with multiple connected devices if the target device is alone on the usb controller

### ISSUE THREAD

**Issue by mailinglists35** [checkra1n/BugTracker#1411]
When two or more phones are connected, checkra1n refuses to proceed.

While I understand this makes sense because of dealing with the usb controller, there should be no restriction when the other devices are not connected to the same controller, so if the target phone is the sole Apple device connected to a particular usb controller, it should proceed.

Example:

````
# lsusb.py
[...]
usb8             1d6b:0002 09  2.00  480MBit/s 0mA 1IF  (ehci_hcd 0000:00:1d.7) hub
 8-3             05ac:12a0 00  2.00  480MBit/s 500mA 3IFs (Apple Inc. iPhone [udid number 1])
usb4             1d6b:0002 09  2.00  480MBit/s 0mA 1IF  (Linux 4.19.0-8-amd64 xhci-hcd xHCI Host Controller 0000:01:00.0) hub
 4-1             05ac:12a8 00  2.00  480MBit/s 500mA 3IFs (Apple Inc. iPhone [udid number 2])
````

this should not require disconnecting one phone since each is connected to distinct usb controllers: 0000:00:1d.7 and 0000:01:00.0:

````
# lspci -s 0000:01:00.0
01:00.0 USB controller: Renesas Technology Corp. uPD720202 USB 3.0 Host Controller (rev 02)
# lspci -s 0000:00:1d.7
00:1d.7 USB controller: Intel Corporation 82801I (ICH9 Family) USB2 EHCI Controller #1 (rev 02)
````

**Comment by Siguza** [comment]
The reason is unrelated to USB controllers, but simply the app not knowing which device to put into recovery.

You can use the CLI though (`-c`), then you won't be guided through DFU, but it supports an unlimited number of devices simultaneously.

**Comment by Siguza** [comment]
So yeah, gonna close this as rejected, see reason above.
