### ISSUE TITLE
Can't make bypass for iPad Air2 using the ticket

### ISSUE THREAD

**Issue by Dutches90** [checkra1n/BugTracker#1412]
**Tell us about your setup:**
1. What iDevice are you using?
iPad Air 2 Wi-Fi only A1566

2. On what version of iOS is it?

13.5
3. What version of checkra1n are you using?

0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
10.13.6 High Sierra

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Directly with original cable without ant adaptors

**What are the steps to reproduce the issue?**
1. Made backup with silver
2. Make Jailbreak
3. Run silver, click untethered bypass, steps 3 and 4. Before I checked the files are really present
...

**What do you expect, and what is happening instead?**
To bypass the idevice using the ticket or the other way

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
no, jailbreak comes with no error

**Any other info, error logs, screenshots, ...?**

**Comment by demhademha** [comment]
Take a look at the bottom of #1
