### ISSUE TITLE
No Restore System Option in Loader App

### ISSUE THREAD

**Issue by CyferNinja3006** [checkra1n/BugTracker#1414]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7 (iPhone 9,3)
2. On what version of iOS is it? 13.4.1
3. What version of checkra1n are you using? 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Xubuntu 20.04
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Genuine Apple USB A to Lightning

**What are the steps to reproduce the issue?**
1. Open Loader app

**What do you expect, and what is happening instead?**
There used to be a Restore system option, now its not there anymore

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Can't reproduce.

![IMG_0010](https://user-images.githubusercontent.com/1659374/83330814-0883c600-a292-11ea-8e43-6d02f0b46b18.png)

**Comment by Siguza** [comment]
(Sorry, didn't mean to close.)

But are you seeing an Option to install Cydia, or is it already installed?

**Comment by CyferNinja3006** [comment]
There was an option to install cydia, i have it installed

**Comment by Siguza** [comment]
Screenshot?

**Comment by CyferNinja3006** [comment]
I rebooted, im going to rejailbreak and see if it persists

**Comment by CyferNinja3006** [comment]
![IMG_8387 356](https://user-images.githubusercontent.com/58089281/83331122-061e6d80-a28c-11ea-8a48-d5dbb9b4da31.PNG)

**Comment by CyferNinja3006** [comment]
I have no tweaks or jailbreak apps installed, cydia crashes immediately (as if im not jailbroken) but the loader app opens normally

**Comment by Siguza** [comment]
Sounds like you already restored rootFS and SpringBoard just didn't update its cache. Can you connect via SSH and run the following?:

    uicache --all && killall backboardd

**Comment by CyferNinja3006** [comment]
How do i connect via ssh? With OpenSSH i just typed `ssh root@_ip address_` but im getting the error that the host is refusing to connect, ive checked that my ip hasnt changed as well

**Comment by Siguza** [comment]
`ssh -p 44 root@...`

**Comment by CyferNinja3006** [comment]
I dont think ssh is installed, still get the host refused to respond error

**Comment by CyferNinja3006** [comment]
Hey, i tapped install cydia in the loader app, i was then able to open cydia again, and in the loader app the restore system option returned. Thank you for your time and making this jailbreak :)
