### ISSUE TITLE
OTA Failed and Update failed using Reiboot

### ISSUE THREAD

**Issue by samuelnext** [checkra1n/BugTracker#1415]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 8 Plus GSM

2. On what version of iOS is it?
12.4 OTA update to 13.5 but failed

3. What version of checkra1n are you using?
0.10.2 beta

4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOS Catalina 10.15

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A Apple lightning cable

**What are the steps to reproduce the issue?**
1. 12.4 run OTA to 13.5, with around 2GB left, which then failed
2. Retry update on iTunes gives error 14
3. Retry on Reiboot gives error saying too few storage left
4. Do not want to run clean restore because it will wipe all data which was not backed up.
5. When boot up gives recovery mode, screen with connect to iTunes logo.

**What do you expect, and what is happening instead?**
I would like to know if a jailbreak in this state of system will help me get back my data / help me ssh into the phone and clone the data / help me install iOS in another way so it will resume functionable?

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by demhademha** [comment]
Backup data through iCloud

**Comment by samuelnext** [comment]
> Backup data through iCloud

Cannot get in the OS currently

**Comment by samuelnext** [comment]
The jail break gives error -12

**Comment by demhademha** [comment]
Have you bootlooped

**Comment by samuelnext** [comment]
It boot 

> Have you bootlooped

It show apple logo and then itunes logo then apple logo and itunes logo and apple logo then itunes logo (3 times) and then followed by a hard reboot. It did not get into the OS.

**Comment by demhademha** [comment]
You will need to restore

**Comment by demhademha** [comment]
Actually does safe mode fix the issue

**Comment by samuelnext** [comment]
> Actually does safe mode fix the issue

It does not. I do not want to restore as it will delete all data. I hope any expert here can help to see if I can update the OS manually.

Thank you.

**Comment by demhademha** [comment]
Hi, 
1. Try https://github.com/libimobiledevice/idevicerestore
2. You probably won’t get your data back, and as harsh as it sounds, you should have made a backup.

**Comment by samuelnext** [comment]
> Hi,
> 
> 1. Try https://github.com/libimobiledevice/idevicerestore
> 2. You probably won’t get your data back, and as harsh as it sounds, you should have made a backup.

Thank you for the help.
I thought the back up was up to date but surprisingly it was only up to Jan 2020 on icloud.
And that was only an OTA which runs in midnight...

Does the tool allow me to delete any file in the storage before?

I just need to get in and delete some useless file and then the update should work as usual.

**Comment by demhademha** [comment]
... 
you’ve probably corrupted something as iOS has checks for storage and your device won’t boot at all.

However, iCloud photos are automatically backed up separate from iCloud in case that is what you were wondering

**Comment by samuelnext** [comment]
> ...
> you’ve probably corrupted something as iOS has checks for storage and your device won’t boot at all.
> 
> However, iCloud photos are automatically backed up separate from iCloud in case that is what you were wondering

The icloud stopped since 2020 Jan due to storage full.

And if it is possible to delete some big files from the storage then the device may be able to do a proper update.

**Comment by samuelnext** [comment]
Seems not able ya?

**Comment by Siguza** [comment]
iOS is known to catch fire when running out of space, especially during an update. checkra1n can't fix that, I'm afraid.
