### ISSUE TITLE
checkra1n and iPhone XS

### ISSUE THREAD

**Issue by deadfish72** [checkra1n/BugTracker#1421]
does checkra1n not work on XS? Could I put a old IOS on it or is it never going to happen? 
Please let me know I'm super new to all this and my iPhone 6s took me 3 days! Also my iPod touch 5th gen won't work as well.
<img width="584" alt="Screen Shot 2020-05-31 at 10 20 08 AM" src="https://user-images.githubusercontent.com/54201638/83358462-9d390300-a328-11ea-9195-8f6c22238272.png">

**Comment by demhademha** [comment]
Please see #1

**Comment by Siguza** [comment]
XS can't be supported because it's not vulnerable to the bug.  
iPod 5g could be supported, but it'd be a huge pain & we value our sanity, plus it already had a JB on all versions.

**Comment by deadfish72** [comment]
Thank you so much for answering me! I thought it was possible and have been
driving my self insane. Lol!   The iPod touch has it available?

**Comment by Siguza** [comment]
The iPod 5g's last version is iOS 9.3.5, which you can jailbreak with this: https://phoenixpwn.com  
And in general, here's a list of all jailbreaks by version and device: https://www.theiphonewiki.com/wiki/Jailbreak
