### ISSUE TITLE
Error code -31 iOS 13.5 iPhone 7

### ISSUE THREAD

**Issue by Stardust-kyun** [checkra1n/BugTracker#1422]
Tell us about your setup:

What iDevice are you using?
iPhone 7
On what version of iOS is it?
iOS 13.5
What version of checkra1n are you using?
checkra1n 1.10.2
What is your host system (OS version? Hackintosh? VM? etc.)?
macOS 10.13.6
How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A
What are the steps to reproduce the issue? 1. 2. 3. ...
1. Start checkra1n
2. Put device into recovery mode
3. Put device into DFU mode
4. Error code -31 at "Right before trigger (this is the real bug setup)", checkra1n will either give out an error or crash
What do you expect, and what is happening instead?
I expected for it to jailbreak normally, but it gets stuck on "Right before trigger (this is the real bug setup)"
Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
Yes
Any other info, error logs, screenshots, ...?
I was able to jailbreak my phone on 13.5 before this but had to reboot it, and now I'm getting this error. This didn't occur until after I updated it and jailbroke once. It happened on 1.10.1, so I updated to 1.10.2 and it still happens.

**Comment by demhademha** [comment]
Try another wire

**Comment by Stardust-kyun** [comment]
I don't know how, but that worked! Thanks!
