### ISSUE TITLE
Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20) On iPhone X iOS 13.5. Checkra1n 10.2

### ISSUE THREAD

**Issue by iSamoi** [checkra1n/BugTracker#1437]
On what version of iOS is it?
13.5

What version of checkra1n are you using?
10.2

What is your host system (OS version? Hackintosh? VM? etc.)?
macOS Catalina os 10.15.5, MacBook white

How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A to MacBook USB-A port

What are the steps to reproduce the issue?

Entering DFU mood
Payload screen shows on iPhone
3.Booting process in Checkra1n GUI, apple logo on iPhone with the payload screen. Then error shows
...
What do you expect, and what is happening instead?
Reboot with Jailbroken Device, stuck in apple logo till i force reboot it.

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
Yes

Any other info, error logs, screenshots, ...?
After restarting my iPhone, I tried to re-inject the Checkr1an payload but it throws this error ( Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20) ). This error came up after most process is done, right after the payload injecting screen on the iPhone, and booting screen on my MacBook. Although this device was successfully jailbroken and I installed a few tweaks in it, but due to this error I can't access Cydia and remove the tweaks if they are what causing this issue
.

**Comment by Siguza** [comment]
Copy-paste of #1432.
