### ISSUE TITLE
PLEASE HELP CHECKRAIN INSTALLED I DOWNLOADED CYDIA BUT NOW THE CHECKRAIN LOADER IS GONE AND I CANT OPEN CYDIA

### ISSUE THREAD

**Issue by alvin710** [checkra1n/BugTracker#1441]
**Tell us about your setup:**
iphone ios 13.5.1 using linux checkrain 

**What do you expect, and what is happening instead?**
i thought that checkrain was going to be greate but cydia keeps on crashing

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
it also happens in safe mode

**Any other info, error logs, screenshots, ...?**
more detail about the title when i first jailbreak i got the checkrain app aka loader i installed cydia however 30 minutes later the checkrain app was gone and i coudnt open up cydia somebody please help me i also wiped my whole iphone and cydia was still there i tried getting a fresh LINUX x86_64 installer and it was stuck on the second to last part 
ANYBODY PLEASE

**Comment by nergzd723** [comment]
You need to restore your rootfs to remove Cydia's icon,

If Cydia is crashing at launch, try deleting Cydia's metadata.

Checkra1n loader appears after you jailbreak, try jailbreaking again. If Cydia is not starting, it means that you are not jailbroken. If checkra1n is stuck, try rebooting the PC or try different USB ports(it's better if they are from different USB host controller)

**Comment by lhaeger** [comment]
... and please DO NOT SHOUT AT US.
