### ISSUE TITLE
Can't Press Start

### ISSUE THREAD

**Issue by brevanbabbar** [checkra1n/BugTracker#1442]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone XS 
MacBook pro
2. On what version of iOS is it?
IOS 13.5.1
3. What version of checkra1n are you using?
0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
10.15.5 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
standard apple cable

**What are the steps to reproduce the issue?**
1. Check untested devices
2. press back
3. can't press start
...

**What do you expect, and what is happening instead?**
should be able to press start

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**
<img width="473" alt="Screen Shot 2020-06-05 at 10 12 29 AM" src="https://user-images.githubusercontent.com/45016760/83886526-2bd8c600-a715-11ea-81ad-a15b3da31fa7.png">
<img width="463" alt="Screen Shot 2020-06-05 at 10 12 34 AM" src="https://user-images.githubusercontent.com/45016760/83886530-2d09f300-a715-11ea-9863-ecf25b8d439f.png">

**Comment by nergzd723** [comment]
A12, A13 are not supported. See #1
