### ISSUE TITLE
Jailbreak done but no effect

### ISSUE THREAD

**Issue by gkul13** [checkra1n/BugTracker#1443]
**Tell us about your setup:**
1. What iDevice are you using? 
iPad Air
2. On what version of iOS is it? 
12.4.7
3. What version of checkra1n are you using?
0.9.7, 0.9.8, 0.9.8.2, 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Catalina 10.15.5
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-C

**What are the steps to reproduce the issue?**
1. Start Checkra1n
2. follow instructions
3. Jailbreak processed - done
...

**What do you expect, and what is happening instead?**
nothing happens - stays as it was

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**
depends on options errors -20, -31

**Comment by nergzd723** [comment]
See #1169

**Comment by Siguza** [comment]
@nergzd723 That's Linux-only.

@gkul13 It's not clear what's happening for you. Does the GUI tell you the jailbreak completed successfully? And your iPad doesn't boot up at all?

**Comment by gkul13** [comment]
@Siguza it was working fine, It updated today to 12.4.7 and now it says update completed - activation locked.
When I jaibreak it it comes back to that same screen.

**Comment by Siguza** [comment]
Did you bypass iCloud lock...?

**Comment by gkul13** [comment]
@Siguza no, I bought it working, just logged in to my account and used it for 2 years or so.
it doesn't say Icloud locked but Activation locked - this iPad was lost and erased.
I don't have details of that guy that sold it to me. is that mean I'm f*&3ed?

**Comment by nergzd723** [comment]
> @Siguza no, I bought it working, just logged in to my account and used it for 2 years or so.
> it doesn't say Icloud locked but Activation locked - this iPad was lost and erased.
> I don't have details of that guy that sold it to me. is that mean I'm f*&3ed?

Basically, yes.

**Comment by gkul13** [comment]
@nergzd723  so there's nothing I can do with it?

**Comment by demhademha** [comment]
If you set it up with your own Apple I’d at original setup, then it can’t be erased by someone else. Check you didn’t do it on accident.

**Comment by gkul13** [comment]
@demhademha I tried with my Apple ID, it says it's not the one.
I don't get it

**Comment by nergzd723** [comment]
> @nergzd723  so there's nothing I can do with it?

Short answer: no.
Long answer: try calling Apple, but probably no luck without the receipt.  And you can always google it!

Anyway, it looks like this issue is not related to checkra1n and should be closed.

**Comment by Siguza** [comment]
So what happens when you boot up unjailbroken? Can you activate the device? Then what happens if you reboot?

**Comment by gkul13** [comment]
@Siguza it always ends up on this ACTIVATION LOCKED screen

**Comment by Siguza** [comment]
So it's not a jailbreak issue then?

**Comment by nergzd723** [comment]
> @Siguza it always ends up on this ACTIVATION LOCKED screen

Fun fact: you can verify if it's jailbroken even on activation screen.

Install libusb using brew, then do `iproxy 4444 44`, and connect to your iPad through ssh like this `ssh -p 4444 root@localhost`. Checkra1n has sshd listening at port 44 by default. The default password is alpine.

edit: BTW how are you using USB-C lightning cable? AFAIK they cannot be used to enter DFU.

**Comment by Siguza** [comment]
Gonna close this, I guess.  
If your device is not activated, it's not activated. Not sure what you expected.
