### ISSUE TITLE
ICloud bypass and then installing Cydia problem

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#1444]
**Tell us about your setup:**
1. What iDevice are you using?
Iphone 6s+
2. On what version of iOS is it?
13.5
3. What version of checkra1n are you using?
10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-C(3rd party)

I jailbreak and bypass ICloud successfully, but then when I restart my phone it shows up Upgrade Complete and goes through activation again.
If i install Cydia with checkra1n, it goes in a forever loop on boot logo. I tried many methods and the only working one is by using SafeShutDown. Please, help me.

**Comment by Siguza** [comment]
See #1. iCloud bypass isn't supported.
