### ISSUE TITLE
ios 13.5.1 unsupported

### ISSUE THREAD

**Issue by yawina** [checkra1n/BugTracker#1448]
**Tell us about your setup:**
1. What iDevice are you using? Iphone 7 
2. On what version of iOS is it? 13.5.1
3. What version of checkra1n are you using? beta 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? OS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple USB cable 

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by demhademha** [comment]
In options, “allow untested versions” and you should be good

**Comment by Siguza** [comment]
I'll close this as a non-issue. We won't push an update just to bump the supported version number, but we will certainly do that next time we release an update.
