### ISSUE TITLE
Error Code: -20 // Timed out waiting for bootstrap upload

### ISSUE THREAD

**Issue by PatrickLaabs** [checkra1n/BugTracker#1449]
1. What iDevice are you using?
iPhone X

2. On what version of iOS is it?
Currently 13.5.1, but this issue also happened on 13.5

3. What version of checkra1n are you using?
0.10.2

4. What is your host system (OS version? Hackintosh? VM? etc.)?
Tried it on two Mac's:
1. iMac 27"; macOS Catalina 10.15.5 Beta (Jailbreaking my iPad with Version 13.4.x worked perfectly)
2. MacBook Pro 13" Touchbar; macOS Catalina 10.15.5

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Tried it with many different variations:
1. Different USB Ports on iMac with original Apple Cable (USB-A to Lightning)
2. USB Hub connected to my iMac
3. iPhone connected to MacBook Pro with USB-C to Lightning
4. iPhone connected to MacBook Pro with USB-C (and a USB-A Adapter attached to it) to Lightning

**What are the steps to reproduce the issue?**
1. Connect iPhone to iMac or MacBook
2. Use Apple USB-A to Lightning Cable (On Macbook with Adapter if Using USB-C)
3. Just Begin the Jailbreaking Process without any additional setups in the "options" menu
4. Put Device into Recovery and after that into DFU
5. Wait for magic to happen
6. But it get sucked at "Booting"; iPhone will boot up normally without jailbreak.

**What do you expect, and what is happening instead?**
I expected to have the checkra1n App on my iPhone (like it did on my iPad), but instead it just booted up normally without being jailbroken

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes, I tried almost any variation and nothing helped.

**Any other info, error logs, screenshots, ...?**
Just the information of Error Code: -20

**Comment by Aa0565781511** [comment]
Hi

**Comment by Hatzil** [comment]
I had the same problem, the only thing that managed to solve the problem is this -
1. Backup your iPhone through Finder/iTunes
2. Do a complete wipe either through the iPhone Settings or by restoring from an IPSW (works both ways)
3. Restore the backup you did earlier
4. Jailbreak
5. ???
6. profit

**Comment by m4nt1** [comment]
not sure if i should do your recommendation, take a look at my post if you will :)

**Comment by aaronbroskisir** [comment]
> I had the same problem, the only thing that managed to solve the problem is this -
> 
> 1. Backup your iPhone through Finder/iTunes
> 2. Do a complete wipe either through the iPhone Settings or by restoring from an IPSW (works both ways)
> 3. Restore the backup you did earlier
> 4. Jailbreak
> 5. ???
> 6. profit

I did what you said, having same issue as OP, but when I restore, apps like cydia, filza, etc show up where I had them and continuing the same problem. any help?
