### ISSUE TITLE
Cydia doesn't launch

### ISSUE THREAD

**Issue by streetbeds** [checkra1n/BugTracker#145]
**What device + iOS version are you on?**
iPhone 7, iOS 12.2.2

**What checkra1n version are you using?**
9.1
**What are the steps to reproduce the issue?**
1.Use checkra1n
2.Install Cydia from the checkra1n loader
3.Launch Cydia
4. Update tweaks
5.Cydia not launching anymore
...

**What do you expect, and what is happening instead?**
I expected that after updating a tweak, cydia will work again. It is not launching anymore.

**Any other info, error logs, screenshots, ...?**
It works when I restored my phone. But, sometimes cydia does not launch anymore

**Comment by ASILVAPT** [comment]
iPhone 8, iOS 13.2.2 same problem here.

When unnistall checkra1n the icon of Cydia on my apps.

**Comment by Shadowedstalker** [comment]
SSH into your phone ssh@rootyour ip go to Go to var/mobile/library/cydia/ and delete metadata.cb0. this will allow Cydia to open again. reinstall your tweaks.

**Comment by Shadowedstalker** [comment]
The icon remain until you ssh into your phone and rebuild the cache (uicache) or wait for the phone to do it on it's own.

**Comment by Shadowedstalker** [comment]
You can also try this! Open ignition.fun Install FilzaEscaped Go to var/mobile/library/cydia/metadata.cb0 and delete metadata.cb0 Open cydia, and boom! It's fixed This is much more easier if you don't know how to SSH into your phone.

Credit to Vlaampie

**Comment by littlelailo** [comment]
Closing this as this issue is related to cydia and not to checkra1n
