### ISSUE TITLE
Random Crash, Won't Run Tweaks

### ISSUE THREAD

**Issue by Dis3ntr0py** [checkra1n/BugTracker#1451]
**Tell us about your setup:**
1. iPhone 6s +
2. ios 13.3
3. Beta 0.9.7
4. I'm using Ra1nUSB which runs the macOS installer version 1 (771.4) 
5. Non apple brand lightning cable 

**What do you expect, and what is happening instead?** 
I woke up one morning and my phone had restarted thus losing the jailbreak, I boot everything up and jailbreak fine however no tweaks work. I can open cydia and all my jb apps like I'm in Checkra1n safe mode.  

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
If anybody knows a way to check what's going on please let me know and I can submit more data.

**Comment by demhademha** [comment]
Reinstall cydia substrate 
Also, update checkra1n

**Comment by Siguza** [comment]
I can only repeat what @demhademha wrote.

This sounds like the Substrate hook broke, so try reinstalling that.  
And your version of checkra1n is quite old, so...

**Comment by demhademha** [comment]
Hi @Siguza  this is quite easy to reproduce on v1.0.2

**Comment by Siguza** [comment]
@demhademha ok, how?

**Comment by demhademha** [comment]
My iPad 7 that uses just theos works fine, my iPad 6 that has tweaks installed that hook into apps have this issue, where every week or so, substrate needs reinstalling to allow hooking into apps, 
Coolstars libhooker works fine, so it’s probably substrate.

**Comment by Siguza** [comment]
Just gonna assume this is a tweak issue then and close it accordingly, until anything suggests otherwise.
