### ISSUE TITLE
iPhone X, Error code -20 on iOS 13.5 & checkra1n 0.10.2

### ISSUE THREAD

**Issue by Hatzil** [checkra1n/BugTracker#1454]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone X

2. On what version of iOS is it?
13.5

3. What version of checkra1n are you using?
0.10.2

4. What is your host system (OS version? Hackintosh? VM? etc.)?
15" MacBook Pro, Mid 2014 running Mojave 10.14.6

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple USB-A Cable, connected directly to the computer

**What are the steps to reproduce the issue?**
I did pretty much everything by the book (not my first time using checkra1n) and unfortunately I get stuck at the 'booting' phase with the following error:
"Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)"

Tried it also with safe mode checked and the same thing occurs.

**What do you expect, and what is happening instead?**
The iPhone boots up regularly without being jailbroken after failing with the -20 error code.

Just to make sure nothing was wrong with my hardware I tried jailbreaking the same device on another Mac with a different Apple USB-A cable and got the same error code.
I have a spare iPhone 7 running iOS 13.3 that was jailbroken successfully on both setups.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yep

**Comment by blaxahmoney** [comment]
I have the same exact issue on 13.4.1

**Comment by r3oo6** [comment]
> **Tell us about your setup:**
> 
> 1. What iDevice are you using?
>    iPhone X
> 2. On what version of iOS is it?
>    13.5
> 3. What version of checkra1n are you using?
>    0.10.2
> 4. What is your host system (OS version? Hackintosh? VM? etc.)?
>    15" MacBook Pro, Mid 2014 running Mojave 10.14.6
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
>    Apple USB-A Cable, connected directly to the computer
> 
> **What are the steps to reproduce the issue?**
> I did pretty much everything by the book (not my first time using checkra1n) and unfortunately I get stuck at the 'booting' phase with the following error:
> "Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)"
> 
> Tried it also with safe mode checked and the same thing occurs.
> 
> **What do you expect, and what is happening instead?**
> The iPhone boots up regularly without being jailbroken after failing with the -20 error code.
> 
> Just to make sure nothing was wrong with my hardware I tried jailbreaking the same device on another Mac with a different Apple USB-A cable and got the same error code.
> I have a spare iPhone 7 running iOS 13.3 that was jailbroken successfully on both setups.
> 
> **Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
> Yep

**Comment by Hatzil** [comment]
Well, the only thing that managed to solve the problem is this -
1. Backup your iPhone through Finder/iTunes
2. Do a complete wipe either through the iPhone Settings or by restoring from an IPSW (works both ways)
3. Restore the backup you did earlier
4. Jailbreak
5. ???
6. profit

**Comment by Siguza** [comment]
Marking this as duplicate of #1449, I guess...
