### ISSUE TITLE
FaceTime own camera bug 

### ISSUE THREAD

**Issue by MarcoSolorzanoZ-65** [checkra1n/BugTracker#1455]
When in checkra1n jailbreak in iOS 13.5 if you start a FaceTime call and you exit out the FaceTime call to another app and then come back your camera stays paused and you need to either restart the call or go to the bottom menu and disable camera off.

**Comment by Siguza** [comment]
1. This is the same behaviour as in non-jailbroken mode.
2. You can just tap the green status bar to resume.
