### ISSUE TITLE
"Install Cydia" not showing in Loader, just the "Cancel" button when you click Cydia

### ISSUE THREAD

**Issue by BreckenLusk** [checkra1n/BugTracker#146]
**What device + iOS version are you on?**
iPhone 7 Plus (iOS 13.2.2)

**What checkra1n version are you using?**
0.9.1 (Latest as of now)

**What are the steps to reproduce the issue?**
I'm not exactly sure how to reproduce the issue.

**What do you expect, and what is happening instead?**
I expect it to show an option to install Cydia.

**Any other info, error logs, screenshots, etc?**
I have run checkra1n many times and also restored through the loader app many times due to errors with Zebra and Cydia because none of the essential packages needed after jailbreaking are hosted on a central repository just for checkra1n, forcing me to experiment by mixing and matching packages from both the Sam Bingner's repositories as well as Coolstar's repository. I've even deleted Cydia.app via SSH and am still having this problem after reinstalling checkra1n, clearing uncache, and restoring roots from Loader, and even a complete restore through Finder.

**Comment by nullpixel** [comment]
Installing CSs repo ontop of our repo is not a supported configuration at all and can even cause bootloops.
