### ISSUE TITLE
Cant able to access DFU MODE

### ISSUE THREAD

**Issue by svturn** [checkra1n/BugTracker#1463]
**Tell us about your setup:**
1. What iDevice are you using? IPHONEX
2. On what version of iOS is it? 13.5.1
3. What version of checkra1n are you using? 10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB APPLE

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**
Stuck on apple logo and i was not able access to force dfu mode

**Comment by Siguza** [comment]
Sorry to hear, but it's not our fault if you can't enter DFU mode.  
Read #1 if you're using a USB-C cable.
