### ISSUE TITLE
the jailbreak was sucessful chekra1n loader worked and installed cydia but every time my device redboots chekra1n loader will disappear and cydia and all tweaks would stop working

### ISSUE THREAD

**Issue by U105** [checkra1n/BugTracker#1465]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 7
2. On what version of iOS is it?
13.5.1
3. What version of checkra1n are you using?
0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Hackintosh
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Through a USB hub

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**
I expected no issues but instead I get this problem

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes it still occurs even in safemode

**Any other info, error logs, screenshots, ...?**

**Comment by Hatzil** [comment]
This is not a bug, the checkra1n jailbreak is a semi-tethered jailbreak which means every time your devices reboots you need to jailbreak it again.

**Comment by U105** [comment]
ohhh I was misinformed then, I thought it was an untethered jailbreak. Well
thank you very much for responding.
