### ISSUE TITLE
Device fails to register audio devices connected via the lightning port in a jailbroken state

### ISSUE THREAD

**Issue by LorenzoPane** [checkra1n/BugTracker#1469]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone X, iPhone SE
2. On what version of iOS is it?
iOS 13.5.1, iOS 13.5.0, respectively
3. What version of checkra1n are you using?
Beta 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacBook Pro 10.15.3
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A to Lightning cable through an Aukey USB-C to USB-A adapter

**What are the steps to reproduce the issue?**
1. Verify lightning audio works in unjailbroken state
2. Freshly jailbreak (Nothing installed)
3. Plug in an audio device and attempt to play sound

**What do you expect, and what is happening instead?**
Audio is played through the device speakers, rather than the connected audio device

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
Not that I know of. Let me know if I can provide more help.

**Comment by Siguza** [comment]
Tried with both an iPhone SE on 13.3 and an iPhone 7 on 13.5, can't seem to reproduce the issue.  
What kind of audio device are you using? I was testing with a lightning-to-3.5mm dongle, but perhaps that's not enough?

**Comment by LorenzoPane** [comment]
Oddly enough, it seems to work pseudorandomly after each boot. I guess I got unlucky that both devices were experiencing it simultaneously.

**Comment by Siguza** [comment]
Well if you ever figure out how to reproduce it consistently, feel free to open a new issue. :/
