### ISSUE TITLE
Loader randomly shows a pop-up upon launching the app that says, "A server with the specified hostname could not be found."

### ISSUE THREAD

**Issue by BreckenLusk** [checkra1n/BugTracker#147]
**What device + iOS version are you on?**
iPhone 7 Plus (iOS 13.2.2)

**What checkra1n version are you using?**
0.9.1 (Latest)

**What are the steps to reproduce the issue?**
1. Open Loader (Doesn't happen all of the time.)

**What do you expect, and what is happening instead?**
I expect nothing to happen, but I am shown an error message that is out of context.

**Any other info, error logs, screenshots, ...?**
Nope. Its pretty self-explanatory.

**Comment by nullpixel** [comment]
Intermittent DNS issue because we recently changed the servers. Sorry about that.
