### ISSUE TITLE
ERROR CODE -20

### ISSUE THREAD

**Issue by westwax** [checkra1n/BugTracker#1475]
Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20.  I want to jailbreak iPhone X with password, got above error ,have tick safe mode got same error .HOW CAN I SOLVE PROBLEM?

**Comment by demhademha** [comment]
Fill out the full form 
Thanks

**Comment by westwax** [comment]
How can I fill out the full form?

**Comment by lantern9** [comment]
use iOS13.5.1 (Error code: -20）. I want to jailbreak iPhone X with password, got above error ,have tick safe mode got same error .HOW CAN I SOLVE PROBLEM?use iOS13.5.1

**Comment by westwax** [comment]
I don’t want to loose passcode phone as password, how can I restored without losing it boss?

**Comment by demhademha** [comment]
You can’t ...

**Comment by demhademha** [comment]
Use checkra1n to restore your passcode

**Comment by westwax** [comment]
How can I use checkra1n to restore password? Sorry for too many questions

**Comment by demhademha** [comment]
You cannot recover your passcode with checkra1n
