### ISSUE TITLE
(macOS) Info.plist not updated to 0.10.2

### ISSUE THREAD

**Issue by UnderEu** [checkra1n/BugTracker#1476]
**Tell us about your setup:**
1. What iDevice are you using? ---
2. On what version of iOS is it? ---
3. What version of checkra1n are you using? 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? macOS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? ---

**What are the steps to reproduce the issue?**
1. Check the app properties or Info.plist file

**What do you expect, and what is happening instead?**
Expected 0.10.2, currently showing 0.10.1

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
---

**Any other info, error logs, screenshots, ...?**
Need to update Info.plist file within checkra1n.app to reflect 0.10.2 update

![Screen Shot 2020-06-13 at 21 02 58](https://user-images.githubusercontent.com/16519758/84581600-60a1e880-adb9-11ea-93cc-cd1d4b71e8ef.png)

**Comment by demhademha** [comment]
Have a look at #1468

**Comment by Siguza** [comment]
Thanks for reporting, it was a configuration issue on our build server.  
It's been fixed, but we're not gonna re-release the 0.10.2 build.

**Comment by Siguza** [comment]
Gonna mark this as complete, 0.11.0 should have the correct version everywhere.
