### ISSUE TITLE
(Resolved) Tweaks not working/Respring Failure

### ISSUE THREAD

**Issue by laelin** [checkra1n/BugTracker#148]
**What device + iOS version are you on?**
iPhone 7 13.2.2

**What checkra1n version are you using?**
0.9.2
**What are the steps to reproduce the issue?**
1. Open cydia 
2. Install a tweak like jellyfish or another iOS 13 supported tweak. 
3. Cydia prompts to restart the springboard, press restart springboard.
4. black screen, no respring wheel.
... 

**What do you expect, and what is happening instead?**
After respringing, the tweak should be able to be found in settings, scrolling down. But no downloaded tweaks can be found there. Cydia says that the tweak was successfully installed by giving the green check mark and you have the option to remove it. But the tweak is otherwise untraceable to the user and doesn’t function at all. Tweaks that were attempted to be installed actually have preference that have been accessible through settings in passed jailbreaks like unc0ver.

**Any other info, error logs, screenshots, ...?**
After downloading and then choosing to respring, while in the respring process, the phone seems to abruptly return to the lock screen... I don't actually see the respring progress wheel, just a black screen after pressing restart springboard from Cydia.

**Comment by Swastik496** [comment]
Are you sure that the tweak supports iOS 13?

**Comment by laelin** [comment]
Yes I used this checkra1n compatibility checker (seems legit) https://docs.google.com/spreadsheets/d/1qce_nLb2WZfQ6ri8R3_BkUHMxEHMTbJK_6DnysgCiL8/htmlview?sle=true#gid=0  

and also tried Jellyfish by Dynastic, they say they’ve updated it for checkra1n and iOS 13. 

on 0.9.2 I've tried to install tweaks mentioned by icrackurdevice. All tries leading to the same result. I think somethings going on with respringing/ "tweak injection"...?..

**Comment by Yazxoi** [comment]
iPhone X iOS 13.2.2
Same issue

**Comment by IanLulz** [comment]
I'm on iPX (iOS 13.2.2) and I'm pretty sure I'm getting this same issue. I installed Jellyfish, which includes Substrate, PreferenceLoader, and Substrate Safe Mode, so these are the only packages I have (apart from packages that come with checkra1n). Jellyfish doesn't load after respring, but the settings pane is there. I'm on a completely fresh iOS (restore without backup) iPX as well.

**Comment by laelin** [comment]
@IanLulz So you see the Jellyfish preference page in settings? I cannot. No tweaks at all in settings.

**Comment by laelin** [comment]
FIXED! Open cydia, go to installed, user view, uninstall things for electra, like electra tweak injector, substitute, basically anything from coolstar repo (no offense). Make sure to keep Cydia Substrate by checkra1n. Tweaks work.

**Comment by laelin** [comment]
Tweak injector / substitute is deff the problem.
