### ISSUE TITLE
iPhone XS Max iOS 13.5.1 not supported

### ISSUE THREAD

**Issue by m4nt1** [checkra1n/BugTracker#1485]
**Tell us about your setup:**
1. What iDevice are you using?
IPhone XS max
2. On what version of iOS is it?
13.5.1
3. What version of checkra1n are you using?
0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOS Catalina 10.15.4
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A
**What are the steps to reproduce the issue?**
1.  download checkrain onto mac with iPhone plugged in computer
2. move checkrain into applications
3. open checkrain
4. error code pops up
...

**What do you expect, and what is happening instead?**
i expect to be able to jailbreak my device since the website says it supports my phone

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes, and i went back and checked each box individually to see if the error code would go away 

![Screen Shot 2020-06-16 at 2 40 29 AM](https://user-images.githubusercontent.com/66990749/84740364-41eb4f80-af7b-11ea-92e7-bf2c2e06ff1b.png)
![Screen Shot 2020-06-16 at 2 41 38 AM](https://user-images.githubusercontent.com/66990749/84740380-49aaf400-af7b-11ea-8006-439478c7c6f0.png)

**Comment by ghost** [comment]
I don't mean to be rude, but it clearly says that it supports iPhone 5S through **iPhone X**. The XS Max is a newer model, and so is not supported.

**Comment by Siguza** [comment]
See #1.
