### ISSUE TITLE
cydia update causing bootloop, unable to rejailbreak

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [checkra1n/BugTracker#1486]

**Comment by afwn90cj93201nixr2e1re** [comment]
**Tell us about your setup:**
1. What iDevice are you using? iphone 7
2. On what version of iOS is it? 13.5.1
3. What version of checkra1n are you using? latest, 0.10.2-beta
4. What is your host system (OS version? Hackintosh? VM? etc.)? 
```
 Download for Linux (CLI, x86_64)SHA256 607faa865e90e72834fce04468ae4f5119971b310ecf246128e3126db49e3d4f
```

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? any

**What are the steps to reproduce the issue?**
1. Install fresh ios
2. Append jailbreak
3. Run cydia, agree with updates (full updates)
4. install some package, for example filza file manager or smthng like that
5. Turn off device
6. Try to turn on or join to recovery mode and try to run checkra1n rejailbreak again

**What do you expect, and what is happening instead?**
Work as expected? Update dependencies or smthng like that.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes, seems like safe mode doesnt work AFTER REJAILBREAK, on 'Booting' action at all, btw there can be some stupid tweaks or something like that which can cause bootloop or stupid stuff like that, so, add one more option, ***Safe Mode (force)***

**Any other info, error logs, screenshots, ...?**
i dont have any

**Comment by afwn90cj93201nixr2e1re** [comment]
@Siguza

**Comment by demhademha** [comment]
... what are you trying to achieve

**Comment by Siguza** [comment]
If a tweak bootloops you, then it broke a part of the OS. You can't just "Safe Mode" that.

**Comment by hoomodo** [comment]
Asa

**Comment by afwn90cj93201nixr2e1re** [comment]
@Siguza did u read anything? Any tweak broke os? That's exactly impossible...

**Comment by Siguza** [comment]
@afwn90cj93201nixr2e1re you've never seen tweaks that replace system files then, huh?

**Comment by afwn90cj93201nixr2e1re** [comment]
em...
how it's realted to the problem? I installing any tweak, any, is filza file manager replacing any SYSTEM library? Or what? I don't think so, it's seems like a wrapper.

**Comment by Siguza** [comment]
Look, whatever problem is bootlooping you, it's not checkra1n and it's not Filza:

https://tmp.siguza.net/Recording.mp4

**Comment by afwn90cj93201nixr2e1re** [comment]
ok, at first thanks for timewasting for me.

Second, then how i can recognize what exactly bootlooping me if im doing same thing's as u?

**Comment by afwn90cj93201nixr2e1re** [comment]
ok, at first thanks for timewasting for me.

Second, then how i can recognize what exactly bootlooping me if im doing same thing's as u? I mean, how i should debug it/get logs and other stuff.

Also why we need verbose output in checkra1n if we can't dump logs to stdout for example, at least at cli mode.

P.s Im not using some stupid after jailbreak stuff like itunes fixes, or icloud bypasses, but getting bootloop on recovery mode, restarts and etc.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/checkra1n/BugTracker/issues/1349

**Comment by afwn90cj93201nixr2e1re** [comment]
@Siguza 

And i get more than 5 reports with same problem, updating Cydia causing bootloops on our device's.

**Comment by Siguza** [comment]
> Also why we need verbose output in checkra1n if we can't dump logs to stdout for example, at least at cli mode.

I don't get what you mean by this. Are you talking about `-v` or `-V`?

But alright, a few things that might help diagnose this:

1. It bootloops after the first reboot, and it bootloops no matter whether you're trying to boot in jailbroken or unjailbroken mode, right?
2. When you restore the OS, are your apps + data still there, or do you have to restore them from backup?
3. How much free space do you have left on disk?
4. Try to boot with verbose option (`-V` on CLI). With any luck, the issue will be logged to the screen (this would work far better with a DCSD cable, but I expect you have none of those?).

**Comment by afwn90cj93201nixr2e1re** [comment]
1. After first reboot with Cydia installation/update, idk what u mean "no jailbroking", so, when i jailbreaked, and tryna reboot it's not going thru bootloops, it's just loading as normal, but without jailbreak, yes, when im trying install cydia, and yhen rebooting (ots tethered, right? We loose jb on reboots), then i can't boot it again, also I can't rejailbreak it, coz it's just showing 77/78(i don't remember Which one, but one of them can ne fixed easy, i just restarting checkra1n) error on latest step (after ur custom os loading), and causing bootloops. 
2. Still there
3. ~100gb or smthng like that
4. Yes, I haven't ;(

I mean can we output ur os logs direvtoy to checkra1n on pc? Thru toonel or smthng like that.
