### ISSUE TITLE
Unsupported

### ISSUE THREAD

**Issue by amishpatadiya** [checkra1n/BugTracker#1488]
**Tell us about your setup:**
1. What iDevice are you using?
- iPad mini 2 wifi only
2. On what version of iOS is it?
- 12.4.7
3. What version of checkra1n are you using?
- 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
- MacOS Mojave 10.14.6 (18G3020)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
- USB-A
**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**
- It says "Error Report - Request for Permission
Unfortunately, an error has occured during installation of the jailbreak. With your permission, the error can be sent back to us so we can investigate this further. we only send the error code and the device's CPU type. No trackable or other personal information will be sent. Click Yes to send it or No to ignore it."

**Comment by mahi347** [comment]
👌👏🏿

**Comment by demhademha** [comment]
Your mac’s os version is too low

**Comment by Siguza** [comment]
Your issue is completely lacking an error description, as well as steps to reproduce.  
If it's the same as #1490, please move there. Otherwise comment with the above & I'll reopen it if appropriate.

**Comment by amishpatadiya** [comment]
Hi Team,

The issue has been resolved by trying after fress restoration of iPad...

Thanks,

--
Regards,
Amish Patadiya
--
