### ISSUE TITLE
Linux on iPhone 

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#1492]
What happened to Linux support on iPhone in the Q&A? Is Linux support no longer planned? If so why not? 

I personally know it would need to be a lot of work but if you guys manage to get Linux on iPhone working with a build like Ubuntu touch or something it would be gamechanging especially if it’s as easy as jailbreaking with Checkra1n. If money is a issue cause time is money I’m sure the community can put together a fund.

**Comment by Siguza** [comment]
Linux on the iPhone is a 3rd party project and can be found at: https://projectsandcastle.org/status
