### ISSUE TITLE
checkra1n violates the terms of the LGPL

### ISSUE THREAD

**Issue by shimtfu** [checkra1n/BugTracker#150]
`checkra1n_gui` links to the following symbols from [libimobiledevice](https://github.com/libimobiledevice/libimobiledevice/blob/74dfc6485b61c76775c332f0ae6c65a28bcced9c/include/libimobiledevice/libimobiledevice.h) and [libirecovery](https://github.com/libimobiledevice/libirecovery/blob/master/include/libirecovery.h):

    % nm /Applications/checkra1n.app/Contents/MacOS/checkra1n_gui | grep 'idevice\|irecv' 
                 U _idevice_event_subscribe
                 U _idevice_event_unsubscribe
                 U _idevice_free
                 U _idevice_new
                 U _irecv_close
                 U _irecv_device_event_subscribe
                 U _irecv_device_event_unsubscribe
                 U _irecv_devices_get_device_by_client
                 U _irecv_devices_get_device_by_product_type
                 U _irecv_get_mode
                 U _irecv_open_with_ecid
                 U _irecv_reboot
                 U _irecv_saveenv
                 U _irecv_setenv

libimobiledevice and libirecovery are licensed under the LGPL. Here is an excerpt from [libirecovery's license](https://github.com/libimobiledevice/libirecovery/blob/e542d279c1185048b9b61aebfb0d726bcb5bdec5/COPYING). Important sections are subscripted.

>6\. As an exception to the Sections above, you may also combine or
link a "work that uses the Library" with the Library to produce a
work containing portions of the Library, and distribute that work
under terms of your choice, provided that the terms permit
modification of the work for the customer's own use and reverse
engineering for debugging such modifications.

>**You must give prominent notice with each copy of the work that the
Library is used in it and that the Library and its use are covered by
this License.^[1]  You must supply a copy of this License.^[2]  If the work
during execution displays copyright notices, you must include the
copyright notice for the Library among them, as well as a reference
directing the user to the copy of this License.^[3]**

Neither the checkra1n app nor the website give credit to libimobiledevice/libirecovery, supply a copy of their licenses, or display their copyright notices ([1], [2], [3]).

~~Since libirecovery is statically linked into `checkra1n_gui`, checkra1n must also comply with [4] and [5]. Again, neither the checkra1n app nor the website provide the source code for libirecovery/any potential changes thereof ([4]) or provide source code/object code to recompile checkra1n according to [5].~~

**Comment by CoderSear** [comment]
Nikias is one of the main contributors to libimobiledevice and libirecovery and, according to the header copyright notices, maintains copyright to a large majority of the code. He's also a checkra1n developer. IANAL but if he wrote the code and he has a copyright to the project he wrote it for, then he can do what he wants with it.

**Comment by misyltoad** [comment]
If @nikias is not happy with @nikias' use of their code, then @nikias can take that up in a court of law with @nikias.

**Comment by shimtfu** [comment]
It's a violation of the other 36+ contributors' copyright: https://www.gnu.org/licenses/gpl-faq.html#Consider

>Consider this situation: 1) X releases V1 of a project under the GPL. 2) Y contributes to the development of V2 with changes and new code based on V1. 3) X wants to convert V2 to a non-GPL license. Does X need Y's permission?

>Yes. Y was required to release its version under the GNU GPL, as a consequence of basing it on X's version V1. Nothing required Y to agree to any other license for its code. Therefore, X must get Y's permission before releasing that code under another license.

Since Nikias isn't the sole author of libi{mobiledevice,recovery}, he/the checkra1n team still need to follow the terms of the license when using it

**Comment by misyltoad** [comment]
Well I'm sure this hopefully is a fairly straight-forward case of just dynamically linking to those libraries or (may be more difficult) relicensing those projects.

The real question is, why do you care? You haven't contributed to any of these projects and are causing pointless drama spamming threads and comments across Reddit about it.

**Comment by CoderSear** [comment]
That quote refers to the GPL. Both libraries are licensed under the LGPL, which is less restrictive.

**Comment by shimtfu** [comment]
@Joshua-Ashton I'm not a fan of proprietary tools violating the (L)GPL. It seems to be a recurring theme in the jailbreaking scene, which is why I bothered to check in the first place

@CoderSear That FAQ is about the GNU licenses in general. The only difference between the LGPL and the GPL is the linking exception, so the principle still applies

**Comment by misyltoad** [comment]
> I'm not a fan of proprietary tools violating the (L)GPL

Tell that to hardware vendors... 🐸🐸🐸🐸

**Comment by marcos1** [comment]
This guy is probably mad because his device(s) aren't supported or he can't get the tool to work. Sounds like a disgruntled person to me.

**Comment by shimtfu** [comment]
@Joshua-Ashton 🙄 don't get me started...

@marcos1 Not that it's relevant, but I have a supported iPhone on which checkra1n runs just fine. I have no ill will towards the checkra1n team, I just want developers to start respecting OSS licenses and I think one of the biggest jailbreaking tools to be released in years is a good place to start

**Comment by nullpixel** [comment]
libmobiledevice is dynamically linked, thanks for your concern about this issue however.

**Comment by kpwn** [comment]
For your future licensing trolling reference: 'U' as output to nm refers to a symbol which is not statically linked, and that has to be provided by an external dynamically linked library. And your '37' contributors claim is quite funny given there's probably two with enough code in libimobiledevice to actually claim copyright on it, and the only one who actually maintains the project to this date is part of this project. 
So, get lost.

EDIT:
To be very clear, my "get lost" can come off as aggressive, especially since @shimtfu comes off as acting in good faith here. I am unable to consider this a good-faith attempt since rather than reporting an issue and seeing how it evolved, he went straight to reddit to start up drama, so there is zero sympathy on my end.

**Comment by shimtfu** [comment]
@kpwn You're right, looks like I got ahead of myself. You still have to follow [1], [2], and [3] though -- 

a. There's no threshold for how much code you have to write to claim copyright (barring maybe a typo fix or something). The code written by contributors is owned by those contributors, and when its compiled into the library they can claim copyright on it.

b. Barring that, it looks like the first commit was authored by a Zach C and committed by a Matt C. Also, a Martin S has more contributions to libimobiledevice than Nikias does. All of them undoubtedly have a claim for copyright.

**Comment by nullpixel** [comment]
How do you teach contributions, because commits certainly don’t tell you anything

**Comment by shimtfu** [comment]
By commits, additions, and total changes. Either way, not really relevant, since it isn't a "biggest-contributor-take-all" scenario

**Comment by kpwn** [comment]
Hey, 
As of 0.9.2 we should be fully LGPL compliant. Please let me know if there's any other compliance issue we haven't spotted.

**Comment by mskiptr** [comment]
@kpwn Some platforms (e.g. [AUR](https://aur.archlinux.org/packages/checkra1n-cli)) have `checkra1n` packaged in a way which makes the GPLed `usbmuxd` a dependency, instead of the LGPLed `libusbmuxd`

Edit: Though idk why they put that as a dependency is at all, since the executable is statically linked.
Which, uhm… is an LGPL no-no. So the discussion above applies again.
