### ISSUE TITLE
Virual Machine Support?

### ISSUE THREAD

**Issue by C4rter10** [checkra1n/BugTracker#1500]
Will a linux/macOS virtual machine on windows work with checkra1n? Has anyone tried this?

**Comment by aspctt** [comment]
The VM would need direct access to the USB controller afaik. You could maybe get it to work with something like HAXM but without third-party help it won't work with a VM. I suggest you use bootra1n if you're on windows, that's what I do an it's pretty easy.

**Comment by Siguza** [comment]
The Windows USB stack does not by itself allow checkm8 to be executed - you need a custom kernel driver for that. In order for a VM to work on there, it would have to do USB passthrough, which, again, would require a kernel driver. I'm not aware of any VMs that do this on Windows.

Also note that there are currently no plans to officially support any VMs whatsoever - they just may or may not work.
