### ISSUE TITLE
Jailbreak on Iphone 8 Plus Bootlooped now

### ISSUE THREAD

**Issue by newstarter369** [checkra1n/BugTracker#1505]
**Tell us about your setup:**
1. What iDevice are you using?
Iphone 8 plus
2. On what version of iOS is it?
13.5.1
3. What version of checkra1n are you using?
0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Pc with linux
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Usb
**What are the steps to reproduce the issue?**
1. Restored iphone with Itunes
2. Jailbreaked it
3. Did some changes for Safe Shutdown
4. Then after i logged into apple store and downloaded Facebook, instagram and soundcloud
5. Then the adjusts page got locked into a white screen
6. After a while the whole phone got stuck on that screen and the only thing i could do is open the camera
7. After forced restart the iphone got into a Loop on the apple logo
8. I cant restore using itunes, neither find it on the linux app for jailbreak again
...

**What do you expect, and what is happening instead?**
I cant go into DFU mode, its entirely looped on apple logo screen, and it wont shutdown, just repeatly turn on 
Anyway i can bring the phone back to life? Even to restore and jailbreak again maybe?
Thanks.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
No

**Any other info, error logs, screenshots, ...?**
No

**Comment by newstarter369** [comment]
Ah also, i tested the safe shutdown a few times and was working ok! 
I think the problem came after installing the apps on the store!
Even if i couldnt go to the applestore would be great to have it jailbreaked and working again..

**Comment by Siguza** [comment]
After reading up on SafeShutdown, it seems ignoring all input is exactly what it's designed to do...

Also it's pretty much impossible that you can't go to DFU. As long as you're connected to USB power and are doing the button sequence correctly as the phone reboots, you will _always_ be able to enter DFU.

**Comment by newstarter369** [comment]
I got able to go to DFU, maybe i was missing the sequence to do it... and then jailbreaked again, now instead of staying logged into apple store after installed my most used apps, i logged out, and it have been working fine.
Thanks a lot for all involved!
All the best

**Comment by Siguza** [comment]
Alright, I'll close this then.
