### ISSUE TITLE
IPhone XR ISO 12.4 is not supported.

### ISSUE THREAD

**Issue by nosounds** [checkra1n/BugTracker#1507]
**Tell us about your setup:**
1. What iDevice are you using? iPhone XR
2. On what version of iOS is it? 12.4
3. What version of checkra1n are you using? 0.10.2 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)? Ubuntu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB A

**What are the steps to reproduce the issue?**
1. It just says that Iphone XR iso 12.4 is not supported, Is there a way around it?
2. 
3.
...

**What do you expect, and what is happening instead?**
I expected it to support iso 12.4

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
ECID 0x1e2c980ef1002e

**Comment by Siguza** [comment]
No, see #1.

**Comment by Scottkush** [comment]
Need help to fix iPhone xr ios 17.5 is not supported 
ECID:0x328ca3cd3002e checkra1n help please
