### ISSUE TITLE
Linux: error while loading shared libraries: libirecovery.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by fullonrager** [checkra1n/BugTracker#1508]
**Tell us about your setup:**
1. What version of checkra1n are you using? 0.10.2-1
2. What is your host system (OS version? Hackintosh? VM? etc.)? Manjaro Arch Linux

**What are the steps to reproduce the issue?**
1. Install checkra1n from the AUR.
2. Run `checkra1n` in a shell.

**What do you expect, and what is happening instead?**
Initially, I expected the checkra1n GUI to launch. After nothing happened, I ran `checkra1n` in a shell and got `checkra1n: error while loading shared libraries: libirecovery.so.3: cannot open shared object file: No such file or directory`.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
N/A

**Any other info, error logs, screenshots, ...?**
This issue seems to have happened before at Issue #776 and was fixed, but I am facing this error currently. It appears to be an issue with the libirecovery dependency.

The checkra1n-cli package from the AUR works just fine, it's only an issue with the main checkra1n package.

**Comment by Siguza** [comment]
Alright, I had a chat with Nikias.

First, please understand that both the checkra1n package and the libimobiledevice stack on AUR are not maintained by us, so you will have to pass this on to whoever is in charge of them there.

Now, it appears that the libimobiledevice packages (or at least libirecovery) was handled wrong on AUR. These libraries recently reached version 1.0.0, and completely broke backwards compatibility, including a renaming of the library. Thus, the right way to handle this would be to have an old package with pre-1.0.0 versions of the library, and a new package with versions 1.0.0 and later, and to configure them in such a way that both can be installed next to each other.  
I'm being told that Debian and Ubuntu have done it that way, but reading the [comments on AUR](https://aur.archlinux.org/packages/checkra1n/), it seems that this was not done there.

I'll mark this issue as invalid, as there's nothing we can do on our end to fix this.

**Comment by fennectech** [comment]
A temporary workarround 

```
cd /usr/lib
sudo ln -s libirecovery-1.0.so.3 libirecovery.so.3
sudo ln -s libirecovery-1.0.so.6 libirecovery.so.6
sudo ln -s libusbmuxd-2.0.so.6 libusbmuxd.so.6
```

This process creates the simlinks that checkra1n requires

**Comment by AndnixSH** [comment]
`sudo apt-get upgrade` solved the problem for me

**Comment by YoannMourot** [comment]
> `sudo apt-get upgrade` solved the problem for me
New to Linux :)
The Issue was on an older version of Checkra1n, by doing apt-get upgrade I think you just upgraded to the last version, that has not this issue.
You can also do "apt upgrade" now. (without omitting the sudo).

**Comment by YoannMourot** [comment]
> `sudo apt-get upgrade` solved the problem for me

The Issue was on an older version of Checkra1n, by doing apt-get upgrade I think you just upgraded to the last version, that has not this issue.
You can also do "apt upgrade" now. (without omitting the sudo).

**Comment by mrAsh4r** [comment]
`sudo apt install checkra1n=0.10.2 libirecovery3=1.0.0-1` finally solved problem
(IPhone 6)
`Distributor ID:	Linuxmint
Description:	Linux Mint 20.1
Release:	20.1
Codename:	ulyssa
❯ uname -a
Linux ASUS-mint 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by iosdec** [comment]
Couldn't find libirecovery3, but found libirecovery-1.0.3, installed and issue resolved

**Comment by K0K0SHA** [comment]
> A temporary workarround
> 
> ```
> cd /usr/lib
> sudo ln -s libirecovery-1.0.so.3 libirecovery.so.3
> sudo ln -s libirecovery-1.0.so.6 libirecovery.so.6
> sudo ln -s libusbmuxd-2.0.so.6 libusbmuxd.so.6
> ```
> 
> This process creates the simlinks that checkra1n requires

You can also change binary names by editing the makefile

**Comment by K0K0SHA** [comment]
I encountered this issue while attempting to run `idevicerestore` in an attempt to downgrade my IPhone 6S iOS from 15.5. I want my jailbreak back. This error is probably caused because the system doesn't know where to look for libirecovery.so.3. For example, on my system these libraries were all in /usr/local/lib and not in /usr/lib

So this issue is solved by showing the program where to load those libs. That can be done through makefile edit. Alternatively, you can figure out where the program looks for the libs, and copy your libs there. Either way. I'll post after I compile.
