### ISSUE TITLE
Jailbreak breaking after reboot

### ISSUE THREAD

**Issue by NaeIll** [checkra1n/BugTracker#1512]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7+
2. On what version of iOS is it? 13.3.1
3. What version of checkra1n are you using? 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? macOS Catalina
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Original iPhone Charger

**What are the steps to reproduce the issue?**
1. Reboot the device
2. The jailbreak will go away after the device is rebooted

**What do you expect, and what is happening instead?**
I expect the jailbreak to stay

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
nope

**Comment by Iphone-cracker** [comment]
Is there a way to jailbreak 13.5.1 yet lol

**Comment by GODLIKE5** [comment]
> Is there a way to jailbreak 13.5.1 yet lol

checkra1n does that...

**Comment by GODLIKE5** [comment]
Please close this as it is not a problem. It is a TETHERED jailbreak meaning it works the same as just like unc0ver and Chimera. only difference is that checkra1n is tethered not semi-tethered and the jailbreak will disappear after the device is rebooted until you re-jailbreak again.

**Comment by Siguza** [comment]
Yeah that's how a tethered jailbreak works.
