### ISSUE TITLE
Checkra1n does not install on iOS 14 dev beta 1

### ISSUE THREAD

**Issue by Dave1482** [checkra1n/BugTracker#1514]
**Tell us about your setup:**
1. What iDevice are you using? iPad 6
2. On what version of iOS is it? iPadOS 14.0 (18A5301v)
3. What version of checkra1n are you using? 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Ubuntu and macOS (both latest stable)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A

**What are the steps to reproduce the issue?**
1. Try jailbreaking while on iOS 14

**What do you expect, and what is happening instead?**
Bootstrap is supposed to be loaded, but this step seemed to crash and reboot

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
I think it automatically sent a bug report

**Comment by Siguza** [comment]
#1513
