### ISSUE TITLE
checkra1n can't open in macOS 11.0 Beta (20A4299v)

### ISSUE THREAD

**Issue by teelekkung** [checkra1n/BugTracker#1517]
**Tell us about your setup:**
1. iPhone se
2. 13.5
3. 0.10.2
4. macOS 11.0 Beta (20A4299v)
5. c to usb and usb to lightning

**What are the steps to reproduce the issue?**
1. update to macOS 11.0 beta
2. download new checkra1n
3.boom

**What do you expect, and what is happening instead?**
 expect to open but not
**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
no because I can't open checkra1n
**Any other info, error logs, screenshots, ...?**
no

**Comment by teelekkung** [comment]
cli and checkra1n terminal still work only app interface can't open

**Comment by JoelOsler** [comment]
Same, either the system is blocking it via name or identifier, or a dependency or framework for the gui is not available anymore.

**Comment by gabriel-1988** [comment]
He

**Comment by brenogbi** [comment]
You can follow these steps:
1. Open the applications folder
2. Right click on Checkra1n and "show package contents"
3. Open "Contents" and then "MacOS"
4. Run the file "Checkra1n"

The entire interface will appear in the terminal.
