### ISSUE TITLE
Checkra1n app not open under Big Sur

### ISSUE THREAD

**Issue by FightMan01** [checkra1n/BugTracker#1527]
**Tell us about your setup:**
1. What iDevice are you using? ~> iPhone 6s
2. On what version of iOS is it? ~> 14 beta 1
3. What version of checkra1n are you using? ~> 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? ~> Big Sur beta 1
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? ~> Through a USB hub

**What are the steps to reproduce the issue?**
1. Install Big Sur beta 1
2. Open checkra1n app

**What do you expect, and what is happening instead?**

The app will open.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

I can't open the app. Even, it does not appear on the dock.

**Any other info, error logs, screenshots, ...?**

Clean install of Big Sur.

Update: I can open the terminal version of it.

**Comment by Siguza** [comment]
#1517
