### ISSUE TITLE
Right before trigger returns to checking if device is ready

### ISSUE THREAD

**Issue by preferprivacy** [checkra1n/BugTracker#1538]
**Tell us about your setup:**
1. Iphone 7 GSM
2. 13.5.1 (17F80)
3. Version beta 0.10.2
4. Ubuntu 20 (On VMWare)
5. Actually don't know type, just default charging cable with lightning 

**What are the steps to reproduce the issue?**
1. Connected Iphone to PC
2. Entered DFU mode step by step
3. Let it sit
...

**What do you expect, and what is happening instead?**
I expect it to continue with the jailbreak, but it return to the first step, from "Checking right before trigger" to "Checking if device is ready"

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Didn't try yet.

**Any other info, error logs, screenshots, ...?**
No error logs, it just returns me to the first step

**Comment by preferprivacy** [comment]
UPD
In safe mode same issue

**Comment by demhademha** [comment]
Virtual machines are not supported 
See #1

**Comment by Siguza** [comment]
Yeah if your host is Windows, then there's no chance VMs will work. (And I'm assuming if it wasn't Windows, you'd run checkra1n natively.)
