### ISSUE TITLE
Iphone 5s stuck on booting and on this is the real bug setup

### ISSUE THREAD

**Issue by ObiKeahloa** [checkra1n/BugTracker#1539]
**Tell us about your setup:**
1. What iDevice are you using?
Iphone 5s
2. On what version of iOS is it?
IOS 12.4.7
3. What version of checkra1n are you using?
0.10.1,0.10.2,0.9.8,0.9.8.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Bootra1n,Ubuntu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Usb-a 2.0 and 3.0

**What are the steps to reproduce the issue?**
1. Start checkra1n like usual
2. the device will be stuck at this is the real bug setup than use the fix (removing the usb quickly and connecting it)
3.Then the device will go on and then get stuck at booting but you have to manually boot it but it will still give errors Error:71
...

**What do you expect, and what is happening instead?**
I really dont know why this is happening

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes it still happens

**Any other info, error logs, screenshots, ...?**
No nothing else

**Comment by Siguza** [comment]
Duplicate of #1169.

**Comment by ObiKeahloa** [comment]
I searched a little bit more and I was able to find the fix. You have to use any other Linux distribution other than Bootra1n. I used Linux Mint
