### ISSUE TITLE
Kernel panic (reboot) on shutdown 

### ISSUE THREAD

**Issue by yhnu** [checkra1n/BugTracker#154]
**What device + iOS version are you on?**

Iphone7 Plus 13.1.2
**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. jabbreak and install cydia
2. reboot
3. alway reboot at the apple log
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**
![IMG_20191111_121909](https://user-images.githubusercontent.com/23090916/68560786-b6a65a80-047d-11ea-9146-5fc6c9acc449.jpg)
![IMG_20191111_121911](https://user-images.githubusercontent.com/23090916/68560788-bf972c00-047d-11ea-9251-8e25ebef12a3.jpg)

**Comment by nullpixel** [comment]
Thanks, we’re aware of the underlying cause and just need to fix it.

**Comment by Siguza** [comment]
Should be fixed in checkra1n 0.10.1.
