### ISSUE TITLE
Checkra1n loader app not showing up

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#1546]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 5S
2. On what version of iOS is it? 12.4.7
3. What version of checkra1n are you using? beta 0.10.2 CLI
4. What is your host system (OS version? Hackintosh? VM? etc.)? Void Linux (bootra1n)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A, Apple lightning cable

**What are the steps to reproduce the issue?**
1. Plug in my iPhone
2. Put it in recovery mode and then DFU mode
3. Jailbreak it

**What do you expect, and what is happening instead?**
I expected the checkra1n loader app to show up on the home screen, but it didn't.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
I didn't try Safe Mode because I don't know what it does to my device.

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Safe Mode just skips Substrate or any other run-at-boot hooks.  
Also, are you able to launch other jailbroken apps like Cydia, or do they all appear to crash on launch?

On one of my 5s'es, the loader just takes like 5 min to show up because battery capacity is <80% and the device is underclocked to hell... but it _does_ show up. Could it be the same for you?

**Comment by ghost** [comment]
> Safe Mode just skips Substrate or any other run-at-boot hooks.  
> 
> Also, are you able to launch other jailbroken apps like Cydia, or do they all appear to crash on launch?
> 
> 
> 
> On one of my 5s'es, the loader just takes like 5 min to show up because battery capacity is <80% and the device is underclocked to hell... but it _does_ show up. Could it be the same for you?

It was my first time jailbreaking my phone, so I had to use the checkra1n loader to install Cydia.
It's been over a day and the loader still hasn't showed up yet.

**Comment by demhademha** [comment]
could you also try an official os such as ubuntu? 
thanks

**Comment by Siguza** [comment]
Oh wait, I totally missed the Linux part.  
Seeing that, I'm actually fairly confident your issue is the same as #1169, just in a variant that reboots the device back to stock iOS. :/

A7 are still broken on Linux, so uh... marking this as duplicate, I guess? :/
