### ISSUE TITLE
Freezing when folder is touched

### ISSUE THREAD

**Issue by nightriderrv** [checkra1n/BugTracker#155]
**What device + iOS version are you on?**
13.2

**What checkra1n version are you using?**
0.9.1

**What are the steps to reproduce the issue?**
1. On the home screen 
2. When a folder is touched the screen freezes 
3. After about 30sec it will respring and the screen will respond to scrolling until a folder is touched, single apps not in folders work fine.

**Comment by littlelailo** [comment]
Can you reproduce this with safe mode enabled? Because if not it's most likley caused by a tweak. If you can reproduce with safe mode active, please reopen the issue
