### ISSUE TITLE
iPhone X iOS 13.3b1 stuck on the checkra1n "booting..." screen

### ISSUE THREAD

**Issue by tryfontheo** [checkra1n/BugTracker#156]
Downloaded a few tweaks and was stuck in a respring loop, rebooted and now cannot get back into jailbroken mode. Went through ssh and tried to kick it into safe mode by killing springboard to no avail and also deleted the plists and dylibs of the recently downloaded tweaks, still being unable to boot. I saw other issues similar to my issue but not the same, as I never get to the actual apple logo, instead staying on the checkra1n screen until it reboots itself after 4-5 minutes and then the normal apple logo comes up and it boots into unjailbroken mode.

Was not having this issue before, I am led to believe that it is not an issue solely with 13.3

**Comment by endercypher** [comment]
Wait for a update. They are working on one that will allow you to boot into safe mode.

**Comment by nullpixel** [comment]
Please lookout for the update which will allow you to enter safe mode.

**Comment by n3oney** [comment]
this is not an issue in 13.3, I am on 13.2.2 and  I have the same issue after installing cercube.
