### ISSUE TITLE
Unable to jailbreak old iPhone SE

### ISSUE THREAD

**Issue by water-sucks** [checkra1n/BugTracker#1561]
**Tell us about your setup:**
1. What iDevice are you using? Old iPhone SE
2. On what version of iOS is it? 13.5.1
3. What version of checkra1n are you using? 10.2 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)? Void Linux
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple USB cable, no USB hub

**What are the steps to reproduce the issue?**
1. Plug in iPhone, run `usbmuxd -f -v` && `idevicepair pair` to detect iPhone
2. Select "Trust This Computer" on iPhone and enter password
3. Run checkra1n
...

**What do you expect, and what is happening instead?**
I expect to be able to run the jailbreak tool on my old iPhone SE, because it has a compatible processor (A9) and is before the iPhone X. However, checkra1n prevents me from proceeding and says "Sorry, iPhone SE is supported, but iOS 13.5.1 is not."

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
I infer it is because jailbreaking a new iPhone SE that is running 13.5.1 is not supported because it has an A13 processor, but since it is detected as an iPhone SE, maybe it could be preventing me from proceeding because it thinks it is a new, rather than an old, iPhone SE.

**Comment by Siguza** [comment]
Go into options and check "Allow untested iOS/iPadOS/tvOS versions".
