### ISSUE TITLE
Iphone 11 pro max

### ISSUE THREAD

**Issue by vishalPwc** [checkra1n/BugTracker#1564]
**Tell us about your setup:**
1. iphone 11 pro max
2. ios 13.5.1
3. beta 0.10.2
4. macOs 10.5.5
5. USB-A

**What are the steps to reproduce the issue?**
1. Connect phone to mac
2. run checkra1n app
3. Throws error "Not Supported"
...

**What do you expect, and what is happening instead?**
iphone 11 pro max should connect with checkra1n

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by ValkyrieViolet** [comment]
iPhone 11 is not supported
Literally says it in huge letters that it's from iPhone 5s up to iPhone X

**Comment by Siguza** [comment]
#1.
