### ISSUE TITLE
LOL MY PHONE IS BRICKED LOL  ERROR CODE -26 AND -21

### ISSUE THREAD

**Issue by Cheesegriller** [checkra1n/BugTracker#1566]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 8 GMS
2. On what version of iOS is it?
13.5.1
3. What version of checkra1n are you using?
0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Gentoo GNU/Linux
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB 2.0 to whatever the iPhone's port is
**What are the steps to reproduce the issue?**
1. Run checkra1n
2. Brick phone
3. ???
4. Profit

Actual steps:
1. Run checkra1n
2. Go into Recovery mode
3. Go into DFU Mode
4. Says failed to run maybe run as root (I RAN AS ROOT)
5. Phone bricked
6. Lie down
7. Try not to cry
8. Cry

**What do you expect, and what is happening instead?**
Expected: To have checkra1n
Got: Brick
I should test this on like a million more phones and maybe build a house.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
I cant because my phone is FUCKING BRICKED

**Any other info, error logs, screenshots, ...?** 
[here's a screenshot of my phone](https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Solid_black.svg/768px-Solid_black.svg.png)

**Comment by worf1337** [comment]
Are you sure it's not in DFU mode?

**Comment by SmanS723** [comment]
> Are you sure it's not in DFU mode?

If it was, how do I exit it.

**Comment by Cheesegriller** [comment]
nvm im retarded
