### ISSUE TITLE
After reinstall, checkra1n disappear, cydia is there but doesn't work. IOS 13.6

### ISSUE THREAD

**Issue by harmonium76** [checkra1n/BugTracker#1569]
**Tell us about your setup:** iPhone 7, IOS 13.6
1. What iDevice are you using? iPhone 7
2. On what version of iOS is it? IOS 13.6
3. What version of checkra1n are you using? 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?  Mac Pro 5,1 - OSX 10.13.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Through a USB hub

**What are the steps to reproduce the issue?**
1. I've installed checkra1n a few days ago (2 days) and everything went well, i've installed new sources and try some tweaks... to change icons
2. I install Snowboard and Anemone, but Anemone was not fully compatible... after respring....
3. I saw only cydia on the screen, checkra1n disappear and cydia doesn't work anymore. I've tried to reinstall checkra1n
3 times but no results, reboot took very long time (2 to 4 minutes). Cydia on the screen (doesn't work) and no checkra1n on screen.
...

**What do you expect, and what is happening instead?**
To remove cydia and do a clean reintall of checkra1n

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes. When i've installed at first, i've selected ¨Allow untested IOS versions¨

**Any other info, error logs, screenshots, ...?**

**Comment by HD421** [comment]
@harmonium76 Have you tried 0.10.2 checkra1n version?

**Comment by harmonium76** [comment]
> @harmonium76 Have you tried 0.10.2 checkra1n version?

Yes i've tried 0.10.1 and 0.10.2 same results

**Comment by harmonium76** [comment]
Yes i've tried 0.10.1 and 0.10.2 same results. I still have Cydia app on the screen but when try to launch the app, it just popup to open and it disappear. So... when i double hit the home button, i see cydia (white app) and when i try to clic the window, it disappear... When i try to download an app from the AppStore, they've telling me that my phone is jailbreaked.

**Comment by wjamesglover** [comment]
I had a similar issue.  I had to restore and update my iPhone via iTunes.  It installed a clean version of IOS 13.6 without the jailbreak.

**Comment by harmonium76** [comment]
wjamesglover Hi! Do you mean RESTORE from a backup or the RESTORE iPhone?

**Comment by wjamesglover** [comment]
I used DFU restore via iTunes to get a fresh copy of IOS 13.6 on my iPhone which completely removed and replaced the copy of IOS 13.6 that had caused the issue.  Once this was done I just did the normal set up you would do when setting up a new iPhone.  Once you sign in to you Apple account it will give you the option to restore from the last saved back up on ICloud.  Here’s a helpful video explaining the DFU restore processs:  [https://youtu.be/X4wbnjeEtkY](url)

**Comment by wjamesglover** [comment]
If above link doesn’t work just look up How to DFU Restore Your IPhone on YouTube.

**Comment by harmonium76** [comment]
I've done the DFU Restore, it doesn't change niet! My problem is i've made a backup but with the problem in it so i can not use the backup to have a clean install. Dum i am???

**Comment by harmonium76** [comment]
I restore and update my iPhone via iTunes, use my backup after and it worked.
Thanks for your time and good suggestions!
