### ISSUE TITLE
I'm trying to remove Cydia after checkra1n failed to install

### ISSUE THREAD

**Issue by harmonium76** [checkra1n/BugTracker#1571]
**Tell us about your setup:**
After installing checkra1n 0.10.2 a few days ago, everything was working well, i've installed a few new sources and tweaks, but one of the tweaks was not perfect fit (compatible), i had to reinstall checkra1n again, after install, reboot took a long time and no checkra1n on screen, cydia was on screen, it can open (white app) and it disappear in a fraction of a second, it's stay's open because when i double clic on the home button to choose an app, it's still there but when i select cydia, it disappear, i have remove cydia from the settings but the app is still on the springboard...
1. What iDevice are you using?
iPhone 7
2. On what version of iOS is it?
IOS 13.6
3. What version of checkra1n are you using?
v0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Mac Pro 5.1, OSX 10.13.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Through a USB hub

**What are the steps to reproduce the issue?**
1. After installing checkra1n 0.10.2 a few days ago, everything was working well, i've installed a few new sources and tweaks, but one of the tweaks was not perfect fit (compatible), i had to reinstall checkra1n again, after install, reboot took a long time and no checkra1n on screen, cydia was on screen, it can open (white app) and it disappear in a fraction of a second, it's stay's open because when i double clic on the home button to choose an app, it's still there but when i select cydia, it disappear, i have remove cydia from the settings but the app is still on the springboard...
When i try to download an app from the AppStore, they've telling me that my phone is jailbreaked.

...

**What do you expect, and what is happening instead?**
To remove cydia and do a clean install of checkra1n

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes, and i've tried checkra1n 0.10.2 and 0.10.1 same results.
When i've installed at first, i've selected ¨Allow untested IOS versions.

**Any other info, error logs, screenshots, ...?**

**Comment by demhademha** [comment]
Is there a checkra1n app on your phone?

**Comment by harmonium76** [comment]
No, there's no checkra1n on screen, in setting too.

**Comment by demhademha** [comment]
When you jailbreak, can you use iproxy to ssh in?

**Comment by harmonium76** [comment]
Is it possible to find a solution without using iProxy?

**Comment by demhademha** [comment]
Hi, it'd be useful to know wether iproxy works as you'd be able to use snappy to restore rootFS and get the checkra1n app back on your phone

**Comment by harmonium76** [comment]
Hi! Something has changed on my phone, i have made a DFU restore, and it looks like ¨i'm out of jailbreak¨cause i was able to get some app from the Apple AppStore, no message saying that my phone is jailbreaked. Now the usual Apple apps can not be removes like it should be. BUT CYDIA IS STILL THERE... not possible to remove... Then i open iMazing, from there i can't open File system, iMazing is telling me: Your device is jailbroken but iMazing cannot connect to ¨AFC2¨.

**Comment by worf1337** [comment]
You should probably wait until it's fully released for a new i(Pad)OS.

You have no idea how many bugs it may have

**Comment by harmonium76** [comment]
I restore and update my iPhone via iTunes, use my backup after and it worked.
Thanks for your time and good suggestions!

**Comment by demhademha** [comment]
Oh excellent, 
Now that your good, you might want to close this issue
