### ISSUE TITLE
What do you expect, and what is happening instead?  Does the issue also occur if you tick "Safe Mode" in the checkra1n options?  Any other info, error logs, screenshots, ...?

### ISSUE THREAD

**Issue by majid077** [checkra1n/BugTracker#1574]
What do you expect, and what is happening instead?

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?

Any other info, error logs, screenshots, ...?

**Comment by majid077** [comment]
What do you expect, and what is happening instead?

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?

Any other info, error logs, screenshots, ...?

**Comment by majid077** [comment]
What do you expect, and what is happening instead?

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?

Any other info, error logs, screenshots, ...?

**Comment by majid077** [comment]
What do you expect, and what is happening instead?

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?

Any other info, error logs, screenshots, ...?

**Comment by SupersAccount** [comment]
Stop spamming. The developers already have plenty to do with their lives, and spamming won't help them.

Please lock
