### ISSUE TITLE
GPS doesn´t work

### ISSUE THREAD

**Issue by xendetor** [checkra1n/BugTracker#1578]
**Tell us about your setup:**
1. What iDevice are you using? **Iphone X**
2. On what version of iOS is it? **13.4.1**
3. What version of checkra1n are you using? **the newest one**
4. What is your host system (OS version? Hackintosh? VM? etc.)? **Ubuntu**
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? **USB-A**

**What are the steps to reproduce the issue?**
**1. Turn on GPS
2. Open Google Maps
3.Locate doesn´t work**
...

**What do you expect, and what is happening instead?** **Locating my place**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?** **didn´t tested**

**Any other info, error logs, screenshots, ...?**

**Comment by worf1337** [comment]
It may be related to a bad tweak. Try using Safe Mode in checkra1n options, then try again.

If it's fixed, then it's a bad tweak.

Otherwise, it's an actual checkra1n issue (unlikely)

**Comment by xendetor** [comment]
I made an rootfs and the jailbreak again. Now everything´s working. Maybe there was a Tweak (maybe CCLocation) or somethin else.
Thank you for your advice
