### ISSUE TITLE
Apple Watch app is not loaded properly

### ISSUE THREAD

**Issue by singgi11** [checkra1n/BugTracker#158]
**What device + iOS version are you on?**
iPhone X (iOS 13.2.2)

**What checkra1n version are you using?**
checkra1n: 0.9.1 (No tweak installed, fresh jailbreak)

**What are the steps to reproduce the issue?**
1. Open Watch app
2. See both My Watch and Face Gallery section

**What do you expect, and what is happening instead?**
I expect the apple watch app to show watch faces along with my installed app, but in this case it won't show anything rather than the static setting interface like General, Display & Brightness, etc.

**Any other info, error logs, screenshots, ...?**
![IMG_1213](https://user-images.githubusercontent.com/20704064/68562605-629f7400-0485-11ea-9db2-53e0112277a8.JPG)
![IMG_1214](https://user-images.githubusercontent.com/20704064/68562607-629f7400-0485-11ea-97d5-c565330156ca.JPG)
![IMG_1215](https://user-images.githubusercontent.com/20704064/68562608-629f7400-0485-11ea-82ec-4bb6b5fed227.JPG)

**Comment by littlelailo** [comment]
Could you please provide a syslog dump

**Comment by singgi11** [comment]
> Could you please provide a syslog dump

how do you get the log?
I am using CrashReporter to find any recent error log, and I found nothing since the app doesn't crash, it just won't load watch faces and installed apps somehow. It works on unjailbroken state.

**Comment by wilwillyy** [comment]
Duplicated issue hire <a class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="520627049" data-permission-text="Issue title is private" data-hovercard-type="issue" data-hovercard-url="/checkra1n/BugTracker/issues/75/hovercard" href="https://github.com/checkra1n/BugTracker/issues/75" aria-label="#75, watchOS notifications don't work when in jailbroken state">#75</a>

**Comment by singgi11** [comment]
> Duplicated issue hire [#75](https://github.com/checkra1n/BugTracker/issues/75)

I thought it was a different case, closed.
