### ISSUE TITLE
Jailbreak for 13.6?

### ISSUE THREAD

**Issue by mrgreen3** [checkra1n/BugTracker#1581]
I am aware of the fact that 13.6 is not supported by checkra1n script currently. Have seen videos on people jailbreaking 13.6 but my attempts under linux have so far failed. Is there any news on a version for 13.6?

**Comment by Siguza** [comment]
Wdym by "failed"?

**Comment by worf1337** [comment]
> Wdym by "failed"?

I think he means that it says it's saying it's unsupported.



> I am aware of the fact that 13.6 is not supported by checkra1n script currently. Have seen videos on people jailbreaking 13.6 but my attempts under linux have so far failed. Is there any news on a version for 13.6?

If your issue is the one above the quote, you need to go to checkra1n options, and select "Allow untested iOS/iPadOS/tvOS versions.

**Comment by kodcih-xiCjam-2kegzo** [comment]
> I am aware of the fact that 13.6 is not supported by checkra1n script currently. Have seen videos on people jailbreaking 13.6 but my attempts under linux have so far failed. Is there any news on a version for 13.6?

**Comment by zavorka** [comment]
My 1st gen iPhone SE boots correctly (the app reports no errors) but the phone remains jailed.

**Comment by worf1337** [comment]
> My 1st gen iPhone SE boots correctly (the app reports no errors) but the phone remains jailed.

You should start a new issue about that

**Comment by Siguza** [comment]
I'm just gonna close this under the assumption that "Options > Allow untested versions" solves the issue.
