### ISSUE TITLE
Not Supported - iPhone 7 on iOS 13.5.1

### ISSUE THREAD

**Issue by the2merlin** [checkra1n/BugTracker#1582]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7
2. On what version of iOS is it? 13.5.1
3. What version of checkra1n are you using? 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Windows 10 (bootra1n)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB 3rd Party Lightning cable

**What are the steps to reproduce the issue?**
1. Launch into bootra1n with 0.10.2 checkra1n
2. Connect iPhone 7
3. Receive error message that iPhone 7 is supported but iOS 13.5.1 is not supported 
...

**What do you expect, and what is happening instead?**
Expected to use checkra1n with this configuration but it is not supported

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
iPhone 7 with iOS 13.5.1 - Not Supported? I am using bootra1n (0.10.2) on an iPhone 7 with iOS 13.5.1 and it is MDM screen locked. When I boot into checkra1n and connect the iPhone, checkra1n states that iPhone 7 is supported but that iOS 13.5.1 is not supported, and I cannot proceed forward. Is there anything I can do to get checkra1n to work in this situation?

**Comment by Siguza** [comment]
Options > Allow untested versions.
