### ISSUE TITLE
can jailbreak 13.6 ipad pro 3gen?

### ISSUE THREAD

**Issue by serbiaman** [checkra1n/BugTracker#1587]

**Comment by serbiaman** [comment]
it says that ipad pro gen3 is supported but jailbreak cannot be done?

**Comment by demhademha** [comment]
Options > allow untested version > follow the instructions

**Comment by serbiaman** [comment]
> Options > allow untested version > follow the instructions

I know about it but it won't say it's not supported...

**Comment by demhademha** [comment]
IPad Pro 3 has an A12 chip, which isn't supported by checkra1n, see #1

**Comment by serbiaman** [comment]
> IPad Pro 3 has an A12 chip, which isn't supported by checkra1n, see #1

Okk and thanks I hope it will be maybe soon :)

**Comment by Siguza** [comment]
Nope, never.
