### ISSUE TITLE
Jailbrake done?

### ISSUE THREAD

**Issue by billywtf** [checkra1n/BugTracker#1588]
**Tell us about your setup:**
1. What iDevice are you using?
+iPhone 7 plus 
2. On what version of iOS is it?
13.3.1.
3. What version of checkra1n are you using?
Latest version
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Im using Ubuntu and Windows
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB A
**What are the steps to reproduce the issue?**
1. First I Jailbrake the phone and it doesnt report any problem, Everything looks succesful (Ubuntu)
2. When I try to use iCloud bypass tool, the program says its not jailbraked (Windows 10)
3.
...

**What do you expect, and what is happening instead?**
I expected the Jailbrake to work Lmao

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes, I tried all options, I also tried in a iPhone 6s and it worked perfectly but not in this one, I also have to say that one day I opened it with chackra1n but i updated to the new version and since then even if I jailbreak it doesnt work, 

**Any other info, error logs, screenshots, ...?**
Thank you so much for all the work you put in this program you guys amazin!

**Comment by Siguza** [comment]
That's not an issue with checkra1n though.
