### ISSUE TITLE
After update to 13.6, iPhone SE remains jailed

### ISSUE THREAD

**Issue by zavorka** [checkra1n/BugTracker#1593]
> My 1st gen iPhone SE boots correctly (the app reports no errors) but the phone remains jailed.

You should start a new issue about that

_Originally posted by @SupersAccount in https://github.com/checkra1n/BugTracker/issues/1581#issuecomment-665312008_

I've been using checkra1n since 12.3, this is the first time I've encountered any problem with it. Tried both 0.10.1 and 0.10.2. The checkm8 boot screen shows up followed by the log (enabled by the `-v` option). The phone however remains in a jailed state.

**Comment by demhademha** [comment]
You were supposed to restore rootFS before you updated,
Anyways, I thin, an app should still appear (if its possible) so you can still restore rootFS rather than having to perform an iTunes erase...

**Comment by nikfam-4hIdqa-jyrzix** [comment]
G

**Comment by nikfam-4hIdqa-jyrzix** [comment]
G

**Comment by zavorka** [comment]
> You were supposed to restore rootFS before you updated,
> Anyways, I thin, an app should still appear (if its possible) so you can still restore rootFS rather than having to perform an iTunes erase...

Firmware restoration in iTunes has apparently resolved the issue for me. Thank you for the idea. It'd be nice if the need for rootfs restoration before an upgrade was mentioned on thee checkra1n website though.
