### ISSUE TITLE
Mega-popular bag (Right before trigger)

### ISSUE THREAD

**Issue by ViewHideName47** [checkra1n/BugTracker#1594]
**Tell us about your setup:** 
1. Iphone 5s 
2. 12.4.7 
3. last (0.10.2) 
4. I put the operating system on my laptop and try every time 
5. Usb lightning noname 

**What are the steps to reproduce the issue?** 
1. Start checkra1n in any operating system, in any way 
2. Take all the steps that the launcher asks 
3. VOUAL, we hit the frozen phrase "right before trigger" 
... 

**What do you expect, and what is happening instead?** 
I'm waiting for the apple and the console to appear on the phone, after switching on with a jailbreak. Instead, I get haemorrhoids that cannot be treated in any way, I have already tried 5-6 operating systems, tried different PCs and carriers, tried different cords, to no avail, it used to help to pull out a frozen phrase and insert the cable into the phone, now it does not help! I don’t already know what to do, I’m sitting waiting for the new version of checkra1n, please help the developers! 

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?** 
Yes 

**Any other info, error logs, screenshots, ...?** 
There is nothing, the screenshot is useless, there are a lot of videos on the Internet because this problem is 100 years old at lunchtime! I do not have a log error because it does not give out, tell me where he should put it, I will find it for you

**Comment by ViewHideName47** [comment]
up, please help me

**Comment by ViewHideName47** [comment]
AU

**Comment by worf1337** [comment]
#1169

**Comment by ViewHideName47** [comment]
Developers are real lazy, they are too lazy to release updates, so fuck you, I rewrote your fucking code and fixed this error, suck the fuck!
