### ISSUE TITLE
Apple blocks checkrain jailbreak?

### ISSUE THREAD

**Issue by caly8464** [checkra1n/BugTracker#1597]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 5s
2. On what version of iOS is it?
12.4.7
3. What version of checkra1n are you using?
0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOsx Mojave
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB original cable
**What are the steps to reproduce the issue?**
error -31
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
The same error

**Any other info, error logs, screenshots, ...?**
I downloaded and installed security package 2020-004 for Mojave since then I can't jailbreak my iPhone. Is there any solution?. Thanks.

**Comment by Siguza** [comment]
Can reproduce, we're going to look into it.  
As a workaround, I verified that at least the CLI works on Mojave.

**Comment by caly8464** [comment]
Ok, thanks. I'll try again.

**Comment by demhademha** [comment]
> Ok, thanks. I'll try again
Could you reopen this issue please?
