### ISSUE TITLE
Can't enter DFU Mode (iPhone 8)

### ISSUE THREAD

**Issue by KibSquib48** [checkra1n/BugTracker#16]
The instructions say to hold the power button for 6 seconds, but every time I do that it reboots

**Comment by fuomag9** [comment]
Had the same issue, I had to manually put my phone in DFU mode and use the CLI version instead of the gui

**Comment by steven30303** [comment]
Follow this guide https://youtu.be/a70jiFqMGX0?t=138

**Comment by KibSquib48** [comment]
That doesn't work, same problem. always reboots. It tells me to hold side button for too long

**Comment by Siguza** [comment]
Closing this as duplicate of #12
