### ISSUE TITLE
Rejailbreak causes panic upon SpringBoard

### ISSUE THREAD

**Issue by Naville** [checkra1n/BugTracker#1603]
**Tell us about your setup:**
1. What iDevice are you using? iPhone8 Plus MQ8D2CH/A
2. On what version of iOS is it? 13.4.1
3. What version of checkra1n are you using? 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? RMBP 10.15.3
5. How are you connecting to the device Official Cable with USB->TB3 Dongle

**What are the steps to reproduce the issue?**
N/A

**What do you expect, and what is happening instead?**

N/A
**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
NO. This time JB fails. Checkrain UI stucks in "Booting" while the device already shows SpringBoard in unjailbroken mode. Verbose mode shows loads of logs as you would expect

**Any other info, error logs, screenshots, ...?**

**Comment by Naville** [comment]
Edit:
In safe mode after stuck in Booting for like 2minutes I got the -20 error and tells me to enable safemode, which I already did

**Comment by demhademha** [comment]
Could you  get a crashlog of the panic from settings > privacy > analitics

**Comment by quiprr** [comment]
This sounds like a tweak issue to me. Try jailbreaking with volume up held during the boot process, and use iCleaner Pro to disable your tweaks.

**Comment by Naville** [comment]
@ItHertzSoGood I was thinking the same but I was under the impression that SafeMode should already disable extra tweaks?

**Comment by quiprr** [comment]
Volume up is an alternative way of getting into safe mode (I believe its a different kind of safe mode but am not sure)
