### ISSUE TITLE
 USBMUX ERROR

### ISSUE THREAD

**Issue by Giddyspurz** [checkra1n/BugTracker#1606]
**Tell us about your setup:**

1. What iDevice are you using?
Iphone 6 [Wi-Fi + Cellular] //Activation Locked

2. On what version of iOS is it?
iOS 12.1.2

3. What version of checkra1n are you using?
checkra1n-Version beta 0.10.2

4. What is your host system (OS version? Hackintosh? VM? etc.)?
Host running Kali Linux 

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple Charger > USB 3.O port 

**What are the steps to reproduce the issue?**
-Opened terminal, used command: chmod +x
-Used command: sudo
-Put device in recovery mode and pressed start
-Did all the steps given
-Shows 'booting' thereafter usbmux error 79

**What do you expect, and what is happening instead?**
Expected the device to complete the jailbreak successfully but instead am getting USBMUX Error -79

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yess

**Any other info, error logs, screenshots, ...?**
[WhatsApp Image 2020-08-06 at 21 52 11(1)](https://user-images.githubusercontent.com/50057312/89714674-07b19380-d9a9-11ea-8933-daeff0de09c1.jpeg)

**Comment by Siguza** [comment]
iOS 12.1.2 is not supported.
