### ISSUE TITLE
app store could not sign in

### ISSUE THREAD

**Issue by MirzaAftabBaig** [checkra1n/BugTracker#1607]
![8CFF4B06-C295-4C65-9F71-5256C5B4E512](https://user-images.githubusercontent.com/46647573/89737826-a3b4cb00-da8d-11ea-8a15-677e08a99d4e.png)
![A80F37EB-B4C7-49A5-8B57-E78DBF97CD93](https://user-images.githubusercontent.com/46647573/89737829-aa434280-da8d-11ea-9628-99d16f968dbb.png)

**Tell us about your setup:**
1. What iDevice are you using? iphone 7 plus
2. On what version of iOS is it? 13.3.1
3. What version of checkra1n are you using? 1.0.1 (1)
4. What is your host system (OS version? Hackintosh? VM? etc.)? don't know 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. i delete some files. using filza (plist etc i don't know)
2. and i check my app store id removed and not sign in again
3. and not sign in again
![3ED263E3-22DA-461C-B182-C4356EC9BF12](https://user-images.githubusercontent.com/46647573/89737203-9fd27a00-da88-11ea-8890-7bf4839b7602.png)

...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
That's the way Apple designed it, so it's working as intended.
