### ISSUE TITLE
stuck in dfu mode

### ISSUE THREAD

**Issue by elioroh** [checkra1n/BugTracker#1609]
1. What iDevice are you using?

Im using a iPhone 8.

2. On what version of iOS is it?

Its on iOS 13.6

3. What version of checkra1n are you using?

im using 0.10.2

4. What is your host system (OS version? Hackintosh? VM? etc.)?

im on macOS

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

i'm using an adapter to plug into my Mac( its not the adapters fault because I've jailbroken my phone before with the adapter and it worked fine before)

**What are the steps to reproduce the issue?**
1. I would open up checkrein and plug my phone in
2. I was on the steps where I had to hold the buttons
3.i pressed the start button on checkrein while my phone was on its home screen, im guessing this is where it started because it didn't turn on
...

**What do you expect, and what is happening instead?**
I just expected the checkrein logo to boot up my iPhone, but instead it is still turned off.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**
ive tried using stuff like Reiboot, it says im in dfu mode and to fix it I have to pay like 30 bucks.

**Comment by elioroh** [comment]
note: my phone will not turn on so im not sure what to do

**Comment by Siguza** [comment]
Literally just reboot your device.

https://support.apple.com/en-us/HT201412

> iPhone 8 or later: Press and quickly release the Volume Up button. Press and quickly release the Volume Down button. Then press and hold the Side button until you see the Apple logo.
