### ISSUE TITLE
Can't jailbrake iPhone 6s Plus 13.4.1

### ISSUE THREAD

**Issue by Zekoslavmrkvica** [checkra1n/BugTracker#1610]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 6s Plus
2. On what version of iOS is it?
13.4.1
3. What version of checkra1n are you using?
10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacMini 10.11.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
3rd party cable

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**
I expect to jailbrake my iCloud locked iPhone

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
YES

**Any other info, error logs, screenshots, ...?**
After "jailbrake" checkra1n shows Normal mode and my home button does not work / can not shut down iPhone

Log file:

10.08.2020. 21:14:26,311 com.apple.usbmuxd[85]: error     Log from 51-c76146186825f3d20c3e2dc1c5fae9e61b9c3574@0x24300000: socketIsClosed sock_receive returned errno 54
10.08.2020. 21:14:26,311 usbmuxd[85]: _AMDeviceInsecureNotificationCallback (thread 0x700000094000): Received insecure notification AMDNotificationFaceplant
10.08.2020. 21:14:29,520 com.apple.usbmuxd[85]: notice    MuxReceivedUSBData device disconnected: 51-c76146186825f3d20c3e2dc1c5fae9e61b9c3574@0x24300000
10.08.2020. 21:14:29,521 MobileDeviceUpdater[5606]: Entered:_AMMuxedDeviceDisconnected, mux-device:51
10.08.2020. 21:14:29,521 MobileDeviceUpdater[5606]: Entered:__thr_AMMuxedDeviceDisconnected, mux-device:51
10.08.2020. 21:14:29,521 MobileDeviceUpdater[5606]: tid:b5c7 - BootedOS mode device disconnected
10.08.2020. 21:14:29,624 com.apple.usbmuxd[85]: error     DeviceRequestAsync @0x24300000 failed: kIOReturnNoDevice: no such device
10.08.2020. 21:14:33,666 MobileDeviceUpdater[5606]: Received an XPC event indicating device attach: Recovery Device v2 was attached
10.08.2020. 21:14:33,671 MobileDeviceUpdater[5606]: Entered:_AMRecoveryDeviceConnected, libusbrestore-device:0xF942CD80
10.08.2020. 21:14:33,671 MobileDeviceUpdater[5606]: Entered:__thr_AMRecoveryDeviceConnected, libusbrestore-device:0xF942CD80
10.08.2020. 21:14:33,672 MobileDeviceUpdater[5606]: Discovered a device. Asking if the device is restorable.
10.08.2020. 21:14:33,672 MobileDeviceUpdater[5606]: Known, supported, and restorable device. Continuing...
10.08.2020. 21:14:43,305 MobileDeviceUpdater[5606]: Entered:_AMRecoveryDeviceDisconnected, libusbrestore-device:0xF942CD80
10.08.2020. 21:14:43,305 MobileDeviceUpdater[5606]: Entered:__thr_AMRecoveryDeviceDisconnected, libusbrestore-device:0xF942CD80
10.08.2020. 21:14:43,305 MobileDeviceUpdater[5606]: tid:b77f - Recovery mode device disconnected
10.08.2020. 21:14:52,016 MobileDeviceUpdater[5606]: Received an XPC event indicating device attach: DFU Device v2 was attached
10.08.2020. 21:14:52,021 MobileDeviceUpdater[5606]: Entered:_AMDFUDeviceConnected, libusbrestore-device:0xF942CD80
10.08.2020. 21:14:52,021 MobileDeviceUpdater[5606]: Discovered a device. Asking if the device is restorable.
10.08.2020. 21:14:52,021 MobileDeviceUpdater[5606]: Known, supported, and restorable device. Continuing...
10.08.2020. 21:14:54,000 kernel[0]: 051655.923006 Apple Mobile Device (DFU Mode)@24300000: AppleUSBDevice::ResetDevice: <software attempt to RESET>
10.08.2020. 21:14:54,710 MobileDeviceUpdater[5606]: Entered:_AMDFUDeviceDisconnected, libusbrestore-device:0xF942CD80
10.08.2020. 21:14:54,710 MobileDeviceUpdater[5606]: Received an XPC event indicating device attach: DFU Device v2 was attached
10.08.2020. 21:14:54,710 MobileDeviceUpdater[5606]: Entered:__thr_AMDFUDeviceDisconnected, libusbrestore-device:0xF942CD80
10.08.2020. 21:14:54,711 MobileDeviceUpdater[5606]: tid:b77f - DFU mode device disconnected
10.08.2020. 21:14:54,740 MobileDeviceUpdater[5606]: Entered:_AMDFUDeviceConnected, libusbrestore-device:0xF958EEF0
10.08.2020. 21:14:54,741 MobileDeviceUpdater[5606]: Discovered a device. Asking if the device is restorable.
10.08.2020. 21:14:54,741 MobileDeviceUpdater[5606]: Known, supported, and restorable device. Continuing...
10.08.2020. 21:14:55,047 MobileDeviceUpdater[5606]: Entered:_AMDFUDeviceDisconnected, libusbrestore-device:0xF958EEF0
10.08.2020. 21:14:55,047 MobileDeviceUpdater[5606]: Entered:__thr_AMDFUDeviceDisconnected, libusbrestore-device:0xF958EEF0
10.08.2020. 21:14:55,047 MobileDeviceUpdater[5606]: tid:b77f - DFU mode device disconnected
10.08.2020. 21:14:55,052 MobileDeviceUpdater[5606]: Received an XPC event indicating device attach: DFU Device v2 was attached
10.08.2020. 21:14:55,064 MobileDeviceUpdater[5606]: Entered:_AMDFUDeviceConnected, libusbrestore-device:0xF958EEF0
10.08.2020. 21:14:55,064 MobileDeviceUpdater[5606]: Discovered a device. Asking if the device is restorable.
10.08.2020. 21:14:55,064 MobileDeviceUpdater[5606]: Known, supported, and restorable device. Continuing...
10.08.2020. 21:14:55,361 MobileDeviceUpdater[5606]: Entered:_AMDFUDeviceDisconnected, libusbrestore-device:0xF958EEF0
10.08.2020. 21:14:55,362 MobileDeviceUpdater[5606]: Entered:__thr_AMDFUDeviceDisconnected, libusbrestore-device:0xF958EEF0
10.08.2020. 21:14:55,362 MobileDeviceUpdater[5606]: tid:b5c7 - DFU mode device disconnected
10.08.2020. 21:14:55,366 MobileDeviceUpdater[5606]: Received an XPC event indicating device attach: DFU Device v2 was attached
10.08.2020. 21:14:55,378 MobileDeviceUpdater[5606]: Entered:_AMDFUDeviceConnected, libusbrestore-device:0xF9435FB0
10.08.2020. 21:14:55,378 MobileDeviceUpdater[5606]: Discovered a device. Asking if the device is restorable.
10.08.2020. 21:14:55,379 MobileDeviceUpdater[5606]: Known, supported, and restorable device. Continuing...
10.08.2020. 21:14:55,503 MobileDeviceUpdater[5606]: Entered:_AMDFUDeviceDisconnected, libusbrestore-device:0xF9435FB0
10.08.2020. 21:14:55,503 MobileDeviceUpdater[5606]: Entered:__thr_AMDFUDeviceDisconnected, libusbrestore-device:0xF9435FB0
10.08.2020. 21:14:55,503 MobileDeviceUpdater[5606]: tid:b83b - DFU mode device disconnected
10.08.2020. 21:14:57,000 kernel[0]: 051658.998968 Apple Mobile Device (DFU Mode)@24300000: AppleUSBDevice::ResetDevice: <software attempt to RESET>
10.08.2020. 21:15:10,123 MobileDeviceUpdater[5606]: Received an XPC event indicating device attach: Muxed iPhone was attached
10.08.2020. 21:15:10,185 com.apple.usbmuxd[85]: notice    device connected: 52-c76146186825f3d20c3e2dc1c5fae9e61b9c3574@0x24300000
10.08.2020. 21:15:10,284 usbmuxd[85]: AMDeviceStartSession (thread 0x700000094000): Could not start session with device c76146186825f3d20c3e2dc1c5fae9e61b9c3574: kAMDInvalidHostIDError
10.08.2020. 21:15:10,298 MobileDeviceUpdater[5606]: Entered:_AMMuxedVersion2DeviceConnected, mux-device:52
10.08.2020. 21:15:10,305 MobileDeviceUpdater[5606]: tid:b843 - unable to query device capabilities
10.08.2020. 21:15:10,322 MobileDeviceUpdater[5606]: Discovered a device. Asking if the device is restorable.
10.08.2020. 21:15:10,351 MobileDeviceUpdater[5606]: Known, supported, and restorable device. Continuing...

**Comment by Siguza** [comment]
That's caused by Apple, not checkra1n.
