### ISSUE TITLE
IOS 13.5.1 iPhone X Cydia won’t open after restart

### ISSUE THREAD

**Issue by smuhammet** [checkra1n/BugTracker#1617]
1. What iDevice are you using?
iPhone X
2. On what version of iOS is it?
13.5.1
3. What version of checkra1n are you using?
0.10.2 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOS Catalina
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Tried USB-A,C | Apple

**What are the steps to reproduce the issue?**
1. I jailbroke it. Both safe mode and not
2. Nothing installed.
3. Cydia worked nice.
4. After restart it, Cydia won’t open.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes.

**Comment by demhademha** [comment]
This is the nature of this jailbreak, as it's semi tethered you'll need to rejailbreak every time your device restarts.

**Comment by Siguza** [comment]
Yep, that's how it works. Closing as invalid.
