### ISSUE TITLE
Cydia apps not showing 

### ISSUE THREAD

**Issue by bluegreen19** [checkra1n/BugTracker#162]
**What device + iOS version are you on?**
iPhone X

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. Reinstalling the app
2. Rejailbreaking 
3. Reinstalling cydia sub and sub safemood 
...

**What do you expect, and what is happening instead?**
Not sure what’s happing 

**Any other info, error logs, screenshots, ...?**
Nope

**Comment by gurkentier** [comment]
This issue is not related to checkra1n.
Some tweaks have to be updated in order to clear UICache properly on iOS 13.

**Comment by GeekBreak** [comment]
> This issue is not related to checkra1n.
> Some tweaks have to be updated in order to clear UICache properly on iOS 13.

Cydia (or any other package manager) should run uicache, not tweaks, in fact Zebra doesn’t have this issue.
So, sbingner should update Cydia.

**Comment by sbingner** [comment]
Cydia should be running uicache - if it is not, let me know how to duplicate... you should be able to email me from cydia and explain what happened... but this isn’t a checkra1n issue
