### ISSUE TITLE
checkra1n 10.2 app doesn’t support iPad 2 Cellular, iOS 13.5.1

### ISSUE THREAD

**Issue by actualone** [checkra1n/BugTracker#1629]
Current set up iPad 2 Cellular, iOS 13.5.1, MAC OS 10.13 with a USB A CONNECTION.

Is there a plan to provide support or do I need to upgrade?

Thank you much!

**Comment by demhademha** [comment]
Options > allow untested ios versions 
However, if your device is running an A12 chip or newer, it will not be supported by checkra1n.

**Comment by actualone** [comment]
> Options > allow untested ios versions 
> However, if your device is running an A12 chip or newer, it will not be supported by checkra1n. 

I have no idea why I didn't think about that option. Everything is working now jailbreakwise.

Thanks!

**Comment by Siguza** [comment]
Idk what iPad you're talking about, but it's not an iPad 2. That came out in 2011 and had an A5 chip.  
But seeing as how you got it to work, I'm gonna close this as "no action needed".
