### ISSUE TITLE
Black screen overnight

### ISSUE THREAD

**Issue by ikoyhn** [checkra1n/BugTracker#1636]
**Tell us about your setup:**
1. What iDevice are you using? IphoneX
2. On what version of iOS is it? 13.6.1
3. What version of checkra1n are you using? Latest, 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Ubuntu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple cable

**What are the steps to reproduce the issue?**
1. Have phone in jail broken state
2. Leave overnight
3. Phone gets stuck on black screen until hard reset or replugging into wall outlet, which loses jail broken state
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by demhademha** [comment]
This is probably a tweak. Does this issue persist when in safemode?

**Comment by ikoyhn** [comment]
Like demhademha mentioned, the issue was from a tweak
