### ISSUE TITLE
Can’t boot in safe mode (downloaded a tweak which boots with a message in my screen which I can’t remove*

### ISSUE THREAD

**Issue by Slaymen** [checkra1n/BugTracker#164]
**What device + iOS version are you on?**

**What checkra1n version are you using?**

**What are the steps to reproduce the issue?**
1.
2.
3.
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by littlelailo** [comment]
This should be resolved with the newest version of checkra1n, if you still have the issue with 0.9.3.2 please reopen the issue
