### ISSUE TITLE
Stuck when restarting Springboard after uninstalling the plugin

### ISSUE THREAD

**Issue by WindowsMEMZ** [checkra1n/BugTracker#1641]
I will use translation software for this error report
**Tell us about your setup:**
1. What iDevice are you using? iPhone 6 Plus
2. On what version of iOS is it? iOS12.4.8
3. What version of checkra1n are you using? checkra1n 0.10.2 for Linux (CLI, x86_64)
4. What is your host system (OS version? Hackintosh? VM? etc.)? Boot with USB flash drive
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A

**What are the steps to reproduce the issue?**
1. Jailbreak normally
2. Install Cydia
3.Install Sileo using the source "https://repo.getsileo.app" in Cydia
4.Install some plugins in Sileo
5.Uninstall some unnecessary plug-ins
6.Restart Springboard

**What do you expect, and what is happening instead?**
There is a 30% probability that it will keep spinning

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by demhademha** [comment]
By plugins I assume tweaks,
Also, sileo support is now deprecated, however the package manager shouldn't matter.
Ensure that you  are not installing out-of-date tweaks or those which are pirated. Rebooting in safe mode will allow you to fix the issue.
