### ISSUE TITLE
Checkra1n dosen't work on 13.6.1 iphone 8

### ISSUE THREAD

**Issue by sasuke4uchiwa** [checkra1n/BugTracker#1642]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 8
2. On what version of iOS is it? 13.6.1
3. What version of checkra1n are you using? 0.10.1 / 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Catalina 10.5.3
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A Apple cable & 3rd  party

**What are the steps to reproduce the issue?**
1. Start Checkra1n
2. follow instructions
3.Jailbreak processed - done
...

**What do you expect, and what is happening instead?**
it need to be jailbroken instead i's boot to unjailbroken state 

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes 

**Any other info, error logs, screenshots, ...?**
i tried safe mode and normal mode i end up in non jailbroken and the procces complete 100% with error but non jailbroken and i tried it in USB booted created in 3uTools.
i was bypassed in 13.2.2 and restored the device to 13.6.1 to make cellular bypass but i can't with no jailbreak and no ssh Acces.

**Comment by demhademha** [comment]
There is no support for iCloud bypassed devices. Refer to #1

**Comment by sasuke4uchiwa** [comment]
> There is no support for iCloud bypassed devices. Refer to #1

There is support for bypass ios 13.6.1 i have iphone 7 successful ly jailbroken and bypassed

**Comment by sasuke4uchiwa** [comment]
I was able to fix it i flashed the wrong firmware my device is iphone 8 A1905 iPhone 10.4 i flashed iPhone 10.1 firmware 🤦😅
