### ISSUE TITLE
USBMUX Error (Error code: -79)

### ISSUE THREAD

**Issue by silvanohirtie** [checkra1n/BugTracker#1643]
**Tell us about your setup:**
1. What iDevice are you using?
**iPhone 8**
2. On what version of iOS is it?
**14 Public Beta 5**
3. What version of checkra1n are you using?
**0.10.2 Beta**
4. What is your host system (OS version? Hackintosh? VM? etc.)?
**Ubuntu 20.04**
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
**Normal lightning cable**

**What do you expect, and what is happening instead?**
After the whole process is completed, I see "Booting..." on the loading bar, and then the iPhone boots with the normal apple logo instead of the checkra1n logo.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes.

**Any other info, error logs, screenshots, ...?**
Before this error, I usually had some problems with the loading bar being stuck at "Checking if device is ready" or stuck at other steps. 
I tried to switch the USB but nothing changes.
Didn't have any problem with IOS 13.6, then switched to ios 14 for some problems that appeared.

**Comment by Siguza** [comment]
#1513

**Comment by zfazli** [comment]
![Uploading 16089300999787831444536396429748.jpg…]()
