### ISSUE TITLE
holding at white apple screen after installed the tweak "appcon"

### ISSUE THREAD

**Issue by 242475125** [checkra1n/BugTracker#165]
**What device + iOS version are you on?**
Iphone 7 + IOS 13.0

**What checkra1n version are you using?**
0.9.1 beta

**What are the steps to reproduce the issue?**
1. Jailbreak the iphone
2. Install tweak "appcon" from cydia
3. When tweak installed, press the "Reboot Spring" button
4. Black screen will shown after press the button, then reboot iphone.

**What do you expect, and what is happening instead?**
Iphone can jailbreak normally

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Not an issue with checkra1n, please wait for a version which includes safe mode via volume up.
