### ISSUE TITLE
Will checkra1n ever be semi-untethered?

### ISSUE THREAD

**Issue by Broadcastre** [checkra1n/BugTracker#1652]

**Comment by Broadcastre** [comment]
I read somewhere that it wont.

Closed.

**Comment by Siguza** [comment]
Correct, it can never be semi-untethered.

**Comment by Worf1337** [comment]
can you delete this issue please by the way? this is the most embarrassing issue i've posted (i have a decent knowledge on jailbreaks now)

**Comment by Siguza** [comment]
Alright, sure.
