### ISSUE TITLE
YouRepo Default Repository

### ISSUE THREAD

**Issue by relisiuol** [checkra1n/BugTracker#166]
Hello,

As jailbreak should not be an olygopoly, here is an alternative repo that could be added as default:
https://www.yourepo.com/

This source contains packages only from verified users on YouRepo. Lot of developers use YouRepo, but switch for Packix only for visibility. Even some themers use YouRepo services (Theme Creator/Zip to Deb/... tools) but host their packages on Packix only for this reason, visibility.

Don't hesitate to contact me if you want more informations or even if you want to help me maintain or moderate the repo:
https://www.yourepo.com/contact/

Regards,
@relisiuol

**Comment by sbingner** [comment]
Not a jailbreak issue

**Comment by relisiuol** [comment]
How to suggest it so?

New Issue > Free form > For everything that is NOT a bug report.
