### ISSUE TITLE
What device does it support and what ios is it capable?

### ISSUE THREAD

**Issue by JustrynaJB** [checkra1n/BugTracker#1662]
Hi, just like what the title says, i was searching for a new jailbreak for iOS 13.6.1, and i cant really find one that can do the job. And i was wondering that does my device supports your method? And also my iOS version is 13.6.1 and then my device is iPad air 3 (2019), iPad Pro (3rd Gen)

**Comment by Siguza** [comment]
Your devices are A12 and A12X, so not supported.
