### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by mona030** [checkra1n/BugTracker#1666]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone XR iPhone XS 

2. On what version of iOS is it?
Both is 13.7

3. What version of checkra1n are you using?
V1.0 premium 

4. What is your host system (OS version? Hackintosh? VM? etc.)?

I'm not sure what this is 

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

Iphone cable 

**What are the steps to reproduce the issue?**
1. Open device 
2. Choose device model and version 
3. Click on jail break loads quick same as bypass and fully load after it says server error 
...

**What do you expect, and what is happening instead?**

Expected to open or At least see something also tried iPhone 7 and same thing  

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

No tick 

**Any other info, error logs, screenshots, ...?**
![image](https://user-images.githubusercontent.com/71194555/93005637-229c9800-f553-11ea-87c5-e17c386723fb.jpeg)

**Comment by Siguza** [comment]
That's a fake tool. The only real one is at https://checkra.in/, and there is no Windows version yet.

**Comment by worf1337** [comment]
where did you download that? not that I'll use it

**Comment by worf1337** [comment]
Never mind. It looks like you got scammed.

You apparently 'paid' for a Windows version from http://checkra1n-windows.com
