### ISSUE TITLE
When CheckRa1n Will update for iPhone XR and XS

### ISSUE THREAD

**Issue by vidi0104** [checkra1n/BugTracker#1667]
Please CheckRa1n update for iPhone XR, and XS because, my iPhone aktivation lock

**Comment by mona030** [comment]
How you mean ? On Sun, Sep 13, 2020 at 04:11 vidi0104 <notifications@github.com> wrote:Please CheckRa1n update for iPhone XR, and XS because, my iPhone aktivation lock?You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Siguza** [comment]
Not possible.
