### ISSUE TITLE
Cydia install only showing cancel

### ISSUE THREAD

**Issue by agentwildfire** [checkra1n/BugTracker#167]
**What device + iOS version are you on?**
iPad Pro (2017) 10.5, IOS 13.2

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1.Install Cydia
2.Install Sileo
3.Cydia Crashes
4.Reinstall Cydia
5.Cydia Crashes
6.Reinstall Jailbreak
7.Cydia Crashes
8.Clear cache
9.Only option is to Cancel in Checkra1n app
...

**What do you expect, and what is happening instead?**
I expect Cydia to open but Cydia just crashes.

**Any other info, error logs, screenshots, ...?**
![IMG_0047](https://user-images.githubusercontent.com/57621403/68584808-84dec500-0478-11ea-9995-a2db0773d4be.png)

**Comment by ghost** [comment]
reboot your device and start again, it works for me

**Comment by agentwildfire** [comment]
> reboot your device and start again, it works for me

I did reboot and try it a few times and it still showed me the same thing :/

**Comment by Shadowedstalker** [comment]
If it's still showing nothing you have to do 'System Restore.' Then reajailbreak and you will see install Cydia.

**Comment by littlelailo** [comment]
Installing Sileo alongside Cydia is currently unsupported

**Comment by jwlptrck** [comment]
How can i fix my iphone se there is no install button, theres only cancel button showing
