### ISSUE TITLE
Status on control center missing after jailbroken 

### ISSUE THREAD

**Issue by Spov3** [checkra1n/BugTracker#1674]
**Tell us about your setup:**
1. What iDevice are you using?
iPad Pro 2nd Gen 12.9 inch with cellular

2. On what version of iOS is it?
iOS 13.7

3. What version of checkra1n are you using?
Tried with both 0.10.1 and 0.10.2

4. What is your host system (OS version? Hackintosh? VM? etc.)?
Macbook Pro 15 inch with macOS 10.15.6

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
through Apple's usb c to usb a adapter, and usb a to lightning 

**What are the steps to reproduce the issue?**
1. update to ios 13.7
2. jailbreak with checkra 0.10.2
3. check control center and no status
4. if i force restart the ipad into non-jailbroken state, the status in control center is back
...

**What do you expect, and what is happening instead?**
i expect status like battery and service signal etc on the control center to remain there after jailbroken, just like previous version of iOS and checkra1n

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
no

**Any other info, error logs, screenshots, ...?**
![IMG_1790](https://user-images.githubusercontent.com/63980067/93301679-02a2f800-f823-11ea-895f-edb0d8d1963e.jpg)

**Comment by worf1337** [comment]
If this is fixed in Safe Mode, this usually means it's a tweak causing the issue

**Comment by Spov3** [comment]
Thanks for your input, Broadcastre. I have identified that the tweak “Gesture 13” was the culprit. The issue is resolved after removing the tweak.

As a note though, the tweak was working fine (with status on control center) in iOS 13.5 with a jailbreak done with Checkra1n 0.10.1.

Hope this will be helpful to others who may face the same issue as me. 

Thanks!

**Comment by worf1337** [comment]
You should close this if it's resolved.
