### ISSUE TITLE
Checkra1n App not appearing on ipad pro gen 2. but it did jailbreak in past

### ISSUE THREAD

**Issue by EmanuelPermane** [checkra1n/BugTracker#1676]
**Tell us about your setup:**
1. What iDevice are you using?
ipad pro gen 2
2. On what version of iOS is it?
13.7 
3. What version of checkra1n are you using?
10.2 gui mode and terminal both were tried
4. What is your host system (OS version? Hackintosh? VM? etc.)?
mac os catalina 10.15.6 (19G2021)
MacBook Pro (Retina, 15-inch, Mid 2014)
also tried on an older mac that my gf has
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
3 different apple official USB-A cables directly into laptop.
**What are the steps to reproduce the issue?**
1. run check rain
2.  use safe mode or not safe mode doesnt matter
3.it doesnt boot with the checkrain app on my ipad
side notes: it jailbroke 1 time using it. I used it for a few days and after installing ncontroller tweak to add bluetooth controller support caused my device to fully restart after getting gray spinning wheel. since then ive not been able to jailbreak again. I have tried holding volume up when booting does nothing.

**What do you expect, and what is happening instead?**
not sure what is happening

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**
icloud disabled. no siri. no pending updates. no passcode
checkrain menu does not throw errors.
I can access my ipad from xcode when it boots fully into stock ios and it is trusted because from xcode i can push test apps i write to confirm its not that.
![boot](https://user-images.githubusercontent.com/11033427/93403473-7b627e00-f83c-11ea-8b6e-cd980a4b15d2.jpg)

I can ssh in but only when i see the checkrain booting menu above on the ipad. then it later boots to stock ios and i cant ssh in again

**Comment by Siguza** [comment]
Based on the fact that the checkra1n host GUI doesn't complain, I'm confident this is a symptom of #1613.  
Safe Mode is currently broken on 13.6 and above, so if a tweak is crashing SpringBoard there, your only remaining option for the moment is SSH, I'm afraid. :/

**Comment by EmanuelPermane** [comment]
what can i do in ssh? i can ssh in when the checkrain menu is on my ipad. is there some commands to try? i checked the thread you referenced and didnt see an ssh solution.

also if you have a way to contact you outside of git i am willing to try things on my ipad if it helps you replicate or test things.

**Comment by Siguza** [comment]
Well, you could either run `dpkg -l` to get a list of all installed packages, and use `apt-get remove ...` to uninstall any of them, if you know or suspect that they are at fault.  
Alternatively, you could disable all run-at-launch scripts by running:

    mv /etc/rc.d /etc/rc.d.backup

That will also disable Substrate, and thus all tweaks, sort of "forcing you into safe mode". Then you should be able to boot and diagnose/fix the tweak issue. Just be sure to put that folder back when you're done.

**Comment by EmanuelPermane** [comment]
You are a legend. with that you helped me help myself. ill explain everything I did if it helps someone else.

first off if on mac you need iproxy 

Install Homebrew (ill assume you have)
Install usbmuxd: `brew install usbmuxd`
Plug device into computer via USB.
Open Terminal Window and Type the following: `iproxy 2222 44`
Open another Terminal window and type the following when you reach the checkrain screen on your ipad and your computer says "done" : `ssh root@localhost -p 2222`

after connecting put your password. default is "alpine"
after you can do your step `dpkg -l` above to find your package OR use a site like (https://www.ios-repo-updates.com/) not trying to advertise its what i used.

search your package there. for me it was `com.orikad.controllersforall `
when you search it up. copy all the dependencies and get ready to remove. this website tells you the dependencies in the same way   `dpkg -l` lists them so i found that handy and quick. this also depends on you knowing what you installed last. i recommend only installing tweaks one at a time to make removing them this way easier.

```
apt-get remove com.orikad.controllersforall

apt-get remove mobilesubstrate
apt-get remove ch.ringwald.btstack
apt-get remove preferenceloader
apt-get remove com.rpetrich.rocketbootstrap
apt-get remove kr.iolate.simulatetouch
```

before you finish it will boot and say springboard crashed but technically youre jailbroken still.  this works on 13.7


you might want to refine this and share with people on the website. might help with tickets :) thank you for your work

**Comment by EmanuelPermane** [comment]
Side not you may need to respring if this happens. @Siguza I would I suggest adding a respring button within the checkrain app that appears now. 

I used a different tool to respring after checking cydia and the checkra1n app. let me know if you need me to try or test anything else but this fully solved my problem.
