### ISSUE TITLE
I can't connet iphone and checkra1n

### ISSUE THREAD

**Issue by xu378947986** [checkra1n/BugTracker#1686]
Tell us about your setup:

What iDevice are you using? iPhone 8p
On what version of iOS is it? iOS 13.5
What version of checkra1n are you using?
0.11.0 and 0.10.2
What is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu 18.04LTS
How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Original iPhone cable
What are the steps to reproduce the issue?

1. update checkra1n to 0.11.0
2. open checkra1n and found I can't connet to my phone!
3. so i use linux command “sudo apt-get install checkra1n=0.10.2” to downgrade
4.still can't connet to my phone
5.checkra1n Interface display “connect your iphone，ipod touch.............................”
6. USB is always normal and can be charged

What do you expect, and what is happening instead?
Please help me to solve this problem, no matter which version is unable to jailbreaking

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?

Any other info, error logs, screenshots, ...?
![c1](https://user-images.githubusercontent.com/33505099/93864919-2ae59780-fcf8-11ea-87b9-d4b8d89eac09.jpg)

**Comment by xu378947986** [comment]
PLESE HELE ME !

**Comment by launchdaemon** [comment]
I'm also having this issue:

1. What iDevice are you using? iPhone 5S (tried two different ones)
2. On what version of iOS is it? 12.4.3 and 12.4.8
3. What version of checkra1n are you using? 0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)? Ubuntu 18.04.5 LTS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Two different third party USB-A lightning cables

**What are the steps to reproduce the issue?**
1. Connect phone, unlock and trust host
2. sudo checkra1n
3.
...

I would expect to see checkra1n list the device connected but it says "Connect your iPhone, iPod touch, iPad or AppleTV to begin."

lsusb sees the device is connected and so does the file explorer, e.g. it mounts the phone to access pictures. However utilities such as ideviceinfo, which were updated by apt with the new version of checkra1n, return "ERROR: No device found!"

**Comment by xu378947986** [comment]
> I'm also having this issue:
> 
> 1. What iDevice are you using? iPhone 5S (tried two different ones)
> 2. On what version of iOS is it? 12.4.3 and 12.4.8
> 3. What version of checkra1n are you using? 0.11.0
> 4. What is your host system (OS version? Hackintosh? VM? etc.)? Ubuntu 18.04.5 LTS
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Two different third party USB-A lightning cables
> 
> **What are the steps to reproduce the issue?**
> 
> 1. Connect phone, unlock and trust host
> 2. sudo checkra1n
> 
> ...
> 
> I would expect to see checkra1n list the device connected but it says "Connect your iPhone, iPod touch, iPad or AppleTV to begin."
> 
> lsusb sees the device is connected and so does the file explorer, e.g. it mounts the phone to access pictures. However utilities such as ideviceinfo, which were updated by apt with the new version of checkra1n, return "ERROR: No device found!"

I think the new version updates the system files, causing this problem, how did you solve it?

**Comment by xu378947986** [comment]
I think the new version updates the system files, causing this problem, how did you solve it?

**Comment by xu378947986** [comment]
> I'm also having this issue:
> 
> 1. What iDevice are you using? iPhone 5S (tried two different ones)
> 2. On what version of iOS is it? 12.4.3 and 12.4.8
> 3. What version of checkra1n are you using? 0.11.0
> 4. What is your host system (OS version? Hackintosh? VM? etc.)? Ubuntu 18.04.5 LTS
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Two different third party USB-A lightning cables
> 
> **What are the steps to reproduce the issue?**
> 
> 1. Connect phone, unlock and trust host
> 2. sudo checkra1n
> 
> ...
> 
> I would expect to see checkra1n list the device connected but it says "Connect your iPhone, iPod touch, iPad or AppleTV to begin."
> 
> lsusb sees the device is connected and so does the file explorer, e.g. it mounts the phone to access pictures. However utilities such as ideviceinfo, which were updated by apt with the new version of checkra1n, return "ERROR: No device found!"

I think the new version updates the system files, causing this problem, how did you solve it?

**Comment by launchdaemon** [comment]
I haven't solved it, I'm having the same issue.  It seems to be an issue with libimobiledevice that is installed with checkra1n as none of those utilities can see the device either.

**Comment by xu378947986** [comment]
> 我还没有解决，我遇到了同样的问题。与checkra1n一起安装的libimobiledevice似乎是一个问题，因为这些实用程序都无法看到该设备。

Even if I downgrade the old version, the problem still cannot be solved.
I don't know which system files have been updated

**Comment by Siguza** [comment]
This is caused by `usbmuxd` segfaulting.  
We just uploaded a new version of it to the checkra1n repo that should fix this issue.

**Comment by nikias** [comment]
```
sudo apt-get update
sudo apt-get upgrade
```

**Comment by xu378947986** [comment]
> ```
> sudo apt-get update
> sudo apt-get upgrade
> ```

Thx，i have already solve it
