### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#1688]
Where can I find the source code? How do I know this isn't spyware? LOL
No seriously, where is the source code?

**Comment by ghost** [comment]
Read the FAQ on their website.

**Comment by Siguza** [comment]
Marking this as a duplicate of #566.  
It will most likely only happen after we release a Windows version, in order to prevent low-quality GUIs to be rigged together on day 1. The situation with SEPOS also stalled us for months, but I'm hoping we can still get this done in 2020.

**Comment by worf1337** [comment]
SEPOS?

**Comment by RokeJulianLockhart** [comment]
Yeah, what are SEPOS?

**Comment by worf1337** [comment]
figured out that SEPOS is what runs SEP

**Comment by RokeJulianLockhart** [comment]
@Worf1337, are you able to elaborate? I know not what SEP is.
