### ISSUE TITLE
Pubg mobile crashes with checkra1n

### ISSUE THREAD

**Issue by Malekalian** [checkra1n/BugTracker#169]
**What device + iOS version are you on?**
I have iphone 7
Ios 13.2.2

**What checkra1n version are you using?**
Beta 0.9.1
**What are the steps to reproduce the issue?**
1. Jailbreak my device with checkra1n 
2. open pubg
3. it crashes !
...

**What do you expect, and what is happening instead?**
Liberty lite works fine and pubg work
But liberty lite isn’t compatible with pubg hacks and it crash while turning on liberty with hacks 

**Any other info, error logs, screenshots, ...?**

**Comment by Logxn** [comment]
You answered your issue yourself.
'liberty lite isn't compatible'

This is not a checkra1n issue.

**Comment by ahammouri** [comment]
i use liberty lite beta on pubg and it works fine

**Comment by nullpixel** [comment]
not a checkra1n issue
