### ISSUE TITLE
No loader after successful jailbreak

### ISSUE THREAD

**Issue by bastiaanno** [checkra1n/BugTracker#1690]
**Tell us about your setup:**
1. What iDevice are you using?
6S/A1688
2. On what version of iOS is it?
14.2 (18B5052h)
3. What version of checkra1n are you using?
0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A normally.

**What are the steps to reproduce the issue?**
1. allow untested versions + verbose boot
2. connect & put in DFU mode
3. jailbreak & enter passcode
...

**What do you expect, and what is happening instead?**
I expect to see the checkra1n loader in which I can select Cydia, but it isn't there.
Checkra1n says that jailbreak was successful.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes, exactly the same.

**Any other info, error logs, screenshots, ...?**
No errors.

**_EDIT:_**

I just downgraded to iOS 14.0 with iTunes, now it does work.

**Comment by SomethingGeneric** [comment]
Same issue except:
* I'm just on `14.0` and not any betas. 
* I'm using Manjaro Linux.
(Assuming @bastiaanno meant checkrain `0.11.0`

**Comment by bastiaanno** [comment]
I just downgraded to iOS 14.0 with iTunes. I still get the same results as I had the first time. (with the same steps)

**Comment by Siguza** [comment]
@SomethingGeneric It seems the OP managed to resolve this, is the issue still occurring for you?  
If so, could you try if SSH works?

**Comment by DylanDuff** [comment]
Same issue here

-  6S on 14.0
- Using High Sierra
- checkra1n 0.11.0
- SSH not working

**Comment by superrnovae** [comment]
Same issue here

- iPad Air 2 on 14.0.1
- Linux Debian Bullseye
- checkra1n 0.11.0
- SSH works

Also reproducible on 14.0

**Comment by SomethingGeneric** [comment]
> @SomethingGeneric It seems the OP managed to resolve this, is the issue still occurring for you?
> If so, could you try if SSH works?

I no longer have a device compatible with CheckRa1n, but I would say not to close the issue. :/

**Comment by cvscade** [comment]
I've noticed this before, you just need to wait for at least 20 minutes, and the checkra1n app will automatically show up after some time. It takes time to show up.

**Comment by Jamieplayz29** [comment]
i have the same issue, i tried to SSH on many ports but all the connections were refused

**Comment by Siguza** [comment]
After some investigating, this seems to have the same root cause as #1689.
