### ISSUE TITLE
78

### ISSUE THREAD

**Issue by Nizam861** [checkra1n/BugTracker#1691]
**checkra1:**
1. What iDevice are you using?  iPhone x
2. On what version of iOS is it?   13.7
3. What version of checkra1n are you using? 
4. What is your host system (OS version? Hackintosh? VM? etc.)? Windows 7 32bit
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Nizam861** [comment]
Error 78

**Comment by worf1337** [comment]
Please provide more information

**Comment by Siguza** [comment]
There is no Windows version yet.  
Whatever you're running isn't checkra1n.
