### ISSUE TITLE
Cannot boot to jailbreak state on iPad Pro 9.7 inch

### ISSUE THREAD

**Issue by n0k0m3** [checkra1n/BugTracker#1692]
**Tell us about your setup:**
1. What iDevice are you using?
iPad Pro 9.7 inch (1st Generation), model number: iPad6,3, board number: j127ap
2. On what version of iOS is it?
iOS 14.0
3. What version of checkra1n are you using?
0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Hackintosh, Macbook Pro, Linux (checkn1x)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A to Lightning 3rd party cable
**What are the steps to reproduce the issue?**
0. Restore the iPad using option/shift restore, or restore from recovery mode, or restore from DFU mode (I did all of them)
1. Setting up iPad without any account attached, making sure nothing is interfering with the JB process (will still fail even if restore from backup though) and no screen lock
2. Jailbreak with checkra1n, from normal mode/recovery mode (or DFU with CLI mode), flag -v and -V
3. 
...

**What do you expect, and what is happening instead?**
Expect: Jailbreak successful, booted to SB from checkra1n logo
Happened: Respring(Restarted?) then boot to SB. Checkra1n stuck at Booting then Error -20 on MacOS, and error -79 on Linux
**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
Same process, same cable worked for iPhone 6s Plus and boot to jailbroken state successfully

P.S: Maybe same issue as #1689

**Comment by Galactic-Dev** [comment]
I have the exact same issue. tried on a catalina hackintosh and arch linux with the same error codes you provided

**Comment by DiegoSepu95** [comment]
So iPad Pro 1 gen is not compatible with checkra1n 11? I will wait to update my 12,9 to ios 14 then.

**Comment by ruul62** [comment]
I have the same problem , ipad pro 1st 9.7 and other ipad pro 1st 9.7 with celullar. Error -20 in MacOs and error -79 in linux. Howerver jailbreak works perfect in iphone 6s

**Comment by bubez81** [comment]
same error here iPad Pro 1st

**Comment by gbone001** [comment]
same problem, any luck with ios13?

**Comment by n0k0m3** [comment]
> same problem, any luck with ios13?

Not sure with checkra1n 0.11 but I used 0.10 and it worked fine

**Comment by bubez81** [comment]
No pro with ios13 and checkra1n 10

**Comment by shikiroot** [comment]
same problem

**Comment by Siguza** [comment]
Can you try a verbose boot?

**Comment by ghost** [comment]
I attempted a verbose boot and got the same error. Is there a way I can get the logs and paste them here? Sorry if this is simple I'm new to checkra1n.

**Comment by CrisioDev** [comment]
![IMG_20200923_112912](https://user-images.githubusercontent.com/21323753/94360765-4235d380-00b0-11eb-8026-f96e2aa23f68.jpg)
![IMG_20200923_113534_1](https://user-images.githubusercontent.com/21323753/94360769-482bb480-00b0-11eb-9ed2-60fa74730a56.jpg)
This is all I could catch with verbose boot.

**Comment by n0k0m3** [comment]
Common booting to jailbreak
![verbose1](https://user-images.githubusercontent.com/10925298/94374289-2eeb2e00-00d9-11eb-8e56-db5a224b36b4.png)

3 times recording verbose I got 3 different verbose output
![verbose2](https://user-images.githubusercontent.com/10925298/94374290-2f83c480-00d9-11eb-8aa2-70c5f6695279.png)
![verbose3](https://user-images.githubusercontent.com/10925298/94374291-301c5b00-00d9-11eb-89ac-9a2c839c1855.png)

Finally got a kernel panic log
![verbose4](https://user-images.githubusercontent.com/10925298/94374293-30b4f180-00d9-11eb-9049-be5f3b23949d.png)

**Comment by nathanielcwm** [comment]
I'm also having issues on my device

Sorry I don't have any pictures yet but my last few lines in the verbose log are identical to @CrisioDev 

After reaching it reaches booting on the non verbose log it black screens and reboots into normal mode.

When run in cli mode it freezes at `Checkmate!`

**Comment by BorisYeltsin** [comment]
same device same error

**Comment by n0k0m3** [comment]
From #1698
Found something interesting, 0.11 also failed on iPad on iOS 12. So the reason is probably the new patch finder or the NVRAM unlock patch that was introduced.

**Comment by buffalonan** [comment]
also using iPad Pro 1st gen in Ubuntu, ios 14.0.1, usbmux error -79

**Comment by Siguza** [comment]
Ok, pretty sure this has the same root cause as #1689. Marking as dupe.

**Comment by Medlk** [comment]
I have the same problem with my iPad pro 9.7 inch ios 14.0.1 I even change the cable and tried checkra1n 0.10.0 with no success. Is this because checkra1n doesn't support iPad 9.7 and will it be fix in the upcoming days?

**Comment by valkimchuk** [comment]
> I have the same problem , ipad pro 1st 9.7 and other ipad pro 1st 9.7 with celullar. Error -20 in MacOs and error -79 in linux. Howerver jailbreak works perfect in iphone 6s

Have you managed to get jailbreak on your device?

**Comment by rafal-kucharski** [comment]
same here cant jailbreak ipad pro 9.7 with 4.0.1, would it be possible soon?

**Comment by valkimchuk** [comment]
I hope it will be possible. I tried to get it using Ubuntu, but didn’t work. iPad goes into black screen.

**Comment by NewHospitals** [comment]
I have iPad Pro 12.9 A1652 model, Please help me if possible jailbreak the model, I tried a lot of times but not working. 

When start jailbreak the is stuck and come error 20

**Comment by NewHospitals** [comment]
What iDevice are you using?
iPad Pro 12.9 inch A1652 Model

On what version of iOS is it?
iOS 14.5.1

What version of checkra1n are you using?
checkra1n 0.12.4 beta

What is your host system (OS version? Hackintosh? VM? etc.)?
MacBook Pro 2010

How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A to Lightning 3rd party cable

I have iPad Pro 12.9 A1652 model, Please help me if possible jailbreak the model, I tried a lot of times but not working.
When start jailbreak the is stuck and come error 20

**Comment by rorocheck** [comment]
same problem for weeks. fixed on ubuntu with

sudo (checkra1n executable drag) -k (pongo bin) and ONLY WORKED when selected all options in checkra1n
