### ISSUE TITLE
USB Error -76 on JB, checkra1n doesn't show on home, and SSH server isn't up

### ISSUE THREAD

**Issue by trn1ty** [checkra1n/BugTracker#1693]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone SE1 64GB (`iPhone 8,4`)
2. On what version of iOS is it?
iOS 14.0
3. What version of checkra1n are you using?
Beta 0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Arch Linux 64-bit with kernel 5.8.10-arch1-1.
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A->Lightning through an AmazonBasics cable, on a USB 2.0 port on a Thinkpad T420.

**What are the steps to reproduce the issue?**
1. Start checkra1n, enter DFU, jailbreak.

---

**What do you expect, and what is happening instead?**
When the jailbreak is complete, the checkra1n splash and debug data (nothing out of the ordinary) will show up as expected, but checkra1n on the computer will print `USB Error (Error code: -76)`. Then, when I reach my home screen, the `checkra1n` app icon won't show up, nor will Cydia. The SSH server on port 44 also isn't open.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes, in the same way.

**Any other info, error logs, screenshots, ...?**
I had the same problem on the last version of checkra1n with iOS 13.5. I don't know why it started because it happened a while ago, but the iOS 14 update seemed to wipe my jailbreak so I figured that would fix it. Fortunately, other than the jailbreak, the phone still works as expected.

**Comment by notsatvrn** [comment]
same here, Arch Linux w/ kernel 5.7.10-17-tkg-pds

**Comment by shellmage** [comment]
same here
iphone 6
ios 12.4.8
checkra1n 11.0 
Arch Linux / kernel 5.8.9-arch2-1
Thinkpad x220

**Comment by trn1ty** [comment]
Interesting... Arch Linux error maybe? Or is it a Thinkpad xx20 thing? Tempted to try on a different distro, might set up a live USB to test because I need one for another project anyway.

Edit: I'm not sure I got this error on Debian...

**Comment by notsatvrn** [comment]
im not on x220

**Comment by demhademha** [comment]
It could be that the libimobiledevice utils are not up to date, maybe build them from source.

**Comment by notsatvrn** [comment]
ill try the -git versions

**Comment by notsatvrn** [comment]
failed to compile so idk

**Comment by ghost** [comment]
Just input
`$ sudo ./checkra1n --cli`
then the checkra1n icon will appear

**Comment by DEALWITHIT199** [comment]
> **Tell us about your setup:**
> 
> 1. What iDevice are you using?
>    iPhone SE1 64GB (`iPhone 8,4`)
> 2. On what version of iOS is it?
>    iOS 14.0
> 3. What version of checkra1n are you using?
>    Beta 0.11.0
> 4. What is your host system (OS version? Hackintosh? VM? etc.)?
>    Arch Linux 64-bit with kernel 5.8.10-arch1-1.
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
>    USB-A->Lightning through an AmazonBasics cable, on a USB 2.0 port on a Thinkpad T420.
> 
> **What are the steps to reproduce the issue?**
> 
> 1. Start checkra1n, enter DFU, jailbreak.
> 
> **What do you expect, and what is happening instead?**
> When the jailbreak is complete, the checkra1n splash and debug data (nothing out of the ordinary) will show up as expected, but checkra1n on the computer will print `USB Error (Error code: -76)`. Then, when I reach my home screen, the `checkra1n` app icon won't show up, nor will Cydia. The SSH server on port 44 also isn't open.
> 
> **Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
> Yes, in the same way.
> 
> **Any other info, error logs, screenshots, ...?**
> I had the same problem on the last version of checkra1n with iOS 13.5. I don't know why it started because it happened a while ago, but the iOS 14 update seemed to wipe my jailbreak so I figured that would fix it. Fortunately, other than the jailbreak, the phone still works as expected.

Did you turn off the passcode of your iDevice before Jailbreaking?

**Comment by trn1ty** [comment]
> Did you turn off the passcode of your iDevice before Jailbreaking?

No, but I just tested again with no password and I had the same problem once again.

**Comment by shellmage** [comment]
I executed the same checkra1n executable from Ubuntu 20.04 and it worked fine
ps: on the same x220 thinkpad

**Comment by notsatvrn** [comment]
might be an arch issue then

**Comment by Siguza** [comment]
Dupe of #1689.

Also FYI: removing the passcode should never be required to make a jailbreak work.
