### ISSUE TITLE
iPod Touch 6G only Boots in safe Mode

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#1694]
**Tell us about your setup:**
1. iPod Touch 6G
2. ios 12.4.8
3. Beta 0.11.0
4. 2020 MacBook Pro 13", MacOS 10.15.6 (19G2021)
5. USB-C Apple Adapter to OG Apple Lighting

**What are the steps to reproduce the issue?**
1. Jailbreak ios 12.4.8 with Checkra1n Beta 0.11.0 (Beta 0.10.2 does function Properly)
2. after succefull Jailbreak, upgrade all Stock Cydia Packages (exactly the Same as on Beta 0.10.2) Device goes into respring Loop
3. After Respring Loop: rejailbreak with Beta 0.11.0, stuck at "uicache..../loader.app/" and Checkra1n App on Mac gives Timeout (Error Code -20)
4. After Reboot and Checkra1n Beta 0.11.0 (Option Safe Mode active) Device boots (obviously) without Tweaks enabled
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**
![Bildschirmfoto 2020-09-23 um 16 36 32](https://user-images.githubusercontent.com/57911581/94027680-65643880-fdbb-11ea-9977-588d59e96dc1.jpeg)
![IMG_0616](https://user-images.githubusercontent.com/57911581/94027689-685f2900-fdbb-11ea-811f-148894e17e0d.jpeg)

**Comment by demhademha** [comment]
Troubleshoot the issue by using iCleaner to find which tweaks conflict

**Comment by ghost** [comment]
it's Cydia Substrate (doesn't matter which version) and/or Substrate Safe Mode (also doesn't matter which version).
When I install both Tweaks and ReJailbreak with Checkra1n 0.11.0 it's either Stuck at a respring Loop or stuck at the Error mentioned above.
When I ReJailbreak with Checkra1n 0.10.2 however, everything works as expected and without any errors.

**Comment by Siguza** [comment]
This is an odd one. I also see from the log that a couple of mounts failed...

**Comment by ghost** [comment]
I Just tested the Same on my iPhone 5s (iPhone6,2) iOS 12.4.8 and the Error still exists.
But Thanks a lot for your fast responses!

**Comment by Siguza** [comment]
Managed to reproduce this.

**Comment by Siguza** [comment]
Should be fixed in 0.12.0.
