### ISSUE TITLE
Restoring jailbreak will also restore sources when rejailbroken

### ISSUE THREAD

**Issue by worf1337** [checkra1n/BugTracker#1697]
**Tell us about your setup:**
1. What iDevice are you using? iPhone SE 1st Generation.
2. On what version of iOS is it? iOS 13.5.1 (not getting iOS 14 yet)
3. What version of checkra1n are you using? 0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)? Linux mint 18
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Official Apple Cable
**What are the steps to reproduce the issue?**
1. Jailbreak
2. Add sources
3. Restore
4. Rejailbreak
5. Install cydia and go to sources
...

**What do you expect, and what is happening instead?**
I expect all the sources to be gone, but they are still there.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yep

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Why do you expect sources to be gone? They're on the data partition, not the system partition...

**Comment by worf1337** [comment]
I see.

Closing this.
