### ISSUE TITLE
error code: -20 on an ipad 5th generation freshly updated (tried restoring)

### ISSUE THREAD

**Issue by Epicvoid986** [checkra1n/BugTracker#1699]
**Tell us about your setup:**
1. What iDevice are you using?
ipad 5th generation (celular)
2. On what version of iOS is it?
IpadOS 14.0
3. What version of checkra1n are you using?
11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
macbook pro
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
regular lightning cable from apple
**What are the steps to reproduce the issue?**
1. run the jailbreak with any or all of the checks in options enabled
2. go through the process normally
3.suffer
...

**What do you expect, and what is happening instead?**
i expect for the device to regularly go through the jailbreak process and install checkra1n
in verbose boot i see that something will show up depending on the enabled options and it'll stay on that and then boom, boots right back into stock ios with no jailbreak and checkra1n will stay on 'booting' for a while and after a minute or so it will show:

Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes, as stated before, no matter what i click, it happens

**Any other info, error logs, screenshots, ...?**
I didn't restore the system before updating which could be it and i've tried restoring my Ipad many times.

**Comment by networkextension** [comment]
iPad Pro 9.7 , iOS 12.0 also hung in Boot, then show Error code: -20

**Comment by ghost** [comment]
Check #1689 this is a known issue and they're looking into it

**Comment by shoyrock** [comment]
I have the same problem

**Comment by Siguza** [comment]
Duplicate of #1689.
