### ISSUE TITLE
Loader crashes when installing Cydia

### ISSUE THREAD

**Issue by jcarlosperez** [checkra1n/BugTracker#17]
**What device + iOS version are you on?**

iPad 6th Gen Wifi 13.2.2

**What are the steps to reproduce the issue?**
1. Jailbreak with Checkra1n
2. Open the checkra1n app on the device
3. Tap Cydia under available installations
...

**What do you expect, and what is happening instead?**

Cydia is expected to be installed but instead, the app crashes upon tapping on the cell.

**Comment by woachk** [comment]
Issue #2 duplicate.
