### ISSUE TITLE
Getting a boot loop even on safe mode 

### ISSUE THREAD

**Issue by worf1337** [checkra1n/BugTracker#1702]
**Tell us about your setup:**
1. What iDevice are you using? iPhone SE
2. On what version of iOS is it? 13.5.1
3. What version of checkra1n are you using? 0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)? Linux Mint 18
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Official Apple Cable

**What are the steps to reproduce the issue?**
1. Install bad tweak
2. Forget to install Substrate Safe Mode
3. Reboot with checkra1n in safe mode
4. Wait for it.
5. Done. It'll reboot when it's supposed to start Springboard
...

**What do you expect, and what is happening instead?**
I expect it to boot into springboard, but it just reboots right before it;s supposed to do it

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
The tweak was a bluetooth file sharing one. It had a suspiciously long list of dependencies
Also, this doesn't happen when I boot w/o checkra1n open

**Comment by SwiftMove** [comment]
Try using v0.10.2 instead and see if you still have the same issue.

**Comment by worf1337** [comment]
Resolved by updating to iOS 14 and rejailbreaking
