### ISSUE TITLE
IOS 14 jailbreak on iphone 6s plus keeps showing error code 63

### ISSUE THREAD

**Issue by lekantolu** [checkra1n/BugTracker#1703]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 6s plus
2. On what version of iOS is it? IOS 14
3. What version of checkra1n are you using? 0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? 3rd party

**What do you expect, and what is happening instead?**
I expected it to jailbreak but it just seems to boot without jailbreak

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
No

**Comment by DEALWITHIT199** [comment]
If you are using a 3rd party cable you will definitely get an error. Please use the original apple cable of your iDevice or use a High quality cable and Try changing from USB 2.0 (black port) to 3.0 (blue port) and vice versa. if still getting errors then get a better high quality cable. Thank you!

**Comment by n0k0m3** [comment]
You didn't provide a step to reproduce the issue. Please don't alter the given template, it's given for a reason. Also fill out your host system, if it's on a VM there maybe some issue with it and devs need to know it

Also, @DEALWITHIT199, any MFI certified cable will work, just a few 3rd party cables which are not compatible. USB 2 or 3 port doesn't matter. This may also just be a host machine setup error and nothing else, maybe also a cable error, but saying "using a 3rd party cable you will definitely get an error" is just wrong.

**Comment by DEALWITHIT199** [comment]
> You didn't provide a step to reproduce the issue. Please don't alter the given template, it's given for a reason. Also fill out your host system, if it's on a VM there maybe some issue with it and devs need to know it
> 
> Also, @DEALWITHIT199, any MFI certified cable will work, just a few 3rd party cables which are not compatible. USB 2 or 3 port doesn't matter. This may also just be a host machine setup error and nothing else, maybe also a cable error, but saying "using a 3rd party cable you will definitely get an error" is just wrong.

Sorry. Just trying to help

**Comment by DEALWITHIT199** [comment]
Umm. Did you press trust when you connect your phone in checkra1n? Just asking. Because I got this error too in my iPhone 6s but the problem is that I forgot to press “trust” when I connect my iDevice into my pc.

**Comment by DEALWITHIT199** [comment]
And one thing, USB Slot 2.0 and 3.0 "DOES" matter and some 3rd party cables do not work.

**Comment by DEALWITHIT199** [comment]
> **Tell us about your setup:**
> 
> 1. What iDevice are you using? iPhone 6s plus
> 2. On what version of iOS is it? IOS 14
> 3. What version of checkra1n are you using? 0.11.0
> 4. What is your host system (OS version? Hackintosh? VM? etc.)?
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? 3rd party
> 
> **What do you expect, and what is happening instead?**
> I expected it to jailbreak but it just seems to boot without jailbreak
> 
> **Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
> Yes
> 
> **Any other info, error logs, screenshots, ...?**
> No

Umm. Did you press trust when you connect your phone in checkra1n? Just asking. Because I got this error too in my iPhone 6s but the problem is that I forgot to press “trust” when I connect my iDevice into my pc.

**Comment by DEALWITHIT199** [comment]
> You didn't provide a step to reproduce the issue. Please don't alter the given template, it's given for a reason. Also fill out your host system, if it's on a VM there maybe some issue with it and devs need to know it
> 
> Also, @DEALWITHIT199, any MFI certified cable will work, just a few 3rd party cables which are not compatible. USB 2 or 3 port doesn't matter. This may also just be a host machine setup error and nothing else, maybe also a cable error, but saying "using a 3rd party cable you will definitely get an error" is just wrong.

And one thing, USB Slot 2.0 and 3.0 "DOES" matter and some 3rd party cables do not work. you have your own opinions and I have my own, end of discussion.

**Comment by DEALWITHIT199** [comment]
> You didn't provide a step to reproduce the issue. Please don't alter the given template, it's given for a reason. Also fill out your host system, if it's on a VM there maybe some issue with it and devs need to know it
> 
> Also, @DEALWITHIT199, any MFI certified cable will work, just a few 3rd party cables which are not compatible. USB 2 or 3 port doesn't matter. This may also just be a host machine setup error and nothing else, maybe also a cable error, but saying "using a 3rd party cable you will definitely get an error" is just wrong.

And one thing, USB Slot 2.0 and 3.0 "DOES" matter and some 3rd party cables do not work. you have your own opinions and I have my own, I'm just trying to help the person and now your like complaining and plus... you didn't even helped. End of Discussion!.

**Comment by lekantolu** [comment]
I figured it out
You have to replace the jailbreak tool with a new one
The old one was probably corrupted

**Comment by lekantolu** [comment]
M SORRY ABOUT THAT

**Comment by DEALWITHIT199** [comment]
> I figured it out You have to replace the jailbreak tool with a new one The old one was probably corrupted
> […](#)

Congrats! You found the solution and sorry that I wasn’t replying anymore.

**Comment by DEALWITHIT199** [comment]
> M SORRY ABOUT THAT
> […](#)

Its fine. Im sorry too because I wasn’t replying a long ago.
