### ISSUE TITLE
Where do I report sellers?

### ISSUE THREAD

**Issue by worf1337** [checkra1n/BugTracker#1704]
Hi there,

I found a scammer who attempted to sell a 'Checkra1n Windows Tool'.

Where do I report them?

**Comment by Siguza** [comment]
I'm assuming you're talking about this? https://github.com/checkra1n/BugTracker/issues/1666#issuecomment-698831637

@rickmark can you handle this?

**Comment by worf1337** [comment]
Yes that's it.

**Comment by rickmark** [comment]
Copyright Infringement
https://support.google.com/legal/answer/3110420?hl=en

Malware
https://safebrowsing.google.com/safebrowsing/report_badware/?hl=en

**Comment by Siguza** [comment]
So... closing this as "no further action needed", I guess?
