### ISSUE TITLE
No Checkra1n loader on iPhone SE

### ISSUE THREAD

**Issue by Jamieplayz29** [checkra1n/BugTracker#1708]
I just attempted to jailbreak my iPhone SE (1st gen) on iOS 14 using the checkra1n beta 0.11.0, everything went fine but there is no checkra1n app installed on my phone. I disabled my password, restored my device, waited 30 mins after the jailbreak while still plugged in and tried jailbreaking from CLI, on CLI i get the error: -20 and my phone just reboots, i haven't jailbroken on iOS 14 yet so i don't have any tweaks installed, when using the GUI it tells me that its 'all done', my phone comes up with the checkra1n logo and the lines of code while jailbreaking but the loader just doesn't get installed.

**Comment by demhademha** [comment]
Can you ssh in via port 44?

**Comment by superrnovae** [comment]
Same issue here, both on 14.0 and 14.0.1
Worked just fine on 13.7

**Comment by superrnovae** [comment]
> Can you ssh in via port 44?

I'm able to ssh via port 2222.

**Comment by demhademha** [comment]
Ok, after jailbreaking, type "uicache -a" (without the quotes) does the checkra1n app that appear for you?

**Comment by Siguza** [comment]
Assuming this is the same as #1690.
