### ISSUE TITLE
SMB Server in Files app failed to connect

### ISSUE THREAD

**Issue by yur1xpp** [checkra1n/BugTracker#171]
**What device + iOS version are you on?**
iPhone X, iOS 13.2.2

**What checkra1n version are you using?**
0.9.1

**What are the steps to reproduce the issue?**
1. Connect to any SMB server on File app (https://www.reddit.com/r/ios/comments/d82piq/pro_tip_sharing_between_pc_and_ios_using_smb_and/)
2. It stuck at loading and connecting

**What do you expect, and what is happening instead?**
To load the files. Prior to jailbreak, SMB connection in File app does work. However, SMB connection works fine in Filza.

**Any other info, error logs, screenshots, ...?**
-

Thank you guys!

**Comment by RonaldRegister** [comment]
Same issue here. 0.9.2 iPhone X 13.2.2

Will not connect to share from inside Files.app. Trying to add the share again lets it stay stuck at connecting screen.

Booted in unjailbroken mode, there it adds and connect instant. Booted into checkra1n, the share is still added to the list, but unable to select or open it.

**Comment by infernoboy** [comment]
This appears to be because the process GSSCred is repeatedly crashing. Doesn't crash when using checkra1n "Safe Mode", but still crashes in "normal" safe mode.

[GSSCred Crash Log via Cr4shed.txt](https://github.com/checkra1n/BugTracker/files/3991074/GSSCred.Crash.Log.via.Cr4shed.txt)

**Comment by RonaldRegister** [comment]
Just tried with 13.3 checkra1n 0.9.7 issue still present.

(Not that big of a deal, because files.app is buggy a.f. anyway. I’m using Filebrowser from the appstore for accessing smb-shares)

**Comment by PlanetAaron** [comment]
The issue is still present in Checkra1n 0.9.8
I'm 100% positive the issue is with substrate

**Comment by PlanetAaron** [comment]
So it seems like this happens because when you try and add a server, it sends GSSCred into a crash loop. I assume whatever it is is required for the smb support. It crashes on a loop until next reboot and ldrestart does not fix it. I will try and get a crash log later today. 

This issue also happens with unc0ver so if it is substrate, the fork of substitute used by unc0ver has a similar one. 

Edit: here’s a crash log from my iPad. [https://hastebin.com/raw/omilezejiq](url)

**Comment by yur1xpp** [comment]
@sbingner perhaps you could comment on this?

**Comment by Brandon4466** [comment]
Yep, same problem with me! Here is my log if it helps: 
[text.txt](https://github.com/checkra1n/BugTracker/files/4314133/text.txt)

It constantly crashes too, I tried swiping the files app away and respringing, Cr4shed just gives me endless notifications over and over about GSSCred crashing until I reboot.

**Comment by tomatotango** [comment]
Also facing this issue. I’d provide logs but unfortunately I had to unjailbreak as my workflow relies on accessing smb shares. Someone suggested disabling GSSCred daemon using Choicy but didn’t work in my case. Look forward to a fix in the near future :)

**Comment by vniehues** [comment]
I have the same issues as well. But im using Unc0ver on an iPhone 11 Pro (256gb). Does that help at finding the culprit?

**Comment by Randomblock1** [comment]
Same issue, iPhone 8+ iOS 13.3 checkra1n 0.10.1.
Still sends GSSCred into a crash loop, unfortunately.

**Comment by shadowscott** [comment]
Same here. iPhone X 13.3.1. Disabled tweak injection from Choicy but still crashing when accessing company web site. @sbingner @Siguza 

https://pastebin.com/fJsjhgQM

**Comment by asislife20** [comment]
Same for me on latest checkra1n and iOS 13.4.1. 
[text.txt](https://github.com/checkra1n/BugTracker/files/4568639/text.txt)

**Comment by shadowscott** [comment]
@sbingner @Siguza Is there an update on this? Substitute was fixed to support this.

**Comment by RonaldRegister** [comment]
Issue still exists on 13.5. Would really like this fixed, but I don't know if this is a priority for the devs? I can imagine other issues (and their deserved free time) are higher on the list. So this is a friendly reminder/request.

**Comment by illixion** [comment]
Just found this issue on Google. Exactly the same problem here, would love to see it fixed.

**Comment by Siguza** [comment]
Issue #1467 contains a lot more info on this, so I'll close this as a duplicate of that one, even though this one is much older.
