### ISSUE TITLE
No checkra1n loader app after successful jailbreak on iPadOS 14.0

### ISSUE THREAD

**Issue by superrnovae** [checkra1n/BugTracker#1713]
**Tell us about your setup:**
1. What iDevice are you using? iPad Air 2 (WiFi)
2. On what version of iOS is it? 14.0
3. What version of checkra1n are you using? 0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)? Debian Bullseye
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Original cable

**What are the steps to reproduce the issue?**
1. Install ios 14.0 or 14.1
2. Jailbreak via GUI
3. Boot your device
...

**What do you expect, and what is happening instead?** Jailbreak succeeds, but there is no checkra1n loader app.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?** Yes.

**Any other info, error logs, screenshots, ...?**Can ssh into the device on port 2222, but apt can't be used. https://i.imgur.com/NbRAR6I.png

**Comment by demhademha** [comment]
If you can ssh in, try "uicache -a" without the quotes,

**Comment by superrnovae** [comment]
> If you can ssh in, try "uicache -a" without the quotes,

That did not help.

**Comment by demhademha** [comment]
Which part did not help?
Are you unable to ssh in or are you unable to run uicache?

**Comment by superrnovae** [comment]
> Which part did not help?

Sorry, I was able to do both.  (ssh on port 2222, and ran uicache -a, and waited for it to finish) But loader app still is not showing on the home screen, nor in the settings.

**Comment by superrnovae** [comment]
So, is there nothing that can be done from my part? 
I have tried checkra1n on debian bullseye, checkn1x, bootra1n (it's broken btw). Always the same result.
iPad is jailbreaked, i can ssh into it. But Loader app is not on the desktop, and neither in the search, so i can't install cydia.
Btw iPad is icloud bypassed, not like it should matter, because everything worked just fine on 13.7. The issue is that i can't install cydia, and can't install filza, which means i can't sideload any .ipa apps.
uicache -a works, but doesn't help.
In /var/binpack/applications/loader.app loader does exist.

**Comment by demhademha** [comment]
Maybe apple added mitigation's on ios 14, for icloud bypassed devices, I'm not  sure about this.

**Comment by superrnovae** [comment]
> Maybe apple added mitigation's on ios 14, for icloud bypassed devices, I'm not sure about this.

I mean, device gets jailbroken just fine, there's something else going on.

**Comment by jaydev79** [comment]
I also have the same problem on my iPhone 6s It was on Ios 14 it didn't show the checkra1n app then I tried 14.0.1 still didn't show. I also tried Linux arm and MacBook 2019 and mid-2012 both mac os Catalina.

**Comment by superrnovae** [comment]
> I also have the same problem on my iPhone 6s It was on Ios 14 it didn't show the checkra1n app then I tried 14.0.1 still didn't show. I also tried Linux arm and MacBook 2019 and mid-2012 both mac os Catalina.

UPD: restored via iTunes and jailbreaked using MacBook, and FINALLY loader app showed up.

When jailbreaking via GUI it will indicate that jailbreak succeeded, even when last step (bootstrap) failed. 
When jail breaking via CLI mode, it logs that Jailbreak succeeded but last step always fails and it retries the jailbreak over and over again. 
Seems to be an issue with usbmuxd, it's unable to find the device on bootstrap, so the device reboots jailbreaked but loader app isn't there.

**Comment by jaydev79** [comment]
Did you use CLI mode or GUI mode and were you able to restore a backup because when I restored my phone on my macbook it still doesn't work

**Comment by Siguza** [comment]
Assuming this is the same as #1690.
