### ISSUE TITLE
Error when installing checkra1n on Ubuntu 20

### ISSUE THREAD

**Issue by RustedMachine** [checkra1n/BugTracker#1714]
Ipa**Tell us about your setup:**
1. What iDevice are you using? Ipad air 2
2. On what version of iOS is it? 13.4.1
3. What version of checkra1n are you using? 0.11.0
4. What is your host system Ubuntu 20

**What are the steps to reproduce the issue?**
1. Using the terminal put in code to install checkra1n 
2. Get error message checkra1n does not install 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**
After running all code for install. Get error message about unmet dependencies. Checkra1n did not install. Last version of checkra1n 0.10.2 had no issues installing. Just the new version. Here is a pic of the terminal after running all the code. 
![20200928_093527](https://user-images.githubusercontent.com/46599736/94442916-85587b00-0172-11eb-8bac-f113301dd112.jpg)

**Comment by superrnovae** [comment]
Looks like ubuntu 20 installs libncurses6 by default, and checkra1n requires libncurses5 that is available from the universe repository. 
I think you should be able to install libncurses5 alongside libncurses6.

**Comment by RustedMachine** [comment]
> Looks like ubuntu 20 installs libncurses6 by default, and checkra1n requires libncurses5 that is available from the universe repository.
> I think you should be able to install libncurses5 alongside libncurses6.

Thanks, I will give that a try this evening. I also tried Ubuntu 18 and got the same results as I did with 20.

**Comment by RustedMachine** [comment]
> Looks like ubuntu 20 installs libncurses6 by default, and checkra1n requires libncurses5 that is available from the universe repository.
> I think you should be able to install libncurses5 alongside libncurses6.

Ok so checkra1n installed but will not open. When I click on the icon nothing happens.

**Comment by Siguza** [comment]
Try running `checkra1n` on the command line, that should at least tell you why it isn't opening.

Also paging @nikias, is there anything that can be done about ncurses?

**Comment by nikias** [comment]
@Siguza I guess we could link against libncurses6, need to check...

**Comment by RustedMachine** [comment]
> Try running `checkra1n` on the command line, that should at least tell you why it isn't opening.
> 
> Also paging @nikias, is there anything that can be done about ncurses?

This is what is get when I run checkra1n. I hope im doing it right still learning Linux. 
![20200928_194049](https://user-images.githubusercontent.com/46599736/94496581-c4162180-01c2-11eb-8175-88cbf26fd63d.jpg)

**Comment by nikias** [comment]
@RustedMachine what does `apt show libimobiledevice6` show you?

**Comment by nikias** [comment]
nevermind, I saw that the dependencies are set to `libimobiledevice6 >= 1.2.0` for `checkra1n`, we need to fix this.
In the meantime, you can install the one from the checkra1n repo:
```
sudo apt install libimobiledevice6=1.3.0-3
```

**Comment by RustedMachine** [comment]
> nevermind, I saw that the dependencies are set to `libimobiledevice6 >= 1.2.0` for `checkra1n`, we need to fix this.
> In the meantime, you can install the one from the checkra1n repo:
> 
> ```
> sudo apt install libimobiledevice6=1.3.0-3
> ```

I will try this and let you know. At least now i know its not me doing something wrong.

**Comment by RustedMachine** [comment]
> nevermind, I saw that the dependencies are set to `libimobiledevice6 >= 1.2.0` for `checkra1n`, we need to fix this.
> In the meantime, you can install the one from the checkra1n repo:
> 
> ```
> sudo apt install libimobiledevice6=1.3.0-3
> ```

This worked! Checkra1n 0.11.0 opened! Thank you for all the help. Now need to stop letting my ipad die......

**Comment by RustedMachine** [comment]
It worked no problem after getting checkra1n to install and run. Thanks again.

**Comment by Siguza** [comment]
Package on the repo has been updated to require libimobiledevice >=1.3.0, which should fix this.
