### ISSUE TITLE
Error -20 while booting 

### ISSUE THREAD

**Issue by abc123000111** [checkra1n/BugTracker#1715]
My device is iPad Pro (1st gen, A9X) 12.9, iPadOS 14.0. When the program runs on my MacBook (OS X 10.15.2), it shows that "Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)" during booting and my iPad opened without any changes. I switched the "safe mode" on but got the same message. I don't know why. Could you please help me out? Thank you so much!

**Comment by EliasSfeir** [comment]
Seems that it doesn't support A9X, having the same issue with my iPad pro 1st gen and several other users, there are several opened issues opened about this

**Comment by Tmarkr** [comment]
having the same problem on  5th gen iPad... hoping that its just he "beta" and there will be a fix soon

**Comment by n0k0m3** [comment]
Same issue as #1692

**Comment by Siguza** [comment]
Marking as dupe of #1689.
