### ISSUE TITLE
restore system did not remove /var/binpack

### ISSUE THREAD

**Issue by adm1n007** [checkra1n/BugTracker#1716]
restore system did not remove /var/binpack
should delete it please?

**Comment by demhademha** [comment]
Restore rootfs doesn't touch anything in /var

**Comment by adm1n007** [comment]
> Restore rootfs doesn't touch anything in /var

Thank you for replying.
Is there any way to completely clean the jailbreak files to make the iphone unjailbreak back?

**Comment by n0k0m3** [comment]
Use Succession Restore here: https://github.com/Samgisaninja/SuccessionRestore
Or a DFU restore

**Comment by adm1n007** [comment]
> Use Succession Restore here: https://github.com/Samgisaninja/SuccessionRestore
> Or a DFU restore

awsome! thx very much!!
