### ISSUE TITLE
Iphone X 13.7 error -20

### ISSUE THREAD

**Issue by ImaBossYo** [checkra1n/BugTracker#1719]
**Tell us about your setup:**
1. What iDevice are you using?
Iphone X
2. On what version of iOS is it?
13.7
3. What version of checkra1n are you using?
0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOS Catalina 10.15.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB A
**What are the steps to reproduce the issue?**
1. Use Checkra1n (used on safe mode as well)
2. Get Apple screen with checkra1n logo and code, then my phones screen goes black
3. Apple logo with no code for about 5 seconds then phone boots up and asks for password, like all I did was power off my phone.
...

**What do you expect, and what is happening instead?**
I try to use checkra1n to jailbreak my phone and I get error -20

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes.

**Any other info, error logs, screenshots, ...?**

![Screen Shot 2020-09-30 at 10 35 48 AM](https://user-images.githubusercontent.com/72060544/94699782-b66ab400-0308-11eb-948a-abb011aa202c.png)
I have already tried a phone wipe (when I did my jailbroken apps like Filza, Apps Manager, and Cydia were still there), when I did so it jailbroke successfully then my phone randomly powered off and my jailbreak was gone after about 2 seconds of my phone successfully jailbreaking I didn't even get through the lock screen, I have already tried MinaUSB and that was not successful, I got to diagnostic used it and I did not see "All Done" on the checkra1n screen and MinaUSB did not say successfully patched. Please Help!

**Comment by ImaBossYo** [comment]
Edit: I have also jailbroken my phone over 10 times and have never had this issue.

**Comment by n0k0m3** [comment]
What's the output on the screen when you run it on verbose mode?

**Comment by ImaBossYo** [comment]
I got to all done then my phone turned on then it randomly rebooted when I got to the home screen :/ and it didn't work and told me to put in my password. when it rebooted it also said "unlock iPhone to use accessories" or something like that.

**Comment by n0k0m3** [comment]
Can you take a screenshot/video of the phone with checkra1n running with verbose mode on?

**Comment by ImaBossYo** [comment]
I have the video I'm having trouble sending it on my phone? How do I do so?

**Comment by n0k0m3** [comment]
Upload on streamable or gfycat or somewhere else

**Comment by ImaBossYo** [comment]
You got an email I can just send it there?

**Comment by ImaBossYo** [comment]
[](https://gfycat.com/demandinglittledobermanpinscher)

**Comment by ImaBossYo** [comment]
https://gfycat.com/demandinglittledobermanpinscher

**Comment by ImaBossYo** [comment]
When the video goes black it's my phone going black btw

**Comment by n0k0m3** [comment]
Try 0.10.2 then. It seems like the new patch finder caused kernel panic

**Comment by ImaBossYo** [comment]
Should I use safe mode or verbose or allow untested?

**Comment by n0k0m3** [comment]
Allow untested

**Comment by ImaBossYo** [comment]
I did so then I got to all done, phone booted up and then it shut down and Apple logo appeared and then "unlock iPhone to use accessories." I bet if I do it again I'll get the same thing that happened in the video I sent.

**Comment by ImaBossYo** [comment]
Dude, I really appreciate the time you're using trying to help me. ☺️

**Comment by ImaBossYo** [comment]
I'm gonna go to sleep, so if you can find a solution for me I'll try it in the morning, I get up at around 7 am EST. Thanks 🙏

**Comment by long36708** [comment]
> 我要去睡觉了，所以如果您能为我找到解决方案，我会在早上尝试，我将在美国东部标准时间早上7点起床。谢谢🙏

I have the same problem as you.If you find a solution，please tell me about it

**Comment by faltugyan** [comment]
have same issue with ios13.5.1 :(

**Comment by Siguza** [comment]
Most likely the same issue as #1689.
