### ISSUE TITLE
<Error>: usbmux: Failed to connect (error code: -79)

### ISSUE THREAD

**Issue by rMutaev** [checkra1n/BugTracker#1725]
Tell us about your setup:
1. iPhone X
2. 13.6
3. checkra1n 0.11.0, 0.10.2
4. Linux XUBUNTU, Linux Mint
5. Connected via 3 orig cables lightning - USB-A

What are the steps to reproduce the issue?
1. Plug-in iPhone
2. Entering DFU mode manually
3. Start checkra1n with arguments: -s -c -v -V
...

What do you expect, and what is happening instead?
Expected success in jailbreak, but took:
<Error>: usbmux: Failed to connect (error code: -79)
sometimes:
<Error>: libusb: Failed to get active config descriptor: LIBUSB_ERROR_NOT_FOUND

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
Yes

Story: my jailbreak was broken by some tweak who took my iPhone into infinite respring, that forced me to reboot my phone and lose the jailbreak. After that i tried re-jailbreak and faced with usbmux problem. 2 days i spent to fix that problem, tried every suggestion (i think so) here and on reddit, nothing helps. 
Changed 4 cables (3 orig & 1 MFI lightning - USB-A) with 9 USB ports (used 2 PC), tried bootra1n, checkn1x, checkra1n 0.10.2, 0.11.0 in GUI & CLI mode, nothing helped me to pass -79 error. 
I'm upset and depressed :c 
Any ideas?

Any other info, error logs, screenshots, ...?
![Screenshot from 2020-10-02 02-09-54](https://user-images.githubusercontent.com/72232660/94872199-a6f88180-0454-11eb-894e-30f990617321.png)

**Comment by bakedpotato191** [comment]
Are you on AMD motherboard?

**Comment by superrnovae** [comment]
Are you by chance on a AMD motherboard?

**Comment by Sandwhich253989** [comment]
Duplicate of #1689 except that this is a different device
And version

**Comment by rMutaev** [comment]
> Are you by chance on a AMD motherboard?

No. My notebook (Fujitsu Lifebook T4215) and All-in-One PC Sony (VPCL22S1R) using their own motherboard
