### ISSUE TITLE
Checkra1n 0.11.0 stuck at booting stage error -20 

### ISSUE THREAD

**Issue by faltugyan** [checkra1n/BugTracker#1728]
**Tell us about your setup:**
1. What iDevice are you using? 
iphone X 
2. On what version of iOS is it?
iOS 13.5.1
3. What version of checkra1n are you using?
checkra1n 0.11.0 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOS Catalina 10.15.5 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A to lightning 
**What are the steps to reproduce the issue?**
1.  Safe mode
2.  Untested mode 
3.
...

**What do you expect, and what is happening instead?**
Get Apple screen with checkra1n logo and code, then my phone's screen goes black. Apple logo with no code for about 5 seconds then the phone boots up and asks for a password, like all I did was power off my phone.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
YES

**Any other info, error logs, screenshots, ...?**
![IMG_3815](https://user-images.githubusercontent.com/72301934/94990567-c26da480-059a-11eb-9dfd-fedf96e7ea1f.jpg)

**Comment by superrnovae** [comment]
Have you tried older versions of checkra1n?

**Comment by faltugyan** [comment]
> Have you tried older versions of checkra1n?

But older version is only 13.5 or lower ; any idea if it works for 13.5.1 ? Didn’t try for this reason

**Comment by superrnovae** [comment]
> > Have you tried older versions of checkra1n?
> 
> But older version is only 13.5 or lower ; any idea if it works for 13.5.1 ? Didn’t try for this reason

older versions of **checkra1n**, NOT iOS.

**Comment by Siguza** [comment]
Considering this a dupe of #1689.

**Comment by faltugyan** [comment]
> > > Have you tried older versions of checkra1n?
> > 
> > 
> > But older version is only 13.5 or lower ; any idea if it works for 13.5.1 ? Didn’t try for this reason
> 
> older versions of **checkra1n**, NOT iOS.

yeah that waht i said **checkra1n** 0.10.2 does not 'officially' support iOS above 13.5
