### ISSUE TITLE
Stalling on "Download mode device disconnected"

### ISSUE THREAD

**Issue by TateB** [checkra1n/BugTracker#173]
**What device + iOS version are you on?**
iPhone 6s Plus, iOS 13.2.2

**What checkra1n version are you using?**
0.9.1

**What are the steps to reproduce the issue?**
1. Put iPhone in DFU mode
2. Run checkra1n in verbose mode

**What do you expect, and what is happening instead?**
Expect the jailbreak to execute, instead it hangs on "Download mode device disconnected", then boots into normal iOS.
Additionally, while in normal recovery mode (put by the GUI), entering DFU mode seems to not be possible? Just restarts into recovery mode again.

**Any other info, error logs, screenshots, ...?**

Log:
```
- [*] DFU mode device found
- [*] == Checkm8 Setup stage ==
- [*] Entered initial checkm8 state after 3 steps, issuing DFU abort..
- [*] DFU device disconnected
- [*] DFU mode device found
- [*] == Checkm8 Trigger stage ==
- [*] Checkmate!
- [*] DFU device disconnected
- [*] DFU mode device found
- [*] == Checkm8 Trying to run payload... ==
- [*] If everything went correctly, you should now have code execution.
- [*] DFU device disconnected
- [*] Download mode device found
- [*] Download mode device disconnected
```

**Comment by shehzaad10** [comment]
I am getting stuck in the same stage as you. I have tried restoring from fresh but can’t get further than this.

**Comment by kpwn** [comment]
How did you enter DFU? Please try entering DFU from recovery mode, not normal mode. I suspect the issue happens due to panic log saving, which will reset iBoot, thus rebooting the device.

A panic log is generated when entering DFU from normal mode.

**Comment by TateB** [comment]
Entering DFU from recovery is seemingly impossible. I’ve tried a million different ways to enter it, and unless I’m doing something crucially wrong, it seems that no matter what it’ll just bring me back to normal recovery mode.

**Comment by kpwn** [comment]
Here's a trick to enter DFU reliably and in a stable way (assumes you have libimobiledevice installed):

1. enter recovery mode
2. type irecovery -n in a terminal window (but don't press enter)
3. press volume down & power
4. whle holding them pressed, quickly press enter in terminal
5. wait until screen goes black, wait another 2 seconds, release power button holding volume
6. wait another 10s and you should be in clean DFU


EDIT-- actually, this is a 6s, so use home button instead of volume

**Comment by TateB** [comment]
I'm seriously confused as to what I'm doing wrong.
If I'm not mistaken DFU mode should not show an Apple logo when it goes into it, however almost immediately when executing irecovery -n, the Apple logo appears, no matter how long I hold the power button or home button.

EDIT: Ok, turns out the real problem was using a USB-C lighting cable.

**Comment by littlelailo** [comment]
Ok so this issue is resolved?

**Comment by pich4ya** [comment]
well, to fix this. 

you need to switch from USB-C-to-lightning cable to genuine Apple's USB 2.0-to-lightning cable!

**Comment by gamersi** [comment]
Im in DFU mode and booting into DFU from recivery with an USB-A cable and I have the same issue(Ipad 7 wifi with ios 15)

**Comment by FreQRiDeR** [comment]
same bug. lame
