### ISSUE TITLE
Boot failure

### ISSUE THREAD

**Issue by cmgamer** [checkra1n/BugTracker#1730]
**Tell us about your setup:**
1. What iDevice are you using? iPad Pro 1st gen 12.9
2. On what version of iOS is it? 14.0
3. What version of checkra1n are you using? 0.11.0
4. What is your host system (OS version Hackintosh? VM? etc.)? Catalina
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB hub. USB A to lightening. 

**What are the steps to reproduce the issue?**
1. Enter DFU
2. Click start
3. Checkra1n logo, boot info, device reboots
...

**What do you expect, and what is happening instead?** boot into jailbroke mode. Reboots instead. 

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?** yes

**Any other info, error logs, screenshots, ...?**
No

**Comment by worf1337** [comment]
What tweaks do you have installed?

Also boot into your device without checkra1n and go to Privacy, Analytics & improvements, and search for 
panic.

Paste the logs.

**Comment by cmgamer** [comment]
Fresh upgrade so no tweaks. Searched for panic logs, couldn’t find any. There were logs present but no panics. This is the initial jailbreak after the upgrade so I don’t even have Cydia installed. I’m having the same issue with my iPad 5 and I did a full restore on it. Any suggestions?
Thank you!

**Comment by Siguza** [comment]
Most likely the same issue as #1689.

**Comment by cmgamer** [comment]
It’s closed? What was the verdict? No help?

**Comment by Siguza** [comment]
See #1689: reproduced and working on a fix.
