### ISSUE TITLE
Error code -77 -79 time out

### ISSUE THREAD

**Issue by ShawnTimez** [checkra1n/BugTracker#1732]
**Tell us about your setup:**
1. What iDevice are you using?
Ipad 5th gen model number A1822

2. On what version of iOS is it?
ios 14.0.1
3. What version of checkra1n are you using?
Checkra1n version 0.11.0

4. What is your host system (OS version? Hackintosh? VM? etc.)?
I've tried mac os, I've tried Linux (Ubuntu)and I've also tried the new 1.1.2 checkn1x and the new bootra1n
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

USB-A lightning to USB 3.0

**What are the steps to reproduce the issue?**
1. Connect phone to computer
2. Attempt jailbreak using checkra1n 0.11.0
3. Hangs on booting (the ipad boots up but not jailbroken) checkra1n errors with -77 or -79 USBMUX
...

**What do you expect, and what is happening instead?**
I expect it to successfully jailbreak as its a Gen5 using the supported A9 processor. I suspect it is because the device is locked as error -77  or -79 using ubuntu usbmux has to do with trust ive heard people say the fix for this is to type in the passcode but I do not know it. Other versions of checkra1n bypassed it. Is this an issue with the current state of checkra1n 0.11.0 or is this on my end?

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes 

**Any other info, error logs, screenshots, ...?**
The device is Icloud locked generation 5 ipad running on ios version 14.0.1 if it was a matter of software not being ready id understand but others are saying they are having success and i continue to get the same error. I've tried different cables different ports different OS. Im convinced checkra1n 0.11.0 isn't ready for an iPad 5th gen running ios 14.0.1

Can anyone help?

**Comment by Siguza** [comment]
Most likely the same issue as #1689.
