### ISSUE TITLE
Cannot start Checkra1n on El Capitan

### ISSUE THREAD

**Issue by techstuffandparts** [checkra1n/BugTracker#1733]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. Macbook pro 2012
2. 10.11.2 El Capitan
3.I have tryed 0.10.1 , 0.10.2 0.11.0
...
I'm runing the image on my macbook pro , no vm no hackintosh
**What do you expect, and what is happening instead?**
I expect that the program should start normally, instead i get an error which i will atach here.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
I cannot even start the app.

**Any other info, error logs, screenshots, ...?**
I will attach it here.
![Screen Shot 2020-10-04 at 18 24 21](https://user-images.githubusercontent.com/65084825/95019786-0383b880-0670-11eb-9263-e8fcb918f594.png)

**Comment by techstuffandparts** [comment]
I have fixed it with the new update of el capitan.

**Comment by Siguza** [comment]
I'm not exactly sure how this works, but AFAIK the MobileDevice framework is a component that can be updated independently.  
Since you said you fixed this though... I'm gonna close this as "no action needed" unless you tell me otherwise?
