### ISSUE TITLE
USB Error -76

### ISSUE THREAD

**Issue by CodeWithShreyans** [checkra1n/BugTracker#1741]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 6S
2. On what version of iOS is it? 13.5.1
3. What version of checkra1n are you using? Beta 0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)? Arch Linux x64
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple USB-A to Lightning

**What are the steps to reproduce the issue?**
1. `sudo checkra1n` in commandline
2. Go through the whole process
3. Fails after `Booting` phase
...

**What do you expect, and what is happening instead?**
I expect the jailbreak to be successful but it fails with USB Error -76

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Not tried safe mode, should I?

**Any other info, error logs, screenshots, ...?**
![Screenshot from 2020-10-08 19-59-45](https://user-images.githubusercontent.com/70191184/95474160-6f349100-09a2-11eb-91b4-75c39dc6b19a.png)

**Comment by brunogrcsada** [comment]
Restart your machine, ensure that you are running your shell as root and change the USB port you are using to connect the cable to your iPhone... See if that helps

**Comment by CodeWithShreyans** [comment]
Tried all of it but did not work

**Comment by brunogrcsada** [comment]
Try disabling your iPad's passcode. Did you enter a root shell before actually running checkra1n (as in sudo su)? If not, you should try doing so.

**Comment by CodeWithShreyans** [comment]
I did disable the passcode and entering root shell or running with sudo is the exact same thing. Sudo means SUPER USER DO. And BTW just `su` is enough to enter root shell.

**Comment by ShawnTimez** [comment]
The problem is with checkra1n 0.11.0 it has not worked functionally sense its release.

Use checkra1n 0.10.2 and you will have success sense you are only on ios 13.5.1

Edit: they broke checkra1n with a early boot. Causes the software to panic and will boot to home screen. They are working on a new version of checkra1n

**Comment by sourcelocation** [comment]
I also get this error, but my device gets jailbroken...

**Comment by E-lovr** [comment]
what about usb error -66 and error -65

**Comment by Playboikey** [comment]
it used  to work perfectly now when I try it I get USB error code -77 anyone know how to fix
