### ISSUE TITLE
T2 MacBookPro15,1 (j680) not supported yet. 

### ISSUE THREAD

**Issue by alex94562** [checkra1n/BugTracker#1747]
**Tell us about your setup:**
1. What iDevice are you using? T2 MacBookPro15,1 (j680) 
2. On what version of iOS is it? 10.15.7
3. What version of checkra1n are you using? 11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)? MacBook Pro (2017)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-C Charging cable that came with the Mac. 

**What are the steps to reproduce the issue?**
1. Plug in and reconnect a few times until the message says: 
Sorry, Apple T2 MacBookPro15,1 (j680) is not supported.
ECID: 0x162d5c0eea0026

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Comment by zexa** [comment]
Have you tried the cli mode?

**Comment by alex94562** [comment]
Works with CLI mode.

**Comment by ziggystar12** [comment]
Does not work in cli mode. Same message on both cli and in Mac OS.

**Comment by dprishep** [comment]
> Does not work in cli mode. Same message on both cli and in Mac OS.

You can jail ?
