### ISSUE TITLE
iPhone SE 1st Gen on 14.0.1 not supported

### ISSUE THREAD

**Issue by farrukhaskari1** [checkra1n/BugTracker#1748]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone SE 1st Gen
2. On what version of iOS is it?
iOS 14.0.1
3. What version of checkra1n are you using?
0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
10.15.7
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Usb-C to lightening
**What are the steps to reproduce the issue?**
simple steps as per checkra1n app
 
**What do you expect, and what is happening instead?**
to jailbreak with the checkra1n logo, it enters DFU mode and nothing happens

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**

**Comment by worf1337** [comment]
Couldn't reproduce with my own

**Comment by farrukhaskari1** [comment]
are you able to JB?

**Comment by worf1337** [comment]
Yes I am.

Are you by any chance using bootra1n?

**Comment by farrukhaskari1** [comment]
nope. checkra1n says device not supported. I am using it in allow untested mode. and it fails.

**Comment by UInt2048** [comment]
@askari01 Have you tried with a Lightning to USB-A cable? See the known issues.

Also, it's probably due to it being iOS 14.0.1 instead of 14.0.0. Just wait for the next release - it will be out soon.

**Comment by farrukhaskari1** [comment]
checkra1n succeeds in jailbreaking the phone via USB-A cable, but fails to install Cydia. Installing Cydia through impactor only succeeds in loading extender VPN but no success with the Package manager.

**Comment by farrukhaskari1** [comment]
Checkra1n 0.12.0 doesn't show Cydia, but I have Cydia impactor

**Comment by farrukhaskari1** [comment]
worked using  #1830
