### ISSUE TITLE
ipad pro 12,9 inch, 3rd generation, 13.6.1 not supported

### ISSUE THREAD

**Issue by cetoria** [checkra1n/BugTracker#1749]
wanted to jailbreak my device today...

ipad pro 12,9 inch, 3rd generation, 13.6.1 

checkra1n gives for this device not supported device warning...  i check the field "allow not supported" but the start button

is not beeing activated...

is there any possibility to jailbreak this device... maybee in the further versions...

**Comment by demhademha** [comment]
This is device is A12, the checkm8 vulnerability  doesn't work on this device, refer 5o #1,

**Comment by worf1337** [comment]
Allow untested versions is only for when an iOS version is untested
