### ISSUE TITLE
Latest checkra1n beta 0.9.1 bootstrap issue fix

### ISSUE THREAD

**Issue by jack254718** [checkra1n/BugTracker#176]
Right hi peeps. Using the latest beta of checkra1n 0.9.1 I had bootstrap issue.

I then went to storage and found 13.2 update downloaded but not installed, so I deleted that. Tried jailbreaking again and hey presto! It worked!

Try deleting the uodate in your storage If you have one, might help though having bootstrap issue. Also when device rebooted into booting, I pressed and held the volume button. 

Hope this helps. Cydia installs and works fine so far

**Comment by kpwn** [comment]
This is unfortunately a known issue - apparently your phone will try to boot with the downloaded OS filesystem but with an older kernel. We are working on a proper fix.

**Comment by jack254718** [comment]
Good to hear.
