### ISSUE TITLE
Any solution to this error. "Sorry, iPad Mini (WiFi) (iOS 9.3.5) is not supported. ECID: 0xb69e0583ab"

### ISSUE THREAD

**Issue by guilbertguerrA** [checkra1n/BugTracker#1761]

**Comment by Sandwhich253989** [comment]
iOS 9 version not supported

**Comment by fyredragon69** [comment]
iOS 9.3.5 is not supported in checkra1n. If you still want to jailbreak it, you have 2 options which both use Phoenix: Option 1 is to use Cydia Impactor with a Apple Developer account and sideload the ipa onto the device. The second option is to use 3uTools to jailbreak the device, but you'll have to re-jailbreak every so often. I forget how often you have to re-jailbreak though...

**Comment by Siguza** [comment]
32bit devices aren't supported.  
See #1.

**Comment by Bey0ndB1nary** [comment]
> iOS 9.3.5 is not supported in checkra1n. If you still want to jailbreak it, you have 2 options which both use Phoenix: Option 1 is to use Cydia Impactor with a Apple Developer account and sideload the ipa onto the device. The second option is to use 3uTools to jailbreak the device, but you'll have to re-jailbreak every so often. I forget how often you have to re-jailbreak though...

                        I have more complicated scenario.

1.  iPad Mini is in " Activation Lock " due to lost icloud credentials. ( Actually forgot ).
2.  It is updated with version "iOS 9.3.5", is there a way to Jailbreak and unlock it  /  just throw it at bin?
3.  "Phoenix Jailbreak" supports this iOS Version, but it needs to be in a bootable USB method like how "chkRa1n" is available.

Please help.

Thanks.

**Comment by Siguza** [comment]
Nope. Even if 32bit devices were supported (which would take months of work, and pain that we're not willing to go through), you'd still need to then port checkra1n to a different environment like an Arduino, since A5 devices have even more unrealistic requirements when it comes to checkm8.

**Comment by 3looolyyy** [comment]
i have Linux distro on my Device can i use Beta to open it
