### ISSUE TITLE
Checkra1n not jailbreaking iPhone 5S

### ISSUE THREAD

**Issue by fyredragon69** [checkra1n/BugTracker#1764]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 5S
2. On what version of iOS is it? iOS 12.4.8
3. What version of checkra1n are you using? 0.11.0 Beta
4. What is your host system (OS version? Hackintosh? VM? etc.)? Ubuntu 18.04 LTS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB A to Lightning (Official cable)

**What are the steps to reproduce the issue?**
1. Follow usual checkra1n steps to install
2. Start checkra1n and put iDevice in DFU mode
3. Try to jailbreak device
4. Never gets past "Right before trigger"

**What do you expect, and what is happening instead?**
I expect the device to boot back to userland, but it stays in DFU mode and does nothing.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes. The same issue still occurs.

**Any other info, error logs, screenshots, ...?**
![Screenshot from 2020-10-19 15-54-45](https://user-images.githubusercontent.com/51103172/96505075-a10bea00-1223-11eb-8338-dc3ff22888f2.png)

**Comment by ghost** [comment]
I have this issue aswell, running Ubuntu 20.04 LTS, happends in both cli and gui.

**Comment by Siguza** [comment]
Duplicate of #1169.
