### ISSUE TITLE
iPhone 8 plus not supported

### ISSUE THREAD

**Issue by khairi98** [checkra1n/BugTracker#1769]
Tell us about your setup:

What iDevice are you using?
iPhone 8 plus
On what version of iOS is it?
iOS 14.0.1
What version of checkra1n are you using?
0.11.0 beta
What is your host system (OS version? Hackintosh? VM? etc.)?
18A393
How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Usb-C to lightening
What are the steps to reproduce the issue?
simple steps as per checkra1n app
What do you expect, and what is happening instead?
to jailbreak with the checkra1n logo, it enters DFU mode and nothing happens and iPhone 8 Plus gsm has not supported 

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
yes

**Comment by immivip** [comment]
of course not work! even incoming new checkra1n not support IOS14 with A11 yet

**Comment by immivip** [comment]
of course not work! even next version checkra1n will not support IOS14 with A11 yet

**Comment by Siguza** [comment]
See https://checkra.in/news/2020/09/iOS-14-announcement
