### ISSUE TITLE
checkra1n not working on iPad mini 2 Wifi - iOS 12.4.8

### ISSUE THREAD

**Issue by KodzghlyCZ** [checkra1n/BugTracker#1771]
I am using Apple iPad mini 2 Wifi
Version of OS is iOS 12.4.8
I am using the latest checkra1n 0.1.0 beta
I am using macOS Catalina latest update on MacBook Pro 2014 13" Retina
I am using genuine Apple lightning cable

Steps to reproduce:
1. Install checkra1n on host device
2. Jailbreak the device
3. Optionally remove the Setup.app via USB SSH

After jailbreak I tried to use the checkm8 tool, it showed up like working but it was not. I tried to remove the Setup.app file via SSH, but nothing happened after even reseting all the processes connected with the Hello screen where I was stuck on. After restart of iPad I was able to get to OS main screen instead of Hello screen but the home button was not working and after I locked the iPad with the power button and then tapped it again, Hello screen appeared again and home button was not working still. 

If I enable safe mode in checkra1n app it fails every time.

Sadly I don't have any screenshots, but I hope I will provide them soon if needed.

**Comment by vaodaa** [comment]
Ddi you found a fix ?

**Comment by KodzghlyCZ** [comment]
Nope, that's why I'm here. I can't even flash the firmware to the preview versions of OS, because they are not signed anymore.

**Comment by vaodaa** [comment]
did you test with that ? https://ipsw.me/iPad4,4

**Comment by KodzghlyCZ** [comment]
Yep, there is only one version signed and that is the 12.4.9 which I'm currently on, as long as you can do some magic with the OTA firmwares, but I don't think that's the case. Or am I wrong?

**Comment by Siguza** [comment]
That's caused by the iCloud lock. checkra1n has nothing to do with that.
