### ISSUE TITLE
When are you going open-source ?

### ISSUE THREAD

**Issue by karthage-spartacus** [checkra1n/BugTracker#1775]
Hello there,

wanted to know if you had a date in mind for the open-source release.
You could use a hand or two 😉

Thanks

**Comment by asdfugil** [comment]
From checkra1n FAQ:
> We plan to open-source later in 2020.

**Comment by karthage-spartacus** [comment]
Yeah, that's why I asked...

I mean 2020 is ending in less than 2 month...

**Comment by asdfugil** [comment]
time's running out

**Comment by Siguza** [comment]
Marking this as dupe of #566.

Basically once we have a working Windows release.
