### ISSUE TITLE
Iphone 6S home button 

### ISSUE THREAD

**Issue by KevinMazelin** [checkra1n/BugTracker#1777]
Hi,
My home button is broken, how to enter dfu mode with this tool ?
I use modra1nusb iso rufus method justatech
i m trying with reiboot an another pc and after i change usb port but checkra1n turn on iphone

**Comment by TOTALMICHEL** [comment]
you do not. dead home button = no DFU

**Comment by KevinMazelin** [comment]
Thank for answer.
Appreciate
