### ISSUE TITLE
System Files Missing !

### ISSUE THREAD

**Issue by jorevi25** [checkra1n/BugTracker#1778]
**Tell us about your setup:**
1. What iDevice are you using?
**IPhone 6s**

2. On what version of iOS is it?
**iOS 14.1**

3. What version of checkra1n are you using?
**checkra1n 0.11.0 beta**

4. What is your host system (OS version? Hackintosh? VM? etc.)?
**OS X EL CAPITAN**

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
**Original Apple  Usb**

**What are the steps to reproduce the issue?**
1. **Jailbreak**
2. **install cydia tweeks**
3.**After clicking Springboard, shown following message...

![IMG_0015](https://user-images.githubusercontent.com/54463833/97344323-f917a180-185e-11eb-87be-4ea00c4a7626.jpg)

**What do you expect, and what is happening instead?**
**apps and tweaks don't get stuck**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
**YES**

**Any other info, error logs, screenshots, ...?
![IMG_0015](https://user-images.githubusercontent.com/54463833/97344323-f917a180-185e-11eb-87be-4ea00c4a7626.jpg)

**Comment by woachk** [comment]
Hello,

That's not a checkra1n issue but one from your bootstrap or whatever.

**Comment by worf1337** [comment]
Install RocketBootstrap from Ryan Petrich's repo
