### ISSUE TITLE
Is there a way to ssh into ipad without having cydia ssh installed. 

### ISSUE THREAD

**Issue by abacus0101** [checkra1n/BugTracker#1784]
So as everyone knows the current build of checkra1n doesnt complete the boot process correctly hence the loader app doesnt appear after attempted jailbreak. Some said to ssh and run a command to get loader to show so we can install cydia. Problem is how do you get ssh onto the ipad if no cydia. Is there another way to do this. Patiently waiting for an update to checkra1n.....

**Comment by raph2705** [comment]
One of the magic perks of jailbreaking, see Google for iproxy use then simply call
`$ ssh root@127.0.0.1 -p <configured port>`
Password is alpine

**Comment by Siguza** [comment]
Also we bind SSH to port 44 on the device side.

**Comment by Siguza** [comment]
I'll consider this resolved.
