### ISSUE TITLE
Checkra1n not working on ipad pro 1st gen (A9X)

### ISSUE THREAD

**Issue by fennectech** [checkra1n/BugTracker#1787]
**Tell us about your setup:**
1. iPad Pro 9.7 (1st gen) A9X
2. 14.1
3. 0.11.0
4. Linux machine
5. Third party MFI cable.  worked fine before I updated

**What are the steps to reproduce the issue?**
1. Boot device in DFU mode
2. Plug in for checkra1n
3. Wait for checkra1n to do the thing
...

**What do you expect, and what is happening instead?**
I expect the checkra1n bpptstrap to appear  but it just boots to an unjailbroken home screen.  

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Same result

**Any other info, error logs, screenshots, ...?**
```
 - [11/01/20 21:42:04] <Verbose>: DFU device connected: 251c210f82226
 - [11/01/20 21:42:04] <Verbose>: == Checkm8 Trigger stage ==
 - [11/01/20 21:42:05] <Verbose>: Checkmate!
 - [11/01/20 21:42:05] <Verbose>: DFU device connected: 251c210f82226
 - [11/01/20 21:42:05] <Verbose>: == Checkm8 Trying to run payload... ==
 - [11/01/20 21:42:06] <Verbose>: If everything went correctly, you should now have code execution.
 - [11/01/20 21:42:07] <Info>: Entered download mode
 - [11/01/20 21:42:07] <Verbose>: Download mode device found
 - [11/01/20 21:42:07] <Info>: Booting...
 - [11/01/20 21:42:07] <Verbose>: Setting bootargs to: rootdev=md0
 - [11/01/20 21:42:09] <Error>: Failed to open USB interface: (No such device) (error code: -76)

Got logs from checkra1n -c -v
```

**Comment by Sandwhich253989** [comment]
I think it is 
Duplicate of #1689

**Comment by Sandwhich253989** [comment]
The device reboots in the middle  right ?

**Comment by fennectech** [comment]
No   im talking about my inability to jailbreak

**Comment by Sandwhich253989** [comment]
Like  the Checkra1n code thingy shows and in the middle it crashes and then the device reboots

**Comment by fennectech** [comment]
yeah  never mind my stupidness   thought you said "so the device reboots in the middle of the night"  but yeah  this is a duplicate

**Comment by guilbertguerrA** [comment]
checkrain 0.10.1  funziona
