### ISSUE TITLE
cannot boot into safe mode after installing bad tweak on iPad 6th gen iOS 13.2.2

### ISSUE THREAD

**Issue by chevy4lifeee** [checkra1n/BugTracker#179]
**What device + iOS version are you on?**
iPad 6th gen wifi model

**What checkra1n version are you using?** 
latest beta release 0.9.1

**What are the steps to reproduce the issue?**
1. I tried holding the volume up button during boot and did not boot into no substrate mode
2. New update to patch the issue
3. New update to be able to boot into safe mode
...

**What do you expect, and what is happening instead?**
go into no substrate mode but instead it just boot loop then eventually boot into stock iOS 

**Any other info, error logs, screenshots, ...?**
there is a substrate safe mode installed on cydia but doesn't work doesn't even go to safe mode with power module tweak

**Comment by MrPigglet** [comment]
Same, after installing a supposedly updated tweak it caused me to crash back to stock and now I get error -20 every time I jailbreak. I cannot for the life of me get into safe mode. On iPhone SE.

**Comment by chevy4lifeee** [comment]
> Same, after installing a supposedly updated tweak it caused me to crash back to stock and now I get error -20 every time I jailbreak. I cannot for the life of me get into safe mode. On iPhone SE.

well i found the fix first update your iPhone to iOS 13.3 beta you can do so from www.betaprofiles.com and once you do that put your iPhone to dfu mode then launch checkra1n on your mac then start and it'll jailbreak again like before but you will have to re install all your tweaks and safe mode should work this time. keep in mind compatibility may suffer since this version of iOS is a beta and not fully supported

**Comment by littlelailo** [comment]
I would advise against this method as it might have side effects instead you can now try 0.9.2 which has a proper safe mode. Because this is resolved now I'll close the issue
