### ISSUE TITLE
My Iphone 7 doesn't boot. When i press the power up button it just does nothing :( HELP

### ISSUE THREAD

**Issue by ImJustGaming123** [checkra1n/BugTracker#1790]
I have an Iphone 7. It doesnt start up at all. I was jailbreaking ios 14.1
Please help me i dont have a phone.

**Comment by ttorynn** [comment]
Does the home button work (can you press it down and will it provide feedback) or can you not press it.

**Comment by Siguza** [comment]
If it doesn't turn on, then there's nothing we can do.
