### ISSUE TITLE
iPhone 6s iOS 14.1 checkra1n app nor cydia app shows up after jailbreak.

### ISSUE THREAD

**Issue by besasdev** [checkra1n/BugTracker#1795]
**Tell us about your setup:**
1. iPhone 6s
2. iOS 14.1
3. 0.11 checkra1n
4. macos
5. Usb-Hub

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**
Jailbreak seems to be successful (I can ssh into device) , but checkra1n app and cydia app are missing.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
Is it because of too little storage? I only have 2 GB of storage left, so is that the problem?

Thanks!

**Comment by avltree9798** [comment]
This happened to me, the fix I did was:
1. SSH to the device
2. run `mount -o rw,union,update /` command
3. Profit

**Comment by besasdev** [comment]
Works, thanks!
