### ISSUE TITLE
[Question]Is possible to redirect GUI alert to socket channel (ssh or telnet) instead?

### ISSUE THREAD

**Issue by kongsub** [checkra1n/BugTracker#1796]
checkra1n is very successful jailbreaked on "**disabled**" iPhone 7 Plus , iOS 12.2 . rootfs can be read , but /private/var still lock by SEP . 
iTunes says 'tap Trust' while usb connected and iPhone show a small icon on the top of screen tell me to unlock screen and answer. but screen is being locked by Springboard ( no bypass 12.2 "passcode locked" module now ), so could i redirect the alert to TCP-like channel and operate by command line?

**Comment by Siguza** [comment]
No idea. But sorry, this isn't a general Q&A forum.  
I'll close this issue since checkra1n seems to be working as intended.
