### ISSUE TITLE
iphone 6 disabled error -77

### ISSUE THREAD

**Issue by sky-finder** [checkra1n/BugTracker#1800]
Dear Bro

I try to jailbreak the iPhone 6 disabled with 0.10.2  checkra1n via bootable dongle created vy Rupus software.

buy got error -77. I don't know what version inside the phone because it is disabled. Need to iCloud bypass.
How to do this bro

Thanks

**Comment by Temock** [comment]
Update it in DFU mode with 3Utools

**Comment by sky-finder** [comment]
> Update it in DFU mode with 3Utools

Thanks bro for reply but it icloud locked need to bypass the icloud.So need to jailbreak it.

**Comment by Siguza** [comment]
We don't support that. You're on your own.
