### ISSUE TITLE
I can't see the tweaks in settings after the install&respring

### ISSUE THREAD

**Issue by CRenatoG** [checkra1n/BugTracker#1806]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 7 9,3 

2. On what version of iOS is it?
iOS 14.2

3. What version of checkra1n are you using?
0.12.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOS Catalina 10.15.5
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple USB-A to Lightning
**What are the steps to reproduce the issue?**
1. Install snowboard
2. Install some theme
3. Install filza file manager
...

**What do you expect, and what is happening instead?**
I can't see the tweaks in settings app and of course I can't configurate it

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
The safe mode option don't work

**Any other info, error logs, screenshots, ...?**
No error codes :(

**Comment by CRenatoG** [comment]
I tried reinstalling cydia,  checkra1n and restore sistem function but not works

**Comment by Siguza** [comment]
This is an issue with PreferenceLoader, not checkra1n.
