### ISSUE TITLE
Iphone X 14.2, 0.12.0, MacOS 10.15.7 ,im using a usb c to a, to connect my phone. Can I use a password because when I renable it checkrain was gone and cydia didnt even open please help me.

### ISSUE THREAD

**Issue by bendoverformeking** [checkra1n/BugTracker#1808]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
No you cannot.  
iPhone 8 and X cannot be jailbroken on iOS 14 when a password is set.
