### ISSUE TITLE
iPhone stuck on Apple logo after reinstalling

### ISSUE THREAD

**Issue by codywaters11** [checkra1n/BugTracker#1809]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 7

2. On what version of iOS is it?
iOS 12.4.1

3. What version of checkra1n are you using?
Version beta 0.11.0

4. What is your host system (OS version? Hackintosh? VM? etc.)?
Windows 7, running checkra1n from flash drive on startup menu.

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A cable.

**What are the steps to reproduce the issue?**
1. Download checkra1n & Cydia
2. Let device die & reboot, after reboot checkra1n or Cydia will not open
3. Try to rejailbreak, will get stuck on Apple boot logo after verbose script is ran on the device. The program on the computer is stuck on “Booting...”
...

**What do you expect, and what is happening instead?**
I expected for the checkra1n program to replace the old app that wouldn’t open with a fresh copy, but instead, the iPhone is stuck on the boot logo.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes.

**Any other info, error logs, screenshots, ...?**
The device will go into recovery mode & DFU mode, and the script will be loaded onto the phone, but will just not boot.

**Comment by Siguza** [comment]
Does it still boot in unjailbroken mode?

**Comment by codywaters11** [comment]
There was no way for me to boot it at all. Anything I did, it ended up going back to the Apple logo & freezing.

**Comment by Siguza** [comment]
Yeah, then there's nothing we can do. IPSW restore it is.
