### ISSUE TITLE
[Feature request] Set generator

### ISSUE THREAD

**Issue by Halo-Michael** [checkra1n/BugTracker#181]
An interesting fact is that iPhoneSE/iPhone6/xx currently can't set generator on iOS13.

**Comment by arx8x** [comment]
Trysystem info from my repository and run "nvnonce 0xgenrator" in command line. If it doesn't crash and reboot, it'll set the generator :P

**Comment by Halo-Michael** [comment]
> Trysystem info from my repository and run "nvnonce 0xgenrator" in command line. If it doesn't crash and reboot, it'll set the generator :P

Thanks for your work of system info. But it can’t unlock nvram on iOS13.

**Comment by Halo-Michael** [comment]
> > Trysystem info from my repository and run "nvnonce 0xgenrator" in command line. If it doesn't crash and reboot, it'll set the generator :P
> 
> Thanks for your work of system info. But it can’t unlock nvram on iOS13.

Seems is the same issue with #236 .

**Comment by arx8x** [comment]
Which version of system info did you try?

**Comment by Halo-Michael** [comment]
> Which version of system info did you try?

13.2/13.2.2

**Comment by Halo-Michael** [comment]
> Which version of system info did you try?

2.3.2-4+debug

**Comment by Halo-Michael** [comment]
If #236 was fixed, then it's easy to set generator. So I think it should be closed.

**Comment by arx8x** [comment]
nvnonce doesn't have 100% success rate on checkra1n. It was working fine on 6s and 6 however (SE shouldn't be much different)

#236 only addresses task validation, the task given is valid and the tools that use tfp0 should work.

**Comment by Halo-Michael** [comment]
> nvnonce doesn't have 100% success rate on checkra1n. It was working fine on 6s and 6 however (SE shouldn't be much different)
> 
> #236 only addresses task validation, the task given is valid and the tools that use tfp0 should work.

In fact it’s totally 0% success rate
tfp0 means task_for_pid_0, it’s the kernel’s task, so I think if task given is not work, kernel task should also affected.

**Comment by arx8x** [comment]
@Halo-Michael Attempt `nvnonce -n` and then `nvnonce`.

**Comment by Halo-Michael** [comment]
> @Halo-Michael Attempt `nvnonce -n` and then `nvnonce`.

![Uploading 5150C8C4-80C7-4EE8-ACF4-78B1CC5A7067.png…]()

**Comment by Halo-Michael** [comment]
> @Halo-Michael Attempt `nvnonce -n` and then `nvnonce`.

![E39F4B23-8F43-4750-AB43-EDED4C860CB4](https://user-images.githubusercontent.com/45062120/68990151-9960fa00-088a-11ea-8f92-d5ee6c81862d.png)

**Comment by quilenle** [comment]
It looks like it will fail on iOS 13

**Comment by Halo-Michael** [comment]
Dimentio has been updated now.
