### ISSUE TITLE
0.12.0 not working on iphone 7 ios 14.1

### ISSUE THREAD

**Issue by chiragvshroff** [checkra1n/BugTracker#1811]
**Tell us about your setup:**
1. What iDevice are you using?
iphone 7
2. On what version of iOS is it?
14.1
3. What version of checkra1n are you using?
0.12.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
macos,linux
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
usb a
**What are the steps to reproduce the issue?**
1. open checkra1n
2. follow all steps to jailbreak
...
**What do you expect, and what is happening instead?**
checkra1n loader app not appearing

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Comment by 01M** [comment]
same

**Comment by ghost** [comment]
The same issue with identical results on iPhone 6S

**Comment by Siguza** [comment]
Duplicate of #1810.
