### ISSUE TITLE
Substrate isn’t launching after rejailbreak (without Safe Mode flag)

### ISSUE THREAD

**Issue by The1Day** [checkra1n/BugTracker#1814]
iPad 2017 (5th generation), iPadOS 14.2, macOS checkra1n 0.12.0

After rejailbreaking you need to reinstall Cydia because of DPKG_LOCKED error and after that install Substrate again with any tweak even before all was working fine (no crashes and Safe Modes because of incompatible tweaks).
I believe it is a problem in the checkra1n itself, checked twice plus without any tweaks installed.

**Comment by asalmero** [comment]
https://github.com/checkra1n/BugTracker/issues/1822

bro try my solution

**Comment by sbingner** [comment]
Dupe of #1825
