### ISSUE TITLE
Passcode Lock

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#1815]
**Tell us about your setup:**
1. What iDevice are you using? Iphone X
2. On what version of iOS is it?14.2
3. What version of checkra1n are you using? checkra1n to 0.12.0.
4. What is your host system (OS version? Hackintosh? VM? etc.)? Checkn1x
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Lightning cable to usb

**What are the steps to reproduce the issue?**
1. remove passcode lock.
2. jailbreak device.
3.reactivate password lock (Screenlock & Faceid).
...

**What do you expect, and what is happening instead? When password is reactivated the phone reboots and jailbreak is removed.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Not sure.

**Any other info, error logs, screenshots, ...?** No.

**Comment by demhademha** [comment]
Could you get a panic log please?

**Comment by danasheka** [comment]
Here is the Panic Log

[panic-full-2020-11-09-162011.000.zip](https://github.com/checkra1n/BugTracker/files/5512189/panic-full-2020-11-09-162011.000.zip)

**Comment by Siguza** [comment]
This is expected. We stated that you can't use a passcode lock on A11 on 14.0 or later.  
We might find a way around this eventually, but for the time being, that's how it is.
