### ISSUE TITLE
Cant start the Jailbreak!

### ISSUE THREAD

**Issue by Eide0** [checkra1n/BugTracker#1817]
Hi, i want to jailbreak my iPhone 11 Pro (IOS 14.1), but I can't. I can't start the Jailbreak, Ive tried to click on Options, then "Allow untested iOs/iPadOS/twOS versions" but I still can't, why?
![Skjermbilde 2020-11-09 kl  18 33 42](https://user-images.githubusercontent.com/73024683/98575947-1ebe9500-22ba-11eb-8371-04f73bcf7916.png)

**Comment by ttorynn** [comment]
An iPhone 11 Pro Runs on an A13 Bionic processor, this is currently not supported for jailbreaking. Only A10/A10X and lower devices are supported for jailbreaking on iOS 14 at the moment.

**Comment by Siguza** [comment]
A13 has no known BootROM bug, that's why.
