### ISSUE TITLE
My phone dead

### ISSUE THREAD

**Issue by HumanMus1c** [checkra1n/BugTracker#1818]
**Tell us about your setup:**
1. What iDevice are you using?
6s plus
2. On what version of iOS is it?
14.2GM
3. What version of checkra1n are you using?
0.12.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
forgot
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A
**What are the steps to reproduce the issue?**
1. use batshmatic to remove all tweaks
2. respring
3.still respring...
.4.. Start new phone setup (data been erased)
5.reboot
6.stuck in reboot

**What do you expect, and what is happening instead?**
bugs fixed

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
not yet

**Any other info, error logs, screenshots, ...?**
phone dead, there was nothing left.

**Comment by Siguza** [comment]
Sounds like you should do a clean IPSW restore. Nothing to do with checkra1n.

**Comment by HumanMus1c** [comment]
yes, and I did.
