### ISSUE TITLE
New installed Cydia apps won't appear after installing

### ISSUE THREAD

**Issue by JackTheFroster** [checkra1n/BugTracker#182]
**What device + iOS version are you on?**
iPod touch 6g iOS 12.4.3

**What checkra1n version are you using?**
0.9.1 beta
**What are the steps to reproduce the issue?**
1. Install an "app" from Cydia (for example iCleaner)
2. After installing, go back to Cydia/Restart Springboard
3. Search for the app on home screen

**What do you expect, and what is happening instead?**
I expect that the app is on my home screen after installation but it's not.

**Any other info, error logs, screenshots, ...?**
I tried reinstalling an app and restart/rejailbreak my iDevice, nothing happened. But when I installed another Cydia app to test if it's also not appearing, suddenly all apps were appearing. But when I uninstalled the "test" app, it's not disappearing.

**Comment by termz64** [comment]
Run uicache from newterm 2 or via ssh. This has already been answered

**Comment by Halo-Michael** [comment]
Just run “uicache” on Terminal. It's not a bug of checkra1n.

**Comment by JackTheFroster** [comment]
Yeah I thought about uicache. thought this might have to do something with the jailbreak because I never experienced this so far. sorry for that!
