### ISSUE TITLE
Start button doesn’t show

### ISSUE THREAD

**Issue by killerman25569** [checkra1n/BugTracker#1823]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone X
2. On what version of iOS is it?
14.2
3. What version of checkra1n are you using?
0.12.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**
![image](https://user-images.githubusercontent.com/74221592/98618000-3c95f500-22ce-11eb-8573-76b252cd5670.jpg)

**Comment by Siguza** [comment]
See https://checkra.in/news/2020/09/iOS-14-announcement and  https://twitter.com/checkra1n/status/1325504063589511170.  
There's a checkbox for BPR check in the options. Proceed at your own risk.
