### ISSUE TITLE
iPhone X 14.1 not working

### ISSUE THREAD

**Issue by ImaBossYo** [checkra1n/BugTracker#1824]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone X (Global)
2. On what version of iOS is it?
14.1
3. What version of checkra1n are you using?
0.12.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
OS Catalina
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Stock Apple Cable

**What are the steps to reproduce the issue?**
1. Load up checkra1n
2. says 14.1 is not supported
3. If I press skip A11 BPR check I get error connecting to lockdownd (lockdownd error -21)
...

**What do you expect, and what is happening instead?**
I expect to be able to make it into the jailbreak process, but I cannot.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
I also have seen the youtuber iCrackuriDevice to this and I repeated his steps, but I still get the same error or not supported outcome (I am using the exact device he is using)
I also get the same error using the CLI.
![Screen Shot 2020-11-09 at 11 21 47 PM](https://user-images.githubusercontent.com/72060544/98627475-580afb00-22e2-11eb-9c8f-42a610a46257.png)
![Screen Shot 2020-11-09 at 11 22 02 PM](https://user-images.githubusercontent.com/72060544/98627487-60fbcc80-22e2-11eb-8897-80bfba57aa38.png)

**Comment by angelobdev** [comment]
You have to go in options and enble the A11 Bypass option

**Comment by ImaBossYo** [comment]
I did that, thats what gave me the lockdownd error -21.

**Comment by Siguza** [comment]
Either pair the device with the host and have it unlocked when you run checkra1n, or use the CLI.

**Comment by yenskillah** [comment]
> Either pair the device with the host and have it unlocked when you run checkra1n, or use the CLI.

Hi, I am experiencing the same problem. Could you let me know how to do this? Perhaps you know any articles that could help with this. Thanks in advance.

**Comment by ImaBossYo** [comment]
Make sure that your device has your computer trusted.
