### ISSUE TITLE
/etc/rc.d didn't loaded (include /etc/rc.d/substrate)

### ISSUE THREAD

**Issue by Halo-Michael** [checkra1n/BugTracker#1825]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone8,4 (SE1)
2. On what version of iOS is it?
iOS14.2 (18B92)
3. What version of checkra1n are you using?
0.12.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Hackintosh 10.13.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A
**What are the steps to reproduce the issue?**
1. Just Jailbreak

**What do you expect, and what is happening instead?**
/etc/rc.d didn't loaded (include /etc/rc.d/substrate)

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
verbose boot log:
2020-11-10 12:13:13.816 payload[33:889] [checkra1n] loading /etc/rc.d
Missing kernel_cache_addr
2020-11-10 12:13:13.816 payload[33:889] failed to restore cache
2020-11-10 12:13:13.816 payload[33:889] [checkra1n] loading daemons
2020-11-10 12:13:13.833 launchd[1:771] checkra1n initlalization completed; continuing boot...

**Comment by ghost** [comment]
same here, I have to manually SSH in and start substrate every time I boot up. (iPad Pro 10.5" Cellular)

**Comment by sbingner** [comment]
Something changed in how it stores the kernel in memory that caused this issue on 14.2 or so... it's been fixed in git

**Comment by Siguza** [comment]
Fixed in 0.12.1.
