### ISSUE TITLE
error 21 Iphone 8 plus (ios 14.1) checkra1n 0.12.0

### ISSUE THREAD

**Issue by RomaKosuk17** [checkra1n/BugTracker#1827]
**Tell us about your setup:**
1. What iDevice are you using?
Iphone 8 plus 
2. On what version of iOS is it?
14.1
3. What version of checkra1n are you using?
0.12.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
macOS 10.12.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple
**What are the steps to reproduce the issue?**
1. Skip A11 BPR check was turned on
2. installation method normal
3.Clicking on Done knocked out error 21
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

YEs
**Any other info, error logs, screenshots, .
![изображение_viber_2020-11-10_11-19-27](https://user-images.githubusercontent.com/74238020/98654215-b36ed480-2346-11eb-8ae3-300927cb5e0b.jpg)
![изображение_viber_2020-11-10_11-19-51](https://user-images.githubusercontent.com/74238020/98654219-b4076b00-2346-11eb-9085-e6f02931f4cc.jpg)

..?**

**Comment by ImaBossYo** [comment]
Same on iPhone X 14.1 Mac version 10.15.6

**Comment by Baeda73** [comment]
Same here, iPhone8 Plus, iOS14.2
macOS 11.0.1 beta

**Comment by Siguza** [comment]
See https://github.com/checkra1n/BugTracker/issues/1824#issuecomment-727782741
