### ISSUE TITLE
Checkra1n loader app not showing up after jailbreak Apple TV 

### ISSUE THREAD

**Issue by artie14** [checkra1n/BugTracker#1828]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. Apple TV 4
2. tvOS 13.4.8
3.Checkra1n beta 0.11.0
...

**What do you expect, and what is happening instead?**
I expected Checkra1n loader app to appear but it doesn’t 

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Should be fixed, at least in 0.12.3 if not earlier?  
If the issue persists, try `--force-revert` and then jailbreak again.

**Comment by artie14** [comment]
Thank you 👍

Sent from my iPhone

On 30 Apr 2021, at 02:51, Siguza ***@***.***> wrote:

﻿

Closed #1828<https://github.com/checkra1n/BugTracker/issues/1828>.
