### ISSUE TITLE
Doesn't want to jailbreak after changing wallpaper

### ISSUE THREAD

**Issue by MatMan02** [checkra1n/BugTracker#183]
**What device + iOS version are you on?**
iOS 13.2.2 iPhone X

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. I changed the wallpaper on my iPhone
2. The phone crashed and the jailbreak (since is thetered) unactivated
3. I try to reactivate it
4. the phone is stuck on Apple Booting Logo after checkra1n said me "All done"

**What do you expect, and what is happening instead?**
The phone to boot, but it doesen't

**Any other info, error logs, screenshots, ...?**

**Comment by termz64** [comment]
This is a duplicate of #84 .Close this issue

**Comment by MatMan02** [comment]
> This is a duplicate of #84 .Close this issue

Yes, sorry. Thank you

**Comment by termz64** [comment]
No problem
