### ISSUE TITLE
Oddyesyra1n making checkra1n app not show up

### ISSUE THREAD

**Issue by EasonJiangOfficial** [checkra1n/BugTracker#1835]
So I started using checkra1n when version 11 came out,it worked fine.Then I found out about oddyesyra1n so i installed that but didn't rootfs,before exiting jail broken state.Now when ever I jailbreak with checkra1n version 12 on Ios 14.2,it boots successful but the checkra1n app doesn't show up.Ive already tried restoring my phone.Now i get USBMUX errors on Linux.First time was -77 now its -92

**Comment by Cexdexbbl** [comment]
Check my post out maybe it could help you #1830

**Comment by Cexdexbbl** [comment]
Don't use odysseyrain with checkra1n. I used it and I had a hard time trying to erase it so everything could go back to normal.

**Comment by Siguza** [comment]
Note that we don't provide support for Odysseyra1n.  
But there's a realistic chance that this particular issue is related to checkra1n. It's being tracked over at #1810.
