### ISSUE TITLE
Ihpone 11 Pro Jailbreak

### ISSUE THREAD

**Issue by Eide0** [checkra1n/BugTracker#1836]
Hi, is there any IOS 14.1 iPhone 11 pro jailbreaks?

**Comment by dalmatele** [comment]
No, it only support Iphone X and below devices.

**Comment by itsTyrion** [comment]
> Hi, is there any IOS 14.1 iPhone 11 pro jailbreaks?

Checkra1n relies on a HARDWARE vulnerability present on A11 (iPhone X) and below. Please just read the manual/FAQ before asking stupid questions.

Other jailbreaks? Given that you are on iOS 13.5 (not 13.5.1) or below, you can use unc0ver. If not, you should stay on the version you're on, unless you have SHSH blobs for a lower version, you can't downgrade anyway.
