### ISSUE TITLE
iPhone X GSM 14.2 

### ISSUE THREAD

**Issue by elcelicas** [checkra1n/BugTracker#1838]
Hola, quisiera saber si en el iPhone X GSM con versión 14.2 se puede hacer el jailbreack, según leí en la nueva versión de checkra1n 0.12.0 se podía hacer quitando la seguridad, pero al abrir el programa me dice que mi iPhone no es compatible con la versión 0.12.0

**Comment by Siguza** [comment]
I'm afraid you're gonna have to repeat that in English.

**Comment by spiouki** [comment]
Translation from google translate:
Hello, I would like to know if the iPhone X GSM with version 14.2 can jailbreack, as I read in the new version of checkra1n 0.12.0 it could be done by removing security, but when I open the program it tells me that my iPhone is not compatible

**Comment by Siguza** [comment]
In that case it's a duplicate of #1823.
