### ISSUE TITLE
Any springboard based app crashes instantly

### ISSUE THREAD

**Issue by slickpads** [checkra1n/BugTracker#184]
**What device + iOS version are you on?**
13.2.2

**What checkra1n version are you using?**
9.1
**What are the steps to reproduce the issue?**
1.download snowboard
2.install it
3.respring and it goes to safe mode.
...

**What do you expect, and what is happening instead?**
To enable my themes and go about my day.

**Any other info, error logs, screenshots, ...?**no.

**Comment by termz64** [comment]
This has already been reported several times. In iOS 13 the springboard files have been relocated. The devs just need to update their packages to be compatible with iOS 13

**Comment by JensdeVlaming** [comment]
Snowboard is updated for iOS 13. Did you update?

**Comment by nullpixel** [comment]
this is not a checkra1n issue. an update will be out soon to allow you to enter safe mode with the volume up button.
