### ISSUE TITLE
JailBreak Frozen

### ISSUE THREAD

**Issue by explodersname** [checkra1n/BugTracker#1841]
**Tell us about your setup:**
1. What iDevice are you using? Iphone 5s
2. On what version of iOS is it? 12.4.8
3. What version of checkra1n are you using? 0.12.0
4. What is your host system (OS version? Hackintosh? VM? etc.)? Ubuntu 20.04
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A

**What are the steps to reproduce the issue?**
1. Download the checkrain app
2. connect phone
3. enter DFU mode
4. get stuck on the screen
...

**What do you expect, and what is happening instead?**
The jailbreak to continue

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**
This is the screen I'm talking about and I've been on it forever.
![image](https://user-images.githubusercontent.com/42114849/98997309-4dc74780-2502-11eb-85b2-52a98755b9f1.png)

**Comment by Siguza** [comment]
To date, A7 is still broken on Linux. See #1169.
