### ISSUE TITLE
iPhone 8 (gsm) jailbreak notworking

### ISSUE THREAD

**Issue by Monda88** [checkra1n/BugTracker#1847]
i have an iPhone 8 (GSM) icloud locked
ios 14.2
using checkra1n 0.12 beta on Ubuntu linux
jailbreaking did not work (even with all the options selected)
i tried jailbreadking the device when it was on ios 13.6 with Checkra1n 0.12 but after the operation completed the home button did not work and the device is stuck on hello screen

is there any new release for checkra1n soon to fix this issue

**Comment by Siguza** [comment]
Working as intended.
