### ISSUE TITLE
task_info() no longer returning TASK_DYLD_INFO for the kernel task

### ISSUE THREAD

**Issue by sfbg1013** [checkra1n/BugTracker#1852]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 7

2. On what version of iOS is it?
14.2

3. What version of checkra1n are you using?
0.12.0

4. What is your host system (OS version? Hackintosh? VM? etc.)?
macOS 10.15.6

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A

**What are the steps to reproduce the issue?**
1. Call task_info(kernel_task_port,  TASK_DYLD_INFO, &dyld_info, &count) and confirm dyld_info.all_image_info_addr is NULL. This normally holds a kernel pointer to a struct filled with useful data like the kernel slide, etc..

...

**What do you expect, and what is happening instead?**
dyld_info.all_image_info_addr to hold a kernel pointer to useful kernel info but the value is NULL

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**

**Comment by sbingner** [comment]
Something changed in how it stores the kernel in memory that caused this issue on 14.2 or so... it's been fixed in git

**Comment by Siguza** [comment]
FIxed in 0.12.1.
