### ISSUE TITLE
LOADER APP NOT APPEARING

### ISSUE THREAD

**Issue by chiragvshroff** [checkra1n/BugTracker#1860]
**Tell us about your setup:**
1. What iDevice are you using?
IPHONE 7
2. On what version of iOS is it?
14.1/14.2
3. What version of checkra1n are you using?
0.12/0.12.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
TRIED LINUX,MAC
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB A

THE ISSUE IS CHECKRA1N APP DOSEN'T APPEAR AT ALL I FIRST TRIED IT ON 14.1 MANY TIMES ALSO TRIED DIFFERENT CABLES BUT NO LUCK SO I DID A COMPLETE DFU RESTORE TO 14.2 AND TRIED AGAIN BUT STILL THE LOADER DIDNT SHOW UP, HOWEVER AFTER A JAILBREAK IF I CHANGE MY LANGUAGE THE APP APPEARS BUT NON OF THE TWEAKS WORK ALSO I AM NOT THE ONLY PERSON FACING THIS ISSUE THERE ARE MANY. I REQUEST THE TEAM TO PLEASE WORK ON THE FIX THANKS!!

**Comment by kingparthav** [comment]
Try Re-jailbreaking, it did work for me, i got iphone X same prob i had and i changed language to English US and then re-jailbreak and its all working fine now

**Comment by crystall1nedev** [comment]
I reported similar finding with Linux, not macOS on my iPhone 7. Try following the response I received maybe?

https://github.com/checkra1n/BugTracker/issues/1935
