### ISSUE TITLE
l

### ISSUE THREAD

**Issue by vosqi** [checkra1n/BugTracker#1861]
**FIXED**
I just factory restored my device through iTunes and rejailbroke it worked fine now

**Tell us about your setup:**
1. What iDevice are you using?
iPad 7th Gen
2. On what version of iOS is it?
Ipados14.2beta
3. What version of checkra1n are you using?
0.12.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Checkn1x
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
UsbA
**What are the steps to reproduce the issue?**
1. Just install tweaks
2. >Settings, nothing shows up

**What do you expect, and what is happening instead?**
Tweaks to show up in settings, but is not, however apps show like filza

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by dnk22** [comment]
same too .

**Comment by Sandwhich253989** [comment]
Same here

**Comment by Sandwhich253989** [comment]
But I downgraded cydia substrate and then upgraded , and then tweaks are showing up

**Comment by Sandwhich253989** [comment]
And I also installed preference loader

**Comment by vosqi** [comment]
> But I downgraded cydia substrate and then upgraded , and then tweaks are showing up

in settings?

**Comment by vosqi** [comment]
> But I downgraded cydia substrate and then upgraded , and then tweaks are showing up

also i dont have cydia substrate showing in my cydia for some reason

**Comment by Sandwhich253989** [comment]
Then install substrate

**Comment by Sandwhich253989** [comment]
> > But I downgraded cydia substrate and then upgraded , and then tweaks are showing up
> 
> in settings?
Yes

**Comment by Sandwhich253989** [comment]
> > But I downgraded cydia substrate and then upgraded , and then tweaks are showing up
> 
> in settings?

Yes

**Comment by Sandwhich253989** [comment]
Idk why preference loader ,substrate, rocket bootstrap were not installed by the checkra1n loader

**Comment by vosqi** [comment]
> Idk why preference loader ,substrate, rocket bootstrap were not installed by the checkra1n loader 

I'd manage to find preferenceloader however it's in the odyssey repo and I'm not sure it's for cydia and not just for sileo.

**Comment by chrismonster13** [comment]
> > Idk why preference loader ,substrate, rocket bootstrap were not installed by the checkra1n loader
> 
> I'd manage to find preferenceloader however it's in the odyssey repo and I'm not sure it's for cydia and not just for sileo.

Just as an FYI, you probably shouldn't be mixing bootstrap repos on different jailbreaks. Rocketbootstrap is originally written and maintained by Ryan Petrich and it can be found on his repo. i would not recommend installing stuff from the Odyssey/Procursus repo unless you are using Odysseyra1n. Those things, are not installed by the loader at beginning either. They are dependencies tied to tweaks.

**Comment by Sandwhich253989** [comment]
I didn’t install from Odessey repo

**Comment by Sandwhich253989** [comment]
I installed from bigboss repo

**Comment by Sandwhich253989** [comment]
I installed from bigboss repo

**Comment by vosqi** [comment]
> I installed from bigboss repo

Can you send me a deb file of yours because I don't seem to find it in my big boss repo, however I did find one other preferenceloader which said something along the lines of arm. That one didn't work and I'm guessing it's for older devices because it has dependencies of arm.

**Comment by littlelailo** [comment]
Did you see a popup on the device stating it entered "Safe Mode" due to an error?

**Comment by yur1xpp** [comment]
I’m seeing this same issue, where tweaks won’t load after a userspace reboot, and the checkra1n app disappeared. Possible the same issue here: https://github.com/checkra1n/BugTracker/issues/1886

**Comment by vosqi** [comment]
Fixed it by restoring device and re-jailbreaking.
