### ISSUE TITLE
My Macbook would not open it

### ISSUE THREAD

**Issue by kevinwelcome27** [checkra1n/BugTracker#1863]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 6S
2. On what version of iOS is it?
Ios 14.2
3. What version of checkra1n are you using?
0.12.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
OS 10.7.5 Macintosh HD  
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
3rd party cable
**What are the steps to reproduce the issue?**
1. Download it into the computer
2. Put it in the applications 
3. Change it into anywhere in general of security & privacy
4. Click it until it says an error message
5. I decide to go to terminal and run it. It said "Illegal instruction: 4" in terminal.

**What do you expect, and what is happening instead?**
It suppose to pop up, but I guess it does not work.

**Comment by Siguza** [comment]
macOS 10.9 is the minimum required version.  
We looked at what it would take to support older versions, but sadly the amount of work required is currently not feasible for us.
