### ISSUE TITLE
/binpack/usr/bin/tar is too old

### ISSUE THREAD

**Issue by ckcfcc** [checkra1n/BugTracker#1871]
device: iphone 6 plus
os:12.4.9
3. What version of checkra1n are you using?
mac 10.15.7

use MonkeyDev dev a logos deb

**error log:**
Preparing to run Xcode Build Phase...
use default localhost
Signing /Users/dark/Library/Developer/Xcode/DerivedData/debugxxx-cnqqvorcmnbbrjddmjwwrdyagixr/Build/Products/Debug-iphoneos/debugxxx.dylib with ldid... Done.
Copying /Users/dark/Library/Developer/Xcode/DerivedData/debugxxx-cnqqvorcmnbbrjddmjwwrdyagixr/Build/Products/Debug-iphoneos/debugxxx.dylib to package directory at /Users/dark/dev_projects/crack_project/xxx/debugxxx/debugxxx/Package/Library/MobileSubstrate/DynamicLibraries...
Preparing to build package...
Building package ... Done.
Creating zip /Users/dark/dev_projects/crack_project/xxx/debugxxx/debugxxx/Packages/com.debug.xx.debugxxx_0.1-1_iphoneos-arm.zip... Done.
Installing package com.debug.xx.debugxxx_0.1-1_iphoneos-arm.deb on device 192.168.0.250... 
**tar: unrecognized option `--warning=no-timestamp'
Try `tar --help' or `tar --usage' for more information.
dpkg-deb: error: tar subprocess returned error exit status 64
dpkg: error processing archive /var/root/MonkeyDevPackages/com.debug.xx.debugxxx_0.1-1_iphoneos-arm.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2**
Errors were encountered while processing:
 /var/root/MonkeyDevPackages/com.debug.xx.debugxxx_0.1-1_iphoneos-arm.deb

/usr/bin/tar version:1.30
but
/binpack/usr/bin/tar version:1.07

I don't kow why dpkg-deb use the old one...

When I use "cp /usr/bin/tar /binpack/usr/bin/", system told me "cp: cannot remove '/binpack/usr/bin/tar': Read-only file system".

How can I replace /binpack/usr/bin/tar?

**Comment by sbingner** [comment]
Please install over port 22 using openssh instead of trying to install using dropbear

**Comment by Siguza** [comment]
0.12.3 should be shipping a more recent version of `tar` now.
