### ISSUE TITLE
Jailbreak gets stuck at Bug Setup and I have to force restart it

### ISSUE THREAD

**Issue by gungurbuz** [checkra1n/BugTracker#1873]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 7 Plus Global
2. On what version of iOS is it?
14.0.1
3. What version of checkra1n are you using?
0.12.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Linux 18.04
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
direct 3rd party usb-a to lighting cable
**What are the steps to reproduce the issue?**
1. Start to jailbreak
2. wait until it tries to do the "real bug setup"
3.wait for 1 hour and then get pissed and unplug the phone
...

**What do you expect, and what is happening instead?**
It's supposed to jailbreak but instead it just gets stuck and i have to restart it, i dont even reach the checkra1n logo part with scrolling text

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by plok5202008** [comment]
same:
Tell us about your setup:

1. What iDevice are you using?
    iPhone 6s A1688
2. On what version of iOS is it?
    12.4.1
3. What version of checkra1n are you using?
    0.12.1 (arm64 linux)
4. What is your host system (OS version? Hackintosh? VM? etc.)?
    Android 6.0 on 360 F4 smartphone
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
    Micro-USB to USB-A to lightning, 3rd party cable.
6. What are the steps to reproduce the issue?
    Open Terminal Emulator, type `su` to get root permission (I use supersu), connect phone and press the buttons to enter DFU, then run `checkra1n -c` or `checkra1n -cv` .
    It will stuck at `Right before trigger` in normal mode and `Checkmate!` in verbose mode

What do you expect, and what is happening instead?
It's supposed to jailbreak and show the checkra1n apple logo, but nothing happens and checkra1n stucks here.

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
Yes

Any other info, error logs, screenshots, ...?
When checkra1n stucks, lsusb does not show the Apple DFU device `05ac:1227`. Using another cable won't make a difference.

**Comment by gungurbuz** [comment]
i forgot to close this i needed to change operating systems (from ubuntu 18.04 to 20.08)
