### ISSUE TITLE
PUBG Mobile Crashing after checkra1n.

### ISSUE THREAD

**Issue by vismittu** [checkra1n/BugTracker#188]
**What device + iOS version are you on?**
13.1.3

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1.Open PUBG Mobile
2.It loads 
3.It crashes
...

**What do you expect, and what is happening instead?**
I expect the game to open. It crashes instead.

**Any other info, error logs, screenshots, ...?**iPhone X is my device.

**Comment by termz64** [comment]
You're a fucking idiot. Pubg has jb protection. Install liberty lite and close this. Waste of a devs time

**Comment by littlelailo** [comment]
This is because of pubgs jailbreak detection. They add that because it's easier to cheat on a jailbroken device.

**Comment by Siguza** [comment]
@natewarter this is the second time you posted an unfriendly comment. Stop that or you will be banned.

**Comment by YamyuCheung** [comment]
try to use tsprotector
