### ISSUE TITLE
iPhone 7 IOS 14.3 beta 2 won't jailbrake and can not restore backup with iTunes or iMazing?

### ISSUE THREAD

**Issue by harmonium76** [checkra1n/BugTracker#1883]
I had my iPhone 7 jailbreaked when i was on IOS 13.6.1 but i update to 14.3.2, tried checkra1n 0.12.1 and notice that usually when it's about to boot, you see the apple on the screen and after a few seconde you can see the checkra1n code (or the checkra1n logo) appearing but it boots back non jailbreaked. After i've tried to restore a backup using iMazing, doesn't worked, i open iTunes on my Mac Pro, iTunes doesn't see my iPhone. I know that i should'nt try this cause checkra1n wasn't ready for IOS 14.3. Somebody can help me?

**Comment by Siguza** [comment]
#1879

**Comment by harmonium76** [comment]
Hi Siguza! Why did you close my issue, my quest? Thats only my second post here, i don't understand! 
Je parle français, je ne connais pas toutes les règles...

**Comment by Siguza** [comment]
Because it's the same as #1879.
