### ISSUE TITLE
try to use checkra1n and it says iphone x is not supported 

### ISSUE THREAD

**Issue by ssjnight** [checkra1n/BugTracker#1884]
**Tell us about your setup:**
1. What iDevice are you using? iphone 11 
2. On what version of iOS is it? ios 14.0.2
3. What version of checkra1n are you using? 12.0.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? windows 10
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? apple usb

**What are the steps to reproduce the issue?**
1. start up checkra1n
2. plug in device 
3.it says it does support i phone 11 
...

**What do you expect, and what is happening instead?**

to boot up checkra1n 
**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
no

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes 

**Any other info, error logs, screenshots, ...?**
it just  say's it doesn't support iphone 11 i just wanted to know if this could be fixed some how i did the untested check and the skip ar11 check and it still wont start

**Comment by mheealx** [comment]
iPhone 11 is really not supported, checkra1n supports up to iPhone X (A11 devices)
