### ISSUE TITLE
Not going recovery

### ISSUE THREAD

**Issue by rkjangir786** [checkra1n/BugTracker#189]
**What device + iOS version are you on?**

6s+ iOS 13.2.2
**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1start the checkra1n app
2.my device going recovery mode with black screen
3.not going dfu mode
...

**What do you expect, and what is happening instead?**

Only black screen and restart device
**Any other info, error logs, screenshots, ...?**
Na

**Comment by spockers** [comment]
Recovery mode is not "black screen," that's DFU. iTunes will call it recovery, but it's not. DFU is a completely black screen, recovery has the connect to iTunes graphic.

**Comment by littlelailo** [comment]
If you weren't able to resolve this issue, please reopen it. But it seems like you know the difference between recovery and DFU now

**Comment by rkjangir786** [comment]
Yas but I updated ios 13.2.2 
And jailbreak Start with cheakr1n
I click start
My device not going recovery (itune grafic like)
Only black screen but cheakr1n show  you are recovery mode
