### ISSUE TITLE
ios14.2 (iphone 8 plus) ERRORS

### ISSUE THREAD

**Issue by iphonesjb** [checkra1n/BugTracker#1891]
Its not permanent whenever it restarts checkra1n get removed and cydia does not open you have to rejailbreak again to open cydia and to get checkra1n back.

I cant even activate iphone passcode. When you jailbreak it will ask you to remove you iphone passcode after jailbreak you cannot activate it (if you try activating the passcode it will restart and then you have to do all jailbreak process again).

Rest its fine if you do not restart or activate the passcode.. it will work fine.

**Comment by Siguza** [comment]
1. Yes, that's how a tethered jailbreak works.
2. Yes, that is documented and may not be fixable.
