### ISSUE TITLE
Files not necessarily cleaned up and .cydia_no_stash not created

### ISSUE THREAD

**Issue by nn9dev** [checkra1n/BugTracker#19]
okay, might not be an issue because i don't know how all you guys have gone about it, BUT, there seems to be an excess of `.` files in the root directory, lacking `.cydia_no_stash`, along with a binary called `payload`, and I'm also unsure if the binpack directory shouldve been removed or not because it seems like all the binaries were moved to their respective directories.

tell me if i'm wrong.

**Comment by nn9dev** [comment]
oh, `/binpack/Library/LaunchDaemons/dropbear.plist` doesnt seem like it was put in the right place but there is an sshd plist there so i dunno

**Comment by kirb** [comment]
Everything is correct.

The files in / are used so the jailbreak payload knows what state you’re in on next reboot. Cydia doesn’t stash on iOS 11 and up. /binpack is a read-only disk image with basic (BSD) tools, you can `umount` it if you want.

**Comment by nn9dev** [comment]
umount returns that the "resource is busy", can i go ahead and safely unmount it with `-f` or...

**Comment by kirb** [comment]
Should be fine.

**Comment by nn9dev** [comment]
cool. thanks.
