### ISSUE TITLE
 iPad Air (A1474)

### ISSUE THREAD

**Issue by manexmane21** [checkra1n/BugTracker#1903]
Hi, what is checkra1n suitable for iPad Air (A1474) and what is BIAPAS. Thank you

**What do you expect, and what is happening instead?**

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Closing this because the question is unintelligible.

Checkra1n supports the iPad Air 1, I'm not sure what your question is on that. And I don't know of any "BIAPAS" - maybe you mean iCloud Lock bypass, but we don't support that.
