### ISSUE TITLE
Error connecting to lockdownd (lockdownd error -21)

### ISSUE THREAD

**Issue by itzJuless** [checkra1n/BugTracker#1905]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. iPhone X
2. 14.3
3. 0.12.1
4. Macbook air (High Sierra)
5. USB-A original apple usb cable

**What do you expect, and what is happening instead?**
cannot even click  'start' because it says "Error connecting to lockdownd (lockdownd error -21)"
even after check allow untested IOS, skip A11 BPR check (and safe mode)

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
no

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
See https://github.com/checkra1n/BugTracker/issues/1824#issuecomment-727782741
