### ISSUE TITLE
Bug sur iOS 14.3 

### ISSUE THREAD

**Issue by alexisgame** [checkra1n/BugTracker#1909]
Bonjour, j’ai fait le crack hier sur iOS 14.3 sur iPhone X cela a bien fonctionné. Mais une le redémarrage de mon téléphone suite à la suppression d’une application de Cydia que j’avais installé, mon téléphone c’est bloquer et l’app chekra1n c’est supprimé et Cydia bloqué impossible de l’ouvrir et elle reste sur mon téléphone. Merci de me donner une solution.

**Comment by Siguza** [comment]
Based on Google Translate, it sounds like you don't understand the limitations of a tethered jailbreak.  
If that is not the case, please open a new ticket, fill out the template, and please do it in English. Thanks.
