### ISSUE TITLE
Lookinf for checkrain 9.3 in linux

### ISSUE THREAD

**Issue by daniele777** [checkra1n/BugTracker#1913]
I'm looking for old version for linux or windows there are? Because i see  only for mac... THX

**Comment by Siguza** [comment]
The first version to support Linux is 0.9.8.  
But why would you want an old version anyway?

**Comment by daniele777** [comment]
Because i with iOS 0.9.3 ...where Is this version?

**Comment by Siguza** [comment]
You most certainly do not have a device on iOS 0.

I assume you're talking about the iPad mini 1 on iOS 9.3.x. Check out https://phoenixpwn.com for that.

**Comment by daniele777** [comment]
You think work ??

**Comment by daniele777** [comment]
no need checkra1n not ok

**Comment by Siguza** [comment]
Ok look, you've given me zero information to work with.

All I can assume is that you're on an iPad mini 1 on iOS 9.x, which is absolutely not supported by checkra1n. checkra1n only works on 64-bit devices, and only on iOS 12 and up. If your device falls into that range, feel free to open a new ticket, but fill out the template.
