### ISSUE TITLE
Whole Lotta Checkra1n Issues

### ISSUE THREAD

**Issue by vlonesway** [checkra1n/BugTracker#1915]
**Tell us about your setup:**
1. What iDevice are you using? **iPhone** **8**
2. On what version of iOS is it? **14.0**
3. What version of checkra1n are you using? **Beta 0.12.1**
4. What is your host system (OS version? Hackintosh? VM? etc.)? **Macbook Pro OSX El Capitan Version 10.11.6**
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? **Apple Lightning USB cable**

**What are the steps to reproduce the issue?**
1. I installed checkra1n about 3 days ago and everything was fine. Then yesterday I was looking for tweaks to install to cydia, and found a source. 
2. I added the source and saw an updated version of Appsync Unified.
3. I deleted the older version of Appsync Unified.
...

**What do you expect, and what is happening instead?**
I expected the springboard to restart, however my iPhone froze. I restarted my device and noticed safari wouldn't work. I would type something in the search bar and it would freeze whenever I pressed go. So I used checkra1n again to jailbreak my phone. Now the checkra1n loader doesn't appear, cydia gets stuck on the loading screen when I open it, and safari refuses to work. Also, I'm not sure if this is related but whenever I try to download an app from the app store, I never get past the spinning circle.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Comment by Oh-no-00-heer-oobr-inei-isis-behind-u** [comment]
thats becuz you sukd preston's d-k atleast once in ur lifetime.

**Comment by Siguza** [comment]
AppSync Unified does not support iOS 14, so it sounds like you installed one of those counterfeit packages that are built by people who don't know what they're doing.  
You can see if SSH is still up on port 44 and attempt to fix stuff that way. Otherwise you'll just have to do an IPSW restore.

Closing this though, checkra1n seems to work as advertised.
