### ISSUE TITLE
Cannot exit DFU Mode after Checkra1n crashed 

### ISSUE THREAD

**Issue by Override-sys-backup** [checkra1n/BugTracker#1916]
**Tell us about your setup:**
1. What iDevice are you using? Iphone 5s
2. On what version of iOS is it? 12.4.5 (Supported)
3. What version of checkra1n are you using? Linux based (Kali) 
4. What is your host system (OS version? Hackintosh? VM? etc.)? Kali linux booting from USB alongside windows
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Is the USB-A the blue port? If so, I was using the USB-C. Also 3rd party cable.

**What are the steps to reproduce the issue?**
1.  Launch checkra1n
2. Click start after connecting.
3. It puts the device in DFU mode.
4. Crashes after the line gets to the end of the bar (I left it for fifteen minutes)
5. I attempted to restart the iphone but it won't work (Power + home 10s, Power 10s)
6. HELP!
...

**What do you expect, and what is happening instead?**
I wanted to jail break my iphone using checkra1n but everything has to be so goddamned hard.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
I can't click start anymore. So no.

**Any other info, error logs, screenshots, ...?**
N/A

**Comment by demhademha** [comment]
Does checkra1n state your device is in DFU mode?

**Comment by Siguza** [comment]
Disconnect the lightning cable, then just hold power + home until you see the Apple logo.
