### ISSUE TITLE
Ubuntu NO_PUBKEY 

### ISSUE THREAD

**Issue by Pinkyhax** [checkra1n/BugTracker#1919]
Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 3B57AE37123C1C64

The following signatures could not be verified because their public key is not available: NO_PUBKEY 3B57AE37123C1C6

This happend while i trying to install checkra1n on ubuntu 20.04

**Comment by Siguza** [comment]
Did you follow [the instructions](https://checkra.in/linux) and run `sudo apt-key adv --fetch-keys https://assets.checkra.in/debian/archive.key`?

**Comment by Siguza** [comment]
I'll assume it was simply the missing public key.
