### ISSUE TITLE
After reboot jb jb not working

### ISSUE THREAD

**Issue by robi62** [checkra1n/BugTracker#192]
**What device + iOS version are you on?**

12.4 iPhone 6s
**What checkra1n version are you using?**
second beta
**What are the steps to reproduce the issue?**
1.Iphone froze I restarted it connect to jb again but app does not finish jb 
I can see jb progress on screen then stops and after I see
2.Timed out waiting for bootstrap upload (Likely caused by a bad tweak, hold volume up during boot to get into safemode) (Error code: -20)

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?** After jb the first time I installed all my tweaks from  batchomatic app from cydia and they where working fine until iphone froze

**Comment by nullpixel** [comment]
this is not a checkra1n issue. an update will be out soon to allow you to enter safe mode with the volume up button.
