### ISSUE TITLE
l

### ISSUE THREAD

**Issue by vosqi** [checkra1n/BugTracker#1920]
**Tell us about your setup:**
1. What iDevice are you using?
2. iPad 7th Gen
2. On what version of iOS is it?
3. iOS 14.2
3. What version of checkra1n are you using?
4. 0.12.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. Checkn1x 1.1.4
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Lightning cable
**What are the steps to reproduce the issue?**
1. Boot Checkra1n
2. Start and do steps
3. Stuck on Apple logo after pongoos screen
...

**What do you expect, and what is happening instead?**
For the device to boot up in an acceptable time period, instead becomes stuck on the apple screen for more than 30 seconds

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
Device manages to get past PongoOS screen and continues into booting from apple logo which gets stuck there. However it shows that’s it’s done on the client.

**Comment by Siguza** [comment]
If the host says it's done, then your issue is most likely SpringBoard crashing.  
Try using Safe Mode and if that doesn't work, you should still be able to SSH in.  
Closing this though as checkra1n itself seems fully functional.
