### ISSUE TITLE
Remount the checkra1n binpack dmg

### ISSUE THREAD

**Issue by worf1337** [checkra1n/BugTracker#1924]
Hi there!

Does anyone know a way to remount the checkra1n binpack dmg? It seems to unmount often.

**Comment by Siguza** [comment]
Just mount `/private/var/checkra1n.dmg` to `/binpack`.

Also why do you have stuff unmounting that?

**Comment by worf1337** [comment]
> Also why do you have stuff unmounting that?

I genuinely have no idea. Thanks.
