### ISSUE TITLE
checkra1n leftover "devhelper" process

### ISSUE THREAD

**Issue by mailinglists35** [checkra1n/BugTracker#1927]
**Tell us about your setup:**
1. What iDevice are you using? 
iphone 8

2. On what version of iOS is it?
13.5

3. What version of checkra1n are you using?
https://assets.checkra.in/downloads/linux/cli/x86_64/63282886157dd08079c8e41522fdc6d58cfecda783ea8cca79ffc1116f13c355/checkra1n

4. What is your host system (OS version? Hackintosh? VM? etc.)?
ubuntu 18.04.5 kernel 5.4.0-47-generic

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A

**What are the steps to reproduce the issue?**
1. open checkra1n
2. jailbreak phone
3. exit checkra1n
...

**What do you expect, and what is happening instead?**
no leftover `/tmp` weird rootkit-style processes that delete their txt fd

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
no

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
don't know

**Any other info, error logs, screenshots, ...?**
I sh*t myself when I found these processess and wasted a friends time digging for the cause.
Luckily I had bash history timestamps turned on and also systemctl helped determine that the process was started via interactive ssh session and not some other improbable method

````
root@server:~#  lsof -nlPp 59191; systemctl status 59191; history|grep '17:27:08'; ls -l /proc/59191/fd/
COMMAND     PID     USER   FD      TYPE             DEVICE SIZE/OFF       NODE NAME
devhelper 59191        0  cwd       DIR              253,5     4096    7340033 /root
devhelper 59191        0  rtd       DIR              253,5     4096          2 /
devhelper 59191        0  txt       REG              253,5  1043488    3784733 /tmp/devhelper.bNngCj (deleted)
devhelper 59191        0    0r     FIFO               0,13      0t0 1338094038 pipe
devhelper 59191        0    1w     FIFO               0,13      0t0 1338094037 pipe
devhelper 59191        0    2u      CHR              136,2      0t0          5 /dev/pts/2 (deleted)
devhelper 59191        0    3u  netlink                         0t0 1338096903 KOBJECT_UEVENT
devhelper 59191        0    4w     FIFO               0,13      0t0 1338094037 pipe
devhelper 59191        0    5r     FIFO               0,13      0t0 1338094038 pipe
devhelper 59191        0    6u     unix 0xffff946f6f002000      0t0 1338087402 type=STREAM
devhelper 59191        0    7r     FIFO               0,13      0t0 1338096904 pipe
devhelper 59191        0    8w     FIFO               0,13      0t0 1338096904 pipe
devhelper 59191        0    9r     FIFO               0,13      0t0 1338096905 pipe
devhelper 59191        0   10w     FIFO               0,13      0t0 1338096905 pipe
devhelper 59191        0   11u  a_inode               0,14        0      13990 [timerfd]
devhelper 59191        0   12u     unix 0xffff946eb5644c00      0t0 1338093110 type=STREAM
● session-20534.scope - Session 20534 of user root
   Loaded: loaded (/run/systemd/transient/session-20534.scope; transient)
Transient: yes
   Active: active (abandoned) since Sat 2020-12-19 17:26:02 EET; 1 weeks 4 days ago
    Tasks: 6
   CGroup: /user.slice/user-0.slice/session-20534.scope
           ├─59191 /tmp/devhelper.bNngCj
           └─64746 /tmp/devhelper.PfOlBI

Dec 19 17:26:02 server systemd[1]: Started Session 20534 of user root.
Dec 20 10:18:12 server sshd[58291]: pam_unix(sshd:session): session closed for user root
16354  [2020-08-26 17:27:08] zpool status -c model,serial,vendor,size
22077  [2020-12-19 17:27:08] checkra1n
total 0
lr-x------ 1 root root 64 Dec 30 21:12 0 -> 'pipe:[1338094038]'
l-wx------ 1 root root 64 Dec 30 21:12 1 -> 'pipe:[1338094037]'
l-wx------ 1 root root 64 Dec 30 21:12 10 -> 'pipe:[1338096905]'
lrwx------ 1 root root 64 Dec 30 21:12 11 -> 'anon_inode:[timerfd]'
lrwx------ 1 root root 64 Dec 30 21:12 12 -> 'socket:[1338093110]'
lrwx------ 1 root root 64 Dec 30 21:12 2 -> '/dev/pts/2 (deleted)'
lrwx------ 1 root root 64 Dec 30 21:12 3 -> 'socket:[1338096903]'
l-wx------ 1 root root 64 Dec 30 21:12 4 -> 'pipe:[1338094037]'
lr-x------ 1 root root 64 Dec 30 21:12 5 -> 'pipe:[1338094038]'
lrwx------ 1 root root 64 Dec 30 21:12 6 -> 'socket:[1338087402]'
lr-x------ 1 root root 64 Dec 30 21:12 7 -> 'pipe:[1338096904]'
l-wx------ 1 root root 64 Dec 30 21:12 8 -> 'pipe:[1338096904]'
lr-x------ 1 root root 64 Dec 30 21:12 9 -> 'pipe:[1338096905]'
````

**Comment by Siguza** [comment]
So - what we're doing here is embed a full separate binary into checkra1n, which we extract, launch and communicate to at runtime. The reason is licensing. On macOS we can link this all into a dylib, and on Ubuntu you could actually install from our APT repo (see https://checkra.in/linux), which would use dynamically linked libraries instead.  
But the CLI builds are intended to work on any flavour of Linux (save for maybe ChromeOS), so we couldn't really do that. :/

**Comment by mailinglists35** [comment]
I understand the reason, but I don't think checkra1n should leave running processes, no matter if the jb was successful or not. it should watch for and kill any spawned processes upon exit, and not just assume they will exit voluntarily (which did not happen in my case)

btw, the modern way of adding repositories in debian/ubuntu is to create a separate `.list` file under `/etc/apt/sources.list.d/`, and not to alter `/etc/apt/sources.list`.

the above link instructs user to alter sources.list which is not recommended.

**Comment by GPopZach** [comment]
Well, considering it's slated to be released as an open source project (which I would imagine is a legal necessity considering your use of libraries or vulnerability reports that have licenses that mandate it), should you be making any design decisions based on licensing concerns?

My point notwithstanding, it's absolutely trivial to launch the devhelper binary as a child process and terminate it along with the main application, and if you can't figure that out, it's even easier to simply use the `system(const char *command)` function included in `stdlib.h`. In your case, you could use `system("killall -9 devhelper");` assuming you're using C, and willing to make the assumption that the user's system shell is POSIX compliant. If you're using some other language I can tell you the equivalent for that as well.

**Comment by mailinglists35** [comment]
> 
> 
> So - what we're doing here is embed a full separate binary into checkra1n, which we extract, launch and communicate to at runtime. The reason is licensing. On macOS we can link this all into a dylib, and on Ubuntu you could actually install from our APT repo (see https://checkra.in/linux), which would use dynamically linked libraries instead.
> But the CLI builds are intended to work on any flavour of Linux (save for maybe ChromeOS), so we couldn't really do that. :/

I'm too lazy to create a new issue, but installing the ubuntu repo on 18.04LTS brings in `libusbmuxd6` from checkra1n repo which breaks system-installed `usbmuxd` that is shipped with `libusbmuxd4`. this in turn prevent any other `idevice` utilities from working.

with libusbmuxd6 from checkra1n repo:

````
Jan 30 14:37:22 server kernel: ipheth 1-1.1:4.2: Apple iPhone USB Ethernet device attached
Jan 30 14:37:22 server kernel: usbmuxd[59805]: segfault at fffffffffffffff9 ip 00007f8e7ed429fd sp 00007f8e7b35ddb0 error 5 in libc-2.27.so[7f8e7ecab000+1e7000]
Jan 30 14:37:22 server kernel: Code: 8b 04 25 28 00 00 00 48 89 44 24 28 31 c0 48 8b 05 00 35 35 00 48 8b 00 48 85 c0 0f 85 9c 02 00 00 48 85 ff 0f 84 13 01 00 00 <48> 8b 77 f8 4c 8d 6f f0 40 f6 c6 02 0f 85 29 01 00 00 48 8b 2d 62
````

reverting to os versions makes usbmuxd work again

broken: `Upgrade: libplist3:amd64 (2.0.0-2ubuntu1, 2.2.0-4), libimobiledevice6:amd64 (1.2.1~git20171128.5a854327+dfsg-0.1, 1.3.0-3)`
working: `libimobiledevice6=1.2.1~git20171128.5a854327+dfsg-0.1 libplist3=2.0.0-2ubuntu1`

**Comment by mailinglists35** [comment]
I managed to make everyone happy by mixing in updated packages from debian and force-overwrite manual dpkg install of libirecovery3 from checkra1n repo:

````
# dpkg -i --force-overwrite /var/cache/apt/archives/libirecovery3_1.0.0-2_amd64.deb
(Reading database ... 427517 files and directories currently installed.)
Preparing to unpack .../libirecovery3_1.0.0-2_amd64.deb ...
Unpacking libirecovery3:amd64 (1.0.0-2) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/lib/udev/rules.d/39-libirecovery.rules', which is also in package libirecovery-common 1.0.0-5
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/x86_64-linux-gnu/libirecovery-1.0.so.3.0.0', which is also in package libirecovery-1.0-3:amd64 1.0.0-5
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/x86_64-linux-gnu/libirecovery-1.0.so.3', which is also in package libirecovery-1.0-3:amd64 1.0.0-5
Setting up libirecovery3:amd64 (1.0.0-2) ...
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
````


final result:
````
ii  idevicerestore             1.0.0-3            amd64              command-line application to restore firmware files to iOS
ii  libimobiledevice6:amd64    1.3.0-3            amd64              Library for communicating with iPhone and other Apple devi
ii  libirecovery-1.0-3:amd64   1.0.0-5            amd64              Library allowing communication with iBoot/iBSS of iOS devi
ii  libirecovery-common        1.0.0-5            all                Common files for libirecovery
ii  libirecovery3:amd64        1.0.0-2            amd64              Library and utility to talk to iBoot/iBSS via USB
ii  libplist3:amd64            2.2.0-4            amd64              Library for handling Apple binary and XML property lists
ii  libusb-1.0-0:amd64         2:1.0.22-2         amd64              userspace USB programming library
ii  libusbmuxd6:amd64          2.0.2-3            amd64              USB multiplexor daemon for iPhone and iPod Touch devices -
ii  usbmuxd                    1.1.1-2            amd64              USB multiplexor daemon for iPhone and iPod Touch devices
````

**Comment by Siguza** [comment]
Should now be properly cleaned up on 0.12.3.
