### ISSUE TITLE
Neptune when i download it on checkra1n my device is keep respring and i cant restore the rootfs system please update neptune or fix it now please

### ISSUE THREAD

**Issue by TysonSchultz51345** [checkra1n/BugTracker#193]
**iPhone 7+ 13.2.2 and 13.1.3**

**checkra1n 0.9.1 beta**

**I cant fix this please fix it**
1.Neptune when i download it on checkra1n my device is keep respiring and i cant restore the rootfs system please update Neptune or fix it now please
2.Neptune when i download it on checkra1n my device is keep respiring and i cant restore the rootfs system please update Neptune or fix it now please
3.Neptune when i download it on checkra1n my device is keep respiring and i cant restore the rootfs system please update Neptune or fix it now please
...

**please help or i will bring this phone to apple**

**Neptune when i download it on checkra1n my device is keep respiring and i cant restore the rootfs system please update Neptune or fix it now please?**

**Comment by nullpixel** [comment]
this is not a checkra1n issue. an update will be out soon to allow you to enter safe mode with the volume up button.
