### ISSUE TITLE
Accidentally removed cable before checra1n finished. Rebooted and tried again and cam]nt jailbreak

### ISSUE THREAD

**Issue by abacus0101** [checkra1n/BugTracker#1934]
Is there a way to fix up my screwup. I disconnected cable after i saw sucessdully in dfu

*Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
This shouldn't be an issue at all. Rebooting (and perhaps closing and re-opening checkra1n on your host) should be enough to fix this. But your report doesn't include any information to go off. If your issue persists, please open a new ticket and describe exactly what fails when trying to jailbreak again.
