### ISSUE TITLE
checkra1n/Cydia not showing in iOS 14.2+? Here's the solution.

### ISSUE THREAD

**Issue by GPopZach** [checkra1n/BugTracker#1942]
Disregard the nonsense in #1830. Idiot just smashed some keys and the application cache happened to update the next time he restarted. Changing your language settings has no correlation with app display.

Run it using a shortcut. It's under the Scripting category. I've been able to reproduce the issue consistently on an iPhone 10 running the final 14.2 developer beta, and it is consistently displayed in the context menu for the "Open App" action from shortcuts. The other "fixes" I've seen have been spotty and inconsistent, I have yet to see a shortcut not work for either the checkra1n application or Cydia.. 

> 1. JAILBREAK IPHONE USING CHECKRA1N
> 2. AFTER YOU HAVE BOOTED NOTHING WILL APPEAR
> 3. GO TO SETTINGS>GENERAL>LANGUAGE & REGION> IPHONE LANGUAGE> CHOOSE A LANGUAGE THAT YOU KNOW
> 4. IT WILL APPLY THE LANGUAGE YOU CHOOSE
> 5. EXIT OUT OF SETTINGS
> 6. CHECKRAIN LOADER SHOULD APPEAR
> 7. INSTALL CYDIA; CYDIA, WILL NOT APPEAR AT THIS TIME
> 8. GO BACK TO SETTINGS>GENERAL>LANGUAGE & REGION> IPHONE LANGUAGE> AND CHOOSE YOUR ORIGINAL LANGUAGE
> 9. LET IT SET THE LANGUAGE
> 10. CYDIA WILL APPEAR IN YOUR HOME SCREEN.
> 
> **It seems you need to re-spring your device to see the bootloader for checkRa1n.** **This was done on an iPhone 7 running IOS 14.2**
> Picture :
> https://ibb.co/j4C06Ws

As an aside, are you kidding me? Change your language setting? You just tried a bunch of random shit, got lucky that it started working on that one, and act like you found a fix 😒 
@nullpixel @Siguza @DanyL @jacc Can we get this issue closed? It makes this idiot's random monkey solution look like some kind of official fix.

_Originally posted by @Zachpocalypse in https://github.com/checkra1n/BugTracker/issues/1830#issuecomment-751494165_

**Comment by demhademha** [comment]
Duplicate of https://github.com/checkra1n/BugTracker/issues/1882

**Comment by GPopZach** [comment]
@demhademha Right you are! I didn't see that, I'll go ahead and close this then!
