### ISSUE TITLE
Stuck on right before trigger

### ISSUE THREAD

**Issue by hellisabove** [checkra1n/BugTracker#1950]
I try to jailbreak my iphone 8 on ios 14.2 with version 0.12.1 but everytime it gets stuck on "Right before trigger (this is the real bug setup)"

**Comment by r1bbi** [comment]
me  too with iPad 6th gen *ipadOs 14.2*

**Comment by ForgottenGods** [comment]
I have been trying with an iPad mini 2, and I have found another partial workaround. I was able to replicate it as well but in my test I did it 20 times and was only able to get it to work 3 times.

What I did was when it got at "right before trigger " I rapidly unplugged and replugged my iPad it toke about 3 times then I would see the "booting" line ,however most of time what happened was it just booted back to the setup menu (my device was reset to act as an icloud locked device)
But 3 out of the 20 times I tried it went through the whole process.
This is on a windows pc using bootra1n as I don't own a mac, also I'm seemed to have better success rate using the 32bit version of bootra1n ,even though my pc is 64bit

I hope this helps somebody as it seems to be a little more consistent. Have a good day

**Comment by hellisabove** [comment]
> I have been trying with an iPad mini 2, and I have found another partial workaround. I was able to replicate it as well but in my test I did it 20 times and was only able to get it to work 3 times.
> 
> What I did was when it got at "right before trigger " I rapidly unplugged and replugged my iPad it toke about 3 times then I would see the "booting" line ,however most of time what happened was it just booted back to the setup menu (my device was reset to act as an icloud locked device)
> But 3 out of the 20 times I tried it went through the whole process.
> This is on a windows pc using bootra1n as I don't own a mac, also I'm seemed to have better success rate using the 32bit version of bootra1n ,even though my pc is 64bit
> 
> I hope this helps somebody as it seems to be a little more consistent. Have a good day

You could make a live usb of ubuntu and use the binary from the website. That's what I did. Anyway The fix I found working is putting the device in dfu and use sudo checkra1n -c to run checra1n in cli mode.
