### ISSUE TITLE
Error getting passcode state parsing error pls help 

### ISSUE THREAD

**Issue by YahmoStudio** [checkra1n/BugTracker#1956]
Hey i want to jailbreak my IPhone x GSM IOS 14.3 phone and evertime i try it this message come
![Screenshot from 2021-01-14 16-16-49](https://user-images.githubusercontent.com/64530630/104617895-ebb2cc00-5683-11eb-86f8-44b9fc3d405e.png)

**Comment by Siguza** [comment]
Duplicate of #1941.
