### ISSUE TITLE
USB Error (Error code: -77)

### ISSUE THREAD

**Issue by Loy6410** [checkra1n/BugTracker#1965]
**Tell us about your setup:**
1. What iDevice are you using?:  iPhone 6S
2. On what version of iOS is it?:  iOS 14.3
3. What version of checkra1n are you using?:  0.12.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?:  Linux Ubuntu 14.04
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?:  Lightning to USB Apple Official Cable

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**:  When it turns on and gives the screen with the Apple logo together with that of checkra1n the iPhone turns on and on the computer it says USB error (error code: -77)

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**:  No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**:  

**Any other info, error logs, screenshots, ...?**:  No

**Comment by 24rtj** [comment]
Hi

**Comment by AdresatHesusa** [comment]
The problem of checkra1n itself, you need to wait for an update or buy a macbook to install jailbreak on the iphone

**Comment by 24rtj** [comment]
I

**Comment by AndreCalifa** [comment]
Try using original cable and/or a different USB port

**Comment by Loy6410** [comment]
> Try using original cable and/or a different USB port

I use it.

**Comment by Pie8** [comment]
![image](https://user-images.githubusercontent.com/79139501/108045721-15c12a80-7044-11eb-99cf-0533781111ac.jpeg)

**Comment by Pie8** [comment]
i got the same problem

**Comment by ghost** [comment]
I have the same problem
