### ISSUE TITLE
iPhone 7 Plus dfu

### ISSUE THREAD

**Issue by Imahacker39** [checkra1n/BugTracker#1969]
I do the steps, hold side button and volume down button for 4 seconds, then Hold the volume down button for 10 seconds. I do that and a Apple logo pops up on my screen and reboots my device :/

**Comment by AdresatHesusa** [comment]
The problem of checkra1n itself, you need to wait for an update or buy a macbook to install jailbreak on the iphone

**Comment by Siguza** [comment]
If you can't put your device in DFU mode, then there's nothing we can do about that.
