### ISSUE TITLE
Cydia crashes sometimes while installing tweaks.

### ISSUE THREAD

**Issue by vismittu** [checkra1n/BugTracker#197]
**What device + iOS version are you on?**
iPhone X iOS 13.1.3

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1.open cydia
2.install a tweak
3.it crashes randomly not always.
...

**What do you expect, and what is happening instead?**
The tweak is supposed to be installed and be usable. It puts my device into a non usable state until restarted my device.

**Any other info, error logs, screenshots, ...?**

**Comment by littlelailo** [comment]
This is an issue with the tweak/Cydia and not with checkra1n itself
