### ISSUE TITLE
iOS 14.2 Iphone 8 Checkra1n 0.12.2 Passcode after jailbreak

### ISSUE THREAD

**Issue by AndreCalifa** [checkra1n/BugTracker#1974]
**Tell us about your setup:**
1. What iDevice are you using?
2. iPhone 8
2. On what version of iOS is it?
3. 14.2
3. What version of checkra1n are you using?
4. 0.12.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. macbook pro 2009
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
6. Original iphone cable

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**
AFTER JAILBREAK (WHICH WORKED FINE) I'M NOT ABLE TO PUT BACK AGAIN PASSCODE AND/OR TOUCH ID... I TRIED A FEW TIMES BUT AFTER A PLACE THE PASSCODE THE PHONE RESTART AND LOSE THE CYDIA ACCESS, SO I HAVE TO REINSTALL. IS THERE A FIX FOR THAT?

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Nope, SEP will kill you if you try.
