### ISSUE TITLE
Icons remain after uninstalling tweak

### ISSUE THREAD

**Issue by vismittu** [checkra1n/BugTracker#198]
**What device + iOS version are you on?**
iPhone X iOS 13.1.3

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1.uninstall any tweak which has app like snapback
2.go to home
3.the icon remains and the tweak doesn’t work
...

**What do you expect, and what is happening instead?**
The icon is supposed to be gone.

**Any other info, error logs, screenshots, ...?**it remains even if i restart spring board.

**Comment by nullpixel** [comment]
dupe of #62
