### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by samchouse** [checkra1n/BugTracker#1981]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7
2. On what version of iOS is it? 14.1
3. What version of checkra1n are you using? 0.12.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Kubuntu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple

**What are the steps to reproduce the issue?**
1. Install checkra1n via apt
2. sudo checkra1n
3. Jailbreak

**What do you expect, and what is happening instead?**
I expect to jailbreak but I get a `Sementation fault` instead.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
No

**Comment by Siguza** [comment]
Could this be the same as #1928?  
If so, adding `-g` on the command line should provide a workaround.

**Comment by samchouse** [comment]
Seemed to fix it

**Comment by samchouse** [comment]
Nevermind just got  `- [!]: Uh oh, got SIGSEGV, trying to clean up the mess...`

**Comment by wvabrinskas** [comment]
I'm getting a segfault as well. here is the log: 

https://ghostbin.co/paste/v3muf

**Comment by andrelec1** [comment]
same here, segmentation fault with a `sudo checkra1in` in terminal ...

start with the `-g` and use the GUI work ...

**Comment by wvabrinskas** [comment]
`-g` does not work as well

**Comment by wvabrinskas** [comment]
This issue is not present on the linux (Ubuntu) version of the tool, however after getting into recovery mode through the tool it crashes. Restarting it does allow me to finish the jailbreak process.
