### ISSUE TITLE
Checkrain 12.2 crashing on macOS 11.2 for jailbreak on tvOS 14.3.

### ISSUE THREAD

**Issue by itsMausyn** [checkra1n/BugTracker#1989]
**Tell us about your setup:**
1. Apple TV 4 (32gb)
2. tvOS 14.3
3. Checkra1n 0.12.2 beta
4. 13 inch Intel MacBook Pro 2016 with 4 usb-c ports running macOS Big Sur 11.2 
5. Usb-c to usb-c cable from MacBook to Apple TV.

**What are the steps to reproduce the issue?**
1. At the DFU stage the app crashes and finder asks to reopen the app as it crashed. 
2. I think it might have to do with a change in macOS 11.2
3.never had an issue before with same set up. Only difference was upgrading to 11.2 
...

**What do you expect, and what is happening instead?**
Expecting the inject of the jailbreak. App crashes. (Moved app to desktop, same issue. Tried running through terminal. Same issue.) 

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No, Apple TV remains in DFU mode. 

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes 

**Any other info, error logs, screenshots, ...?**
None.

**Comment by Siguza** [comment]
Hmm. I wonder if that's the same issue that seems to be plaguing the 11.3 beta... because I only have a USB-A MacBook, and I can't reproduce it there.

**Comment by itsMausyn** [comment]
> Hmm. I wonder if that's the same issue that seems to be plaguing the 11.3 beta... because I only have a USB-A MacBook, and I can't reproduce it there.

I think there might be something there, everything was working perfectly fine on 11.1- once I updated I noticed the problem:/

**Comment by arturbier** [comment]
+

**Comment by raphaelts3** [comment]
I was having the same behavior with `macOS 11.3`, but the fresh new `0.12.3` worked perfectly! Thank you!
@cc/ @itsstormywithin

**Comment by itsMausyn** [comment]
Can confirm 0.12.3 fixed it for me too!
