### ISSUE TITLE
Jail break IPhone 11

### ISSUE THREAD

**Issue by idk90** [checkra1n/BugTracker#1991]
**Tell us about your setup:**
1. What iDevice are you using? Iphone 11
2. On what version of iOS is it?IOS14.2
3. What version of checkra1n are you using? Beta 0.12.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Mac
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Usb A 3rd party

**What do you expect, and what is happening instead?**
It said my phone was not supported i turned off the all untested ios and the skip A11 BPR check and it still says it wasn't supported

**Any other info, error logs, screenshots, ...?**

ECID: 0x12552c36d8802e (idk if this is a error code or log)

**Comment by Siguza** [comment]
iPhone 11 isn't vulnerable to checkm8.
