### ISSUE TITLE
Loader.app crashes installing Cydia on iPads

### ISSUE THREAD

**Issue by QwebYT** [checkra1n/BugTracker#2]
**What device + iOS version are you on?**

Ipad 6th gen 2018 13.2, macbook air Catalina
**What are the steps to reproduce the issue?**
1.press load cydia
2.
3.
...

**What do you expect, and what is happening instead?**
i expect it to load cydia but when i press the button the app crashes

**Any other info, error logs, screenshots, ...?**

**Comment by Deppjones123** [comment]
What device + iOS version are you on?

iPad Air 1st gen (iPad4,2) / iOS 12.4.3,  MacPro5,1 / Mojave 10.14.6

iPad Pro 10,5 at 13.2.2 the same problem

What are the steps to reproduce the issue?
1.press load cydia
2.
3.
...

What do you expect, and what is happening instead?
i expect it to load cydia but when i press the button the app crashes

Any other info, error logs, screenshots, ...?

**Comment by nullpixel** [comment]
Hi, this is a known bug and will be resolved in a future release soon.

**Comment by mpacepa** [comment]
@nullpixel Just want to say thank you from the bottom of my heart for all your guys' hard work!

**Comment by Samplasion** [comment]
You can open the app in Slide Over view and it'll work, as a workaround

**Comment by mpacepa** [comment]
> You can open the app in Slide Over view and it'll work, as a workaround

Do you mean by swiping up and choosing the checkra1n app? It doesn’t work for me... (iPad Pro 10.5 WiFi )

**Comment by Deppjones123** [comment]
> You can open the app in Slide Over view and it'll work, as a workaround

Awesome! Worked like a charm on iPad Pro 10,5 with 13.2.2. Thanks a lot.

**Comment by Deppjones123** [comment]
> > You can open the app in Slide Over view and it'll work, as a workaround
> 
> Do you mean by swiping up and choosing the checkra1n app? It doesn’t work for me... (iPad Pro 10.5 WiFi )

Put Checkra1n into the dock, start one of your apps, swipe from the bottom to show the dock, select Checkra1n and pull it over the open app. Install Cydia :-)

**Comment by mpacepa** [comment]
> > > You can open the app in Slide Over view and it'll work, as a workaround
> > 
> > 
> > Do you mean by swiping up and choosing the checkra1n app? It doesn’t work for me... (iPad Pro 10.5 WiFi )
> 
> Put Checkra1n into the dock, start one of your apps, swipe from the bottom to show the dock, select Checkra1n and pull it over the open app. Install Cydia :-)

Awesome that worked !!! Thanks so much!

**Comment by jvaglivelo** [comment]
> You can open the app in Slide Over view and it'll work, as a workaround

Here to confirm that this worked, iPad 6th gen iOS 13.2.2

**Comment by AidanDaniel97** [comment]
Also worked here iPad Air (1st gen) 12.3.1

**Comment by zra95** [comment]
Same things on iPad mini4 Cellular, thank's for impressive works btw !

**Comment by charlie-niekirk** [comment]
Works like a treat on my iPad Pro 10.5 LTE, thanks

**Comment by woachk** [comment]
This issue is fixed in 0.9.1.

Please download the latest version at https://checkra.in.

**Comment by panhaseav** [comment]
ipad pro 10.5 inch wont enter dfu mode it just keep showing the apples logo. Any help would be appreciate.

**Comment by Deppjones123** [comment]
"ipad pro 10.5 inch wont enter dfu mode it just keep showing the apples logo. Any help would be appreciate."

Push Home and Power Button for 10 seconds. Release the Power Button but keep pushing the Home Button until you get the iTunes message, that a device in restore mode was found.

**Comment by jvaglivelo** [comment]
> ipad pro 10.5 inch wont enter dfu mode it just keep showing the apples logo. Any help would be appreciate.

Had this issue and it was a problem with the cable I used. Had to use a USB cable on my MBP, couldnt get USB C - Lightning to enter DFU mode

**Comment by kirb** [comment]
Going to lock this thread since the bug was fixed and it’s attracting some unrelated comments.
