### ISSUE TITLE
Cydia Installation Crash - iPad Pro 10.5 (WiFi) iOS 13.2.2

### ISSUE THREAD

**Issue by mpacepa** [checkra1n/BugTracker#20]
**What device + iOS version are you on?**
iPad Pro 10.5 (WiFi) iOS 13.2.2 (fresh restore)

**What are the steps to reproduce the issue?**
1. checkra1n does its magic
2. Upon startup, open the checkra!n app
3. Click on Cydia installation
4. CRASH (app closes)
...

**What do you expect, and what is happening instead?**
I believe this is the 2nd Gen iPad Pro so I'm thinking my iPad is supported..

**Any other info, error logs, screenshots, ...?**

**Comment by Lakr233** [comment]
it should be the app problem. calling action sheet is not allowed on the iPad.

**Comment by mpacepa** [comment]
i tried re-running checkra1n a 2nd time and same thing happens

**Comment by nullpixel** [comment]
Hi, I've closed this issue as a duplicate of #2.
