### ISSUE TITLE
Jailbreaking seems to work but then "crashes" iDevice, then back to normal

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#2002]
**Tell us about your setup:**
1. What iDevice are you using?
**iPad 6th Generation - A10**
2. On what version of iOS is it?
**14.2**
3. What version of checkra1n are you using?
**0.12.2 beta**
4. What is your host system (OS version? Hackintosh? VM? etc.)?
**Raspberry Pi 4 - 4GB, Raspberry Pi OS, Debian**
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
**Using both third-party and official Apple cable, USB-C to Lightning.**

**What are the steps to reproduce the issue?**
1. Connect iDevice to host
2. Launch checkra1n
3. Enable relevant settings; A11 BPR Check, allow untested iOS versions
4. Jailbreak as normal
5. Wait

**What do you expect, and what is happening instead?**
I would expect it to launch to a functioning jailbreak with checkra1n and Cydia. 

Instead, it:
- First boots as it should, Apple logo gets replaced with the checkra1n logo
- Custom respring animation appears for ~1 minute
- After this, two things can happen:
    - **Either it:**
        - Goes black for ~5 seconds, then respring animation appears for another 30 seconds or so
        - Repeats ^^^ again
        - Launches into jailbroken home screen
        - Freezes for ~1 minute
        - Screen goes black
        - Shows Apple logo, boots back into "normal", non-jailbroken mode
    - **Or it:**
        - Goes black for ~5 seconds, then respring animation appears for another 30 seconds or so
        - Goes black for another 5-10 seconds
        - Shows Apple logo, boots back into "normal", non-jailbroken mode

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
No.

**Any other info, error logs, screenshots, ...?**
Attempted the same with the standalone checkra1n application as well as images such as [checkn1x](https://github.com/asineth0/checkn1x) and [pira1n](https://github.com/raspberryenvoie/piRa1n).

**Comment by Siguza** [comment]
Boot in Safe Mode.

**Comment by ghost** [comment]
Yep, turned out the issue was missing/out of date USB drivers.

Damnit, Linux.
