### ISSUE TITLE
Weird Issue

### ISSUE THREAD

**Issue by AyaanZaveri** [checkra1n/BugTracker#2003]
I woke up and my Jailbreak went into a weird phase. None of the tweaks were working but I was still jailbroken. You might be thinking there might be a tweak thats causing this! But I removed them all! I’m on iOS 12.4.8 and using Odysseyra1n. Why is this happening!?!

**Comment by Siguza** [comment]
We didn't develop Odysseyra1n. Ask CoolStar.
