### ISSUE TITLE
Error for rejailbreak

### ISSUE THREAD

**Issue by Filtar2000** [checkra1n/BugTracker#201]
**What device + iOS version are you on?**
Iphone 7 plus - IOS 13.1.2

**What checkra1n version are you using?**
beta 0.9
**What are the steps to reproduce the issue?**
1.Jailbreak device
2.Turn off
3. Try to rejailbreak... (it doesn't work), it will restart as normal mode (non jailbroken)
...

**What do you expect, and what is happening instead?**

I expect that my device is rejailbroken. I have cydia installed but not checkra1n app and it isn't jailbroken
**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Hi, does rebooting into no substrate mode (hold volume up whilst jailbreaking) resolve this issue for you?

**Comment by perpelator** [comment]
@Filtar2000 Here’s now I got it: 1. Plug in your device. 2: Click start and get into recovery mode via Checkra1n (don’t manually go into recovery mode via buttons yourself. Let checkra1n do it for you by pressing next). 3: Once your device is detected again, begin to start the DFU mode process. After get ready (which is 3 seconds), the next step will begin at 6 seconds. Do NOT begin until that hits 5 seconds. 4: Continue to do what it says at the normal amount of said time. Personally I started at 6 seconds but then cut all the other steps short by 1 second, but it’ll work either way. I personally was using a Hackintosh via usb a 2.0 on MacOS 10.13.6. Cannot confirm this method works (but it should) for other versions. I tested this on both 0.9 and 0.9.1, so should carry over with the following versions until fixed. Happy Jailbreaking, and let me know if this works. :)

**Comment by perpelator** [comment]
@Filtar2000 Here’s now I got it: 1. Plug in your device. 2: Click start and get into recovery mode via Checkra1n (don’t manually go into recovery mode via buttons yourself. Let checkra1n do it for you by pressing next). 3: Once your device is detected again, begin to start the DFU mode process. After get ready (which is 3 seconds), the next step will begin at 6 seconds. Do NOT begin until that hits 5 seconds. 4: Continue to do what it says at the normal amount of said time. Personally I started at 6 seconds but then cut all the other steps short by 1 second, but it’ll work either way. I personally was using a Hackintosh via usb a 2.0 on MacOS 10.13.6. Cannot confirm this method works (but it should) for other versions. I tested this on both 0.9 and 0.9.1, so should carry over with the following versions until fixed. Happy Jailbreaking, and let me know if this works. :)

**Comment by Filtar2000** [comment]
@nullpixel how to get into no substrate mode?
@perpelator i did the same process, but it didn't work

**Comment by perpelator** [comment]
@Filtar2000 Hold volume up button on boot (on the Apple logo).

**Comment by Filtar2000** [comment]
@perpelator no substrate mode doesn't work.
I turnd off my iphone, i booted it and when I immediately saw the apple logo i holded volume up button but it doesn't work

**Comment by Filtar2000** [comment]
no substrate mode doesn't work

**Comment by Filtar2000** [comment]
@nullpixel man no substrate mode doesn't work, what can i do?

**Comment by Filtar2000** [comment]
I solved it, you need to download 0.9.3 version from the checkra1n website. Connect your device, tick the safe mode option when you open the application from the desktop. Click start, when the device is booted remove the last tweak or the one you know it's the one that freezed your device
