### ISSUE TITLE
Home button broken after jailbreaking, touch id works

### ISSUE THREAD

**Issue by Elevate-U** [checkra1n/BugTracker#2015]
**Tell us about your setup:**
1. What iDevice are you using?iPhone 7 Plus
2. On what version of iOS is it? 14.4 (broke on 13.5.1)
3. What version of checkra1n are you using? 0.12.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Mac OS Catalina 10.15.7
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A 3rd party cable
**What are the steps to reproduce the issue?**
1.Jailbreak
...

**What do you expect, and what is happening instead?**
I expected my home button to work, but one day it just randomly stopped working, touch id is fine, but it just got all glitchy and eventually just broke. One time, after rejailbreaking due to a random reboot, it worked, but after my phone rebooting again, it broke and never came back.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
Yes

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
I don't think this is a hardware issue due to the fact it came back again, although short-lived. Plus my touch ID still works so it couldn't be that. When my home button started glitching, it started being unresponsive but still kinda worked and little touches activated it, but slowly over the course of the day, it started being more and more unresponsive until it just broke entirely, except for the touch ID which has zero problems. Software-wise, the phone knows there's a home button and didn't say that the home button was broken, so something that had to do with checkra1n caused this problem.

**Comment by Siguza** [comment]
Does it work if you reboot into unjailbroken mode?

**Comment by Elevate-U** [comment]
it doesn't work but I realised its due to the fact I'm supposed to hold down the power button until checkrain says the bug setup screen, probably something to do with the fact DFU mode wasn't properly achieved.

**Comment by Mexicool** [comment]
> **Tell us about your setup:**
> 
> 1. What iDevice are you using?iPhone 7 Plus
> 
> 2. On what version of iOS is it? 14.4 (broke on 13.5.1)
> 
> 3. What version of checkra1n are you using? 0.12.2
> 
> 4. What is your host system (OS version? Hackintosh? VM? etc.)? Mac OS Catalina 10.15.7
> 
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
> 
> USB-A 3rd party cable
> 
> **What are the steps to reproduce the issue?**
> 
> 1.Jailbreak
> 
> ...
> 
> 
> 
> **What do you expect, and what is happening instead?**
> 
> I expected my home button to work, but one day it just randomly stopped working, touch id is fine, but it just got all glitchy and eventually just broke. One time, after rejailbreaking due to a random reboot, it worked, but after my phone rebooting again, it broke and never came back.
> 
> 
> 
> **Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
> 
> Yes
> 
> 
> 
> **Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
> 
> Yes
> 
> 
> 
> **Any other info, error logs, screenshots, ...?**
> 
> I don't think this is a hardware issue due to the fact it came back again, although short-lived. Plus my touch ID still works so it couldn't be that. When my home button started glitching, it started being unresponsive but still kinda worked and little touches activated it, but slowly over the course of the day, it started being more and more unresponsive until it just broke entirely, except for the touch ID which has zero problems. Software-wise, the phone knows there's a home button and didn't say that the home button was broken, so something that had to do with checkra1n caused this problem.
