### ISSUE TITLE
checkra1n crashing on ipad air 2 iOS 14.4 error -79

### ISSUE THREAD

**Issue by tzmercurio** [checkra1n/BugTracker#2018]
hi guys, I am trying to jailbreak my iPad Air 2 on iOS 64GB, when checkra1n says "booting" the ipad shows only the Apple logo instead of Checkra1n and reboots then checkra1n app shows -79 error. any clue? I tried on ubuntu and mac with no success.

**Comment by Siguza** [comment]
Duplicate of #1880.
