### ISSUE TITLE
Camera not working on 0.9.1

### ISSUE THREAD

**Issue by Joyfilled** [checkra1n/BugTracker#202]
**What device + iOS version are you on?**
iOS 13.2 iPhone 6s

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. Open camera
2.
3.
...

**What do you expect, and what is happening instead?**

My camera working
**Any other info, error logs, screenshots, ...?**

**Comment by kpwn** [comment]
What device + iOS version are you using? Camera is working fine on my devices. 
What tweaks do you have installed?

**Comment by Joyfilled** [comment]
> What device + iOS version are you using? Camera is working fine on my devices.
> What tweaks do you have installed?

I’m on 13.2 with an iPhone 6s, I also have the payment not completed issue. It’s fixed when i re jailbreak but then it happens again

**Comment by Joyfilled** [comment]
> What device + iOS version are you using? Camera is working fine on my devices.
> What tweaks do you have installed?

I’m on 13.2 with an iPhone 6s, I also have the payment not completed issue.

**Comment by Joyfilled** [comment]
Tweak list:

AppList: 1.5.14
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 0.7 Transitional (apt-key): 1:0
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Atlantic: 1.0b5
AureliaOS: 1.0.0
Base Structure: 1-5
BatteryPercent12: 1.0.1
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-1
bzip2: 1.0.6-1
CA Certs: 0.0.2
CCModules: 1.4-3
CCSupport: 1.2.2
Cephei: 1.13.1-2
CircleIcons: 1.1.3-15
CleanHomeScreen: 1.0.4
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cydia Installer: 1.1.32~b22
Cydia Substrate: 0.9.7100~b3
Cydia Translations: 1.1.32~b1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
Essential: 0-1
file: 5.35-2
Find Utilities: 4.6.0-2
Flame: 1.3
FloatingDock: 1.5
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
HapticKeys: 2.9
HS.Ryu_006 Fluid Widget: 1.0.8
Installer Prefs: 0.1
iOS Firmware: 13.2
iPhone Firmware (/sbin): 0-1
KSBA: 1.3.5-1
ldRun: 0.0.4
libcolorpicker: 1.6.4
libCSColorPicker: 1.0
libCSPreferences: 1.1.6
libidn2: 6.1.2-1
libimagepicker: 1.0.4
libpackageinfo: 1.1.0.1-1
libplist: 2.0.0-2
libSparkAppList: 1.0.3
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
NudePassScreen: 1.1.1
OpenSSH: 7.9p1-3
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
pincrush: 0.9.2-1
PreferenceLoader: 2.2.3-3
Profile Directory: 0-1
readline: 8.0-1
RealCC: 1.0.2
RocketBootstrap: 1.0.6
sed: 4.5-1
shell-cmds: 118-8
shuffle: 0.8.0b
SmallSiri: 1.2.2
Snappy: 1.2
SnowBoard: 1.2.44~Beta1
Substrate Safe Mode: 0.9.6003
system-cmds: 790.30.1-2
Take 1!: 1.01
Tape Archive: 1.30-2
TechSupport Framework: 1.5.0.1-1
Tweak Count 2: 1.0.1
UIKit Tools: 1.1.15-2
wget: 1.19.5-2
Xen HTML: 1.0.1~release
XZ Utils: 5.2.4-4
Zebra (BETA): 1.0~beta23-1

**Comment by nullpixel** [comment]
Could you rejailbreak into no substrate mode (hold volume up during the jailbreak) and let me know if the issue persists?

**Comment by Joyfilled** [comment]
> Could you rejailbreak into no substrate mode (hold volume up during the jailbreak) and let me know if the issue persists?

Oh well I rejailbroke and it’s working, so. Guess that’s good.
