### ISSUE TITLE
Checkra1n error

### ISSUE THREAD

**Issue by MemZNTV** [checkra1n/BugTracker#2022]
So I have this iPhone SE The new model and I get this error 
![image](https://user-images.githubusercontent.com/75344653/109892799-9c872180-7c58-11eb-96d5-02e28506a5a6.jpg)

Got any way to bypass it

**Comment by teelekkung** [comment]
This is not issue, This is not support model ,The support model are  A7-A11 with ios 12-14 . Pls close the issue(You has iphone se2 with A13 processor)
