### ISSUE TITLE
Starting p/w protection on iPhone X

### ISSUE THREAD

**Issue by nickksoares** [checkra1n/BugTracker#2026]
1. What iDevice are you using? iPhone x
2. On what version of iOS is it? 14.2
3. What version of checkra1n are you using? 0.12.2
4. What is your host system (Ubuntu 20.04 ,2 LTS)?
5. How are you connecting to the device (Apple cable)

**What are the steps to reproduce the issue?**
1. Get Jailbreaked
2. Try to setup a 4digit passcode
...

**What do you expect, and what is happening instead?**
Expect to be able to use a 4 digit passcode, however the phone reboots and I loose my jailbreak status.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Did not try yet because I am able to jailbreak again when this happens.

**Any other info, error logs, screenshots, ...?**

**Comment by RyzenRoll** [comment]
Bump. This is happening with my iPhone 8 (iOS 14.4.1) ;(

**Comment by salocor** [comment]
This is the way it works as of now on A11 devices (iPhone 8, 8 Plus, X).  
From Notes on [checkra.in](https://checkra.in/):

> A11 devices on iOS 14.0 and above require removing the passcode and enabling “Skip A11 BPR check” in the options. This is not recommended, but it’s there.

**Comment by Siguza** [comment]
This is not currently planned unless a new SEP bug comes our way.
