### ISSUE TITLE
Chinese Model Phones: Internet Connection Error

### ISSUE THREAD

**Issue by e4b338e1b6acfe0fa68f06dc71ea4c89** [checkra1n/BugTracker#203]
Chinese model of iPhones have a `com.apple.networkextension` plist that prevents unauthorized apps from accessing the internet. It **was** possible to delete this (I am using IOS12's unc0ver as an example here) using:

- Deleting the file via SSH

- installing filza escaped and deleting it from there

- Installing ConditionalWifi3 via SSH and enabling the app's wifi capability

It is not possible to do any of these methods to my knowledge. Would there be any way to acomplish this right now?

![image0](https://user-images.githubusercontent.com/34167604/68614372-ab245500-04b8-11ea-9851-a82ca063cf07.png)

**Comment by woachk** [comment]
This is issue #3 .

Closing as a duplicate.
