### ISSUE TITLE
Detect Linux phone and create menu for the small screen

### ISSUE THREAD

**Issue by jclsn** [checkra1n/BugTracker#2031]
I think it would be great if checkra1n worked on the Pinephone and Librem 5. Then you could jailbreak people's iPhones with another phone. Technically it installs and runs on the Pinephone, but then complains that it does not fulfill the minimum screen size. Can you make a smaller menu and detect the hardware?

**Comment by demhademha** [comment]
Perhaps a temporary solution is just to do `sudo checkra1n -c` from the terminal - this would   require the other device to be  manually placed in **dfu mode**

**Comment by jclsn** [comment]
Nevermind. The iPhone doesn't seem to recognize the phone as a PC.
