### ISSUE TITLE
checkra1n crashes because tries to write to an invalid address (0x18)

### ISSUE THREAD

**Issue by cutesmilee** [checkra1n/BugTracker#2036]
I'm using an iPhone 6 on 12.5.1 with checkra1n 0.12.1 on macOS Big Sur 11.2.3 (hackintosh) with a USB A - Lightning MFi cable.
checkra1n just crashes when i open it (even if there aren't connected device), seems like it's trying to write the content of RDX register to 0x18 (at least that's what i understood with a research, my x86 assembly knowleadge are near 0). 
![lldb screenshot](https://user-images.githubusercontent.com/41830087/111697238-9b97e780-8835-11eb-803b-6c4096717fc4.png)

**Comment by cutesmilee** [comment]
i noticed that i was actually using 0.12.1, 0.12.2 have the same error, but it's trying to copy RAX's content to itself.
![screenshot](https://user-images.githubusercontent.com/41830087/111698047-a4d58400-8836-11eb-8094-fcf33c8ba91c.png)

**Comment by cutesmilee** [comment]
also printing registers confirms that rax contains 0x18, maybe a compiler bug?
![screenshot](https://user-images.githubusercontent.com/41830087/111698294-f2ea8780-8836-11eb-8529-973036971d4c.png)

**Comment by Siguza** [comment]
Fixed in 0.12.3.
