### ISSUE TITLE
iPad mini 4 14.4.2 error code -20 stuck on checkra1n boot checkra1n 0.12.0

### ISSUE THREAD

**Issue by thedigi321** [checkra1n/BugTracker#2048]
**Tell us about your setup:**
1. What iDevice are you using? iPad mini 4
2. On what version of iOS is it? 14.4.2
3. What version of checkra1n are you using? 0.12.0
4. What is your host system (OS version? Hackintosh? VM? etc.)? Hackintosh Mojave
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?USB-a to lightning 3rd party

**What are the steps to reproduce the issue?**
1. run checkra1n as normal
2. get to booting 
3. encounter error code -20
...

**What do you expect, and what is happening instead?**
execting it to boot instead receive error code -20 stuck on checkra1n booting screen

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
yes

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**
![Screen Shot 2021-04-08 at 10 39 37 PM](https://user-images.githubusercontent.com/7421129/114133748-62deb180-98bb-11eb-9efb-36b2d623a2cb.png)

**Comment by Siguza** [comment]
Use a newer version of checkra1n.
