### ISSUE TITLE
iPad Pro 10.5 not charging

### ISSUE THREAD

**Issue by dxdeity** [checkra1n/BugTracker#205]
**What device + iOS version are you on?**
iPad Pro 10.5 Inch iOS 13.2.2

**What checkra1n version are you using?**
0.9.1 BETA
**What are the steps to reproduce the issue?**
1. Jailbreak the device
2. Plug the device in to a charger (I’m using 29W Apple quick charger and the cable is the official Apple 2 Meter lightning to USBC
3. Watch the battery fall in percent

**Comment by charlie-niekirk** [comment]
I can confirm, I have the same issue on the same device.  It works if you plug into a PC/Mac and get the ‘not charging’ thing and wait 10000 years for the battery to charge but not ideal.

**Comment by nullpixel** [comment]
This issue was fixed in 0.9.6.
