### ISSUE TITLE
Checkra1n not detecting DFU

### ISSUE THREAD

**Issue by sanitizethosehams** [checkra1n/BugTracker#2054]
**Tell us about your setup:**
1. What iDevice are you using?
2. iPad 7th gen wifi
2. On what version of iOS is it?
3. 14.2
3. What version of checkra1n are you using?
4. beta 0.12.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. Ubuntu 20.10
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
6. Official USB-A

**What are the steps to reproduce the issue?**
1. Start the jailbreak process
2. Enter dfu mode at prompt
3. Wait
...

**What do you expect, and what is happening instead?**
I Expected a Sucess DFU prompt
IPad is in DFU, Checkrain is just waiting
Replugging usb will lead to a USB Error -77

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
Sometimes DFU Succeeds but still led to a -77 error
Checkra1n used to work on the same version

**Comment by tuguldur** [comment]
1. Enter DFU mode 
2. Open checkra1n `sudo checkra1n -c`
3. Connect the device

enjoy
