### ISSUE TITLE
iPhone X Touch Unresponsive on Hello Screen

### ISSUE THREAD

**Issue by tuguldur** [checkra1n/BugTracker#2057]
**Setup:**
1. iPhone X (iPhone10,6)
2. iOS 14.4.2 (18D70)
3. checkra1n 0.12.2 beta
4. Ubuntu 18.04
5. USB-A

**Steps**
1. Open checkra1n in cli mode `sudo checkra1n -c`
2. Enter device dfu mode
3. Connect
...

**Comment by fullonrager** [comment]
Set up the device first before jailbreaking.

**Comment by tuguldur** [comment]
Using `checkra1n 0.12.1 beta` solved the Error
