### ISSUE TITLE
Problem with some apps

### ISSUE THREAD

**Issue by Lomer-er** [checkra1n/BugTracker#2059]
I deleted the jailbreak, but some applications still say that the jailbreak is installed on my device. How can I delete the jailbreak permanently or delete its files manually?

**Comment by Siguza** [comment]
```
rm -rf /var/lib/*
```

**Comment by Lomer-er** [comment]
> ```
> 
> rm -rf /var/lib/*
> 
> ```

![image](https://user-images.githubusercontent.com/75914558/115792319-c0eab900-a3d2-11eb-9b92-31d869e2ceb8.png)
That is what I found in var/lib

Delete all this ?

**Comment by Siguza** [comment]
Yes, that should do the trick.
