### ISSUE TITLE
Reboot remove cydia

### ISSUE THREAD

**Issue by HappyLand206** [checkra1n/BugTracker#206]
If i reboot my device than my device unjailbreak it.

**Comment by termz64** [comment]
You're a fucking idiot. This is a semi-tethered jailbreak. People like you shouldn't be able to jailbreak. Stop wasting developers time.

**Comment by woachk** [comment]
@natewarter Please use nicer language.

@HappyLand206 When you don't power on through the checkra1n app on your Mac, your phone will boot to stock iOS.

I'll close this issue.
