### ISSUE TITLE
After latest Catalina Security Update Checkra1n crashes and will not jailbreak phone

### ISSUE THREAD

**Issue by galaxy-nomad** [checkra1n/BugTracker#2063]
**Tell us about your setup:**
1. What iDevice are you using? iPhone SE (1st Gen) 
2. On what version of iOS is it? iOS 14.1
3. What version of checkra1n are you using? Latest 0.12.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Hackintosh (Was able to Jailbreak 4 other iPhone SE with this setup) This new phone is the first that I've ever had an issue with.
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Genuine Apple USB-A to lightning

**What are the steps to reproduce the issue?**
1. Put phone in DFU with Checkra1n
2. Follow steps ending with Holding down Home button 
3. Process will not complete and Checkra1n crashes and phone goes to black screen and must be hard reset to get system booted again.
...

**What do you expect, and what is happening instead?**
Jailbreak complete expected but instead Checkra1n closes/crashes and phone is left on black screen.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

Yes same behavior in safe mode

**Any other info, error logs, screenshots, ...?**

**Comment by galaxy-nomad** [comment]
UPDATE: I can confirm this is due to the latest Security update in Catalina or perhaps the Safari update if that could have any effect. I booted from a backup System SSD that was created before the latest Catalina Safari and Security updates and Checkra1n worked flawlessly. So it looks like Apple has blocked Checkra1n on the macOS system side or something like this?

**Comment by heyhello1** [comment]
oh no!!! I don't have a system backup :( I have the same issue, and started just later the last update

**Comment by galaxy-nomad** [comment]
> oh no!!! I don't have a system backup :( I have the same issue, and started just later the last update

If you're desperate and have a Catalina installer you can do a reinstall and I think that will downgrade your system to a state before the security update. I haven't tried it with Catalina but did it numerous times with Mojave for my own reasons. Basically just re-install an earlier version of Catalina without erasing your drive. In theory it will only replace system files and leave all user files and installed apps intact. Then just ignore/don't install any updates until Checkra1n is updated.😁

**Comment by heyhello1** [comment]
Thank you! yes! I'll try it right now :)

**Comment by buiniyslavik** [comment]
Same problem. Latest Catalina security update, MBP mid '12. CLI version just segfaults on launch.

**Comment by galaxy-nomad** [comment]
Latest update beta 0.12.3 fixed it!😄
