### ISSUE TITLE
GUI/TUI freezes with 14.5 if device is locked

### ISSUE THREAD

**Issue by chinchenghanji** [checkra1n/BugTracker#2064]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 6s Plus 
2. On what version of iOS is it?
14.5
3. What version of checkra1n are you using? Latest
4. What is your host system (OS version? Hackintosh? VM? etc.)? 
Ubuntu 20.04 on a usb 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? 
USB A official cables

**What are the steps to reproduce the issue?**
1. Plug the iPhone on iOS 14.5 update
2. Click next on put on recovery mode
3. And it stuck there and I can’t into recovery mode
...

**What do you expect, and what is happening instead?**
Going into recovery 

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**
![image](https://user-images.githubusercontent.com/78309912/116576576-f8e08780-a90f-11eb-84ee-38bad5de3d1b.jpg)

**Comment by chinchenghanji** [comment]
It worked with 14.4.1 but on 14.5 nop

**Comment by chinchenghanji** [comment]
Update: got manually into recovery but kernel crash after some seconds

**Comment by teelekkung** [comment]
checkra1n 0.12.3 come out with the support of iOS 14.5 please close issue

**Comment by Siguza** [comment]
This issue should go away if you unlock your device.  
But yeah, we should fix this... @nikias? 😇

**Comment by Siguza** [comment]
I'd actually like to keep this issue open until we ship a fix.

**Comment by chinchenghanji** [comment]
I din’t see the 0.12.3 release
So I used 0.12.2 
Now I used 0.12.3 and it works 
But Touch ID no longer works even after reboot
