### ISSUE TITLE
iPhone SE (2020) (iOS 14.5) is not supported.

### ISSUE THREAD

**Issue by pulpyboy0130** [checkra1n/BugTracker#2069]
**Tell us about your setup:**
1. What iDevice are you using?
  iPhone se 2nd gen
2. On what version of iOS is it?
  ios 14.5
3. What version of checkra1n are you using?
  0.12.3
4. What is your host system (OS version? Hackintosh? VM? etc.)?
  Ubuntu 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
  USB-A
**What are the steps to reproduce the issue?**
1. Sorry, iPhone SE (2020) (iOS 14.5) is not supported.
2. 
3.
...

**What do you expect, and what is happening instead?**

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
A13 is not vulnerable.
