### ISSUE TITLE
Typos on checkra.in

### ISSUE THREAD

**Issue by justtryingthingsout** [checkra1n/BugTracker#2072]
In changelogs for 0.9.8.1 - 0.10.2 
> The Apple TV 4K will produce a -20 error, even on a successful jailbreak Other known issues are available on our issue tracker.

There should probably be a newline in the middle of 'jailbreak' and 'Other' seeing other versions
Also, there are 2 'Known issues' sections in the same changelogs which should probably be merged

In changelogs for 0.11.0 - 0.12.3
> Linux GUI build when using CLI mode doesn’t support auto assertion of DFU mode on advanced Apple TV 4k breakout boards.

Usage of '4k' and '4K' are inconsistent, should probably be 4K

**Comment by Siguza** [comment]
Should all be fixed now. :)
