### ISSUE TITLE
Checkra1n Linux does not work on iOS 14.5 on iPhone 6S

### ISSUE THREAD

**Issue by Giantvince1** [checkra1n/BugTracker#2075]
I had updated my iPhone 6S to iOS 14.5, and proceeded to attempt to jailbreak it to no success. It would successfully inject the payload in DFU mode, but the kernel would panic similar to how A10(X) devices started doing so with iOS 14.0. I'm not 100% sure if this is because they updated the SEP in a similar fashion on A9(X) devices with iOS 14.5, but using iOS 14.4.2 I was successfully able to jailbreak my iPhone. Luckily that version is still signed by Apple as of today, April 30, 2021, otherwise I'd be out of luck. The jailbreak worked on 14.4.2 without any issues whatsoever minus the whole inability to automatically go into standard recovery mode bit, but that's a known issue with iOS 14 in general.

**Comment by mystrain** [comment]
i have an iPad pro 1st gen which has the A9x and yes its not working for me either.

getting error 20 on checka1n

**Comment by Siguza** [comment]
If the kernel panics, then post a panic log.  
I can jailbreak my iPhone SE (s8003) on 14.5 just fine.

**Comment by mystrain** [comment]
> If the kernel panics, then post a panic log.
> I can jailbreak my iPhone SE (s8003) on 14.5 just fine.


Hi Siguza

the below images show the errors im getting both on the ipad side and on checkra1n.

i have restored , used with safe mode and and without safe mode, still same issue.

![IMG_1502](https://user-images.githubusercontent.com/83470183/116795054-13f6f700-aaca-11eb-844a-2c3c9f919a0b.jpg)

![IMG_1501](https://user-images.githubusercontent.com/83470183/116795051-093c6200-aaca-11eb-90aa-9436feb41f89.jpg)

**Comment by Siguza** [comment]
@mystrain I'm not sure this is the same bug that Giantvince1 is encountering.

**Comment by DrJapan** [comment]
I'm also experiencing this issue with iOS 14.5, or 14.4.2 with an Intel MacBook Pro on macOS 11.3. I've tried using a USB-C to USB-A adapter and I've also tried a hub to no avail. Are either Homebrew or usbmuxd a requirement for Checkra1n? Or both?

**Comment by Siguza** [comment]
On macOS there are no external dependencies. All you need is the checkra1n app.

**Comment by dmatora** [comment]
Same issue iPad Pro 12.9 1st gen. iOS 14.4.1, iOS 14.5, macOS 11.3 - getting `Error code: -20`
Previous release was working fine before I tried 0.12.3, but now crashes with `Segmentation fault: 11`

**Comment by mystrain** [comment]
> Same issue iPad Pro 12.9 1st gen. iOS 14.4.1, iOS 14.5, macOS 11.3 - getting `Error code: -20`
> Previous release was working fine before I tried 0.12.3, but now crashes with `Segmentation fault: 11`

Hi dmatora,

I think you may be facing a similar issue mentioned here:

**A9X / iOS 14.5: Detected corrupted kerninfo #2074**

**Comment by Giantvince1** [comment]
Hello, I'm sorry for the long response time. I will be able to reproduce the bug for you tomorrow, as I have to download the IPSWs for both iOS 14.5 and 14.4.2 so that I can redowngrade once I get a photo of the bug, and on top of that, I have to use Linux on an old AMD board because Ryzen has a USB issue that prevents it from working properly, and I do not have a Mac.

**Comment by dmatora** [comment]
@mystrain thanks, you're right

**Comment by Giantvince1** [comment]
@Siguza I have tried again with checkra1n 12.3 on my old board and iOS 14.5 and I'm happy to report that this release fixed my issue. I discovered this as I was wanting to collect the output from my connected camera to post here for you to look at. Version 12.2 was the one I initially used as it was the latest at that moment.

**Comment by mystrain** [comment]
> @Siguza I have tried again with checkra1n 12.3 on my old board and iOS 14.5 and I'm happy to report that this release fixed my issue. I discovered this as I was wanting to collect the output from my connected camera to post here for you to look at. Version 12.2 was the one I initially used as it was the latest at that moment.

That’s great giantvince1 but it doesn’t work for me on 12.3 on iOS 14.5. 
may I ask what device your using?
I’ve tried everything and still no luck I’m really hoping Siguza gets back.
