### ISSUE TITLE
Battery settings not loading 

### ISSUE THREAD

**Issue by check8ed0ut** [checkra1n/BugTracker#208]
**What device + iOS version are you on?**
i phone x on OS 13.2.2

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1.just open battery center inside settings app it just has loading wheel never loads!
2.Works fine in non jailbroken state!!!
3.aside from that everything works damn near perfect THANK YOU ALL!!!
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by JensdeVlaming** [comment]
Did you installed any tweaks? For me it's working fine..

**Comment by joeff3** [comment]
Same issue here, iPhone X, 13.2.2

**Comment by check8ed0ut** [comment]
Yes i have
  
snowboard   
  
Perfect time xs   
  
Pull to respring   
  
Color my sb   
  
Unicode faces   
  
Jellyfish
  
Thats it so far idk which one it is i will try uninstalling each till i figure out thanks for the fast response and thanks for this awesome jailbreak!!!!!😊
  

  

  
  

  
  
>

**Comment by JensdeVlaming** [comment]
Can you try Restore System in the Checkra1n app? Let me know if it works?! If the issue is fixed with that process then it's up to the tweaks. (My cydia app crashed by uninstalling tweaks, idk why, but I fixed it. So maybe you can better try it with the checkra1n restore option)

**Comment by check8ed0ut** [comment]
Ok i will try this evening thank you !!!
  

  
  

  
  
>

**Comment by check8ed0ut** [comment]
I did system restore no tweaks it works but every orher time i go in there it wont load thanks for responding 👍
  

  
  

  
  
>

**Comment by check8ed0ut** [comment]
Sooo it seems like if i close settings app lockphone then reopen and back into battery settings it loads but only that way if i back out and dont go rhru those steps it just spins   
  

  
  

  
  
>

**Comment by JensdeVlaming** [comment]
> I did system restore no tweaks it works but every orher time i go in there it wont load thanks for responding 👍
> […](#)

So battery in settings works of you’ve done restore system and then Jailbreak via checkra1n on computer?

**Comment by check8ed0ut** [comment]
Yes it’s definitely something im installing cause its not working at all again now   
  

  
  

  
  
>

**Comment by vcarus** [comment]
When dylib inject to powerlogHelperd, powerlogHelperd crashes and reload. So battery settings can't load.
Many tweaks have this issue.

My temporary workaround is unload the daemon to prevent high CPU usage by powerlogHelperd.
`launchctl unload -w /System/Library/LaunchDaemons/com.apple.powerlogHelperd.plist`

Maybe there's a way to block tweak injection to powerlogHelperd?

**Comment by kratos9394** [comment]
when i closed enough tweaks,battery setting work

**Comment by Shadowedstalker** [comment]
I too have/had this issue.

Solution (if you have SpringPlus 11 installed): install iCleanerPro http://ib-soft.net/cydia/
lower Left side hit + open Cydia Substrate Addons
scroll down turn off SpringPlus 11, Hit apply. Hit yes when it asks about respringing.

Check your battery info.

You can reverse the processor and keep SpringPlus and just do the process over again to check or uninstall SpringPlus.

**Comment by kratos9394** [comment]
0.9.3.2，battery setting still not work
my tweaks installed[https://thumbsnap.com/f/0mrbEbik](url)
[https://thumbsnap.com/f/NGqFxFQL](url)

**Comment by Shadowedstalker** [comment]
@kratos9394  #301

**Comment by nullpixel** [comment]
these issues are caused by third party tweaks
