### ISSUE TITLE
iOS 14.5

### ISSUE THREAD

**Issue by abdoargr** [checkra1n/BugTracker#2080]
i use iPad 5 génération and iOS 14.5 
with la st version of chekra1n the phone doesnt want To jailbreak with  host system OSversion AND USB A 
CAN SOMEONE HELP PLEASE

**Comment by salocor** [comment]
Can you give us some more information?  What error code do you get when you try to jailbreak?

**Comment by Siguza** [comment]
Open a new ticket and fill out the template.
