### ISSUE TITLE
Why does it say iPhone se is not supported also the start button is greyed out please help

### ISSUE THREAD

**Issue by dantejolson** [checkra1n/BugTracker#2089]
**Tell us about your setup:**
1. What iDevice are you using? iPhone se 
2. On what version of iOS is it? 14.5.1
3. What version of checkra1n are you using? Latest one
4. What is your host system (OS version? Hackintosh? VM? etc.)? Idk
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? A regular apple charger 

**What are the steps to reproduce the issue?**
1. Plug in iPhone
2. Go to options
3.allow untested versions

still doesn’t work
...

**What do you expect, and what is happening instead?**
I expect it to SHOW THE START BUTTON not it being greyed out and I don’t have the option to press it

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

Yes
**Any other info, error logs, screenshots, ...?**
No I didn’t ss anything

**Comment by dantejolson** [comment]
Also here are some screen shots
![Uploading DBD8AE7F-85AE-4CBC-BFEC-DC6561C34C87.jpeg…]()

**Comment by dantejolson** [comment]
![1896A658-4428-463D-8B53-FCE15E89F45A](https://user-images.githubusercontent.com/83738054/117237155-2a10fa00-addf-11eb-8945-d3007d59adb8.jpeg)

**Comment by dantejolson** [comment]
![Uploading 30162D1C-CD0D-4109-9ACE-5385D30D8281.jpeg…]()

**Comment by Siguza** [comment]
A13 is not vulnerable.
