### ISSUE TITLE
YouTube and Google Maps crashing 

### ISSUE THREAD

**Issue by JKakaofanatiker** [checkra1n/BugTracker#209]
**What device + iOS version are you on?**

13.2
**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. First Jailbreak
2. Installation of some Tweaks
3. Opened YouTube and Google Maps
...

**What do you expect, and what is happening instead?**
I expected it to work normally but it hang and crashed

**Any other info, error logs, screenshots, ...?**

**Comment by JKakaofanatiker** [comment]
Edit: YT only crashes when I search something

**Comment by kpwn** [comment]
"Installation of some Tweaks" seems like the culprit here. Does the issue persist if you uninstall the tweaks?

**Comment by JKakaofanatiker** [comment]
Working after many resprings
