### ISSUE TITLE
iPhone X 14.5 - NO PASSCODE & FACEID

### ISSUE THREAD

**Issue by DadaniKurt** [checkra1n/BugTracker#2093]
Hi there! After jailbreaking my iPhone X, does my device have to remain without passcode and FaceID to continue using Cydia? Cause after installing Cydia and I try to turn on PC and FaceID, my phone reboots and removes Checkra1n. Is this a bug or is this how 14.5 Checkra1n jailbreak is meant to work at the moment?

**Comment by Siguza** [comment]
This is unfortunately how things are.  
To change that, we would need another SEP bug.

**Comment by DadaniKurt** [comment]
Thank you for the quick reply. I have been searching online for days for an answer but could not find one. I'll stay in stock iOS for now until PC and FaceID can be turned on again. Appreciate your help!
