### ISSUE TITLE
Error code -20 on Apple iPad Pro 9.7 (2016) previously working now stopped after upgrade to 14.5

### ISSUE THREAD

**Issue by sreeniHari** [checkra1n/BugTracker#2097]
Stuck with Error Code -20 

**Tell us about your setup:**
1. What iDevice are you using? ipad pro 9.7 2016
2. On what version of iOS is it? 14.5 
3. What version of checkra1n are you using? 0.12.4
4. What is your host system (OS version? Hackintosh? VM? etc.)? Mac running on catalina
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB apple

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**
boot successfully 

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
no

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**
<img width="473" alt="Screenshot 2021-05-12 at 10 28 11 PM" src="https://user-images.githubusercontent.com/20319848/117994316-074c8b80-b373-11eb-86b6-74109cb20df8.png">

<img width="471" alt="Screenshot 2021-05-12 at 10 26 52 PM" src="https://user-images.githubusercontent.com/20319848/117994372-116e8a00-b373-11eb-8bda-259927e01f62.png">

<img width="474" alt="Screenshot 2021-05-12 at 10 32 47 PM" src="https://user-images.githubusercontent.com/20319848/117994463-264b1d80-b373-11eb-81fb-25dc8065ab87.png">

**Comment by sreeniHari** [comment]
Same problem on 0.12.3 as well. Tried several times 20 times or more in different modes like opening checkra1n with already in recovery mode or manually triggering. And also all possible combinations like with safe mode and without etc.

**Comment by sreeniHari** [comment]
refer https://github.com/checkra1n/BugTracker/issues/2074# 

Below command works 
/Applications/checkra1n.app/Contents/MacOS/checkra1n -k ~/Downloads/Pongo/PongoConsolidated.bin

**Comment by JTSG01** [comment]
> referir [# 2074](https://github.com/checkra1n/BugTracker/issues/2074)
> 
> O comando abaixo funciona
> /Applications/checkra1n.app/Contents/MacOS/checkra1n -k ~ / Downloads / Pongo / PongoConsolidated.bin

Only works on the IpadOS 14.5 version, on 14.5.1 it doesn't work!

**Comment by UInt2048** [comment]
@JTSG01 Does it have anything to do with the fact that when you tried to translate it, you added spaces in the command?

**Comment by JTSG01** [comment]
> @ JTSG01 Isso tem a ver com o fato de que, ao tentar traduzir, você adicionou espaços no comando?

Were you able to work on IpadOS 14.5.1?

**Comment by UInt2048** [comment]
@JTSG01 I had already restored back to 14.5 before finding out that #2074 and the fix existed. I'm now on 14.3, so I can't test it.

**Comment by sreeniHari** [comment]
> > @ JTSG01 Isso tem a ver com o fato de que, ao tentar traduzir, você adicionou espaços no comando?
> 
> Were you able to work on IpadOS 14.5.1?

@JTSG01  wait for next release they will fix it for sure
