### ISSUE TITLE
Checkra1n error -20 on second boot

### ISSUE THREAD

**Issue by asislife20** [checkra1n/BugTracker#2098]
**Tell us about your setup:**
1. iPad 7,11
2. 14.5.1
3. 0.12.4
4. Mac OS  Big Sur
5. Standard Apple lightning cable. Tried both USB 2.0 and 3.0 ports

**What are the steps to reproduce the issue?**
1. Jailbreak with checkra1n succeeds
2. Install Cydia
3.Reboot and jailbreak gives error -20
5.Jailbreak safemode works.
...

**What do you expect, and what is happening instead?**
I expect it to jailbreak and load, but it freezes and gives error -20.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
Only when I specifically boot checkra1n with safemode toggle.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
No

**Any other info, error logs, screenshots, ...?**
At first I thought it might be due to a bad tweak, so I did a full restore of rootfs and of the iPad and tried without installing any tweaks or upgrading essentials, but the same thing happens.

**Comment by Siguza** [comment]
If it works in safe mode, then it's definitely a tweak issue though.
