### ISSUE TITLE
bootloop cercube

### ISSUE THREAD

**Issue by 0ch4rl1e0** [checkra1n/BugTracker#21]
**What device + iOS version are you on?**
iPhone 8 Plus 13.2

**What are the steps to reproduce the issue?**
1. Install Cercube from apt.alfhaily.me and get the bootloop.
2. Try to boot the iPhone and it won't boot on checkra1n
3. Device works in stock iOS
...

**What do you expect, and what is happening instead?**
i spect cercube to work but i can't becouse of the bootloop and now i have to restore to have a jb working again... do a restore rootfs in the program, it will be really useful. thanks for the jailbreak

**Any other info, error logs, screenshots, ...?**

**Comment by fordz0** [comment]
Pretty sure I did the same thing. Did you get a -20 error code?

**Comment by 0xkj** [comment]
Same thing and same problem. Usually this would be fixed by booting in safe mode but not sure if checkra1n has one or how to use it.

**Comment by 0ch4rl1e0** [comment]
yep, i get error -20 on checkra1n. I made a backup and restored my iPhone 8 to 13.2.2...

**Comment by TheBlueKingLP** [comment]
got the same problem, how to go into jailbroken mode again after this?

**Comment by nullpixel** [comment]
Hi there, this is not an issue with checkra1n.
