### ISSUE TITLE
Not loading or installing tweaks iOS 13.2.2

### ISSUE THREAD

**Issue by Yazxoi** [checkra1n/BugTracker#210]
**What device + iOS version are you on?**
iPhone10,6 iOS 13.2.2

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. Open Cydia
2. Install a tweak
3. notice that it doesn't work/load
...

**What do you expect, and what is happening instead?**
I expect it to run the tweak, Instead it doesn't do anything 
(Cydia marks it as installed though!)

**Any other info, error logs, screenshots, ...?**
No.. :(

**Comment by nullpixel** [comment]
this is due to a broken tweak and not checkra1n.
