### ISSUE TITLE
Ipad 1st gen A9X stuck on booting option even after release of 0.12.4 

### ISSUE THREAD

**Issue by AkSingh03** [checkra1n/BugTracker#2101]
**Tell us about your setup:**
1.i am using an ipad pro 1st gen with a9x
2. 14.5.1
3. 0.12.4
4. linux ubuntu
5. apple original usb

**What are the steps to reproduce the issue?**
1. try jailbreaking A9X again it gets stuck on booting
2. 
3.
...

**What do you expect, and what is happening instead?**
I hoped that the problem would be fixed as in the key notes of checkra1n 0.12.4 but i an unable to jailbreak ipad on A9x with the same issue as 0.12.3

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
NO

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
YES

**Any other info, error logs, screenshots, ...?**
![Screenshot from 2021-05-16 16-01-25](https://user-images.githubusercontent.com/51170427/118394107-483cec80-b660-11eb-85a7-d7bd8e0300ea.png)

**Comment by driversat** [comment]
same problem here:
1.i am using an ipad pro 1st gen with a9x
2. 14.5.1
3. checkrain 0.12.4
4. macos 11.3.1
5. apple original usb
6. On iPad screen: 
Found old-style rdsk!
Detected corrupted kerninfo!
Enabling USB
Done!
pongoOS>

**Comment by caracol1Satelite** [comment]
> **Cuéntenos acerca de su configuración:**
> 1. Estoy usando un ipad pro de 1.ª generación con a9x
> 2. 14.5.1
> 3. 0.12.4
> 4. linux ubuntu
> 5. apple original usb
> 
> **¿Cuáles son los pasos para reproducir el problema?**
> 
> 1. intente jailbreak A9X nuevamente, se atasca al arrancar
> 
> ...
> 
> **¿Qué esperas y qué está sucediendo en su lugar? **
> Esperaba que el problema se solucionara como en las notas clave de checkra1n 0.12.4 pero no puedo hacer jailbreak al ipad en A9x con el mismo problema que 0.12.3
> 
> **¿Viste una ventana emergente en el dispositivo que indica que ingresó en "Modo seguro" debido a un error? **
> NO
> 
> **¿El problema también ocurre si marca "Modo seguro" en las opciones de checkra1n? **
> SÍ
> 
> **¿Alguna otra información, registros de errores, capturas de pantalla, ...?**
> ![Captura de pantalla de 2021-05-16 16-01-25](https://user-images.githubusercontent.com/51170427/118394107-483cec80-b660-11eb-85a7-d7bd8e0300ea.png)

A MI ME PASA LO MISMO, TENGO UN IPAD AIR 2 Y CUANDO HAGO EL JAILBREAK SE ME QUEDA EL CHECKRA1N EN BOOTING Y EL IPAD EN LA MANZANA PERO NO SALEN LOS CÓDIGOS DEL CHECKRA1N ENCIMA DE LA MANZANA 

1. ipad air 2 (A1566)
2. Checkra1n 0.12.4 y 0.12.3 ( Haciendolo normalmente y probado con verboose boot, safe mode, en modo Cli y ninguna de ellas me ha funcionado.
3. Macbook Pro9,2 con Os Catalina 10.5.7
4. Usb original de apple y otros
5. En la pantalla del ipad solo sale la manzana y luego se reinicia en la manzana de nuevo y vuelve a salir la pantalla de bloqueo de activación.

**Comment by caracol1Satelite** [comment]
> > **Cuéntenos acerca de su configuración:**
> > 
> > 1. Estoy usando un ipad pro de 1.ª generación con a9x
> > 2. 14.5.1
> > 3. 0.12.4
> > 4. linux ubuntu
> > 5. usb original de manzana
> > 
> > **¿Cuáles son los pasos para reproducir el problema?**
> > 
> > 1. intente jailbreak A9X nuevamente, se atasca al arrancar
> > 
> > ...
> > ** ¿Qué esperas y qué está sucediendo en su lugar? ** 
> > Esperaba que el problema se solucionara como en las notas clave de checkra1n 0.12.4 pero no puedo hacer jailbreak al ipad en A9x con el mismo problema que 0.12.3
> > ** ¿Viste una ventana emergente en el dispositivo que indica que ingresó en "Modo seguro" debido a un error? ** 
> > NO
> > ** ¿El problema también ocurre si marca "Modo seguro" en las opciones de verificación? ** 
> > SÍ
> > **¿Alguna otra información, registros de errores, capturas de pantalla, ...?**
> > ![Captura de pantalla de 2021-05-16 16-01-25](https://user-images.githubusercontent.com/51170427/118394107-483cec80-b660-11eb-85a7-d7bd8e0300ea.png)
> 
> A MI ME PASA LO MISMO, TENGO UN IPAD AIR 2 Y CUANDO HAGO EL JAILBREAK SE ME QUEDA EL CHECKRA1N EN BOOTING Y EL IPAD EN LA MANZANA PERO NO SALEN LOS CÓDIGOS DEL CHECKRA1N ENCIMA DE LA MANZANA
> 
> 1. ipad aire 2 (A1566) con ios 14.5.1
> 2. Checkra1n 0.12.4 y 0.12.3 (Haciendolo normalmente y probado con verboose boot, safe mode, en modo Cli y ninguna de ellas me ha funcionado.
> 3. Macbook Pro9,2 con Os Catalina 10.5.7
> 4. Usb original de apple y otros
> 5. En la pantalla del ipad solo sale la manzana y luego se reinicia en la manzana de nuevo y vuelve a salir la pantalla de bloqueo de activación.

**Comment by hamza-1998-del** [comment]
Same issue here with iPad Pro A1674 2016 boot frozen...
My Configuration:
1. macOs 11.3.1 on MacBook Pro 12,1
2. iPadOS 14.5.1 on iPad Pro 9.7inch A1674 with Apple A9X (S8001)
3. Checkra1n Version 0.12.4
4. Checkra1n log------------Found Old-style rdsk!
                                                 Detected Corrupted kernelinfo!
                                                 Enabling USB
                                                 Done!
                                                 pongoOS>
5. Same Response with safe mode ticked or unticked....
![Screenshot 2021-05-20 at 16 36 50](https://user-images.githubusercontent.com/84508486/118972971-99afe900-b98a-11eb-9b66-7f494bb2842e.png)

**Comment by caracol1Satelite** [comment]
> Same issue here with iPad Pro A1674 2016 boot frozen...
> My Configuration:
> 
> 1. macOs 11.3.1 on MacBook Pro
> 2. iPadOS 14.5.1 on iPad Pro 9.7inch A1674 with Apple A9X (S8001)
> 3. Checkra1n Version 0.12.4
> 4. Checkra1n log------------Found Old-style rdsk!
>    Detected Corrupted kernelinfo!
>    Enabling USB
>    Done!
>    pongoOS>
>    ![Screenshot 2021-05-20 at 16 36 50](https://user-images.githubusercontent.com/84508486/118972971-99afe900-b98a-11eb-9b66-7f494bb2842e.png)

LO MISMO ME SALE A MI

**Comment by mashtyme** [comment]
i opened a trouble then i found this section... happens the same to me
Ipad pro 12.9 1st gen 
iOS 14.6
checkra1n 0.12.4
linux 
same lines as the guy above:
Found old-style rdsk!
Detected corrupted kerninfo!
Enabling USB
Done!
pongoOS>

**Comment by Siguza** [comment]
Duplicate of #2074.

**Comment by roeyleon** [comment]
Hi, same issue here.
Was anyone able to solve it?

**Comment by driversat** [comment]
https://github.com/checkra1n/BugTracker/issues/2145#issuecomment-891025327

**Comment by h-low-high** [comment]
habeis podido solventarlo?

**Comment by h-low-high** [comment]
> [#2145 (comment)](https://github.com/checkra1n/BugTracker/issues/2145#issuecomment-891025327)

 a mi eso no me funciona.

**Comment by driversat** [comment]
mira 
 https://www.reddit.com/r/checkra1n/comments/n2fmf5/comment/gxptdnc/

**Comment by h-low-high** [comment]
no me funciona, lo hago pero sale la pantalla de hell

> mira https://www.reddit.com/r/checkra1n/comments/n2fmf5/comment/gxptdnc/

no me funciona, lo hago pero sale la pantalla de hello...

**Comment by mashtyme** [comment]
this worked for me on ipad pro 1st gen ios 14.6: https://pastebin.com/raw/prXkLFth did it from kali linux hope it helps (make sure you're correctly in DFU mode, ipad should show black screen)

**Comment by h-low-high** [comment]
> this worked for me on ipad pro 1st gen ios 14.6: https://pastebin.com/raw/prXkLFth did it from kali linux hope it helps (make sure you're correctly in DFU mode, ipad should show black screen)

not work for me.... from mac m1.

**Comment by h-low-high** [comment]
im try using kali linux live cd and not work...
