### ISSUE TITLE
Error When Downloading SSH Tweaks in Checkra1n

### ISSUE THREAD

**Issue by thecolbster91** [checkra1n/BugTracker#2122]
**Tell us about your setup:**
1. What iDevice are you using?  iPhone 6s
2. On what version of iOS is it?   iOS14.6
3. What version of checkra1n are you using? 0.12.4
4. What is your host system (OS version? Hackintosh? VM? etc.)?  PC
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A

**What are the steps to reproduce the issue?**
1.  Downloaded Zebra in place of Sileo.
2. 
3.
...

**What do you expect, and what is happening instead?**
I want to add the tweak SSH Toggle and Port but I get an error.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**

What’s up? When I tried to download SSH toggle and port, it gives me an error, “Open SSH has issues that cannot be resolved in Zebra, and an apt-get update error in Sileo. I need this to export my sources to my email address. What could be the issue?

![CC844253-4393-447F-B080-E5C9D980067D](https://user-images.githubusercontent.com/35181281/120908694-ccb8d480-c63a-11eb-80c0-8b1bfd7c4930.png)

![31A8922D-D3E6-40C3-969A-5DA742455F1C](https://user-images.githubusercontent.com/35181281/120908695-cd516b00-c63a-11eb-83f9-91438a311c16.png)

**Comment by Siguza** [comment]
That's an issue with third-party software. not checkra1n.
