### ISSUE TITLE
checkra1n app crashes on macOS 12 Monterey

### ISSUE THREAD

**Issue by pnxl** [checkra1n/BugTracker#2126]
**Tell us about your setup:**
1. The device is an iPhone 5s
2. iOS version 12.5.3
3. Checkra1n app version beta 0.12.2
4. Running macOS 12 "Monterey" Developer Beta, Hackintosh
5. Connected directly to my USB port on the laptop

**What are the steps to reproduce the issue?**
1. Open checkra1n
2. Follow the steps on screen to recovery mode
3. App crashes

**What do you expect, and what is happening instead?**
for it to not crash lmao
instead it crashes

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Comment by teelekkung** [comment]
checkra1n 0.12.4 already fix that issue

for accuracy , It's fix on 0.12.3 and make it better in 0.12.4
