### ISSUE TITLE
Mount checkra1n0.12.4.dmg by user interface in MacOS Monterey will make kernel panic

### ISSUE THREAD

**Issue by teelekkung** [checkra1n/BugTracker#2127]
I have a problem about Bluetooth in macOS Monterey ,So I decide to do a clean installation but the issue still present. After report a problem to apple And reinstall app. when I double click a checkra1n beta 0.12.4.dmg from my drive . My Mac freeze and reboot into kernel panic . After some redownload and a lot of try I manage to confirm that it is happened only in user interface . The command ("hdiutil attach ~/Downloads/checkra1n\ beta\ 0.12.4.dmg") still work. 

I don't know if this happened with other Mac but I think it will 
My Mac is MacBook Air 2018 with 16g of ram and 250g storage

**Comment by Siguza** [comment]
A few people helped me look into this. Seems like on M1 it just errors out, whereas on x86_64 it panics on a division by zero.  
I filed a bug report with Apple (FB9191084), since only they can fix that part.  
I guess it remains to be seen whether or not we have to patch up our disk image builder, so I'll leave this ticket open for now and mark it as accepted.

**Comment by ghost** [comment]
@Siguza 

Just out of curiosity, are the latest checkra1n builds supposed to work on arm64 devices running on Darwin in general other than the M1? 

It’s certainly really cool to see it having been ported to the M1 but would that also point to the ability to potentially adding support for iOS devices w CCK (or third party equivalent) in general? Obviously with some hacky patches on the kernel cache you should be able to run M1 binaries on iOS (cc zhuowei et al) and theoretically one could just compile it for iOS to begin with if they have the source code. All that said tho, I’m not sure if the USB controller has been exposed in a way to facilitate a working checkra1n. Userspace libusb currently works flawlessly (working builds from elucubratus/odyssey) but I guess if one actually tries to do that some stupid launchd services will start to interfere. Totally wouldn’t mind sacrificing the default USB implementation to be able to connect to devices more natively tho without iOS with all of its dumb limitations.

On a related note, arm64 checkra1n builds for the Linux kernel running on Android kinda suffers from the same problem but usually things work out just fine when booting from custom recoveries (which conveniently solves the problem of the OS hijacking USB controllers). Kinda makes me wonder what’s the team’s stance on running checkra1n within iOS itself👀

Cheers!

**Comment by Siguza** [comment]
Are they supposed to work there? No.  
Would it be feasible to get them working? Probably.  
Is it a priority for us? Nope.

If anything, that'll have to be considered after the Windows version, after open sourcing and after iOS 15 support.

**Comment by ghost** [comment]
Ahh thank you so much for the reply!

Yeah would completely agree this shouldn’t be a priority -- doubt there’s going to be a lot of people actually leveraging this (unless they have the CCK or a jailbroken iPad Pro with Type-C dongle, which represent a small enough population) and realistically it’s probably not worth it to put in all that development effort just to prove a point. Well, appreciate the quick response and would definitely be looking forward to the historic moment when checkra1n is getting open sourced then! ;)

**Comment by teelekkung** [comment]
In beta 2 is still happen but not kernel panic ,instead 
<img width="372" alt="Screen Shot 2564-06-30 at 14 36 55" src="https://user-images.githubusercontent.com/47544781/123921059-d0791600-d9b0-11eb-9f81-21013e9b9a9e.png"> 
The disk you attached was not readable by this computer


as usual "hdiutil attach ~/Downloads/checkra1n\ beta\ 0.12.4.dmg" work fine

**Comment by teelekkung** [comment]
In beta 3 Apple finally fix . @Siguza if you wanna close this now it up to you . I will leave this open until RC of 12.0

**Comment by Siguza** [comment]
Alright, I'll consider it resolved.
