### ISSUE TITLE
Black Out

### ISSUE THREAD

**Issue by mado10** [checkra1n/BugTracker#2129]
It worked at first, but after the third transition to DFU mode, an error occurred and it blacked out.

OS ---
IPhone 8.1
IOS 14.4.1
Mac 10.14.6
GPU Intel Iris Plus Graphics 640
GPU Geforce GTX 1050Ti
Storage 1TB
CPU Intel Core i5 2.3GHz
Memory 8GB 2133 MHz DDR4

MORE ---
**_Q_**   It worked at first, but after the third transition to DFU mode, an error occurred and it blacked out.
**_A_**   No, all buttons are not responding.

**_Q_**   Is it possible to force a restart?
**_A_**   No, I tried all IPhone methods but couldn't

**_Q_**   Wouldn't it be cured if all Tweaks were turned off in safe mode?
**_A_**   No, it's as if the LCD on your device is off

**_Q_**   If you jailbreak again, you'll be cured, right? Are you stupid?
**_A_**   If you try to jailbreak again, the USB will not be recognized. Probably the power is off

**_Q_**   I understand! Let's charge!
**_A_**   I charged it all night, but it doesn't change.

**Comment by Scott1012** [comment]
Hello, I have the same problem as you on an iphone 8 did you manage to fix it? 

There is written this on checkra1n: 

Phone 8 (GSM) connected in DFU mode.
ECID: 0x1904120404483a
Please connect device in Normal/Recovery mode or run checkra1n in CLI mode

**Comment by Siguza** [comment]
It's hard for me to understand what's going on here, or if you two even have the same issue.

But if your device is in a weird state in DFU, `irecovery -f /dev/null` will reboot it.  
If it's stuck somewhere in iBoot, then I can only point at [the new reset sequence](https://support.apple.com/en-gb/guide/iphone/iph8903c3ee6/ios#ipha06f91990) for A11 and later. If performed correctly, that sequence will _always_ reboot your phone, no matter what.

**Comment by Scott1012** [comment]
hello, thanks for you reply, i have successful the phone was drained of its batteries and restarted
