### ISSUE TITLE
iPhone won’t enter DFU mode

### ISSUE THREAD

**Issue by OhMyTact** [checkra1n/BugTracker#2132]
**Tell us about your setup:**
1. IPhone 6s Plus
2. 14.4.2
3. Newest one
4. Mac OS 
5. A Mac book air iPhone charger

**What are the steps to reproduce the issue?**
1. Start the jailbreak
2. Next
3. Hold home button and side button until phone enter DFU mode 
...

**What do you expect, and what is happening instead?**
I expect it to go to DFU mode but instead it goes back and says phone didn’t enter DFU mode retry

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yea

**Any other info, error logs, screenshots, ...?**
No

**Comment by Siguza** [comment]
See #1, "USB-C cables".
