### ISSUE TITLE
Does it support iPhone X (Global) iOS 14.6?

### ISSUE THREAD

**Issue by gee1k** [checkra1n/BugTracker#2143]
Device: iPhone X (Global) 
iOS: iOS 14.6

Turned off Face ID and Passcode and Find Me

Error reported every time

![image](https://user-images.githubusercontent.com/12059800/124419893-ff1c3580-dd90-11eb-9583-83bd62e7997d.png)

![image](https://user-images.githubusercontent.com/12059800/124418154-69cb7200-dd8d-11eb-943c-3b7f51e02016.png)

**Comment by Siguza** [comment]
Please file a new ticket and fill out the template this time.
