### ISSUE TITLE
Freezes on Screen

### ISSUE THREAD

**Issue by iKasprModz** [checkra1n/BugTracker#215]
**What device + iOS version are you on?**
iPhone X 13.2
**What checkra1n version are you using?**
Beta 
**What are the steps to reproduce the issue?**
1.Open Checkra1n On Mac
2.Enter DFU Mode
3.Complete Jailbreak and frozen on screen never reboot 
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**
![FD30A330-D701-4493-887F-3B51340717B0](https://user-images.githubusercontent.com/57599650/68630537-a611d680-04b5-11ea-80cb-f133caf9ccc8.jpeg)

That’s where I get stuck but in my iPhone

**Comment by GuyInHiding** [comment]
Does it sit on the screen with the text

**Comment by halfbread10** [comment]
Happening to mine too. iPhone X 13.2.2. Reboots and then gets stuck on lock screen. Same thing happens in safe mode using 0.9.2. 0.9.1 worked fine.

Edit: The screen is unresponsive the volume and side buttons still work.

**Comment by nullpixel** [comment]
Reboot and rejailbreak whilst holding the volume up button. Does this resolve the issue?

**Comment by halfbread10** [comment]
No. It just boots into safe mode but screen is still unresponsive.

**Comment by nullpixel** [comment]
Could you verify how you are entering no substrate mode? It is very likely that a tweak is causing this

**Comment by halfbread10** [comment]
Im holding the volume up button when the text appears on the phone. It loads up to the lock screen which is the default one and not jellyfish. Screen is unresponsive after that. My last reboot was with version 0.9.1 which worked fine and I haven't installed anything new since then.

**Comment by FraserEmbrey** [comment]
Having a similar issue. I installed the Latchkey tweak and that seemed to break my device. I had to restart it. Tried to normally jailbreak but my iPhone got stuck in a boot loop. When jailbreaking holding volume up, the screen is completely unresponsive although buttons all work as does raise to wake. Not sure how to fix aside from resetting and reinstalling iOS

(Using 0.9.2)

**Comment by ghost** [comment]
> Having a similar issue. I installed the Latchkey tweak and that seemed to break my device. I had to restart it. Tried to normally jailbreak but my iPhone got stuck in a boot loop. When jailbreaking holding volume up, the screen is completely unresponsive although buttons all work as does raise to wake. Not sure how to fix aside from resetting and reinstalling iOS
> 
> (Using 0.9.2)

What IOS version are you on? I am having a problem similar to this one on IOS 13.2.

**Comment by nullpixel** [comment]
We’ll look into it, thanks.

**Comment by denniskns** [comment]
have this issue too, also iphone x, touchscreen doesnt work.

**Comment by FraserEmbrey** [comment]
> > Having a similar issue. I installed the Latchkey tweak and that seemed to break my device. I had to restart it. Tried to normally jailbreak but my iPhone got stuck in a boot loop. When jailbreaking holding volume up, the screen is completely unresponsive although buttons all work as does raise to wake. Not sure how to fix aside from resetting and reinstalling iOS
> > (Using 0.9.2)
> 
> What IOS version are you on? I am having a problem similar to this one on IOS 13.2.

iOS 13.2.2, macOS 10.15.1

**Comment by halfbread10** [comment]
In the meantime Id recommend everyone to revert back to 0.9.1 which works fine for me.

**Comment by FraserEmbrey** [comment]
> In the meantime Id recommend everyone to revert back to 0.9.1 which works fine for me.

I tried in 0.9.1 and it left me in exactly the same state

**Comment by HeyItsMicro** [comment]
I am having this issue as well, iPhone X 13.2.2 using checkra1n 0.9.2. I jalbroke with checkra1n and when it booted i was unable to interact with the screen. The device wasn't frozen, just unresponsive to touches. I thought a tweak was causing the issue so I jailbroke with checkra1n again but this time holding the volume up button on boot into no-substrate mode. Once booted, I noticed the issue persisted, so I believe this is an issue with the jailbreak.

**Comment by halfbread10** [comment]
> > In the meantime Id recommend everyone to revert back to 0.9.1 which works fine for me.
> 
> I tried in 0.9.1 and it left me in exactly the same state

Must be a tweak then. 0.9.1 works perfectly fine for me

**Comment by GuyInHiding** [comment]
When do I start to hold down the  button to boot into no-substrate mode?
I'm trying to rejailbreak after a tweak required me to restart my device

**Comment by halfbread10** [comment]
> When do I start to hold down the button to boot into no-substrate mode?
> I'm trying to rejailbreak after a tweak required me to restart my device

When the text appears on your device.

**Comment by GuyInHiding** [comment]
> > When do I start to hold down the button to boot into no-substrate mode?
> > I'm trying to rejailbreak after a tweak required me to restart my device
> 
> When the text appears on your device.

When I do that Cydia doesn't open and the checkra1n app is not on the device

**Comment by nullpixel** [comment]
What tweaks do you all have installed?

**Comment by GuyInHiding** [comment]
> What tweaks do you all have installed?

I attempted to install Xen HTML and that's when it broke
I also cannot remove Cydia

**Comment by FraserEmbrey** [comment]
The issue started when I installed latchkey as mentioned. I also had snowboard, ShortLook, speculum, Checkra1n boot logo and InkCC installed.
iPhone X on iOS 13.2.2 is one of: in no substrate with no touch, boot looping, or not jailbroken.
I have tried with 0.9.1, 0.9.2 and my Mac is running 10.15.1

**Comment by iKasprModz** [comment]
> What tweaks do you all have installed?

I installed the tweak SimplePasscodeButtons and when I respiring it never stop it froze on respring and I decided to DFU mode that’s when I got the problem

**Comment by furby8704** [comment]
iphone x 13.2.2 unresponsive touchscreen at 1st run. rebooted to normal state and ran jb again. 2nd time all is fine now.

**Comment by FraserEmbrey** [comment]
I kept trying for a while perhaps 3-5 times. I have just come back and tried again. Same cable etc. it worked fine this time and now all is well again.

**Comment by yur1xpp** [comment]
Same issue, Face ID can’t be activated and screen freezes upon boot, only side button is responsive. iPhone X, 13.2.2.

**Comment by fadedos** [comment]
im having the same exact problem. I'll enter DFU mode and it will just say "booting" and stay on it. the checkrain app on my computer is saying that the jailbreak is done when the bar fills but the phone wont boot for minutes and when it does, my phone isn't jailbroken. I'm using an iphone X with ios 13.2.2 and checkrain 0.9.2, although I had the same problem using 0.9.1

**Comment by liudayu** [comment]
Same problem, screen was not responsible after boot success, however after couple of tries, it just started working again somehow

**Comment by napoleonjames** [comment]
Same Problem,Froze on the lockscreen and touch does not response.Only work side button.0.9.2

**Comment by shehzaad10** [comment]
I had the same issue, it resolved for me by not putting the iPhone in DFU mode but allow the checkra1n app to put it into recovery and following the instructions to enter the iPhone into DFU mode.

iPhone now has everything running smoothly without any freezes and also faceID also works.

**Comment by boog2dan** [comment]
same issue, touch screen not responding at lockscreen after a successful jailbreak boot.
entered DFU from regular reset from iOs (I could not enter following chackra1n tutorial)

0.9.2 version on macbook pro 2018

**Comment by azzeddine94** [comment]
have this issue too, also iphone x, touchscreen doesnt work.

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.
