### ISSUE TITLE
Menu loads but nothing clicks after bypassing icloud lock screen on iPhone 7 iOS v14.6

### ISSUE THREAD

**Issue by l0x539** [checkra1n/BugTracker#2152]
**arch linux/ iproxy ssh login:**
1. What iDevice are you using?
IPhone 7
2. On what version of iOS is it?
14.6
3. What version of checkra1n are you using?
latest beta 0.12.4
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Arch Linux
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB
**What are the steps to reproduce the issue?**
1.  run checkrain on arch linux after pluging the device
2.  check first option on options which allow other versions than required.
3. after installing, use iproxy to run usb through ssh (guide: https://myicloud.info/ssh-connection-to-localhost-with-checkra1n-read-write/)
5. ssh to the device.
6. run the required commands from that tutorial or main checkra1n tutorial.
7. restarting the phone will unlock it but the home button will be disabled and nothing will click.
...

**What do you expect, and what is happening instead?**
i expected the icons and home button to click, but it does nothing.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
i haven't check that yet, i will and update the issu

**Any other info, error logs, screenshots, ...?**
just nothing clicks after the lock screen goes.

**Comment by Siguza** [comment]
checkra1n has nothing to do with iCloud Lock. If you have SSH access, then everything's working as intended.
