### ISSUE TITLE
Checkra1n says "All Done" but doesn't install on iPhone

### ISSUE THREAD

**Issue by brianwalczak** [checkra1n/BugTracker#2154]
**Tell us about your setup:**
1. What iDevice are you using? || iPhone 6s
2. On what version of iOS is it? || iOS 14.7
3. What version of checkra1n are you using? || Checkra1n 0.12.3
4. What is your host system (OS version? Hackintosh? VM? etc.)? || Mac Mini, Apple M1 Chip, Big Sur 11.5
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? || Apple USB-C

**What are the steps to reproduce the issue?**
1. Open Checkra1n (Any Version)
2. Open settings and enable "Allow untested iOS versions"
3. Start jailbreaking
...

**What do you expect, and what is happening instead?**

Expectation: Checkra1n Loader appears and I am able to install Cydia
Reality: Checkra1n says "All Done", but Checkra1n isn't on the iDevice

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

False/No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

True/Yes

**Any other info, error logs, screenshots, ...?**

Checkra1n Jailbreak looks successful but is not installed on the iDevice

**Comment by brianwalczak** [comment]
Does anybody know a solution to this??

**Comment by shinji257** [comment]
Just going to say it worked fine for me.  iPhone 6S Plus w/ Checkra1n 0.12.4 and iOS 14.7.  Mac Book Air w/ unofficial 10.15 Catalina install.  Maybe try again with a USB-A cable?  I got a generic $8 Onn branded cable to do this with.

**Comment by scris** [comment]
If "all done", though you can't see the app, most probably it is here, and will appear some time else (maybe). 

To get it know, open Shortcuts, create a new shortcut and insert "Open App", then select checkra1n from the list and run this shortcut.

**Comment by brianwalczak** [comment]
> If "all done", though you can't see the app, most probably it is here, and will appear some time else (maybe).
> 
> To get it know, open Shortcuts, create a new shortcut and insert "Open App", then select checkra1n from the list and run this shortcut.

Resolved :)

**Comment by Un1Gfn** [comment]
another way to force checkra1n show up  w/o waiting  

1. Settings - General - Language & Region - iPhone Language - (Switch to any other language)
1. Revert to your preferred language
