### ISSUE TITLE
when I try to use checkra1n kernel crash

### ISSUE THREAD

**Issue by GiuCrox** [checkra1n/BugTracker#2160]
For various reasons I used Checkra1n on this iPhone 7 and after the first success, the phone restarts and goes into recovery and does not go beyond the Apple logo.

<a href="https://ibb.co/DD5pq8d"><img src="https://i.ibb.co/99stMVP/aaaaa.jpg" alt="aaaaa" border="0"></a>

**Comment by Siguza** [comment]
Use a newer checkra1n version.

**Comment by GiuCrox** [comment]
> Use a newer checkra1n version

It's the latest version

**Comment by Siguza** [comment]
Doesn't it say "pongoOS-2.4.6" at the top?

**Comment by GiuCrox** [comment]
> Doesn't it say "pongoOS-2.4.6" at the top?

yes but he does it with checkrain1n 0.12.4

**Comment by GiuCrox** [comment]
> Doesn't it say "pongoOS-2.4.6" at the top?

[https://streamable.com/rtnr81](url)

This is the video checkra1n

**Comment by Siguza** [comment]
That's an entirely different issue. It doesn't even crash in PongoOS.

**Comment by GiuCrox** [comment]
how can i fix checkra1n probem?

**Comment by Siguza** [comment]
I wanna tell you to file a new bug and fill out the template this time, but tbh you probably just installed a broken tweak that's crashing your system.
