### ISSUE TITLE
pangooOS error

### ISSUE THREAD

**Issue by GiuCrox** [checkra1n/BugTracker#2162]
For various reasons I used Checkra1n on this iPhone 7 and after the first success, the phone restarts and goes into recovery and does not go beyond the Apple logo.

<a href="https://ibb.co/ZStKbnF"><img src="https://i.ibb.co/sCkQX0N/aaaaa.jpg" alt="aaaaa" border="0"></a>

**Comment by Siguza** [comment]
Duplicate of #2160, and still not a valid bug report.
