### ISSUE TITLE
iPhone X unable to activate FaceID

### ISSUE THREAD

**Issue by mehmeteminkartal** [checkra1n/BugTracker#217]
**What device + iOS version are you on?**
iPhone X(GSM) 13.2.2

**What checkra1n version are you using?**
0.9.2
**What are the steps to reproduce the issue?**
1. Enter the dfu mode while device is on (Not using checkra1n's steps)
2.Jailbreak using checkra1n 0.9.2 on an iPhone X
3.
...

**What do you expect, and what is happening instead?**
a working FaceID

**Any other info, error logs, screenshots, ...?**

when I first jailbreaked with checkra1n 0.9.2 screen was unresponsive and I re jailbreaked right after then touch was working but FaceID is not working and iOS gives the `Unable to activate FaceID` message

**Comment by mehmeteminkartal** [comment]
If I reboot without jailbreak touch and faceid functionality returns to normal.
(Animoji's still work even if it says faceid is not working 😆 )
![IMG_FEFF101C1E19-1](https://user-images.githubusercontent.com/5096916/68629701-cbbed000-04f5-11ea-8214-26ec17811801.jpeg)

**Comment by ghost** [comment]
Same issue

**Comment by ghost** [comment]
Jailbreak with 0.9.1

**Comment by scuty2000** [comment]
same issue, jailbroken using versione 0.9.2, not able to use faceID only when jailbroken.

**Comment by yur1xpp** [comment]
Having same issue on iPhone X, and trying to downgrade/rejailbreak with 0.9.1 and 0.9. BUT, every attempt is success(no error, it shows "Booting...") just the **device is not jailbroken**, it just boot into non jailbroken mode. No verbose booting screen is shown. Verbose only showed when using 0.9.2 to jailbreak. 0.9.2 somehow making 0.9.1 and 0.9 unable to jailbreak.

**Comment by kpwn** [comment]
Does booting with volume up pressed help at all?

**Comment by mehmeteminkartal** [comment]
@yur1xpp 
I has the same issue. I couldn’t jailbreak using 0.9.1 but the 0.9.2 fixes the iPhone X Error -20 issue. So we have to wait for a fix

**Comment by shehzaad10** [comment]
I had the same issue, it resolved for me by not putting the iPhone in DFU mode but allow the checkra1n app to put it into recovery and following the instructions to enter the iPhone into DFU mode. 

iPhone now has everything running smoothly and also faceID also works.

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.
