### ISSUE TITLE
iOS 11 untethered jailbreak support

### ISSUE THREAD

**Issue by Grandboy46** [checkra1n/BugTracker#2175]
Hello,

I found that there is an unther on iOS 11 called Acorn untether and there is no untethered jailbreak for iOS 11. Is it possible to support checkra1n for iOS 11 and install acorn untether? Checkm8 does support iOS 11.

Acorn Unthether: https://github.com/xerub/acorn

Sincerely,

**Comment by Siguza** [comment]
I don't see why checkra1n has to be involved in this. You can grab any jailbreak that already supports iOS 11 and just use that.
