### ISSUE TITLE
kernel panic with frida 12.7.20

### ISSUE THREAD

**Issue by korniltsev** [checkra1n/BugTracker#218]
**What device + iOS version are you on?**
build : iPhone OS 13.1.3 (17A878)
product : iPhone9,3
kernel : Darwin Kernel Version 19.0.0: Tue Sep  3 21:52:11 PDT 2019; root:xnu-6153.2.3~2\/RELEASE_ARM64_T8010
  

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. install frida from cydia from https://build.frida.re version 12.7.20
2. install frida version on macOS with pip3 
3. no other tweaks are installed
4. execute `fria-ps -U` on macOs

**What do you expect, and what is happening instead?**
I expect to see an enumeration of processes on ios device, but the kernel panics.
This might be an issue with frida though.

**Any other info, error logs, screenshots, ...?**

[panic-full-2019-11-12-023308.741.txt](https://github.com/checkra1n/BugTracker/files/3833731/panic-full-2019-11-12-023308.741.txt)

**Comment by Siguza** [comment]
Closing as it looks like this is an issue on Frida's side: https://twitter.com/fridadotre/status/1193681074687291392

**Comment by korniltsev** [comment]
fixed in frida 12.7.21 
https://github.com/frida/frida-core/commit/b19baa78d8571758cffa638a3133281d152cd776
