### ISSUE TITLE
Option to use different bootstraps

### ISSUE THREAD

**Issue by magmaus3** [checkra1n/BugTracker#2182]
I think that adding an option to use different bootstraps (like procursus) from the loader app would be awesome.

Optionally, the user would have an option to migrate from one bootstrap to another.

**Comment by crystall1nedev** [comment]
It was made clear in the Hack Different (checkra1n) Discord that no other bootstraps would be added to the loader. It is very much a sad thing to hear and see that a checkra1n team member pretty much said "I don't care, do it yourself", but hopefully once checkra1n is open source we can expect to see a pull request/fork of checkra1n that does have other straps.

**Comment by magmaus3** [comment]
Thanks for response.
