### ISSUE TITLE
ios 15 support

### ISSUE THREAD

**Issue by Grandboy46** [checkra1n/BugTracker#2187]
Hi @Siguza,

I heard that checkra1n does not work on ios 15. Can you please add support for ios 15 or give more information about ios 15 support?

Sincerely,

**Comment by Gerriarob** [comment]
No, it works.

**Comment by Grandboy46** [comment]
> No, it works.

https://github.com/checkra1n/BugTracker/issues/2187#issuecomment-927172449

**Comment by Gerriarob** [comment]
Have it working on two iPad 6 gen and 1 iPhone 7. iOS 15 and checkra1n

**Comment by Siguza** [comment]
Duplicate of #2124.  
Already being worked on.
