### ISSUE TITLE
Can You give a support  for iPad 8th A12 for iPad OS 14.4.2 ?I’d just open it and find out it’s on this crappy version despite that what Apple claimed it would be (14)

### ISSUE THREAD

**Issue by Vinzest** [checkra1n/BugTracker#2192]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Vinzest** [comment]
Lastest on mac with usb A

**Comment by crystall1nedev** [comment]
Uhh... checkra1n is a hardware-based jailbreak that doesn't work on A12 or higher. The dev team can't change that.

**Comment by vadimszzz** [comment]
Checkra1n never would work on A12.

@Siguza close the issue
