### ISSUE TITLE
iPhone SE 1st Generation Issue

### ISSUE THREAD

**Issue by zeker4321** [checkra1n/BugTracker#2197]
**Tell us about your setup:**
1. What iDevice are you using? iPhone SE (1st Generation)
2. On what version of iOS is it? 14.6
3. What version of checkra1n are you using? 0.12.4 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)?  Manjaro aarch64 for Raspberry Pi 3b
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A cable, Third Party, Directly connected to RP

**What are the steps to reproduce the issue?**

1. Launch Checkra1n
2. Turn on 'Allow untested iOS/iPadOS/tvOS versions'
3.Plug in iPhone
4. Follow steps
5.Get Error Code -35

**What do you expect, and what is happening instead?**
I expect: to see my device booting into jailbroken iOS
What is Happening: I get error code -35 and iPhone is still in DFU mode
**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No, it never booted into iOS

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by lilboat357** [comment]
I have the same issue on my first gen. When I press next nothing happens.

**Comment by zeker4321** [comment]
I tried using a different computer and it worked just fine. I think my Pi’s usb controller wasn’t supported.
