### ISSUE TITLE
5C (Global) - Unsupported Device

### ISSUE THREAD

**Issue by FredericaNurk** [checkra1n/BugTracker#2204]
Your site indicates that a iPhone 5c is supported by checkra1n beta 0.12.4.  I have a 5c (Global) and when I connect it, checkra1n issues error message "Sorry, iPhone 5c (Global) is not supported".  I presume that this is an oversight.

regards, Freda

**Comment by asdfugil** [comment]
No, it didn't indicate. And it is not supported.

**Comment by Siguza** [comment]
It says 5s, not 5c.
