### ISSUE TITLE
Tweaks not working

### ISSUE THREAD

**Issue by iKasprModz** [checkra1n/BugTracker#221]
**What device + iOS version are you on?**
iPhone X 13.2

**What checkra1n version are you using?**
0.9.2
**What are the steps to reproduce the issue?**
1.Go on Cydia 
2.Install a tweak
3.it install it but never work and I don’t see it on setting or anything 
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by laelin** [comment]
Don’t know how your data is set up on your phone but I would say do a factory reset and start iPhone as New, don’t restore from any back up. To get your iCloud Drive pictures and stuff just log in to iCloud after setting up as NEW. Past jailbreak tweak injectors and substitutes seem to interfere with Cydia and tweaks themselves for checkra1n. Perhaps before the factory reset try going to cydia and removing any tweak injector/ substrate / substitute, everything from Electra and coolstar repo. The only substrate you need is the Cydia Substrate found in the checkra1n repo. Make sure all other substrates are removed! Then try tweaks.. if that doesn’t work... full file system restore.

**Comment by iKasprModz** [comment]
> Don’t know how your data is set up on your phone but I would say do a factory reset and start iPhone as New, don’t restore from any back up. To get your iCloud Drive pictures and stuff just log in to iCloud after setting up as NEW. Past jailbreak tweak injectors and substitutes seem to interfere with Cydia and tweaks themselves for checkra1n. Perhaps before the factory reset try going to cydia and removing any tweak injector/ substrate / substitute, everything from Electra and coolstar repo. The only substrate you need is the Cydia Substrate found in the checkra1n repo. Make sure all other substrates are removed! Then try tweaks.. if that doesn’t work... full file system restore.

I got it fixed I just unjailbreak my phone and jailbreak it back again and everything works I guess that’s my fix for all my problems because everytime I have a problem even with spring board I got it fixed with unjailbreaking and jail breaking back again thank you anyways
