### ISSUE TITLE
Attaching to any process with frida is denied or panics device and reboots

### ISSUE THREAD

**Issue by blacktop** [checkra1n/BugTracker#222]
**What device + iOS version are you on?**
iPod Touch, 12.4

**What checkra1n version are you using?**
0.92
**What are the steps to reproduce the issue?**
1. frida-ps -U
2. find "interesting" process
3. frida -U Calculator
4. ☠️ 
...

**What do you expect, and what is happening instead?**
I expect to have fun with frida like 1337 p0 hax0rz 😭 

**Any other info, error logs, screenshots, ...?**

**Comment by blacktop** [comment]
Sounds like it might be a frida issue.  https://twitter.com/fridadotre/status/1193681074687291392

**Comment by Siguza** [comment]
Also marking this as duplicate of #218.
