### ISSUE TITLE
Unsupported Versions

### ISSUE THREAD

**Issue by nxofkin** [checkra1n/BugTracker#2224]
**Tell us about your setup:**
1. What iDevice are you using? ipad mini 4 lte 
2. On what version of iOS is it? 11.2.5
3. What version of checkra1n are you using? 0.12.4
4. What is your host system (OS version? Hackintosh? VM? etc.)? macos 10.13.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple cable to usb port

**What are the steps to reproduce the issue?**
1. Run Allow untested ios version option
2. Run Allow untested ios option and Safe Mode option
3." Verbose Boot option tried too
...

**What do you expect, and what is happening instead?**
Booting bar fills to 3/4 then stops, a short scroll(shorter than a successful jailbreak) of commands run on ipad screen, then Checkra1n goes to DONE after 60-80 seconds and  reads, " Timed out waiting for bootstrap upload (Likely caused by incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)"  
ipad has already gone back to white screen black Apple after about 5 seconds as the  booting has stalled. 

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?** No, the ipad just goes back into its normal screen after 5 seconds of the Booting stage.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes it reads the same, "Timed out...." during booting

**Any other info, error logs, screenshots, ...?**
I tried Checkra1n older versions-0.9.1, 0.9.3.2, 0.9.6 ---some would not allow START, or not provide for OPTIONS.
Please let me know if I can test run anything else.  This iPad will be a wallhanger if I can not get the activation lock undone.

**Comment by sharedito** [comment]
Same happened to me when my iPad Mini 4 was on 13.x iOS version, so I tried checkra1n 0.10.2 and it worked. 
https://checkra.in/releases/0.10.2-beta
I hope this helps.

PS: I updated my iPad to 14.6 by mistake and now I cannot Jailbreak it, I hope they support iPad Mini 4 on 14.6 soon...PLEASE!!

**Comment by P5-2005** [comment]
> **Tell us about your setup:**
> 
>     1. What iDevice are you using? ipad mini 4 lte
> 
>     2. On what version of iOS is it? 11.2.5
> 
>     3. What version of checkra1n are you using? 0.12.4
> 
>     4. What is your host system (OS version? Hackintosh? VM? etc.)? macos 10.13.6
> 
>     5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple cable to usb port
> 
> 
> **What are the steps to reproduce the issue?**
> 
>     1. Run Allow untested ios version option
> 
>     2. Run Allow untested ios option and Safe Mode option
>        3." Verbose Boot option tried too
>        ...
> 
> 
> **What do you expect, and what is happening instead?** Booting bar fills to 3/4 then stops, a short scroll(shorter than a successful jailbreak) of commands run on ipad screen, then Checkra1n goes to DONE after 60-80 seconds and reads, " Timed out waiting for bootstrap upload (Likely caused by incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)" ipad has already gone back to white screen black Apple after about 5 seconds as the booting has stalled.
> 
> **Did you see a popup on the device stating it entered "Safe Mode" due to an error?** No, the ipad just goes back into its normal screen after 5 seconds of the Booting stage.
> 
> **Does the issue also occur if you tick "Safe Mode" in the checkra1n options?** Yes it reads the same, "Timed out...." during booting
> 
> **Any other info, error logs, screenshots, ...?** I tried Checkra1n older versions-0.9.1, 0.9.3.2, 0.9.6 ---some would not allow START, or not provide for OPTIONS. Please let me know if I can test run anything else. This iPad will be a wallhanger if I can not get the activation lock undone.

checkra1n only from ios 12 and up, your ios is not supported

**Comment by nxofkin** [comment]
> Same happened to me when my iPad Mini 4 was on 13.x iOS version, so I tried checkra1n 0.10.2 and it worked. https://checkra.in/releases/0.10.2-beta I hope this helps.
> 
Yes I tried version 0.10.2 with NO JOY ...Thanks for the response .

**Comment by nxofkin** [comment]
> checkra1n only from ios 12 and up, your ios is not supported

Yes I see that supported versions go from 12 and up, it was just a hope that during Checkra1n development that an iOS 11x version was put aside that would allow untested iOS/iPadOS versions.  Thank you for responding.
