### ISSUE TITLE
Iphone 12 pro max ios 15.2

### ISSUE THREAD

**Issue by lfcc12** [checkra1n/BugTracker#2226]
Hello and i am sorry to bother u guys, is  it possible for me to use one checkra1n beta or developer for my iphone cause i rly needed and if u guys can do it for me was amazing

**Comment by Rexwei** [comment]
checkmate only support A7-A11

**Comment by Rexwei** [comment]
> Hello and i am sorry to bother u guys, is it possible for me to use one checkra1n beta or developer for my iphone cause i rly needed and if u guys can do it for me was amazing

checkmate only support A7-A11

**Comment by Siguza** [comment]
See #1.
