### ISSUE TITLE
Touch not responding - 0.9.2 iPhone X

### ISSUE THREAD

**Issue by scuty2000** [checkra1n/BugTracker#224]
**What device + iOS version are you on?**
13.2.2, updated via iTunes.

**What checkra1n version are you using?**
0.9.2
**What are the steps to reproduce the issue?**
1. enter dfu mode
2. jailbreak using the gui tool
3. try to use anything
...

**What do you expect, and what is happening instead?**
a working touchscreen, but it is not responding

**Any other info, error logs, screenshots, ...?**
I tried to dump some error logs but nothing

**Comment by yur1xpp** [comment]
Duplicated issue https://github.com/checkra1n/BugTracker/issues/215

**Comment by gnutnos98** [comment]
is that Haptic Touch, can you test you Sound also, mine not working

**Comment by scuty2000** [comment]
Closed as a duplicate of [#215](https://github.com/checkra1n/BugTracker/issues/215)
