### ISSUE TITLE
ignore

### ISSUE THREAD

**Issue by segg21** [checkra1n/BugTracker#2241]
w.e

**Comment by sultan5505** [comment]
hi
good morning

**Comment by sultan5505** [comment]
00923000056640 contact me urgent

‪On Sat, Jan 8, 2022 at 6:59 AM ‫سطان موسئ‬‎ ***@***.***> wrote:‬

> hi
> good morning
>

**Comment by ghost** [comment]
@LegitSoulja  Whats the point removing issues like that? everyone can still see your edit history. Delete your account if you are worried about privacy

**Comment by segg21** [comment]
That's not the point. Mind your business and go delete your account, like you even use Github anyways..
