### ISSUE TITLE
How to restore Face ID after “restore rootfs”?

### ISSUE THREAD

**Issue by vadimszzz** [checkra1n/BugTracker#2243]
Hi @Siguza! After jailbreaking iPhone X Face ID doesn’t work for sure. But it’s still doesn’t work in stock iOS after restoring rootfs, factory reset & iOS reinstall… Tell please how to unjailbreak and restore Face ID? Is there any way or it’s broken forever?

**Comment by Siguza** [comment]
If it doesn't work after an IPSW restore, then it's probably broken in hardware.

**Comment by vadimszzz** [comment]
> If it doesn't work after an IPSW restore, then it's probably broken in hardware.

No, sorry, I’m not the only one who experienced this issue. It worked before checkra1n.

https://www.reddit.com/r/checkra1n/comments/moqwds/comment/gu5py41/

**Comment by vadimszzz** [comment]
If it’s impossible to restore even with clean IPFS install maybe something wrong in blobs? I don’t know what means A11 BPR check but I think it’s the problem.

**Comment by Siguza** [comment]
If you do a clean IPSW restore, then no tracke of checkra1n is left on the device. If something is still broken after that, take it to Apple.
