### ISSUE TITLE
Random display issues

### ISSUE THREAD

**Issue by Naville** [checkra1n/BugTracker#225]
**What device + iOS version are you on?**
iPhone 6s iOS 12.4

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. Jailbreak the device

**What do you expect, and what is happening instead?**
Everything works as expected

**Any other info, error logs, screenshots, ...?**
It's happening 2~4 times in a day and is indeed very random for me to take a photo or anything. But I do experience weird screen display artifacts and/or random screen flashes every now and then.  
I do have my battery and storage replaced before but considering it still works perfectly find prior to using cr I highly doubt this is the case

**Comment by Naville** [comment]
Update:  
Seems like this mostly took place when the device is awake from a long sleep mode(lock screen)

**Comment by kpwn** [comment]
unrelated from this issue: Thanks for Hikari!! We are using it for checkra1n.

**Comment by Naville** [comment]
@kpwn Should have asked me for the premium version for better security : P

Also the pipeline scheduling is a bit broken in the version you are using, results in some strings not fully obfuscated.

**Comment by nullpixel** [comment]
@Naville can you still reproduce this issue?

**Comment by comthre3** [comment]
I’ve got the same issue.
Updated to iOS 13.2.3 used checkra1n 0.9.6 iPhone resprings I don’t get the all done message. Phone reboots and the screen is unresponsive. 

PS. I broke my screen and had it replaced with a non original screen. Could that be the issue?

Thanks for the awesome work guys
