### ISSUE TITLE
Stuck with cydia files on i15

### ISSUE THREAD

**Issue by dafidka** [checkra1n/BugTracker#2253]
I have jailbreaked my device with checkra1n on i14, brainlessly upgraded to i15, JB detection apps detect it (or won't even run), what are my options now on 15.2.1? I've got no blobs, nothing. If i restore my phone with iTunes will it erase cydia data?

**Comment by enhancedrock** [comment]
The only option unfortunately would be to reset, however resetting **doesn't** delete you're cydia files/tweaks (it might do with downgrading, not sure bout' that). I know this from personal experience, all jb data is kept intact. I performed a reset once on my iPad and when I re-jailbroke, everything was still there.

**Comment by Siguza** [comment]
Backup + wiping the device + restoring backup should help.
