### ISSUE TITLE
springboard crash

### ISSUE THREAD

**Issue by les971** [checkra1n/BugTracker#226]
**What device + iOS version are you on?**
IPhone X 13.2.2

**What checkra1n version are you using?**
beta 9.2
**What are the steps to reproduce the issue?**
1.happpened randomly 
2.
3.
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**
![checkimage0](https://user-images.githubusercontent.com/57648897/68636126-8801a180-04c8-11ea-813a-af0c4c4e0e93.png)

**Comment by alnandr** [comment]
Did you install any tweaks to your device, or is this a fresh install of the checkra1n jailbreak with Cydia?

Reading the modal dialog message, you will understand why this occurs most often.

**Comment by les971** [comment]
I installed a few things it crash last night while I was sleeping when I
woke up I saw this it’s so often. But Idk what cause this to happened.
Below are what I install.

**Comment by kpwn** [comment]
This is not a tweak support issue tracker.
