### ISSUE TITLE
Jailbreak reset on reboot.

### ISSUE THREAD

**Issue by Kief5555** [checkra1n/BugTracker#2272]
**Tell us about your setup:**
1. Ipad air first gen
2. 12.5
3. 0.12.4
4. mAcOs baby
5. apple cable

**What are the steps to reproduce the issue?**
1. Do the jb
2. restart the device
3. and its gone.
...

**What do you expect, and what is happening instead?**
for it to work after every restart 

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
no

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes.
**Any other info, error logs, screenshots, ...?**
Nope

**Comment by lumiini** [comment]
You do realise that it's a semi-tethered jailbreak right you will lose jailbreak after you restart. For you to be able to keep the jailbreak after you restart it has to be an untethered jailbreak but checkra1n is not untethered

**Comment by Kief5555** [comment]
> 

Ah, I didn't know.

**Comment by lumiini** [comment]
Ok great
