### ISSUE TITLE
Jailbreaking process looping and eventually failing (error code -31)

### ISSUE THREAD

**Issue by Theslees** [checkra1n/BugTracker#2295]
## **Tell us about your setup:**
1. What iDevice are you using?
**iPhone 7**
3. On what version of iOS is it?
**iOS 13.**
4. What version of checkra1n are you using?
**0.12.4 beta**
6. What is your host system (OS version? Hackintosh? VM? etc.)?
**Arch Linux 5.18.8 x86_64 (no vm, and no arch flavor, vanilla arch.)**
7. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
**USB-A to Lightning cable**
----------------------------------------------------------------------
**What are the steps to reproduce the issue?**
1. Run the binary as root with `./checkra1n`
2. tick "Allow untested iOS/iPadOS/tvOS versions"
3. Start and follow the steps accordingly.
...

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
> No, it stays black the entire time

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
> Yea

**Any other info, error logs, screenshots, ...?**
![image](https://user-images.githubusercontent.com/59808149/177025520-c09f538b-596a-458c-9458-14344853e5fc.png)
![image](https://user-images.githubusercontent.com/59808149/177025558-d86f4533-9167-49c7-b1c4-af9bd72ddad4.png)
![image](https://user-images.githubusercontent.com/59808149/177025563-b8a83b1e-82a8-4775-83f3-dfa1b89601c4.png)
then repeats... until it errors. Please let me know how to get the logs since I don't know how to

**Comment by Theslees** [comment]
UPDATE; Fixed by turning on `Verbose Boot`!
For anyone having this issue too :)

**Comment by EnzoLeoncio** [comment]
i turned on the verbose boot bus didn t is efective

**Comment by Theslees** [comment]
@EnzoLeoncio You're probably better off with a different solution like Palera1n (a fork), I think you should really only use this tool for older iOS firmwares too, though you might aswell update to a newer ios firmware aswell (with itunes or flash a .ipws file that's signed, if your device is old enough then the latest signed ios firmware should still be compatible with something like palera1n or odyssey)
