### ISSUE TITLE
Haptic Touch and Sound not responding 

### ISSUE THREAD

**Issue by gnutnos98** [checkra1n/BugTracker#231]
**What device + iOS version are you on?**
iPhone 8 Plus + iOS 13.2.2

**What checkra1n version are you using?**
0.9.2

**What are the steps to reproduce the issue?**
1. No problems with Jailbreak

**What do you expect, and what is happening instead?**
I don't no if I installed bad tweak or not? But in the latest version (0.9.2) is work OK.
But with the older version (0.9.1) still have -20 errors. 

The issues when I Jailbreak with 0.9.2 version are:
-  Haptic Touch not responding
- . Can not adjust volume
-  Phone Call have no sound

(I restored the Cydia in Checkra1n app but still got these above errors)

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.

**Comment by Mr-Resetti** [comment]
stopped working for me too

**Comment by cherifsahraoui** [comment]
Same behavior with iPhone 8 Plus + iOS 14.7.1. No sound and haptic touch
