### ISSUE TITLE
Bootloop iOS 13 after Hard Reset

### ISSUE THREAD

**Issue by 1supercooldude** [checkra1n/BugTracker#234]
The music widget on lockscreen wasnt popping up so i decided to do a hard reset, now my iphone X is in bootloop and i cannot even get it to go into dfu mode or itunes to connect it

**Comment by nullpixel** [comment]
Rejailbreak holding volume up when you see the Apple logo and don’t let go until the device boots.

**Comment by TiagoSoares** [comment]
This fixed it for me

**Comment by TiagoSoares** [comment]
> Rejailbreak holding volume up when you see the Apple logo and don’t let go until the device boots.

This fixed it for me
