### ISSUE TITLE
"checkra.1n" Wont let you Download Version (0.9.2)

### ISSUE THREAD

**Issue by 0x41c** [checkra1n/BugTracker#237]
**What device + iOS version are you on?**(**MacOS**)
Catalina 10.15.1

**What checkra1n version are you using?**(**Trying to use**)
0.9.2

**What are the steps to reproduce the issue?**
1.Go to https://checkra.in 
2.scroll down a tiny eensy teensy bit
3.press **Download For MacOS**
...

**What do you expect, and what is happening instead?**
It to work like two bunnies under a bed      
```
(Download)
```
_______________________________________________

**Instead**
It Gives you the Bird 
```
(404)
```
**Any other info, error logs, screenshots, ...?**
![Screen Shot 2019-11-12 at 12 53 00 AM](https://user-images.githubusercontent.com/56287516/68656500-cc039f00-04e6-11ea-8cb2-a9e04a9c8cdf.png)

**Comment by kpwn** [comment]
This seems like a DNS caching issue. Could you try running "ping checkra.in" in Terminal, or changing your DNS to 8.8.8.8? We moved the infrastructure to a new server 24 hours ago.

**Comment by nullpixel** [comment]
closing because this is a DNS issue but if it’s not resolved by using 8.8.8.8 then please reply and I’ll reopen
