### ISSUE TITLE
cant download the windows app after completing more than one offer 

### ISSUE THREAD

**Issue by chronicknight86** [checkra1n/BugTracker#2379]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. im still on checkra1n.in and tryint to download but after completing 2 offers it still will not allow me to download app
![Screenshot (2)](https://github.com/checkra1n/BugTracker/assets/33399651/b5860dd0-b8cc-4946-94c2-37ed1a2dcb1a)
. 
3.
...

**What do you expect, and what is happening instead?**

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by teebow1e** [comment]
there is no checkra1n on Windows.

**Comment by Siguza** [comment]
Do you not see the bullshit URL in the address bar?
