### ISSUE TITLE
iPhone 6s with iOS 13.2.2 error code : -20

### ISSUE THREAD

**Issue by abuhassan-dev** [checkra1n/BugTracker#238]
**What device + iOS version are you on?**
6s
iOS 13.2.2
iMac with latest Catalina
Original Cable 
**What checkra1n version are you using?**
all versions 

**What are the steps to reproduce the issue?**
1.DFU Mode
2.Hit start
3.stuck a bit on booting
4.the device boot and the bar still say booting
5.after this it’s say an error code -20

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**
someone reported same issue at Twitter

**Comment by TateB** [comment]
Make sure you're going from Recovery mode -> DFU mode.

**Comment by abuhassan-dev** [comment]
> Make sure you're going from Recovery mode -> DFU mode.

Still got same error

**Comment by TateB** [comment]
If you run it in terminal with -v, what does it stall on

**Comment by littlelailo** [comment]
Did you try to boot with safe mode? And what's happening on the phone?

**Comment by abuhassan-dev** [comment]
Fixed by start jailbreaking from normal mode

**Comment by lyuxxx** [comment]
@anonfantom Could you please tell me how to enter DFU mode,I can't enter DFU mode by the instructions.My device is also iPhone 6s.Thanks in advance.
