### ISSUE TITLE
I have a problem about Iphone 11 (iOS 16.4.1)

### ISSUE THREAD

**Issue by alexxx47** [checkra1n/BugTracker#2385]
**Tell us about your setup:**
1. What iDevice are you using? HP Notebook
2. On what version of iOS is it? 16.4.1
3. What version of checkra1n are you using? 0.12.4
4. What is your host system (OS version? Hackintosh? VM? etc.)? OS 10
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A

**What are the steps to reproduce the issue?**
1.  Sorry, iPhone 11 (iOS 16.4.1) is not supported. ECID: 0xa0536ea0402e
2. 
3.
...

**What do you expect, and what is happening instead?**

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by ElectroBoy404NotFound** [comment]
Ummm as it says, iPhone 11 is not supported and will never be as it is invulnerable to checkm8.
