### ISSUE TITLE
Core DLL not found

### ISSUE THREAD

**Issue by Azur3Dev** [checkra1n/BugTracker#2389]
I am currently trying to jailbreak my iPhone 8 plus ( running ios 16.7.7) but as soon as i start the procedure after putting the phone in dfu mode it tells me that I am missing the core dll, I will post some screenshots bellow

![image_2024-06-03_231513263](https://github.com/checkra1n/BugTracker/assets/167893572/cadbb6fd-6d2e-4c9d-9c2e-e5578f4a787c)

**Comment by mostwise** [comment]
wrong jailbreak bud, try reporting your issue @ https://github.com/palera1n/palera1n/issues
