### ISSUE TITLE
Checkra1n doesn't install checkra1n app

### ISSUE THREAD

**Issue by dylanneve1** [checkra1n/BugTracker#24]
**What device + iOS version are you on?**
iPhone 6S, iOS 13.2.2

**What are the steps to reproduce the issue?**
1. Plug device into Mac with checkra1n app open.
2. Get device into DFU mode.
3. Run checkra1n.
4. Checkra1n boot screen will appear with the text and all while the program displays "booting".
5. Unlock device, no checkra1n app.
6. Checkra1n for Mac errors.

**What do you expect, and what is happening instead?**
Checkra1n app to install successfully.

**Any other info, error logs, screenshots, ...?**
![Screen Shot 2019-11-10 at 14 16 36](https://user-images.githubusercontent.com/31746704/68545406-dded2100-03c4-11ea-8f75-711de0d646d3.png)

**Comment by dylanneve1** [comment]
Update! After leaving phone plugged into Mac for a minute or two. Checkra1n app appears. Not sure if this is intended behaviour or not

**Comment by cjf99** [comment]
how did you run it through the console?

**Comment by dylanneve1** [comment]
@cjf99 used the command they listed. "./checkra1n.app/Contents/MacOS/checkra1n_gui"

**Comment by cjf99** [comment]
for me it says: no such file or directory :/

**Comment by nullpixel** [comment]
The loader app might take a while to show due to uicache
