### ISSUE TITLE
Checkra1n IPhone 7 stuck on "Checking if device is ready"

### ISSUE THREAD

**Issue by cezarkrc** [checkra1n/BugTracker#240]
**What device + iOS version are you on?**

iPhone 7 + iOS 13.3 Beta + macOS High Sierra in VMWare
**What checkra1n version are you using?**
Beta 0.9.2
**What are the steps to reproduce the issue?**
1.
2.
3. The device is in DFU mode
Checkra1n IPhone 7 stuck on "Checking if device is ready"

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by ahammouri** [comment]
Checkra1n doesnt support VMware

**Comment by littlelailo** [comment]
VMs aren't supported. See: https://twitter.com/checkra1n/status/1193606172366057472
