### ISSUE TITLE
Unlock iCloud 

### ISSUE THREAD

**Issue by Ayushpandey-ay** [checkra1n/BugTracker#2405]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. iPhone 11 pro
2. 
![IMG-20240816-WA0009](https://github.com/user-attachments/assets/d30aceec-ae3f-4ab6-9b47-138235e6d983)
![IMG-20240816-WA0007](https://github.com/user-attachments/assets/f4f391a2-5f51-4f59-b4da-c9827ba04c27)
![IMG-20240816-WA0003](https://github.com/user-attachments/assets/ac76dde9-6e5f-414d-847f-88577f9b79f7)
![IMG-20240816-WA0005](https://github.com/user-attachments/assets/995404fd-953a-49a6-99eb-c5d826032692)
![IMG-20240816-WA0001](https://github.com/user-attachments/assets/7765f441-d9c6-42ba-9bf7-5f79dc208a09)
![IMG-20240816-WA0009](https://github.com/user-attachments/assets/e803f3de-a103-4f6e-b0ba-367b22733fb1)
![IMG-20240816-WA0007](https://github.com/user-attachments/assets/200930d5-4edc-4973-b4a8-68cb4d1b47d8)
![IMG-20240816-WA0003](https://github.com/user-attachments/assets/a1972ddb-511e-4be5-8226-b9b55826befe)
![IMG-20240816-WA0005](https://github.com/user-attachments/assets/0a6c0669-bfd5-43c4-bc21-107ed9cd1231)
![IMG-20240816-WA0001](https://github.com/user-attachments/assets/f1fa398a-be2a-4a42-81be-fbf7a71579f4)

3.
...

**What do you expect, and what is happening instead?**
I want to unlock my iCloud account because I forgot my password 

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
iCloud locked by owner 

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by waleedsid** [comment]
I do not think this iphone belongs to you but if it does all you have to do is Reset your password using another device or just call/email apple care.
