### ISSUE TITLE
Iphone 3Gs // iOS 6.1.6 // Checkra1n 0.12.4 B // phone not found

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#2406]
**Tell us about your setup:**
1. What iDevice are you using? **iPhone 3GS**
2. On what version of iOS is it? **6.6.1**
3. What version of checkra1n are you using? **beta 0.12.4**
4. What is your host system (OS version? Hackintosh? VM? etc.)? **linux dualboot**
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? **original usb a cable from apple**

**What are the steps to reproduce the issue?**
1. connect iPhone 3GS
2. Open Checkra1n
3. checkra1n wont find the iphone but linux  does
...

**What do you expect, and what is happening instead?**
it should show that my phone is found and that i can jb

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
never i reset that phone yesterday

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Comment by Siguza** [comment]
What made you think 3GS was even vulnerable to checkm8?
