### ISSUE TITLE
help

### ISSUE THREAD

**Issue by me06-blip** [checkra1n/BugTracker#2407]
> found this: sudo apt-get remove --purge libgdk-pixbuf2.0 sudo apt-get -f install

**System brick risk - do not run this unless you know what you're doing!**
At least for my system this command removed 200+ libraries and crashed the whole UI, couldn't even boot the machine (even in recovery mode). I had to use a live USB to chroot into the system, check the apt-get history, reinstall everything it had removed, then reboot my system. Honestly my fault for not scrutinizing the command more before I ran it, but don't want others to make the same mistake.

_Originally posted by @mpvoss in https://github.com/checkra1n/BugTracker/issues/2312#issuecomment-2075358825_

**Comment by me06-blip** [comment]
can someone help i accidentally removed my UI now i have nothing but the  cli

**Comment by Siguza** [comment]
That has nothing to do with checkra1n. Try [askubuntu.com](https://askubuntu.com/), [unix.stackexchange.com](https://unix.stackexchange.com/) or [superuser.com](https://superuser.com/).
