### ISSUE TITLE
cant connect to wifi after checkra1n boot and home button won't give haptic feedback

### ISSUE THREAD

**Issue by bbbbbbora** [checkra1n/BugTracker#244]
**What device + iOS version are you on?**
iPhone 8 iOS 13.1.3

**What checkra1n version are you using?**
0.9.2 beta
**What are the steps to reproduce the issue?**
1. Use Jailbreak
2. Hold Volume Up for safe mode
3. Wait for boot
...

**What do you expect, and what is happening instead?**
I expected to be in safe mode to remove bad tweaks, but when it booted, I cant connect to wifi and my home button wont give haptic feedback

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.
