### ISSUE TITLE
FaceID doesn’t work & Frozen 

### ISSUE THREAD

**Issue by polichan** [checkra1n/BugTracker#249]
Checkra1n Version: 0.9.2 

My device is frozen after the first attempt to jailbreak. So I hard boot my device and jailbreak again and my device isn’t frozen but with the FaceID not working. I am pretty sure the FaceID hardware is in good condition because when I reboot my device the FaceID works well. It seems the device will not be frozen (but FaceID won’t work)anytime you jailbreak your device twice.

Not installed any tweaks on my device.

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by polichan** [comment]
Device: iPhone X 
The iOS version is 13.2.2

**Comment by TiebeVercoutter** [comment]
same

**Comment by neil0306** [comment]
Same with you

**Comment by denniskns** [comment]
same

**Comment by alisabah025** [comment]
Same. 
iPhone X ,iOS 13.2.2 , beta 0.9.3 
And this is my first time so I don’t have any tweaks

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.
