### ISSUE TITLE
Not able to ssh to Iphone with iproxy

### ISSUE THREAD

**Issue by Xwdit** [checkra1n/BugTracker#25]
Trying to solve the chinese network problem with iproxy,an I installed usbmuxd ,connected my iphone with usb.and typed "iproxy 1234 44",then "ssh -p 1234 root@127.0.0.1 and it said connection reset to peer,and for iproxy  it said Error connecting to device

**Comment by StefanNienhuis** [comment]
I think this is an issue with the Checkra1n website. I was able to SSH into my iPhone through port 22.

**Comment by Xwdit** [comment]
> I think this is an issue with the Checkra1n website. I was able to SSH into my iPhone through port 22.

still not connectable

**Comment by woachk** [comment]
@Xwdit kill iproxy, unplug device, launch iproxy again and then connect

**Comment by Xwdit** [comment]
notwork

**Comment by clarityzzz** [comment]
ssh root@localhost -p 1234

**Comment by littlelailo** [comment]
Which ios version and which device

**Comment by Hackerpunk1** [comment]
I'm able to ssh with iproxy due to the fact that in FAQ, it has been posted that ssh is on port 44 and not 22

**Comment by Siguza** [comment]
Closing due to lack of responses and lack of reproducibility.

**Comment by Thecrazyskull** [comment]
@Siguza I am able to reproduce this problem every single time on an iPhone 5s using Checkra1n CLI mode. I noticed that after sometime the terminal windows returns error code -20 (this happens after I run iproxy and get the error as stated in this ticket in a different terminal window). Let me know if any more info is needed. Thanks

**Comment by appleguru** [comment]
Am also having this issue; ssh does not appear to work at all via proxy. Tried ports 22 and 44 with no luck.

```
accepted connection, fd = 4
waiting for connection
Number of available devices == 2
Requesting connecion to device handle == 147 (serial: xxxxx), port 44
Error connecting to device!
```
```
waiting for connection
accepted connection, fd = 4
waiting for connection
Number of available devices == 2
Requesting connecion to device handle == 147 (serial: xxxx), port 22
Error connecting to device!
```

```
 % ssh root@localhost -p 2222
ssh_exchange_identification: read: Connection reset by peer
```

**Comment by appleguru** [comment]
(but was able to get this to work by unplugging/replugging and restarting iproxy. Working on port 44). It never works right after jailbreaking without unplugging first.
