### ISSUE TITLE
iOS 13.2.2 - iPhone X touchscreen disabled after jb

### ISSUE THREAD

**Issue by peterwin97** [checkra1n/BugTracker#250]
**What device + iOS version are you on?**
iOS 13.2.2

**What checkra1n version are you using?**
beta 0.9.2
**What are the steps to reproduce the issue?**
1.DFU Mode
2.Start jailbreak
3.iPhone boots up
...

**What do you expect, and what is happening instead?**
I would expect to use device but the touchscreen was not responding. Buttons still worked.

**Any other info, error logs, screenshots, ...?**
Only happens on MacBook Pro 2017 running macOS Mojave 10.14.6.
Moved onto MacBook Pro 2015 running macOS Catalina 10.15 and everything works fine there.

**Comment by ThatSebastjan** [comment]
I have the same issue.... Using MB Pro 2018 tough.

**Comment by SeaStone001** [comment]
Same here with iPhone X (GSM) iOS 13.2.2 on MBP 2019 13´ MacVer. 10.15.1

With iPad 6th Gen on same MacBook no Problems.

**Comment by ThatSebastjan** [comment]
I’ll try downgrading to 13.2

**Comment by ThatSebastjan** [comment]
It hasn't fixed it 😪

**Comment by peterwin97** [comment]
Do y’all have access to another Mac, if so try it there. That’s the only solution I’ve had that worked for me

**Comment by ThatSebastjan** [comment]
I could bring out my old hackintosh but will it work?

**Comment by punpunpunpunpun** [comment]
Same with iPhone X (Global) iOS 13.2.2 on MBP 2017 15' macOS 10.15.1.
With iPad Pro 10.5 -> Works.

**Comment by greenywd** [comment]
Same occurs with my iPhone X (iOS 13.2.2) but it doesn't appear to happen on 0.9.1 (and I presume 0.9.0).

**Comment by kpwn** [comment]
can you try with this test build? https://assets.checkra.in/test/checkra1n%20beta%200.9.3.4.dmg

**Comment by punpunpunpunpun** [comment]
checkra1n app doesn't appear on my iPhone.
Also, Face ID doesn't work.

**Comment by kpwn** [comment]
Can you try with this: https://assets.checkra.in/test/checkra1n%20beta%200.9.4.dmg

**Comment by peterwin97** [comment]
Just tried the 0.9.4 build on my 2017 MacBook Pro. Initially it didn't work for me, but I read in another thread it might be a USB C issue so I tried a USB A to Lightning cable into a USB C adapter and I was able to get into DFU mode from the recovery mode screen.

Face ID and touch screen works. Lmk if this worked for y'all, and I can close this tracker.

**Comment by ThatSebastjan** [comment]
No it still didn’t work for me

**Comment by trulynb** [comment]
Fixes an issue where the touch screen became unresponsive for some users
--------------------------------
still    on   my   iphone x  13.2.2

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.
