### ISSUE TITLE
Unable to use some apps

### ISSUE THREAD

**Issue by vismittu** [checkra1n/BugTracker#252]
**What device + iOS version are you on?**
iPhone X iOS 13.1.3

**What checkra1n version are you using?**
0.9.2
**What are the steps to reproduce the issue?**
1.Install checkra1n 
2.Open a few apps.
3.Try going back to any one from the recent apps section.
...

**What do you expect, and what is happening instead?**
The app to open. It freezes

**Any other info, error logs, screenshots, ...?** 
This happened to my Whatsapp.

**Comment by RonaldRegister** [comment]
could you provide a list of installed tweaks?

**Comment by vismittu** [comment]
I installed Filza and iCleaner. That’s it.

**Comment by RonaldRegister** [comment]
does it eventually open Whatsapp for example?

Could it be the ios 13 issue where switching between apps, the previous app was killed by memorymanagement, and has to completly reload?

**Comment by vismittu** [comment]
It just doesn’t open until i restart my phone. It stays blank only when jailbroken. It is not the problem in iOS 13.
