### ISSUE TITLE
Stuck at bootlogo after installation is complete

### ISSUE THREAD

**Issue by 0x41c** [checkra1n/BugTracker#254]
**What device + iOS version are you on?**

iPhone 6s iOS 13.2.2
**What checkra1n version are you using?**
(0.9.2)
**What are the steps to reproduce the issue?**
1.do everything normally 
2.
3.
...

**What do you expect, and what is happening instead?**
To boot **Normally**

**Instead*
I get stuck at second boot logo
**Any other info, error logs, screenshots, ...?**

**Comment by egshame** [comment]
Did the phone ever boot fully? I had same issue but finally booted on its own but was without checkra1n

**Comment by 0x41c** [comment]
##
@egshame 
Yeah no it didn’t 
I had to **restore** then rejailbreak 
It really _sucked_
##
