### ISSUE TITLE
Tweaks regarding Color Change

### ISSUE THREAD

**Issue by Shadowedstalker** [checkra1n/BugTracker#256]
So I have tried a few different tweaks that allow for color customization to no avail. they install and other functions of the tweak work, but when I tap to change color nothing happens. I have libcolorpicker and libCSColorpicker installed and still nothing.

Thought this is not an issue for the wonderful Devs of Checkra1n I was hoping some one smarter than myself could point me in the right direction.

**Comment by jacc** [comment]
[r/jailbreak](https://reddit.com/r/jailbreak) is what you're looking for

**Comment by Shadowedstalker** [comment]
Thanks, but no. unless you can point me to a specific post this isn't helpful.

**Comment by jacc** [comment]
[Here's a link that shows both color pickers are not working](https://www.reddit.com/r/jailbreak/comments/dv9e24/discussion_is_libcolorpicker_not_working/). As it says in the checkra1n FAQ most tweaks haven't been updated past iOS 13 so I'd recommend waiting for the developers to update them.

**Comment by Shadowedstalker** [comment]
Thanks helpful and yes I realize that Checkra1n hasn't been out long enough for Dev to update everything. Just though maybe someone had found a workaround.
