### ISSUE TITLE
iMessage Only (No SMS)

### ISSUE THREAD

**Issue by isyweisy** [checkra1n/BugTracker#258]
**What device + iOS version are you on?**
iPhone 6s
iOS 13.2.2
**What checkra1n version are you using?**
0.9.1-0.9.2
**What are the steps to reproduce the issue?**
1. Open the YouTube app
2. Find a video you like
3. Press share
4. Choose messages
5. Choose someone with an android phone
...

**What do you expect, and what is happening instead?**
What I expect is that it will send the message over SMS

What happens is that it tried to send over iMessage but fails because he has never had a iPhone and so it has no iCloud account to go to. I then entered the messages app and tried to send the message manually and it tried iMessage again. I then entered non substrate mode and it still would not work.
**Any other info, error logs, screenshots, ...?**
Respringing fixes the issue until I try to share the link again using the above method.

As a side note, I noticed that the sharing over iMessage window would not obey the system wide dark mode. I haven’t tested this on stock iOS but I can’t imagine that Apple would have missed that.

**Edit:** Images of installed tweaks in a comment below
**Edit 2:** Updated checkra1n and the issue persists

**Comment by Shadowedstalker** [comment]
Does all other Cellular work (phone, safari LTE, ect..)

**Comment by isyweisy** [comment]
Yes, everything else has been pretty functional so far! I’ll let you know if that changes.

**Comment by isyweisy** [comment]
I’ve attached photos of my currently installed tweaks in case you need theme but, as I said, I reproduced the issue is non substrate mode so I don’t think that they are the issue.
![A0464AFD-DC94-4745-B31D-03661FD8D6A3](https://user-images.githubusercontent.com/38620974/68710127-e6915300-058e-11ea-862e-52fd6853f07d.png)
![2DEFA1B3-D435-405B-9FBE-E97DAEDA04C4](https://user-images.githubusercontent.com/38620974/68710128-e6915300-058e-11ea-8f9b-ba8d93d318a5.png)
![0F66F824-B5B3-4BAB-BF34-6B58DCA812CA](https://user-images.githubusercontent.com/38620974/68710134-e729e980-058e-11ea-9b21-a5a0810a3058.png)
![234AFD85-45FE-448B-AEFF-ADA63F32D39B](https://user-images.githubusercontent.com/38620974/68710135-e729e980-058e-11ea-8311-9a91c795192e.png)
![CBD0F2AB-21C1-459B-AF80-808D0471CF77](https://user-images.githubusercontent.com/38620974/68710136-e7c28000-058e-11ea-9acc-c66317580ceb.png)
![305DC476-332D-424E-8655-ECBB51CD41F0](https://user-images.githubusercontent.com/38620974/68710137-e7c28000-058e-11ea-8097-dc0c1d39cf05.png)
![77AC9CB0-85CF-4F4A-A2D4-CC9411E70FB1](https://user-images.githubusercontent.com/38620974/68710138-e7c28000-058e-11ea-95e7-afd6be332556.png)

**Comment by Shadowedstalker** [comment]
i would suggest trying iCleanerPro http://ib.soft.net/cydia

once installed, open the the + at the bottom, open Cydia Substrate addons turn everything off. hit apply. test your messages. if it works go in and turn them on one at a time testing after each. if it is a tweak you can narrow it down to the exact tweak.

**Comment by Shadowedstalker** [comment]
Any luck?

**Comment by isyweisy** [comment]
Hi sorry, I seem to be in a different timezone to you, sorry for the delay. Thanks I’ll try iCleaner, hopefully it works this time.

**Comment by isyweisy** [comment]
Hi, just like last time, iCleaner’s icon would not appear on my desktop and so I could not launch it.

**Comment by Shadowedstalker** [comment]
Ok that is an easy fix. open terminal ssh@root your ip,
default password is alpine
type uicache
it will rebuild your cache.

**Comment by isyweisy** [comment]
Ok thanks, I’m at school at the moment but I will try as soon as I return home and let you know how it goes!

**Comment by isyweisy** [comment]
Hi, I have followed your instructions to disable all substrates with iCleaner. No joy the issue still occurs. I have also updated to checkra1n 0.9.2 where the issue still occurs. I have added 0.9.2 to the initial bug ticket. I can record a video of the steps if you like?

**Comment by isyweisy** [comment]
Mistakes were made. Issues have been fixed. Im sorry that I have been a waste of your time.

**Comment by Shadowedstalker** [comment]
That's that we are all here for to help each other. if you don't mind, what mistakes? what fixed it?

**Comment by isyweisy** [comment]
Oh, I don’t know why but share mode was defaulting to an unrelated number which it was trying to send over iMessage but then using the drop down fixed it. Also I checked up and the share window ignores dark mode on stock as well.
