### ISSUE TITLE
Sub-process dpkg --set-selections returned an error code (2) 

### ISSUE THREAD

**Issue by Emu1342** [checkra1n/BugTracker#270]
**What device + iOS version are you on?**
12.4

**What checkra1n version are you using?**
0.9
**What are the steps to reproduce the issue?**
1. Try and install/upgrade/remove anything
2.  Watch process til “running Debian packager”
3. Error appears. Usually have to respring
...

**What do you expect, and what is happening instead?** to modify/install a file is what I expected. Error is happening instead

**Any other info, error logs, screenshots, ...?**
It’s pretty cut and dry

**Comment by johnwatson122** [comment]
@Emu1342 
Probably your DPKG is corrupted. Did you erase all content and settings or install the electra repo?
