### ISSUE TITLE
iPad 6 Fail to JB

### ISSUE THREAD

**Issue by spiouki** [checkra1n/BugTracker#271]
**What device + iOS version are you on?**
iPad (6th generation)--iOS13.2.2

**What checkra1n version are you using?**
checkra1n 0.9.2 beta — MacOS 10.14 on VMWare pro
**What are the steps to reproduce the issue?**
1. Connect iPad to MacOS 
2. Enter DFU mode
3. Checking if the device is ready (remains on the screen until I disconnect and force out of DFU mode- I have waited for it at least 30minuts)
...

**What do you expect, and what is happening instead?**
Fails to jailbreak 

**Any other info, error logs, screenshots, ...?**
![macOS 10 14-2019-11-12-19-55-36](https://user-images.githubusercontent.com/4134716/68732633-fc9c1500-0588-11ea-926e-401be43d50d6.png)

**Comment by Lonegwadiwaitor** [comment]
https://twitter.com/qwertyoruiopz/status/1192745591878508546

**Comment by spiouki** [comment]
If anyone knows how to remap an entire USB controller via IOMMU to VMware guest please put me on the right track. If I learn I'll make a video tutorial of it and post it here.

Has anyone tried using checkrain on Hackintosh?
Thanks

**Comment by kpwn** [comment]
It should work on a hackintosh but your mileage may vary.

**Comment by woachk** [comment]
VMWare is not supported so closing the issue.
For IOMMU PCIe remapping, use Linux + KVM...
