### ISSUE TITLE
not work with smart keyboard after jailbreak when charging 

### ISSUE THREAD

**Issue by briopapa** [checkra1n/BugTracker#273]
**What device + iOS version are you on?**
ipad pro12.9(2ed)/ios13.1.3

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1.jailbreak 
2.use smart keyboard when charging 
3.smart keyboard doesn't work while charging but work fine while not charging.
...

**What do you expect, and what is happening instead?**

Fix this issue. Non-jailbrake status don't have this issue.
**Any other info, error logs, screenshots, ...?**
No

**Comment by nullpixel** [comment]
closing as a dupe of #48

**Comment by briopapa** [comment]
This issue occurs again on 0.9.5beta
