### ISSUE TITLE
battery drain 

### ISSUE THREAD

**Issue by bluegreen19** [checkra1n/BugTracker#274]
since i jailbroke my iphone, my iphone battery drains soo fast. i dont know if its my phone or jailbreak. when i go to settings and to the battery section it doesnt show what is taking my battery. before i jailbroke my phone it used to work. hope you guys can fix it if its the jailbreak. if not what i should do to fix the problem

**Comment by amishakov** [comment]
Please at first add you tweak list. You can find eztweak list in Cydia

**Comment by Guw0pp** [comment]
Same, disabled every tweak still the same problem and powerlogHelperd daemon keeps on crashing

![75D35B8D-A50D-40E1-A43D-2A197F6BBF2C](https://user-images.githubusercontent.com/57712576/68763032-be9a0200-0617-11ea-8986-649f22121ccd.jpeg)

**Comment by bluegreen19** [comment]
Here is the tweak list on my iPhone 

Sent from my iPhone

>> On Nov 13, 2019, at 01:15, Alex Mishakov <notifications@github.com> wrote:
> ﻿
> Please at first add you tweak list. You can find eztweak list in Cydia
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Tweaks Installed:

7-zip (POSIX) v16.02-1
AppList v1.5.15~beta1
APT v1.8.2-3
APT (apt-key) v1.8.2-1
APT (libapt-pkg) v1.8.2-1
APT 0.7 Transitional (apt-key) v1:0
APT 1.4 Transitional v1:0
APT Strict (lib) v1.8.2-1
Assuan v2.5.1-1
Base Structure v1-5
Berkeley DB v6.2.32-1
BigBoss Icon Set v1.0
Bourne-Again SHell v5.0.3-2
bzip2 v1.0.6-1
CA Certs v0.0.2
ChromaHomeBarX v0.4
ColorMyBattery v1.3.2
Core Utilities v8.31-1
Core Utilities (/bin) v8.31-1
Cydia Installer v1.1.32~b22
Cydia Substrate v0.9.7100~b3
Cydia Translations v1.1.32~b1
Darwin Tools v1.1-1
Debian Packager v1.19.7-1
Debian Utilities v4.8.6-1
Diff Utilities v3.6-1
diskdev-cmds v593.221.1-1
DismissProgress v1.0.3
Essential v0-1
EZTweakList v1.0.1-1
file v5.35-2
Filza File Manager v3.6.4
Find Utilities v4.6.0-2
gettext v0.19.8-1
GNU Cryptography v1.8.3-1
GNU Multiple Precision Arithmetic Library v6.1.2-1
GnuPG v2.2.11-2
GnuPG Errors v1.32-1
GnuTLS v3.5.19-1
grep v3.1-1
gzip v1.9-1
HideYourApps v1.2.1
iCleaner Pro v7.7.5
iOS Firmware v13.2.2
iPhone Firmware (/sbin) v0-1
Kiiimo Repo Icons v12.6
KSBA v1.3.5-1
libcolorpicker v1.6.4
Liberty Lite (Beta) v0.2.12
libidn2 v6.1.2-1
libplist v2.0.0-2
libtasn1 v4.13-1
libunistring v0.9.10-1
Link Identity Editor v2:2.1.1+elucubratus2
LocalIAPStore v1.4-2
LZ4 v1.7.5-1
LZMA Utils v2:4.32.7-2
MTerminal v1.4-6
Nettle v3.4.1-1
New Curses v5.9-1
New Curses v6.1-1
New GNU Portable Threads v1.6-1
NudeKeys (iOS 12) v1.0.0~b8
OpenSSH v7.9p1-3
OpenSSL 1.0 Libraries v1.0.2s-1
p11-kit v0.23.12-1
PowerApp v4.4.0
PreferenceLoader v2.2.4~beta1
Profile Directory v0-1
PullToRespring v1.2
readline v8.0-1
ReProvision v0.5~experimental3
RocketBootstrap v1.0.7~beta3
rsync v3.1.3-2
sed v4.5-1
shell-cmds v118-8
Snappy v1.2
Substrate Safe Mode v0.9.6003
Succession v1.4.3
system-cmds v790.30.1-2
Tape Archive v1.30-2
UIKit Tools v1.1.15-2
unrar v5.6.4-1
unzip v6.0+deb9u1-1
wget v1.19.5-2
XZ Utils v5.2.4-4
Zebra (BETA) v1.0~beta2
zip v2.32-1

**Comment by nullpixel** [comment]
Not a checkra1n issue

**Comment by bluegreen19** [comment]
Then what can I do to fix the issue? If it’s not the checkra1n
