### ISSUE TITLE
Mobile Network not working.

### ISSUE THREAD

**Issue by vismittu** [checkra1n/BugTracker#275]
**What device + iOS version are you on?**
iPhone X iOS 13.1.3

**What checkra1n version are you using?**
0.9.2
**What are the steps to reproduce the issue?**
1.Install checkra1n and cydia
2.try using the device with mobile network.
3.
...

**What do you expect, and what is happening instead?**
I expected to use my device normally but i am unable to use the mobile data and make calls and also unable to receive calls or messages.

**Any other info, error logs, screenshots, ...?** I am from India.

**Comment by nullpixel** [comment]
could you let us know if 0.9.5 fixes these issues?

**Comment by vismittu** [comment]
Yeah sure! I’ll get back to you tomorrow as i am travelling and I don’t have my notebook with me at the moment. Thank you!

**Comment by nullpixel** [comment]
thank you! :)

**Comment by vismittu** [comment]
It is fixed now. I just got my device jailbroken again and everything works great. Thank you!

**Comment by djjoe123-tech** [comment]
sorry someone could solve activating mobile data or incoming calls?

**Comment by vismittu** [comment]
Rejailbreak with the latest checkra1n beta and try. This worked for me.

**Comment by djjoe123-tech** [comment]
friend, some other solution I have jailbroken again and still nothing I can use mobile data and much less make calls
