### ISSUE TITLE
Home screen not responding to touch.

### ISSUE THREAD

**Issue by vismittu** [checkra1n/BugTracker#276]
**What device + iOS version are you on?**

iPhone X iOS 13.1.3
**What checkra1n version are you using?**
0.9.2
**What are the steps to reproduce the issue?**
1.After installing both checkra1n and cydia 
2.respring the device
3.try using the device now.
...

**What do you expect, and what is happening instead?**
The screen should be responding to my touch but it remains unresponsive until i touch the dock are and the screen kind of kills some task and the touch works fine now.

**Any other info, error logs, screenshots, ...?**

**Comment by woachk** [comment]
Which tweaks do you use?

**Comment by vismittu** [comment]
None. Just installed filza and icleaner on my device.

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.
