### ISSUE TITLE
Can't open DMG on macOS 10.10

### ISSUE THREAD

**Issue by Baselk52** [checkra1n/BugTracker#28]
**What device + iOS version are you on?**
macbook air mid 2011 (osx 10.10)
iphone 7+ 13.1.1
**What are the steps to reproduce the issue?**
1.open dmg file
2.
3.
...

**What do you expect, and what is happening instead?**
the dmg runs and the tool show up

**Any other info, error logs, screenshots, ...?**
![Screen Shot 2019-11-10 at 4 20 10 PM](https://user-images.githubusercontent.com/57593341/68545459-029dc480-03d6-11ea-9484-69bb7bf89d6f.png)

**Comment by nullpixel** [comment]
Hi -- seems like your download is corrupted, could you try downloading it again?

**Comment by Baselk52** [comment]
sure, but is osx 10.10 supported to lunch checkra1n ?

**Comment by youran1314** [comment]
same

**Comment by luapp** [comment]
Me to !
iPhone 8 + 13.2

**Comment by nullpixel** [comment]
What macOS version are you running?

**Comment by luapp** [comment]
It is a very old mac
10.6.8

**Comment by nullpixel** [comment]
Hi, you need to update checkra1n to update to use checkra1n. @Creator-360

**Comment by nullpixel** [comment]
Our minimum supported macOS is 10.10 so I'll reopen this issue as I believe it's due to our compression not being supported on that version.

**Comment by luapp** [comment]
ok thanks

**Comment by ishsed** [comment]
Having the same problem can't open DMG Mac osx 10.10.5

**Comment by Rechart41** [comment]
Same problem 10.9

**Comment by nullpixel** [comment]
@Rechart41 macOS 10.9 is not supported by checkra1n, sorry.

**Comment by Keter** [comment]
Same problem here OSX 10.10.5

**Comment by B3NT03** [comment]
so is the file just corrupted on the website or is my mac not compatible

**Comment by nova9575** [comment]
Same here i have downloaded checkra1n 10 times and still saying the same
![C51A3CD1-C078-4045-84A6-F6180BCA9D4A](https://user-images.githubusercontent.com/57633323/68601781-f2045180-049c-11ea-8cba-b27417bee6f8.jpeg)

**Comment by Keter** [comment]
> Same here i have downloaded checkra1n 10 times and still saying the same
> ![C51A3CD1-C078-4045-84A6-F6180BCA9D4A](https://user-images.githubusercontent.com/57633323/68601781-f2045180-049c-11ea-8cba-b27417bee6f8.jpeg)

Had the same issue, updated my macOS from 10.10.5 to 10.11.6, now it's working just fine.

**Comment by nullpixel** [comment]
This issue with the DMGs on macOS 10.10 has been fixed in 0.9.2, which is available at https://checkra.in.
