### ISSUE TITLE
no tweak injection

### ISSUE THREAD

**Issue by crazytechkid** [checkra1n/BugTracker#281]
i have tried multiple versions of check rain and have went through many system restores  as well as rejailbreaking  my device with each check rain releses the jailbreak process runs normally the check rain app does load and cydia is openable but after installing tweaks they dont load into the springboard and the prefrences dont load. i am running ios 13.2.2 on an iphone X check rain did work at some point but it just randomly stopped working and i started expiernceing these issues

**Comment by Shadowedstalker** [comment]
The apps not appearing on the homescreen is due to a a cache issue. Open Terminal 
type ssh root@your ip
default password is alpine
type uicache hit enter  Your icons should appear.

now the preferences, first open Cydia, Open Checkra1n source is it empty or do you see Cydia Substrate?

If it is empty clear out your sources, except the main sources. a number of us have face this and found it to be the solution. if it works you can add the sources back one by one until you find out what is causing it.

**Comment by Shadowedstalker** [comment]
Also make sure you have installed PreferenceLoader via http://rpetri.ch/repo/

**Comment by fhc5326** [comment]
> The apps not appearing on the homescreen is due to a a cache issue. Open Terminal
> type ssh@root your ip
> default password is alpine
> type uicache hit enter Your icons should appear.
> 
> now the preferences, first open Cydia, Open Checkra1n source is it empty or do you see Cydia Substrate?
> 
> If it is empty clear out your sources, except the main sources. a number of us have face this and found it to be the solution. if it works you can add the sources back one by one until you find out what is causing it.

Hello there, I'm facing this problem,too.
But I can see Checkra1n source and Cydia Substrate.

**Comment by Shadowedstalker** [comment]
@fhc5326 Which problem are you referencing? The missing icons or Missing settings?

**Comment by fhc5326** [comment]
Missing icons after I install tweaks, and I have to run uicache.

**Comment by Shadowedstalker** [comment]
From early post I was typing too fast and messed up the SSH

it's ssh root@yourIP.

I corrected it above.

**Comment by Shadowedstalker** [comment]
The apps not appearing on the homescreen is due to a a cache issue. Open Terminal
type ssh root@your ip
default password is alpine
type uicache hit enter Your icons should appear.

will fix it.

**Comment by Shadowedstalker** [comment]
Any problems, let me know, or if you are unfamiliar with sshing.

**Comment by fhc5326** [comment]
I know, but I can't always do this...
because some user is lazy, you know.

**Comment by Shadowedstalker** [comment]
Well a solution to that is install NewTerm 2 (mobile Terminal)

you may have to uicache it on the Mac once, but after you get NewTerm 2 you can open it and type uicache right on the phone.

**Comment by Shadowedstalker** [comment]
I have only had to rebuild the cache maybe twice.

**Comment by Mrcoolawesome** [comment]
I still cannot use my tweaks or see the contents of the Checkra1n substrate, I did what you said and I also got rid of all the other sources. Everything was fine until I updated some tweaks and then none of my tweaks would load, I unjailbraked and jailbroke several times but still nothing. Please help

**Comment by Shadowedstalker** [comment]
@crazytechkid Were you able to fix it following my instructions?

If So you should Close the Thread
