### ISSUE TITLE
Touch ID not functional

### ISSUE THREAD

**Issue by paz** [checkra1n/BugTracker#282]
**What device + iOS version are you on?**
iPhone 6s, 13.2.2

**What checkra1n version are you using?**
0.9.2 beta
**What are the steps to reproduce the issue?**
1. Jailbreak
2. Use any app with Touch ID locking functionality
3. There is no prompt
...

**What do you expect, and what is happening instead?**
The touch ID prompt is missing, and not just hidden. You cannot use Touch ID functionality.
Unlocking your phone and using the app store/in app purchases still works.

**Any other info, error logs, screenshots, ...?**
No, sorry.

**Comment by mrcm311** [comment]
> **What device + iOS version are you on?**
> iPhone 6s, 13.2.2
> 
> **What checkra1n version are you using?**
> 0.9.2 beta
> **What are the steps to reproduce the issue?**
> 
> 1. Jailbreak
> 2. Use any app with Touch ID locking functionality
> 3. There is no prompt
>    ...
> 
> **What do you expect, and what is happening instead?**
> The touch ID prompt is missing, and not just hidden. You cannot use Touch ID functionality.
> Unlocking your phone and using the app store/in app purchases still works.
> 
> **Any other info, error logs, screenshots, ...?**
> No, sorry.

iPhone 8 Plus same issue Touch ID not having the click feeling but all other functionality is working fine , going to home screen , opening background app switcher

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.
