### ISSUE TITLE
[Feature Request] Allowed user to restore rootfs without internet

### ISSUE THREAD

**Issue by Halo-Michael** [checkra1n/BugTracker#283]
I don’t know why Loder must exit without Internel. Is restore rootfs need internel?

**Comment by nullpixel** [comment]
Could you let us know what you mean by this?

**Comment by Halo-Michael** [comment]
> Could you let us know what you mean by this?

When users offline, Loader will told the user “I’m offline” then exit.
But what if the user just want Restore Rootfs instead of install package managers? Then he must online first. But this is totally unnecessary. I think you didn't take this into consideration.

**Comment by Mikagreat** [comment]
> 
> 
> Could you let us know what you mean by this?

Please help to confirm if the Internet is necessary for rootfs restore, due to the Internet is requested while we try to restore rootfs by **checkra1n loader**. Thanks for you great works!
Best Regards,
M1ka

**Comment by nullpixel** [comment]
Fixed in checkra1n 0.9.8
