### ISSUE TITLE
0.9.3 Battery Status Issue

### ISSUE THREAD

**Issue by IDAoADI** [checkra1n/BugTracker#285]
**What device + iOS version are you on?**
iPhone X(10,3) iOS 13.2.2

**What checkra1n version are you using?**
0.9.3

**What are the steps to reproduce the issue?**
1. Jailbreak using checkra1n
2. Goto settings>battery
3. Doesn't load
...

**What do you expect, and what is happening instead?**
I expected the battery-per-app usage stats to load, they did not.

**Any other info, error logs, screenshots, ...?**
It works when in a normal state, 0.9.3 says that it is fixed when it is not.

**Comment by opa334** [comment]
Same here! Also on checkra1n 0.9.3 / iPhone X 13.2.2.

**Comment by Guw0pp** [comment]
Same still not working 0.9.3 / iPhone X 13.2.2

**Comment by Shadowedstalker** [comment]
I too have/had this issue. 

Solution (if you have SpringPlus 11 installed):  install iCleanerPro http://ib-soft.net/cydia/
lower Left side hit + open Cydia Substrate Addons
scroll down turn off SpringPlus 11, Hit apply. Hit yes when it asks about respringing.

Check your battery info.

**Comment by Shadowedstalker** [comment]
You can reverse the processor and keep SpringPlus and just do the process over again to check or uninstall SpringPlus.

**Comment by d8vedmg** [comment]
Yea...issue still persist after this new release.

**Comment by Shadowedstalker** [comment]
Do you have SpringPlus?

**Comment by Guw0pp** [comment]
0.9 - 0.9.2 battery status in settings wont show at all even after turning off all tweaks with iCleaner. 0.9.3 turning off all tweaks with iCleaner solves this issue tried few tweaks, eclipse is also a culprit just curious are these tweaks hooking UIView ? Maybe there’s an issue with this I’m a noob when it comes to this don’t hate me if I’m wrong pls it’s definitely something causing this stock works fine

**Comment by Shadowedstalker** [comment]
No Hate, that's why we are here to help others. One thing people need to remember is these tweaks weren't designed for iOS 13, Checkra1n hasn't been out long enough for the devs to update.

**Comment by d8vedmg** [comment]
> Do you have SpringPlus?

Spent over two hours on iCleaner toggling off tweaks and on. Makes no difference. Sometimes it will work and sometimes it just flat out doesn’t.

**Comment by kratos9394** [comment]
0.9.3.2，same problem，battery setting loading

**Comment by Shadowedstalker** [comment]
> Spent over two hours on iCleaner toggling off tweaks and on. Makes no difference. Sometimes it will work and sometimes it just flat out doesn’t.

You may have to uninstall all tweaks and "system restore" then reload your tweaks one at a time checking.

**Comment by Shadowedstalker** [comment]
@kratos9394  as mentioned in your other post, have you viewed #301?

**Comment by d8vedmg** [comment]
> > Spent over two hours on iCleaner toggling off tweaks and on. Makes no difference. Sometimes it will work and sometimes it just flat out doesn’t.
> 
> You may have to uninstall all tweaks and "system restore" then reload your tweaks one at a time checking.

Spent a day prior doing just that. Restoring system. Installing tweaks one but one. Checking one after another. Then when one tweak causes it to not load usage. Uninstall and it still doesn’t work. It got too frustrating.

**Comment by Shadowedstalker** [comment]
Remember Checkra1n hasn't been out that long and the Devs haven't had time to update the tweaks for iOS 13.

**Comment by d8vedmg** [comment]
> Remember Checkra1n hasn't been out that long and the Devs haven't had time to update the tweaks for iOS 13.

I realize that and it’s in beta for a reason. I’m not complaining either, this is just I guess...commenting about the issue and sharing.

**Comment by Shadowedstalker** [comment]
I understand that and that's what help us help you.

**Comment by abduuu007** [comment]
Here are my findings after spending a day n half.

- Cercube
- Cr4shed
- ExactTimeMessages
- HomePlusBeta (Latest)
- MiscSettings
- NotToday13
- NudeKeys (iOS 12)
- PreferenceOrganizer 2
- PullToRespring
- LetMeBlock
- libSparkAppList

These tweaks have caused my Battery status to freeze/not show up. Your tweak list could vary.

**Comment by nullpixel** [comment]
this is an issue with tweaks you have installed.
