### ISSUE TITLE
same non responsive screen 

### ISSUE THREAD

**Issue by mrcm311** [checkra1n/BugTracker#287]
**What device + iOS version are you on?**
iPhone X iOS 13.2.2

**What checkra1n version are you using?**
0.9.3
**What are the steps to reproduce the issue?**
1. DFU
2. CLICK NEXT 
3. DEVICE BOOTS UP AND SCREEN BECOMES NON RESPONSIVE 
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**
 I HAVE A VIDEO

**Comment by scuty2000** [comment]
same problem, still have unresponsive screen on checkra1n 0.9.3. Also tried booting in safe mode.

**Comment by mrcm311** [comment]
> same problem, still have unresponsive screen on checkra1n 0.9.3. Also tried booting in safe mode.

yeah idk what to do. I see they added a verbose boot option but idk what that does

**Comment by gurkentier** [comment]
Confirm the same issue, have more issues with 0.9.3 than with 0.9.2

**Comment by scuty2000** [comment]
> **What device + iOS version are you on?**
> iPhone X iOS 13.2.2
> 
> **What checkra1n version are you using?**
> 0.9.3
> **What are the steps to reproduce the issue?**
> 
> 1. DFU
> 2. CLICK NEXT
> 3. DEVICE BOOTS UP AND SCREEN BECOMES NON RESPONSIVE
>    ...
> 
> **What do you expect, and what is happening instead?**
> 
> **Any other info, error logs, screenshots, ...?**
> I HAVE A VIDEO

To temporary fix the issue, if you jailbreak after a first jailbreak (like you're on unresponsive screen and go straight to DFU not using recovery mode) the touch functionality comes back

**Comment by mrcm311** [comment]
> > **What device + iOS version are you on?**
> > iPhone X iOS 13.2.2
> > **What checkra1n version are you using?**
> > 0.9.3
> > **What are the steps to reproduce the issue?**
> > 
> > 1. DFU
> > 2. CLICK NEXT
> > 3. DEVICE BOOTS UP AND SCREEN BECOMES NON RESPONSIVE
> >    ...
> > 
> > **What do you expect, and what is happening instead?**
> > **Any other info, error logs, screenshots, ...?**
> > I HAVE A VIDEO
> 
> To temporary fix the issue, if you jailbreak after a first jailbreak (like you're on unresponsive screen and go straight to DFU not using recovery mode) the touch functionality comes back

wow that actually worked but now when I come back to home screen message popped up saying faceid not working and there's no checkra1n app for me open and install Cydia !

**Comment by scuty2000** [comment]
> > > **What device + iOS version are you on?**
> > > iPhone X iOS 13.2.2
> > > **What checkra1n version are you using?**
> > > 0.9.3
> > > **What are the steps to reproduce the issue?**
> > > 
> > > 1. DFU
> > > 2. CLICK NEXT
> > > 3. DEVICE BOOTS UP AND SCREEN BECOMES NON RESPONSIVE
> > >    ...
> > > 
> > > **What do you expect, and what is happening instead?**
> > > **Any other info, error logs, screenshots, ...?**
> > > I HAVE A VIDEO
> > 
> > 
> > To temporary fix the issue, if you jailbreak after a first jailbreak (like you're on unresponsive screen and go straight to DFU not using recovery mode) the touch functionality comes back
> 
> wow that actually worked but now when I come back to home screen message popped up saying faceid not working and there's no checkra1n app for me open and install Cydia !

faceid not working is a known issue, but the app not showing is not. Try repeating everything from the begin

**Comment by mrcm311** [comment]
just did everything from the beginning and same thing. no checkra1n app is to be found after redoing it on Dfu mode from non responsive lock screen

**Comment by scuty2000** [comment]
> just did everything from the beginning and same thing. no checkra1n app is to be found after redoing it on Dfu mode from non responsive lock screen

idk what to tell you, try using 0.9.2

**Comment by mrcm311** [comment]
> > just did everything from the beginning and same thing. no checkra1n app is to be found after redoing it on Dfu mode from non responsive lock screen
> 
> idk what to tell you, try using 0.9.2

its all good. I appreciate your help !! just have to wait for 0.9.4

**Comment by HeyItsMicro** [comment]
> same problem, still have unresponsive screen on checkra1n 0.9.3. Also tried booting in safe mode.

ive tried safe mode as well and still the same issue from 0.9.2 persists

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.

**Comment by HeyItsMicro** [comment]
can confirm it does, thanks!
