### ISSUE TITLE
Battery not loading iphone x

### ISSUE THREAD

**Issue by jonatansuarez1208** [checkra1n/BugTracker#288]
**What device + iOS version are you on?**
IPHONE X

**What checkra1n version are you using?**
0.9.3
**What are the steps to reproduce the issue?**
1. Battery graph is not loading 

2.
3.
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**
![EJRitTVXsAA7ROR](https://user-images.githubusercontent.com/46586683/68794906-81cd0b80-0615-11ea-8796-e9f6d42a43e4.jpg)

**Comment by scuty2000** [comment]
iOS version?

**Comment by jonatansuarez1208** [comment]
sorry forgot to mention

13.2.2  iphone x huge battery problems

deamon powerlogHelperd keeps crashing and crashing and huge battery drain
________________________________
De: Luca Scutigliani <notifications@github.com>
Enviado: miércoles, 13 de noviembre de 2019 01:34 p. m.
Para: checkra1n/BugTracker <BugTracker@noreply.github.com>
CC: jonatansuarez1208 <jonatansuarez@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [checkra1n/BugTracker] Battery not loading iphone x (#288)


iOS version?

**Comment by jonatansuarez1208** [comment]
> iOS version?
sorry forgot to mention 

13.2.2  iphone x huge battery problems

deamon powerlogHelperd keeps crashing and crashing and huge battery drain

**Comment by scuty2000** [comment]
> sorry forgot to mention 13.2.2 iphone x huge battery problems deamon powerlogHelperd keeps crashing and crashing and huge battery drain
> […](#)

Already tried safe mode? What about restoring via iTunes? I'm on the same device/iOS combo and have no issue on battery (instead I have broken Face ID)

**Comment by jonatansuarez1208** [comment]
> > sorry forgot to mention 13.2.2 iphone x huge battery problems deamon powerlogHelperd keeps crashing and crashing and huge battery drain
> > […](#)
> 
> Already tried safe mode? What about restoring via iTunes? I'm on the same device/iOS combo and have no issue on battery (instead I have broken Face ID)

well actually i did restored as clean via itunes when i switch from 12.4 to 13.2.2 this is the second time i do it, and same problem,  the issue is when is in a jailbroken state if im in stock ios battery looks good.

**Comment by jonatansuarez1208** [comment]
looking at cocoatop powerlogHelperd keeps crashing and crashing so i guess is because of that... im gonna rename that process to stop the battery drain.  want to mention after unloading all tweaks now battery is showing i need to check if its a tweak that is causing this....

**Comment by jonatansuarez1208** [comment]
> > sorry forgot to mention 13.2.2 iphone x huge battery problems deamon powerlogHelperd keeps crashing and crashing and huge battery drain
> > […](#)
> 
> Already tried safe mode? What about restoring via iTunes? I'm on the same device/iOS combo and have no issue on battery (instead I have broken Face ID)

looking at cocoatop powerlogHelperd keeps crashing and crashing so i guess is because of that... im gonna rename that process to stop the battery drain. want to mention after unloading all tweaks now battery is showing i need to check if its a tweak that is causing this....

**Comment by Shadowedstalker** [comment]
I too have/had this issue.

Solution (if you have SpringPlus 11 installed): install iCleanerPro http://ib-soft.net/cydia/
lower Left side hit + open Cydia Substrate Addons
scroll down turn off SpringPlus 11, Hit apply. Hit yes when it asks about respringing.

Check your battery info.

You can reverse the processor and keep SpringPlus and just do the process over again to check or uninstall SpringPlus.

**Comment by jonatansuarez1208** [comment]
> I too have/had this issue.
> 
> Solution (if you have SpringPlus 11 installed): install iCleanerPro http://ib-soft.net/cydia/
> lower Left side hit + open Cydia Substrate Addons
> scroll down turn off SpringPlus 11, Hit apply. Hit yes when it asks about respringing.
> 
> Check your battery info.
> 
> You can reverse the processor and keep SpringPlus and just do the process over again to check or uninstall SpringPlus.

i dont use springPlus.. any other tweak?

**Comment by Shadowedstalker** [comment]
> i dont use springPlus.. any other tweak?

I would still install iCleanerPro and instead of disabling SpringPlus(which you said you don't have) disable all and check, then turn them on one by one rechecking after each. Follow the above instructions for iCleanerPro if you are unfamiliar with it.

**Comment by jonatansuarez1208** [comment]
> I too have/had this issue.
> 
> Solution (if you have SpringPlus 11 installed): install iCleanerPro http://ib-soft.net/cydia/
> lower Left side hit + open Cydia Substrate Addons
> scroll down turn off SpringPlus 11, Hit apply. Hit yes when it asks about respringing.
> 
> Check your battery info.
> 
> You can reverse the processor and keep SpringPlus and just do the process over again to check or uninstall SpringPlus.

found the issue its / . eclipse 12 and noctis neo

**Comment by jonatansuarez1208** [comment]
> > i dont use springPlus.. any other tweak?
> 
> I would still install iCleanerPro and instead of disabling SpringPlus(which you said you don't have) disable all and check, then turn them on one by one rechecking after each. Follow the above instructions for iCleanerPro if you are unfamiliar with it.

yes im doing that

**Comment by jonatansuarez1208** [comment]
> > i dont use springPlus.. any other tweak?
> 
> I would still install iCleanerPro and instead of disabling SpringPlus(which you said you don't have) disable all and check, then turn them on one by one rechecking after each. Follow the above instructions for iCleanerPro if you are unfamiliar with it.


cyder / darkkeysXII / libfoxfortsplash so far are the ones causing that testing more......

**Comment by Shadowedstalker** [comment]
I created an open ticket to help other and I will add these to the list of known causes.

**Comment by Shadowedstalker** [comment]
Ticket #301

**Comment by jonatansuarez1208** [comment]
> I created an open ticket to help other and I will add these to the list of known causes.

nobigtitlescydia / nobreadcrum13 / noctis neo / nolargetitles still testing have few more give me sometime to remove all of them and will confirm the complete list...

**Comment by jonatansuarez1208** [comment]
> Ticket #301

nomoresmallapps / reddit no ads / resetCPU fix / pureinstagram / shuffle / shadow / shuffle / speed intensifier rocketboostrap  / realcc almost done will let you know   //// .  you know what i notice something weird.. after launching the settings app battery shows then i kill the battery graphs and open it again and now its not working again sometimes it opens it and sometime it doesnt

**Comment by jonatansuarez1208** [comment]
going to start all over again something is not working.....

**Comment by jonatansuarez1208** [comment]
> Ticket #301

going to start all over again something is not working.....

**Comment by Shadowedstalker** [comment]
Are you doing it one by one and checking? Because I have Real CC and Shuffle, and both working smooth.

**Comment by jonatansuarez1208** [comment]
> Are you doing it one by one and checking? Because I have Real CC and Shuffle, and both working smooth.

yes, thats why i started again to confirm what is going on....

**Comment by jonatansuarez1208** [comment]
> Are you doing it one by one and checking? Because I have Real CC and Shuffle, and both working smooth.

seems i cant find the issue, im thinking maybe is an issue with my settings app... cause i disable tweaks and starts to work then i enable 1 and stop working, then enable the one that is working and now graphs stops to show again

**Comment by jonatansuarez1208** [comment]
> Are you doing it one by one and checking? Because I have Real CC and Shuffle, and both working smooth.

i think im going to do a fresh restore and then install one by one and see where is the issue, if its something related to the ios13.2.2. what version are you in? maybe is the ios.. dunno

**Comment by Shadowedstalker** [comment]
13.1.2. keep me updated and I will try to help and update the ticket I created to help others.

**Comment by jonatansuarez1208** [comment]
> 13.1.2. keep me updated and I will try to help and update the ticket I created to help others.

ok im gonna futurerestore to ios13.1.2 will let you know and my findings. and test if having the same problem again

**Comment by jonatansuarez1208** [comment]
> 13.1.2. keep me updated and I will try to help and update the ticket I created to help others.

is that version the one that had issues with few weeks back?

**Comment by Shadowedstalker** [comment]
In the meantime you should close the tread.

**Comment by Shadowedstalker** [comment]
I have had no issues. with the 3.1.2 itself.

**Comment by jonatansuarez1208** [comment]
> In the meantime you should close the tread.

just close the one that says close at the bottom?

**Comment by Shadowedstalker** [comment]
yes, close the issue and do the testing. I can still see what you type.

**Comment by jonatansuarez1208** [comment]
> yes, close the issue and do the testing. I can still see what you type.
ok then will do ill be back with my findings thanks...

**Comment by Shadowedstalker** [comment]
Now it's off the Open issues, which makes it easier for other to help others.

**Comment by Shadowedstalker** [comment]
How is it going? have you been successful?

**Comment by jonatansuarez1208** [comment]
> How is it going? have you been successful?

just complete the futurerestore process to ios13.1.2 and setting up my phone now

**Comment by jonatansuarez1208** [comment]
> How is it going? have you been successful?

started to install my tweaks and will let you know if i found something, i will report back in a few hours on my way to work will continue there will report back
