### ISSUE TITLE
checkra1n app doesn't open

### ISSUE THREAD

**Issue by riki2002** [checkra1n/BugTracker#289]
**What device + iOS version are you on?**
I'm using an iphone 7 with ios 13.2.2

**What checkra1n version are you using?**
0.9.3
**What are the steps to reproduce the issue?**
1. instal checkra1n normaly
2.open the checkra1n app
3.app crashes
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by scuty2000** [comment]
deleting and re-installing the app works fine.

**Comment by riki2002** [comment]
Thank you, it worked 

Inviato da iPhone

**Comment by scuty2000** [comment]
Ah bella, sei italiano, chiedi l'issue così non ti picchiano.

En: Oh nice, you're Italian. Close the issue, so they don't kill you.

**Comment by riki2002** [comment]
Ok grazie del consiglio 😂

Inviato da iPhone
