### ISSUE TITLE
iPad Air (1st gen) doesn't work with GUI

### ISSUE THREAD

**Issue by lgariv** [checkra1n/BugTracker#292]
**What device + iOS version are you on?**
iPad Air (1st gen)
iOS 12.4.3

**What checkra1n version are you using?**
0.9.2

**What are the steps to reproduce the issue?**
1. Connect the iPad already in DFU mode
2. press start
3. it *will* boot with the checkra1n app, will installs Cydia, but Cydia says some things needs update, update won't work and can't install any tweaks - Cydia gives an error (something about dpkg, sub process, error 2).

The funny thing is, that when installing via Terminal it doesn't give any error during the installation process.

if I connect the iPad to the GUI in normal mode: it get stuck on the apple logo while trying to boot to recovery for about 5 minutes, then it boots normally. then the GUI says to try again, I click next and it boots successfully to recovery mode - but then the GUI's next button is greyed out (it doe says "Device is now in recovery mode".

If I try to connect the iPad to the GUI in recovery mode, nothing happens when I press the start button.

**What do you expect, and what is happening instead?**
Obviously, I didn't expected it to work perfectly because of the fact that support for this device is experimental.

**Comment by jhakie** [comment]
I'm using checkra1n with an ipad air as well.  If I start in normal mode, ipad boots to DFU and app recognises it's in recovery mode but next button is grayed out.  If I try with ipad already in recovery the start button does nothing.

**Comment by nikias** [comment]
Ok someone forgot to add the iPad Air mapping for the UI. Will be fixed in the next release.

**Comment by jhakie** [comment]
I tryed again with .9.6.  Still the same.
    On Sunday, December 1, 2019, 08:34:32 PM EST, Nikias Bassen <notifications@github.com> wrote:  
 
 
Ok someone forgot to add the iPad Air mapping for the UI. Will be fixed in the next release.

**Comment by HECTICO2412** [comment]
ANY UPDATE?

**Comment by HECTICO2412** [comment]
Done!!!! ..
Just do this> turn off the ipad, put it in restore mode .. put it in DFU mode ... Run Checkra1n in CLI mode (see images) .... and voila .. ready to bypass !!!! It took me almost the day but I got it !!!

![checkra1n-show-package-contents-1](https://user-images.githubusercontent.com/58675775/70407697-591d1380-1a13-11ea-8fbb-de25b67ba5f6.jpg)
![checkra1n-hidden-gui](https://user-images.githubusercontent.com/58675775/70407683-4d315180-1a13-11ea-97a7-8a751ce4bac8.jpg)

**Comment by Siguza** [comment]
Should be fixed in 0.9.7.
