### ISSUE TITLE
Still no fast charging iPhone X 0.9.3 beta

### ISSUE THREAD

**Issue by tpljeron** [checkra1n/BugTracker#295]
**What device + iOS version are you on?**
13.2.2

**What checkra1n version are you using?**
0.9.3

**What are the steps to reproduce the issue?**
1. Checkra1n boot
2. Connect fast charger
3.
...

**What do you expect, and what is happening instead?**
When I turn on my phone without checkra1n jb, it's fast charging (two times charge sound and vibrating). After checkra1n jb, it's just vibrating once and it's not fast charging. After a reboot, fast charging is working fine. Same issue with 0.9.2 beta.

**Any other info, error logs, screenshots, ...?**

**Comment by YUPPUN** [comment]
I have too this issue
System info show 7W Max charging on 30W Power Delivery charger.
iPX 256GB Global 13.2.2 / 0.9.3 Beta

**Comment by tpljeron** [comment]
Fixed in 0.9.3.2 :)!

**Comment by YUPPUN** [comment]
> Fixed in 0.9.3.2 :)!

thx
