### ISSUE TITLE
Signed out of apple after 0.9.3 update

### ISSUE THREAD

**Issue by asislife20** [checkra1n/BugTracker#296]
**What device + iOS version are you on?**
iPad 7,11 IOS13.2

**What checkra1n version are you using?**
0.9.3
**What are the steps to reproduce the issue?**
1.jailbreak with checkra1n 
2.tried to check my email but all accounts were gone. 
3.checked settings and iPad was also signed out of all Apple services. 
...

**What do you expect, and what is happening instead?**
Not to have to enter my information again, but I had to. 

**Any other info, error logs, screenshots, ...?**
After the first boot with 0.9.3 device froze, so I had to re boot, and that's when I noticed the issues.

**Comment by 4rtz1z** [comment]
Happened to my iPad Pro 10,5 Wifi (iPadOS 13.2.2) too, with 0.9.3 and 0.9.3.2 apple id being signed out while jailbroken, but after re-jb with 0.9.2 it doesn't signed out

**Comment by nullpixel** [comment]
0.9.5 fixes these issues.
