### ISSUE TITLE
Taptic Engine and Volume Buttons not working 

### ISSUE THREAD

**Issue by gurkentier** [checkra1n/BugTracker#297]
**What device + iOS version are you on?**
iPhone 8 13.2.2

**What checkra1n version are you using?**
0.9.3

**What are the steps to reproduce the issue?**
1. Set device into DFU mode 
2. Use checkra1n
3. Taptic Engine and volume Buttons Not working
...

**What do you expect, and what is happening instead?**
Taptic Engine and volume buttons not working while hard reset is still working

**Any other info, error logs, screenshots, ...?**

**Comment by gurkentier** [comment]
In addition the Sound is Not working at all. Cannot take any screenshots. WhatsApp is Not starting anymore.

**Comment by nullpixel** [comment]
Is this fixed with 0.9.3.2?

**Comment by gurkentier** [comment]
If fixed it using the checkra1n instructions on entering DFU mode. Will test 0.9.3.2 soon

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.
