### ISSUE TITLE
Cydia won’t open after a little bit and have to restart

### ISSUE THREAD

**Issue by Contonion** [checkra1n/BugTracker#299]
**What device + iOS version are you on?**
13.2.2

**What checkra1n version are you using?**
0.9.3
**What are the steps to reproduce the issue?**
1.  Install Cydia 
2. Wait a bit
3.
...

**What do you expect, and what is happening instead?**
Cydia to open whenever

**Any other info, error logs, screenshots, ...?**
I love the jailbreak so far :)

**Comment by Contonion** [comment]
Also iPhone X

**Comment by Shadowedstalker** [comment]
Cydia crashing and won't open..

ssh into your phone go to /var/mobile/Library/Cydia and delete metadata.cb0 . Cydia will open. reinstall tweaks.

**Comment by Contonion** [comment]
Thanks! I will try that when I get home!
