### ISSUE TITLE
iPhone X China no internet connection

### ISSUE THREAD

**Issue by marcos1** [checkra1n/BugTracker#3]
**What device + iOS version are you on?**
13.2.2

**What are the steps to reproduce the issue?**
1. First Install
2.
3.
...

**What do you expect, and what is happening instead?**
iPhones from China require you to grant permission for any app to access the internet.
you get an error saying can't access the internet and their is not option to allow the app to access the internet. (NOT A VPN ISSUE)

**Any other info, error logs, screenshots, ...?**

**Comment by lone-wolf-akela** [comment]
I believe this problem exists since iOS 11 when I was using electra. 
A way to fix this on iOS 12 was to install this deb http://apt.thebigboss.org/repofiles/cydia/debs2.0/renet_1.0.deb (https://moreinfo.thebigboss.org/moreinfo/depiction.php?file=renetDp). But I don't know if it works for iOS13.

**Comment by marcos1** [comment]
No ssh access.

**Comment by lone-wolf-akela** [comment]
Quote from checkra1n FAQ: 
```
Q: Can I ssh into my device?
A: Yes! An SSH server is deployed on port 44 on localhost only. You can expose it on your local machine using iproxy via USB.
```
Have you tried this?

**Comment by puderty** [comment]
http://tieba.baidu.com/p/5785271205

**Comment by Lakr233** [comment]
ssh into the device and delete the following files and restart

rm -r /var/preferences/com.apple.networkextension*

**Comment by qyouqme** [comment]
> http://tieba.baidu.com/p/5785271205
乐网大法好，已成功

**Comment by Lakr233** [comment]
the same. the apps in /Applications are not injected to the control list.

**Comment by senseiod** [comment]
You can use 乐网(please download for i4 assistant, web address www.i4.cn) app,  install it, and Turn on the switch.

**Comment by zhengjianfeng1103** [comment]
> You can use 乐网(please download for i4 assistant, web address [www.i4.cn](http://www.i4.cn)) app, install it, and Turn on the switch.

Turn one what? I need details.

**Comment by wstyres** [comment]
Take a look at https://github.com/wstyres/Zebra/issues/379 and https://github.com/pwn20wndstuff/Undecimus/issues/136 for more information. This only happens on devices purchased in mainland China.

**Comment by Halo-Michael** [comment]
https://github.com/parrotgeek1/Globalize
Change your model to Australia model.

**Comment by marcos1** [comment]
There’s no dpkg command to install these debs

**Comment by rockqj** [comment]
Just write a simple tool to enable network access for checkra1n loader and cydia.
https://github.com/rockqj/networkfixer
But you may still install cydia first to have dpkg ready and make rootfs writeable. 
![image](https://user-images.githubusercontent.com/17329921/68573265-5d9ced80-04a2-11ea-8f5b-c0da11989bba.png)

**Comment by birkhofflee** [comment]
@rockqj  How do I install Cydia first?

**Comment by rockqj** [comment]
@BirkhoffLee You may try the mentioned app 乐网. It worked fine in my device, and can be removed after the fixer installed.
Or you could wait for the official update of checkra1n. The dev team is likely working on it.

**Comment by birkhofflee** [comment]
Just successfully installed Cydia thru checkra1n loader on a Chinese phone. Here’s a side note. If you have Quantumult APP installed, you can just use it to workaround the issue, there’s no need to install 乐网.

**Comment by marcograss** [comment]
https://twitter.com/marcograss/status/1194144061126369280

**Comment by Dope46** [comment]
I downloaded 乐网, turned the switch on and didn’t work.
What dns should i use to open the loader.

**Comment by f-steff** [comment]
Globalize, which aims at  "Remove region differences on iPhones" may be of use here.
https://github.com/parrotgeek1/Globalize  

Also, here's a great explanation about what's actually happening on Chinese iPhones, seen from a users perspective: https://github.com/pwn20wndstuff/Undecimus/issues/136#issuecomment-457032394

**Comment by f-steff** [comment]
To make checkra1n 0.9.5 work on my chinese iPhone 6 and 6 plus, I had to perform the following steps:

1. Perform CheckRa1n
2. ssh into iPhone using iproxy, to allow Loader access to the internet:
   $ rm /Library/Preferences/com.apple.networkextension.plist
   $ killall -9 CommCenter
3. Execute the loader, and install Cydia
4. ssh into iPhone using iproxy, to allow Cydia access to the internet:
   $ rm /Library/Preferences/com.apple.networkextension.plist
   $ killall -9 CommCenter
5. Install ReNet (Chinese app) from Bigboss repo.
6. ssh into iPhone using iproxy, to allow Cydia apps to show up on the homescreen:
   $ killall SpringBoard

The jailbreak now works, but for every app I install that require network access, I have to run ReNet.

During this I found that  executing uicache would give this error: Error: CFBundleExecutable defined but missing for UICache.app - this is a fatal error. Aborting.
Might be related?

**Comment by sbingner** [comment]
The underlying issue has been identified and resolved.  You should get the proper popup on future releases.

**Comment by wstyres** [comment]
@sbingner Is this also being done for the package managers? They will also run into the same issue if they're not given permission to access WLAN/Cellular

**Comment by Halo-Michael** [comment]
> @sbingner Is this also being done for the package managers? They will also run into the same issue if they're not given permission to access WLAN/Cellular

Yes, same fix will also add to Checkra1n Loader.

**Comment by elviss116** [comment]
> Just write a simple tool to enable network access for checkra1n loader and cydia.
> https://github.com/rockqj/networkfixer
> But you may still install cydia first to have dpkg ready and make rootfs writeable.
> ![image](https://user-images.githubusercontent.com/17329921/68573265-5d9ced80-04a2-11ea-8f5b-c0da11989bba.png)

hi, how to use this?? any tutorial please?

**Comment by rockqj** [comment]
@elviss116 Just a reminder. The tool is a temporary workaround. Checkra1n 0.9.6 will officially fix the network issue.
If you still want to try, you may refer to [README](https://github.com/rockqj/networkfixer/blob/master/README.md). We can discuss in that repo.

**Comment by houssemos** [comment]
@rockqj will the 0.9.6 fix calls and sms ?

**Comment by amyking2011** [comment]
I have found the solution. All you need is an iPhone with checkra1n and cydia installed. backup that iphone. restore the backup to Chinese version iPhone. jailbreak it with Checkra1n. Voila. it`s done!

**Comment by f-steff** [comment]
0.9.6 fixed the issues on my chinese 6 and 6+.  Thanks A LOT for the effort!

However please note that in order for it to work for the loader, I had to restart the loader three times: 

1. The first time, it said asked for permission as it should, then the loader said no internet connection and quit on pressing ok. 
2. The second time, the loader just quit right after being started. Just briefly showed the UI, then quit.
3. The third time the loader just worked, and I were able to install Cydia without further problems.

For both the 6 and 6+ I first tried to run 0.9.6 on top of the installed 0.9.5, and on both devices I observed the same pattern. I first did the 6, and were restarting the loader in pretty quick succession. For the 6+ I allowed something like 30 seconds, and still observed the same.
I then wiped both of the phones (reset all settings and contents), and tried again with 0.9.6, and again I saw the same pattern.

Ultimately it's working, but it does behave a bit strange.

**Comment by yakuv0** [comment]
locra1n no internet no issue

https://github.com/yakuv0/locra1n
