### ISSUE TITLE
iPad 6th gen no longer booting in jailbroken mode on 0.9.3 had to revert to 0.9.2

### ISSUE THREAD

**Issue by chevy4lifeee** [checkra1n/BugTracker#300]
**What device + iOS version are you on?**
13.3 beta 2 which is not fully supported but works just fine on 0.9.2

**What checkra1n version are you using?**
new beta 0.9.3
**What are the steps to reproduce the issue?**
1. check the safe mode option didn't work but verbose boot does work
2. tried holding volume up but didn't work (works on 0.9.2)
3. substrate safe mode stopped working after updating to 13.3 beta 2 and never worked on 13.2.2
...

**What do you expect, and what is happening instead?**
more improvements but iPad doesn't want to boot to jailbroken mode with 0.9.3

**Any other info, error logs, screenshots, ...?**
safe mode no longer works on 0.9.3 but still works on 0.9.2

**Comment by Bram-Brooks** [comment]
Same here. iPad 6th gen on 13.2.2. 0.9.2 works fine, 0.9.3 seems fubar. Every version since 0.9.0 worked first time every single time. On my iPhone 6 as well.

**Comment by chevy4lifeee** [comment]
well it is a beta so it won't be stable till later on but it seems like iPads has been having issues with checkra1n lately. anyone that reads this i recommend staying on 0.9.2 till a new beta is realeased

**Comment by jcarlosperez** [comment]
Maybe this will help in narrowing down the issue. 

![4B1A4E9C-BE29-418C-A096-049F22B8D771](https://user-images.githubusercontent.com/28281280/68803887-98cc2780-062e-11ea-9d7b-377977d492b9.jpeg)

**Comment by FM1337** [comment]
this happened to me as well, I downgraded to 0.9 (first release) and it worked fine

**Comment by hykilpikonna** [comment]
Same here, `000142.734622 wlan0.A[5] handleAdjustBusy@1159:AdjustBusy  timeout in 120000 ms! busystate 0`

**Comment by nullpixel** [comment]
0.9.6 fixes this issue.
