### ISSUE TITLE
Fix Battery not Loading

### ISSUE THREAD

**Issue by Shadowedstalker** [checkra1n/BugTracker#301]
Solution : install iCleanerPro http://ib-soft.net/cydia/
lower Left side hit + open Cydia Substrate Addons
scroll down turn off All at top, Hit apply. Hit yes when it asks about respringing.

Check your battery info.

Reopen iCleanerPro and turn them on one by one until you find the tweak that is causing your issue.

Known tweaks include
SpringPlus 11 = Myself

**Comment by kratos9394** [comment]
i dont even know this springplus11 tweak，done，not even a solution

**Comment by Shadowedstalker** [comment]
It's not a matter of ONE tweak, others are also doing it for people.

Hence, Reopen iCleanerPro and turn them on one by one until you find the tweak that is causing your issue.

You may not have SpringPlus, but it's another tweak you have may easily cause this. If it works in Non-jailbreak state, it's most likely a tweak you installed.

Remember Checkra1n hasn't been out that long and the Devs haven't had time to update the tweaks for iOS 13.

**Comment by ruffes107** [comment]
On my iPhone X iOS 13.2.2 The tweaks That are doing this error is bioprotect xs and Liberty Lite Beta. I Hope the devs can fix it.

**Comment by nullpixel** [comment]
this is an issue with tweaks you have installed.
