### ISSUE TITLE
Cydia Crash while Checkra1n Installed (0.9.3)

### ISSUE THREAD

**Issue by gnutnos98** [checkra1n/BugTracker#305]
**What device + iOS version are you on?**
iPhone 8 Plus - iOS 13.2.2

**What checkra1n version are you using?**
0.9.3
**What are the steps to reproduce the issue?**
1. Jailbreak success 
2. Cydia Crash
3.
...

**What do you expect, and what is happening instead?**
In the 0.9.3, I have installed the checkra1n app into my phone but the cydia is crash. Even when I install or reinstall the cydia in the checkra1n app. 

**Any other info, error logs, screenshots, ...?**
haptic engine and volume is solved in this version.

**Comment by Shadowedstalker** [comment]
Connect the device to your mac. open terminal. enter ssh root@yourIP (on the phone go to wifi click info and get your ip.)

if it asks you a question type yes.

the default password is alpine.

cd /

cd var/mobile/Library/Cydia/

ls (you should see metadata.cb0)

rm metadata.cb0

exit

Now open Cydia.

**Comment by GiladanoN** [comment]
@Shadowedstalker you are a freaking lifesaver & a blessing!

**Comment by Shadowedstalker** [comment]
Glad I could help.

**Comment by Shadowedstalker** [comment]
@gnutnos98 Did this fix your problem?

If so you should close the thread.

**Comment by goldengod123** [comment]
THANKS! Fixed my cydia crashing problem. Closed my thread issue.

**Comment by gnutnos98** [comment]
OMG!!! it's worked!!!!! thank you so much! BUT I still not know how can I do it. 

I do follow your instruction, after the step enter the password. Then I need to paste "em metadata.cb0" to terminal, right? 
I need to make sure in case I got this problem again.

p/s: thank you again, my first time jailbreak is when I have iPod touch gen 3. my childhood really comeback 😄

**Comment by Shadowedstalker** [comment]
@gnutnos98 
 After you enter the password 

cd /

cd var/mobile/Library/Cydia/

ls (you should see metadata.cb0)

rm metadata.cb0      <--- making sure it RM (lower case)

exit

Now open Cydia.

**Comment by gnutnos98** [comment]
Im sorry but I am not sure I get it!
after I enter the password
what do I need to do next?

**Comment by Shadowedstalker** [comment]
Ok, after you type the password into terminal.

Type cd / (this will put in to the root directory or your device)

Type cd var/mobile/Library/Cydia/ (this changes to the directory where the file is)

Type ls (Lower case LS) (this allows you to see what is in the directory you are in)

Type rm metadata.cb0 <--- making sure it RM (lower case) (This removes the file)

Type exit (this will close the terminal connection to your device)

Close Terminal

Now open Cydia on your device.

**Comment by gnutnos98** [comment]
great! thank you so much again! 😁this will very helpful for me!
