### ISSUE TITLE
Touch still not working after boot, 0.9.3

### ISSUE THREAD

**Issue by denniskns** [checkra1n/BugTracker#307]
**What device + iOS version are you on?**
ipX 13.2.2

**What checkra1n version are you using?**
0.9.3
**What are the steps to reproduce the issue?**
1. Steps from checkr1n 
2. booting
3. touch not working
...

**What do you expect, and what is happening instead?**
touch should work (:

**Any other info, error logs, screenshots, ...?**

**Comment by tuncersahinci** [comment]
Same issue, didn't have this one on 0.9.2.

Went back to 0.9.2 after this issue, resolved for now.

**Comment by denniskns** [comment]
also a method which works is to double jailbreak, but then face id does not work :/

**Comment by kpwn** [comment]
We pushed 0.9.3.2, should fix this.

**Comment by halfbread10** [comment]
Happening on 0.9.3.2 also. iPhone X 13.2.2. Had the same issue with 0.9.2, 0.9.3 seemed to have fixed it. updated to 0.9.3.2 and the touch is not working, going back to 0.9.3 doesn't work anymore either. haven't installed anything new. since 0.9.1

**Comment by HeyItsMicro** [comment]
this has happened to me on 0.9.2, 0.9.3, and 0.9.3.2

**Comment by halfbread10** [comment]
> this has happened to me on 0.9.2, 0.9.3, and 0.9.3.2

same. 0.9.3 worked once somehow but now it won't.

**Comment by kpwn** [comment]
https://assets.checkra.in/test/checkra1n%20beta%200.9.4.dmg

Can you try this build? We updated the DFU guide, please follow it and don't attempt to enter DFU mode beforehand.

**Comment by halfbread10** [comment]
Instructions don't seem to be working. Phone turns on normally.

**Comment by halfbread10** [comment]
Update: Got the DFU working with the guide. not sure why it didn't work earlier. Touch and Face ID are both working correctly but some tweaks don't load after boot until a manual respring.

**Comment by kpwn** [comment]
The tweaks issue was a 0.9.4 bug addressed in 0.9.5.
