### ISSUE TITLE
DFU instructions not working 

### ISSUE THREAD

**Issue by gurkentier** [checkra1n/BugTracker#308]
**What device + iOS version are you on?**
iPhone X 13.2.2 and iPhone 8 13.2.2

**What checkra1n version are you using?**
0.9.3
**What are the steps to reproduce the issue?**
1. run checkra1n
2. follow DFU instructions strictly
3. device boots normally 
...

**What do you expect, and what is happening instead?**
Device goes into DFU mode
But is booting normally 

**Any other info, error logs, screenshots, ...?**

**Comment by Shadowedstalker** [comment]
The timing is off on the Checkra1n app.

Hold power watch your phone when it turns off release power, hold volume down and power, watch Checkra1n release the power button at 1 and hold volume down, Checkra1n will tell you when it has entered DFU.

This is a known issue.

**Comment by spockers** [comment]
1) connect iphone to computer and make sure your phone is on, not off.
2) quickly press volume up, quickly press volume down then press and hold power until the screen JUST goes black
3) release the power, then re hold down volume down and hold power together for 5 seconds
4) after 5 seconds, release power button but keep hold volume down
5) wait until checkra1n  detects as DFU mode as the phone 8/8plus goes black :)

**Comment by Shadowedstalker** [comment]
> 
> 
>     1. connect iphone to computer and make sure your phone is on, not off.
> 
>     2. quickly press volume up, quickly press volume down then press and hold power until the screen JUST goes black
> 
>     3. release the power, then re hold down volume down and hold power together for 5 seconds
> 
>     4. after 5 seconds, release power button but keep hold volume down
> 
>     5. wait until Itunes detects as DFU mode as the phone 8/8plus goes black :)

Why would you use iTunes? The Checkra1n app works perfectly well to detect DFU, it's simply a matter of time.

And there's no need for a Hard Reset (Volume Up, Down, Power.)

**Comment by spockers** [comment]
> Why would you use iTunes?

I wouldn’t. I copy/pasted that from elsewhere, it helped me when I was having difficulty getting my new 8 into dfu. There were 2 references to iTunes and I missed one of them. 😎

**Comment by Shadowedstalker** [comment]
Yes the timing has been off for the beginning. But if you watch your phone and Checkra1n you can get the timing down pat.

**Comment by spockers** [comment]
> And there's no need for a Hard Reset (Volume Up, Down, Power.)

Oh? Good to know, thanks.

**Comment by gurkentier** [comment]
Following the DFU instructions with correct timing solved all of my issues! Thanks!
