### ISSUE TITLE
Hackintosh -26 and -31 errors

### ISSUE THREAD

**Issue by Wamy-Dev** [checkra1n/BugTracker#309]
**What device + iOS version are you on?**
iPhone 7
ios 13.2
MacOs 10.13.6 Hackintosh

**What checkra1n version are you using?**
Tried all available. 0.9-0.9.3

**What are the steps to reproduce the issue?**
1.Install Hackintosh 10.13.6
2.Download Checkra1n
3.TRY and jailbreak
...

**What do you expect, and what is happening instead?**
I expect to jailbreak, and instead I am getting annoying errors.

**Any other info, error logs, screenshots, ...?**

**Comment by Shadowedstalker** [comment]
Can't speak of the Hackintosh, as I haven't done that for many years. but even on a real Mac these errors occur. it's a matter of retrying and retrying again. I had a split second issue with -31 but after i unplugged the phone and reconnected and tried a few more times it worked.

**Comment by GuyInHiding** [comment]
On my hackintosh I switched to a USB 2 port and I've been able to jailbreak fine.
Are you using an AMD hackintosh?

**Comment by littlelailo** [comment]
Hackintosh isn't supported sry
