### ISSUE TITLE
 /etc/master.passwd.lqPYNe: Read-only file system

### ISSUE THREAD

**Issue by Lakr233** [checkra1n/BugTracker#31]
**What device + iOS version are you on?**
iPad Pro 10.5 + 13.2

**What are the steps to reproduce the issue?**
1. run checkra1n
2. connect ssh
3. ssh into it
...

**What do you expect, and what is happening instead?**
 /etc/master.passwd.lqPYNe: Read-only file system

**Any other info, error logs, screenshots, ...?**
qaq@Lakrs-iMac ~ % /Volumes/Applications/checkra1n.app/Contents/MacOS/checkra1n_gui
- [*] Waiting for DFU devices
- [*] DFU mode device found
- [*] Attempting to perform checkm8 on 8011 10...
- [*] == Checkm8 Preparation stage ==
- [*] Stalled input endpoint
- [*] DFU mode device found
- [*] == Checkm8 Setup stage ==
- [*] Entered initial checkm8 state after 3 steps, issuing DFU abort..
- [*] DFU device disconnected
- [*] DFU mode device found
- [*] == Checkm8 Trigger stage ==
- [*] Checkmate!
- [*] DFU device disconnected
- [*] DFU mode device found
- [*] == Checkm8 Trying to run payload... ==
- [*] If everything went correctly, you should now have code execution.
- [*] DFU device disconnected
- [*] Download mode device found
- [*] Download mode device disconnected
- [*] Bootstrap already installed, done

qaq@Lakrs-iMac ~ % ssh root@127.0.0.1 -p 4444
root@127.0.0.1's password: 
-bash-3.2# passwd
Changing password for root.
New password:
Retype new password:
passwd: /etc/master.passwd.lqPYNe: Read-only file system
-bash-3.2# mount
/dev/md0 on / (hfs, local, nosuid, read-only)
devfs on /dev (devfs, local, nosuid, nobrowse)
/dev/disk0s1s1 on / (apfs, local, nosuid, read-only, union, journaled, noatime)
devfs on /dev (devfs, local, nosuid)
/dev/disk0s1s3 on /private/xarts (apfs, local, nodev, nosuid, journaled, noatime, nobrowse)
/dev/disk0s1s2 on /private/var (apfs, local, nodev, nosuid, journaled, noatime, protect)
/dev/disk0s1s4 on /private/var/MobileSoftwareUpdate (apfs, local, nodev, nosuid, journaled, noatime, nobrowse)
/dev/disk4 on /binpack (hfs, local, nosuid, read-only)
/dev/disk5 on /private/var/binpack (hfs, local, nosuid, read-only)
lifs://livefileproviderd@198/LiveFiles on /private/var/mobile/Library/LiveFiles (lifs, nodev, noexec, nosuid, noowners, noatime, nobrowse, mounted by mobile)
-bash-3.2#

**Comment by nullpixel** [comment]
Yes, this is intentional. You must bootstrap your device, or remount `/` as rw to write to it.

**Comment by Lakr233** [comment]
so it is back to the loader app crash on iPad..... understand

**Comment by nullpixel** [comment]
We're fixing it and It should be ready soon.

**Comment by alessaba** [comment]
How do we remount / as rw?
