### ISSUE TITLE
Bootstrap error 2

### ISSUE THREAD

**Issue by Efraimbo** [checkra1n/BugTracker#313]
**What device + iOS version are you on?**
Iphone 6 ios 12.4

**What checkra1n version are you using?**
0.9.2
**What are the steps to reproduce the issue?**
1.open checkra1n 
2.install cydia

**What do you expect, and what is happening instead?**
Install cydia again

**Any other info, error logs, screenshots, ...?**
I used to be jailbroken using unc0ver, but since it has been revoked i tried checkra1n and when i install cydia from within to overwrite the old cydia it gives me this error

**Comment by arx8x** [comment]
Restore rootFS before jailbreaking with checkra1n

**Comment by Efraimbo** [comment]
How to do that arx8x since unc0ver license has been revoked?

**Comment by arx8x** [comment]
with xcode and ios app signer

Generate a profile with xcode, sign the ipa with that profile using ios app signer and sideload it with xcode
