### ISSUE TITLE
Error -20 & touchscreen still unresponsive 

### ISSUE THREAD

**Issue by MyRatHadPuppies** [checkra1n/BugTracker#316]
**What device + iOS version are you on?**
iPhone X iOS 13.2.2

**What checkra1n version are you using?**
0.9.3.2
**What are the steps to reproduce the issue?**
1. Enter DFU
2. Proceed with jailbreak
3. Device boots, but touchscreen won't work.
...

**What do you expect, and what is happening instead?**
For the device to boot up in a jailbroken state with the touchscreen function working properly.

**Any other info, error logs, screenshots, ...?**
When using verbose boot the same issue happens, trying to boot in safe mode did not work for me either I continued to get error -20 but when it would boot in a jailbroken state touch is unresponsive

**Comment by napoleonjames** [comment]
Same Problem

**Comment by nullpixel** [comment]
0.9.5 fixes these issues, with the new DFU sequence.
