### ISSUE TITLE
Cydia keeps crashing

### ISSUE THREAD

**Issue by goldengod123** [checkra1n/BugTracker#317]
**What device + iOS version are you on?**
Iphone 7 plus  iOS 13.2.2

**What checkra1n version are you using?**
beta 0.9.3.2
**What are the steps to reproduce the issue?**
1. Jailbreak on Mac
2. Open checkra1n loader
3.Install cydia
...

**What do you expect, and what is happening instead?**
Cydia is installing, but cydia keeps crashing afterwards

**Any other info, error logs, screenshots, ...?**

**Comment by GiladanoN** [comment]
try this, seemed to help me ~
https://github.com/checkra1n/BugTracker/issues/305#issuecomment-553615506

**Comment by Shadowedstalker** [comment]
Just a repost of my post He's referencing 

Connect the device to your mac. open terminal. enter ssh root@yourIP (on the phone go to wifi click info and get your ip.)

if it asks you a question type yes.

the default password is alpine.

cd /

cd var/mobile/Library/Cydia/

ls (you should see metadata.cb0)

rm metadata.cb0

exit

Now open Cydia.

**Comment by Shadowedstalker** [comment]
If this fixed your problem you should close the thread.

**Comment by goldengod123** [comment]
When I try this it says "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:xevIPkidCjUaaMXlphslja+3eCJfMQBlixKUeIzoBI8.
Please contact your system administrator.
Add correct host key in /Users/cesar/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/cesar/.ssh/known_hosts:2
RSA host key for 192.168.1.222 has changed and you have requested strict checking.
Host key verification failed.

**Comment by Shadowedstalker** [comment]
@goldengod123 Answered in #354

**Comment by goldengod123** [comment]
Thank you it worked.
