### ISSUE TITLE
Feature request - quick ssh actions

### ISSUE THREAD

**Issue by GiladanoN** [checkra1n/BugTracker#319]
any chance of adding a short menu with a few quick actions?

since it's dead simple to use ssh to run these, and -t to run commands is an option,
i was wondering if the following commands may be added to the GUI somehow:
- respring i.e - killall SpringBoard
- clear uicache i.e - uicache --all
- fix broken cydia i.e - rm var/mobile/Library/Cydia/metadata.cb0

i'm sure there's a ton more,
these are just a few i found myself having to use a couple of times.

and i definitely know this won't improve on the tool itself, however it could save a slight hassle.
let me know if it's relevant, if not i guess i could write a small CLI tool myself and share :)

**Comment by Shadowedstalker** [comment]
For Respring might I suggest CCModules,

NewTerm 2 (Mobile Terminal) Makes uicache a snap as you can do it directly from the phone itself.

**Comment by DanyL** [comment]
Thanks for the suggestion, but it's not something we would like to incorporate as part of our tool.
Feel free to write a script which automates this for you.
