### ISSUE TITLE
checkra1n app not opening

### ISSUE THREAD

**Issue by a-a14** [checkra1n/BugTracker#320]
**What device + iOS version are you on?**
iOS 13.2.2

**What checkra1n version are you using?**
checkra1n 0.9.3.2 beta

**What are the steps to reproduce the issue?**
1. Downloaded the application onto my MacBook
2. Unjailbroken my device
3. Rejailbroke my device via the app

**What do you expect, and what is happening instead?**
Expect: Can open app to install Cydia
Instead: Cannot open the app - launches, then crashes

**Any other info, error logs, screenshots, ...?**
None

**Comment by gnutnos98** [comment]
#305 this may help you, see the comment!
