### ISSUE TITLE
Update to checkra1n beta 0.9.3.2 failed with error -20

### ISSUE THREAD

**Issue by quilenle** [checkra1n/BugTracker#324]
**What device + iOS version are you on?**
iPhone 6S + iOS 12.4

**What checkra1n version are you using?**
beta 0.9.3.2

**What are the steps to reproduce the issue?**
1. Already jailbroken with checkra1n beta 0.9.2, installed some tweaks, everything works normally.
2. Download checkra1n beta 0.9.3.2 and re-jailbreak

**What do you expect, and what is happening instead?**
My expect: jailbreak success and update to beta 0.9.3.2
Result: it can't jailbreak the device, displays the error -20

**Any other info, error logs, screenshots, ...?**
I have tried "Restore system" but it seems like it not working, after reboot, it still shows the jailbroken app (in non-jailbroken state).
Then I use the beta 0.9.2 to re-jailbreak, the result is I re-jailbroken successful, and all my setup is still there.

**Comment by arx8x** [comment]
This happens on an iPhone 6 on 12.4 I have as well. It works fine on checkra1n 9.3 and below. Patches are applied and device boots up fine but file system is read-only. On 9.3. it shows "Found ASPS support" the device but not on 9.3.2. On 9.3.2, it shows "injected fakemd" but not on 9.3. That's all the info I have.

**Comment by malhaar** [comment]
same pinch

**Comment by cat24max** [comment]
Yup, can confirm. While 0.9.2 was finally able to jailbreak my iPhone X, it caused Face ID to not work. Now on 0.9.3.2 it's impossible to jailbreak again because of -20.

**Comment by a1ex4** [comment]
Can confirm 0.9.3.2 always failing with an iPhone 6 12.4, while 0.9.2 works first try.
Thanks so much for everything kjc gang !

**Comment by kpwn** [comment]
As suggested by @arx8x, try https://assets.checkra.in/test/checkra1n%20beta%200.9.4.dmg and close the issue if it fixes it for you.

**Comment by quilenle** [comment]
> As suggested by @arx8x, try https://assets.checkra.in/test/checkra1n%20beta%200.9.4.dmg and close the issue if it fixes it for you.

Fixed this issue via beta 0.9.4.
