### ISSUE TITLE
iPad 6th gen iOS 13.3 still not booting to jailbroken state on 0.9.3.2

### ISSUE THREAD

**Issue by chevy4lifeee** [checkra1n/BugTracker#325]
What device + iOS version are you on?
13.3 beta 2 which is not fully supported but works just fine on 0.9.2

What checkra1n version are you using?
new beta 0.9.3.2
What are the steps to reproduce the issue?

check the safe mode option didn't work but verbose boot does work
tried holding volume up but didn't work (works on 0.9.2)
substrate safe mode stopped working after updating to 13.3 beta 2 and never worked on 13.2.2
...
What do you expect, and what is happening instead?
more improvements but iPad doesn't want to boot to jailbroken mode with 0.9.3.2

Any other info, error logs, screenshots, ...?
safe mode no longer works on 0.9.3.2 but still works on 0.9.2

**Comment by Xador123** [comment]
I have the same problem

**Comment by ASlien** [comment]
yes  same problem 
and wait for next version 
i think next version will be fixed

**Comment by jamminceo** [comment]
Same here and I am still on 13.2. I always revert back to the original JB update and everything works. I assume there will be an update soon.

**Comment by Xador123** [comment]
checkra1n beta 0.9.3.4.dmg does not work with IPad 6Gen. 2018   
 Booted not and then Error 20. Only 0.9.2 works well.

**Comment by Xador123** [comment]
checkra1n beta 0.9.3.7.dmg does not work with IPad 6Gen. 2018
Booted not and then Error 20. Only 0.9.2 works well.

**Comment by kpwn** [comment]
Can you try testing this build: https://assets.checkra.in/test/checkra1n%20beta%200.9.4.dmg

**Comment by chevy4lifeee** [comment]
still not working same resultes as the last 2 recent builds i've tried. not sure what the issue is but 0.9.2 is the latest version that i have luck with. here are some screenshots of the issues i'm having 
![Screen Shot 2019-11-14 at 21 18 24](https://user-images.githubusercontent.com/57630809/68914626-c98e8880-0724-11ea-83be-9664d87ac002.png)

**Comment by kpwn** [comment]
Can you try booting with verbose mode on and sending a picture of your screen?

**Comment by chevy4lifeee** [comment]
I think the issue is the new update is not compatible with the iPad according to the verbose boot and it’s also talking about an issue with substrate on the bottom 


![E195560B-AA7F-4FC9-A7A2-B0969F835794](https://user-images.githubusercontent.com/57630809/68915298-0196cb00-0727-11ea-9779-dc7dee8353fa.jpeg)
![07504CD2-7603-4455-9490-DA16D9B0C545](https://user-images.githubusercontent.com/57630809/68915299-0196cb00-0727-11ea-9c6b-55a2c00fd511.jpeg)

**Comment by kpwn** [comment]
that is very odd and should most definitively not be happening. Does enabling Safe Mode help at all?

**Comment by kpwn** [comment]
Also just to make sure - you are using the DFU instructions from the app, correct?

**Comment by chevy4lifeee** [comment]
![33DD34ED-AB18-4068-9A87-954E07B38547](https://user-images.githubusercontent.com/57630809/68915738-ee84fa80-0728-11ea-96a3-146649fb11c5.jpeg)
> Also just to make sure - you are using the DFU instructions from the app, correct?

yes i'm doing everything correctly. i'm not sure what the issue is and other people are having issues booting up their iPad 6th gen after 0.9.3 update and safe mode doesn't work either not even the volume up method but it does work on 0.9.2 here's some pics of it working on 0.9.2 
![Screen Shot 2019-11-14 at 21 44 24](https://user-images.githubusercontent.com/57630809/68915698-c09fb600-0728-11ea-811a-79f70ff7897f.png)

**Comment by Xador123** [comment]
With me exactly the same problem, only the 0.9.2 boots on IPad 6Gen 2018 IOS 13.2.2. The new trial versions up to 0.9.4 are stuck and "Permission and then Error 20. Just like above the pictures.

**Comment by Xador123** [comment]
V.9.4.1 same error as before, booted the IPad Gen.6. not. Still only 0.9.2 works.

**Comment by ghost** [comment]
iPad 6th:

Currently only works with checkra1n 0.9.2 flawlessly.
Unable to work with checkra1n 0.9.3 ~ 0.9.5

checkra1n is compatible with iOS 13.2.3 and older version.
Even the version 0.9.5 for now showing the message that only support iOS 13.2 and oldest version, it's still work by running following commands in Terminal under DFU mode:
/Applications/checkra1n.app/Contents/MacOS/checkra1n_gui

If you need newest version, the team is working on supporting in future releases.

**Comment by jamminceo** [comment]
As it stands, the first two builds Conroe to work on iPad. I have continued to have the same issues with the bottom substrate. I have not seen any updates on the horizon as of yet. I continue to work with 9.1...is there a link for 0.9.2?

**Comment by nullpixel** [comment]
0.9.6 should resolve this issue. Let me know if it doesn't!
