### ISSUE TITLE
iCloud Drive not working.

### ISSUE THREAD

**Issue by Stux-Sec** [checkra1n/BugTracker#329]
**What device + iOS version are you on?**
iPhone X iOS 13.2.2

**What checkra1n version are you using?**
0.9.1

**What do you expect, and what is happening instead?**
**Happening**: When opening the “Files” app and clicking “iCloud Drive”, it gets stuck on “iCloud Drive is loading...”
**Expect**: iCloud Drive to load with all my files

**Any other info, error logs, screenshots, ...?**
![C6B18BED-A381-4BBB-AE50-C627540CCC03](https://user-images.githubusercontent.com/30992426/68833561-a43c4480-0668-11ea-99cf-f47bea6e6f1e.jpeg)

**Comment by RonaldRegister** [comment]
I've had something similar, for me it worked when disabling and enabling iCloud drive in settings OR signing out (and in) of iCloud alltogether. Can't remember which one.

**Comment by Stux-Sec** [comment]
I’ve tried both, still doesn’t work.

**Comment by RonaldRegister** [comment]
Does it work in non-jailbroken mode?

**Comment by Stux-Sec** [comment]
Yes
