### ISSUE TITLE
Error code: -20

### ISSUE THREAD

**Issue by salem300** [checkra1n/BugTracker#33]
Timed out waiting for bootstrap upload (Error code: -20)
iPhone 6s IOS 12.4

**Comment by fouadg** [comment]
same

**Comment by cat24max** [comment]
Same thing on iPhone X 13.1

**Comment by Zacharous** [comment]
Same. iPhone X on iOS 13.1.3

**Comment by liuter1983** [comment]
the same here  (Error code: -20)
iPhone 6s IOS 12.4.1 ,waiting for  a  solution

**Comment by ygzok** [comment]
same iphone x on ios 13.2.2

**Comment by nullpixel** [comment]
Hi, did you install any tweaks?

**Comment by ygzok** [comment]
> Hi, did you install any tweaks?

i just found that cercube caused that. i'm restoring now.

**Comment by nullpixel** [comment]
Yeah, this issue is generally caused by a bad tweak.

**Comment by cat24max** [comment]
@nullpixel Nope, I get this error and my X has never been jailbroken before.
