### ISSUE TITLE
iPhone 6 0.9.3 and 0.9.3.2 bugs

### ISSUE THREAD

**Issue by LetsGetStarted999** [checkra1n/BugTracker#331]
**What device + iOS version are you on?**
iPhone6 12.4.3

**What checkra1n version are you using?**
0.9.3 and/or 0.9.3.2

**What are the steps to reproduce the issue?**
1. Install CheckRa1n. Here happened to me two types of bug:
2a. When opening CR Icon 1-2 times on 5 (when rebooting for rejailbreaking) the app crashes. 
2b. When taking a screenshot, 1-2 times on 10 the iPhone goes on Safe Mode.

**What do you expect, and what is happening instead?**
I expect that it isn’t tweaks-correlated, because I have “normal tweaks” (not installed by pirated repository).

**Any other info, error logs, screenshots, ...?**
When rebooting after the screenshot that caused this reboot. the screenshot was not even saved ahahahah.

**Comment by DanyL** [comment]
All tweaks can have bugs which may cause this kind of behaviour, try removing all tweaks and see if the problem continues.

If it's unrelated to any tweak, please re-open the issue.
