### ISSUE TITLE
Can't open any app of apple or other app

### ISSUE THREAD

**Issue by Hardik933** [checkra1n/BugTracker#334]
**What device + iOS version are you on?**
iPhone SE + iOS 13.2.2

**What checkra1n version are you using?**
checkra1n 0.9.3.2 beta
**What are the steps to reproduce the issue?**
1.Install home gesture tweak
2.
3.
...

**What do you expect, and what is happening instead?**
After Install home gesture tweak when I unlock my device it's will respring again come up will lock screen and same thing.

**Any other info, error logs, screenshots, ...?**

**Comment by DanyL** [comment]
Enter Safe-Mode and remove the tweak.
Closing as unrelated to checkra1n.
