### ISSUE TITLE
iPhone X 13.2.2 / checkra1n 0.9.3 - lag system, Camera dont work

### ISSUE THREAD

**Issue by CoreKracker** [checkra1n/BugTracker#335]
**What device + iOS version are you on?**
iPhone X iOS 13.2.2

**What checkra1n version are you using?**
checkra1n 0.9.3

**What are the steps to reproduce the issue?**
1. The hole system workflow is extremly lagging after the update from checkra1n 0.9.2 to 0.9.3
2. Since the checkra1n update the camera does not open anymore. This in the Stock Camera App, and in all other apps that use the camera.

**Comment by Wamy-Dev** [comment]
Same issue with camera on iphone7

**Comment by CoreKracker** [comment]
> 
> 
> Same issue with camera on iphone7

i've done yesterday a LDRestart with PowerSelector. After that the problem with the cam was solved
