### ISSUE TITLE
It's awful !!!!!!!

### ISSUE THREAD

**Issue by AliRzAsd** [checkra1n/BugTracker#337]
**_Iphone X & Ios 13.2.2
Checkra1n 0.9.3.2
1. After jailbreak, the tweets I installed are not activated
2. And the camera crashes
3. And vpn profile is not installed_**

**Comment by nullpixel** [comment]
do you want help, or not? try safe mode and uinstalling any bad tweaks, then open a new issue with better wording for your issue.
