### ISSUE TITLE
iphone 5s error 

### ISSUE THREAD

**Issue by Kuina1999** [checkra1n/BugTracker#338]
**What device + iOS version are you on?**
ios 12.4.3 iphone 5s icloud

**What checkra1n version are you using?**
0.9.3.2 beta
**What are the steps to reproduce the issue?**
1.jailbreak inactive, iphone restarts
2.
3.
...

**What do you expect, and what is happening instead?**

jailbreak active

**Any other info, error logs, screenshots, ...?**

**Comment by Kuina1999** [comment]
https://drive.google.com/file/d/1YY4T_XzsHdXY2XCqwi4C4gMJ_woh2Mcx/view?usp=sharing

**Comment by fhc5326** [comment]
I did happen this at this version,too.

**Comment by littlelailo** [comment]
We don't support iCloud locked devices

**Comment by OrkhanAlikhanov** [comment]
@Kuina1999 try https://github.com/checkra1n/BugTracker/issues/377#issuecomment-554327129
