### ISSUE TITLE
Sorry, iPhone X (Global) is supported, but iOS 13.3 is not. Supported versions are 12.3 - 13.2.2. ECID: 0x114d042807093a

### ISSUE THREAD

**Issue by ciaranburke95** [checkra1n/BugTracker#339]
**What device + iOS version are you on?**

**What checkra1n version are you using?**

**What are the steps to reproduce the issue?**
1.
2.
3.
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by littlelailo** [comment]
Yes iOS 13.3 isn't offically supported atm, you can try to use the CLI tool at your own risk if you still want to try experimental support
