### ISSUE TITLE
Install checkra1n succeed but Cydia crash. Taptic engine and volume not respond

### ISSUE THREAD

**Issue by gnutnos98** [checkra1n/BugTracker#345]
**What device + iOS version are you on?**

iPhone 8 plus + iOS 13.2.2

**What checkra1n version are you using?**
0.9.3.2

**What are the steps to reproduce the issue?**
1. Installed Checkra1n app
2. Cydia crash when Open
3. Taptic engine and volume not respond

**Comment by nullpixel** [comment]
closing as a #291 dupe, please see https://github.com/checkra1n/BugTracker/issues/291#issuecomment-554001715
