### ISSUE TITLE
boot loop (apple logo) after jailbreak

### ISSUE THREAD

**Issue by denniskns** [checkra1n/BugTracker#346]
**What device + iOS version are you on?**
ipX 13.2.2

**What checkra1n version are you using?**
tried all
**What are the steps to reproduce the issue?**
1. follow instruction
2. checkrain loads and program on mac says it is finished
3. also it says that the device is connected in normal mode
...

**What do you expect, and what is happening instead?**
i ended in booting, apple logo keeps on black screen, and after some time it disappears for a second and start again in loading the apple logo

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
try booting with safe mode and removing bad tweaks

**Comment by Siguza** [comment]
Closing due to lack of response.
