### ISSUE TITLE
Hard to see Home button text for iPhone 6s Plus by entering DFU mode tutorial.

### ISSUE THREAD

**Issue by Michael1999US** [checkra1n/BugTracker#348]
**What device + iOS version are you on?**
iPhone 6s Plus 13.2.2
**What checkra1n version are you using?**
0.9.3.2
**What are the steps to reproduce the issue?**
1. Stick lightning cable to iPhone 6s Plus
2. Start recovery mode
**What do you expect, and what is happening instead?**
Expected to see Home button clearly, while it's really hard to see it.
**Any other info, error logs, screenshots, ...?
<img width="477" alt="Screenshot 2019-11-14 at 17 11 57" src="https://user-images.githubusercontent.com/56358359/68875200-b36fd080-0702-11ea-8b96-5fdee8b218e8.png">

**Comment by nikias** [comment]
This is a bug in older checkra1n that has been fixed now. Blame nitoTV :P 
@Michael1999US update to latest version: https://checkra.in/releases/0.9.5-beta
