### ISSUE TITLE
Fix Cydia Crash

### ISSUE THREAD

**Issue by Shadowedstalker** [checkra1n/BugTracker#354]
Connect device to your Mac
Open Terminal
Type ssh root@YourIP (to find your IP look under setting-WiFi info)
If it asks a question type yes
Default password is alpine
Type cd / 
Type cd var/mobile/Library/Cydia
Type rm metadata.cb0
Type exit
Open Cydia

If it says No Such directory 
Type ls (lower case LS)
If you only see Library and Media you forget to type cd / and are not in the root directory.

**Comment by goldengod123** [comment]
when i do this it says "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:xevIPkidCjUaaMXlphslja+3eCJfMQBlixKUeIzoBI8.
Please contact your system administrator.
Add correct host key in /Users/cesar/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/cesar/.ssh/known_hosts:2
RSA host key for 192.168.1.222 has changed and you have requested strict checking.
Host key verification failed.

**Comment by Shadowedstalker** [comment]
If you see this 

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Type ssh-keygen -R yourIP  hit Enter

ssh root@yourIP
answer Yes
password alpine 

and so on.

**Comment by goldengod123** [comment]
Thank you! Worked

**Comment by napoleonjames** [comment]
> Connect device to your Mac
> Open Terminal
> Type ssh root@YourIP (to find your IP look under setting-WiFi info)
> If it asks a question type yes
> Default password is alpine
> Type cd /
> Type cd var/mobile/Library/Cydia
> Type rm metadata.cb0
> Type exit
> Open Cydia
> 
> If it says No Such directory
> Type ls (lower case LS)
> If you only see Library and Media you forget to type cd / and are not in the root directory.

Thank You! Its work.

**Comment by JiZZER6** [comment]
its not working for me 
i did everything right but it says: port22: connection refused for example ssh: connect to host MY;IP port 22: connection refused

what should i do?
<img width="193" alt="Bildschirmfoto 2019-11-18 um 16 37 19" src="https://user-images.githubusercontent.com/49577000/69066728-1d011f00-0a22-11ea-9b43-eebf7db925d8.png">

**Comment by Shadowedstalker** [comment]
You have Jailbroken and installed Cydia. Cydia installs Open SSH. Which listens on port 44, you should not be entering a port .

**Comment by JiZZER6** [comment]
But it does yes i installed fresh 30 min ago checkra1n from official site
and it was succesfull and when i try to install some tweak it does not
working idk what i am doing wrong and i saw ur post and i did also
everything right but its saying port 22: connection refused

What can be did wrong?

Shadowedstalker <notifications@github.com> schrieb am Mo. 18. Nov. 2019 um
4:51 PM:

**Comment by Shadowedstalker** [comment]
I would suggest doing a "system restore" from within Cheackra1n, don't worry about the left over icons.
Then rejailbreak and let it reinstall Cydia. it's possible that it did not complete correctly.

**Comment by UrBaN103** [comment]
> Connect device to your Mac
> Open Terminal
> Type ssh root@YourIP (to find your IP look under setting-WiFi info)
> If it asks a question type yes
> Default password is alpine
> Type cd /
> Type cd var/mobile/Library/Cydia
> Type rm metadata.cb0
> Type exit
> Open Cydia
> 
> If it says No Such directory
> Type ls (lower case LS)
> If you only see Library and Media you forget to type cd / and are not in the root directory.

When I do ssh root@my ip, it gives me connection refused and plus it adds a port after my ip when I press enter

**Comment by Shadowedstalker** [comment]
You can SSH anytime with Terminal open. The device doesn't have to be connected as long as you have the device IP.

So you open Terminal you type something like
ssh root@192.168.0.0 and it returns something like
ssh toot@192.168.0.0:XX connection refused?
what is the port number?

**Comment by UrBaN103** [comment]
> You can SSH anytime with Terminal open. The device doesn't have to be connected as long as you have the device IP.
> 
> So you open Terminal you type something like
> ssh root@192.168.0.0 and it returns something like
> ssh toot@192.168.0.0:XX connection refused?
> what is the port number?

I think the port number was 22 idk bc I am not on my computer rn but there were 2s in them

**Comment by Shadowedstalker** [comment]
I figured it might be 22. Have you tried the 'System restore" option mentioned above?

**Comment by UrBaN103** [comment]
> I figured it might be 22. Have you tried the 'System restore" option mentioned above?

Yeah I have but still says port 22

**Comment by UrBaN103** [comment]
> I figured it might be 22. Have you tried the 'System restore" option mentioned above?

Should I do the steps again restore system and then try the commands?

**Comment by Shadowedstalker** [comment]
It's worth a shot.

Have you been jailbroken before?

**Comment by UrBaN103** [comment]
> It's worth a shot.
> 
> Have you been jailbroken before?

Yeah I have but I never got a problem cydia crashing before

**Comment by Shadowedstalker** [comment]
That could play a part in it. I have not experienced it, but I have seen others say they have had problems with previous jailbreaks causing an issue. 

Try this  

In Safari on the device

https://app.ignition.fun/

Search Filza

Install FilzaEscaped

Go to var/mobile/library/cydia/metadata.cb0 and delete metadata.cb0

**Comment by UrBaN103** [comment]
> That could play a part in it. I have not experienced it, but I have seen others say they have had problems with previous jailbreaks causing an issue.
> 
> Try this
> 
> In Safari on the device
> 
> https://app.ignition.fun/
> 
> Search Filza
> 
> Install FilzaEscaped
> 
> Go to var/mobile/library/cydia/metadata.cb0 and delete metadata.cb0

Ok I will try that. Also can you look at my other issue bc I am stuck as DPKG_LOCKED and i don’t know how to fix it.

**Comment by UrBaN103** [comment]
> That could play a part in it. I have not experienced it, but I have seen others say they have had problems with previous jailbreaks causing an issue.
> 
> Try this
> 
> In Safari on the device
> 
> https://app.ignition.fun/
> 
> Search Filza
> 
> Install FilzaEscaped
> 
> Go to var/mobile/library/cydia/metadata.cb0 and delete metadata.cb0

Am I supposed to download filza when I’m jail broken on my device? It does not allow me to get any filza in ignition

**Comment by Shadowedstalker** [comment]
First, it appears that Cydia did NOT install correctly or became corrupted. DPKG_LOCKED is usually given when one or the other happen. 

So do a "system restore." then try Ignition.fun (on the device itself)

I have Filza the Cydia version, but I went to ignition and had no problems attempting to get FILZAESCAPED,

**Comment by UrBaN103** [comment]
> First, it appears that Cydia did NOT install correctly or became corrupted. DPKG_LOCKED is usually given when one or the other happen.
> 
> So do a "system restore." then try Ignition.fun (on the device itself)
> 
> I have Filza the Cydia version, but I went to ignition and had no problems attempting to get FILZAESCAPED,

Which iOS version are you on bc I am on iOS 13.1.2 and the filza in ignition are for 12.x

**Comment by Shadowedstalker** [comment]
I too am on 13.1.2. yes, it says 12. Thought once you get Cydia working you can on install that and install the one from within Cydia.

**Comment by Shadowedstalker** [comment]
How long have you been having the DPKG_LLOCKED error? that would account for not being able to ssh into the device as well. If the Cydia install went bad, Cydia would not have been able to install OpenSSH which would prevent you from sshing into port 44.

**Comment by UrBaN103** [comment]
> How long have you been having the DPKG_LLOCKED error? that would account for not being able to ssh into the device as well. If the Cydia install went bad, Cydia would not have been able to install OpenSSH which would prevent you from sshing into port 44.

I’ve been in DPKG_ LOCKED for about a week and just did a system restore rn. But I’m guessing that if I remain real I can get filza from ignition bc I can not instal tweaks at all in cydia.

**Comment by Shadowedstalker** [comment]
It sounds to me like you like you may need to hook the phone to iTunes and restore the phone entirely. if you choose to do this I suggest you set the phone up as New, Don't use an old back up. You could even update to 13.2.2
