### ISSUE TITLE
Notifications Not Appearing 

### ISSUE THREAD

**Issue by jakemonte** [checkra1n/BugTracker#355]
**What device + iOS version are you on?**

iPhone X 10,3, iOS 13.2.2
**What checkra1n version are you using?**
0.9.3.2 (latest) 
**What are the steps to reproduce the issue?**
1.
2.
3.
...

**What do you expect, and what is happening instead?**

Notifications aren’t appearing / showing up.

Shows in lockscreen but not homescreen / in apps.  

**Any other info, error logs, screenshots, ...?**

**Comment by jakemonte** [comment]
Tweaks: 
#——————————#
7-zip (POSIX): 16.02-1
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 0.7 Transitional (apt-key): 1:0
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
AudioSnapshotServer: 1.0.1
AutoUnlockX: 1.0.6
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bohemic NOIR: 1.0.3
Bohemic: 1.1.4
Bourne-Again SHell: 5.0.3-2
bzip2: 1.0.6-1
CA Certs: 0.0.2
Cephei: 1.13.1-2
checkra1n-Bootlogo: 1.0
CircleSettings: 1.0.1
Codling: 1.0.4
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cydia Installer: 1.1.32~b22
Cydia Substrate: 0.9.7100~b3
Cydia Translations: 1.1.32~b1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
DismissProgress: 1.0.4
DoubleCut: 0.5
Dragspring: 1.2.1
Essential: 0-1
file: 5.35-2
Filza File Manager 64-bit: 3.7.0-18
Find Utilities: 4.6.0-2
Flame: 1.3
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
HideBarX [Public]: 0.0.4
HomePlus Beta: 0.0.68
iCleaner Pro: 7.7.5
IconSupport: 1.11.1
IconSupportFix: 1.0.0
iOS Firmware: 13.2.2
iPhone Firmware (/sbin): 0-1
KSBA: 1.3.5-1
libcolorpicker: 1.6.4
libCSPreferences: 1.2.0
libidn2: 6.1.2-1
libmitsuha: 0.1.9
libnepeta: 0.1.1
libpackageinfo (SparkDev): 1.1.4
libplist: 2.0.0-2
libSparkAppList: 1.0.3
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
Locale Profiles in UTF-8: 1.0-1
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
MakeRespringsGreatAgain: 2.0
Mitsuha Infinity: 0.1.8-3
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
NewTerm 2 (iOS 10 – 12): 2.2.1
NoMoreSmallApps [Public]: 0.0.2
OpenSSH: 7.9p1-3
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
PreferenceLoader: 2.2.4~beta1
Profile Directory: 0-1
readline: 8.0-1
RocketBootstrap: 1.0.7~beta3
RomanPasscode: 2.1
sed: 4.5-1
shell-cmds: 118-8
ShortLook: 1.0.15.4
shuffle: 1.0.4
Snappy: 1.2
SnowBoard: 1.2.57~Beta1
Soda HS 17: 1.0
Soda Repo Icons: 1.2
Substrate Safe Mode: 0.9.6003
SwipeForMore: 1.1.10
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TechSupport Framework: 1.5.0.1-1
TranslucentCydia: 0.9.0-1
TweakCompatible for Zebra: 1.1.4
tweakCompatible: 0.1.5
UIKit Tools: 1.1.15-2
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
Viola Dark: 1.6
Viola: 1.9
wget: 1.19.5-2
XenInfo: 2.2.6
XZ Utils: 5.2.4-4
Zebra (BETA): 1.0~beta23-1
zip: 2.32-1
#——————————#

**Comment by DaJakerBoss** [comment]
Have you double-checked your notification settings? You could have DnD on. Do notifications work when in a non-jailbroken state? Does this affect all apps? Have you tried disabling all tweaks?

**Comment by jakemonte** [comment]
[UPDATE]

After some debugging, I have found that it was the tweak “XenInfo”  (just so everyone is aware) 

Thanks so much! This can now be closed.
