### ISSUE TITLE
Find my iPhone won't work

### ISSUE THREAD

**Issue by r3b00tl00p** [checkra1n/BugTracker#356]
**What device + iOS version are you on?**
iOS 13.2.2 on iPhone 7

**What checkra1n version are you using?**
0.9.3.2

**What are the steps to reproduce the issue?**
1. Jailbreak your iPhone with checkra1n
2. Go to http://icloud.com/find or on "Find My" app on another iDevice
3. Chose an action like "Play a sound" or "Mark as lost"
4. The iPhone won't execute the action and will crash on a black screen

**What do you expect, and what is happening instead?**
I'm expecting for my iPhone to ring nor to be marked as lost and it just crash

**Any other info, error logs, screenshots, ...?**

**Comment by DaJakerBoss** [comment]
Can you replicate the issue with Substrate Safe Mode on?

**Comment by r3b00tl00p** [comment]
It works now, so it was probably done by a bad tweak.
Thanks ;-)
