### ISSUE TITLE
Error 20 and Loader app crashing

### ISSUE THREAD

**Issue by CobreDev** [checkra1n/BugTracker#358]
**What device + iOS version are you on?**
iPhone 6 on iOS 12.4. Edit: Updated to 12.4.3 and still doesn't work.

**What checkra1n version are you using?**
Beta 0.9.3.2

**What are the steps to reproduce the issue?**
1. Open checkra1n
2. Follow the steps
3. Phone doesn't act like it's plugged in until after it boots up, meaning that checkra1n times out and gives error -20

**What do you expect, and what is happening instead?**
I expect it to jailbreak successfully, whereas it's throwing error -20. No tweaks load, but my jailbreak apps (Cydia, iCleaner Pro, Filza, etc.) all open. I've tried disabling all tweaks w/ iCleaner, but as soon as I hit "Apply", they enable themselves again. When I try to remove some tweaks in Cydia, it says "subprocess /usr/libexec/cydia/cydo returned an error code (2). Also the loader app crashes immediately on startup, which means that I can't restore rootFS.

**Any other info, error logs, screenshots, ...?**
![Screen Shot 2019-11-14 at 4 19 00 PM](https://user-images.githubusercontent.com/36574329/68896970-8c150580-06fa-11ea-9374-d3ab184a7422.png)

Jailbreaking with safe mode enabled also gives error -20.

Checkra1n beta 0.9.2 gives error -20 sometimes, but tweaks work fine, so I'm not sure what's wrong there.

Update: Beta 0.9.4 completes successfully, but tweaks don't load
Update 2: After reinstalling iCleaner Pro and respringing, tweaks load fine. I'm going to close this, but please don't delete it. If you are having the save problem I was, get beta 0.9.4 from here: https://assets.checkra.in/test/checkra1n%20beta%200.9.4.dmg

**Comment by paopaopo** [comment]
I am having the same problem using ios 12.4.3 ? It does not successful load Checkra1n on my iphone but shows my non activated iphone 6

**Comment by burntscarr** [comment]
It happens for me too, my issue was my charger kept unplugging slightly and the phone disconnected from my Mac over and over. Although nothing touched the charger so it wasn’t a hardware issue.

**Comment by CobreDev** [comment]
@burntscarr that sounds like a bad cable. Try again with a new cable
