### ISSUE TITLE
Bootloop on iPad (after cydia install)

### ISSUE THREAD

**Issue by diamkil** [checkra1n/BugTracker#36]
**What device + iOS version are you on?**
iPad 6th generation, iOS 13.2

**What are the steps to reproduce the issue?**
1. install cydia using the checkra1n app in slideover
2. update all packages
3. when going back to springboard it freezes
4. force restart device
5. bootlooping
...

**What do you expect, and what is happening instead?**
expected it to simply restart in non jailbroken state but it bootlooped instead

**Any other info, error logs, screenshots, ...?**

**Comment by Dawesy6000** [comment]
it says 'Some index files failed to download. They have been ignored, or old ones used instead' that's when i refresh data.

**Comment by nullpixel** [comment]
Hi, did you install any tweaks?

**Comment by diamkil** [comment]
> Hi, did you install any tweaks?

I installed zebra and added those repos: https://pastebin.com/84CGWU5N

then did upgrade all in zebra and it froze when exited out of the app, I then force restarted and it bootlooped

**Comment by nullpixel** [comment]
@diamkil you bootlooped because you added `https://electrarepo64.coolstar.org/` which installed the electra bootstrap over the top of your already bootstrapped device.

**Comment by Dawesy6000** [comment]
What about this for iPhone 7

**Comment by nullpixel** [comment]
@Dawesy6000 please let me know what tweaks/repos you have installed.

**Comment by Dawesy6000** [comment]
> Hi, did you install any tweaks?



> @Dawesy6000 please let me know what tweaks/repos you have installed.

I installs cleaner then tried to install cydia substrate and it says 'Depends com.saurik.substrate.safemode'

**Comment by Connor0p76** [comment]
Boot in safe mode and then restore and retry the jailbreak

**Comment by Dawesy6000** [comment]
> Boot in safe mode and then restore and retry the jailbreak

Safe mode?

**Comment by nullpixel** [comment]
Closing this because it's an issue with tweaks installed.
