### ISSUE TITLE
tweaks dont show up in setting

### ISSUE THREAD

**Issue by iliketurtules** [checkra1n/BugTracker#362]
apparently a lot people are having this issue. Installed PreferenceLoader and RocketBootStap still had the same problem. Then I tried to restore jailbreak and reinstalled the jailbreak still had the same problem. Tried almost everything I could find on the internet and still had the same problem. please help!

**Comment by scuty2000** [comment]
Please use the issue template.

**Comment by iliketurtules** [comment]
What device + iOS version are you on?
13.2.2

What checkra1n version are you using?
0.9.3.2

What are the steps to reproduce the issue?
1. Updated from ios 12.4 (unc0ver) to 13.2.2 
2. Jailbreaked smoothly with checkra1n but when i install tweaks they don't show up in my setting
3. Tweaks like Filza, Newtem2, icleaner that install straight to the homescreen work just fine but other tweaks dont show up in my setting 
4. I tried installing PreferenceLoader and RocketBootStap it didnt solve my issue 
5. I did a uicache and it still didnt solve my issue 
6. I changed some stuff in filza and still didnt solve my issue 


What do you expect, and what is happening instead?
I expect tweaks to install and show up in the setting so i can use them.

**Comment by Shadowedstalker** [comment]
Ok, first look in Checkra1n source, do you have Cydia Substrate?

If it's empty and you have no tweak settings, it's most likely a source conflict. remove all your sources except the main ones.

Now check the Checkra1n source.

If still missing do a "system restore" from Checkra1n. rejailbreak install Cydia and check without adding sources.

Check Checkra1n.

If it's there, make sure PreferenceLoader is installed and try a tweak.

Check your settings.

Preference Loader should be installed via http://rpetri.ch/repo/

**Comment by iliketurtules** [comment]
did all that and now I see cydia substrate in checkra1n but do i install cydia substrate first or PreferenceLoader?

**Comment by iliketurtules** [comment]
YESSSSSS SOLVED IT! THANK YOU SOOO MUCH!!!
