### ISSUE TITLE
Fix Tweak Settings Not Showing

### ISSUE THREAD

**Issue by Shadowedstalker** [checkra1n/BugTracker#364]
First look in Checkra1n source, do you have Cydia Substrate?

If it's empty and you have no tweak settings, it's most likely a source conflict. remove all your sources except the main ones.

Now check the Checkra1n source.

If still missing do a "system restore" from Checkra1n. rejailbreak install Cydia and check without adding sources.

Check Checkra1n.

If it's there, make sure PreferenceLoader is installed and try a tweak.

Check your settings.

Preference Loader should be installed via http://rpetri.ch/repo/

**Comment by moteshubham** [comment]
There is one more simple solution
1) Go to Cydia
2) Search for "Cydia Substrate"
3) Reinstall "Cydia Substrate" 
 ( If it gives any error while installing, reinstall again, it will install )
4) Search for "RocketBootstrap"
5) Then reinstall "RocketBootstrap"
6) Profit
That's it..
