### ISSUE TITLE
SSH Not working

### ISSUE THREAD

**Issue by jayden000** [checkra1n/BugTracker#366]
I am using the port 44 using iProxy and using this command: iproxy 4444 44. When trying to ssh into the device using: ssh root@localhost -p 4444 the ssh command gives me this error: ssh_exchange_identification: read: Connection reset by peer
and iProxy gives me this error: waiting for connection
accepted connection, fd = 7
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 98 (serial: ), port 44
Error connecting to device!

**Comment by OrkhanAlikhanov** [comment]
Try port 22 `iproxy 4444 22`

**Comment by nullpixel** [comment]
port is `22` locally for now
