### ISSUE TITLE
Stuck on "Checking if device is ready"

### ISSUE THREAD

**Issue by wxb1ank** [checkra1n/BugTracker#37]
**What device + iOS version are you on?**
iPhone 7, iOS 13.2.2

**What are the steps to reproduce the issue?**
1. Run **checkra1n.app** (or launch from CLI) with a device in DFU mode attached (iPhone 7)
2. Wait until the freeze

**What do you expect, and what is happening instead?**
I expect the jailbreaking process to continue. Instead, the program is "stuck" at this "Checking" stage.

**Any other info, error logs, screenshots, ...?**
The `checkra1n_gui` CLI only displays "Checkm8 Preparation stage". Any device disconnects during this freeze produce no GUI or CLI output. I am using a Hackintosh (though this *should* make no difference). I am on Mojave 10.14.6.

**Comment by fuomag9** [comment]
Managed to reproduced the same issue, in the last run I got #9

**Comment by Toooorch** [comment]
Can confirm, this issue occurred to me as well

**Comment by wxb1ank** [comment]
**Solved.** It is a USB controller issue, and possibly on my end. I switched from a USB 3.0 port to a USB 3.1 port, if that makes any difference -- it probably doesn't, as Hackintosh setups differ greatly.

**Comment by zotanmew** [comment]
@wxb1ank thank you, that actually solved the issue for me as well. (AMD Hackintosh)

**Comment by snowhawk1** [comment]
Having this issue on an iPhone 8+ running iOS 14.1. Checkra1n version 0.12.1 is installed and running on bare metal Arch Linux using KDE Plasma as a DE. Is it safe for me to unplug my device while this issue is occuring?
