### ISSUE TITLE
Install Cydia Bootstrap Error 11

### ISSUE THREAD

**Issue by rajbir012** [checkra1n/BugTracker#372]
**What device + iOS version are you on?**
iPhone X + iOS 13.2.2

**What checkra1n version are you using?**
0.9.3.2
**What are the steps to reproduce the issue?**
1. Enter DFU mode 
2. Start checkra1n
3. Open Checkra1n
4. Install Cydia

**What do you expect, and what is happening instead?**
Cydia should get installed but it gives Bootstrap Error 11

**Any other info, error logs, screenshots, ...?**
The jailbreak was previously running fine. I updated a tweak from Cydia (Live Weather Widget) and it asked to "Reboot Device" after the update is installed. After I rebooted, I have been unable to get it back into a jailbroken state. I did run in safe mode but it got rid of Cydia and now I cannot install Cydia.

**Comment by StateOfInstinct** [comment]
iPhone 7 + iOS 13.2.2


![BootstrapError11](https://user-images.githubusercontent.com/48070732/68919374-aebd1380-0726-11ea-89f2-74a8ae83c36b.gif)

**Comment by rajbir012** [comment]
Yes this is exactly what is happening. I do not have the option to reinstall. Just install.

**Comment by nullpixel** [comment]
You have an OTA update downloaded in settings. Remove it and then reboot stock.

**Comment by rajbir012** [comment]
Thank you for the response.

I can confirm that I do not have the OTA update downloaded. I went through the storage and there is no update. Tried multiple times. I even restored my iphone to before this issue was happening.

Still receiving Bootstrap Error 11 :(

**Comment by StateOfInstinct** [comment]
> Thank you for the response.
> 
> I can confirm that I do not have the OTA update downloaded. I went through the storage and there is no update. Tried multiple times. I even restored my iphone to before this issue was happening.
> 
> Still receiving Bootstrap Error 11 :(

I got it to work. I downloaded iMazing, 13.2.2 ispw and updated my firmware. No more Error 11
