### ISSUE TITLE
Bootstrap error OTA is prestaged to rootfs 

### ISSUE THREAD

**Issue by pWnDbym3rvyn** [checkra1n/BugTracker#373]
**What device + iOS version are you on?**
iPhone 10,3 + iOS 13.2.2

**What checkra1n version are you using?**
Checkra1n beta 0.9.4
**What are the steps to reproduce the issue?**
1. Follow on screen instructions to jailbreak
2. After the reboot completes the phone starts normally I.e stock iOS 
3. When try to open Checkra1n app and tap re-install cydia it keeps on crashing and if clicked the install cydia it throws the above error.
...

**What do you expect, and what is happening instead?**
It should boot jailbroken but doesn’t boot into jailbroken state. There are no OTA updates in the system. Neither there are any files present!

**Any other info, error logs, screenshots, ...?**

**Comment by pWnDbym3rvyn** [comment]
![FAA8EAA7-D128-40BE-B09B-D95DFD88F844](https://user-images.githubusercontent.com/49151026/68918576-badfba00-0794-11ea-9a2b-e834d5e6dd74.png)

**Comment by WesternIcelander** [comment]
How did you get onto iOS 13.2.2?  Not by OTA update is it?  OTA updates is one of the leading causes of failures, it's always best to restore using iTunes.  If you OTA'd to 13.2.2 you might want to do a DFU restore.

**Comment by pWnDbym3rvyn** [comment]
Thank you for your reply, yes it OTA’d but I found a way I think. I jailbroke via 0.9.1 downloaded iCleaner pro and cleaned the OTA files and then used 0.9.4 pointed out by Luca and it worked well!

**Comment by nullpixel** [comment]
This is not a good idea. The real fix is to remove the OTA update in settings and reboot stock, then jailbreak.

**Comment by pWnDbym3rvyn** [comment]
Do you think the DFU restore will be better?

**Comment by WesternIcelander** [comment]
DFU restore is always the best, but only do that next time you want to upgrade to a new firmware unless you’re having issues now that can’t be fixed any other way.
