### ISSUE TITLE
Tweaks Only Work with Downgraded Substrate Compatibility Layer/Metadata.Cb0

### ISSUE THREAD

**Issue by SwagJesus** [checkra1n/BugTracker#374]
**What device + iOS version are you on?**
13.2.2

**What checkra1n version are you using?**
0.9.3.2

**What are the steps to reproduce the issue?**
Upgrading Substrate compatibility layer in cydia causes Cydia to force close and cannot be opened up until metadata.cb0 in var/mobile/library/cydia is deleted via filzaescaped (iosninja). 

**What do you expect, and what is happening instead?**
I'm expecting to see tweaks in the settings app.

I have to delete metadata.cb0 in var/mobile/library/cydia folder, reinstall cydia via checkra1n & downgrade Substrate compatibility layer to get my tweaks working.

**Any other info, error logs, screenshots, ...?**
None. Hopefully this can be addressed. Thanks!

**Comment by kpwn** [comment]
Hey, this should be fixed in https://assets.checkra.in/test/checkra1n%20beta%200.9.4.1.dmg
