### ISSUE TITLE
everything seems corrupt in Cydia

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#375]
i have jailbroken my iphone 6S plus, however when i get into Cydia, I cannot add any repo sources. And when I open every repo source package everything is empty in nearly all of them. I tried to delete all the sources to then re-install them but I get the below error...so nothing is working and I cant get anything to add in sources...

![IMG_0772](https://user-images.githubusercontent.com/41420071/68931143-d55f6680-0787-11ea-8612-05dccf78aacf.png)

**Comment by WesternIcelander** [comment]
You might wanna check your internet connection?  No WiFi symbol in the status bar and no SIM card installed so no cellular data either?  Might that be why?

**Comment by ghost** [comment]
hi my wifi was actually working ... no sim...but wifi was 100% i will replicate the issue

**Comment by kpwn** [comment]
no route to host means your wifi is not in fact working. closing as this is is not a checkra1n issue.
