### ISSUE TITLE
Apple ID and Accounts logged out

### ISSUE THREAD

**Issue by MertCYLN** [checkra1n/BugTracker#379]
**What device + iOS version are you on?**
iPad 12.9” (2. gen) 256GB iOS 13.2.2

**What checkra1n version are you using?**

0.9.3.2

**What are the steps to reproduce the issue?**
1.it happened only once

**What do you expect, and what is happening instead?**

After I jailbreaked for the 3th time since it released (first time with this version of checkra1n) I saw that there is no logged in Apple ID, my shared photos are gone, apple music needs to login, notes are gone, all of my email accounts are deleted from mail.app
These are all I’ve noticed yet

**Any other info, error logs, screenshots, ...?**

**Comment by 4rtz1z** [comment]
Use the latest 0.9.4 it didn't logged out the account, check luca's tweet or search in one of the issue threads here

**Comment by nullpixel** [comment]
fixed in 0.9.4 beta, will be released soon

**Comment by MertCYLN** [comment]
Thanks 😊

**Comment by nullpixel** [comment]
0.9.5 beta is now available which fixed this issue!
