### ISSUE TITLE
iPhone 6 12.4.3 / checkra1n 0.9.4 - rear Camera dont work

### ISSUE THREAD

**Issue by arinanda** [checkra1n/BugTracker#380]
**What device + iOS version are you on?**
iPhone 6 + 12.4.3

**What checkra1n version are you using?**
0.9.4

**What are the steps to reproduce the issue?**
1. open the camera
2.
3.
...

**What do you expect, and what is happening instead?**
black screen. front camera is working

**Any other info, error logs, screenshots, ...?**

**Comment by raf1dd** [comment]
Open newterm then run su after that run ldrestart

**Comment by arinanda** [comment]
hi @raf1dd 

just tried to ldrestart but nothing changed, the rear camera still not working :(

**Comment by Siguza** [comment]
And the rear camera works when booting normally? If so, try using the safe mode in checkra1n.

**Comment by arinanda** [comment]
hi @Siguza 
yes it was :( ok, will try use safe mode, thanks for your advice! 👍

**Comment by raf1dd** [comment]
Happens to me a lot i just ldrestart and it fixes itself or just disable all tweaks from icleaner then reenable them, never had this issue before hopefully it gets fixed soon.

**Comment by Siguza** [comment]
Aight, I'll close this then as it seems to be a tweak issue.
