### ISSUE TITLE
An SSL error has occurred

### ISSUE THREAD

**Issue by yanhotdamn** [checkra1n/BugTracker#382]
**What device + iOS version are you on?**
iPhone 7, 13.2.2

**What checkra1n version are you using?**
0.9.4
**What are the steps to reproduce the issue?**
1. Install checkra1n on Mac
2. Follow all steps to jailbreak
3. Open checkra1n on iPhone
4. 'An SSL error has occurred and a secure connection to the server cannot be made'
...

**What do you expect, and what is happening instead?**
I expected to see Cydia there to be selected and downloaded, but it doesnt show. Only the above error

**Any other info, error logs, screenshots, ...?**
Worth noting, there is no simcard in this phone, only connected to wifi

**Comment by yanhotdamn** [comment]
Can you tell me why this is invalid?

**Comment by nullpixel** [comment]
it's likely your ISP/business blocking the site or typing to MITM it because assets.checkra.in has a valid SSL certificate

**Comment by yanhotdamn** [comment]
Thanks. Appreciate the feedback. 

- sent from my iPhone
