### ISSUE TITLE
tweaks cannot load on boot

### ISSUE THREAD

**Issue by sandbox404** [checkra1n/BugTracker#383]
**What device + iOS version are you on?**
iPhone10,1 iOS 12.4

**What checkra1n version are you using?**
0.9.4
**What are the steps to reproduce the issue?**
1. fresh jailbreak
2. install some tweaks
3. reboot then reenable jailbreak status
...

**What do you expect, and what is happening instead?**
auto load tweaks when re-enable jailbreak status. it works fine in 0.9.2 but now I must run sbreload or ldrestart to load tweaks.

**Any other info, error logs, screenshots, ...?**

**Comment by kpwn** [comment]
Hey, give this a shot, it should fix this: https://assets.checkra.in/test/checkra1n%20beta%200.9.4.1.dmg

**Comment by sandbox404** [comment]
> Hey, give this a shot, it should fix this: https://assets.checkra.in/test/checkra1n%20beta%200.9.4.1.dmg

works great, thanks!!
