### ISSUE TITLE
Home screen error

### ISSUE THREAD

**Issue by GerardPolloRebozado** [checkra1n/BugTracker#384]
**What device + iOS version are you on?**
I'm on iPad 2018 with ios 13.1.13

**What checkra1n version are you using?**
0.9.3

**What are the steps to reproduce the issue?**
1.Swipe to another home screen page
2.And one of the pages disappears
3.To solve you need to respring
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

[Video of the issue](https://drive.google.com/file/d/13Av5GhqoLOcV4b1pSuT0f7rvGDGuvpOQ/view?usp=drivesdk)

**Comment by nullpixel** [comment]
what tweaks do you have installed?

**Comment by GerardPolloRebozado** [comment]
![4BC7F064-3480-4531-8295-09B62F8F0024](https://user-images.githubusercontent.com/37554513/69001011-051d8400-08d8-11ea-847a-7ee3f90864cd.png)
![Uploading 30B809C2-C5D2-4F8D-B43A-ED40B5A73C18.png…]()

**Comment by nullpixel** [comment]
Try updating to 0.9.5 and enabling safe mode. Does the issue persist?
