### ISSUE TITLE
Battery details cannot be displayed！

### ISSUE THREAD

**Issue by biankobe24** [checkra1n/BugTracker#387]
**What device + iOS version are you on?**
13.2.2

**What checkra1n version are you using?**
0.9.4

**Any other info, error logs, screenshots, ...?**
use checkra1n0.9.3.2 jailbrea, Battery details cannot be displayed,always loading
![QQ图片20191116013735](https://user-images.githubusercontent.com/9103468/68963387-c7562800-0811-11ea-9079-a81dcd352e59.png)

**Comment by nullpixel** [comment]
closing - is an issue with a tweak.
