### ISSUE TITLE
Charging with Power Delivery Charger Doesn't Work

### ISSUE THREAD

**Issue by 4rtz1z** [checkra1n/BugTracker#388]
**What device + iOS version are you on?**
iPhone X (10,6) 13.2.2 
iPad Pro 10.5 Wifi 13.2.2

**What checkra1n version are you using?**
0.9.4

**What are the steps to reproduce the issue?**
1. Plugged the cable (using Apple 29W Charger + USB C to Lightning)
2. 
3.
...

**What do you expect, and what is happening instead?**
Charging

**Any other info, error logs, screenshots, ...?**

**Comment by 4rtz1z** [comment]
Still happening with the latest 0.9.5

**Comment by kratos9394** [comment]
yes,0.9.3.2 is better

**Comment by tpljeron** [comment]
Same issue for me again.. v0.9.3.2 is fine, v0.9.5 no fast charging and need to trust my Mac again every 5 seconds. iPhone X 13.2.2

**Comment by 4rtz1z** [comment]
Fixed on the latest v0.9.6, thanks everyone !!
