### ISSUE TITLE
LDrestart Puts iPhone Into a Infinite Boot

### ISSUE THREAD

**Issue by nxtsite** [checkra1n/BugTracker#389]
**What device + iOS version are you on?**

iPhone 6s Plus iOS 13.2.2

**What checkra1n version are you using?**

checkra1n beta 0.9.3.2

**What are the steps to reproduce the issue?**
1. Jailbreak with checkra1n
2. Install Any Terminal you want
3. Type su , after entering root , type “ldrestart”
4. Now just get a infinite boot
...

**What do you expect, and what is happening instead?**

I expect LDrestarting my device but i get an infinite boot

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
try 0.9.5 with safe mode enabled

**Comment by nxtsite** [comment]
Thanks!
