### ISSUE TITLE
Air Drop on iPhone X 13.2.2 broken

### ISSUE THREAD

**Issue by kurtbain250** [checkra1n/BugTracker#390]
**What device + iOS version are you on?**
iPhone X 13.2.2

**What checkra1n version are you using?**
0.9.3.2
**What are the steps to reproduce the issue?**
1. boot jailbroken
2. open control centre 
3. try to enable air drop

**What do you expect, and what is happening instead?**
air drop should enable, remains off. Can reproduce. Works in stock mode without jailbreak enabled

**Any other info, error logs, screenshots, ...?**
Only seems to be an iPhone X issue, tested on iPhone 7 Plus 12.4 working, tested on iPhone 6S 13.3 beta 2 working all using checkra1n 0.9.3.2

**Comment by kpwn** [comment]
does this persist with version 0.9.4?

**Comment by kunal2991** [comment]
AirDrop works perfectly for me. Same device - iOS Version - Checkra1n Version.

**Comment by nullpixel** [comment]
Update to 0.9.5 and try that out!

**Comment by kurtbain250** [comment]
I can confirm 0.9.5 has corrected the issue on my iPhone X running 13.2.2. Also just for fun I tested my other devices an had the same results. No issues with airdrop. I should of mentioned in my first post that my iOS 13.3 (iPhone 8,1) device had no substrates tweaks installed (which may have been why I only had issues on my X) and my 12.4 (iPhone 9,4) does has a bunch of substrate tweaks as-well but tweak compatibility is better on this device. Cant rule out this may have been a 13.x + substrate tweak compatibility issue with my iPhone X which could be why user kunal2991 didnt have the same results.
Anyways whatever you did in 0.9.5 has resolved the issue so thank you kindly!
Also thank you both (qwerty and nullpix) for your continued contributions to the community. It means allot to the silent majority. 
Ill be more diligent in the future with reporting issues if i come across any.
And qwerty I have a iPhone 6,1 10.2 yalu still >.< someday if your bored and feeling nostalgic I would love to see that device ra1n SON lol.
Thanks again, take care.

**Comment by vinnie12341234** [comment]
iPhone X, iOS 13.3.3,  v0.9.7.

Airdrop works fine in non JB state but stuck on 'off' in JB state.

**Comment by vinnie12341234** [comment]
@Siguza please see above, not sure if this should be reopened?
