### ISSUE TITLE
My college website doesn't load with JB

### ISSUE THREAD

**Issue by RaspberryTech01** [checkra1n/BugTracker#392]
Hi all, my college website won't load when using a JB. Using checkRa1n ios 13.2.2 and unc0ver ios 12.2. I have tried disabling all tweaks in icleaner (the ones that aren't needed such as the ones in green) but that did nothing. I have also tried the duckduckgo browser, chrome and ecosia to no avail. When I tried puffin web browser (has some sort of VPN inside of it) it loads alright. I have tried loading the website with a VPN as well but that has done nothing either.

What can I do? Previously on unc0ver, I had the option to turn off tweaks after jailbroken (for some reason they were still active though) and the website loaded. What could be the issue here?

**Comment by boierito** [comment]
Please use the checkra1n bug tracker template.

**Comment by Siguza** [comment]
If the issue exists on both checkra1n and Unc0ver then it's independent of the jailbreak - as such, I'm closing this as invalid.

I suggest you download checkra1n 0.9.5 and try with the "Safe Mode" checkbox in the GUI to see if that fixes it. If it does, it's definitely a tweak.
