### ISSUE TITLE
iPad 6 - Timed Out waiting for bootstrap (Error: -20)

### ISSUE THREAD

**Issue by jvaglivelo** [checkra1n/BugTracker#393]
**What device + iOS version are you on?**
iPad 6, Wifi, 32GB, 13.2.2

**What checkra1n version are you using?**
0.9.3-0.9.5
0.9.2 works occasionally for me and 0.9 is the most reliable, working every time

**What are the steps to reproduce the issue?**
1. Run checkra1n
2. Freeze on booting... and get error -20
3.
...

**What do you expect, and what is happening instead?**
Expected device to boot

**Any other info, error logs, screenshots, ...?**
This problem only seems to be happening with the iPad 6th gen after reading replies in [issue/291](https://github.com/checkra1n/BugTracker/issues/291), so I thought it'd be better to make a separate issue for iPad 6th Gen owners.

**Comment by Xador123** [comment]
I have exactly the same problem !

**Comment by Bram-Brooks** [comment]
Same here, exact same problem. My iPhone 6 works fine on 0.9.5 first try. iPad 6th gen hasn't worked since 0.9.3 and later.

**Comment by DubWarrior03** [comment]
Same issue here. Same device, same problem.

**Comment by nullpixel** [comment]
Known bug, will be fixed in a future update :)

**Comment by maurediaz96** [comment]
I have same device, same problem, same version.... I need help please

**Comment by maurediaz96** [comment]
this is what happens!!!! iPad 6ta iOS 13.2.2 Chekra1n 0.9.5...

<img width="484" alt="Captura de pantalla 2019-11-16 a las 23 06 15" src="https://user-images.githubusercontent.com/56781270/69002889-ce3e7280-08c5-11ea-8455-f5115ed039f5.png">
![IMG_6768](https://user-images.githubusercontent.com/56781270/69002890-d3032680-08c5-11ea-8108-4503d94826db.JPG)

**Comment by brado** [comment]
Same problem here, experienced on three different iPhones, all using checkra1n 0.9.5:

- iPhone 6S, iOS 13.2.2
- iPhone 6, IOS 12.4.3
- iPhone 6, iOS 12.4.3

Note that it was very difficult to get any of these three devices into DFU mode, especially with the GUI present. I only was able to achieve it with the GUI once, but it seemed easier to perform the DFU sequence from an iPhone not in recovery mode within the GUI -- I used the CLI. But regardless, whether GUI or CLI, same eventual error.

**Comment by nullpixel** [comment]
@brado: this issue is only for the iPad 6th gen. Your issue sounds like incorrect DFU mode entry. Are you using a USB C to lightning cable? Because you should be following the steps in the UI and not manually entering DFU mode.

**Comment by rangeroverct** [comment]
Same issue, disabling tweaks via iCleaner Pro in safemode and re-enabling them while not in safe mode works. Also, ldrestart doesn`t work and you have to reboot your phone if you attempt to LDrestart or SSH in and killall -SEGV SpringBoard.

**Comment by brado** [comment]
@nullpixel forgive me, I thought the error (and its presence on other devices) would be significant. To your comments: I am using a 2019 MacBook Pro, macOS Catalina v10.15.1, and using a USB-C to lightning cable. 

The only reason I even attempted entering DFU mode manually and then using the CLI is because I spent 2-3 hours repeatedly following the steps in the UI and none of the three phones would ever enter DFU mode at all. In fact, the one phone I could get to enter DFU mode via the UI wasn't any of these phones, but an iPhone 8, when entered immediately, no problem. But none of my iPhone 6(S) would enter DFU mode via the UI. I imagine I tried each device well over 10 times apiece, but no DFU mode for those. 

None of these phone devices have ever been jailbroken or have any prior tweaks on them at all. These are vanilla default iOS installs. If there's a known issue with these devices, or compatibility with Catalina, that would be good to know, because for whatever reason, checkra1n 0.9.5 does not seem to work with this combination.

**Comment by nullpixel** [comment]
@brado: it's the USB C cable. Some cables unfortunately do not work well with entering DFU mode, so you will need to try and use a USB A -> C adapter and using a normal cable.  Sorry about that.

**Comment by brado** [comment]
@nullpixel copy that. Thanks for the tip. I'll give it a go again today and report back -- hopefully success!

**Comment by zarox85** [comment]
Same issue i have 2 x iPad 6 Wifi, 128GB, on 13.2.2 
Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)

**Comment by brado** [comment]
@nullpixel you were right as rain -- switched out the USB-C to lightning cable (note, this was the official Apple brand cable) for a standard USB lightning cable connected to the USB-C multi-adapter (USB, HDMI, USB-C), and that did it. First time, all four phones, worked like a charm. No problems getting any of the devices immediately into DFU mode using the UI instructions. Thanks so much!

**Comment by brado** [comment]
@zarox85 - full disclosure: I know nothing about the internals of checkra1n, so I'm just trying to contribute incidental info from my experience, in case it might help you. I did encounter this same error again on another device after first removing unc0ver (restoring the rootFS), and then upgrading iOS to a new version (12.1.2 to 12.4.3). Following this, when I ran checkra1n, I could enter DFU mode just fine, but had the same -20 timeout error as you. I performed an "Erase all Content and Settings", then after the restore, ran checkra1n again, and everything ran smoothly. Dunno if that will help you, but that was my experience. Good luck!

**Comment by zarox85** [comment]
@brado i tried to erase all content, performed full restore, got the same error with the bootstrap time out. :/

**Comment by Bram-Brooks** [comment]
Why does it have to be iPad 6 only though haha, the agony.

**Comment by ghost** [comment]
iPad 6th:

Currently only works with checkra1n 0.9.2 flawlessly.
Unable to work with checkra1n 0.9.3 ~ 0.9.5

checkra1n is compatible with iOS 13.2.3 and older version.
Even the version 0.9.5 for now showing the message that only support iOS 13.2 and oldest version, it's still work by running following commands in Terminal under DFU mode:
/Applications/checkra1n.app/Contents/MacOS/checkra1n_gui

If you need newest version, the team is working on supporting in future releases.

**Comment by nullpixel** [comment]
Fixed in 0.9.6
