### ISSUE TITLE
libnotificationd continually crashes 13.2.2

### ISSUE THREAD

**Issue by Tobicake** [checkra1n/BugTracker#396]
**What device + iOS version are you on?**
iPhone X 13.2.2

**What checkra1n version are you using?**
0.9.5
**What are the steps to reproduce the issue?**
1.jailbreak
2.no notifications while in jailbreak
3.
...

**What do you expect, and what is happening instead?**
There should be any notifications. Instead notifications just show up in lockscreen. No sound, no vibration, no push.

**Any other info, error logs, screenshots, ...?**
Already uninstalled Cr4shed which seems to produce the same bug but didn’t fixed it. No other tweaks installed which hook into the notification.

**Comment by kpwn** [comment]
does booting your device with Safe Mode change anything?

**Comment by Tobicake** [comment]
> does booting your device with Safe Mode change anything?

Yes it works in Safe Mode. So it seems to be an tweak? I've already uninstalled some other tweaks that could possibly hook into the notifications in any way but nothing changed.

**Comment by kpwn** [comment]
I'd say it's probably either a tweak or a supporting library.

**Comment by HeyItsMicro** [comment]
you are correct. I figured this out a few days ago, its libnotifications which is a dependency for cr4shed. I would recommend using CrashReporter instead. @Tobicake please close this issue

**Comment by Tobicake** [comment]
> you are correct. I figured this out a few days ago, its libnotifications which is a dependency for cr4shed. I would recommend using CrashReporter instead. @Tobicake please close this issue, thanks.

I've uninstalled Cr4shed and it's dependency but it was still not fixed. Now I've restored RootFS and installed checkra1n again and all the tweaks I had before (without Cr4shed) and it works again. Thank you guys.

Edit: It was XenInfo 🤪
