### ISSUE TITLE
ipad gen 7 dfu mode issue

### ISSUE THREAD

**Issue by rcpag1103** [checkra1n/BugTracker#398]
**What device + iOS version are you on?**
ipad gen 7 ios 13.2.2

**What checkra1n version are you using?**
0.9.5
**What are the steps to reproduce the issue?**
1.previous update allowed me to start the checkra1n app if my device is in dfu mode already
2.in 0.9.5, the start button was greyed out and need to put my device into normal or recovery mode first
3. now, it wont allow me to be in dfu mode whatever tries i have done.
...

**What do you expect, and what is happening instead?**should be working normal like the steps i did. 

**Any other info, error logs, screenshots, ...?**

**Comment by kpwn** [comment]
Using a device already in DFU mode is no longer supported. Please enter either recovery or normal mode and start from there.
