### ISSUE TITLE
iPhone 7 Plus gets stuck in booting stage

### ISSUE THREAD

**Issue by lehoe** [checkra1n/BugTracker#399]
**What device + iOS version are you on?**
iPhone 7 Plus (ios 13.2) 
Previously worked, however after a restart this issue started happening.

**What checkra1n version are you using?**
Tried all versions. 

**What are the steps to reproduce the issue?**
1. After the device has been put into DFU mode successfully. Checkra1n app started to jailbreak my iPhone.
2. Everything seems normal until the checkra1n app on my mac says it finished the jailbreak however my device's screen is still stuck in the booting stage forever until after around 10 mins it automatically restarts. (Booting...) 
3. After restarting, the phone is back to normal, however, this issue keeps happening every time I tried to jailbreak.

(It was once jailbroken with checkra1n 0.9, however, ever since I restarted it does not work anymore.)
![WechatIMG28](https://user-images.githubusercontent.com/57595931/68986832-80daea80-085e-11ea-9eff-f075583e79a9.png)

**Comment by kpwn** [comment]
Try safe mode, this is likely a bad tweak. Am closing this since i am almost certain, reopen if it's not the case.
