### ISSUE TITLE
[Unc0ver => Checkra1n error] Bootstrap Error: OTA is prestaged to rootfs

### ISSUE THREAD

**Issue by reteps** [checkra1n/BugTracker#400]
**What device + iOS version are you on?**
X running 13.2.2

**What checkra1n version are you using?**
0.9.5 beta
**What are the steps to reproduce the issue?**
1. Be running unc0ver on ios 12.x.x
2. Disable OTA blocking & restore RootFS (so that i am able to update IOS)
3. Download update to 13.2.2 on RootFS mode & update phone to 13.2.2 (go through setup, etc.)
4. Jailbreak using Checkra1n through MacOS instructions
5. Attempt to install Cydia through checkra1n app

**What do you expect, and what is happening instead?**
I get the error `Bootstrap Error: OTA is prestaged to rootfs. Remove OTA and reboot to stock then try again.` instead of cydia :(

**What are my options at this point?**
* Is a full restore the only method to fix this? I didn't save IPSW blobs for 12.x.x.

**Comment by TempAccountNull** [comment]
> **What device + iOS version are you on?**
> X running 13.2.2
> 
> **What checkra1n version are you using?**
> 0.9.5 beta
> **What are the steps to reproduce the issue?**
> 
> 1. Be running unc0ver on ios 12.x.x
> 2. Disable OTA blocking & restore RootFS
> 3. Download update to 13.2.2 & update phone
> 4. Install Checkra1n
> 5. Install Cydia through checkra1n app
> 
> **What do you expect, and what is happening instead?**
> I get the error `Bootstrap Error: OTA is prestaged to rootfs. Remove OTA and reboot to stock then try again.` instead of cydia :(
> 
> **What are my options at this point?**
> 
> * Is a full restore the only method to fix this? I didn't save IPSW blobs for 12.x.x.

**Peace of mind**
This doesn’t just jailbreak with Cydia installed. 

**Why**
You cannot jailbreak on iOS <version> with the 13.2.2 (iOS x) update waiting to install! This would cause a **potential** bootloop as the OTA has to use a **remount** to install the update, trying to jailbreak without this protection **can** risk device boot loops. 

Note: you won’t get Cydia immediately after jailbreaking with checkra1n. This is (**user installed only** and only once!)

**Only options**
1. Either install 13.2.2
2. delete the update file in storage

**Deleting OTA files**
0. Go to settings->general-> storage -> ‘iOS 13.2.2’ click it, hit delete update
1. Jailbreak in DFU as normal
2. When in “stock jailbreak” launch ‘checkra1n‘ Application
3. Click Cydia
4. Install Cydia.
5. Done.

**Comment by reteps** [comment]
> Go to settings->general-> storage -> ‘iOS 13.2.2’ click it, hit delete update

The update was installed before I started the checkra1n jailbreak, sorry for the confusion(i am now on 13.2.2) 
> When in “stock jailbreak” launch ‘checkra1n‘ Application
Click Cydia
Install Cydia.
Done.

I attempted to install cydia through the checkra1n app, that is where I got the error. @TempAccountNull

**Comment by nicfitzgerald** [comment]
I get the same errors and, as far as I know, I had no prior Jailbreak on the device. I am unable to install Cydia due to an OTA/rootfs error.

**Comment by reteps** [comment]
My solution, although annoying was to 
1) backup my phone to a computer
2) restore phone to factory
3) read from the backup after phone was restore

I then jailbroke it normally with checkra1n

**Comment by WeedyWeedSmoker** [comment]
@reteps Oh... I was hoping one would have an idea of the file(s) causing the error to appear...

I'm in indonesia right now with no wi-fi, an iPad Pro 2 512GB full of apps, and 15GB of internet with my phone costs $6,5...

Restoring, for me, is NOT a practical option!

**Comment by WeedyWeedSmoker** [comment]
@Siguza @nullpixel @TempAccountNull @kpwn After using the older checkra1n 0.9.2 successfully and checking my filesystem, the "/private/var/MobileSoftwareUpdate" folder is populated, is it the culprit?

I'm tempted to delete its contents but cannot afford having to restore due to a required file missing right now!

_BTW, there's no OTA update in the iPad storage options for me to delete, and I'm on iOS 13.2.2..._

-------------------------

EDIT: It was indeed the culprit... Fixed! 

I left these files and folders untouched inside the /private/var/MobileSoftwareUpdate directory : 

```
ƒ Controller
-- (empty)
ƒ db
-- (empty)
ƒ Firmware
-- (empty)
ƒ Hardware
ƒ- Battery
ƒ-- Library
ƒ--- Preferences
----- com.apple.batteryhealthdata.plist
- last_update_result.plist
ƒ lastOTA
-- ota_tolerated_failures.plist
ƒ mnt1
-- (empty)
ƒ MobileAsset
ƒ- AssetsV2
ƒ-- downloadDir
---- (empty)
- nvram.plist
- restore.log
```

Please keep in mind that this may be a little different depending on the hardware/software combination you're using... 😉

**Comment by nicfitzgerald** [comment]
I just tried @WeedyWeedSmoker's method of using `checkra1n 0.9.2` and it worked like a charm! I'm sure it's a similar issue with the folder existing but the update not being visible in `General -> iPhone Storage`.

**Comment by nullpixel** [comment]
do ***not*** do this. 0.9.2 lacks the checks for this and they were deliberately added to prevent bootloops. you likely _will_ experience a bootloop if you heed this advice.

closing this issue as there is no real fix. sometimes you actually just have to update the device because getting the device to revert the rootfs changes is harder than it's worth.

**Comment by nullpixel** [comment]
@WeedyWeedSmoker: that folder literally has a mount point for your rootfs and deleting things in it will likely also do it to your disk. do ***not*** do this.

**Comment by WeedyWeedSmoker** [comment]
@nullpixel I jailbroke an iPhone 5s just to check what files were in there to be safe... I hope my iPad is safe, but I couldn't afford to restore it in the situation I'm in...

I immediately jailbroke again with checkra1n 0.9.5 and it worked fine, but I sure understand your concern... Anyway, hope the team finds a way to help other people in my previous situation without having them restore, and thank you for everything you're doing... You're great ! 😉
