### ISSUE TITLE
Checkra1n Doesn't Delete Cydia When Using "System Restore" (0.9.3.5) / Safe Mode Not Working

### ISSUE THREAD

**Issue by SwagJesus** [checkra1n/BugTracker#402]
I've had this problem since 0.9.2 where I'm trying to do a fresh install of Checkra1n, but i'm still left with the Cydia icon on the springboard. 

I re-jailbreak> go to checkra1n & press "Cydia". 

It says "Cydia is already installed". Pressing "Reinstall Cydia" force closes Checkra1n.

I re-jailbreak and try to go into safe mode, the regular springboard comes up.

Any help on this would be grateful. Thanks!

**Comment by IamArayel** [comment]
Same for me (iPhone 8+ iOS 13.2.2).
Try to "jailbreak"/install Checkra1n with version 0.9.2, install Cydia, then "restore System" and Cydia will be gone.

**Comment by Shadowedstalker** [comment]
Before you do a "system Restore" open Terminal 

Type ssh root@YourIP (look on device, Settings-Wifi-info)
If it asks you a question type yes.
default password is alpine
Type uicahce -u /Applications/Cydia.app
type exit

now when you do the "system restore" Cydia will be gone.

**Comment by SwagJesus** [comment]
Thanks! I used ssh over usb to do something similar to this. 
("uicache --all" & then "kill SpringBoard")

I was totally unaware you could do it without a usb. 

Since i've done this checkra1n & cydia have been working fine. Thanks again.

**Comment by Shadowedstalker** [comment]
If you have any issue with Tweak Icons, you can also install NewTerm 2 and SSH from the device itself.

**Comment by tazaraz** [comment]
I've got the problem as well, however due to some weird crash of unknown origin, I ended up being jailed again. Besides not removing Cydia when using "System Restore", "the Reinstall Cydia" does also not work.

I can still install checkra1n, and sometimes it even gives me the "Install Cydia" option on top of the "Reinstall Cydia" one, but even "Installing" Cydia again, opening Cydia is not spoken of, yet crashing is. Jailbreak did work before the weird crash, though I am on iOS 13.2.3.

**Comment by nullpixel** [comment]
The issue with Cydia remaining on the homescreen after a rootfs restore is fixed in 0.9.6

**Comment by mailinglists35** [comment]
does “Restore System” only rolls back rootfs (/) from apfs snapshot, or does it also afect the other partitions? (goal being “can I safely Restore System and keep existing /private/var data untouched?”)

sorry for the spam - i just setup a mdm supervised phone that was jailbroken before and I did not shift restore but instead “erase all content and settings” which left the rootfs untouched and with cydia/icleaner & friends under /Applications) - so I just want to fix cydia or even reset it completely
