### ISSUE TITLE
Tweaks Only Work With Downgraded Substrate Compatibility Layer 

### ISSUE THREAD

**Issue by SwagJesus** [checkra1n/BugTracker#404]
**What device + iOS version are you on?**
13.2.2

**What checkra1n version are you using?**
0.9.3.5

**What are the steps to reproduce the issue?**
1. Jailbreak. Install Cydia. Install a tweak. 

**What do you expect, and what is happening instead?**
I'm expecting to see tweaks in the settings menu, but do not see any. 
As soon as I downgrade Substrate Compatibility Layer, tweaks work.

**Any other info, error logs, screenshots, ...?**
I'm not able to boot into safe mode via checkra1n. I'm also not able to delete the cydia icon upon using system restore in checkra1n. 
When I try to do a fresh install of Checkra1n, it says Cydia is already installed.

**Comment by SwagJesus** [comment]
I was able to get my tweaks working again!

There seems to be some issue with electra/coolstar's repo & checkra1n. 

Once i deleted his repo, all of his tweaks that come with cydia got deleted & I was able to install tweaks while having them show up in settings. 

However, I'm still not able to boot into safe mode via checkra1n : (

Not sure if these two issues are related.

**Comment by Siguza** [comment]
Can you try again with 0.9.5? It has a checkbox in the GUI that should 100% work for safe mode.

**Comment by SwagJesus** [comment]
That's what i'm currently using now (0.9.5).

It's not booting into safe mode. The regular springboard comes up. 

Also, after adding tweaks it seems my tweaks have disappeared from settings : (

I'm still able to install tweaks & remove tweaks but no tweaks that I have installed are active.

**Comment by Siguza** [comment]
That is precisely what safe mode does though.  
If you want tweaks to be enabled again, you'll have to boot without safe mode.

**Comment by SwagJesus** [comment]
Damnnnn, so no "safe mode" on the status bar indicating safe mode?

**Comment by kpwn** [comment]
No, as that uses MobileSubstrate. We just skip code injection altogether.
