### ISSUE TITLE
Wont let me update Cydia to Cydia Substrate.

### ISSUE THREAD

**Issue by Dawesy6000** [checkra1n/BugTracker#41]
When i try to install Cydia Substrate from 'checkra1n Substrate Repo' in sources it just says 'The requested modifications cannot be applied due to required dependencies or conflicts that cannot be automatically found or fixed' and then it says Continue Queuing. Please help me.

**Comment by nullpixel** [comment]
Hi, you already opened #35 so I'm closing this as a duplicate.
