### ISSUE TITLE
checkra1n 0.9.5 beta crashes on start

### ISSUE THREAD

**Issue by michaelmantz** [checkra1n/BugTracker#414]
**What device + iOS version are you on?**
Iphone 6s iOS 13.2.2

**What checkra1n version are you using?**
0.9.5 beta

**What are the steps to reproduce the issue?**

downloaded from checkra.in and started

**What do you expect, and what is happening instead?**
it crashes

**Any other info, error logs, screenshots, ...?**

Process:         launchd [202]
Path:            /Applications/checkra1n.app/Contents/MacOS/checkra1n_gui
Identifier:      kim.cracksby.checkra1n
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [97]

Date/Time:       2019-11-16 15:24:49.927 +0100
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          2248 sec
Crashes Since Last Report:           6
Per-App Crashes Since Last Report:   6
Anonymous UUID:                      08001B9C-0E95-4C9D-8097-B4C4DEF36626

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_PROTECTION_FAILURE at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 1

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 156
    thread_create: 0
    thread_set_state: 0

Model: iMac5,1, BootROM IM51.0090.B09, 2 processors, Intel Core 2 Duo, 2.16 GHz, 2 GB, SMC 1.9f4
Graphics: ATI Radeon X1600, ATY,RadeonX1600, PCIe, 128 MB
Memory Module: BANK 0/DIMM0, 1 GB, DDR2 SDRAM, 667 MHz, 0x0000000000000000, 0x000000000000000000000000000000000000
Memory Module: BANK 1/DIMM1, 1 GB, DDR2 SDRAM, 667 MHz, 0x0000000000000000, 0x000000000000000000000000000000000000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x87), Broadcom BCM43xx 1.0 (5.10.131.36.15)
Bluetooth: Version 4.0.8f17, 2 service, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: WDC WD2500JS-40TGB0, 250,06 GB
Parallel ATA Device: MATSHITADVD-R   UJ-85J
USB Device: Built-in iSight, apple_vendor_id, 0x8501, 0xfd400000 / 2
USB Device: 2.4GHz 2way RF Receiver, 0x1bcf  (Sunplus Innovation Technology Inc.), 0x05ca, 0x3d100000 / 2
USB Device: Hub in Apple Extended USB Keyboard, apple_vendor_id, 0x1003, 0x5d100000 / 2
USB Device: Apple Extended USB Keyboard, apple_vendor_id, 0x020b, 0x5d130000 / 3
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x8206, 0x7d100000 / 2
USB Device: IR Receiver, apple_vendor_id, 0x8240, 0x7d200000 / 3

**Comment by DanyL** [comment]
We’re supporting macOS Yosemite (10.10) and up, macOS Lion (10.7) is not supported.
