### ISSUE TITLE
[ATV4] When waking from sleep, Apple TV 4 is unjailbroken

### ISSUE THREAD

**Issue by Rov3r** [checkra1n/BugTracker#415]
**What device + iOS version are you on?**
Apple TV 4 (HD) - 13.2

**What checkra1n version are you using?**
0.9.3.2-tvos-1

**What are the steps to reproduce the issue?**
1. Sleep device
2. Wait for a prolonged sleep time
3. Wake the ATV by remote

**What do you expect, and what is happening instead?**
nitoTV app is gone, along with other tweaks

**Any other info, error logs, screenshots, ...?**
No error logs. Just unjailbroken.

**Comment by 0x41c** [comment]
That’s probably because after a prolonged time the Apple TV slowly shuts itself down. If it gets farther then a software shut down then you’ll have to rejailbreak

**Comment by Rov3r** [comment]
The thing is I leave it for only an hour, then I have to rejailbreak. When I wake it (after an hour) it then immediately reboots.

**Comment by Rov3r** [comment]
Issue was caused by incompatible Kodi app. Uninstalled and stability was restored.
