### ISSUE TITLE
Bootstrap Error When Installing Cydia

### ISSUE THREAD

**Issue by rajbir012** [checkra1n/BugTracker#416]
**What device + iOS version are you on?**
iPhone X + iOS 13.2.2

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1. Install Checkra1n
2. Install cydia
3. bootstrap error

**Any other info, error logs, screenshots, ...?**
On the latest iOS 13.2.2 and there is no OTA update file to delete from settings. 

![9BEB4CE9-88FA-4845-BCA7-D783CCB53C0A](https://user-images.githubusercontent.com/57785575/68997542-92bb8e00-085c-11ea-9952-cd53051fd8e2.png)

**Comment by nullpixel** [comment]
remove the OTA from settings (if there is one) and reboot.

**Comment by rajbir012** [comment]
Thanks NullPixel. 

But there is no OTA update in settings. I’ve also rebooted multiple times and still same error.
