### ISSUE TITLE
(Big Issue) IPhone Not Bootstrapped!

### ISSUE THREAD

**Issue by 0x41c** [checkra1n/BugTracker#420]
### Before We Start:
* ik that this is a different format... I don’t care
* people who say that this isn’t a big issue is lying
### What Happened 

What happened was I was having issues with the tweaks I was using and I figured that I should just start over. But! Once I got into the checkra1n app at first it wouldn’t open, then once I reinstalled the jailbreak it wouldn’t show the button. 
That means that the iPhone (_even though it was clearly jailbroken_) was not bootstrapped. 

### All it would show is this :
![68998750-3a3fbd00-086b-11ea-90e3-dd38ee0e55b3](https://user-images.githubusercontent.com/56287516/69000738-4470b400-0889-11ea-814a-d447e75447b9.png)

### In The End 

(Is it possible to feel claustrophobia while using a phone?) 

Not being able to do anything makes me annoyed. On top of that, tweaks aren’t even working!! This stinks and I would really like it if you guys could help!

## The Details 

**IOS: 13.2.2**

**Checkra1n Version: 0.9.5**

**Iphone Hardware: iPhone 6s**

**A9 chip**

**SoC: s8000**

**Comment by Shadowedstalker** [comment]
Try Checkra1n 0.9.3.2 and see if that helps you for the moment.

https://checkra.in/releases/0.9.3.2-beta

**Comment by 0x41c** [comment]
**Ok**
I’ll try it

**Comment by nullpixel** [comment]
the button only shows when the system has been bootstrapped

**Comment by 0x41c** [comment]
So I’ve been jailbroken but not completely bootstrapped


Hmmmm

**Comment by 0x41c** [comment]
I just tried the older version of checkra1n.... that didn’t work either.

**Comment by 0x41c** [comment]
I just restored my iPhone

:(
