### ISSUE TITLE
smart keyboard doesn't work while charging 

### ISSUE THREAD

**Issue by briopapa** [checkra1n/BugTracker#424]
**What device + iOS version are you on?**
Ipad pro12.9+ios13.2.2

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1.jailbreak 
2.charging 
3.keyboard doesn't work 
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by ghost** [comment]
Are you following the DFU instructions in the app?

**Comment by briopapa** [comment]
Of course I am. And when it finished, it said all done.

**Comment by nullpixel** [comment]
0.9.6 resolves this issue
