### ISSUE TITLE
iPad 6ta error -20 bad tweak

### ISSUE THREAD

**Issue by maurediaz96** [checkra1n/BugTracker#425]
I had the jailbreak and installed a damaged tweak I had to proceed to reactivate the jailbreak again I get an error -20 from there restore with iTunes to jailbreak again from scratch and keep giving error -20 and check the option safely and even So it gives error -20 what can I do I have iPad 6th generation. Thanks in advance

**Comment by DanyL** [comment]
Duplicate of #393
