### ISSUE TITLE
Cydia crashes after checkra1n is installed 

### ISSUE THREAD

**Issue by sotjos3610** [checkra1n/BugTracker#426]
**What device + iOS version are you on?**
IPhone X 13.2.2

**What checkra1n version are you using?**
9.5

**What are the steps to reproduce the issue?**
1.
2.
3.
...

**What do you expect, and what is happening instead?** cydia started randomly crashing so i “restored” from checkra1n app and re jail broke and the issue is still happening 

**Any other info, error logs, screenshots, ...?**

**Comment by gnutnos98** [comment]
#305 this may help you, see the comment!

**Comment by sotjos3610** [comment]
Worked, thx
