### ISSUE TITLE
I just updated checkra1n to 0.9.5 and cydia app is work but no tweak are running

### ISSUE THREAD

**Issue by bumb1e** [checkra1n/BugTracker#432]
**What device + iOS version are you on?**
iPhone 8 Plus + iOS 13.2.2

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1. just update by download latest version
2. start rejailbreaking (no restore system files)
3. open setting app after jailbreak and other app that have tweak
...

**What do you expect, and what is happening instead?**
there's no tweak in setting app and an app that have tweak isn't running

**Any other info, error logs, screenshots, ...?**
no

**Comment by bumb1e** [comment]
I trying to reinstall some of cydia package. guessing like Cydia Installer, Substrate and respring after reinstall. It's Work! and my tweaks are back and functional.

**Comment by Filtar2000** [comment]
same problem for me

**Comment by Filtar2000** [comment]
i tried to reinstall cydia installer, preference loader, rocketbootstrap but it doesn't work

**Comment by coenkcore** [comment]
> I trying to reinstall some of cydia package. guessing like Cydia Installer, Substrate and respring after reinstall. It's Work! and my tweaks are back and functional.

If your problem has been solved please close this issue.
