### ISSUE TITLE
Tweaks don't show up in settings

### ISSUE THREAD

**Issue by Filtar2000** [checkra1n/BugTracker#433]
**What device + iOS version are you on?**
Iphone 7 plus- ios 13.1.2

**What checkra1n version are you using?**
checkra1n beta 0.9.5

**What are the steps to reproduce the issue?**
1. Install tweaks 
2. respring
3. Check settings
...

**What do you expect, and what is happening instead?**
I expect to see my tweaks in settings but there aren't. However i see them in preference folder

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Issues with tweaks are not related to checkra1n and should be reported to the respective author - in this case PreferenceLoader, I guess?
