### ISSUE TITLE
Banner notifications freezing whole phone

### ISSUE THREAD

**Issue by StefanNienhuis** [checkra1n/BugTracker#44]
**What device + iOS version are you on?**
iOS 13.2

**What are the steps to reproduce the issue?**
1. Get a notification while using your iPhone

**What do you expect, and what is happening instead?**
I expect my iPhone to continue like it normally does, but instead it freezes the whole phone for about 20 seconds and resprings.

**Any other info, error logs, screenshots, ...?**
No.

**Comment by nullpixel** [comment]
Could you let us know more information, such as any tweaks you have installed?

**Comment by StefanNienhuis** [comment]
This happened before I even installed anything. I just booted, installed cydia and I was just browsing cydia when I got a notification and it froze.

**Comment by nullpixel** [comment]
Do you have any logs?

**Comment by StefanNienhuis** [comment]
Where would I see those?

**Comment by StefanNienhuis** [comment]
Looks like a re-jailbreak did the trick. Thanks for the help anyways.
