### ISSUE TITLE
cydia crashing every time I try to open it

### ISSUE THREAD

**Issue by UrBaN103** [checkra1n/BugTracker#442]
**What device + iOS version are you on?**
iPhone 6s plus + IOS 13.1.2

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1.download youtube tools
2.going to change and downloading the preferenceloaders from electra (which I was dumb and still did it)
3.Cydia crashes every time I try to open it and I don't know what to do
...

**What do you expect, and what is happening instead?**
I expect to open cydia and try to remove it but instead cydia keeps crashing

**Any other info, error logs, screenshots, ...?**
no

**Comment by MeSHol** [comment]
> **What device + iOS version are you on?**
> iPhone 6s plus + IOS 13.1.2
> 
> **What checkra1n version are you using?**
> 0.9.5
> 
> **What are the steps to reproduce the issue?**
> 1.download youtube tools
> 2.going to change and downloading the preferenceloaders from electra (which I was dumb and still did it)
> 3.Cydia crashes every time I try to open it and I don't know what to do
> ...
> 
> **What do you expect, and what is happening instead?**
> I expect to open cydia and try to remove it but instead cydia keeps crashing
> 
> **Any other info, error logs, screenshots, ...?**
> no

**Comment by Shadowedstalker** [comment]
Check #354
