### ISSUE TITLE
Haptic button issues.

### ISSUE THREAD

**Issue by H-sana** [checkra1n/BugTracker#447]
**What device + iOS version are you on?**
13.2.2

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1. Jailbreak with chechra1n
2.
3.
...

**What do you expect, and what is happening instead?**

I thought re-jailbreaking with the latest 0.9.5 fix the issue but I’m getting now haptic feedback when I press the home button, some times it doesn’t even work. When I boot into stock my home button is fine. 

**Any other info, error logs, screenshots, ...?**

**Comment by DanyL** [comment]
Did you follow the on screen instructions to cleanly enter DFU mode?

**Comment by nullpixel** [comment]
will reopen upon response

**Comment by 11five** [comment]
Yes I followed the steps right. I just re jailbroke another iPhone 7 and the same issue persists even on the the latest checkra1n version.

**Comment by freakorio** [comment]
Same as mine  ,i use 0.9.7 for iphone 6s and the home button not working but i'm able to enter recovery mode which mean the home button are working perfectly.

**Comment by Marvin2012** [comment]
Same problem the jailbreak works, but after that I tried icloud bypass after that the phone reboot and home button and power button not work... Think this problem is just on IOS 13.3 cause on IOS 12.4 on another iPhone it worked perfekt

**Comment by over40fb** [comment]
I have the same issue. Home button haptic feedback doesn´t work on ios 13.3 and using 0.9.7 for iphone 7. works perfectly fine when I reboot and without jailbreak.

**Comment by acil55** [comment]
> I have the same issue. Home button haptic feedback doesn´t work on ios 13.3 and using 0.9.7 for iphone 7. works perfectly fine when I reboot and without jailbreak.

same problem waiting solution

**Comment by acil55** [comment]
> Same as mine ,i use 0.9.7 for iphone 6s and the home button not working but i'm able to enter recovery mode which mean the home button are working perfectly.

same waiting solution

**Comment by arturonox** [comment]
Same issue, hope it gets fixed at some point.

**Comment by sirfred333** [comment]
> 
> 
> Same as mine ,i use 0.9.7 for iphone 6s and the home button not working but i'm able to enter recovery mode which mean the home button are working perfectly.

Same problem for me... waiting for solution... Thank you.

**Comment by TonyHarvey** [comment]
I have the same issue on an Ipad Air 2 :(

**Comment by MamaButtsey** [comment]
Same issue for iPhone 6s iOS 13.3. Will there be a fix?

**Comment by JeankeVG** [comment]
Same thing on iPhone 6S 13.3, any fix yet?

**Comment by prathamchopra12** [comment]
I followed all these instructions terminal was unable to find usbmux and i googled it and tried the command with usbmuxd. Everything ahead went good but then the home button stopped working after respring. I tried to power off but it didn’t let me slide to power off or use assistive touch. They appeared but touch wasn’t letting me slide. Assistive touch too opened and closed quickly. I removed battery to restart the device but same problem appeared. Upon reading on the web I restored it with itunes but still home button isn’t working. So now I can’t put it in dfu either to retry this. I am stuck. I am using an iphone 6s on 13.3.1. Please help?

**Comment by over40fb** [comment]
Found the solution that worked for me. Found it on Reddit. Look at the picture. I’ve just disabled Cercube from ICleaner. 
![910500C5-2A79-4A91-9E2A-EC0D8555FB50](https://user-images.githubusercontent.com/57912093/78979372-05831980-7b1c-11ea-95a2-fcdee7b132b8.jpeg)

**Comment by dvrtech-us** [comment]
I have the same issue and did cleanly enter DFU. I was able to reproduce it on 2 iPhone 6s plus phones and the latest version of IOS
