### ISSUE TITLE
-20 error Hackintosh?

### ISSUE THREAD

**Issue by cookietvlove** [checkra1n/BugTracker#449]
**What device + iOS version are you on?**
iPhone 8 Plus IOS 13.0

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1. pluged in my phone 
2. let checkra1n put me in recovery 
3.followed  their steps to get into dfu 
...

**What do you expect, and what is happening instead?**
I expected for it to jailbreak my phone but it just glitched my phone out and freezed it 
After me freaking out thinking I broke my phone I hard reset it and I got the -20 error 

**Any other info, error logs, screenshots, ...?** btw I’m running high Sierra on my dell pc 

 ![BB71345D-B7B5-4E10-A4F6-807CDB8DAD0B](https://user-images.githubusercontent.com/57891688/69034980-5b053100-0997-11ea-8077-3701c08649a2.jpeg)

**Comment by ghost** [comment]
Without any problems on Hackintosh from  Dell XPS 13, works with checkra1n version 0.9.2

**Comment by Bram-Brooks** [comment]
Hackintosh does not cause this issue.

**Comment by cookietvlove** [comment]
So how do I fix this

**Comment by ghost** [comment]
> So how do I fix this

There is no issue with Hackintosh...

**Comment by nullpixel** [comment]
closed as a dupe of #9
