### ISSUE TITLE
Cant unlock Mac with Apple Watch

### ISSUE THREAD

**Issue by hansdampf01** [checkra1n/BugTracker#452]
**What device + iOS version are you on?**
13.2.2 // Mac OS Catalina 10.15.1

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1.On Mac: Settings--> Security&Privacy--> General: Checkbox for Use your Apple Watch to unlock apps and your Mac.
2.Type in PW of Mac
3.Error states your Mac cant communicate with your Apple Watch
...

**What do you expect, and what is happening instead?**
Expect no error message - Unlock App installation and Mac via double Tap on Apple Watch

**Any other info, error logs, screenshots, ...?**
![2019-11-18_12-41-03](https://user-images.githubusercontent.com/55264284/69049671-b6b7d480-0a00-11ea-9f3e-f0eb488b1dc6.png)

**Comment by DanyL** [comment]
Does it still happen when your'e booting stock?

**Comment by hansdampf01** [comment]
No seems not to work when booting stock.
I even unpaired the Watch and repaired it. Still no luck.

**Comment by DanyL** [comment]
I suggest you to set an appointment with Apple Genius Bar and ask for support, this is unrelated to checkra1n.

**Comment by sterling0x1** [comment]
Turn handoff in iPhone settings off and back on. That will fix your problem.
