### ISSUE TITLE
Cydia dpkg could not configure error

### ISSUE THREAD

**Issue by abdulk4d1r** [checkra1n/BugTracker#453]
**What device + iOS version are you on?**
iPhone 7 iOS 13.2.2

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1. After Jailbreaking using Checkra1n in safe mode (and tried verbose mode), install Cydia
2. Try to install a tweak. It seems that 7 changes from apt.bingner.com source cannot upgrade.
3. Error comes up
'Could not configure 'dpkg:iphoneos-arm'
Could not perform immediate configuration 'dpkg:iphoneos-arm'. Please see man 5 apt.conf under APT::Immediate-Configure for details (2)
Could not configure 'dpkg:iphoneos-arm'.
...

**What do you expect, and what is happening instead?**
Expected behaviour is Cydia to update relevant dependencies and launch tweak/gui, but cant install any tweeks at all.

**Any other info, error logs, screenshots, ...?**
![IMG_4389](https://user-images.githubusercontent.com/36931281/69054650-f9c77700-0a03-11ea-8795-6817143db06d.PNG)

**Comment by GODLIKE5** [comment]
you deleted some files didnt you

**Comment by abdulk4d1r** [comment]
@GODLIKE5  - Nope, all i did was jailbreak using checkra1n 0.9.5 and then install cydia. Tried to then install a tweak, it would then come up with error. I have even jailbroken it 5 times as some said it may fix, but hasnt

**Comment by abdulk4d1r** [comment]
I fixed this by backing up then restoring my iphone using finder on the Mac. 
Then re-jailbreaking as per BAU steps and then installing cydia. It works. Closing ticket

**Comment by ThinkDigitalSoftware** [comment]
Would this be considered a solution?

**Comment by abdulk4d1r** [comment]
@ThinkDigitalSoftware could be. But the only reason this happened was due to a previous jailbreak. So cause is due to previous jailbreak (electra) and this is the only fix. So kind of self inflicted issue.

**Comment by hehacks** [comment]
Hi abdulk4d1r,

Can you please share your contact details? like mail ID , I am currently facing the same issue need your help on this asap.

**Comment by hehacks** [comment]
> I fixed this by backing up then restoring my iphone using finder on the Mac.
> Then re-jailbreaking as per BAU steps and then installing cydia. It works. Closing ticket

I need you help on this, please share me the steps to my mail: pentestbugs@gmail.com
