### ISSUE TITLE
Files in /private/var/mobile not readable via SSH

### ISSUE THREAD

**Issue by sraka1** [checkra1n/BugTracker#458]
**What device + iOS version are you on?**

iPhone 6S, 12.4.1
Darwin Kernel Version 18.7.0: Mon Aug 19 22:24:08 PDT 2019; root:xnu-4903.272.1~1/RELEASE_ARM64_S8000 iPhone8,1

**What checkra1n version are you using?**

0.9.5 beta

**What are the steps to reproduce the issue?**
1. SSH into device (using instructions and `iproxy`) as `root`
2. Mount / as r/w using `mount -o rw,union,update / && echo "" >> /.mount_rw`
3. Try to read a file from `/private/var/mobile` using `cat` or copy it using `scp` (i.e. copying file from `/private/var/mobile/Media/DCIM/` to host computer)
4. Receive `cat: IMG_0239.JPG: Operation not permitted`

**What do you expect, and what is happening instead?**

I expect to receive/be able to read the file, but it looks like some sort of FS security layer prevents files from being accessed. 
The use case is a broken phone (broken screen), which is now jailbreakable (thanks! 👍) and has some photos I'd like to recover.

**Any other info, error logs, screenshots, ...?**

I am unaware of the state of the phone due to broken screen, however the broken digitizer made it "auto-press" buttons all the time (you can hear the clicks), so it's likely to be in a disabled state (if lock screen PIN was pressed too many times).

**Comment by nullpixel** [comment]
you need to unlock the phone due to data protection, sorry :/

**Comment by sraka1** [comment]
@nullpixel is this an iOS limitation or an intentional safety check by checkra1n?

**Comment by nullpixel** [comment]
iOS limitation, enforced by the SEP. Absolutely nothing you can do about it, sorry.
