### ISSUE TITLE
iMessage 3D Touch on images not working

### ISSUE THREAD

**Issue by ticozz** [checkra1n/BugTracker#460]
**What device + iOS version are you on?**
iPhone X - 13.2.2

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1. Receive an image through iMessage in chat view 
2. 3D touch on the image nothing happens
3. Phone thinks you are long pressing
...

**What do you expect, and what is happening instead?**
Long press effect shows instead

**Any other info, error logs, screenshots, ...?**

**Comment by m0420** [comment]
Normal iOS 13 behavior. Try installing FxxkHapticTouch from Cydia

**Comment by ticozz** [comment]
Installed it, doesn't fixed the issue, and FxxkHapticTouch's description as far as I know is disabling the HapticTouch and it didn't it kept working normally elsewhere. In this case it's just not working on the images in iMessage. 

N.B: It works everywhere else until now on the system except there

**Comment by nullpixel** [comment]
lol iOS 13 removed this from the messages app

**Comment by ticozz** [comment]
Thanks for finally explaining, I just couldn’t find where they announced this! Now it’s time to request this tweak 🤣.. Thanks a lot man
