### ISSUE TITLE
Loader app crash

### ISSUE THREAD

**Issue by Bluefire3010** [checkra1n/BugTracker#461]
**What device + iOS version are you on?**

iPhone 6s iOS 13.2.2
**What checkra1n version are you using?**

0.9.5 beta
**What are the steps to reproduce the issue?**
1.jailbreak normaly
2.the loader app take times to appear on the springboard
3.then the app crash, later the app work and now the app just crash 
...

**What do you expect, and what is happening instead?**
The app should be here right after the jailbreak and do not crash 

**Any other info, error logs, screenshots, ...?**Crash logs 

> {"blame":[],"app_name":"loader","timestamp":"2019-11-18 19:49:35.54 +0100","app_version":"1.0","slice_uuid":"24a49fc9-783e-31a0-b212-f721bc8745a6","adam_id":0,"build_version":"1","bundleID":"kjc.loader","share_with_app_devs":false,"is_first_party":true,"bug_type":"109","os_version":"iPhone OS 13.2.2 (17B102)","incident_id":"F7939484-4426-4C64-8BC5-1442BBE79285","name":"loader","symbolicated":true}
Incident Identifier: F7939484-4426-4C64-8BC5-1442BBE79285
CrashReporter Key:   5a98bcd99efd3b8114aef43daa468cfccc688291
Hardware Model:      iPhone8,1
Process:             loader [6986]
Path:                /private/var/binpack/Applications/loader.app/loader
Identifier:          kjc.loader
Version:             1 (1.0)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           kjc.loader [909]

Date/Time:           2019-11-18 19:49:35.3103 +0100
Launch Time:         2019-11-18 19:49:34.9563 +0100
OS Version:          iPhone OS 13.2.2 (17B102)
Release Type:        User
Baseband Version:    7.11.01
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001b0d06710
Termination Signal: Trace/BPT trap: 5
Termination Reason: Namespace SIGNAL, Code 0x5
Terminating Process: exc handler [6986]
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0       libxpc.dylib                  	0x1b0d06710 0x1b0ceb000 + 0x1b710	// _xpc_api_misuse + 0x54
1       libxpc.dylib                  	0x1b0d06708 0x1b0ceb000 + 0x1b708	// _xpc_api_misuse + 0x4c
2       libxpc.dylib                  	0x1b0d05614 0x1b0ceb000 + 0x1a614	// xpc_endpoint_copy_listener_port_4sim + 0x0
3       loader (*)                    	0x104bac18c 0x104ba4000 + 0x818c	// -[LoaderdClient connect] + 0x60
4       loader (*)                    	0x104bad2d4 0x104ba4000 + 0x92d4	// -[RootViewController viewDidLoad] + 0xa40
5       UIKitCore                     	0x1b4b74d4c 0x1b4791000 + 0x3e3d4c	// -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 0x64
6       UIKitCore                     	0x1b4b7985c 0x1b4791000 + 0x3e885c	// -[UIViewController loadViewIfRequired] + 0x3a8
7       UIKitCore                     	0x1b4aeb780 0x1b4791000 + 0x35a780	// -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 0xa8
8       UIKitCore                     	0x1b4aeba8c 0x1b4791000 + 0x35aa8c	// -[UINavigationController _startTransition:fromViewController:toViewController:] + 0xb0
9       UIKitCore                     	0x1b4aec8c0 0x1b4791000 + 0x35b8c0	// -[UINavigationController _startDeferredTransitionIfNeeded:] + 0x470
10      UIKitCore                     	0x1b4aedc04 0x1b4791000 + 0x35cc04	// -[UINavigationController __viewWillLayoutSubviews] + 0xa4
11      UIKitCore                     	0x1b4ad10dc 0x1b4791000 + 0x3400dc	// -[UILayoutContainerView layoutSubviews] + 0xe0
12      UIKitCore                     	0x1b5627604 0x1b4791000 + 0xe96604	// -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 0x85c
13      QuartzCore                    	0x1b7b7578c 0x1b7a25000 + 0x15078c	// -[CALayer layoutSublayers] + 0x11c
14      QuartzCore                    	0x1b7b7b908 0x1b7a25000 + 0x156908	// CA::Layer::layout_if_needed(CA::Transaction*) + 0x1e0
15      QuartzCore                    	0x1b7b86528 0x1b7a25000 + 0x161528	// CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 0x88
16      QuartzCore                    	0x1b7aceed0 0x1b7a25000 + 0xa9ed0	// CA::Context::commit_transaction(CA::Transaction*, double) + 0x130
17      QuartzCore                    	0x1b7af8bbc 0x1b7a25000 + 0xd3bbc	// CA::Transaction::commit() + 0x2a4
18      UIKitCore                     	0x1b51a9bac 0x1b4791000 + 0xa18bac	// __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 0x50
19      CoreFoundation                	0x1b10a75f8 0x1b0ffe000 + 0xa95f8	// __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 0x14
20      CoreFoundation                	0x1b10a6d98 0x1b0ffe000 + 0xa8d98	// __CFRunLoopDoBlocks + 0x108
21      CoreFoundation                	0x1b10a2014 0x1b0ffe000 + 0xa4014	// __CFRunLoopRun + 0x44c
22      CoreFoundation                	0x1b10a18a0 0x1b0ffe000 + 0xa38a0	// CFRunLoopRunSpecific + 0x1d0
23      GraphicsServices              	0x1baff9328 0x1baff6000 + 0x3328	// GSEventRunModal + 0x68
24      UIKitCore                     	0x1b5192740 0x1b4791000 + 0xa01740	// UIApplicationMain + 0x790
25      loader (*)                    	0x104bb181c 0x104ba4000 + 0xd81c	// 0x0000d7c4 + 0x58
26      libdyld.dylib                 	0x1b0f2c360 0x1b0f2b000 + 0x1360	// start + 0x4

Thread 1:
0       libsystem_pthread.dylib       	0x1b0e49acc 0x1b0e3b000 + 0xeacc	// start_wqthread + 0x0

Thread 2:
0       libsystem_pthread.dylib       	0x1b0e49acc 0x1b0e3b000 + 0xeacc	// start_wqthread + 0x0

Thread 3:
0       libsystem_pthread.dylib       	0x1b0e49acc 0x1b0e3b000 + 0xeacc	// start_wqthread + 0x0

Thread 4 name:  com.apple.uikit.eventfetch-thread
Thread 4:
0       libsystem_kernel.dylib        	0x1b0f00634 0x1b0efd000 + 0x3634	// mach_msg_trap + 0x8
1       libsystem_kernel.dylib        	0x1b0effaa0 0x1b0efd000 + 0x2aa0	// mach_msg + 0x48
2       CoreFoundation                	0x1b10a704c 0x1b0ffe000 + 0xa904c	// __CFRunLoopServiceMachPort + 0xd8
3       CoreFoundation                	0x1b10a216c 0x1b0ffe000 + 0xa416c	// __CFRunLoopRun + 0x5a4
4       CoreFoundation                	0x1b10a18a0 0x1b0ffe000 + 0xa38a0	// CFRunLoopRunSpecific + 0x1d0
5       Foundation                    	0x1b13e1824 0x1b13da000 + 0x7824	// -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 0xe4
6       Foundation                    	0x1b13e1704 0x1b13da000 + 0x7704	// -[NSRunLoop(NSRunLoop) runUntilDate:] + 0x58
7       UIKitCore                     	0x1b522b158 0x1b4791000 + 0xa9a158	// -[UIEventFetcher threadMain] + 0x98
8       Foundation                    	0x1b15120c4 0x1b13da000 + 0x1380c4	// __NSThread__start__ + 0x350
9       libsystem_pthread.dylib       	0x1b0e461d0 0x1b0e3b000 + 0xb1d0	// _pthread_start + 0x7c
10

**Comment by quilenle** [comment]
Was here https://github.com/checkra1n/BugTracker/issues/385

**Comment by Bluefire3010** [comment]
> Was here #385

I see, thanks !
