### ISSUE TITLE
substrated crash, no apps will open

### ISSUE THREAD

**Issue by m1stadev** [checkra1n/BugTracker#465]
**What device + iOS version are you on?**
iPhone 8 Plus running iOS 13.2.2.

**What checkra1n version are you using?**
0.9.5 (latest as of 11/18/2019)

**What are the steps to reproduce the issue?**
No real steps, because I don’t know how it happened.

**What do you expect, and what is happening instead?**
I expect my apps to open, but they freeze on the launch screen for a couple minutes then crash

**Any other info, error logs, screenshots, ...?**
[Crash log (pulled from CrashReporter)](https://psty.io/p?q=b9ecb)

**Comment by m1stadev** [comment]
note: I don’t know that the substrated crash was the cause of none of my apps opening, but I’m assuming it is because it crashed around the same time my apps stopped opening

**Comment by Siguza** [comment]
The link you posted says `Non-Image content-type returned`.  
Also this sounds like an issue with either Substrate or a tweak, but not checkra1n.

**Comment by m1stadev** [comment]
sorry about that, here’s the link https://psty.io/p?q=b9ecb

it probably is just a substrate issue, but I don’t really know where else to put substrate issues, so I figured here would be good

**Comment by nullpixel** [comment]
please file this issue with saurik.
