### ISSUE TITLE
checkra1n Bug on 13.2.3

### ISSUE THREAD

**Issue by tens0rfl0w** [checkra1n/BugTracker#466]
**What device + iOS version are you on?**
iPhone X + iOS 13.2.3

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1. Restore rootFS
2. Update OS from 13.2.2 to 13.2.3
3. Re-Jailbreak (CLI-Mode)

**What do you expect, and what is happening instead?**
Touchscreen doesn't recognizes any touch, can't get behind lock screen, so no further errors.

**Any other info, error logs, screenshots, ...?**
/

**Comment by Siguza** [comment]
Sounds like you're entering DFU without fully resetting the SoC. Please try following the steps shown in the GUI, we put them there for good reason.

**Comment by tens0rfl0w** [comment]
Never mind, works now, entered recovery mode manually and then Jailbroke. So checkra1n on 13.2.3 works for me.
