### ISSUE TITLE
DPKG_LOCKED when trying to update packages in Cydia

### ISSUE THREAD

**Issue by UrBaN103** [checkra1n/BugTracker#468]
**What device + iOS version are you on?**
iPhone 6s Plus + iOS 13.1.2

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1. Reinstalled checkra1n loader
2. Opened cydia to see 11 packages needed to be updated
3. Tried to update but got DPKG_LOCKED error
...

**What do you expect, and what is happening instead?**
Expected files to be updated but kept getting errors

**Any other info, error logs, screenshots, ...?**
![EB161EC4-0489-4BB3-A4E5-33CBD6A54F2B](https://user-images.githubusercontent.com/47288535/69109829-b71a9480-0a2d-11ea-9144-3133a5db1ec0.png)
![8C0897E8-A990-4B0F-9B65-28D495587F97](https://user-images.githubusercontent.com/47288535/69109830-b71a9480-0a2d-11ea-97f2-36300b285648.png)
![C1A5C727-E1CE-4E17-B5BF-DF487CEAEC37](https://user-images.githubusercontent.com/47288535/69109831-b7b32b00-0a2d-11ea-8cb3-e1401a1dfaed.png)
![05141EF2-467F-4B6A-91A9-1F9F451E06F3](https://user-images.githubusercontent.com/47288535/69109832-b7b32b00-0a2d-11ea-80be-de08246d3f8e.png)

**Comment by nullpixel** [comment]
did you use a previous jailbreak before?

**Comment by UrBaN103** [comment]
> did you use a previous jailbreak before?

Not for a while. I did use unc0ver on iOS 12. But I think that the problem is when I accidentally downloaded Electra prefrenceloaders it crashed cydia and I had to reinstall checkra1n jailbreak a couple times before I could’ve opened cydia. But now I keep getting DPKG_LOCKED when I try to update the packages.

**Comment by johnwatson122** [comment]
@UrBaN103 
Try method 2 replacing ifile with filza:
[](https://www.cydiaos.com/fix-cydia-dpkg-was-interrupted-error/)

**Comment by UrBaN103** [comment]
> @UrBaN103
> Try method 2 replacing ifile with filza:

Can you elaborate on that?

**Comment by johnwatson122** [comment]
@UrBaN103 

Try this method using filza instead of Ifile:

2) Launch the iFile application from apps drawer and tap the HOME button from bottom bar.

3) tap the back button from top-left corner to open up “var” folder.

4) now search and open “lib” folder > then “dpkg” folder.

5) From inside the dpkg folder open the “updates” folder and delete everything inside it.

6) now go back to dpkg folder and open up each and every folder one by one and search if there is any file name starting with “000” (zero) or “1111” , if you found any – delete them immediately.

7) Now close the iFile app.

8) Reboot your i-device. (Don’t go for respring, make a complete reboot)

After the reboot try opening cydia and I hope now it won’t show any DPKG error. If it still showing the same error then probably you have missed any file to deleted that starts with 000.
(copied)

**Comment by UrBaN103** [comment]
> @UrBaN103
> 
> Try this method using filza instead of Ifile:
> 
> 1. Launch the iFile application from apps drawer and tap the HOME button from bottom bar.
> 2. tap the back button from top-left corner to open up “var” folder.
> 3. now search and open “lib” folder > then “dpkg” folder.
> 4. From inside the dpkg folder open the “updates” folder and delete everything inside it.
> 5. now go back to dpkg folder and open up each and every folder one by one and search if there is any file name starting with “000” (zero) or “1111” , if you found any – delete them immediately.
> 6. Now close the iFile app.
> 7. Reboot your i-device. (Don’t go for respring, make a complete reboot)
> 
> After the reboot try opening cydia and I hope now it won’t show any DPKG error. If it still showing the same error then probably you have missed any file to deleted that starts with 000.
> (copied)

can i get ifile from a website without using cydia?

**Comment by johnwatson122** [comment]
you can use tweakbox to download filza. You can also use SSH to do this but I don't know how

**Comment by johnwatson122** [comment]
Oh and I'm just curious: did you ever press the "erase all content and settings" on your device?

**Comment by UrBaN103** [comment]
> Oh and I'm just curious: did you ever press the "erase all content and settings" on your device?

Yeah I did thinking the cydia icon would go away

**Comment by johnwatson122** [comment]
@UrBaN103 
You should NEVER ever do that. It always creates problems with cydia. I would recommend that you do a full restore in iTunes and re jailbreak with checkra1n

**Comment by UrBaN103** [comment]
> @UrBaN103
> You should NEVER ever do that. It always creates problems with cydia. I would recommend that you do a full restore in iTunes and re jailbreak with checkra1n

Ooof i was planning to stay on iOS 13.1.2 for like over jailbreaks lol but I’ll try fully restoring my phone

**Comment by johnwatson122** [comment]
@UrBaN103 
You are waiting for unc0ver? Well it's ok. Just remember from now on not to erase content and settings

**Comment by UrBaN103** [comment]
> @UrBaN103
> You are waiting for unc0ver? Well it's ok. Just remember from now on not to erase content and settings

Your method of fully restoring my device worked and now my problem does not exist. Thanks man

**Comment by nullpixel** [comment]
yeah this issue is caused by corruption to dpkg files, probably from adding the Electra repo.
