### ISSUE TITLE
When Restart Phone The Jailbreak Missing

### ISSUE THREAD

**Issue by NeoVilsonWong** [checkra1n/BugTracker#469]
**What device + iOS version are you on?**
IphonX 

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1.all
2.
3.
...

**What do you expect, and what is happening instead?**
when restart phone the jailbreak missing?

**Any other info, error logs, screenshots, ...?**

**Comment by punpunpunpunpun** [comment]
Checkra1n is a semi-tethered jailbreak, so if you restart your iPhone, you need to run checkra1n.app using your Mac.
