### ISSUE TITLE
Cercube for Youtube - Do NOT Install!!

### ISSUE THREAD

**Issue by mpacepa** [checkra1n/BugTracker#47]
**What device + iOS version are you on?**
iPad Pro 10.5 Wifi

**What are the steps to reproduce the issue?**
1. Had a perfect running jailbreak.
2. Installed Cercube for Youtube tweak
3. After tweak installation, tweak required respring.  Respring took forever, and eventually the iPad just restarted.
4.  Now, when trying to jailbreak it, I get a -20 error.
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Hi, this issue is not related to checkra1n.
