### ISSUE TITLE
Woke up to Loader / tweaks not working anymore

### ISSUE THREAD

**Issue by a1ex4** [checkra1n/BugTracker#470]
**Iphone 6 iOS 12 Checkra1n 0.9**
(I know it’s kind of an older release but 0.9.2 was not working with ip6 and I don’t have access to a Mac anymore)

After 3.5 days of uptime and everything working perfectly, I woke up thinking my device restarted because no tweaks were loaded. But my iphone didn’t reboot, still have 4 days of uptime, every jailbreak app opening and working without problems (Cydia, Zebra, MTerminal...) although Loader crashes immediately.

I’m confused, this never happened to me and I’m not sure in what state my device currently is.

I didn’t reboot, is there a way to get back to a jailbroken state ? Respring / sbreload does nothing, safe mode isn’t working.

Thanks in advance for any help.

**Comment by arx8x** [comment]
`/etc/rc.d/substrate`
`killall SpringBoard`

**Comment by a1ex4** [comment]
Thanks for the suggestion but it did not do it, respring normally
