### ISSUE TITLE
Killed: 9

### ISSUE THREAD

**Issue by shinvou** [checkra1n/BugTracker#471]
**What device + iOS version are you on?**
iPad Air, iOS 12.4.3

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1. Write simple hello world program
2. Compile
3. Execute

**What do you expect, and what is happening instead?**
I expect the program to run but get a SIGKILL. Packages from Cydia execute fine.

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
You're running from /var and lack the `com.apple.private.security.no-container` entitlement.

**Comment by shinvou** [comment]
Yep, I was missing the entitlement. Thanks.
