### ISSUE TITLE
Sidecar not working

### ISSUE THREAD

**Issue by bart172** [checkra1n/BugTracker#473]
**What device + iOS version are you on?**
iPad 6, iOS 13.2.2

**What checkra1n version are you using?**
0.9.2 (as for now it's the most recent checkra1n version working for the device, as detailed in issue #360) 

**What do you expect, and what is happening instead?**
Using both an Hackintosh and a proper Mac, the computers don't recognise the iPad as a Sidecar device. Can still do normal stuff through Finder.

**Comment by clarityzzz** [comment]
This is probably a hackintosh related problem and not the jailbreak's fault. If you don't have wifi and bluetooth working properly, sidecar won't appear on system preferences and will not work.

**Comment by Bram-Brooks** [comment]
You need either native Wifi/BT support or a usb c to usb cable. Lighting to usb does NOT work. I found this out the hard way. Has nothing to do with checkra1n whatsoever afaik.

**Comment by bart172** [comment]
> Lighting to usb does NOT work.

Well, it did work for me via cable, both on the hackintosh and the Mac. 

> This is probably a hackintosh related problem and not the jailbreak's fault. 

I confirm it did work on hackintosh via cable. Wireless connectivity depends if the Bluetooth adapter supports handoff.

**Comment by NikoUY** [comment]
It works for me using 0.9.2 (iPad 6) with a Hackintosh and a cable (no wifi/bluetooth), so either is an issue with a newer version of checkrain or with your setup, it's probably worth trying to use older versions to narrow down the issue.

**Comment by Bram-Brooks** [comment]
> It works for me using 0.9.2 (iPad 6) with a Hackintosh and a cable (no wifi/bluetooth), so either is an issue with a newer version of checkrain or with your setup, it's probably worth trying to use older versions to narrow down the issue.

Yeah, but you're using a usb c to lightning cable right? Not a lightning to usb cable? Apparently only the first cables mentioned work for wired sidecar. Am I correct about this?

**Comment by NikoUY** [comment]
I’m using a USB-A to Lighting cable, I also tested it with a USB-C to USB-A adapter and it works too, I don’t think the cable is an issue.

**Comment by bart172** [comment]
Managed to make it work by:

- attaching iPad to the computer via cable (Lightning-USBA, in my case)
- rebooting
- activating sidecar
- disconnecting sidecar, not the cable
- jailbreaking (still with 0.9.2)

**Comment by Bram-Brooks** [comment]
> Managed to make it work by:
> 
> * attaching iPad to the computer via cable (Lightning-USBA, in my case)
> * rebooting
> * activating sidecar
> * disconnecting sidecar, not the cable
> * jailbreaking (still with 0.9.2)

Are you saying Checkra1n is causing the sidecar issues? Since it apparently worked for you once you booted iPad without JB. I have been trying to get my iPad 6 working on my hackintosh system without any luck. Mapped usb ports and everything else is working.

**Comment by bart172** [comment]
> > Managed to make it work by:
> > 
> > * attaching iPad to the computer via cable (Lightning-USBA, in my case)
> > * rebooting
> > * activating sidecar
> > * disconnecting sidecar, not the cable
> > * jailbreaking (still with 0.9.2)
> 
> Are you saying Checkra1n is causing the sidecar issues? Since it apparently worked for you once you booted iPad without JB. I have been trying to get my iPad 6 working on my hackintosh system without any luck. Mapped usb ports and everything else is working.

Without jailbreak, it worked just fine as soon as I updated to Catalina. As soon as I jailbroke, it stopped working. As a non technical guy, I think the same workaround that blocks the OTA updates, which has always also blocked Handoff, now also blocks Sidecar, but somehow it can be "unlocked" by connecting the iPad to the Mac, while in an unjailbroken state, but after having done the jailbreak at least once.

**Comment by Bram-Brooks** [comment]
@bart172 I tried your step but still does not seem to be detected in my mac. Strange.
