### ISSUE TITLE
Bootstrap error

### ISSUE THREAD

**Issue by alecs99** [checkra1n/BugTracker#474]
**What device + iOS version are you on?**
iPhone 8 Plus + iOS 13.2.3

**What checkra1n version are you using?**
 0.9.5

**What do you expect, and what is happening instead?**
 I want to install Cydia and i receive bootstrap error, remove OTA update and try again. But I have the latest version of the iOS. I don't have a developer account so I don't receive any beta update, so I don't quite understand why I receive this error. I had before checkra1n on version 0.9.2 and it worked fine and after I updated to 0.9.5 I get this error.

**Comment by sbingner** [comment]
This was resolved in v0.9.7
