### ISSUE TITLE
PUBG Mobile crashed when installed Cydia Substrate

### ISSUE THREAD

**Issue by napoleonjames** [checkra1n/BugTracker#475]
Jailbreak worked sucessfully but when i installed cydia substrate PUBG Mobile was crashed.
iOS 13.2.2 on iphone X. Checkra1n version 0.9.5.

**Comment by DrConflict** [comment]
You could have easily found an answers to this on reddit or google... install Liberty lite beta 0.1.12

**Comment by djd2** [comment]
i have been banned now, i don't know if it's because this, but i have an iphone 7 plus, played pubg mobile 2 years, installed that Liberty Beta, and NoSub and now i'm banned...

i tryed to make other account, and got banned again...

**Comment by DrConflict** [comment]
@djd2 That seems strange. Why would they ban for using a JB? Are you sure you aren't using hacks lol?

**Comment by djd2** [comment]
man... im playing pubg 2 years... do you think i'm stupid or something? is very strange to me too...

**Comment by Siguza** [comment]
PUBG has jailbreak detection, not an issue with checkra1n.
