### ISSUE TITLE
smart keyboard disconnecting

### ISSUE THREAD

**Issue by rcpag1103** [checkra1n/BugTracker#479]
**What device + iOS version are you on?**
ipad 10.2 ios 13.2.2

**What checkra1n version are you using?**
0.9.5 

**What are the steps to reproduce the issue?**
1. smart keyboard working normal until you connect the ipad to a charger and it will stop working.
2.it will function as normal once you disconnect the ipad from the charger and disconnect it also from smart keyboard then connect again to the ipad
3. working perfectly with 0.9.3
...

**What do you expect, and what is happening instead?**will work as normal

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Fixed in 0.9.6

**Comment by 23Aaron** [comment]
This issue seems to still be occurring in 0.10.1
