### ISSUE TITLE
SmartKeyboard not work after install checkra1n

### ISSUE THREAD

**Issue by Lakr233** [checkra1n/BugTracker#48]
iPad Pro 10.5 iOS 13.2 and 13.2.2

![F1CF3DBA-058A-47A9-BC18-1D8D46E7D7F5](https://user-images.githubusercontent.com/25259084/68546503-ca1bdc00-0411-11ea-8dcc-ca4429123fa9.jpeg)

**Comment by nullpixel** [comment]
Hi, could you let us know more information about the issue you're experiencing with any relevant logs?

**Comment by Lakr233** [comment]
which kind of log do you want?

**Comment by Lakr233** [comment]
checkra1n app's logs look all good like another time

**Comment by nullpixel** [comment]
Maybe there's syslogs about why the accessory doesn't work.

**Comment by Lakr233** [comment]
got some logs from kernel 

kernel
IOSEPBiometricService::sksQueueDequeue -> err:0xe00002f0
AppleBiometricServices::message -> err:0xe00002c7
Ignoring out of line finger-on event from BiometricKit - previous finger-on was already received and we haven't yet received a finger-off.

com.apple.cdp
"Daemon connection invalidated!"

and rest of error were photolibraryd related

--------
above, all logs shown as error was listed. and no error generated when connect and disconnect

**Comment by Lakr233** [comment]
Don’t know why but it is working now. I’d didn’t do anything.

**Comment by Lakr233** [comment]
a just work solution:

Install deepsleep from https://github.com/userlandkernel/DeepSleep/
call deepsleep from root after disconnect keyboard
connect your keyboard and done

@nullpixel might have a look there it is 100% working in my 10 tests

**Comment by Lakr233** [comment]
0.9.3, not fixed. disconnected each time connect to a charger or whatever is but a lighting cable.  :/

**Comment by nullpixel** [comment]
this is fixed in 0.9.5
