### ISSUE TITLE
Installing tweaks / repos

### ISSUE THREAD

**Issue by Aelleono** [checkra1n/BugTracker#480]
**What device + iOS version are you on?**
iPhone 7 Plus iOS 13.2.2

**What checkra1n version are you using?**
0.95 

**What are the steps to reproduce the issue?**
1.Load Cydia
2.Try Installing ANYTHING
3.Error or wait a long time for it to just stay on loading
...

**What do you expect, and what is happening instead?**

I'm expecting for the package to be installed normally like it did when I was on unc0ver. On this though package take SOOO long to download and most of the time either the package does not download or you cannot install tweaks

Another thing is I'm using batchomatic and SO many of tweaks give me an error like "Cannot find com.(something).(eg. exvanco) then I A. Have to remove it from my queue B. Not have the tweak at all, so i'm suspecting there is something with the repo's that causes this.

**Any other info, error logs, screenshots, ...?**
I get error messages like "Hash *a big hash* and error 1703 or something like that.

**Comment by Aelleono** [comment]
Its obviously a beta so I can't blame checkra1n for it after all. I just wanted to be on iOS 13 to update my apple watch and to have the iOS 13 features. Hell I messed up and should've waited for the full release of the release with 13.2.3 for checkra1n because the 13.2.2 is very buggy from what people say and experience.

**Comment by Aelleono** [comment]
Here is what I get 
![90162AC4-6A6B-4ADF-BEA7-B2FB6D816EA7](https://user-images.githubusercontent.com/57971415/69200970-e226e600-0b0a-11ea-94ae-2babcbb38926.png)
![78238EE0-1ACD-450D-99F4-44C7840561EB](https://user-images.githubusercontent.com/57971415/69200971-e2bf7c80-0b0a-11ea-9ef9-7f1e71241d06.png)
![E7E9E4F7-B76F-4280-B6E5-17709B906462](https://user-images.githubusercontent.com/57971415/69200972-e2bf7c80-0b0a-11ea-9aac-428b81f3f6ed.png)

**Comment by Siguza** [comment]
Your screenshots indicate that you used a 3rd party tool to stash and reconfigure sources or something of that sort. For one, you should verify manually that this didn't mess anything up with regard to default repos, and secondly, any chance you have `nepeta.me` in your sources? Because that has been taken offline a while ago, and would explain the long loading times.

Either way, this is at best an issue with Cydia rather than checkra1n, so I'm closing this as unrelated.
