### ISSUE TITLE
iOS 13.2.3 support please

### ISSUE THREAD

**Issue by PrismFox67** [checkra1n/BugTracker#487]
Title

yes please

**Comment by biankobe24** [comment]
download:https://www.lanzous.com/i7g249i 
password:h9e1
this is Personal modification，support IOS12.0-IOS13.3

**Comment by PrismFox67** [comment]
Why would the website not be in English?
Hesitant to download from a website I cannot read as likely they turn out to be scams which in the past have downloaded things such as MDMs onto computers.
Any verification this is legitimate?

**Comment by Bram-Brooks** [comment]
Why do you even make a bug tracker issue for this. It's obvious that they are working on it for the next version. Another pointless bug tracker "issue".

**Comment by ann0see** [comment]
I heard that you could use the cli version.

**Comment by vjonas** [comment]
It is possible. Run it through the CLI. It worked for my IPhone X on ios 13.2.3
