### ISSUE TITLE
Feature Request: Verbose Startup without Cydia download

### ISSUE THREAD

**Issue by PrismFox67** [checkra1n/BugTracker#488]
Just add a checkbox for "Install Cydia"

If the box is not checked then it will simply boost verbose to look cool and that's it.

If the box is checked cydia will install too but if you want to get rid of cydia all you have to do is go back into checkrain uncheck the box and boot again

**Comment by boierito** [comment]
You can check verbose and safe mode

**Comment by nullpixel** [comment]
Have you used checkra1n? Booting verbose normally doesn’t install anything — it only adds a checkra1n app which allows you to install Cydia, but this is removed on the next boot.

**Comment by PrismFox67** [comment]
How do you uninstall cydia once you have it?

**Comment by boierito** [comment]
Open checkra1n app in iOS and do a restore
