### ISSUE TITLE
Error -31 on iPhone SE (iOS 13.2)

### ISSUE THREAD

**Issue by LLinoor** [checkra1n/BugTracker#493]
**Tell us about your setup:**
1. What iDevice are you using? iPhone SE also tryied with iPhone 5S (iOS 12.4.1)
2. On what version of iOS is it? iOS 13.2
3. What version of checkra1n are you using? GUI or CLI? GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)? VM on MacOS Mojave Beta
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A (USB 3.0 I also tryied with USB 2.0)

**What are the steps to reproduce the issue?**
1. Follow the requested steps

**What do you expect, and what is happening instead?**
I thought everything would work out but not everything is going as planned

**Does the issue also occur if you enable Safe Mode?**
yes

**Any other info, error logs, screenshots, ...?**
no

**Comment by boierito** [comment]
Checkra1n does not support VMs. Please close the issue.

**Comment by TechDev12** [comment]
Hello thank you for your great work
i'm having error -31
iPhone 6 OS 12.4.3
GUI version 0.95 beta
VM on vmware 15.5.1 running high sierra
Tried Both USB 3 and USB 2.0 (directly connected no HUB)
recovery mode detected upon switching to DFU more error -31 occurs 
issue also with safe mode

**Comment by boierito** [comment]
> Hello thank you for your great work
> i'm having error -31
> iPhone 6 OS 12.4.3
> GUI version 0.95 beta
> VM on vmware 15.5.1 running high sierra
> Tried Both USB 3 and USB 2.0 (directly connected no HUB)
> recovery mode detected upon switching to DFU more error -31 occurs
> issue also with safe mode

Hi, checkra1n does not support any type of VMs.
