### ISSUE TITLE
Phone Unresponsive leading to Re-spring Loop on Wallpaper Change (Using Settings Panel)

### ISSUE THREAD

**Issue by kunal2991** [checkra1n/BugTracker#494]
**Tell us about your setup:**
1. What iDevice are you using?
- iPhone X 

2. On what version of iOS is it?
- iOS 13.2.2

3. What version of checkra1n are you using? GUI or CLI?
- 0.9.5 - GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
- MacOS Mojave - 10.14.6

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
- USB-A using an Apple Cable.

**What are the steps to reproduce the issue?**
1. In a Jailbroken state, navigate to Settings -> Wallpaper
2. Device stops responding/responds with a significant lag.
3. Goes into a Re-spring Loop.
...

**What do you expect, and what is happening instead?**
- Should be able to change wallpaper w/o going into a re-spring loop.
- Instead, Device Freeze -> Re-spring Loop -> Hard Reset -> Change Wallpaper in stock iOS State -> Re-JB

Note: Tweak named "Wallpaper Loader" caused a similar problem. However, this issue persists post uninstall of that tweak too.
Also, changing Wallpaper from the actual "Photo" selection menu using "Photos -> Use as Wallpaper" is working properly in Jailbroken state.

**Does the issue also occur if you enable Safe Mode?**
- Issue is not present in Safe Mode.

**Any other info, error logs, screenshots, ...?**

**Comment by boierito** [comment]
Do you have any other tweak for wallpapers? I have the Wallpaper Loader with the set of wallpapers from iPhone 11 and it works. So... It looks rare.

**Comment by kunal2991** [comment]
> Do you have any other tweak for wallpapers? I have the Wallpaper Loader with the set of wallpapers from iPhone 11 and it works. So... It looks rare.

Nope. No "Wallpaper" tweaks whatsoever.

**Comment by boierito** [comment]
> > Do you have any other tweak for wallpapers? I have the Wallpaper Loader with the set of wallpapers from iPhone 11 and it works. So... It looks rare.
> 
> Nope. No "Wallpaper" tweaks whatsoever.

Ok, if you can restart in safe mode and tell us if the error persists

**Comment by kunal2991** [comment]
> > > Do you have any other tweak for wallpapers? I have the Wallpaper Loader with the set of wallpapers from iPhone 11 and it works. So... It looks rare.
> > 
> > 
> > Nope. No "Wallpaper" tweaks whatsoever.
> 
> Ok, if you can restart in safe mode and tell us if the error persists

This issue is not present in Safe Mode.

**Comment by boierito** [comment]
> > > > Do you have any other tweak for wallpapers? I have the Wallpaper Loader with the set of wallpapers from iPhone 11 and it works. So... It looks rare.
> > > 
> > > 
> > > Nope. No "Wallpaper" tweaks whatsoever.
> > 
> > 
> > Ok, if you can restart in safe mode and tell us if the error persists
> 
> This issue is not present in Safe Mode.

So... it seems that the error is a tweak or something else. Can you clean your mobile with iCleaner?

**Comment by nullpixel** [comment]
The issue is with a tweak.
