### ISSUE TITLE
iPhone X Unable to re-jailbreak?

### ISSUE THREAD

**Issue by Katalyst84** [checkra1n/BugTracker#496]
I had a successful jailbreak with iphone x, 13.2.2.  I was trying out a tweak, and it failed after respringing. It temporarily "bricked" until I did a hard-reset.  Upon reboot, cydia and other jailbroken-apps kept crashing, so I assumed my phone was no longer jailbroken...  I attempted checkra1n several times with no success; I got the reboot-loop for a few minutes before loading to an un-jailbroken home screen, and cydia is still crashing.   How do I re-jailbreak successfully?  Am I just doing something wrong?

**Comment by HitecHippie** [comment]
Did you figure your problem out? I am in the same situation currently :(

**Comment by Katalyst84** [comment]
Yeah... I updated/upgraded checkra1n and reloaded it.  The update also works with 13.2.3 :)
