### ISSUE TITLE
Face ID disabling 

### ISSUE THREAD

**Issue by dev4700** [checkra1n/BugTracker#498]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using? GUI or CLI?
![0BB8E33C-3EC6-4DE2-A354-D592D7ED88EA](https://user-images.githubusercontent.com/45528143/69404563-9d29cc00-0d23-11ea-87cc-3ebb46d43030.png)

4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by elhamzaouii** [comment]
Iphone X 13.2.2
All versions of checkra1n gave me faceID problems after couple of hours. ( GUI )
Tried deleting faceID and reactivating but it's still gone after couple of hours.
SafeMode doesn't help.
StraightToPasscode tweak is a lifesaver now if u dont want to rejailbreak every dag for faceID.

**Comment by nullpixel** [comment]
Are you following the steps to enter DFU mode in the GUI?

**Comment by elhamzaouii** [comment]
Off course, followed al steps on the GUI, everything else is super stable though. I did enable the faceid before jailbreaking first time. But shouldn't be a problem normal ?

**Comment by TheAustinG** [comment]
I'm having the same issue. iPhone X 13.2.3 w/ Checkra1n 0.9.5. I used the CLI to be able to jailbreak 13.2.3 and everything works great except for the Face ID being unavailable every time I try. Sometimes I also don't have touch capability when the jailbreak is finished but I can fix that by just retrying.

**Comment by dev4700** [comment]
Pls fix Face ID issue it’s big headache.

**Comment by elhamzaouii** [comment]
yes it's really the only bug I noticed so far but also the most anoying

**Comment by nullpixel** [comment]
You have to jailbreak using the app. To bypass the version restriction, put your device into recovery mode first

**Comment by NAYN9** [comment]
> **Tell us about your setup:**
> 
> 1. What iDevice are you using?
> 2. On what version of iOS is it?
> 3. What version of checkra1n are you using? GUI or CLI?
>    ![0BB8E33C-3EC6-4DE2-A354-D592D7ED88EA](https://user-images.githubusercontent.com/45528143/69404563-9d29cc00-0d23-11ea-87cc-3ebb46d43030.png)
> 4. What is your host system (OS version? Hackintosh? VM? etc.)?
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
> 
> **What are the steps to reproduce the issue?**
> 1.
> 2.
> 3.
> ...
> 
> **What do you expect, and what is happening instead?**
> 
> **Does the issue also occur if you enable Safe Mode?**
> 
> **Any other info, error logs, screenshots, ...?**

Iphone X
ios 13.2.2
i used all the beta but no luck 
try'd hackintosh and macbook pro 2016
UsbA cable
the phone was i cloud locked don't know if it's the cause

**Comment by nullpixel** [comment]
You have to use the GUI app, not the CLI.

**Comment by TheAustinG** [comment]
> You have to use the GUI app, not the CLI.

Yep, this fixed the issue for me. Put the phone into recovery mode and then connected it to the Mac and ran the GUI and it let me jailbreak. iPhone X 13.2.3 and Face ID is working great for me now. Thanks for the help!

**Comment by elhamzaouii** [comment]
I use the GUI app, like I said. What is the solution for me then ? @nullpixel

**Comment by dev4700** [comment]
We’re to get GUI app

**Comment by TheAustinG** [comment]
> I use the GUI app, like I said. What is the solution for me then ? @nullpixel

Did you try doing what he said? Putting your phone into recovery first? Not DFU. I got it to work on the first try for me.

**Comment by elhamzaouii** [comment]
First try ? What are u talking about? My problem is that faceID get broken after several hours when being jailbroken.

**Comment by nullpixel** [comment]
Okay, well that sounds like a tweak or something else

**Comment by elhamzaouii** [comment]
@nullpixel Already tried deleting some tweaks, crashreporter doesnt say anything neither...

**Comment by nullpixel** [comment]
try using safe mode. does the issue happen then?

**Comment by elhamzaouii** [comment]
still happening...

**Comment by AnonMujo** [comment]
1. iPhone X
2. 13.2.2
3. GUI (Checkra1n 0.9.5) 
4. Hackintosh (MacOS Sierra on a Lenovo z50)
5. I use 3rd party cable (Syncwire Lightnig cable)

I have no issues with FaceID

**Comment by dev4700** [comment]
All tried wasted so much time restored / jail broken thru checkra1n 0.9.5 not a single tweak I installed , Face ID worked 7 to hrs perfectly and now it not detecting .

**Comment by dev4700** [comment]
There is only Face ID issues that’s it every thing is perfect I installed b4 this 34 tweaks all we’re working perfectly the issue is Face ID detection not working properly that’s it I am using ipx 13.2.3 .

**Comment by elhamzaouii** [comment]
I will wait for a new GUI release that supports 13.2.3 and restore my iphone to start from scratch, hopefully that will fix it ...

**Comment by jacc** [comment]
@elhamzaouii, did you follow the exact steps that @nullpixel gave you?
- Put your phone into recovery mode (Follow these steps: http://www.iphonehacks.com/2017/11/how-to-put-iphone-x-recovery-mode.html)
- Run the GUI version of checkra1n 
![image](https://user-images.githubusercontent.com/6956351/69875838-10838e80-128c-11ea-878e-60246f387e13.png) (looks like this)
- Jailbreak

**Comment by elhamzaouii** [comment]
But the GUI(0.9.5) doesn't ask me to go into recovery.. I follow the steps on the GUI ...

**Comment by nullpixel** [comment]
You have to put your phone into recovery yourself _first_

**Comment by elhamzaouii** [comment]
Couple hours later. Broken again... sigh

**Comment by jacc** [comment]
@elhamzaouii 0.9.6 just got released. Can you try that version and report back?

**Comment by elhamzaouii** [comment]
Still broken after an hour on 0.9.6

**Comment by jacc** [comment]
What were the steps you took?

**Comment by elhamzaouii** [comment]
The steps I have to take, following the GUI. recovery and then the presses

**Comment by nullpixel** [comment]
Did the issue happen in safemode?

**Comment by elhamzaouii** [comment]
Again, yes. faceid doesnt work in safe mode neither

**Comment by elhamzaouii** [comment]
I restored to 13.2.3 and tested my iphone without jailbreak couple of days. FaceID is broken after couple of hours. Checkra1n did break my faceID it seems :( What can I do know beside bringing it to an apple store ...

**Comment by nullpixel** [comment]
checkra1n did not break your Face ID, lol

**Comment by elhamzaouii** [comment]
Then what did ? :)

**Comment by dev4700** [comment]
There was a Face ID hardware issue in my iPhone X . Got replaced Face ID camera service centre . Everything is working perfectly/ no jailbreak issue it was . If any facing same problem visit to Apple service centre
