### ISSUE TITLE
Does not work on Catalina...

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#5]
**What device + iOS version are you on?**
Trying to install onto 13.1.1 iPhone 6s 16gb. Early 2015 MacBook Air on Catalina.

**What are the steps to reproduce the issue?**
1. Install Catalina
2. Move the .app to your Application folder
3. Boom, insta crash.
...

**What do you expect, and what is happening instead?**
Checkra1n to launch.

**Any other info, error logs, screenshots, ...?**
If somebody points me how to add logs, I'll happily add them.

Command line interface works fine, and allowed me to load checkra1n sucessfully.

**Comment by woachk** [comment]
Right-click and click on Open.
It should work the second time.

**Comment by ghost** [comment]
@woachk - I know about this fix, however it doesn't do anything - the app bounces on a dock for a single time, then immediately closes (as in no dot under app icon, no windows launch, absolutely no reaction).

**Comment by m1stadev** [comment]
just jailbreak using the CLI tool (those don’t need to be notarized to run in Catalina afaik)

**Comment by woachk** [comment]
or run the GUI through ./checkra1n.app/Contents/MacOS/checkra1n_gui without the -

**Comment by ghost** [comment]
@woachk, this fixes the problem. However, I still think the issue of the app not launching normally should be fixed - even if only for convenience.

**Comment by blanxd** [comment]
> @woachk, this fixes the problem. However, I still think the issue of the app not launching normally should be fixed - even if only for convenience.

did you try to
`sudo xattr -r -d com.apple.quarantine /Applications/checkra1n.app`
(right-click-open didn't work for me on High Sierra neither, but this did. Not sure if a second try might have worked or if the command does the same, though. Personal habbit going like this with self-made apps and stuff)

**Comment by ghost** [comment]
@blanxd, sadly, after testing, it doesn't do the trick either. Only thing that works for me (at least for now) is opening the app from Terminal

**Comment by feherneoh** [comment]
@lukizel does the app work when you manage to launch it? I'm on Catalina too, and I get a "ERROR: Failed to open device 0xXXXXXXXXXXXXXX in recovery/DFU mode" error as soon as I connect the phone

Phone is 6S 32GB with S8003

**Comment by littlelailo** [comment]
Does it work when you change your primary language to english?

**Comment by feherneoh** [comment]
> Does it work when you change your primary language to english?

if that was for me, will try later, I don't have the laptop with me
(will try anyways even if it wasn't for me)

**Comment by Siguza** [comment]
Just tried this with checkra1n 0.9.5 on macOS 10.15.1, and I can't reproduce the issue. Is it still present @lukizel @feherneoh ?

**Comment by nullpixel** [comment]
Closing through lack of response (I'll reopen it if you can still reproduce the issue)

**Comment by ghost** [comment]
New issue arose where, after updating checkra1n, I can't open it at all now - macOS is giving me a "subtle" hint that the app is "DAMAGED" and I can only move it to the Bin. What can I do now? CLI still works fine

**Comment by NotExactlyMeerkat** [comment]
@lukizel, have you tried the `xattr` command? Because it removes this "Damaged" message.

**Comment by blanxd** [comment]
yeah, could even try ```xattr -cr /Applications/checkra1n.app``` so it clears all the stuff, it could be the thing starting with Mojave that macos is "calling home" when launching apps "downloaded from the internet". Like, downloading it with ```curl``` would not attach the "downloaded from internet" flag on it like the web browsers do, and it might work fine... google for this concept, there's a lot about it, precisely that "damaged" issue etc. (I only learned about it recently, when I finally upgraded to Mojave, so many apps started giving me that)
