### ISSUE TITLE
Bootstrap Error 2

### ISSUE THREAD

**Issue by WayneBishop1** [checkra1n/BugTracker#50]
**What device + iOS version are you on?**
Iphone 7 gsm Iphone 9,3
IOS 12.4

I installed the checkra1n on my jailbroken iphone 7 and tried installing cydia and just got the error

Bootstrap Error 2

And it won't install cydia?

**Comment by nullpixel** [comment]
Hi, do you have unc0ver or chimera installed?

**Comment by WayneBishop1** [comment]
uncover however i can't unjailbreak it using the uncover app as it is no longer signed and i can't re-sign it due to apple changing something on thier servers which breaks the sideloading of it.

**Comment by nullpixel** [comment]
You can use the restore RootFS button inside the loader app. We currently do not support bootstrapping a device which has already been jailbroken.

**Comment by WayneBishop1** [comment]
There is no restore option it only offers me to install cydia nothing else?

**Comment by nullpixel** [comment]
That is a known issue, so for now you will need to find an alternative way to remove unc0ver.

**Comment by WayneBishop1** [comment]
Ok thanks for the info :)
Maybe i will just update to ios 13.2.2
