### ISSUE TITLE
activation

### ISSUE THREAD

**Issue by candra2606** [checkra1n/BugTracker#501]
hello , everyone ,
did someone found a way about set to activated device or set brickstate to false ?

best regards

**Comment by boierito** [comment]
Hi @candra2606 Are you talking about iCloud bypass?

**Comment by candra2606** [comment]
Yes bro

**Comment by boierito** [comment]
> Yes bro
> […](#)
> Sent from my iPhone
> On 23 Nov 2019, at 04.42, boierito ***@***.***> wrote: Hi @candra2606 Are you talking about iCloud bypass? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Ok, so please close the issue. Checkra1n is not a tool for do a iCloud Bypass
