### ISSUE TITLE
Not a Bug only a Question for  jailbreak developers

### ISSUE THREAD

**Issue by ifixweb** [checkra1n/BugTracker#505]
Hi,

Sorry for my english

There are any way to send a home click command on an iphone 7 jailbroaken via ssh ? or activate Assistive Touch?

https://ibb.co/jRsj69b

I have this problem, this iPhone 7 have a complety un operable home buttom, after upgrate, I need to do a click on the home buttom but its damage and there are not form to fix it.

I already try with a newone genuine home buttom to get the Assistive Touch fix, but not work out.

I can't trust on the device because the only option on this mode is a click

I don't want a loose the iphone data

thank you for your help

**Comment by 0xlazY** [comment]
I used 3uTools software, you can connect your iphone to a pc and activate the Assitive Touch function

**Comment by ifixweb** [comment]
Thank you lazyjd I already try with 3uTools but I can't do it, because it's a special recovery mode for data recovery, and I can't trust on the device for PC/Mac recognize without home click

**Comment by ifixweb** [comment]
Also I already try with the chinese home button modification mod remplacement without bluetooth (3th gen), and not work

**Comment by nullpixel** [comment]
This is not a checkra1n issue, so as such I'm closing it. Apologies.
