### ISSUE TITLE
ssh

### ISSUE THREAD

**Issue by gabriel-nsiqueira** [checkra1n/BugTracker#507]
is there a way to ssh and unjailbreak by ssh?

**Comment by Bram-Brooks** [comment]
What the hell does this have to with checkra1n? You could've used google or youtube and gotten an answer in 1 minute.

**Comment by arx8x** [comment]
If you can SSH, USB should also work. Why don't you use iTunes or idevicerestore to simply "update" to the same version so that your root partition is restored.
