### ISSUE TITLE
unresponsive screen

### ISSUE THREAD

**Issue by gabriel-nsiqueira** [checkra1n/BugTracker#508]
**Tell us about your setup:**
1. What iDevice are you using? iPhone X
2. On what version of iOS is it? 13.2.2
3. What version of checkra1n are you using? GUI or CLI? GUI and CLI, I tried both. Checkra1n beta 0.9.5
4. What is your host system (OS version? Hackintosh? VM? etc.)? Macbook Pro 2017 running MacOS 10.15
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A from apple

**What are the steps to reproduce the issue?**
1. I jailbroke my phone
2. it loaded the jailbreak
3. when i tried to unlock it, it became unresponsive
...

**What do you expect, and what is happening instead?**
screen is not working to touch
**Does the issue also occur if you enable Safe Mode?**
yes

**Any other info, error logs, screenshots, ...?**
no

**Comment by nullpixel** [comment]
Are you entering DFU mode through the app?

**Comment by gabriel-nsiqueira** [comment]
yes

**Comment by ghost** [comment]
The iPhone X has touch responsiveness issues.
Just sayin'
