### ISSUE TITLE
unable to open checkra1n file

### ISSUE THREAD

**Issue by youran1314** [checkra1n/BugTracker#51]
**What device + iOS version are you on?**
iPhone 6 + 12.4.1

**What are the steps to reproduce the issue?**
1.trying to open it
2.
3.
...

**What do you expect, and what is happening instead?**

I have tested it on 2 macbooks ones running 10.7.5 and the other running 10.10.5
both cant access it
tried redownloading it multiple times no luck

![Screen Shot 2019-11-10 at 11 35 11 PM](https://user-images.githubusercontent.com/57594382/68546584-cb013d80-0412-11ea-832f-fa4a12b44a3a.png)

**Any other info, error logs, screenshots, ...?**

**Comment by luapp** [comment]
Me to !
iPhone 8 + 13.2

**Comment by nullpixel** [comment]
Hi, I'm closing this as a duplicate of #28.
