### ISSUE TITLE
Face ID 

### ISSUE THREAD

**Issue by alexjackfish** [checkra1n/BugTracker#510]
I have a problem, I have an iPhone X and a cable for the top speaker has broken in it and because of this, Face ID does not work.  I replaced the cable with a new original one and the speaker began to work, but there was no Face ID.  I think this is all due to the fact that the serial number of the component is being checked.  is it possible to somehow disable this check using jailbrake?

**Comment by nullpixel** [comment]
It is possible, but out of scope for checkra1n.
