### ISSUE TITLE
After jailbreak download, touchscreen is not working

### ISSUE THREAD

**Issue by bobbyg16** [checkra1n/BugTracker#511]
**Tell us about your setup:**
1. What iDevice are you using?
iphone X
2. On what version of iOS is it?
13.2.3
3. What version of checkra1n are you using? GUI or CLI?
terminal one
4. What is your host system (OS version? Hackintosh? VM? etc.)?
latest mac os
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
apple cable
**What are the steps to reproduce the issue?**
1. jailbreak normally
2. 
3.
...

**What do you expect, and what is happening instead?**
i expect to be able to login with passcode
i cannot touch the screen as it is unresponsive
**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Are you following the steps to enter DFU mode in the app?

**Comment by bobbyg16** [comment]
Yes it goes into DFU mode and downloads and everything but once it's done and I get to open my phone the touch screen doesn't work. I have to reset to get the touch back

**Comment by nullpixel** [comment]
Does the issue happen if you enable safe mode?

**Comment by bobbyg16** [comment]
I do it in terminal, how do I enable safe mode?

**Comment by nullpixel** [comment]
So you’re not following the steps to enter DFU mode in the _app_? 

Could you please use the GUI and follow those steps, and let me know if your issue persists?

**Comment by bobbyg16** [comment]
It won't let me on app since I have 13.2.3 ios

**Comment by nullpixel** [comment]
Put your device into recovery mode first, then it will allow you

**Comment by bobbyg16** [comment]
Then do i do it in terminal or in the app?

**Comment by boierito** [comment]
Then open the GUI app of checkra1n

**Comment by nullpixel** [comment]
Do it in the app, but put your phone into recovery mode first.

**Comment by nullpixel** [comment]
Closed through lack of response

**Comment by jeffyzf** [comment]
I too am having this problem
