### ISSUE TITLE
Cant't install cydia

### ISSUE THREAD

**Issue by h101-nazi** [checkra1n/BugTracker#512]
It keeps saying the internet connection appears to be offline i restarted my phone checkra1n was removed
I have iphone 7 plus 
ios 13.1.3

**Comment by boierito** [comment]
Checkra1n is a semi-tethered jailbreak. So you need to re-jailbreak to get access again to checkra1n iOS app

**Comment by nullpixel** [comment]
0.9.6 should fix the internet issue, and the above comment is why the app went on a reboot^
