### ISSUE TITLE
After re-jailbreaking upon reboot I lose everything and have to fresh install Cydia every time along with all my tweaks

### ISSUE THREAD

**Issue by ecain45** [checkra1n/BugTracker#513]
**Tell us about your setup:**
1. What iDevice are you using?
Iphone x
2. On what version of iOS is it?
13.2.3 but it was problem persists on 13.2.2
3. What version of checkra1n are you using? GUI or CLI?
0.9.2 works. 0.9.5 does not (OTA update problem)
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Hackintosh High Sierra
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Standard USB cable that comes with iPhone direct in usb 3.0

**What are the steps to reproduce the issue?**
1. Reboot iPhone due to dead battery
2. Redo checkra1n process 
3. Option to reinstall Cydia or in install Cydia
...

**What do you expect, and what is happening instead?**
I expect all my tweaks to just kick back up after the checkra1n process is complete

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
This occurs on 0.9.2 and on 0.9.5 it's even worse. Says I have an OTA update when that is DEFINITELY not the case, I've checked every where I could and couldn't find that update file

**Comment by sahilibrahimmohd** [comment]
I have the same issue bro!!

**Comment by sbingner** [comment]
That's the thing you did have an OTA update but it should be resolved with v0.9.7
