### ISSUE TITLE
Face ID detection

### ISSUE THREAD

**Issue by dev4700** [checkra1n/BugTracker#514]
Hi I am using iPhone X on 13.2.2 jail broken with checkra1n 0.9.5 Face ID doesn’t work for me . It works properly for hour then down again restart it show Face ID not activated on this phone . Done reboots restore it worked again today it’s same

**Comment by elhamzaouii** [comment]
https://github.com/checkra1n/BugTracker/issues/498

**Comment by nullpixel** [comment]
Are you following the instructions in the GUI?

**Comment by Err0rSh0** [comment]
@nullpixel my iPhone X Face ID same problem. (Ver13.2.3 iTunes DFU RESTORED)
This problem has occurred since the jailbreak of checkra1n ver.0.9.5.

Use checkra1n ver0.9.6 following GUI. 
Face ID Can SETUP. But, Can’t  FACE DETECTION. 
So setup cannot be completed. 
Can’t use FACE ID.
Please help.
Sorry my cheap English.

**Comment by dev4700** [comment]
Face ID not detecting again worked perfectly 4 hrs  0.9.6

**Comment by dev4700** [comment]
I have just limited basic tweaks installed list below
AudioRecorder xs
Bio protect
Liberty lite 
Watusi 2

**Comment by nullpixel** [comment]
Remove bio protect — does the issue still occur?

**Comment by elhamzaouii** [comment]
Still broken after an hour on 0.9.6

**Comment by nullpixel** [comment]
@elhamzaouii: repeatedly commenting on multiple issues does not help you get your issue resolved faster

**Comment by dev4700** [comment]
Face ID not working removed bio protect

**Comment by elhamzaouii** [comment]
I restored to 13.2.3 and tested my iphone without jailbreak couple of days. FaceID is broken after couple of hours. Checkra1n did break my faceID it seems :( What can I do know beside bringing it to an apple store ...

**Comment by elhamzaouii** [comment]
Now working since yesterday, maybe it is checkra1n after all ..

**Comment by dev4700** [comment]
Yesterday I got my iPhone back from service centre replaced Face ID camera now everything is perfectly working/ there no issue of jailbreak it was hardware problem
