### ISSUE TITLE
iPhone 7 Plus, IOS 13.2.3 fail bot test, redirect to install 2 x VPN's fails

### ISSUE THREAD

**Issue by mickyjj** [checkra1n/BugTracker#516]
Hello,
Due to recent jailbreak fail on ios 10.0.3, I reset my phone with itunes, upgraded to 13.2.3 and restored from backup.

I installed Checkra1n profile, ran program from the icon. 
It said it did all it's work then did Bot test.
Ticked I am not a Bot but up came three options, I have to install 2. 
I selected Symantec VPN and Ghost VPN and waited. Neither will install. iTunes store throws up an error after waiting 30 or so seconds that it can't install. I tried again, and again.
Then tried a reboot. Still will not install.

started Checkrain from the icon again, stuck in the same place.
Can't verify

**Comment by mickyjj** [comment]
I am thinking I fell prey to a fake Checkrain. Maybe leave this issue for others to see, so that they can see if they also followed a fake path ? I saw Checkrain.com was a fake, avoided that but then went to checkrain,org. Looks and smells like the real thing, but I now have my doubts as checkra.in looks different. Users be ware ! there are fakes out there. I have not proved checkrain.org to be a fake but, it smells like it.

**Comment by boierito** [comment]
Yes, you fall into a fake checkra1n page, be careful.

**Comment by mickyjj** [comment]
Comparing the whois DNS records for Checkra.in and checkrain.org / checkrain.com all prove this is a fake. Only checkra.in is real.

**Comment by mickyjj** [comment]
I have reported the video on youtube that lead to this. https://www.youtube.com/watch?v=KQMG-g2SAeg

**Comment by Siguza** [comment]
Sorry to hear you fell for a scam, but I'll close this ticket then.
