### ISSUE TITLE
Whatsapp, Google Photos, Instagram, etc are unable to show the photos present in the device

### ISSUE THREAD

**Issue by sahilibrahimmohd** [checkra1n/BugTracker#517]
![2E9EFE45-E79C-4323-8955-863064A4B27F](https://user-images.githubusercontent.com/50659246/69560703-26662a80-0fd2-11ea-8bfd-cd6d62412611.png)
![2FD663F2-795C-4DD8-ADD3-5F04736B1DBA](https://user-images.githubusercontent.com/50659246/69560704-26fec100-0fd2-11ea-9258-fca4c44e59ec.png)

**Tell us about your setup:**
1. Iam using iPhone SE
2. version of iOS: 13.2.2
3. version of checkra1n: 0.9.5 beta
4. Hackintosh Mojave
5. USB-A 3rd party cable

**What are the steps to reproduce the issue?**
1. After booting if you try to send/post it doesn’t show photos 
...

**What do you expect, and what is happening instead?**
I expect my device to show photos while I am about to send photos or about to post

**Does the issue also occur if you enable Safe Mode?**
No this doesnot happen in safe mode

**Any other info, error logs, screenshots, ...?**

**Comment by Halo-Michael** [comment]
Are you using Liberty?

**Comment by Siguza** [comment]
If this does not happen in safe mode, it is caused by a tweak. I can only suggest using iCleaner to disable different combinations of tweaks until you find the faulty one.

**Comment by sahilibrahimmohd** [comment]
> Are you using Liberty?

Yes

**Comment by sahilibrahimmohd** [comment]
> If this does not happen in safe mode, it is caused by a tweak. I can only suggest using iCleaner to disable different combinations of tweaks until you find the faulty one.

Thank you bro! 👍
