### ISSUE TITLE
Can’t see loader on iPhone after jailbreak

### ISSUE THREAD

**Issue by SarKaa** [checkra1n/BugTracker#518]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 7 Plus
2. On what version of iOS is it?
IOS 13.3
3. What version of checkra1n are you using? GUI or CLI?
GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Hackintosh
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Official apple lighting cable
**What are the steps to reproduce the issue?**
1. Jailbreak normally
2. 
3.
...

**What do you expect, and what is happening instead?**
Can’t see loader after jailbreak

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by ToiletBraet** [comment]
iOS 13.3 is not supported, you can still jailbreak if you do a workaround, but don't expect it to work

**Comment by SarKaa** [comment]
It does work, you just have to wait a bit
