### ISSUE TITLE
Cydia is crashing after is installed by checkra1n loader 1.0 (1)

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#522]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 7 Plus 128GB 
2. On what version of iOS is it?
13.2.2 and 13.2.3 (the issue is present on both)
3. What version of checkra1n are you using? GUI or CLI?
beta 0.9.5, the issue is present in both GUI and CLI version 
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Macbook running MacOS X High Sierra 10.13.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Im using USB-A to connect to the device, it is an Apple Certified 3rd party cable by UNBREAKcable, no hubs etc. being used, just 
USB 2.0 from Mac > USB-A UNBREAKcable > iPhone 7 Plus
**What are the steps to reproduce the issue?**
1. Install checkra1n as explained in the GUI ( DFU mode at the time specified in GUI, very carefully following everything)
2. After the iphone home screen appears run checkra1n app to install Cydia 
3. Install and try to open Cydia

**What do you expect, and what is happening instead?**
I expect Cydia to run normally but instead it is crashing. ( like trying to open it after reboot without re-running checkra1n from PC first,)
Also a notification pops up all the time ( network working) when checkra1n is installed on the device.
![1F4580B8-C8F8-4A0E-A99E-550A647E41C0](https://user-images.githubusercontent.com/58224113/69648484-51e52580-1063-11ea-8248-f19f26276835.png)
I have to mention that it worked the first time I installed checkra1n on the device  ( had access to Cydia and everything went smooth). At some point the battery died and I had to re-run checkra1n from Mac. After doing so checkra1n was running but Cydia didn’t, at this point tried a clean install of Cydia, iOS update, downgrade but nothing seems to bring back the running Cydia ( reinstall option crashes )
**Does the issue also occur if you enable Safe Mode?**
Yes, issue is still present if Safe Mode is enabled ( Cydia still crashing)

**Any other info, error logs, screenshots, ...?**
If needed please inform me and i will do my best to provide further info, error logs, etc.
![E7BD60C0-39E2-41C9-9495-E26AD506E616](https://user-images.githubusercontent.com/58224113/69649339-ce2c3880-1064-11ea-80b2-bdd935f1a49e.png)

**Comment by ghost** [comment]
I found a fix for the issue, what I did was SSH into the device then:

- Navigate to   var/mobile/Library/Cydia/metadata.cb0

- Delete metadata.cb0

- Respring

- Open Cydia

- Fixed.

**Comment by Siguza** [comment]
Duplicate of #60.
