### ISSUE TITLE
Please don't bundle OpenSSH

### ISSUE THREAD

**Issue by blanxd** [checkra1n/BugTracker#526]
This opens users' devices up to an attack opportunity, because not everyone knows to change their passwords. The localhost:44 was way safer than having everyone listening on :22 with a default pwd. (This was the reason behind my [[SSH Toggle and Port]] since Electra was the 1st jb I guess, to have :22 publicly open by default)

**Comment by Siguza** [comment]
This was an oversight, and was never meant to hit production.  
Should be fixed now, thanks for reporting. :)

**Comment by blanxd** [comment]
yes perfectly understandable. Right now going from a clean / fs, after installing Cydia, it doesn't get installed by default, so fixed, indeed.
