### ISSUE TITLE
i have to manually run uicache 

### ISSUE THREAD

**Issue by ahammouri** [checkra1n/BugTracker#53]
**What device + iOS version are you on?**

iPhone 7 ios 13.2.2
**What are the steps to reproduce the issue?**
1. installed icleaner pro from cydia
2. icon didnt show up
3. i had to ssh into device from mac and run uicache from there to get the icon to show
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Hi, this is not an issue with checkra1n, contact the app developer for support.
