### ISSUE TITLE
ERREUR -31 ( ra1nstorm ) 

### ISSUE THREAD

**Issue by matth327** [checkra1n/BugTracker#531]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone X (gsm)
2. On what version of iOS is it? 
iOS 13.2.2
3. What version of checkra1n are you using? GUI or CLI? CLI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Dualboot Windows10/unbuntu-ra1nstorm
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A câble Apple et pas Apple 

**What are the steps to reproduce the issue?**
1. je lance ra1nstorm depuis Linux unbuntu
2. je branche mon iPhone qui est reconnu par checkra1n et macOS ( catalina by ra1nstorm ) 
3. Et j’essaye de jailbreak mon iPhone qui échoue sur erreur -31 sur toutes les version de checkra1n   
...

**What do you expect, and what is happening instead?**
J’attend que mon iPhone se jailbreak mais il reste bloquer sur erreur -31 

**Does the issue also occur if you enable Safe Mode?** OUI !

**Any other info, error logs, screenshots, ...?**
PC Portable HP ( amd A10, Radeon r5 et r7 ) 
Erreur -31 
( 3 days that I do not sleep, to solve this problem .. but always impossible! )

**Comment by boierito** [comment]
Please use english for do a report

**Comment by matth327** [comment]
Tell us about your setup:

 What iDevice are you using?
 iPhone X (gsm)
 On what version of iOS is it?
 iOS 13.2.2
 What version of checkra1n are you using?  GUI or CLI?  CLI
 What is your host system (OS version? Hackintosh? VM? Etc.)?
 Dualboot Windows10 / unbuntu-ra1nstorm
 How are you connecting to the device (USB-A? USB-C? Apple / 3rd party cable? Through a USB hub?)?  USB-A Apple cable and not Apple
 What are the steps to reproduce the issue?

 I run ra1nstorm from Linux unbuntu
 I plug my iPhone which is recognized by checkra1n and macOS (catalina by ra1nstorm)
 And I try to jailbreak my iPhone that fails on error -31 on all version of checkra1n
 ...
 What do you expect, what is happening instead?
 I'm waiting for my iPhone to be jailbreak but it remains blocked on error -31

 Does the issue also occur if you enable Safe Mode?  YES !

 Any other info, error logs, screenshots, ...?
 HP Notebook PC (amd A10, Radeon r5 and r7)
 Error -31
 (3 days that I do not sleep, to solve this problem .. but always impossible!)

**Comment by nullpixel** [comment]
Could you verify that the issue still occurs on 0.9.6?

**Comment by matth327** [comment]
Yes ! Always error 31

**Comment by woachk** [comment]
Switch away from ra1nstorm now please and please try the native build.

Issue closed because of inactivity.
