### ISSUE TITLE
ERROR 31 BRASIL

### ISSUE THREAD

**Issue by Broonks** [checkra1n/BugTracker#539]
**Tell us about your setup:**
1. What iDevice are you using?
Iphone 6s
2. On what version of iOS is it?
13.2.2
3. What version of checkra1n are you using? GUI or CLI?
0.9.5
4. What is your host system (OS version? Hackintosh? VM? etc.)?
virtual machine/macOS High Sierra
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
original cable

**What are the steps to reproduce the issue?**
1. 
I plug in the cable, I can only hit start if I go into dfu or recovery mode, and after that from error 31 how do I solve this problem?
I'm using the translator I'm Brazilian I await answer thanks

2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**
error -31

**Comment by FloppiTuna** [comment]
> What is your host system (OS version? Hackintosh? VM? etc.)?
> Virtual Machine/macOS High Sierra

I don't think virtual machines are supported at the moment. (Unless you are using ra1nstorm of vmra1n; if that's the case let me know)

**Comment by emady3000** [comment]
i have Iphone 6s with ios 12.4.3 i have the same problem ( ERROR 31) 
how to solve it 

thanks

**Comment by nullpixel** [comment]
Virtual machines are not supported - see #1
