### ISSUE TITLE
TFP0 patch (iPhone 8, 13.2.2)

### ISSUE THREAD

**Issue by AlexeyGorbushin** [checkra1n/BugTracker#54]
Does checkra1n support TFP0 patch? According to the PDF and boot log, it supports:
`vm_map_protect, vm_fault_enter, AMFI trustcache
validation, sandbox MACF hooks, mount, TFP0,
apfs…`

But when I try to run the code 
`kernel_task_port = MACH_PORT_NULL;
task_for_pid(mach_task_self(), 0, &kernel_task_port);`
The kernel_task_port is still 0.

**Comment by Lakr233** [comment]
kern_ret_t kr = host_get_special_port(mach_host_self(), 0, 4, &(yourmach_port_t));

try this

**Comment by nullpixel** [comment]
Do you have the correct entitlements to use task_for_pid?

**Comment by Siguza** [comment]
checkra1n does patch tfp0, via real `task_for_pid`, not hsp4.

I just tested, and it works if you are root and have the `task_for_pid-allow` entitlement, so closing this as invalid.
