### ISSUE TITLE
SFTP Support 

### ISSUE THREAD

**Issue by sharklatan** [checkra1n/BugTracker#541]
There are plans to support SFTP.  DROPBEAR is currently being used and it does not have sftp support.  

in some next version could you add OpenSSH or some solution for SFTP?

thanks in advance the work they are doing is appreciated. 🙂

**Comment by Siguza** [comment]
The binpack is supposed to be minimal, and serve mainly as a recovery option.  
If you're jailbroken, you can install the actual OpenSSH, and if you really need to transfer large amounts of files in a non-jailbroken environment, you can `tar` and then `scp` in either direction.
