### ISSUE TITLE
Error -20 for iPad 6th Gen

### ISSUE THREAD

**Issue by queengooborg** [checkra1n/BugTracker#542]
**Tell us about your setup:**
1. What iDevice are you using?  iPad 6th Gen (WiFi)
2. On what version of iOS is it?  iOS 13.2.2
3. What version of checkra1n are you using? GUI or CLI?  Both
4. What is your host system (OS version? Hackintosh? VM? etc.)?  macOS Catalina (10.15.1)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-a cable

**What are the steps to reproduce the issue?**
1. Run `checkra1n` 0.9.3 or newer in either GUI or CLI mode and run through the steps
2. That's pretty much it; the error -20 pops up right after.

**What do you expect, and what is happening instead?**
It seems that the bootloader freezes during installation on my iPad, and it's something regarding a change between 0.9.2 and 0.9.3.

**Does the issue also occur if you enable Safe Mode?**
Yes, it does.

**Any other info, error logs, screenshots, ...?**
`checkra1n` installs just fine when using 0.9.1 or 0.9.2, but 0.9.3 times out waiting for the bootstrap upload.

Note to developers: I’m willing to assist with testing new builds on my device, if need be!

**Comment by ASlien** [comment]
just work in 092
waitting fix

**Comment by nullpixel** [comment]
Fixed in 0.9.6

**Comment by queengooborg** [comment]
Can confirm 0.9.6 did the trick, thank you!
