### ISSUE TITLE
iPad 2018 6th 13.2.3 - Error -20

### ISSUE THREAD

**Issue by ikhd** [checkra1n/BugTracker#544]
**Tell us about your setup:**
1. What iDevice are you using? IPad 2018 6th
2. On what version of iOS is it? 13.2.3
3. What version of checkra1n are you using? GUI or CLI? Both
4. What is your host system (OS version? Hackintosh? VM? etc.)? MacOS Catalina + QEMU VM
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple cable

What are the steps to reproduce the issue?

1- Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode pass the '-s' option) (Error -20).

2- Unfortunately, an error has occured during installation of the jailbreak. With your permission,
the error can be sent back to us so we can investigate this further.
we only send the error code and the device's CPU type. No trackable or other personal information will be sent.

**Does the issue also occur if you enable Safe Mode?** YES

**Any other info, error logs, screenshots, ...?**

![990289DD-DAC7-4A18-9910-55932E1D0381](https://user-images.githubusercontent.com/31629995/69885211-21b0b780-12ed-11ea-9380-277e1f0c5184.jpeg)
![E269E49B-CCCB-42D9-A8BB-9A16163BC13D](https://user-images.githubusercontent.com/31629995/69885394-f67a9800-12ed-11ea-8c7d-806ff0950a68.jpeg)
![11722D20-C6FB-46BE-A509-41D56709ED37](https://user-images.githubusercontent.com/31629995/69885396-f67a9800-12ed-11ea-98ce-41a5e0524e91.jpeg)

**Comment by ikhd** [comment]
Update: work on 0.9.2 ! Wow 🤣👍.

**Comment by ASlien** [comment]
only work in 092...
wait another update 0951

**Comment by nullpixel** [comment]
Fixed in 0.9.6
