### ISSUE TITLE
Error report 

### ISSUE THREAD

**Issue by azoztnt** [checkra1n/BugTracker#546]
![6C6980B0-A932-49CB-BD03-F0477D07C6B7](https://user-images.githubusercontent.com/58352557/69895811-4441d100-12eb-11ea-8af4-f49adbf42ba2.jpeg)

**Comment by boierito** [comment]
What mistake did you get?

**Comment by Siguza** [comment]
Sorry, but a photo of your screen tells us absolutely nothing. Please open a new issue and fill out the bug report template.
