### ISSUE TITLE
suddenly Cydia stopped working

### ISSUE THREAD

**Issue by avdesai2845** [checkra1n/BugTracker#548]
**Tell us about your setup:**
1. What iDevice are you using? - iPhone X
2. On what version of iOS is it? - 13.2.2
3. What version of checkra1n are you using? GUI or CLI? Version 0.9.5
4. What is your host system (OS version? Hackintosh? VM? etc.)? Mac OS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple cable

**What are the steps to reproduce the issue?**
1. Cydia Crashed, I have tried to reinstall as well but same issue.
2. 
![IMG_46C2157A73C0-1](https://user-images.githubusercontent.com/58384783/69911348-35b8fe00-1440-11ea-998a-e84eb4d2a908.jpeg)
![IMG_46C2157A73C0-1](https://user-images.githubusercontent.com/58384783/69911352-3f426600-1440-11ea-8c34-6dfd21043ebf.jpeg)

3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Cydia is working normally in these screenshots.
