### ISSUE TITLE
Touch not responding - 0.9.5  iPhone X

### ISSUE THREAD

**Issue by wodawoda** [checkra1n/BugTracker#549]
**1. What iDevice are you using?**
iPhone X GSM

**2. On what version of iOS is it?**
13.2.3, 13.3 beta 3

**3. What version of checkra1n are you using? GUI or CLI?**
0.9.5 CLI

**4. What is your host system (OS version? Hackintosh? VM? etc.)?**
Mac OS 10.15.2

**5. How are you connecting to the device** 
USB-A

**What are the steps to reproduce the issue?**
1. enter dfu mode
2. jailbreak using the CLI
3. try to use anything

**What do you expect, and what is happening instead?**
a working touchscreen, but it is not responding

**Comment by nullpixel** [comment]
follow the instructions in the GUI

**Comment by wodawoda** [comment]
13.2.3, 13.3 beta 3 doesn't work at GUI only CLI work. With 0.9.5

**Comment by nullpixel** [comment]
0.9.6 supports jailbreaking with the GUI.

For 13.3, first put your phone into recovery mode, then use the GUI.

**Comment by wodawoda** [comment]
I'll wait. I do not have access to 0.9.6
Thank you for the info

**Comment by nullpixel** [comment]
It's available at https://checkra.in/releases/0.9.6-beta for everyone!
