### ISSUE TITLE
Respring when opening corrupt PNG file

### ISSUE THREAD

**Issue by Xyl3n3** [checkra1n/BugTracker#55]
**What device + iOS version are you on?**
12.4.1

**What are the steps to reproduce the issue?**
1. try to view PNG that's corrupt
2.
3.
...

**What do you expect, and what is happening instead?**
it should say, this filetype is unsupported

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Hi, this is not an issue with checkra1n.
