### ISSUE TITLE
Sim activation not supported (calls , sms)

### ISSUE THREAD

**Issue by houssemos** [checkra1n/BugTracker#550]
**Tell us about your setup:**
1. What iDevice are you using?
iphone 7 
2. On what version of iOS is it?
13.2
3. What version of checkra1n are you using? GUI or CLI?
gui , 0.9.5
4. What is your host system (OS version? Hackintosh? VM? etc.)?
vm linux
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
usb-c 3rd party
**What are the steps to reproduce the issue?**
1. icloud iphone bypass correct
2. no call 
3.no sms
...

**What do you expect, and what is happening instead?**
calls working

**Does the issue also occur if you enable Safe Mode?**
yes

**Any other info, error logs, screenshots, ...?**
no

**Comment by quilenle** [comment]
Did you read the tutorial carefully? If you had bypassed your iCloud phone, then you can’t use the SIM function such as calling.

**Comment by Siguza** [comment]
iCloud lock bypasses are neither solicited nor supported, and are not issues of the jailbreak.
