### ISSUE TITLE
Checkra1n makes device think it's on an older iOS version for updates

### ISSUE THREAD

**Issue by conorthedev** [checkra1n/BugTracker#551]
**Tell us about your setup:**
1. What iDevice are you using?
- iPhone 6s
2. On what version of iOS is it?
- iOS 13.2.2
3. What version of checkra1n are you using? GUI or CLI?
- GUI, 0.9.6
4. What is your host system (OS version? Hackintosh? VM? etc.)?
- macOS 10.13.6, normal
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
- USB-A / Apple

**What are the steps to reproduce the issue?**
1. Jailbreak with checkra1n
2. Restore rootFS
3. Jailbreak again after a while (just from experience)
4. Go into Settings > General > Software Update

**What do you expect, and what is happening instead?**
Expected:
- Download the small ~200mb (I think) patch update

Happening:
- Download the big 2.87gb normal update

**Does the issue also occur if you enable Safe Mode?**
Yes, even if you go into userland again it still thinks it's on iOS 12 in the update screen

**Any other info, error logs, screenshots, ...?**
![](https://cdn.discordapp.com/attachments/647216485038817292/650701273376489483/image0.png)

**Comment by TiebeVercoutter** [comment]
13.2.2 is an older version than 13.2.3

**Comment by conorthedev** [comment]
Yes but it wants to download the full sized update as if it was iOS 12

**Comment by conorthedev** [comment]
After trying to download the update it downloaded in about 2 minutes, which is too fast for a 2.87gb file so I'm guessing the metadata is getting displayed wrong. If the device doesn't boot loop or get f*cked up I'll close this issue as it's a visual bug that checkra1n might not even be causing

**Comment by conorthedev** [comment]
Seems to be working fine now, update completed successfully although it did take nearly an hour to update. Closing issue as it’s probably not checkra1n related
