### ISSUE TITLE
checkra1n Loader app not showing up on iPad 5th generation, iOS 13.1.3. 

### ISSUE THREAD

**Issue by jacc** [checkra1n/BugTracker#553]
**Tell us about your setup:**
1. What iDevice are you using? iPad 5h gen
2. On what version of iOS is it? iOS 13.1.3
3. What version of checkra1n are you using? GUI or CLI? GUI. version 0.9.6 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)? Macintosh
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A, Apple Lightning cable

**What are the steps to reproduce the issue?**
1. Plug iPad in
2. Jailbreak with checkra1n

**What do you expect, and what is happening instead?**
I expected the Loader app to open / install, but it is not there

**Does the issue also occur if you enable Safe Mode?**
I didn't try safe mode as I didn't know what it did.

**Any other info, error logs, screenshots, ...?**
The iPad does have an MDM profile on it that restricts installing non-allowed apps, not sure if that would effect it as I believed Loader installed itself as a system app.

**Edit 1 @ 11:24**: I was able to use iproxy to SSH into the iPad, so the iPad is definitely broken. Just loader is not showing up. Any way to manually open it?

**Comment by conorthedev** [comment]
Have you tried running ``uicache --all`` from the SSH prompt you got open?
Also try: ``ldrestart``. If none of them work run the following command: ``cd /var/binpack`` and then ``ls`` and see does the loader app exist there

**Comment by jacc** [comment]
1. `uicache --all` did not make the app show up.
2. `ldrestart` does not exist.
3. in `/var/binpack/applications/loader.app`, it does exist.

**Comment by jacc** [comment]
OK so here's what else I've tried:
I modified the MDM to include the bundle ID of `kjc.loader`, and in the MDM it's recognizing checkra1n as an app, but it's still not appearing on the actual iPad.

**Comment by m1stadev** [comment]
removing the MDM through SSH should work. try following something like [this](https://reddit.com/r/jailbreak/comments/blk1ul/tutorial_removing_mdm_profile_a_sort_of_howto_not/) guide?

edit: the only (potential) downside is that restoring may not bring back MDM, but I’ll try this guide then restore on my MDM iPad and see if it still stays

**Comment by jacc** [comment]
i’m not wanting to completely remove the MDM, i just want certain aspects (app restrictions) gone.

![image](https://user-images.githubusercontent.com/6956351/69918116-246df280-143c-11ea-8d40-361aba88e272.jpg)

you can see here by modifing the MDM i was able to include the checkra1n app in the list of allowed apps but it still doesn’t show up and it disappears after a reboot

**Comment by jacc** [comment]
Ended up just needing to remove the MDM profile and the checkra1n app is now installed.

**Comment by Siguza** [comment]
I see you managed to work around the issue, but for future reference I'm marking this as a duplicate of #451.
