### ISSUE TITLE
iPad Air 2 can't connect to ssh (ssh_exchange_identification: Connection closed by remote host)

### ISSUE THREAD

**Issue by joniand** [checkra1n/BugTracker#562]
**Tell us about your setup:**
1. What iDevice are you using?
iPad Air 2
2. On what version of iOS is it?
13.2.2 and 13.2.3
3. What version of checkra1n are you using? GUI or CLI?
0.9.6 GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Macbook Pro and iMac
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A with adapter on the Macbook (the one from apple) and straight USB-A on the iMac

**What are the steps to reproduce the issue?**
1. Jailbreak the device
2. Trying to connect to the port 22 (through the USB with iproxy)

**What do you expect, and what is happening instead?**
I expect to connect to the device. I get "ssh_exchange_identification: Connection closed by remote host" instead

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Dropbear runs on port 44. Is that what you're trying to connect to, or did you install OpenSSH?

**Comment by joniand** [comment]
Oh I thought it was 22. It works perfectly, thanks!
