### ISSUE TITLE
iPhone 6s Cydia Crash on boot Issue

### ISSUE THREAD

**Issue by antontech393** [checkra1n/BugTracker#565]
I'm on iOS 13.2.3 on an iPhone 6s with checkra1n beta 0.9.6, when i try to jailbreak and install the checkra1n app, it is successful. But when i try to install the cydia package manager, it opens for a split second and then crashes.

**Comment by Siguza** [comment]
Any chance you could attach a crash log?

**Comment by antontech393** [comment]
no because no info was stored on the phone

**Comment by iuseaios13on6s** [comment]
same issues anyone knows if this is being worked on

**Comment by Siguza** [comment]
Assuming this is a duplicate of #60.
