### ISSUE TITLE
Apps start crashing after jailbreaking

### ISSUE THREAD

**Issue by UnitTHK** [checkra1n/BugTracker#567]
**Tell us about your setup:**
1. What iDevice are you using?
IPhone 6s Plus and iPhone 6s (I have 2 devices)
2. On what version of iOS is it?
iOS 13.2.3 
3. What version of checkra1n are you using? GUI or CLI?
GUI 
4. What is your host system (OS version? Hackintosh? VM? etc.)?
VM
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Direct USB-A 3.0 to phone
**What are the steps to reproduce the issue?**

1. Install Checkra1n
2. Jailbreak using Checkra1n
3. Install Cydia
4. Start an app
...

**What do you expect, and what is happening instead?**
Nothing, apps should work normally 

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
https://pastebin.com/4hty7Yje

Only heavy apps, such as Games, Video Editor, etc crashes, other apps doesn’t crash. I suspect this is because of the mechanism of Checkm8, the error message seems similar to what checkm8 use (An DFU buffer bug)

**Comment by trulynb** [comment]
nicegram   crashes  when  starts

**Comment by ducanh2002123** [comment]
Another update: Only heavy apps (Such as games, video editing, etc) crashes, other light apps (YouTube, Facebook, etc) don’t crash. 
Issue also extended to an iPhone 6s (Same iOS version)

**Comment by UnitTHK** [comment]
Quick update. Liberty/ Liberty Lite seems to fix the problem, the apps stop crashing but it seems that some other issues are appearing. apps doesn't seem to have access to stuff that they normally do, like Discord can't access any photo

**Comment by quilenle** [comment]
Same to me, it seems like the issue on iOS 13, it was fine on iOS 12. After I updated my phone to iOS 13 and jailbroken with checkra1n (0.9.6 and 0.9.7) the heavy apps were crashing after opened a while.

**Comment by quilenle** [comment]
Dear @sbingner , @Siguza ,

Did you check this issue?

Best regards.

**Comment by Siguza** [comment]
Sounds like the generic "Substrate is broken" issue. :/

**Comment by quilenle** [comment]
Hi @Siguza , I saw the tweak was still working, but when I started using a heavy app such as a Game online, then the app will crashing after a few minutes of using.

**Comment by quilenle** [comment]
Hi @Siguza ,

After I tried much stuff, then I switch to "Safe Mode" on the checkra1n app, then the Game on my device is work.

I hope the team will figure out and fix it in the next version. Because this is a stable jailbreak I ever used. On my device, when it on iOS 12.4, I had 10 days used without any issues.

Best regards.

**Comment by UnitTHK** [comment]
Another update: A-Bypass seems to work really well to resolve my issue now, recommending it

**Comment by UnitTHK** [comment]
For now this issue will be closed

**Comment by quilenle** [comment]
> Another update: A-Bypass seems to work really well to resolve my issue now, recommending it

What do you mean "A-Bypass"? Could you please write down step-by-step? I really need this to run the jailbreak on my 6S

**Comment by UnitTHK** [comment]
I meant that the tweak name is A-Bypass
