### ISSUE TITLE
Cydia crashes on launch

### ISSUE THREAD

**Issue by bachelorbob** [checkra1n/BugTracker#569]
Checkra1n 0.9.6; iOS 13.2.3; iPhone SE

Cydia instantly crashes on launch.  No option to delete.  Checkra1n fails to re-install Cydia.

Rebooted, which forced need to re-jailbreak.  Cydia was already present after re-jailbreak.  Still instantly crashes on launch.  Checkra1n still fails to re-install Cydia.

Remaining option seems to be a full restore.

Cydia desperately needs the ability to respring and/or enter safe mode from outside of Cydia, without installing a tweak.  Also desperately needs the ability to be deleted from the homescreen.

Checkra1n desperately needs the ability to delete Cydia, not just an install option.

*****

Update: Used 'Restore System' to begin from scratch.  Re-jailbroke iPhone SE.  Re-installed fresh version of Cydia.  Still instantly crashes on launch.

**Comment by antontech393** [comment]
i have the same issue with my 6s also on 13.2.3 and i dont know what the problem could be

**Comment by rpendleton** [comment]
I wonder if you're running into this?
https://www.reddit.com/r/jailbreak/comments/durll6/news_fix_cydia_crashing_checkra1n/

Cydia was crashing on my iPhone X on 13.2.3, even after rebooting the device and reinstalling Cydia. Deleting the file mentioned in that post using SSH fixed it for me though: `/var/mobile/Library/Cydia/metadata.cb0`

**Comment by bachelorbob** [comment]
Deleting /var/mobile/Library/Cydia/metadata.cb0 via 'Termius' resolved the issue for me.

Back under iOS 6, there were many excellent tweaks that made jailbreaking well worth the effort.  Not seeing that under iOS 12-13.

**Comment by ruben17non** [comment]
how can i delete /var/mobile/Library/Cydia/metadata.cb0  ???
i restore system in loader, and now i not have SSH open.

allways crash cydia when i open, not know how can i solve this

**Comment by bachelorbob** [comment]
Install 'Termius' via the APP store.  Launch it.

Add a new host.
Hostname: localhost
Use SSH: toggle to ON
Port: 44
Username: root
Password: alpine

Once at the terminal 'root#' prompt, enter 'rm /var/mobile/Library/Cydia/metadata.cb0'  (Note the capital L and C, and the last character being a zero.)  With that file deleted, Cydia will no longer immediately crash on launch.

**Comment by antontech393** [comment]
When i try to connect it tells me Connection refused

**Comment by Extremejor** [comment]
Thank you!  Fixed.

Although it looks like while the apps installed via Cydia are on the Cydia "Installed" list, they don't seem to be working/are not present in Settings, e.g., SnowBoard or CoolFolder....

**Comment by bachelorbob** [comment]
> When i try to connect it tells me Connection refused

I do not know why that would happen, unless you have previously changed the default iOS password from 'alpine' to something else.  That, or you have not used the settings I previously described.

Note that anyone who jailbreaks an iOS device should change the 'root' and 'mobile' passwords from 'alpine' to something else ASAP.

**Comment by natewall824** [comment]
> When I try to connect it tells me Connection refused

I am having this same issue. I have had issues in the past with needing to SSH into it. However, I was on a different Ip address, so that might be my issue. I am just not sure how to fix that.

**Comment by daodevinc** [comment]
> 
> 
> Install 'Termius' via the APP store. Launch it.
> 
> Add a new host.
> Hostname: localhost
> Use SSH: toggle to ON
> Port: 44
> Username: root
> Password: alpine
> 
> Once at the terminal 'root#' prompt, enter 'rm /var/mobile/Library/Cydia/metadata.cb0' (Note the capital L and C, and the last character being a zero.) With that file deleted, Cydia will no longer immediately crash on launch.

Thxxxxxxxxxxxx !

Putty with 22 habitual port don't work, because when cydia down, remote ssh down i think..

**Comment by zidanmahmoud** [comment]
> Install 'Termius' via the APP store. Launch it.
> 
> Add a new host.
> Hostname: localhost
> Use SSH: toggle to ON
> Port: 44
> Username: root
> Password: alpine
> 
> Once at the terminal 'root#' prompt, enter 'rm /var/mobile/Library/Cydia/metadata.cb0' (Note the capital L and C, and the last character being a zero.) With that file deleted, Cydia will no longer immediately crash on launch.

Solved it for me, too. Thank you!

**Comment by Siguza** [comment]
Duplicate of #60.
