### ISSUE TITLE
Wifi not working, and relocked when rebooting

### ISSUE THREAD

**Issue by barayaghi** [checkra1n/BugTracker#570]
İpod touch 6th generation
İos 12.4.x
Last version 0.9 , gui, but also tried on the terminal method still not working
Hackintosh
Direct apple cable

İ jailbreaked my device, unlocked my icloud, it booted normally, but i couldnt open the wifi.... not like its not working or something, no, i couldnt open it at all. 
When i rebooted the device it relocked the icloud again and showed me the activation screen
I couldnt boot it into safemode cause whenever it reboots it relock itself, and ofcourse because checkra1n is tethered the jailbreak too deletes itself

Thanks for helping, hope you fix it soon.

**Comment by nullpixel** [comment]
how are you “unlocking” iCloud?

**Comment by boierito** [comment]
Sir close the issue. Checkra1n is not a iCloud bypass tool.
