### ISSUE TITLE
I installed chekra1n and my iPhone 7 booted just fine，I installed a lock screen plug-in of "Six (LS) IOS6". In the plug-in, I disabled the home key. However, I couldn't enter the mobile phone after the lock screen, and I still couldn't enter the home page after reinstalled chekra1n again, because he recorded the setting in the plug-in. How to solve this problem? I feel like I'm in a loop.

### ISSUE THREAD

**Issue by quyongtao** [checkra1n/BugTracker#573]
I installed chekra1n and my iPhone 7 booted just fine，I installed a lock screen plug-in of "Six (LS) IOS6". In the plug-in, I disabled the home key. However, I couldn't enter the mobile phone after the lock screen, and I still couldn't enter the home page after reinstalled chekra1n again, because he recorded the setting in the plug-in. How to solve this problem? I feel like I'm in a loop.

**Comment by nullpixel** [comment]
Use the same mode option in the checkra1n app.

**Comment by quyongtao** [comment]
i try to Use the safe mode option in the checkra1n app.and success! thanks ~

At 2019-12-03 15:30:30, "nullpixel" <notifications@github.com> wrote:


Use the same mode option in the checkra1n app.
