### ISSUE TITLE
stuck during jailbreak - device freezes completely

### ISSUE THREAD

**Issue by 0-g0d** [checkra1n/BugTracker#575]
**Tell us about your setup:**
1. What iDevice are you using?
iphone X 10,6
2. On what version of iOS is it?
13 Beta
3. What version of checkra1n are you using? GUI or CLI?
GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Hackintosh 10.13.4
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
A

**What are the steps to reproduce the issue?**
1. Click Jailbreak in GUI and wait :)
2. 
3.
...

**Does the issue also occur if you enable Safe Mode?**
Can't get into safe mode

Tried to jb using the gui tool, device freezes during jb process on checkra1n logo, can't get into DFU, no known combination of buttons changes anything, can't even turn it off or make it restart, hackintosh does not show that device is connected - neither itunes not gui tool

![2019-12-03 16 48 27](https://user-images.githubusercontent.com/58479153/70066404-f380ef80-15ec-11ea-81cb-293f45247cf5.jpg)

Thanks for any help in advance
g0d

**Comment by 0-g0d** [comment]
Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)

**Comment by nullpixel** [comment]
Beta versions of iOS are not supported by checkra1n, please update to the latest stable version.
