### ISSUE TITLE
sometimes  my phone gets locked

### ISSUE THREAD

**Issue by trulynb** [checkra1n/BugTracker#578]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone X      iPhone 10,3
2. On what version of iOS is it?
13.2.3
3. What version of checkra1n are you using? GUI or CLI?
0.9.5   gui
4. What is your host system (OS version? Hackintosh? VM? etc.)?
mac   10.15.1
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Belkin hub        usb-a  anker 

**What are the steps to reproduce the issue?**
1. I read sth in bed，and I keep touching the screen all the time，but sometimes my  device  get  locked suddenly
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**
no

**Any other info, error logs, screenshots, ...?**

**Comment by clubby789** [comment]
What tweaks have you got installed?

**Comment by boierito** [comment]
Use 0.9.6

**Comment by nullpixel** [comment]
This is an issue with a tweak, and not checkra1n.
