### ISSUE TITLE
Pls help me with this problem

### ISSUE THREAD

**Issue by tuank9999** [checkra1n/BugTracker#579]
![C4DC0E54-AFF0-48D0-81D9-49B9420343BD](https://user-images.githubusercontent.com/58514349/70141268-44661600-16c9-11ea-8ba1-5654328ebf0b.jpeg)

It keeps showing this text when i entered the first command in the second window. I made it successfully to bypass an iPhone 6 with this same Macbook but when i do with another phones it keep showing these text. Anyone know how to solve it?

**Comment by tcg96** [comment]
Run the command: `rm .ssh/known_hosts`

**Comment by nullpixel** [comment]
Not a checkra1n issue.
