### ISSUE TITLE
Error -31

### ISSUE THREAD

**Issue by Thathip** [checkra1n/BugTracker#581]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 5s
2. On what version of iOS is it?
iOS 12.4.3
3. What version of checkra1n are you using? GUI or CLI? Checkra1n 
0.9.6 GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
VMWare Mac 10.13 High Sierra
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB Lightning cable

**What are the steps to reproduce the issue?**
1. Connect to computer
2. Jailbreak
3.
...

**What do you expect, and what is happening instead?**
Run Checkra1n as CLI,Nothing

**Does the issue also occur if you enable Safe Mode?**
Never Tried

**Any other info, error logs, screenshots, ...?**
no

**Comment by nullpixel** [comment]
VMs are not supported.
