### ISSUE TITLE
iPhone X (10,3) iOS 13.2.3 FaceID Not Available

### ISSUE THREAD

**Issue by bweibel2** [checkra1n/BugTracker#584]
**Tell us about your setup:**
1. What iDevice are you using? iPhone X (10,3)
2. On what version of iOS is it? 13.2.3
3. What version of checkra1n are you using? GUI or CLI? Checkra1n beta 0.9.6 CLI
4. What is your host system (OS version? Hackintosh? VM? etc.)? 15" MacBook Pro 2018, macOS Catalina 10.15.1
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? I am connecting through a 2M Apple USB-C to lightning cable.

**What are the steps to reproduce the issue?**
1. Connect iPhone to MacBook using USB-C to lightning cable
2. Open CLI client, everything working correctly
3. Put iPhone into DFU Mode by pressing up then down on volume controls, hold side button until screen goes black, when the screen goes black I let go within a second the side button then immediately press the side button and volume down button for ~3 seconds, release side button and keep holding volume down until iPhone is in DFU Mode
4. Since the program automatically runs when the phone reaches DFU mode, there is no need for any further steps

**What do you expect, and what is happening instead?**
I expect my phone to work normally where I can use FaceID on boot up, but my phone shows an error (without fail) that FaceID is not functioning. I am unable to use FaceID then to unlock my phone, and when I turn off FaceID I am unable to reenable it.

**Does the issue also occur if you enable Safe Mode?**
Yes, this issue occurs no matter what happens with the Jailbreak active, and while in Safe mode.

**Any other info, error logs, screenshots, ...?**
Unfortunately I have been unable to get a error log for this issue, but it does happened last time I enabled the Jailbreak through CLI. Another issue that is annoying is that my phone screen becomes unresponsive while jailbreaking the first time through CLI forcing me to rejailbreak.
![IMG_5562](https://user-images.githubusercontent.com/58539088/70202262-2a3b3080-16e7-11ea-9cdc-8fae9aed92e6.png)
![IMG_5561](https://user-images.githubusercontent.com/58539088/70202263-2a3b3080-16e7-11ea-9df0-3f62a9197c3e.png)

**Comment by clarityzzz** [comment]
You have to jailbreak using the GUI to get into clean DFU mode. You're doing it the "dirty" way and that's why you have that error.

**Comment by nullpixel** [comment]
Use the GUI.
