### ISSUE TITLE
Some Apps (Gmail, etc) crashes on launch

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#587]
1. What iDevice are you using?
A: iPhone 7
2. On what version of iOS is it?
A: iOS 13.2.3
3. What version of checkra1n are you using? GUI or CLI?
A: Chechra1n 0.9.6, GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
A: Mac OS Mojave QEMU (Ra1nstorm)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
A: USB-A Apple Branded Cable

**What are the steps to reproduce the issue?**
1. Open the App Nomally

**What do you expect, and what is happening instead?**
I expect Apps to launch Normally but instead crashes instantly on launch sometime, having to reopen the app 5-6 times until the App is working normally.

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
[Crash Log of Gmail](https://github.com/checkra1n/BugTracker/files/3927114/text.2.txt)

**Comment by Siguza** [comment]
Could you get us a crash log when using Safe Mode, please?

**Comment by ghost** [comment]
> Could you get us a crash log when using Safe Mode, please?

[Gmail Crash Log in Safemode](https://github.com/checkra1n/BugTracker/files/3934541/Gmail-2019-12-07-075101.txt)

**Comment by Siguza** [comment]
There are `SubstrateInserter.dylib` and `libsubstrate.dylib` in your crash log, indicating you're not actually in Safe Mode...

**Comment by ghost** [comment]
> There are `SubstrateInserter.dylib` and `libsubstrate.dylib` in your crash log, indicating you're not actually in Safe Mode...

How do I go to Safemode properly? I’m using “Yobun” to go to safemode

**Comment by Siguza** [comment]
Use the checkbox in the checkra1n GUI.

**Comment by ghost** [comment]
> Use the checkbox in the checkra1n GUI.

Sorry but I’m nowhere near my computer, do you have any other methods please?

**Comment by nullpixel** [comment]
The only official way to enter no substrate mode is via the Mac app.
