### ISSUE TITLE
Stuck on "Checking if device is ready" on iPod Touch 7th gen

### ISSUE THREAD

**Issue by JimmyG49ers** [checkra1n/BugTracker#59]
**What device + iOS version are you on?**
13.1.3

**What are the steps to reproduce the issue?**
1.Enter recovery mode
2.Follow checkra1n steps
3.Stuck on "Checking if device is ready"
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**
I'm on a hackintosh

**Comment by FloppiTuna** [comment]
Not a dev, but I was getting the same problem when my iPad 6 was plugged into the front ports on my Hackintosh. I tried the back port, and it worked. Hope that helps you out a bit.

**Comment by JimmyG49ers** [comment]
> Not a dev, but I was getting the same problem when my iPad 6 was plugged into the front ports on my Hackintosh. I tried the back port, and it worked. Hope that helps you out a bit.

**Comment by JimmyG49ers** [comment]
Sorry for responding here, not sure how to do it on the website and
accidentally closed it. Could you show me what tutorial you followed for
hackintosh? Thank you!

**Comment by FloppiTuna** [comment]
If you have an AMD machine, use https://vanilla.amd-osx.com/

I'm not so sure how to do Intel machines.
