### ISSUE TITLE
Non Substrate/Safe Mode crashes

### ISSUE THREAD

**Issue by isyweisy** [checkra1n/BugTracker#591]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 6s

2. On what version of iOS is it?
13.2.3

3. What version of checkra1n are you using? GUI or CLI?
GUI

4. What is your host system (OS version? Hackintosh? VM? etc.)?
iMac running MacOS Catalina

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Directly to the Mac with a 3 party lightning to USB-A cable

**What are the steps to reproduce the issue?**
1. Install a tweak that crashes Springboard when it is booting
2. Respring

**What do you expect, and what is happening instead?**
What happens is safe mode crashes and then springboard restarts back into normal mode which crashes because of the tweak and goes back to safe mode. The boot loop continues for a while and then iOS reboots itself into stock so I need to re-jailbreak

**Does the issue also occur if you enable Safe Mode?**
I cannot access a Mac right now to try it that way but by booting to safe mode with the power app tweak it goes back to regular mode.

**Any other info, error logs, screenshots, ...?**
No

**Comment by Siguza** [comment]
Use the "Safe Mode" checkbox in the checkra1n GUI. That prevents Substrate from running at all, and should allow you to uninstall the tweak.
