### ISSUE TITLE
RESPRING

### ISSUE THREAD

**Issue by Filtar2000** [checkra1n/BugTracker#594]
**Tell us about your setup:**
1. What iDevice are you using? Iphone 7 plus
2. On what version of iOS is it? ios 13.1.2
3. What version of checkra1n are you using? GUI or CLI? GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)? OS MOJAVE 10.14.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple cable

**What are the steps to reproduce the issue?**
1. Install many tweaks (supported ones)
2. Often the device resprings automatically 
3.
...

**What do you expect, and what is happening instead?**

I expect the device doesn't respring automatically
**Does the issue also occur if you enable Safe Mode?**
No

**Any other info, error logs, screenshots, ...?**

**Comment by makejohn** [comment]
two solutions:
First: Download Cr4shed see which tweak caused this issue.
Second: using iCleaner Pro function "Cydia Substrate Addons" unselected all > apply and respring> then select tweak one-by-one, find out which one caused your problem

**Comment by Filtar2000** [comment]
i'll try

**Comment by Siguza** [comment]
If a tweak is crashing SpringBoard, then that is not an issue with checkra1n.
