### ISSUE TITLE
No cydia after phone boots up

### ISSUE THREAD

**Issue by fuomag9** [checkra1n/BugTracker#6]
**What device + iOS version are you on?**
iphone 8 13.2.2 on hackintosh mojave

**What are the steps to reproduce the issue?**
1. follow checkr1n instructions
2. iphone reboots
3. nothing has changed
...

**What do you expect, and what is happening instead?**

to have the jailbreak succeed and install cydia

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Hi there, you need to open the checkra1n app on your phone and select Cydia. Could you verify that this fixes your issue?

**Comment by fuomag9** [comment]
@nullpixel I fixed it in #16, the GUI steps for putting in DFU mode didn't work for me (I tried them multiple times)
