### ISSUE TITLE
Random restarts

### ISSUE THREAD

**Issue by vismittu** [checkra1n/BugTracker#600]
**Tell us about your setup:**
1. What iDevice are you using? iPhone X
2. On what version of iOS is it? iOS 13.2.3
3. What version of checkra1n are you using? GUI or CLI? 0.9.6
4. What is your host system (OS version? Hackintosh? VM? etc.)? Mac OS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? 3rd party lightning cable

**What are the steps to reproduce the issue?**
1. Jailbreak
2. And use the device
3.it sort of freezes and then restarts
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by jamminceo** [comment]
Since the new update that included the iPad 6 Gen, I have been experiencing abnormal reboots as compared to the original 9.1 setup which didn't crash at all. Since the update, I have had 7 reboots. I am still on the iOS 13.2.2 I am reinstalling on my MBP. USB 3rd party Cable. I have minimum two tweaks and they aren't tweaks that modify the operating system 

Duane

**Comment by Extremejor** [comment]
My iPhone SE on 13.2.3 just randomly rebooted.  I re-jailbroke, and Cydia now, although already installed & reinstalled, won't open, but, Sileo does (it was on there before) and Unc0ver says 'unsupported'  I do believe it's an original cable, using OSX 10.13.6 this time, originally used 10.11.6 to do the first jailbreak.  Have not tried safe mode.  Using checkra1n 0.9.6 beta, just downloaded it last night.

**Comment by rangeroverct** [comment]
Same issue here. iPhone 8, checkra1n 0.9.7 beta. Happening since 0.9.7.

**Comment by fennectech** [comment]
Same issue. First gen iPad Pro 9.7 WiFi/cell   Its absolutely infuriating.  About 2 or 3 times a week.

**Comment by fennectech** [comment]
Has it been fixed?

**Comment by Siguza** [comment]
Can only guess that it's a dupe of #533. :/
