### ISSUE TITLE
searchd keep crashing in background in 0.9.6

### ISSUE THREAD

**Issue by yur1xpp** [checkra1n/BugTracker#602]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone X

2. On what version of iOS is it?
iOS 13.2.2

3. What version of checkra1n are you using? GUI or CLI?
0.9.6, GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
KVM

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB A, Apple cable, USB controller

**What are the steps to reproduce the issue?**
1. Connect to power for charging
2. Lock screen
3. Wait and Cr4shed will reports searchd crashed
...

**What do you expect, and what is happening instead?**
Not crashing.

**Does the issue also occur if you enable Safe Mode?**
I diagnosed this by:
1-disable all tweak in iCleaner, only enabled Cr4shed, and using the steps to reproduce above. Result = crashed.

2-enter safe mode and observe processes running via CocoaTop, com.apple.searchd appear to peak at 100-200% regularly. Seems like related to com.apple.mobilesnotes.spotlight(if I didn’t misspelled it), as this also peaked, but not crashed.

3-downgrade to checkra1n 0.9.5 and this issue doesn’t happens at all.
Hope this helps!

**Any other info, error logs, screenshots, ...?**
Logs: https://pastebin.com/REcBqsFJ
Screenshot: https://imgur.com/a/Z15kDEh

**Comment by Siguza** [comment]
You have upwards of 10 libraries injected in that process. Use the "Safe Mode" checkbox in the checkra1n GUI.

**Comment by yur1xpp** [comment]
That solved the issue to check if it’s crashing still after entering safe mode via checkra1n (using Choicy eventually to disable process injection). Maybe I ask is entering safe mode manually via `killall -9 SEGV` is different from entering via checkra1n?

**Comment by Siguza** [comment]
Yes. checkra1n's safe mode doesn't run substrate at all, and thus prevents any tweak injection whatsoever. Other forms of safe mode try to disable tweaks somehow, but a lot of stuff has already been injected and patched by that point, and at least substrate itself is still manipulating processes.

**Comment by yur1xpp** [comment]
Didn’t know that, thanks! Is it possible to integrate the ‘checkra1n safe mode’ into the loader app without rebooting the device? Maybe a ldrestart that entering the safe mode?
