### ISSUE TITLE
Checkra1n doesn't get past boot screen when not using safe mode

### ISSUE THREAD

**Issue by foxt** [checkra1n/BugTracker#603]
**Tell us about your setup:**
1. What iDevice are you using? iPad7,5 (2018 Wifi)
2. On what version of iOS is it? 12.4.0
3. What version of checkra1n are you using? GUI or CLI? GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)? Catalina on MBP 2015
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple branded USB straight into computer

**What are the steps to reproduce the issue?**
1. Use checkra1n

**What do you expect, and what is happening instead?**
It boots and tweaks load. However, it gets stuck on the Apple/CR logo, and reboots after a while.

**Does the issue also occur if you enable Safe Mode?**
No.

**Any other info, error logs, screenshots, ...?**
I tried using safe mode and disabling all the tweaks in iCleaner Pro, don't know if that actually works. I have used u0 to install the tweaks before, which I can provide a list of here: https://hasteb.in/cecolope

**Comment by foxt** [comment]
Sorry if this is a really obvious bug that gets asked every 2 seconds :p

**Comment by Serenity420** [comment]
Same issue. Cr hangs at end when Mac says done and then reboots stock.
IPad Pro 1st gen. iOS 12.4. Using cr 0.9.6 GUI. 2013 MacBook Pro with newest Catalina. Tried few diff white stock apple cables gotten with IPad and iPhones. Don’t currently have a 3rd party cable. Got late and haven’t been able to try safe mode. After work tomorrow will run in verbose and snapshot ending before it reboots. Will keep an eye here and update. Been using u0 no prob. Interested in having both avail.

**Comment by Serenity420** [comment]
https://photos.app.goo.gl/BpgjBdrHuzYGuZ8T6
This is best pic I could snap of the end before it reboots back stock. Those last few line repeat a couple times with only the OP value changing. Then reboot

**Comment by Serenity420** [comment]
Tried with my iphone8 which has an extremely similar setup. Devices mirror one another. Same apps, iOS(12.4 unc0ver), same tweaks(IPad actually has less, no dark mode tweaks, no clean home screen stuff like on ip8),even same background. Same Mac and cord and all of course. Works flawlessly very quickly. Just assuming it’s prob the device. And since IPad Pro 1st gen all new ...to be expected. Will keep eye here and be glad to give info or assist anyway possible to help.

**Comment by Serenity420** [comment]
New cr 0.9.7 fixed my problem.

**Comment by foxt** [comment]
0.9.7 works for me! 😃

**Comment by FinleyVickers** [comment]
I'm having the same problem after restoring rootfs through the checkra1n app now whenever I try to rejailbreak I get stuck on the checkra1n boot loader screen
