### ISSUE TITLE
iPad Mini 5 not supported

### ISSUE THREAD

**Issue by dalem01** [checkra1n/BugTracker#605]
I have an iPad mini 5 running 13.1 and i used the .9.6 checkra1n that says it supports the ipad mini 5 now but in the app it says: Sorry, iPad Mini 5 (WiFi) (iOS 13.1) is not supported
Do i need to update to 13.2.3?

Thanks,
Dale

**Comment by Siguza** [comment]
The iPad mini 5 has an A12 SoC, which is not vulnerable to checkm8.  
Where did you see iPad mini 5 support advertised?

**Comment by dalem01** [comment]
Sorry, I seen it on the release notes for .9.6 on you're website but i looked again and its said iPad 5 but not iPad 5 mini. Sorry misunderstanding!! 
On another Note, if there is something i could do to help with getting the iPad Mini 5 supported, please let me know, donations or whatever is needed please dont hesitate to ask, kind of in desperate need for the iPad Mini 5 to be jailbroken, really i just need a single app on called Grider , if there is another way to load it without the jailbreak, i would do that as well and help anyone for helping me with it!! Thank You for all you all do!! 
-Dale

**Comment by Siguza** [comment]
I mean, you can sacrifice a couple of years of your life, become a hacker, reverse the A12 BootROM, try and find a new vulnerability... other than that, not much.
