### ISSUE TITLE
libfatman.dylib contains info about a user named "molt"

### ISSUE THREAD

**Issue by ath-inactive-account** [checkra1n/BugTracker#606]
Part of that user's filesystem structure is shown in strings, for instance at offset 0x00129b32, of the binary file : `libfatman.dylib`. This was probably not meant to be public.
The strings were apparently generated by the compilation of libimobiledevice.
This was discovered while decompiling the file with Cutter.

**Comment by Siguza** [comment]
Yes, that would be my old username/handle. While I don't consider this information private or critical, I do appreciate you reaching out to us about it. :)
