### ISSUE TITLE
Checkra1in loader icon not visible

### ISSUE THREAD

**Issue by vsbalint** [checkra1n/BugTracker#608]
**Tell us about your setup:**
1. What iDevice are you using? IPad Air 2
2. On what version of iOS is it? 13.2.3
3. What version of checkra1n are you using? GUI or CLI? GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)? OS X Catalina
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

I had first -20 error but finally managed to complete the process. But there is no Checkra1in icon on my screen and cannot install cydia 
Jailbreak was certainly complete as I was able to bypass iCloud using checkm8t.info tool

**Comment by Siguza** [comment]
We don't support iCloud lock bypass, sorry.
