### ISSUE TITLE
Apple tv stuck on installer

### ISSUE THREAD

**Issue by arturgoms** [checkra1n/BugTracker#611]
**Tell us about your setup:**
1. What iDevice are you using?
Apple tv 4 (2015)
2. On what version of iOS is it?
13.2
3. What version of checkra1n are you using? GUI or CLI?
GUI 0.9.6
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Macintosh - 10.15.2
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-C
**What are the steps to reproduce the issue?**
1. Plug device, enter DFU mode, jailbreak
2. On the boot the installer will come and no loading screen will raise
3. Nothing is installed
...

**What do you expect, and what is happening instead?**
I thing in this steps should be installed the jailbreak apps(?)

**Does the issue also occur if you enable Safe Mode?**
Don't tested

**Any other info, error logs, screenshots, ...?**
![8n21QP8q jpg-large](https://user-images.githubusercontent.com/6445354/70485684-5f23fa80-1ace-11ea-9804-9c429f97e939.jpeg)

**Comment by sbingner** [comment]
This should have been fixed in v0.9.7 - if not, let us know.

**Comment by cookuricoo** [comment]
0.9.8 same issue for me
