### ISSUE TITLE
Told to delete OTA and reboot but I don’t have an OTA in my storage

### ISSUE THREAD

**Issue by githubuser596** [checkra1n/BugTracker#617]
I’m on an IPad Mini 4 running iOS 13.2.3. I can download and install iOS 13.3, but it’s not currently downloaded on my IPad, and it’s not in my storage. However, whenever checkra1n tries to install Cydia I keep getting told that the OTA has preset the rootfs and to delete the OTA and reboot, which is impossible. I’ve even tried starting the download+install, deleting it, rebooting, reinstalling checkra1n and installing Cydia but I keep getting the same error.

**Comment by sbingner** [comment]
This was resolved in v0.9.7

**Comment by shtuseriff** [comment]
I'm using 0.9.7 and I'm having the same issue.. iPhone X 13.3
