### ISSUE TITLE
No call support

### ISSUE THREAD

**Issue by ravimalluriteja** [checkra1n/BugTracker#620]
After jailbreaking my iphone se i was able to unlock the device and I'm getting service in my device but I'm unable to call from the device or I'm unable to take calls to the device and not even mobile data is turning on.

**Comment by quilenle** [comment]
Did you bypass iCloud on your device?

**Comment by ravimalluriteja** [comment]
Yes

**Comment by baobaoit** [comment]
This is your answer that when you bypassed your iCloud then you can’t use the SIM functions (such as Call, Text,...)

You can close the issue please. Because of the team will not support this.

Best regards.
