### ISSUE TITLE
Cydia crashing

### ISSUE THREAD

**Issue by Ryotalol** [checkra1n/BugTracker#624]
**setup**
1. iphone 7
2. 13.2.2
3. Checkra1n 0.9.6
4. MAc

My Cydia crashes when I updated Cydia substrate and my tweaks don't show up on the settings screen. I tried deleting metadata.cb0 but it still crashes.

**Comment by ElianG25** [comment]
Same problem, i have to restore Jailbreak twice.

**Comment by Shadowedstalker** [comment]
Check out 
#354 
#364

**Comment by Siguza** [comment]
This may be related to either Cydia or Cydia Substrate, but either way it sound not related to checkra1n itself, so I'm gonna close this.
