### ISSUE TITLE
Checkra1n app crashes/CLI doesn’t work

### ISSUE THREAD

**Issue by HarleyWildman** [checkra1n/BugTracker#625]
**Tell us about your setup:**
1. What iDevice are you using?
iPad Pro 9.7 A1674
2. On what version of iOS is it?
13.2.3
3. What version of checkra1n are you using? GUI or CLI?
I have attempted to use GUI and CLI with differing results in each but without ever jailbreaking. 
4. What is your host system (OS version? Hackintosh? VM? etc.)?
2010 iMac on 10.11.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple USB-A to lighting. 

**What are the steps to reproduce the issue?**
1. Enter dfu, open terminal run CLI command, it runs but gives me one of three errors -10, -31 and/or “Abort trap: 6”
2. Enter dfu, open app, app says device in dfu mode and can’t get any further. 
3.Open checkrain app, follow instructions, get into dfu mode, then app crashes.
...

**What do you expect, and what is happening instead?**
1 in regards to 1 above: I expect the CLI to run and to boot and to see the verbose booting and then seeing jail broken iPadOS. Instead I get the errors above and my iPad boots to stock os. 
2 in regards to 2 above: same as what I described. 
3 in regards to 3 above: I expect to see the jailbreak tool running. Instead I see the app crash and nothing happens. 

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
I have done research for hours and I can’t find anything related to this issue. Or the ones that are similar like the error codes I’ve received I try those work around and still get nothing. Please help

**Comment by camschmottlach03** [comment]
I'm having the same problem regarding the app not letting me go further with jailbreaking after entering recovery mode.

**Comment by travisjneuman** [comment]
Just started experiencing this today as well.

Yesterday I was able to jailbreak my iPad Pro 10.5 (A1701) on iOS13.3, using Checkra1n 0.9.7 on a mid-2009 MBP running OS X (MacOS?) 10.11.6 El Capitan.

Today I rebooted my iPad, and went to do the jailbreak again - and it just keeps force closing on my MacBook at the same point each time. It will boot the iPad into recovery mode, let me press home and power buttons to continue the process, then the timer counts all the way down and it says I have entered DFU mode successfully. The progress bar starts going and hits about 2/5th of the way and the app "quits unexpectedly".

Here is the report I can pull when the app crashes for reference: [PasteBin: Checkra1n Force Quit Log](https://pastebin.com/raw/aRW6q7Ws)

Let me know if you would like me to send over any screenshots, or want me to do any further specific  testing. Happy to help out.

**Comment by neumant** [comment]
> Just started experiencing this today as well.
> 
> Yesterday I was able to jailbreak my iPad Pro 10.5 (A1701) on iOS13.3, using Checkra1n 0.9.7 on a mid-2009 MBP running OS X (MacOS?) 10.11.6 El Capitan.
> 
> Today I rebooted my iPad, and went to do the jailbreak again - and it just keeps force closing on my MacBook at the same point each time. It will boot the iPad into recovery mode, let me press home and power buttons to continue the process, then the timer counts all the way down and it says I have entered DFU mode successfully. The progress bar starts going and hits about 2/5th of the way and the app "quits unexpectedly".
> 
> Here is the report I can pull when the app crashes for reference: [PasteBin: Checkra1n Force Quit Log](https://pastebin.com/raw/aRW6q7Ws)
> 
> Let me know if you would like me to send over any screenshots, or want me to do any further specific testing. Happy to help out.

After attempting in safe mode and still being unable to get it to get by, I decided to reset my iPad as I did not really have much of a setup done yet so it wasn't going to be so painful. After the reset, it failed at the same spot - but then I ran it in Safe Mode, and this time it went through!

**Comment by HarleyWildman** [comment]
As soon as I updated my mac to Mojave I was able to jailbreak using ui and cli.  hope this helps
