### ISSUE TITLE
Unable to UnJailbreak

### ISSUE THREAD

**Issue by smiley-94** [checkra1n/BugTracker#626]
I had an issue with a tweak "preference organizer 2" that made my cydia and checkra1n apps crash (coudn't get into safe mode and cydia crashed every time i opened it), i had to rejailbreak, after a couple of attempts i got it to work, i managed to install filza but everything else seems to not show up unless i install PreferenceLoader, that makes my jailbreak crash again, i think some files are still there from the previous jb.
now i unjaibreaked and some apps i need still detects my iphone as jailbroken, do anyone know how to clean every file checkra1n and cydia so i can freely jailbreak again or just clean my phone from those files without loosing all my data?
thank you all for your patience.
i'm on iphone x, running 13.2.3.

**Comment by MrTaiany** [comment]
Download iOS 13.2.3 ipa then restore your device using iTunes then jailbreak

**Comment by smiley-94** [comment]
> Download iOS 13.2.3 ipa then restore your device using iTunes then jailbreak

Already done that, and it did not work, since i have to restore from backup

**Comment by MrTaiany** [comment]
download icleaner pro 

Press + then press Cydia substrate addons   

Turn off tweak that broke jailbreak

**Comment by antontech393** [comment]
Install iOS 13.3 that should really be it

**Comment by Siguza** [comment]
Apps having broken jailbreak detection is not a checkra1n issue, so I'm closing this.

**Comment by smiley-94** [comment]
> Install iOS 13.3 that should really be it

It doesn’t work sadly

**Comment by smiley-94** [comment]
> download icleaner pro
> 
> Press + then press Cydia substrate addons
> 
> Turn off tweak that broke jailbreak

Can you explain what you meant? I can’t use cydia stuff

**Comment by smiley-94** [comment]
> Apps having broken jailbreak detection is not a checkra1n issue, so I'm closing this.

It’s not a matter of broken jailbreak detection, i still have some old jailbreak files in my phone

**Comment by tonyvazgar** [comment]
I hope you have resolve it, but in case that you be looking for the solution maybe this will work:
Re-install checkra1n from computer/mac
It should be working because the system recover the permissions
Otherwise re-install cydia
