### ISSUE TITLE
[Help] checkra1n randomly disappears from my iPhone X (have to rejailbreak) 

### ISSUE THREAD

**Issue by sshrmr** [checkra1n/BugTracker#631]
[Help] checkra1n randomly disappears from my iPhone X (have to rejailbreak)

iPhone X, tried different versions of checkra1n (0.9.1, 0.9.3, 0.9.5, 0.9.6) and different versions of iOS 13 (13.2.2, 13.2.3, 13.3) - still having the same issue. After 2-3 days of using checkra1n it just randomly disappears. 

For example, i open YouTube and i see that Cercube is all of a sudden no longer injected into the app, the tweak list disappears from the settings e.t.c.

So i have to plug it to my Mac and rejailbreak again. 

Anyone facing this too?

**update**: figured that reinstalling Cydia Substrate fixes the issue. But its still there :/

**Comment by Siguza** [comment]
Most likely the same issue as #533.
