### ISSUE TITLE
Battery graphs not showing iPhone X 13.2.3

### ISSUE THREAD

**Issue by Nuke11Proof** [checkra1n/BugTracker#639]
Settings - Battery - Graphs and usage doesn't show up, spinning wheel for ever. 

Solution: Reboot, it doesn't work when iPhone its on jailbreak mode.

**Comment by boierito** [comment]
It is a tweak problem. Close the issue please.

**Comment by Nuke11Proof** [comment]
> It is a tweak problem. Close the issue please.

Hi! Has been that problem resolved?
