### ISSUE TITLE
Some heavy apps crashes

### ISSUE THREAD

**Issue by quilenle** [checkra1n/BugTracker#644]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 6S

2. On what version of iOS is it?
iOS 13.2.3

3. What version of checkra1n are you using? GUI or CLI?
beta 0.9.6 and beta 0.9.7 - GUI

4. What is your host system (OS version? Hackintosh? VM? etc.)?
Hackintosh Mojave 10.14.6 (18G2022)

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A

**What are the steps to reproduce the issue?**
1. Jailbreak the device successfully
2. Open a heavy app such as a MOBA Game Online

**What do you expect, and what is happening instead?**
Expect: the app is working normally
Happening: the app is crashing after a few minutes

**Does the issue also occur if you enable Safe Mode?**
No

**Any other info, error logs, screenshots, ...?**
No

**Comment by quilenle** [comment]
Dear @Siguza ,

Since issue https://github.com/checkra1n/BugTracker/issues/567 has been closed, we will discuss it here.

Best regards.

**Comment by UnitTHK** [comment]
Okay, so what I’m saying is
The A-Bypass tweak is working well on resolving the crashes for me,
Search google for it, I can’t share the link to it here

**Comment by UnitTHK** [comment]
Never mind I think I can https://repo.rpgfarm.com/package/com.rpgfarm.a-bypass

**Comment by UnitTHK** [comment]
@quilenle

**Comment by quilenle** [comment]
> Never mind I think I can https://repo.rpgfarm.com/package/com.rpgfarm.a-bypass

Dear @ducanh2002123 ,

Thank you for sharing, this is so wonderful. Currently, my MOBA game works and it isn't crashing instantly. I will test more and summary at the day-end.

Now, I use the Liberty Lite (Beta) tweak to bypass the jb detection, cause the A-Bypass tweak doesn't work for my banking.

Best regards.

**Comment by UnitTHK** [comment]
Use multiple in chain, one for the type of app you need

**Comment by quilenle** [comment]
Dear @ducanh2002123 , @Siguza ,

After I tested a while, my summary is the A-Bypass tweak can fix the crashes on iOS 13 (I don't know why).

I hope the team fixes this issue officially in the next version.

I will close the issue here.

Best regards.

**Comment by Siguza** [comment]
Okay, if A-Bypass helps, that sounds like either an incompatible tweak, or an issue with jailbreak detection, which is not something we currently plan to counter.

**Comment by baobaoit** [comment]
Hi @Siguza , this issue only on iOS 13.X, I didn’t need A-Bypass tweak on iOS 12.4 and 11.X for my game.

**Comment by Siguza** [comment]
Okay, then it's probably an incompatible tweak and A-Bypass is stopping it from being injected... I guess?

**Comment by baobaoit** [comment]
When I don’t install any tweak the game is crashing instantly when I start. When I installed the A-Bypass tweak, the game is start normally.

**Comment by baobaoit** [comment]
The game is start and play normally on non-jb state and after I installed A-Bypass tweak.

**Comment by Siguza** [comment]
Does it happen if you run checkra1n with Safe Mode too?

**Comment by quilenle** [comment]
Hi @Siguza ,

Reference to my comment here: https://github.com/checkra1n/BugTracker/issues/567#issuecomment-565814814
The app is working with Safe Mode.

Sorry about the late reply, baobaoit is my main account.

Best regards.
