### ISSUE TITLE
Iphone 6s not boot

### ISSUE THREAD

**Issue by baonq243** [checkra1n/BugTracker#646]
**Tell us about your setup:**
1. What iDevice are you using?
Iphone 6s
2. On what version of iOS is it?
13.3
3. What version of checkra1n are you using? GUI or CLI?
9.0.7
4. What is your host system (OS version? Hackintosh? VM? etc.)?
10.13.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Usb-C hub
**What are the steps to reproduce the issue?**
1. Start button
2. Iphone Reboot
3. Stuck Black Screen, I press Power + Home but still stuck after white boot screen logo

...

**What do you expect, and what is happening instead?**
What should i do now?

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by sergey-zakharov** [comment]
@baonq243 Did you fix that? What was the reason and the way to fix?
