### ISSUE TITLE
Checkra1n won't work ipad air 2 ios 13.3

### ISSUE THREAD

**Issue by jinn6x** [checkra1n/BugTracker#649]
**Tell us about your setup:**
1. ipad air 2 
2. 13.3
3. checkra1n 0.9.7 beta / GUI
4. Macbook 15''
5. USB-A to lightning cable 

**What are the steps to reproduce the issue?**
1. lunch Checkra1n and everything worked flawlessly
2. lunched another another app that does the one click to open icloud (worked in other devices)
3.ipad still stuck on hello activation lock and nothing works
...

**What do you expect, and what is happening instead?**
i expect to bypass icloud and i have done it one other devices but not on ios 13.3 but the ipad stuck on hello icloud activation lock and nothing works like home button and the ipad won't let me even turn it off (exactly like the video below)
i wonder if this problem is only on ios 13.3 or Checkra1n 0.9.7

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**
https://www.youtube.com/watch?v=WCrzF_tLPIM
i had the same problem as this guy i want to know if his solution actually works

**Comment by jinn6x** [comment]
https://youtu.be/WCrzF_tLPIM?t=274
my exact problem

**Comment by Siguza** [comment]
The purpose of checkra1n is to jailbreak, not bypass iCloud lock.
