### ISSUE TITLE
Respring after enter password.

### ISSUE THREAD

**Issue by jdjingdian** [checkra1n/BugTracker#65]
**What device + iOS version are you on?**
iPhone 7 Plus iOS 13.2.2

**What are the steps to reproduce the issue?**
1.Use Checkra1n to jailbreak the device.
2.Poweroff and restart(without checkra1n)
3.Use Checkra1n to jailbreak again, after rebooting, I try to enter my password, then the system freeze, after a while my 7p respring and getting loop.
...

**What do you expect, and what is happening instead?**
No idea whats happening, I only install a tweak named preferenceLoader and ConditionalWIFI4 to unlock network permission for cydia and checkra1n.

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Hi, this is an issue with the tweaks you have installed, and not with checkra1n.
