### ISSUE TITLE
Cydia Crashing after downloading a tweak

### ISSUE THREAD

**Issue by natewall824** [checkra1n/BugTracker#656]
**Tell us about your setup:**
1. What iDevice are you using? iPhone X
2. On what version of iOS is it? iOS 13.2.2
3. What version of checkra1n are you using? GUI or CLI? 0.9.7
4. What is your host system (OS version? Hackintosh? VM? etc.)macOS Mojave
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?Apple cable

**What are the steps to reproduce the issue?**
1. Open Cydia
2. Cydia Crashes
3. 
...

**What do you expect, and what is happening instead?**
I expect to open Cydia and it should work.

**Does the issue also occur if you enable Safe Mode?**
yes

**Any other info, error logs, screenshots, ...?**
It started off by me downloading a tweak that included extra tweaks(possibly uasharedtools). I downloaded it and it worked. I didn't want the tweak anymore so, I went to remove it, then my Cydia crashed. So I tried to re-jailbreak it without restoring. That did not work, so then I tried to restore. That did not work either. So I have had the issue of Cydia crashing in the past. Normally I would ssh into the phone and fix it. However, I previously ssh from a different IP. I am not sure if that has anything to do with it. But when I go to ssh into the phone it tells me that connection is refused. I am not sure how to get my phone back to being jailbroken. Anything would help thanks.

**Comment by moedayraki** [comment]
Same thing is happening to me but with a different setup.
What iDevice are you using? iPhone 8
On what version of iOS is it? iOS 13.3
What version of checkra1n are you using? GUI or CLI? 0.9.7 GUI
What is your host system (OS version? Hackintosh? VM? etc.)macOS Catalina
How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A

What are the steps to reproduce the issue?

Open Cydia
Cydia Crashes
...

What do you expect, and what is happening instead?
I expect to open Cydia and it should work.

Does the issue also occur if you enable Safe Mode?
yes

Everything was working perfect and fine.
I installed Youtube Tools (Info in the following link)
https://www.ios-repo-updates.com/repository/electra-s-ios-utilities/package/com.justinpetkovic.youtubetools/
and then...boom, all my tweaks stopped working and the phone was not jailbroken anymore. Everything returned to normal and was so limited. 
Tried to open Cydia, it didnt work. 
Tried to Rejailbreak, it didnt work.
Tried Safe Mode, didnt work.
Tried Verbose Boot, didnt work.
Tried deleting youtube application, didn't work.

Dunno what to do next

**Comment by natewall824** [comment]
> Same thing is happening to me but with a different setup.
> What iDevice are you using? iPhone 8
> On what version of iOS is it? iOS 13.3
> What version of checkra1n are you using? GUI or CLI? 0.9.7 GUI
> What is your host system (OS version? Hackintosh? VM? etc.)macOS Catalina
> How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A
> 
> What are the steps to reproduce the issue?
> 
> Open Cydia
> Cydia Crashes
> ...
> 
> What do you expect, and what is happening instead?
> I expect to open Cydia and it should work.
> 
> Does the issue also occur if you enable Safe Mode?
> yes
> 
> Everything was working perfect and fine.
> I installed Youtube Tools (Info in the following link)
> https://www.ios-repo-updates.com/repository/electra-s-ios-utilities/package/com.justinpetkovic.youtubetools/
> and then...boom, all my tweaks stopped working and the phone was not jailbroken anymore. Everything returned to normal and was so limited.
> Tried to open Cydia, it didnt work.
> Tried to Rejailbreak, it didnt work.
> Tried Safe Mode, didnt work.
> Tried Verbose Boot, didnt work.
> Tried deleting youtube application, didn't work.
> 
> Dunno what to do next

That’s weird because I had YouTube tools. But that wasn’t what caused it for me. Someone told me a possible way to fix it. I am going to try and if it works I will comment what I did.

**Comment by moedayraki** [comment]
> > Same thing is happening to me but with a different setup.
> > What iDevice are you using? iPhone 8
> > On what version of iOS is it? iOS 13.3
> > What version of checkra1n are you using? GUI or CLI? 0.9.7 GUI
> > What is your host system (OS version? Hackintosh? VM? etc.)macOS Catalina
> > How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A
> > What are the steps to reproduce the issue?
> > Open Cydia
> > Cydia Crashes
> > ...
> > What do you expect, and what is happening instead?
> > I expect to open Cydia and it should work.
> > Does the issue also occur if you enable Safe Mode?
> > yes
> > Everything was working perfect and fine.
> > I installed Youtube Tools (Info in the following link)
> > https://www.ios-repo-updates.com/repository/electra-s-ios-utilities/package/com.justinpetkovic.youtubetools/
> > and then...boom, all my tweaks stopped working and the phone was not jailbroken anymore. Everything returned to normal and was so limited.
> > Tried to open Cydia, it didnt work.
> > Tried to Rejailbreak, it didnt work.
> > Tried Safe Mode, didnt work.
> > Tried Verbose Boot, didnt work.
> > Tried deleting youtube application, didn't work.
> > Dunno what to do next
> 
> That’s weird because I had YouTube tools. But that wasn’t what caused it for me. Someone told me a possible way to fix it. I am going to try and if it works I will comment what I did.

I would really appreciate that. It's hard to get out of jail and them come back LOL

**Comment by moedayraki** [comment]
Nate!! I found the solution for me! Everything is working again!

https://www.icloud.com/shortcuts/d92eef70a014452ab0146a43bc6aaddd

Just open this icloud shortcut and run it on your iphone. You can check the shortcut script before running it (If you don't trust me).
It just ssh to your localhost and deletes a file from inside cydia. You need to have your Shortcuts application trusting outsource shortcuts.

Please let me know if it works or not.

**Comment by natewall824** [comment]
> Nate!! I found the solution for me! Everything is working again!
> 
> https://www.icloud.com/shortcuts/d92eef70a014452ab0146a43bc6aaddd
> 
> Just open this icloud shortcut and run it on your iphone. You can check the shortcut script before running it (If you don't trust me).
> It just ssh to your localhost and deletes a file from inside cydia. You need to have your Shortcuts application trusting outsource shortcuts.
> 
> Please let me know if it works or not.

I will try it when I get a chance. But once you ran that what did you do?

**Comment by moedayraki** [comment]
> > Nate!! I found the solution for me! Everything is working again!
> > https://www.icloud.com/shortcuts/d92eef70a014452ab0146a43bc6aaddd
> > Just open this icloud shortcut and run it on your iphone. You can check the shortcut script before running it (If you don't trust me).
> > It just ssh to your localhost and deletes a file from inside cydia. You need to have your Shortcuts application trusting outsource shortcuts.
> > Please let me know if it works or not.
> 
> I will try it when I get a chance. But once you ran that what did you do?

After deleting the metadata.cb0, cydia started to work. I then went and downgraded the substrate compatibility later from cydia and everything started to work

**Comment by natewall824** [comment]
I was having the issue of connection refused in terminal. And even the metadata delete wasn’t working. So what I did was restored my iPhone and now cydia is working.
