### ISSUE TITLE
Can't Re-Jailbreak iPhone 6S + after adding tweaks.

### ISSUE THREAD

**Issue by Luminator97** [checkra1n/BugTracker#659]
So last night I used CheckRa1n on my phone, and it worked. Cydia was installed and I was getting tweaks and themes. Then my phone crashed and I didn't have CheckRa1n again (Cydia doesn't seem to open unless CheckRa1n is on my phone). I tried to re-jailbreak, but I get this message: 

> [!]: Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode pass the '-s' option) (error code: -20) - [!]: Unknown error (error code: -20)

I saw on your website to press and hold the Vol-UP button while it reboots, but that didn't work.

**Comment by Siguza** [comment]
If your phone boots to the lock screen, just make sure to unlock it before unplugging, then the bootstrap should still get uploaded.

If your phone does _not_ boot to the lock screen, invoke checkra1n with `-s` as the error message says, then your phone will boot with substrate disabled, allowing you to find and uninstall the tweak that's crashing SpringBoard.

**Comment by quilenle** [comment]
There is a Safe Mode option on the checkra1n UI, clicks on that before you click on the Start button.

**Comment by Luminator97** [comment]
I downloaded checkra1n, but there was no GUI to open. It only had the console version. I don't know how to invoke checkra1n with -s.

**Comment by Siguza** [comment]
Ok I need a screenshot of your setup.

**Comment by Luminator97** [comment]
Setup?

**Comment by Luminator97** [comment]
I can't enter no-substrate mode when I press and hold Vol-UP while my phone boots.

**Comment by Luminator97** [comment]
I want to Un-Jailbreak my phone, but I don't know how to.

**Comment by Luminator97** [comment]
Can someone get me a direct download of the GUI? It's not in the package contents in 0.9.6 and 0.9.7 betas

**Comment by Siguza** [comment]
Are you kidding me? Wtf are you downloading?

Go to https://checkra.in, download the dmg, and there is precisely one thing on there, which is the GUI app.

**Comment by Luminator97** [comment]
![Screen Shot 2019-12-21 at 5 40 27 PM](https://user-images.githubusercontent.com/34755627/71315019-0717bd00-2419-11ea-94db-522dc9e6a0b8.png)
That's all I've got. No GUI, just something that opens terminal and another thing that doesn't work.

**Comment by Luminator97** [comment]
Yeah, I did download the dmg from checkra.in, saved it to my applications, hit show package contents, content, macos, and that is what is there

**Comment by Siguza** [comment]
The thing where you do "show package contents" - click "open" instead.

**Comment by Luminator97** [comment]
It never opens. It just looks like it's going to, then it doesn't open.

**Comment by Siguza** [comment]
System Preferences > Security & Privacy > General > Open Anyway

**Comment by Luminator97** [comment]
There is no "Open Anyway"

**Comment by Siguza** [comment]
Wtf is wrong with your installation. But ok, do this:

Open a Terminal window and drag the "checkra1n" binary from your screenshot above in there. Then hit space, type `-g` and hit enter.

**Comment by Luminator97** [comment]
Thanks! That worked!

**Comment by Siguza** [comment]
I'll close this ticket then. Safe Mode should give you what you need.

**Comment by Luminator97** [comment]
I have this app that won't work because my phone is jailbroken. I opened CheckRa1n to restore my system, and that worked, but the app still detects my phone as jailbroken. Anything i can do to fix it?
