### ISSUE TITLE
Timed out waiting for bootstrap upload (Error code: -20)

### ISSUE THREAD

**Issue by CircuitSavage** [checkra1n/BugTracker#66]
**What device + iOS version are you on?**
IPX, 13.1.3

**What are the steps to reproduce the issue?**
1.Booting DFU with the app
2.Booting DFU then using the app
3.
...

**What do you expect, and what is happening instead?**
I'm expecting this app to run through without error codes

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Do you have any tweaks installed?

**Comment by CircuitSavage** [comment]
I couldn't even get to installing tweaks

**Comment by CircuitSavage** [comment]
No checkra1n app on springboard & no cydia

**Comment by nullpixel** [comment]
Hm, I'm going to close this as a dupe of #13. Could you provide more information over there please?
