### ISSUE TITLE
Apple Pencil lagging iOS13.2.3

### ISSUE THREAD

**Issue by photry** [checkra1n/BugTracker#661]
I observe such lagging with Note Apps and Proceate. The Pencil works well in Safe Mode. Is there anything with substrate?

**Comment by Siguza** [comment]
If it works fine in Safe Mode, the issue is either with Substrate or a tweak. Best I can recommend is installing iCleaner and selectively disabling tweak dylibs until you find the culprit.  
Gonna close this issue now as it's not caused by checkra1n directly.

**Comment by photry** [comment]
Thanks.
