### ISSUE TITLE
Loader gives me this error

### ISSUE THREAD

**Issue by CyferNinja3006** [checkra1n/BugTracker#666]
**Tell us about your setup:**
1. What iDevice are you using?
ip7
2. On what version of iOS is it?
13.3
3. What version of checkra1n are you using? GUI or CLI?
gui
4. What is your host system (OS version? Hackintosh? VM? etc.)?
ra1nstormed device
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Standard lightning to usb a cable from the box
**What are the steps to reproduce the issue?**
1. Open loader

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
![f](https://user-images.githubusercontent.com/58089281/71313567-7057fa00-2432-11ea-8355-8b4401bac57a.png)

**Comment by CyferNinja3006** [comment]
This also happens if i stand next to my wifi router, my wifi chip is fine, it works perfectly for all my other applications

**Comment by CyferNinja3006** [comment]
Also, i have find my iphone turned off but not share my location

**Comment by Siguza** [comment]
On that device, does https://checkra.in load in the browser?

**Comment by CyferNinja3006** [comment]
No, checkra.in is blocked by my wifi provider so i have to visit it on my mobile data once and then it works as long as I dont clear safari data, I'll try using the app on my data and seeing if it works

**Comment by CyferNinja3006** [comment]
Edit: Just tried it on my data and it works, thanks!
