### ISSUE TITLE
Crashed on iPhone X

### ISSUE THREAD

**Issue by koda-png** [checkra1n/BugTracker#667]
Installed checkra1n v. 0.9.7 on an iPhone X running iOS 13.3. Was working fine for a few hours or so, installed around 5-6 tweaks. Went to install a tweak before the screen froze on the loading icon for about 12 minutes. Device went unresponsive for about another 5 minutes before rebooting. Upon reboot, I found that the checkra1n app had removed itself from the springboard, and the Cydia app is still present, but will not open. Tried to reinstall numerous times, but code stops at “Booting...” before device returns to normal apple logo screen. (3x each attempt).

**Comment by Fmhassni** [comment]
My problem is like yours. I lost all configurations after restarting my iphone X IOS 13.3...

**Comment by Siguza** [comment]
Enable Safe Mode in the checkra1n GUI.

**Comment by Fmhassni** [comment]
I activated the safe mode, but the problem is still persistent, after a restart of my iphone X IOS 13.3 the Loder checkra1n disappears and cydia no longer works.
I did the operation 5 times without success.

**Comment by koda-png** [comment]
Sort of found a fix, since the checkra1n app was not on the device, instead I restored the device software (13.3), which removed the bugged jailbreak and was able to reinstall. Works as it should again.

**Comment by Fmhassni** [comment]
if you restart your iphone does the jailbreak it work?
