### ISSUE TITLE
Time out during initial jailbreak boot

### ISSUE THREAD

**Issue by JaycePlays** [checkra1n/BugTracker#67]
**What device + iOS version are you on?**
iPhone 8, IOS 13.2.2

**What are the steps to reproduce the issue?**
1. Install a tweak of some sort and get stuck on loading to respring
2. Force restart phone
3. Connect to computer and initiate jailbreak
...

**What do you expect, and what is happening instead?**
I don't exactly know but checkra1n won't boot again and I keep getting the same error. Im forced to restore my phone to factory and restore my backup before I can boot again

**Any other info, error logs, screenshots, ...?**
![Screen Shot 2019-11-10 at 11 37 41 AM](https://user-images.githubusercontent.com/26234885/68547353-8ba10580-03ae-11ea-92cd-264448df5ae0.png)

**Comment by nullpixel** [comment]
Hi, this is an issue with the tweak you installed. You could try booting with volume up held, but if that doesn't resolve your issue then you will need to restore.
