### ISSUE TITLE
0.9.7 not works for ios 13.3 icloud passby

### ISSUE THREAD

**Issue by TBSKBJustin** [checkra1n/BugTracker#671]
**Tell us about your setup:**
1. What iDevice are you using?
Iphone 7 plus 128g
2. On what version of iOS is it?
13.3(I want to back to 13.2.3 but apple close it)
3. What version of checkra1n are you using? GUI or CLI?
0.9.7
4. What is your host system (OS version? Hackintosh? VM? etc.)?
10.15.1 catalina
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
usb a

**What are the steps to reproduce the issue?**
1. I saw 0.9.7 work with ios 13.3 so i download it(also because apple stop to back to 13.2.3)
2. there is nothing wrong with 0.9.7 to booting it but after the iphone turn on(to the first page that let you choose the language )
3. after i use icloud passby, it stop in the first page and the just like use 0.9.6 for ios 13.3
...

**What do you expect, and what is happening instead?**
just want make it works

**Does the issue also occur if you enable Safe Mode?**
yes

**Any other info, error logs, screenshots, ...?**

**Comment by quilenle** [comment]
The first thing, this issue page only supports the issue after jailbreaking your device. It's doesn't support bypass iCloud - this is not the main function of this tool.
The second, the iOS 13.3 fixes the iCloud bypass. You can research for more details.
Finally, you can close this issue now.
Best regards.
