### ISSUE TITLE
Ios 13.3 tweaks dosent show up

### ISSUE THREAD

**Issue by EXEM0N** [checkra1n/BugTracker#676]
**Hi!**
I jailbreaked ios 13.3 (iphone 7) and everything worked except for the tweaks.
The tweaks dosent show up in settings. 
I attempt to rejailbreak but still nothing happens.
Im using mac os x and the latest version of checkra1n.
I hope you guys can fix it and keep up the work!

Im sorry for bad english.

**Comment by jaytj95** [comment]
+1 Tweaks don't show up and Cydia fails to open (as if I'm unjailbroken) although not seeing any errors on checkra1n mac app

**Comment by Siguza** [comment]
That's an issue in 3rd party software, not checkra1n.
