### ISSUE TITLE
Safe Mode

### ISSUE THREAD

**Issue by MohdAlaagip** [checkra1n/BugTracker#68]
**iPhone 6S iOS 13.2.2**

**Installed lock Screen Tweak and now I can't Get to my Home Screen to remove the tweak**
1.
2.
3.
...

**a shortcut to enter safe mode through the iPhone or the App**

**Shortcut to enter Safe Mode**

**Comment by nullpixel** [comment]
Hi, if you ssh in and run `killall -SEGV SpringBoard` you will be able to enter Safe Mode. I'm closing this issue as it's not an issue with checkra1n.
