### ISSUE TITLE
BFU mode broken

### ISSUE THREAD

**Issue by Schlaubischlump** [checkra1n/BugTracker#683]
According to https://blog.elcomsoft.com/2019/12/bfu-extraction-forensic-analysis-of-locked-and-disabled-iphones/ BFU (Before First Unlock) data extraction is broken since checkra1n version 0.96. I can verify that data extraction is indeed not working using version 0.97. Sadly I can not test if it was working before, because my iPad Pro (9.7) was not supported in the previous versions.

**Comment by Siguza** [comment]
We never aimed to support that.
