### ISSUE TITLE
error -20 wile trying to use iCloud bypass need a way to restore rootfs though cli or other

### ISSUE THREAD

**Issue by iha3ker1920** [checkra1n/BugTracker#684]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 5s (gsm)
2. On what version of iOS is it? 12 .4.4
3. What version of checkra1n are you using? GUI or CLI? both
4. What is your host system (OS version? Hackintosh? VM? etc.)? macOS High Sierra and others on official Mac!
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A Official cable

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by quilenle** [comment]
Sorry, but this issue page doesn't support for iCloud bypass issue. Only support the issue before and after you jailbreak your device related to the tool.
Please close the issue now. Best regards.

**Comment by iha3ker1920** [comment]
It’s more of a jailbroken iPhone that had uncover on it but is now iCloud locked and can only be iCloud unlocked to use but I get error -20 when trying to use Checkra1n because of uncovers rootfs not being restored if there was only a rootfs restore for Checkra1n in cli or program I could unlock my iPhone

**Comment by Siguza** [comment]
You can do a clean IPSW restore.
