### ISSUE TITLE
Installer crashes when trying to install cydia

### ISSUE THREAD

**Issue by wbraffman** [checkra1n/BugTracker#7]
**iPad7 + 13.1?**

**What are the steps to reproduce the issue?**
1. Jailbreak the device
2. Open app on device
3. click cydia
...

**What do you expect, and what is happening instead?**
To install cydia, but instead it just crashes

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Hi, I've closed this issue as a duplicate of #2.
