### ISSUE TITLE
Conflict with unc0ver on iOS 12.4

### ISSUE THREAD

**Issue by a1malik** [checkra1n/BugTracker#70]
**What device + iOS version are you on?**

iPad Pro 2nd gen. 12.9 inches on 12.4

**What are the steps to reproduce the issue?**
1.  If jailbroken with unc0ver, new checkra1n version of Cydia won’t install. 
2.
3.
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by WarningImHack3r** [comment]
If Cydia is already installed then no need to reinstall it ? Reboot and jailbreak with cherckra1n, then Cydia should work fine as it does with unc0ver

**Comment by Lonegwadiwaitor** [comment]
I believe checkra1n isn't meant for 12.4. It's meant for 13.2+. You should (and probably need) to update your device to use checkra1n.

**Comment by Lonegwadiwaitor** [comment]
also make sure to read the FAQ in the future.

**Comment by nullpixel** [comment]
Checkra1n is not compatible with devices already jailbroken. Please restore the rootfs and try again.
