### ISSUE TITLE
slow, or hung, iOS kernel extensions

### ISSUE THREAD

**Issue by reduritsch** [checkra1n/BugTracker#700]
I'm a security researcher and one of the things I do is fuzz iOS kernel extensions.

**Tell us about your setup:**
1. What iDevice are you using?
from iPhone 7 to iPhone X
2. On what version of iOS is it?
iOS 12.4 to iOS 13.3.1 beta
3. What version of checkra1n are you using? GUI or CLI?
0.9.3.2 to 0.9.7
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacBook Pro 2018, macOS 10.15 Catalina
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB C cable
**What are the steps to reproduce the issue?**
1. root the device with checkra1n
2. run my fuzzer
3.
...

**What do you expect, and what is happening instead?**
I expect fairly swift speed through each kext that I am able to open. After a few weeks of using checkra1n I am certain that it is causing some kexts to appreciable slow down in execution, and some just hang, compared to a device jailbroken with unc0ver or chimera. It appears that the kexts that produce the most kernel log output are the ones affected. Perhaps you guys are monitoring the log and this is slowing things way down?

**Does the issue also occur if you enable Safe Mode?**
haven't tried safe mode

**Any other info, error logs, screenshots, ...?**

BTW I should mention that I love your effort!  It enables me to do _much_ more than I ever would be able to do without it. I thought you would like to know that it does affect kext fuzzing. It may not be noticeable to a user any other way. THANKS

**Comment by Siguza** [comment]
Depending on checkra1n version and flag combination, you might have logging to serial/UART turned on, and that would probably significantly impact performance, and scale with how much logging a kext does...

**Comment by reduritsch** [comment]
I should have mentioned, I'm just using the checkrein.app GUI, with nothing checked

**Comment by reduritsch** [comment]
Other security researchers have seen this post and have reached out. They are also seeing these issues wrt kext fuzzing. Here is a small sample of some hung kexts with selectors:

AppleCredentialManager selector 0
com_apple_driver_FairPlayIOKit selector 3
AppleSSE selector 0
ApplePearlSEPDriver selector 0
IOHDIXController selector 1

**Comment by nullpixel** [comment]
This is likely not a checkra1n issue at all. It is probable that they're being very verbose over UART and Apple's UART driver honestly sucks

**Comment by reduritsch** [comment]
It could be that Apple's UART driver is flawed, but we see these issues with no other jailbreaks, so I'm wondering if there is some kind of interaction that can be avoided.

**Comment by nullpixel** [comment]
those other jailbreaks are fully within userland though and they wouldn't be able to enable UART logging

**Comment by reduritsch** [comment]
I understand your point. Perhaps I'll have to start blacklisting the offending drivers/selectors

**Comment by reduritsch** [comment]
So Siguza saids earlier "you might have logging to serial/UART turned on". I haven't explicitly turned that on. Is there a way to turn it off? I don't see any CLI cmd for that

**Comment by nullpixel** [comment]
Yeah, not sure there is. We could definitely look into that though

**Comment by reduritsch** [comment]
Appreciated!

**Comment by reduritsch** [comment]
checkra1n vrs 0.9.8 seems to have fixed this problem. Thanks to all of you very much. I can fuzz kexts again!

**Comment by nullpixel** [comment]
was definitely apple’s awful UART driver then! :p
