### ISSUE TITLE
Ipad 6 2018 Checkra1n finishes it's thing but terminal commands fail at Killall Backboardd every time

### ISSUE THREAD

**Issue by Coleraine** [checkra1n/BugTracker#702]
**Tell us about your setup:**
1. What iDevice are you using?  Ipad 6 2018 128gb
2. On what version of iOS is it? iOS 13.3
3. What version of checkra1n are you using? GUI or CLI? GUI 0.9.6
4. What is your host system (OS version? Hackintosh? VM? etc.)?  iMac OS 10.13.6 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB A

**What are the steps to reproduce the issue?**
1. Checkra1n does what it is meant to do fine
2. The problem starts right at the last command  killall backboardd
3. Then I press enter but it does not do anything to the Ipad 6, it is still icloud locked
...

**What do you expect, and what is happening instead?**
I expect it to make a noise on my Ipad and icloud lock is gone, what happens and I should see Checkra1n icon on the iPad. Plus the Ipad is none responsive on the language setup screen, power button or home button do not work correctly, I have to restore the Ipad in iTunes. 

**Does the issue also occur if you enable Safe Mode?**
I never have run Checkra1n in safe mode

**Any other info, error logs, screenshots, ...?**
Has anyone had this same problem and was able to get it sorted.
Can anyone help?

**Comment by Siguza** [comment]
We don't support iCloud lock bypass, and it's not our fault if you can't get it right.
