### ISSUE TITLE
setup not skip after bypass on ios 13.3 iphone 7 plus please fix this fast

### ISSUE THREAD

**Issue by fazikamboh** [checkra1n/BugTracker#706]
setup app not skip after jailbreak ios 13.3 iphone 7 plus using icloudbypassca2.4 please fix this fast

**Comment by ozonostudio** [comment]
icloudbypassca it's not part of this, they can't fix it and don't even try to do something about

**Comment by quilenle** [comment]
You can Google to more information that bypassing iCloud was patched on iOS 13.3
