### ISSUE TITLE
ios-kern-utils and checkra1n

### ISSUE THREAD

**Issue by AlexeyGorbushin** [checkra1n/BugTracker#71]
Is it possible to run Siguza's **ios-kern-utils** tool on the device (iPhone8) jailbroken by checkra1n?
I am trying to run the kmap tool but get such output in the log:

./kmap -v
[DEBUG] Getting kernel task... [src/lib/libkern.c:91]
[DEBUG] Trying host_get_special_port(4)... [src/lib/libkern.c:97]
[DEBUG] Returned success, but port is invalid (0x00000000) [src/lib/libkern.c:99]
[DEBUG] Trying task_for_pid(0)... [src/lib/libkern.c:157]
[DEBUG] Success! [src/lib/libkern.c:159]
[DEBUG] Checking if port is restricted... [src/lib/libkern.c:162]
[DEBUG] Failure: task port 0x00001303 is restricted. [src/lib/libkern.c:162]
[DEBUG] Returning failure. [src/lib/libkern.c:166]
[!] Failed to get kernel task ((os/kern) no access, kernel_task = 0)

I found that **mach_ports_lookup()** returns error code 4 which is:

#define KERN_INVALID_ARGUMENT		4
		/* The function requested was not applicable to this
		 * type of argument, or an argument is invalid
		 */

**Comment by nullpixel** [comment]
I forwarded this to @Siguza but basically it should be using task_for_pid 0 now. Anyway, this is not a checkra1n issue so as such I'll close it.
