### ISSUE TITLE
Having problems while connecting via SSH over USB.

### ISSUE THREAD

**Issue by Anulo2** [checkra1n/BugTracker#711]
Device: iPad Air 2 (Wi-Fi)
iOS: 13.3
Checkra1n version: 0.9.7
Device which I'm using to connect to the iPad: HP Probook 450 G6 (Hackintosh Mojave 10.14.6)
The hackintosh works fine and can jailbreak the iPad and everything. The problem is not caused by it.

The problem:
I'm using iproxy as told on the checkrain page to connect to the device.
iproxy 2222 44
After that I open another terminal and try to SSH into my device: ssh root@localhost -p 2222
Unfortunately I get the error: ssh_exchange_identification: read: Connection reset by peer

Meanwhile in the iproxy terminal:

waiting for connection
accepted connection, fd = 4
waiting for connection
Number of available devices == 2
Requesting connecion to device handle == 2 (serial: c**************************************************2), port 44
Error connecting to device!

I've checked the serial and is correct. The device is jailbroken successfully.
I really don't know what could cause this. If anyone has an idea that could help me I would be really grateful.

**Comment by black9404** [comment]
I have the same issue in an Ipad Air 2 while trying to SSH on port 44 ...
I have tried using itunnel_mux_rev71 on Windows and keep getting "Error: Device Service" and also tried using Linux and get the same error as you ...

EDIT: after searching for a while I was able to find that with iPadOS 13.3 you can't use SSH ... I found this on this YouTube video https://www.youtube.com/watch?v=6VOJWR7HX8Q

**Comment by Siguza** [comment]
Could you try:

1. Unlocking your device
2. Running `idevicepair pair` on the host
3. If that opens a popup on the device, tap "Trust"

and see if that fixes the issue?

**Comment by Anulo2** [comment]
That worked perfectly! Thank you! I've also just tried to reinstall Apple File conduit 2 and it solved the problem. Both methods work fine to me.

**Comment by Siguza** [comment]
Sounds like USB restricted mode was the culprit then. Closing this as resolved.
