### ISSUE TITLE
No tweaks work

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#714]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7
2. On what version of iOS is it? 13.3
3. What version of checkra1n are you using? GUI or CLI? GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)? Hackintosh Niresh Mojave 10.14.1
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?) USB-A 

**What are the steps to reproduce the issue?**
1.Install a tweak that isn't an app
2. Respring by clicking Restart Springboard once the tweak is installed
go into settings and try to find the settings for the tweak. There won't be any settings for it and the tweak won't do anything
3.
...

**What do you expect, and what is happening instead?**
There his meant to be settings for the tweak but there isn't and the tweak doesn't work

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by Anulo2** [comment]
Try to re-enable tweaks by running:
rm /var/tmp/.substrated_disable_loader;/etc/rc.d/substrate;killall -9 SpringBoard

**Comment by Siguza** [comment]
That's an issue with the tweak, not checkra1n.
