### ISSUE TITLE
Mohave VM crashing at end of install and shutting computer off.

### ISSUE THREAD

**Issue by lkoehler11** [checkra1n/BugTracker#715]
Trying to JB iPad pro 9.7 (2016) running 13.3. 

My computer is a Lenovo laptop, 8 GB RAM, 512 SSD, Win 10 64 bit, 

What I have done: disabled Secureboot, enabled Intel VM whatever its called, downloaded ra1nstorm "setup.exe" which successfully downloaded, installed, and eventually dual-booted Ubuntu, booted Ubuntu and opened terminal, ran /host/ra1nstorm/ra1nstorm.run as root, clicked install radio button then next, iOS Mohave was downloaded and install completed after following directions to erase VM Partition, then reinstalled iOS Mohave, got to choose language screen, clicked "yes I agree, then install" computer said "installing this will take a long time," timer counted down from 19 minutes or so, and as installer approached 0 mins left, computer shuts off as if someone pulled the plug. So I restart everything, do the entire process above again, bam, same thing. 

Don't know what to do now. Any help would be appreciated. 

Thank you for your time. 

Lance

**Comment by quilenle** [comment]
I think you should go to the ra1nstorm repo to report your issue. Because this isn't a checkra1n issue.

Thank you.

**Comment by Siguza** [comment]
I agree with @quilenle: we're not the authors of ra1nstorm, so we can't offer support for it.

**Comment by lkoehler11** [comment]
Thank you for the reply, I will head to the ra1nstorm repo with this.
