### ISSUE TITLE
iPados 13.2.2

### ISSUE THREAD

**Issue by tariq-192** [checkra1n/BugTracker#72]
**What device + iOS version are you on?**iPados13.2.2

**What are the steps to reproduce the issue?**1
1.
2.
3.
...

**What do you expect, and what is happening instead?** when i open checkra1n loader clicking cydia crash app

**Any other info, error logs, screenshots, ...?**

**Comment by robsee** [comment]
See Issue #2 for the workaround

**Comment by nullpixel** [comment]
Closing as a dupe of #2.
