### ISSUE TITLE
Freezes and goes into a bootloop

### ISSUE THREAD

**Issue by StateOfInstinct** [checkra1n/BugTracker#720]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7
2. On what version of iOS is it? 13.3
3. What version of checkra1n are you using? GUI or CLI? GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)? MacOs Catalina 10.5.2 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A. 3rd party cable

**What are the steps to reproduce the issue?**
N/A
...

**What do you expect, and what is happening instead?**
I expect my device to not to freeze and go into a bootloop. My device will act like I'm not on wifi/cellular so nothing will load or app will freeze. I exit out of app from the app switcher and try to go back in or ill try to respring. My device freezes for a minute or two and goes into a bootloop and reboots

**Does the issue also occur if you enable Safe Mode?**
No

**Any other info, error logs, screenshots, ...?**
This isn't tweak related because I've only had filza and batchomatic installed and this still happened. Sometimes this happens multiple times a day, every couple of days.

**Comment by foxfortmobile** [comment]
Looks like same issue as:
https://github.com/checkra1n/BugTracker/issues/533

**Comment by StateOfInstinct** [comment]
> Looks like same issue as:
> #533

Yeah that’s the ex

**Comment by StateOfInstinct** [comment]
> Looks like same issue as:
> #533

Okay I’ll check it out

**Comment by Siguza** [comment]
I agree that it looks an awful lot like #533, and it should be fixed in the latest substrate update.
