### ISSUE TITLE
Make the checkra1n window always on top.

### ISSUE THREAD

**Issue by megabitsenmzq** [checkra1n/BugTracker#725]
iTunes/Finder will pop up two times during the jailbreak progress. It's very annoying. Can you make the checkra1n window always on top, or bring it to front after finder windows show up? It will make the app experience better.

**Comment by Siguza** [comment]
This issue needs to be addressed, but making the checkra1n window always on top is the wrong approach. We actually have code to SIGSTOP the offending processes, but it seems we need to greatly refine that...

**Comment by k3nnyg** [comment]
I just wanted to add that this may not be a bad idea as an option at least maybe. If I should open a separate issue please let me know, however a problem I had using the GUI (worked around it with CLI) was that I was left with a choice of either having my phone plugged in OR having a working mouse. If I unplugged the phone the mouse would return fully functional. I woild then change the focus back to checkra1n and plug my phone back in thinking I’ll just get around with the keyboard. Problem is, when I plug the phone back in (re-losing my mouse function) I lose focus on checkra1n. The windows key + ~ did not work as a replacement for the command key and I had no way of changing windows without a mouse. CLI wasn’t an issue and that’s how I got it to work finally after some rather comical frustration of back and forth with the GUI and no mouse etc. I should also mention this was using ra1nusb final on a dell inspiron. 

Not that it matters but the laptops installed OS was Ubuntu. It was a great option for me to use ra1nusb. May save ya some porting for Windows and Linux. Other than what I mentioned the new version was a breeze and took NO time at all to get it going. I don’t use nor allow windows on my home network, it works on any system at this point, and at this point I’m happy and don’t have to wait for a native app anymore:)

I realize this is an issue with my platform and not your code. That’s why I didn’t open an issue. I saw this thread and thought I’d put a vote in for this enhancement. Maybe as an option? On ra1nusb there are no other windows or apps to trample on anyways. I agree tho it shouldn’t be forced on real full MacOS machines and it’s in poor taste to code an app like that imho except for good/necessary reasons. 

Thanks again for the jailbreak!

**Comment by k3nnyg** [comment]
Update.....

Just FYI using an external mouse solves it for me. Just the trackpad won’t work. 

Thanks again for all u do for us;)

**Comment by Siguza** [comment]
This issue was fixed some time ago. checkra1n isn't technically "always on top", but it prevents iTunes/Finder from popping up over it while performing the jailbreak.
