### ISSUE TITLE
Ipad 6 2018 ios 13.3 hangs at killall backboardd.

### ISSUE THREAD

**Issue by Coleraine** [checkra1n/BugTracker#729]
Ipad 6 2018 ios 13.3, ipad hangs after input last line in terminal Killall Backboardd. Stuck at language screen with none responsive home button and power button. Ipad needs to be entered into DFU mode to recover and update. Any fix for this?

**Comment by Siguza** [comment]
We don't support iCloud unlocks.

**Comment by Coleraine** [comment]
There are 1000's of iPhones and pads out there that people have forgotten the login details and Apple is not very helpful when you don't have proof of purchase. Why do you not support icloud unlocks?
