### ISSUE TITLE
Swipe up to open doesn't work after using checkra1n

### ISSUE THREAD

**Issue by onecruz** [checkra1n/BugTracker#735]
**Tell us about your setup:**
1. What iDevice are you using?
IPhone X
2. On what version of iOS is it?
13.3
3. What version of checkra1n are you using? GUI or CLI?
0.9.7
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Mac High Sierra 10.13.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-lightning cable

**What are the steps to reproduce the issue?**
1. followed steps on checkra1n
2. rebooted it after jailbreak
3.unable to swipe up after to open 
...

**What do you expect, and what is happening instead?**
I expect it to go onto the main screen but I'm unable to swipe up to access the phone.

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

![Swipe up issue](https://user-images.githubusercontent.com/9735791/72407410-56999200-3714-11ea-8204-ad308c947040.gif)

**Comment by quilenle** [comment]
Did you have bypass iCloud?

**Comment by onecruz** [comment]
Not sure. Can't get passed the swipe up to open screen

**Comment by swptcw** [comment]
I am having the same exact problem with my iPhone X 10,6. I tried the iCloud bypass, but narrowing it down for me the issue starts after the uicache -a step.

it worked great with 0.9.6 and iOS 13.2.3 with no issues.

**Comment by quilenle** [comment]
@swptcw Did you bypass on iOS 13.3? Because this was patched on iOS 13.3.

**Comment by swptcw** [comment]
Not completely, it gives you access to the file system so you can gain access to look around, but the phone becomes useless as the touch screen no longer swipes up. On my phone you can complete all the steps without any errors, but at the "uicache --all" step the digitizer no longer will swipe up. I can get my phone into pwndfu and complete all of the ipwndfu commands including the "-p --boot" "--demote" and "--dump-rom" and the decrypts using command line tools on my macbook, but that is about it. So whatever Apple patched has an affect on the digitizer function so it becomes useless. I can get some of the idevice apps to do somethings as well. But the digitizer kills it.

But I did get the bypass with 13.2.3 before messing around with 13.3. Its an iPhone X my kid found in a parking lot and the police refused to take it and AT&T wanted nothing to do with it. So I have been using it to learn mostly. I dont know if any of that made sense or not, sorry this is my first go round.
