### ISSUE TITLE
iPhone 5s (iOS 12.4.4) Error -31 and Error -20

### ISSUE THREAD

**Issue by zoomer555** [checkra1n/BugTracker#743]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 5s
2. On what version of iOS is it? iOS 12.4.4
3. What version of checkra1n are you using? GUI or CLI? checkra1n 0.9.6 CLI, checkra1n 0.9.6 CLI 
4. What is your host system (OS version? Hackintosh? VM? etc.)? Hackintosh macOS sierra
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? a third party USB-A cable.

**What are the steps to reproduce the issue?**
1.open the cli version of checkra1n 
2. wait until error -31 and 20
3.
...

**What do you expect, and what is happening instead?**
i expect a successful jailbreak, doesn't proceed to code execution (the screen where some code pops up in the phone) and then shows error -31 and error -20 every time.

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Gonna close this as a duplicate of #9. Also please note that hackintoshes are not officially supported, as we can't reliably test them whatsoever.
