### ISSUE TITLE
 Cydia is broken / DPKG is locked

### ISSUE THREAD

**Issue by cmaisno** [checkra1n/BugTracker#744]
**Tell us about your setup:**
1. What iDevice are you using?      Iphone 6s
2. On what version of iOS is it?          13.3
3. What version of checkra1n are you using? GUI or CLI?           0.9.7
4. What is your host system (OS version? Hackintosh? VM? etc.)?    OS High serria
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?      2.0

**What are the steps to reproduce the issue?**
1. open cydia
2. 

1. install any tweak or update
...

**What do you expect, and what is happening instead?**
work as intended

**Does the issue also occur if you enable Safe Mode?**
yes

**Any other info, error logs, screenshots, ...?**

```
" flAbsPath on /var/lib/dpkg/status failed - realpath (2: No such file or directory)"

"Could not open file - open (2: No such file or directory)

"Problem opening"
```

```
"DPKG_LOCKED"

"Could not open file - open (2: No such file or directory)

"Problem opening"
```

SO..

-I reseted/ 'Erase all Content and Settings ' from my phone

-then used a backup from the night before to restore

Now Cydia is broken.

Everytime I load Cydia I get

" flAbsPath on /var/lib/dpkg/status failed - realpath (2: No such file or directory)"

"Could not open file - open (2: No such file or directory)

"Problem opening"

So I click on "return to Cydia"

Wants me to do a whole bunch of upgrades. and I get this error

"DPKG_LOCKED"

"Could not open file - open (2: No such file or directory)

"Problem opening"

**Comment by Siguza** [comment]
You completely nuked your dpkg installation. If you're skilled enough you can fix this manually with SSH access, otherwise just do an IPSW restore and jailbreak fresh.

Also closing this since it's user error rather than a checkra1n issue.

**Comment by cmaisno** [comment]
Was able to ssh thru usb into my iphone and completely erased cydia/jailbreak stuffs
reinstalled jailbreak cydia with no problems now :)

what a headach

**Comment by EasyBoy55** [comment]
> Was able to ssh thru usb into my iphone and completely erased cydia/jailbreak stuffs
> reinstalled jailbreak cydia with no problems now :)
> 
> what a headach

I need the commands that you used after opening ssh to get rid of dpkg locked problem please

**Comment by cmaisno** [comment]
@EasyBoy55 after getting passed ssh i just deleted everything related to jailbreaking.

**Comment by EasyBoy55** [comment]
what is the command that delete everything in cydia
Thank you for replying

**Comment by cmaisno** [comment]
@EasyBoy55 I don't think you should be doing this method if you don't understand what i said.

**Comment by EasyBoy55** [comment]
I understand but how to delete everything related to jailbreak via ssh is their a tutorial for that?

**Comment by EasyBoy55** [comment]
plz replay  😩

**Comment by imkms** [comment]
i need some help too.. please

**Comment by dunderhay** [comment]
A little late to the party but just ran into this issue after trying to "erase all content and settings" on my device (apparently you should not do that from jailbroken phone as it leaves Cydia files lying around - which I noticed that after the device rebooted, everything was removed except Cydia). 

I used the `Restore System` option under troubleshoot in checkra1n and it fully removed all Cydia files. Could then jailbreak again and reinstall Cydia - resolving the issue for me.


![IMG_0001](https://user-images.githubusercontent.com/27876907/145294221-34081df3-50e9-4661-b3df-1ddcedbb097c.PNG)
