### ISSUE TITLE
Substrate Safe Mode deleted cydia not opening

### ISSUE THREAD

**Issue by caferyukseloglu** [checkra1n/BugTracker#745]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 8+
2. On what version of iOS is it?
13.3 Latest
3. What version of checkra1n are you using? GUI or CLI?
checkra1n 0.9.7 beta GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Hackintosh Majove 10.14.5
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A 2.0

**What are the steps to reproduce the issue?**
1. Deleted Substrate Safe Mode
2. Auto Respiring cydia broken
3. Re Jailbreak now cydia not working
...

**What do you expect, and what is happening instead?**
Expecting to find bad tweak instead deleted main cydia tweak now can't get in cydia

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
After JailBreak it was working i installed UnlimApps / Karens AppSync / CCLinker / CoolCC / Control Tweak for CC Respiring Reboot etc. However, today my apps all were crashing so i installed liberty and NoSub still didn't work. I was used this before https://www.reddit.com/r/jailbreak/comments/dwgkzg/tutorial_how_to_fix_tweaks_not_showing_in/ so I deleted Substrate Safe Mode then Cydia crashed now can't Jailbreak after Restore System i have checkra1n install cydia installed but not opening.

**Comment by caferyukseloglu** [comment]
Okey I just fixed via  Termius Apstore app and deleted metadata.cb0 from var/mobile/library/cydia/

**Comment by ferbogajo** [comment]
Hello my friend, could you please tell me how you fixed that? I deleted Substrate Safe Mode by accident and now it won't open anymore. I uninstalled it and installed it again but I won't open. Thank you man.
