### ISSUE TITLE
No jailbreak after updating Cydia Substrate

### ISSUE THREAD

**Issue by jaytj95** [checkra1n/BugTracker#746]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 8+
2. On what version of iOS is it?
13.3
3. What version of checkra1n are you using? GUI or CLI?
checkra1n GUI 0.9.7
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Macbook Pro on OSX 10.14.6 Mojave
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A Apple Cable through a USB-C adapter

**What are the steps to reproduce the issue?**
1. Upgrade Cydia Substrate to latest
2. Reboot/Respring
...

**What do you expect, and what is happening instead?**
I expect to have Cydia functionality (able to open cydia and do things) and have all my tweaks
Instead, I am unable to open Cydia and my tweaks are not loading 

**Does the issue also occur if you enable Safe Mode?**
Either I am always getting kicked into safe mode, or I am unable to get into safe mode. I'm not seeing anything clear that tells me I am in safe mode. 

**Any other info, error logs, screenshots, ...?**
Can't get into localhost via Termius (Connection refused). 
I fixed this before by restoring my phone and losing all my data. Is it possible to fix this without going that route?
I was going along on an old version of Cydia Substrate (downgraded via Cydia) after doing the restore but accidentally updated a bunch of tweaks through Cydia, which unfortunately included Cydia Substrate

Logs upon request (I don't know how to get them)

**Comment by GODLIKE5** [comment]
You might have had a bad tweak that wasn't hooking right, also make sure to try to boot in safemode next time as well as avoiding downgrading/reinstalling essential packages.

**Comment by jaytj95** [comment]
Thanks for your response. Is the only solution here to restore and be more careful (booting into safe mode does nothing -- boots phone as normal) or is there something else I can do?

**Comment by GODLIKE5** [comment]
I’m not sure what’s wrong but If you have not done anything to it yet, try maybe running checkra1n on a different port? also Make sure you’re using an Apple cable and if you manage to get back into your phone try to download bachomatic to create an online backup of your tweaks prefs and repos. So you can restore later. I had this problem before but I managed to remove a recent tweak while on safemode which was causing it to do this. It did not show I was in safemode, also didn’t show the tweaks or exit safemode anywhere. Best choice is if you can open cydia remove the latest installed tweaks or use iCleaner if installed previously to disable all tweaks one by one until the culprit is found.

**Comment by Siguza** [comment]
> **Does the issue also occur if you enable Safe Mode?**
> Either I am always getting kicked into safe mode, or I am unable to get into safe mode. I'm not seeing anything clear that tells me I am in safe mode. 

There's a checkbox in the checkra1n GUI labelled "Safe Mode" - try that.

**Comment by jaytj95** [comment]
> There's a checkbox in the checkra1n GUI labelled "Safe Mode" - try that.



This is how I am trying to enter safe mode, it wasn't doing the trick. 

I resolved my issue by restoring my iPhone (losing all my data/jailbreak tweaks in the process) but would like to see what could be done in a situation like this.

**Comment by GODLIKE5** [comment]
honestly i think this is not checkra1n related. maybe one of your tweaks corrupted causing this, just like my case for example.

**Comment by jaytj95** [comment]
That's fair. I'll go ahead and close this. Thanks for your help!
