### ISSUE TITLE
no notifications

### ISSUE THREAD

**Issue by iphale** [checkra1n/BugTracker#753]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 5s and iPhone 6 
2. On what version of iOS is it? 12.4.4 and 12.4.3
3. What version of checkra1n are you using? GUI or CLI? 0.9.7 (last one)
4. What is your host system (OS version? Hackintosh? VM? etc.)? hackintosh
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? usb c with apple cable

**What are the steps to reproduce the issue?**
1. open chekra1n jailbreak on iMac and jailbreak the I device
2. iCloud bypassed the idevice
3. using the idevice without any tweak
...

**What do you expect, and what is happening instead?**
receive app notification but I don't receive any 

**Does the issue also occur if you enable Safe Mode?** yes

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
That's because the device is not activated. iCloud bypass isn't supported and never will be.
