### ISSUE TITLE
jailbreak fail if trigger one hour iOS usb restricted mode

### ISSUE THREAD

**Issue by genknife** [checkra1n/BugTracker#755]
1.Let the phone into recovery mode.
2.Open the checkra1n app, and follow the instructions to put your device into DFU mode.
Jailbreak fail when boot complete and run into lock screen.
I think because I have not unlock the phone before let the phone into recovery mode and trigger one hour iOS usb restricted mode. Recovery/DFU mode does not check this restrict, only when in iOS system.
So I want to ask whether I can bypass this iOS usb restricted mode or not.
If iOS usb restricted mode check in SEP, then it is impossilbe. But if it check in kernel/kext or user space,  then it is always possible.
Thank you very much!

**Comment by Siguza** [comment]
Once the device boots to the lock screen, you can just unlock it and the jailbreak should continue uploading bootstrap. This should work even if you got a timeout in the checkra1n GUI, as long as the device is still attached.

**Comment by genknife** [comment]
thx
