### ISSUE TITLE
iphone 8 stuck apple boot logo

### ISSUE THREAD

**Issue by parazyt75** [checkra1n/BugTracker#769]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using? GUI or CLI?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by parazyt75** [comment]
iphone 8
ios 12.4.1
checkra1n 0.9.7 GUI
macbookpro 10.13.6 or 10.14.6
connectiong with apple usb-A cable directly to the macbook

jailbreaked with checkra1n --> OK
Installed few tweaks that i had on my iphone SE 12.4 (unc0ver)
Restored prefs from BackupAZ3

After theat, my ask me to reboot --> now iphone stuck at boot logo
If I run checkra1n, it stay at bootlog & then iphone restart itself i stuck at apple boot logo.

When I run checkra1n with verbose boot it stop at kSMCNotifyExternalPowerChange: .....

When I run checkra1n with safemode enable it stop at 
KPF: Disabled snapshot temporarily
adding mapping... done!

Main window of checkra1n tell me that. 

Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)
Booting

SSH Method doesn't work too

any ideas ? I really would like to stay on ios 12

Thanks for your help


![IMG_4657](https://user-images.githubusercontent.com/37327130/73609443-f8065c00-45cd-11ea-9829-3a3f9f30e4ea.JPG)
![IMG_4658](https://user-images.githubusercontent.com/37327130/73609444-f8065c00-45cd-11ea-8640-82e6776cc005.JPG)
![IMG_4660](https://user-images.githubusercontent.com/37327130/73609479-63502e00-45ce-11ea-98c5-6526787604cf.JPG)
<img width="584" alt="checkra1n -s -v" src="https://user-images.githubusercontent.com/37327130/73610377-c1810f00-45d6-11ea-837d-178be17e00c5.png">

**Comment by Siguza** [comment]
So when you enable safe mode, it just sits there doing nothing, but doesn't reboot?  
Can you try what happens if you enable both safe mode and verbose boot?

**Comment by parazyt75** [comment]
Hi Siguza 
When i try to jb with both verbose & safemode enabled it do the same as you can see i the 2nd screenshot (the one without apple).

**Comment by Siguza** [comment]
Hm, weird. I see the checkra1n userland payload running, but I guess the rest of userland never comes up. This is debuggable in theory, but you'd pretty much have to run off an entirely custom ramdisk... but it seems like whatever you installed messed with the files on disk and broke something.

**Comment by parazyt75** [comment]
Thank for those explanations. 
I really don't know who to run off an entire custom ramdisk.
If is there no way for me to stay on ios 12.4.1, I think I'm going to upgrade to 13.3 while is signed.

**Comment by parazyt75** [comment]
I saw that you just post a new version of checkra1n : 0.9.8
Do you think that could help me ?

**Comment by Siguza** [comment]
I suppose once we release the toolkit to interface with pongoOS, you could build something that lets you mount & modify the partitions on disk, but... you'd still have to debug the issue yourself. :/

**Comment by parazyt75** [comment]
Well, i've jumped to 13.3 this morning.
Many thanks for taking a look at my case.
Thank to you and to all the team for your great work for keeping alive jailbreak community.
Cheers

**Comment by parazyt75** [comment]
I close the case
Thanks
