### ISSUE TITLE
CAN"T ENTER SAFE MODE!!!

### ISSUE THREAD

**Issue by bumbie** [checkra1n/BugTracker#772]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 8+
2. On what version of iOS is it?
13.3.1
3. What version of checkra1n are you using? GUI or CLI?
0.9.7
4. What is your host system (OS version? Hackintosh? VM? etc.)?
10.15.3
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-C hub
**What are the steps to reproduce the issue?**
1. I have a PowerSelector from ichitaso and use it for some operation
2. everything seem fine except SAFE MODE
3. I pressed Safe Mode and it doesn't enter and it return to normal mode. 
...

**What do you expect, and what is happening instead?**
when press "Safe Mode" the screen turn black with respring icon and it return to normal mode. No sign of safe mode

**Does the issue also occur if you enable Safe Mode?**
safe mode broken

**Any other info, error logs, screenshots, ...?**
list of tweak

7-zip (POSIX): 16.02-1
Adguard Unbounded: 0.0.1.1
AppList: 1.5.15~beta1
Apps Manager: 1.4.2
AppStore++: 0.9.7
AppSync Unified: 70.0
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 0.7 Transitional (apt-key): 1:0
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
AudioRecorder XS (iOS 12/13) Cracked: 3.2-27
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
BlockEmAll: 0.0.2.2
Bourne-Again SHell: 5.0.3-2
Bright - English Hack: 0.0.2
bzip2: 1.0.6-1
CA Certs: 0.0.2
CacheClearer (iOS 11): 0.1a
CCSupport: 1.2.2
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cydia Installer: 1.1.32~b23
Cydia Substrate: 0.9.7100
Cydia Translations: 1.1.32~b1
CyDown: 7.0.6
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
ExactTimeMessages: 1.0
ExactTimePhone: 1.0-1+debug
Ext3nder Installer: 022b
file: 5.35-2
Filza File Manager: 3.7.2
Find Utilities: 4.6.0-2
Flame: 1.3
Flex 3 Beta: 1:3~Beta86
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
iCleaner Pro: 7.8.0
Immortal: 1.2.1-1
iOS Firmware: 13.3.1
ipadify: 0.0.1
iPhone Firmware (/sbin): 0-1
JailProtect: 0.0~beta4a
KarenLocalizer: 1.0.5
KarenPrefs: 1.5
Keyboard Accio: 2.3.5
Kiiimo Repo Icons: 12.6
KSBA: 1.3.5-1
Launch Daemon Controller: 23-1
LetMeBlock: 0.0.7.1
libcolorpicker: 1.6.7
libidn2: 6.1.2-1
libplist: 2.0.0-2
libtasn1: 4.13-1
libunistring: 0.9.10-1
LINE Switcher: 0.1-9
Link Identity Editor: 2:2.1.2+24497ae-1
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Mega UHB IPv4+6 - iOS 9/10/11/12 - MUHB IPv4+6 (Mega Untrusted Hosts Blocker IPv4 and IPv6): 2.1.1
Messenger+: 1.3.4-2
mikoto: 4.0.3
My IAP CRACKER 2: 0.0.4
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1+20181013-1
New GNU Portable Threads: 1.6-1
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
Pasithea 2 (iOS 10 to 13) Cracked: 2.2.1
plutil: 0.2.1
PowerSelector (iOS 11 to 13): 1.2.6
PreferenceLoader: 2.2.4~beta1
Profile Directory: 0-1
readline: 8.0-1
Rocket for Instagram Cracked: 3.6.9
RocketBootstrap: 1.0.7~beta3
sed: 4.5-1
shell-cmds: 118-8
Snappy: 1.3.0
StoreSwitcher 2: 1.0.0
Substrate Safe Mode: 0.9.6003
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
UHB - iOS 9/10/11/12 (Untrusted Hosts Blocker): 1.7.1
UIKit Tools: 1.1.15-2
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
wget: 1.19.5-2
XZ Utils: 5.2.4-4
zip: 2.32-1

**Comment by Siguza** [comment]
That's not checkra1n's fault.  
Checkra1n has its own Safe Mode, which you can activate by ticking a checkbox in the GUI.
