### ISSUE TITLE
Checkra1n install succeeds without error code but installing cydia crashes.

### ISSUE THREAD

**Issue by tungnnt** [checkra1n/BugTracker#775]
**Tell us about your setup:**
1. I use iphone 7 global
2. I am on ios 13,3
3. I am using the lastest version of checkra1n via GUI
4. I install the software in my hackintosh system
5. I connect via USB 2.0 and 3.0 port

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**
The checkra1n was installed successfully, when i install cydia, it says that: downloading,,, installing ,,, then it crashes, i can access cydia

**Does the issue also occur if you enable Safe Mode?**
The thing happens again when i tick safemode button in the GUI

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Does the _checkra1n app_ crash when attempting to install Cydia, or does _Cydia itself_ crash?

**Comment by tungnnt** [comment]
> Does the _checkra1n app_ crash when attempting to install Cydia, or does _Cydia itself_ crash?

Checkra1n app says that installing cydia, after a moment, checkra1n exits, like pressing home button, it not like crashing, when i press cydia app, it crashes

**Comment by Siguza** [comment]
Could you try connecting via SSH (port 44) and running this command:

    rm /var/mobile/Library/Cydia/metadata.cb0

Then try to open Cydia again.

**Comment by tungnnt** [comment]
> rm /var/mobile/Library/Cydia/metadat

I try ssh root@my_iphone_ip -p 44 but connection refused

**Comment by Siguza** [comment]
It only works via iproxy/localhost.

**Comment by tungnnt** [comment]
> It only works via iproxy/localhost.

I tried ssh my iphone via usb without wifi and it worked. Thank a lot for your support.

**Comment by Siguza** [comment]
Aight, then this was a dupe of #60.
