### ISSUE TITLE
Linux: Checkra1n: libirecovery.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 0n1cOn3** [checkra1n/BugTracker#776]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using? GUI or CLI?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. Installed as given steps on the checkra1n Website
2. Error eccoured when start checkra1n under Debian
3.
...

**What do you expect, and what is happening instead?**
Library Issue

**Does the issue also occur if you enable Safe Mode?**
Not depended

**Any other info, error logs, screenshots, ...?**

debian@debian:~$ echo "deb https://assets.checkra.in/debian /" | sudo tee -a /etc/apt/sources.list
deb https://assets.checkra.in/debian /
debian@debian:~$ sudo apt update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease                      
Get:3 https://assets.checkra.in/debian  InRelease [1,359 B]              
Get:4 https://assets.checkra.in/debian  Packages [2,458 B]
Fetched 3,817 B in 1s (5,088 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
24 packages can be upgraded. Run 'apt list --upgradable' to see them.
debian@debian:~$ sudo apt install checkra1n
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libirecovery3 libplist3 libusbmuxd6
The following NEW packages will be installed:
  checkra1n libirecovery3 libusbmuxd6
The following packages will be upgraded:
  libplist3
1 upgraded, 3 newly installed, 0 to remove and 23 not upgraded.
Need to get 11.0 MB of archives.
After this operation, 19.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://assets.checkra.in/debian  libplist3 2.1.0-0build1 [32.6 kB]
Get:2 https://assets.checkra.in/debian  libusbmuxd6 2.0.2-1 [17.5 kB]
Get:3 https://assets.checkra.in/debian  libirecovery3 1.0.0-1 [17.6 kB]
Get:4 https://assets.checkra.in/debian  checkra1n 0.9.8-1 [10.9 MB]
Fetched 11.0 MB in 3s (3,916 kB/s)    
(Reading database ... 190745 files and directories currently installed.)
Preparing to unpack .../libplist3_2.1.0-0build1_amd64.deb ...
Unpacking libplist3:amd64 (2.1.0-0build1) over (2.0.1~git20190104.3f96731-1) ...
Selecting previously unselected package libusbmuxd6:amd64.
Preparing to unpack .../libusbmuxd6_2.0.2-1_amd64.deb ...
Unpacking libusbmuxd6:amd64 (2.0.2-1) ...
Selecting previously unselected package libirecovery3:amd64.
Preparing to unpack .../libirecovery3_1.0.0-1_amd64.deb ...
Unpacking libirecovery3:amd64 (1.0.0-1) ...
Selecting previously unselected package checkra1n.
Preparing to unpack .../checkra1n_0.9.8-1_amd64.deb ...
Unpacking checkra1n (0.9.8-1) ...
Setting up libplist3:amd64 (2.1.0-0build1) ...
Setting up libusbmuxd6:amd64 (2.0.2-1) ...
Setting up libirecovery3:amd64 (1.0.0-1) ...
Setting up checkra1n (0.9.8-1) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.28-10) ...
debian@debian:~$ checkra1n 
checkra1n: error while loading shared libraries: libirecovery.so.2: cannot open shared object file: No such file or directory
debian@debian:~$ uname -a
Linux debian 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
debian@debian:~$

**Comment by sferia82** [comment]
same error with ubuntu.

**Comment by UnitTHK** [comment]
Uninstall and reinstall
the dev messed up the dependency. It should be fixed now

**Comment by woachk** [comment]
Fixed.
