### ISSUE TITLE
Checkra1n stuck at checking device

### ISSUE THREAD

**Issue by Mr-Bobby** [checkra1n/BugTracker#778]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 7 plus
2. On what version of iOS is it?
13.3
3. What version of checkra1n are you using? GUI or CLI?
CLI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
XUbuntu Linux 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple cable into usb-a on back of pc

**What are the steps to reproduce the issue?**
1. Installed Checkra1n cli for Linux x86
2. Run as root in terminal
3. Turn on boot in safe mode
4. Follow steps for jailbreak exactly
...

**What do you expect, and what is happening instead?**
For it to work but keeps getting stuck at the “checking if device is ready” (1st stage), if I run Checkra1n again in another terminal window it gets to the “Right before trigger (this is the real big setup)” (3rd stage) but then gets stuck there again and won’t go further

**Does the issue also occur if you enable Safe Mode?**
Been doing it only in safe mode as was having problems when was last jailbroken in earlier version but think was due to a incompatible tweak. 

**Any other info, error logs, screenshots, ...?**

**Comment by Mr-Bobby** [comment]
Don’t know if this is important, but on second terminal window it says “failed to get string descriptive: LIBUSB_ERROR_TIMEOUT

**Comment by kotschy** [comment]
You have to disable your Passcode and sign out from your ICloud.

**Comment by Mr-Bobby** [comment]
That didn’t work. 
When I ran it with the -c command it said USBMUX Error (error code: -79)

**Comment by Siguza** [comment]
@kotschy no you don't. All you have to do is enter your passcode on boot to avoid the timeout message, but even if you don't, you can still unlock the device later and it should still upload bootstrap, as long as your device is still connected.

**Comment by truff1ep1g** [comment]
Try this i was stuck trying all this other crap 3 days myself.  This worked first try 4 separate devices different combo of cables and ports. All on 13.3 from iPhone 7, 8+, X, iPad air2 https://github.com/foxlet/bootra1n/blob/master/README.md

**Comment by Mr-Bobby** [comment]
Fixed it, input this command “ sudo apt install ideviceinstaller python-imobiledevice libimobiledevice-utils python-plist ifuse usbmuxd libusbmuxd-tools ” into terminal and swapped usb ports and seems to be working, dunno which fixed it just glad it’s working now, thanks for the help.
