### ISSUE TITLE
"Error - Missing device layout?!" 

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#78]
iPad Mini 2 on iOS 12.4.3 has an error after entering DFU mode. 

"Error - Missing device layout?!" 

checkra1n then proceeds by closing itself and the device remains in DFU mode

**Comment by nielsfranke** [comment]
I have the same error on the iPad Mini2 with iOS 12.4.2.

<img width="481" alt="error message" src="https://user-images.githubusercontent.com/4923534/68548607-10137880-03ef-11ea-992b-f0a39734c2fd.png">

**Comment by woachk** [comment]
This issue has been fixed in 0.9.1.

Please re-download from https://checkra.in.
