### ISSUE TITLE
stuck at re-jailbreaking after intstalling HomeGesture tweak

### ISSUE THREAD

**Issue by zidanmahmoud** [checkra1n/BugTracker#787]
Very similar to #215 after intstalling HomeGesture tweak

**Tell us about your setup:**
1. What iDevice are you using?
iPhone 7

2. On what version of iOS is it?
13.2.3

3. What version of checkra1n are you using? GUI or CLI?
0.9.8 GUI

4. What is your host system (OS version? Hackintosh? VM? etc.)?
ubuntu ... using `sudo checkra1n -g`

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A

**What are the steps to reproduce the issue?**
1. Jailbreak device
2. Install HomeGesture tweak ... stuck in respring until automatically reboots unjailbroken
3. try to re-jailbreak and it gets stuck at *Entering download mode*
...

**What do you expect, and what is happening instead?**
I think the tweak is the issue. I am not sure how to remove the tweak without going into a jailbroken state.

**Does the issue also occur if you enable Safe Mode?**
Can I go into safe mode? I tried holding the volume up while jailbreaking and it did not do anything. Sorry for being naive.

**Any other info, error logs, screenshots, ...?**
`USBMUX Error (Error code: -79)` after forcing shutdown while stuck at *Entering download mode*

**Comment by Siguza** [comment]
Use checkra1n with the `-s` flag to enter safe mode.

**Comment by zidanmahmoud** [comment]
It worked. Thanks for the quick reply!!

**Comment by Siguza** [comment]
Sure, np.

**Comment by boierito** [comment]
I have the same issue, please help. I restored all my jailbreak data and then I installed a couple of tweaks and when I re-jailbreak my iPhone X, checkra1n gave me the 20 error

**Comment by Siguza** [comment]
Well go into Safe Mode.

**Comment by zidanmahmoud** [comment]
> I have the same issue, please help. I restored all my jailbreak data and then I installed a couple of tweaks and when I re-jailbreak my iPhone X, checkra1n gave me the 20 error

As @Siguza said, I used `sudo checkra1n -s`, followed the steps, gained access to cydia, removed the tweak, then did a re-jailbreak normally.

**Comment by boierito** [comment]
iOS 13.3.1 iPhone X checkra1n 0.9.8 macOS Catalina

Yeah, I know about safe mode, but... The tweaks that I have installed, I have them installed weeks ago and I could always jailbreak after the iPhone turned off, I would not be understanding why now it fails.

I understand that the error is not because of the tweaks, but it may be the version of checkra1n

**Comment by boierito** [comment]
> Yeah, I know about safe mode, but... The tweaks that I have installed, I have them installed weeks ago and I could always jailbreak after the iPhone turned off, I would not be understanding why now it fails.
> 
> I understand that the error is not because of the tweaks, but it may be the version of checkra1n


I have fully updated tweaks for iOS 13 installed, such as PauseOnMute, Temporary Background Spawn, SuperLPM, System Info and Jumpskip. Those are all I have and still fail.
