### ISSUE TITLE
0.9.8版本问题很大，

### ISSUE THREAD

**Issue by iPhoneX-liuchao** [checkra1n/BugTracker#788]
我之前用0.9.7越狱后发现更新了最新的0.9.8版本我就重启后用最新版的0.9.8越狱，一切顺利结果提示错误-20，我勾选了安全模式成功了，可惜插件死活不显示在设置内，最后我清除了越狱环境卸载删除一切后用0.9.8版本不选安全模式越狱成功后开始安装插件，安装后重启再一次越狱不勾选安全模式是不能越狱，最后勾选安全模式越狱成功插件还是不显示，最后我没有办法我只能用0.9.7越狱不勾选安全模式一步到位成功越狱，之前安装的插件都显示在设置里，
这说明0.9.8越狱工具还是存在问题，求作者修复谢谢。

**Comment by Siguza** [comment]
I feel like this is a duplicate of your other ticket, #789. If I'm wrong, please reply here.
