### ISSUE TITLE
-92 error by re-jb iDevice, Checkra1n app disappears after reboot iDevice

### ISSUE THREAD

**Issue by CrafterPika** [checkra1n/BugTracker#792]
This is related to Linux checkra1n btw!

1. issue:
i Jailbroke my device with checkra1n and after a reboot the checkra1n app is gone.... it appears again if i re-jb the device...

2. issue
every time if i re-jb the device it shows me error -92 (i use ManjaroLinux btw) the the jailbreak is successfully completed

![Screenshot_20200205_225448](https://user-images.githubusercontent.com/48294025/73882318-1dab9380-4862-11ea-8f0d-97ea93307418.png)

**Comment by ZenIsBestWolf** [comment]
Experiencing same issue on Manjaro, but I believe the app is supposed to disappear after a reboot. Regardless the jailbreak still works even though this error pops up.

**Comment by CrafterPika** [comment]
Ik that by error -92 the jb successful was, but I’m not sure if the checkra1n app is supposed to disappear after reboot, cause on older versions it was different...

**Comment by Siguza** [comment]
The checkra1n app _is_ supposed to disappear on unjailbroken boots, it's just possible that the icon cache doesn't get updated - but the app itself is never written to disk, and never was.

**Comment by CrafterPika** [comment]
ah thanks, good to know
