### ISSUE TITLE
error check_snapshot_error_code:General

### ISSUE THREAD

**Issue by fnprog** [checkra1n/BugTracker#796]
**Tell us about your setup:**
1. What iDevice are you using?
  Iphone 7

2. On what version of iOS is it? 
ios 13.3

3. What version of checkra1n are you using? GUI or CLI?
 checkra1n 0.9.8 Gui

4. What is your host system (OS version? Hackintosh? VM? etc.)?
Linux Mint 19.3 

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Stock apple cable

**What are the steps to reproduce the issue?**
1. jailbreak iphone
2. enter loader
3.install cydia
...

**What do you expect, and what is happening instead?**
cydia installation succes

**Does the issue also occur if you enable Safe Mode?**
yes

**Any other info, error logs, screenshots, ...?**

**Comment by adem0909** [comment]
Which iDevice do you use?
Ipad Pro 9.7

Which iOS version is it on?
ios 13.3.1

Which version of checkra1n are you using?
CLI x86_64 checkra1n 0.9.8

What is your host system
Ubuntu 18.4

How to connect to the device USB

What are the steps to reproduce the problem?

Jailbreak iPad

Enter loader 3.install cydia
...
Cydia installation


check_snapshot_error_code: General

**Comment by woachk** [comment]
You have a pre-staged iOS update. Please either remove it or upgrade to the newest iOS before jailbreaking.

**Comment by adem0909** [comment]
First of all, Thank you for the comment
what I did not understand
where can I find it pre-deployed iOS update.

installed the latest iOS 13.3.1 via itunes
I have to install other ios.

**Comment by maoex** [comment]
I have with my iphone 7 Plus and ios 13.2.3 the same problem, so i cannot install any of the repos. Cydia shows only alredy installed, reinstall. Thats all. 
But i need to mention that i made after checkra1n Jailbreak an icloud unlock by shiftkey on Windows. Others like tweakbox dont want install also, others like unc0ver not supported yet.
But i diddnt face any other issues with facetime or app center.
Without Cydia it seems to me i cannot use it. 
Sileo and Chimera i also have trouble.

**Comment by fnprog** [comment]
did anyone found a solution

**Comment by fnprog** [comment]
> You have a pre-staged iOS update. Please either remove it or upgrade to the newest iOS before jailbreaking.

how can i install no pre-staged update ?

**Comment by anoma-yt** [comment]
Tengo el mismo problema, y aun no he encontrado nada, he probado con varias versiones de IOS y nada. Si alguien tiene la solución y la da, seria de muy gran ayuda. Muchas Gracias.

**Comment by xuefer** [comment]
are you using icloud by pass utility?

this happens when loader is installed by icloudbypass utility instead of by checkra1n

**Comment by iHad169** [comment]
Tell us about your setup:
What iDevice are you using?
Iphone X

On what version of iOS is it?
ios 13.3.1

What version of checkra1n are you using? GUI or CLI?
checkra1n 0.9.8

What is your host system (OS version? Hackintosh? VM? etc.)?
Linux Mint 19.3

How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Lighting USB Cable

What are the steps to reproduce the issue?
jailbreak iphone
enter loader
install cydia
...

What do you expect, and what is happening instead?
cydia installation succes

Does the issue also occur if you enable Safe Mode?
yes

Any other info, error logs, screenshots, ...?
![Img](https://user-images.githubusercontent.com/27337315/75456840-04f05280-59b6-11ea-9787-08b2dd1fa8a6.jpg)

**Comment by provanzza** [comment]
What iDevice are you using?
Iphone X

On what version of iOS is it?
ios 13.3.1

What version of checkra1n are you using? GUI or CLI?
checkra1n 0.9.8
checkra1n 0.9.8.1
checkra1n 0.9.8.2

same error.. 


What is your host system (OS version? Hackintosh? VM? etc.)?
Debian unstable - Linux 5.4
via
https://asineth.gq/checkn1x/

How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Lighting USB Cable

What are the steps to reproduce the issue?
jailbreak iphone
enter loader
install cydia
...

What do you expect, and what is happening instead?
cydia installation succes

p.s. rumors says, on Iphone X only work v0.9.7 and v0.9.2, but only available for macOS, no Linux or Windows ..

**Comment by MRblackDZ** [comment]
Anyone find solutions please

**Comment by lucascantos** [comment]
Tell us about your setup:

What iDevice are you using?
iPad Air 2
On what version of iOS is it?
iOS 13.3 and iOS 13.3.1
What version of checkra1n are you using? GUI or CLI?
Checkra1n 0.9.8.2
What is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu
How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple Cable
What are the steps to reproduce the issue?
>Jailbreak
>Go to the CheckRa1n app
>Install Cydia
error check_snapshot_error_code:Genera

Does the issue also occur if you enable Safe Mode?
Yes

**Comment by MhmdAMiNE** [comment]
> 
> 
> are you using icloud by pass utility?
> 
> this happens when loader is installed by icloudbypass utility instead of by checkra1n

This worked for me, Thanks :)
I rejailbreaked my iPhone with checkra1n and it worked

**Comment by kenkit** [comment]
I think it happens when jailbreak does not complete uploading resources

**Comment by maoex** [comment]
Since The last 3 Checkra1n/iOS updates after reboot when jailbreaking „All done“ I not have a checkra1n App anymore. The first time it was gone after resorting, since then ,with iOS 14.0 no checkra1n to fix something.Gor Cydia I don’t need that, installed already and I JB again only after problems like a Loop. So I cannot use the app to fix ,someone mentioned me that before.maybe like an root fs. If I wrote that before then Sorry,some time ago.

**Comment by DimplyKitten824** [comment]
> are you using icloud by pass utility?
> 
> this happens when loader is installed by icloudbypass utility instead of by checkra1n

How do I stop the icloudbypass from installing the loader?
