### ISSUE TITLE
Re-Jailbreak isnt working

### ISSUE THREAD

**Issue by chiragvshroff** [checkra1n/BugTracker#808]
i have a iphone 7 ios 13.3 im not able to jailbtreak it again it goes to a bootloop when i try to jail break

**Comment by hrz0x** [comment]
same here

**Comment by JosefWaida** [comment]
You have to reflash 13.3 (or simply ota to 13.3.1 - that is supported as well)

**Comment by hrz0x** [comment]
> You have to reflash 13.3 (or simply ota to 13.3.1 - that is supported as well)

Why? Is it necessary? Is it a bug that can be fixed later?

**Comment by thekio1984** [comment]
try jailbreaking in safe mode & delete any possible conflicting tweaks..thats my only suggestion, & with it supporting currently signed ios, does it really matter if you need to dfu restore?!?

**Comment by truff1ep1g** [comment]
Try this i was stuck trying all this other crap 3 days myself. This worked first try 4 separate devices different combo of cables and ports. All on 13.3 from iPhone 7, 8+, X, iPad air2 https://github.com/foxlet/bootra1n/blob/master/README.md
