### ISSUE TITLE
iPhone 7 stuck on 'Checking if device is ready'

### ISSUE THREAD

**Issue by m3rtngs** [checkra1n/BugTracker#81]
**What device + iOS version are you on?**
iPhone 7, iOS 13.2.2

**What are the steps to reproduce the issue?**
1. Boot into recovery
2. Boot into DFU
3. Checkra1n application on Hackintosh begins 'Checking if device is ready'
...

**What do you expect, and what is happening instead?**
Expecting to move onto the next steps, however it has been stuck on 'Checking if device is ready' for a while now.

**Any other info, error logs, screenshots, ...?**
Should be noted that my device is affected by a problem known as 'Audio IC Disease' where my devices microphone is broken.

**Comment by littlelailo** [comment]
Which macos version? I suspect that another process on the system is trying to access the device and that's causing issues. If itunes starts to pop up, kill it before continuing

**Comment by m3rtngs** [comment]
I am using a hackintosh running High Sierra.

**Comment by nullpixel** [comment]
Hackintoshes aren’t a supported configuration due to the multitude of things which could go wrong

**Comment by m3rtngs** [comment]
Alright I understand, thanks guys.

**Comment by littlelailo** [comment]
This could still be related to the stuff I described here: https://github.com/checkra1n/BugTracker/issues/27#issuecomment-552446326
But I'll close this here, because either the comment resolves it for you or it's just because you got a Hackintosh, sry.
