### ISSUE TITLE
Won't enter PongoOS

### ISSUE THREAD

**Issue by sebastianpc** [checkra1n/BugTracker#813]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 6
2. On what version of iOS is it? 12.4.4
3. What version of checkra1n are you using? GUI or CLI? 0.9.8 linux, GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)? Ubuntu 19.04
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A, Original cable

**What are the steps to reproduce the issue?**
1. sudo checkra1n -p
2. go through standard procedure to jailbreak
...

**What do you expect, and what is happening instead?**
I expect to enter PongoOS
I'm seeing PongoOS for a short amount of time and then it boots normally

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
No

**Comment by Siguza** [comment]
Just for clarification, the device reboots into unjailbroken mode, right?

**Comment by sebastianpc** [comment]
Yep

**Comment by Siguza** [comment]
Alright, I'm able to reproduce this on an iPad Pro 2nd gen, 12.3.1. Marking the issue as accepted.

**Comment by Siguza** [comment]
This should have been fixed in checkra1n 0.12.0, perhaps even before that.
