### ISSUE TITLE
After deleting the jailbreak iphone will not activate and set up apple ID

### ISSUE THREAD

**Issue by xmrus** [checkra1n/BugTracker#815]
My phone (iPhone 6s) after deleting the jailbreak files in the checkra1n app won't let me log into icloud. I updated it by mistake and then restored it back to ios 13.3. Now when I log into icloud it gets stuck on: It may take a few minutes to set up your apple ID... it has been like that for 40 minutes. I jailbroke it with checkra1n 0.9.8 beta for Linux on Ubuntu 18.04.

**Comment by fuomag9** [comment]
Did you do a DFU restore or a normal one?

**Comment by xmrus** [comment]
Through iTunes so I guess a normal one

**Comment by fuomag9** [comment]
Try to restore again while in [dfu mode](https://help.ifixit.com/article/108-dfu-restore)

**Comment by woachk** [comment]
Hello,

Did you try to login on a boot without checkra1n enabled?
Which device do you use? And which steps did you follow?

**Comment by xmrus** [comment]
I restored again now in dfu mode and it worked now it's logged in and works just how it should.
