### ISSUE TITLE
Shell script will be killed.

### ISSUE THREAD

**Issue by Halo-Michael** [checkra1n/BugTracker#82]
**What device + iOS version are you on?**
iPhone7 iOS13.2.2

**What are the steps to reproduce the issue?**
1.
![IMG_0944](https://user-images.githubusercontent.com/45062120/68547927-90070600-0422-11ea-86b0-c934e9bfcaf7.png)

**What do you expect, and what is happening instead?**
It shouldn't happen

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Shell scripts cannot be in var and must be on the rootfs.
