### ISSUE TITLE
Start button greyed out

### ISSUE THREAD

**Issue by rcpag1103** [checkra1n/BugTracker#824]
**Tell us about your setup:**
1. What iDevice are you using? ipad 10.2 7th gen
2. On what version of iOS is it? 13.3.1
3. What version of checkra1n are you using? GUI or CLI? 0.9.8
4. What is your host system (OS version? Hackintosh? VM? etc.)? MacOS 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-C, Apple and 3rd party cable, USB C hub

**What are the steps to reproduce the issue?**
1. in previous version, 0.9.7 was able to jailbreak via terminal
2. device already in dfu mode then run the terminal and device will be jailbroken
3. in 0.9.8, start button is greyed out after running the command via terminal which works in 0.9.7
...

**What do you expect, and what is happening instead?** should work the same as 0.9.7

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
So your issue boils down to "you start in DFU and the GUI won't work with that, so you use the CLI but 0.9.8 has a GUI on the command line as well"?  
In that case, I think you might just be looking for the `-c` flag...

**Comment by rcpag1103** [comment]
That fixes the issue. Thank you!!! Hope to experience again a 40+days uptime
