### ISSUE TITLE
fix usb error (error codo -77) checkra1n 

### ISSUE THREAD

**Issue by mostafaadel0** [checkra1n/BugTracker#836]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using? GUI or CLI?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by fuomag9** [comment]
@mostafaadel0 You're supposed to write what you did, the devs are very aware of that error

**Comment by truff1ep1g** [comment]
Try this please. It works   I’ve tried all else too. https://github.com/foxlet/bootra1n/blob/master/README.md

**Comment by mostafaadel0** [comment]
https://youtu.be/TL__898sZHA
Thx all that my video 

I searched and found the solution here and made a video for my benefit
