### ISSUE TITLE
USB error (error code -77)on Ubuntu 16.04

### ISSUE THREAD

**Issue by Agape2077** [checkra1n/BugTracker#837]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 6s Plus 
2. On what version of iOS is it?
iOS 13.3.1
3. What version of checkra1n are you using? GUI or CLI?
Linux CLI 0.9.8 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu 16.04.5 x86_64 liveCD
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
connect to machine via 3rd party cable

**What are the steps to reproduce the issue?**

1. After entered dfu mode and when phone got reboot
2.it shows Entered download mode before error happends
3.verbose boot works fine but still get a error code.
**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**
I don’t know...Will try it 

**Any other info, error logs, screenshots, ...?**
Sorry I Don't know where i can get log file....

**Comment by Agape2077** [comment]
Update:When I plug the cable off and plug in after phone booted ,it told me done.....

**Comment by truff1ep1g** [comment]
Try this https://github.com/foxlet/bootra1n/blob/master/README.md
