### ISSUE TITLE
Error -94

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#839]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7
2. On what version of iOS is it? iOS 13.2.3
3. What version of checkra1n are you using? GUI or CLI? CLI
4. What is your host system (OS version? Hackintosh? VM? etc.)? Slax Debian using pendrive
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? 3rd party cable

**What are the steps to reproduce the issue?**
1. Connect device
2. DFU works
3. works everything until error appears almost finishing. usbmux error -94. usbmuxd is installed.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**
Didn’t try

**Any other info, error logs, screenshots, ...?**
![7C5E3E95-9B0D-4FDB-81B6-5F162D02ABB3](https://user-images.githubusercontent.com/33403626/74043434-a7c23c00-49c9-11ea-9bff-da50f9789df6.jpeg)

**Comment by fengqiangppp** [comment]
me too

**Comment by ghost** [comment]
Fixed using https://github.com/foxlet/bootra1n
