### ISSUE TITLE
iPhone 6 Problems in jailbreaking

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [checkra1n/BugTracker#842]
> **Information**
> * iPhone 6
> * Model Number: A1586
> * Software version: 12.4.4

Firstly the steps to produce it are the regular steps to jailbreak. The reason is because i did use the GUI steps carefully then used the CLI so there is a randomity to it.

The machine i tried on is an hp pavilion running kali linux and a raspberry pi 4 GB model running raspbian full image and tried with lite image also.

The first problem is that the iPhone 6 won't jailbreak whatever i do. That happened after installing some tweaks from cydia. During the respring process it screwed and restarted rather than going into safe mode. I have tried multiple times and multiple ways but it won't work either.

The other problem is that the phone jailbroke successfully once but when i go to the home screen it has no apps except a "added to home screen icon from safari", not even stock apps. Literately I was scrolling through empty screens, the spotlight also has no apps to search for. But after restarting the phone it was restored to unjailbroken state but cydia and filza are there but can;t be opened since the phone is not in a jailbroken state.

**SO I THINK THIS IS A CRUCIAL THING**

**Comment by Randomblock1** [comment]
This is a tweak-related problem. Turn on “Safe Mode” in Checkra1n options and uninstall the bad tweak.

**Comment by YazeedAlKhalaf** [comment]
Thanks, it is solved. I upgraded to 12.4.5 and jailbroke again and it worked!

Close it??!
