### ISSUE TITLE
Sorry, iPhone 6 is supported, but iOS 10.2 is not

### ISSUE THREAD

**Issue by slaesh** [checkra1n/BugTracker#850]
.. is there a possibility to update the device? its locked..

**Comment by woachk** [comment]
> it's locked

In which way you mean? If iCloud Lock you are on your own and we will not support it.
If otherwise, get to DFU mode using a guide and then restore to an newer iOS version using iTunes (or Finder on Catalina).

Anyhow, this is not a checkra1n issue.
