### ISSUE TITLE
MacOS 10.10.5 (corrupt image when attempting to mount DMG)

### ISSUE THREAD

**Issue by williammuff** [checkra1n/BugTracker#867]
**Tell us about your setup:**
3. What version of checkra1n are you using? GUI or CLI?
0.9.8
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Mac OS X 10.10.5
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
N/A (can't even get the app to mount)

**What are the steps to reproduce the issue?**
1. Attempt to open/mount DMG
...

**What do you expect, and what is happening instead?**
The image to mount

**Does the issue also occur if you enable Safe Mode?**
N/A

**Any other info, error logs, screenshots, ...?**

**Comment by kilomanjaro4** [comment]
Hey, let me know if you find a fix or workaround for this issue. I am on the same OS 10.10.5 and I get the corrupt file too when I download it. Can't open it or mount it or verify it or anything.

**Comment by woachk** [comment]
Hello,

Known issue because the DMG compression format used for this release doesn't work on 10.11.
We are going to solve this (again) soon.

**Comment by kilomanjaro4** [comment]
Thank you for letting me know!

**Comment by Siguza** [comment]
This should have been fixed with at least 0.9.8.2.
