### ISSUE TITLE
Deleted apps remain on the screen

### ISSUE THREAD

**Issue by MatMan02** [checkra1n/BugTracker#87]
**What device + iOS version are you on?**
iPhone X 13.2.2

**What are the steps to reproduce the issue?**
1. download an app from cydia (ex: Anemone)
2. enter cydia and delete it
3. Return to home screen and the app won't delete

**What do you expect, and what is happening instead?**
I expect the app to delete, but instead it remains on the home screen (without the icon)

**Any other info, error logs, screenshots, ...?**

**Comment by JensdeVlaming** [comment]
Run uicache in terminal. 
You can install New Term 2 via Cydia. Or you can do it via SSH.
If you have trouble with SSH just leave a comment. 
Quick guide:
-Open terminal on MacBook 
-Copy past this link to install Homebrew: 
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
Copy past in terminal (after home-brew is installed): Brew install usbmuxd
- Open 2 new terminal windows after the download is finished.
- First windows: copy past: iproxy 2222 22
- Wait for a few seconds and copy past this: ssh root@localhost -p 2222 in the second window!!!
- Type in 'yes' if it asks. And hit Enter/return, if you want to abort just hit any other key.
- Type in the root password of your iPhone, by default this is 'alpine'
- Now you're in your iPhone
- Copy past: uicache 
- If there are no mistakes in the guide or you didn't make any mistakes, the apps should be gone.

Let me know if it works

**Comment by nullpixel** [comment]
Closing as a dupe of #62
