### ISSUE TITLE
iPhone 5s iOS 12.4.5 stuck "Right before trigger"

### ISSUE THREAD

**Issue by nikaqil** [checkra1n/BugTracker#871]
**Tell us about your setup:**
1. What iDevice are you using?
- iPhone 5S (GSM)
2. On what version of iOS is it?
- iOS 12.4.5 (via itunes)
3. What version of checkra1n are you using? GUI or CLI?
- 0.9.8 (both on linux)
4. What is your host system (OS version? Hackintosh? VM? etc.)?
- windows 10
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
- directly to motherboard

**What are the steps to reproduce the issue?**
1. nothing
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by sudo-ghost** [comment]
im pretty sure this is a know issue given the amount of post about this exact issue not sure when it will be fixed

**Comment by maxii26** [comment]
Same here :c

**Comment by AMDBartek** [comment]
This is a known issue. #984

**Comment by Siguza** [comment]
Marking this as duplicate of #984 (this issue is older, but the other one is more generic and thoroughly documented).
