### ISSUE TITLE
What happened if I update 13.3 to 13.3.1?

### ISSUE THREAD

**Issue by RogelioAyus** [checkra1n/BugTracker#874]
Can I still jailbreak and saved all my tweaks and my apps? I am using iPhone 6s Plus with 13.3 version, I want to upgrade to 13.3.1 cuz I have a laptop to rejailbreak but I’m afraid because I don’t know the result, since this is a different trail and error and it could lose my data, please reply

**Comment by FedeltaMedia** [comment]
Since this is a **BUG** tracker and you're not reporting a bug but instead asking a question, it's best if you remove this and ask questions related to Jailbreak here:
https://www.reddit.com/r/jailbreak/

**Comment by Siguza** [comment]
13.3.1 is supported. Just note that 13.4 beta is known to _not_ work for now.
