### ISSUE TITLE
Support for 13.4

### ISSUE THREAD

**Issue by lucifermark** [checkra1n/BugTracker#877]
**Tell us about your setup:**
1. What iDevice are you using?
Iphone X
2. On what version of iOS is it?
134
3. What version of checkra1n are you using? GUI or CLI?
Both
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Win 10
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Original cable from box itself

**What are the steps to reproduce the issue?**
1. Plz add support for 13.4 ASAP
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by reduritsch** [comment]
Yeah! I also vote for 13.4 beta support. Thanks for the great tool

**Comment by Siguza** [comment]
Fixed in checkra1n 0.10.1.
