### ISSUE TITLE
Any support for A5 and A5X based devices?

### ISSUE THREAD

**Issue by V3n3zu3l4n** [checkra1n/BugTracker#886]
Hi! rather than give me a chit chat about how are there jailbreaks for these devices, think about having checkra1n support for them. will you include it? a lot of people are expecting something like that as well.
Truly yours, V3n3zu3l4n.

**Comment by woachk** [comment]
Hello, 

We do not expect to support ARM 32-bit iOS & watchOS devices, and it isn't currently at all on the roadmap.

**Comment by V3n3zu3l4n** [comment]
Is there any reason whatsoever? hmmmmmm?

**Comment by alessaba** [comment]
@V3n3zu3l4n it's basically double the work, since A5 and A5X are 32 bit CPUs and the jailbreak was developed to only support 64 bit CPUs
