### ISSUE TITLE
iPhone 5s (iOS 12.4.5) Stuck on right before trigger

### ISSUE THREAD

**Issue by maxii26** [checkra1n/BugTracker#887]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 5s (GSM)
2. On what version of iOS is it?
iOS 12.4 and 12.4.5
3. What version of checkra1n are you using? GUI or CLI?
gui and cli
4. What is your host system (OS version? Hackintosh? VM? etc.)?
ubuntu 18.04 and 19.04 dual boot with win 10
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
3rd party with USB-A to Lightning
**What are the steps to reproduce the issue?**
1. boot ubuntu
2. open checkra1n
3. follow the steps
4. stuck on right before trigger
...

**What do you expect, and what is happening instead?**
 a bug fix :/ because I don't know how to go back to ios 12.4

**Does the issue also occur if you enable Safe Mode?**
nope

**Any other info, error logs, screenshots, ...?**
nope :c

**Comment by joanbono** [comment]
Attaching logs.

Also from iPhone 5S on 12.4.5

[iPhone5S_12.4.5.log](https://github.com/checkra1n/BugTracker/files/4194281/iPhone5S_12.4.5.log)

**Comment by joanbono** [comment]
@imanoobonthis in the meantime, on Checkra1n 0.9.8

Go to **Options** > And mark the **Enable Verbose Boot** ✅ 

This solved the problem for me in 2 iPhone 5S on 12.4.5

![image](https://user-images.githubusercontent.com/7288621/74372056-48559900-4dda-11ea-919f-1f6fd281a357.png)


<img src="https://user-images.githubusercontent.com/7288621/74372589-388a8480-4ddb-11ea-851c-950814916055.png" width="300"/> <img src="https://user-images.githubusercontent.com/7288621/74372668-57891680-4ddb-11ea-8b83-aa28db86b503.png" width="300"/>

**Comment by maxii26** [comment]
ok thank u i will try that

**Comment by Moaaga** [comment]
I also have this same problem at the time when I am writing you with an ipad air ios 9.3.5. that I just updated to ios 12.4.5. last night. (Right before trigger (this is the real bug setup) and meanwhile Dfusyncupload FAILED: -1

**Comment by joanbono** [comment]
@Moaaga have you tried enabling Verbose Boot?

**Comment by maxii26** [comment]
I dont have different results :c

**Comment by ghettoDdOS** [comment]
> @imanoobonthis in the meantime, on Checkra1n 0.9.8
> 
> Go to **Options** > And mark the **Enable Verbose Boot** 
> 
> This solved the problem for me in 2 iPhone 5S on 12.4.5
> 
> ![image](https://user-images.githubusercontent.com/7288621/74372056-48559900-4dda-11ea-919f-1f6fd281a357.png)
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/7288621/74372589-388a8480-4ddb-11ea-851c-950814916055.png"> <img alt="" width="300" src="https://user-images.githubusercontent.com/7288621/74372668-57891680-4ddb-11ea-8b83-aa28db86b503.png">

You are using version 0.9.7, it works. This problem is only on A7 with version 0.9.8 on Linux and Mac.

**Comment by joanbono** [comment]
@ghettoDdOS download 0.9.7 for Mac but anyway, it worked also with 0.9.8

**Comment by kenoButler** [comment]
version 0.9.2 worked

**Comment by AMDBartek** [comment]
This is a known issue. #984

**Comment by Siguza** [comment]
Marking this as duplicate of #984 (this issue is older, but the other one is more generic and thoroughly documented).
