### ISSUE TITLE
Home button not working after removal of setup.app / SSH not functioning anymore

### ISSUE THREAD

**Issue by JeankeVG** [checkra1n/BugTracker#888]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 6S
2. On what version of iOS is it? 13.3
3. What version of checkra1n are you using? GUI or CLI? CLI x86
4. What is your host system (OS version? Hackintosh? VM? etc.)? Ubuntu 19.10 live usb
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A third party
![Screenshot from 2020-02-12 09-15-34](https://user-images.githubusercontent.com/60261236/74321264-e2392980-4d79-11ea-9afc-c706f02551cb.png)

**What are the steps to reproduce the issue?**
1. Jailbreak with checkra1n - succesfull
2. SSH into device - succesful
3. Followed the steps to remove setup.app - succesful
mount -o rw,union,update /
mv /Applications/Setup.app /Applications/Setup.bak
uicache -a
killall backboardd

**What do you expect, and what is happening instead?**
I expect full functionality of the home button to pass device setup but nothing happens.
When trying to SSH into the device it hangs -> above screenshot, not moving at all

**Does the issue also occur if you enable Safe Mode?**
No idea, activated safe mode when jailbreaking in the options, no idea how to get into it without getting into the phone.

**Any other info, error logs, screenshots, ...?**

**Comment by woachk** [comment]
Unrelated to checkra1n.

**Comment by ghettochild2600** [comment]
@JeankeVG 

Did you ever figure this out?

**Comment by AhmadChasing** [comment]
![image](https://github.com/user-attachments/assets/40946a8b-e62a-4146-bdce-1e1ea578d8b4)


I'm getting this error when trying to
# mount -o rw, union, update /
mount_apfs: volume could not be mounted: Operation not supported mount: / failed with 69
