### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by alemciex** [checkra1n/BugTracker#889]
I jailbroken the phone with checkra1n. There was something while loading tweak from cydia and it is throwing as soon as I enter the cydia and checkra1n icon disappeared. How can I fix it?

**Comment by dim4der** [comment]
I'd ask on /r/jailbreak since I don't think the people here can help you. Your issue seems not to be related to the jailbreak itself.

**Comment by alemciex** [comment]
@dim4der my friend tell me the incident, I jailbroken with checkra1n and started installing tweak from cydia, my phone turned off and when I opened it, checkra1n icon disappeared and when I entered twydia or tweak, it was throwing away from the application I could not delete tweakes.

**Comment by dim4der** [comment]
You can try savemode in checkra1n or a restore (which means all your data will be deleted and you have to update to the latest iOS version).
But I don't think I can help you. https://reddit.com/r/jailbreak is a much better place to ask since there are more people who can help you.

**Comment by Siguza** [comment]
If your issue still exists, please file a new ticket and fill out the bug report template.
