### ISSUE TITLE
0.9.8 - Doesn't recognize iPhone X in DFU on CLI

### ISSUE THREAD

**Issue by caffeineflo** [checkra1n/BugTracker#892]
**Tell us about your setup:**
1. What iDevice are you using? iPhone X
2. On what version of iOS is it? 13.3.1
3. What version of checkra1n are you using? GUI or CLI? CLI
4. What is your host system (OS version? Hackintosh? VM? etc.)? macOS 10.15.2
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-C Apple 

**What are the steps to reproduce the issue?**
1.  Put iPhone X into DFU mode while connected to the mac
2. Start checkra1n on CLI
3. Checkra1n says "Please connect device in Normal/Recovery mode or run checkra1n in CLI mode" (it's already running in CLI mode)

**What do you expect, and what is happening instead?**
Previous version would start to jailbreak the device if it's already in DFU. 0.9.8 seems not to recognize that it's already running in CLI and satisfying the error message metioned

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
![Screen Shot 2020-02-12 at 21 47 04](https://user-images.githubusercontent.com/1525283/74396865-43481800-4de1-11ea-9e27-3052a7199fe2.png)

**Comment by caffeineflo** [comment]
Nvm, terminal != cli mode

checkra1n requires to be started with the -c flag to avoid the ncurses terminal GUI and recognize the device in DFU

**Comment by BradConde** [comment]
hi, i have the same problem with device, iphone 6s
can you help me?

**Comment by jacobecret** [comment]
> hi, i have the same problem with device, iphone 6s
> can you help me?

"checkra1n --cli"

**Comment by darkkeduardo** [comment]
presiona volumen arriba, luego volumen abajo y luego presiona el de encendido por 10 segundos
