### ISSUE TITLE
OS Update facilitate

### ISSUE THREAD

**Issue by sachingimhan** [checkra1n/BugTracker#899]
I would like to suggest if there is any way to add an OS update facilitate for this tool. today I got iCloud locked 6s mobile and it has a 10.3.4so I try to update it using iTunes but I did not work. so suggest you if you can develop this it would be better. thank you.!

**Comment by Siguza** [comment]
Bullshit.

1. There is no 10.3.4 for 6s
2. iCloud lock does not and cannot prevent an OS update.

In addition, iCloud locked devices aren't supported.
