### ISSUE TITLE
iPad Mini Problem

### ISSUE THREAD

**Issue by xavomar** [checkra1n/BugTracker#901]
**Tell us about your setup:**
1.iPad Mini
2.14.4.4
3. last one 0.9.8
4. Capitan
5. usb on Macbook

**What are the steps to reproduce the issue?**
1. connect to computer 
2. Open and executed Checkra1n
3.just crash and shows "Error Report - Request for Permission..." on every iPad Mini i try to jailbreak

**What do you expect, and what is happening instead?**

just work
**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
There is no iOS 14.4.4...

**Comment by xavomar** [comment]
iOS 13.4 mean

**Comment by Siguza** [comment]
Well that's not supported yet. Marking as duplicate of #877 then.

**Comment by xavomar** [comment]
Have to double check,  I'm on a trip and don't have it on me to verify the
ios
