### ISSUE TITLE
checkra1n application crashes when i click "cydia"

### ISSUE THREAD

**Issue by admookk** [checkra1n/BugTracker#91]
**What device + iOS version are you on?**
Ipad pro 10.5 IOS 13.2.2

**What are the steps to reproduce the issue?**
1.opening checkra1n application
2.clicking on cydia
3.checkrain installs cydia
...

**What do you expect, and what is happening instead?**
"install cydia" will popup and install cydia, application crashes
**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Hi, this issue is fixed in 0.9.1, available at https://checkra.in.

**Comment by nullpixel** [comment]
(also is a dupe of #2)
