### ISSUE TITLE
iPad Pro and Outlook 13.3 IOS crashing

### ISSUE THREAD

**Issue by cernaj** [checkra1n/BugTracker#911]
**Tell us about your setup:**
1. What iDevice are you using? iPad Pro MQEY2B/A
2. On what version of iOS is it? 13.3
3. What version of checkra1n are you using? GUI or CLI? guy
4. What is your host system (OS version? Hackintosh? VM? etc.)? latest MacOS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?USB-A directly

**What are the steps to reproduce the issue?**
1. restart iPad after jailbreak and outlook works. 
2. jailbreak and outlook crashes
3.
...

**What do you expect, and what is happening instead?**
outlook does not crash

**Does the issue also occur if you enable Safe Mode?**
not tested

**Any other info, error logs, screenshots, ...?**

**Comment by BMohan91** [comment]
Try TweakRestrictor, it worked for my outlook on iOS 13.

**Comment by cernaj** [comment]
Hi

Thanks for this. I added your repo 

https://store.geometricsoftware.se/packages/se.geometric.tweakrestrictor

But it is empty. Can you help?


Kind regards

Jurgen

**Comment by lpbuccilli** [comment]
Try adding https://apt.geometricsoftware.se

**Comment by cernaj** [comment]
Great thanks. Works great. Sorry for your patience. 

Kind regards

Jurgen

**Comment by ann0see** [comment]
I think outlook added jailbreak detection recently. So everything is working now? If that’s true, please close the issue ;-).
