### ISSUE TITLE
Re-Jailbreak not working even after updating substrate

### ISSUE THREAD

**Issue by chiragvshroff** [checkra1n/BugTracker#915]
**Tell us about your setup:**
1. What iDevice are you using?
iphone 7
2. On what version of iOS is it?
13.3
3. What version of checkra1n are you using? GUI or CLI?
GUI&CLI tried both
4. What is your host system (OS version? Hackintosh? VM? etc.)?
kali linux and macos tried both os
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
usb a

**What are the steps to reproduce the issue?**
1. jailbreak for first time
2. restart
3.re-jailbreak(bootloops)
...

**What do you expect, and what is happening instead?**
obviously expect it to re-jailbreak ans boot
but verbose appears on the phone and gets stuck on apple logo until force shutdown 
**Does the issue also occur if you enable Safe Mode?**
boots into safe mode fine

**Comment by Siguza** [comment]
Some tweak is crashing SpringBoard. You can use iCleaner to selectively disable tweaks, that should allow you to find and remove the faulty one.

Gonna close this though, since checkra1n itself appears to be working fine.
