### ISSUE TITLE
Checkra1n not deleting '/var/mobile/Library/preferences' causing Cydia crashes after attempting to re-install after update.

### ISSUE THREAD

**Issue by JustForOnce3** [checkra1n/BugTracker#916]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 6s
2. On what version of iOS is it?
iOS 13.2.3
3. What version of checkra1n are you using? GUI or CLI?
Both.
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Linux, but problem occurred on Mac.
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple lightning cable.
**What are the steps to reproduce the issue?**
1. Restore system
2. Update iOS.
3. Attempt to jailbreak again.
...

**What do you expect, and what is happening instead?**
I was expecting Cydia to install flawlessly, as usual, and continue to use my Jailbroken phone. Instead, when reinstalling Cydia, it kept crashing and could not install it properly.

**Does the issue also occur if you enable Safe Mode?**
Yes, it does.

**Any other info, error logs, screenshots, ...?**
Checkra1n did not clean it self entirely.

**Comment by ghost** [comment]
Hi ^^ So... Cydia crashes everytime? Try this: 

Open App Store
Install "Termius"
Open it and add a new host: as IP type "127.0.0.1" and as port type "44", as username type "root" and as password "alpine" and connect
Type: rm /var/mobile/Library/Cydia/metadata.cb0

Cydia should now be working ^^

**Comment by JustForOnce3** [comment]
Worked! Thank you so much.

**Comment by Siguza** [comment]
This is something Cydia should fix, not checkra1n. It's being tracked at #60 though, so I'll mark this as a dupe.
