### ISSUE TITLE
Tells you to run in cli while being in cli

### ISSUE THREAD

**Issue by EdLustig** [checkra1n/BugTracker#917]
Hello, my iPhone 6s (S8000) is connected to my MacBook (15,4) running checkra1n version 0.9.8 with a usb c adapter and a regular lighting cable. I was entering DFU manually to run ipwndfu and now I want to tether-boot, but when running checkra1n in cli (/Applications/checkra1n.app/contens/MacOS/checkra1n) it tells me that I need to run it from cli like im running it from gui. Even when just entering DFU manually (regular DFU not soft DFU from recovery, tho I haven't tried the latter) it says the same. I haven't marked it as a bug because im not sure it actually is.
<img width="717" alt="Screen Shot 2020-02-17 at 23 48 39" src="https://user-images.githubusercontent.com/50769154/74688390-06fd2900-51e0-11ea-90cb-aa8d22680c10.png">

**Comment by dalmatele** [comment]
You should run it with `-c` option:
`/Applications/checkra1n.app/Contents/MacOS/checkra1n -c`

**Comment by EdLustig** [comment]
Thanks
