### ISSUE TITLE
Stucks In Right Before Trigger

### ISSUE THREAD

**Issue by CanerKaraca23** [checkra1n/BugTracker#926]
**Tell us about your setup:**
1. iPhone 5s
2. iOS 12.4.2
3. 0.9.8
4. bootra1n
5. Just normal Lightning cable.

**What are the steps to reproduce the issue?**
I switch to DFU mode, then the process starts and I get stuck in the "right before trigger". And after a while, it says timed out.

**What do you expect, and what is happening instead?**
I heard that this error is happening on all iPhone 5s users.

**Does the issue also occur if you enable Safe Mode?**
Yes.

**Any other info, error logs, screenshots, ...?**
https://www.jailbreaktr.com/attachments/b0c4813b-7321-468c-95f0-4f92fe70a25c-jpeg.16069/

**Comment by sukualam** [comment]
same like me, iPhone 5s , 12.4.4, tried every linux distro, still same bug... "Right Before Trigger"

**Comment by junetried** [comment]
Can reproduce, although I waited three hours and did not see a time out. I turned the phone off and saw `DFUSyncUpload FAILED: -1` in the progress bar. iPhone 5S (6,1), iOS 12.4.2, running the linux installer.

**Comment by zurabi97** [comment]
It seems at the moment 0.9.8 can't be jailbroken with checkra1n due to this issue on all A7 iDevices.
Same happens there with iPad Mini 3 running iOS 12.4.5

**Comment by CanerKaraca23** [comment]
Yes, 0.9.8 isn't working on A7. But 0.9.7 works. But i can't install 0.9.7 to bootra1n.

**Comment by lb99** [comment]
> Yes, 0.9.8 isn't working on A7. But 0.9.7 works. But i can't install 0.9.7 to bootra1n.

I have a hackintosh with Yosemite macOS and checkra1n 0.97. It will not jailbreak an Ipad Air 1st Generation with 12.4.5 IOS. Stops at "Right before the trigger (this is the real bug setup). It will jailbreak my iPhone 8  with no problem. Seems to be a problem the the iPad Air 1st generation

**Comment by junetried** [comment]
> > Yes, 0.9.8 isn't working on A7. But 0.9.7 works. But i can't install 0.9.7 to bootra1n.
> 
> I have a hackintosh with Yosemite macOS and checkra1n 0.97. It will not jailbreak an Ipad Air 1st Generation with 12.4.5 IOS. Stops at "Right before the trigger (this is the real bug setup). It will jailbreak my iPhone 8 with no problem. Seems to be a problem the the iPad Air 1st generation

No, it _seems_ like a problem with the A7.

**Comment by brwajumaa** [comment]
i think the bug was fix.

**Comment by junetried** [comment]
> i think the bug was fix.

No. Using 0.9.8.2, I got to the step much quicker, but the checkra1n still hangs there.

**Comment by AMDBartek** [comment]
This is a known issue. #984

**Comment by junetried** [comment]
@AMDBartek that issue is a duplicate of this issue, as it is newer.

**Comment by Siguza** [comment]
Marking this as duplicate of #984 (this issue is older, but the other one is more generic and thoroughly documented).
