### ISSUE TITLE
Can’t enter dfu mode on 9.8

### ISSUE THREAD

**Issue by Jkceee** [checkra1n/BugTracker#927]
**Tell us about your setup:**
1. What iDevice are you using? iPhone X
2. On what version of iOS is it? 13.3.1
3. What version of checkra1n are you using? GUI or CLI? GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)? MacOS 10.15.3
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-C Apple

**What are the steps to reproduce the issue?**
1. Run app 

2. Start 

3. Try to enter dfu mode
...

**What do you expect, and what is happening instead?** I expect to enter dfu mode and then jailbreak. I just get the Apple logo after repeated tries. 

**Does the issue also occur if you enable Safe Mode?** yes. And in verbose boot

**Any other info, error logs, screenshots, ...?**

**Comment by douleireiy** [comment]
It means that [iPhone X stuck on Apple Logo](https://www.eelphone.com/solution/phone-stuck-on-apple-logo.html) at last,  try this step:
1. Press then release the volume up button.
2. Immediately press then release the volume down button.
3. Hold the side button till you see an Apple logo. Let go of the button when you see this logo.

But if it doesn't work, you have to use the tool to fix iPhone stuck on Apple Logo, it's easy to fix iOS system problem, just have a try.

**Comment by Jkceee** [comment]
It’s not stuck, it just won’t go into dfu to jailbreak.

**Comment by david2descent** [comment]
> It’s not stuck, it just won’t go into dfu to jailbreak.

You have to hold the side button and volume down for 3 seconds.  Wait at least 2 seconds  after iPhone X shows blank screen. Then after the 2 seconds release side button but keep holding volume down.  This enters dFu  mode.  You didn’t mention if you did this step or not?

**Comment by Jkceee** [comment]
I did that step. But, it’s ok. I solved in with a different cord.

**Comment by Siguza** [comment]
Yeah, Apple's USB-C cables are known to be not detected by the ROM, so it won't let you enter DFU. Any other cable should work.

I just added this info to issue #1, gonna close this as a duplicate.
