### ISSUE TITLE
Not Supported  iOS 13.3.1

### ISSUE THREAD

**Issue by grumpy777** [checkra1n/BugTracker#928]
It sit says that is is unavailable for my iPhone that is running iOS 13.3.1.

**Comment by ihorbovkit** [comment]
same question as above.

**Comment by danieltroger** [comment]
Have you tried enabling untested OS's in the options?

**Comment by ann0see** [comment]
Which phone do you use? Only the iPhone X and lower are supported.

**Comment by ihorbovkit** [comment]
Im using iPhone 7 with iOS 13.3.1.

**Comment by ann0see** [comment]
From which device did you jailbreak (MAC/PC/SBC)

**Comment by ihorbovkit** [comment]
> From which device did you jailbreak (MAC/PC/SBC)

it's MAC - > macOS Mojave 10.14.6

**Comment by ihorbovkit** [comment]
@ann0see any updates?

**Comment by ann0see** [comment]
Sorry for not commenting this issue. 
But I don’t have any idea. 
But did you try to use the latest version or a jailbreak via linux?

**Comment by ihorbovkit** [comment]
Hello @ann0see 
Yes, I used **checkra1n beta 0.9.8.2** to jailbreak the device and then **Checkm8.info iCloudBypass 1.2 beta** to unlock icloud. 

In the end, I got notification - your device was successfully bypassed
But Home isn't working anymore.

**Comment by Siguza** [comment]
13.3.1 is supported. If the checkra1n GUI of the latest release mistakenly displays it as not supported, please file a new ticket and fill out the template, in particular the device model & checkra1n version you're using.

Also @ihorbovkit note that we don't support iCloud bypasses. Apple has ramped up the effects of iCloud locks, and we won't do anything against that.
