### ISSUE TITLE
SFTP does not work with iproxy, ssh works

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#932]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 7, but i tried this on iPhone 6 Plus too
2. On what version of iOS is it?
iPhone 7: iOS 13.3.1 iPhone 6 Plus: 12.4.5
3. What version of checkra1n are you using? GUI or CLI?
Tried both, but mostly CLI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Manjaro 18.1.5 but tried Ubuntu 18.04 too.
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Original iPhone lightning cable on USB 2.0

**What are the steps to reproduce the issue?**
1. Jailbreaking works, everything works
2. iproxy 2222 44
3. ssh works, sftp does not work (Cannot initialize SFTP protocol. Is the host running an SFTP server?)
...

**What do you expect, and what is happening instead?**
sftp obviously, no sftp, only ssh

**Does the issue also occur if you enable Safe Mode?**

of course
**Any other info, error logs, screenshots, ...?**
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 3 (serial: serial here ), port 44
run_ctos_loop: fd = 712
run_stoc_loop: fd = 712
recv failed: Resource temporarily unavailable (after trying to connect with filezilla)

**Comment by Siguza** [comment]
This is not an iproxy thing, it's a dropbear thing.  
If you want SFTP, please install OpenSSH on your device (and then connect to port 22 rather than 44).
