### ISSUE TITLE
Re-open issue #533

### ISSUE THREAD

**Issue by vladaad** [checkra1n/BugTracker#936]
This was the substrate crash bug (device reboots randomly) and it got "fixed" by a substrate update but it still happens regularly to me.

**Comment by QcSamuel** [comment]
same thing for me and there no crash logs on crashreporter and on cr4shed

iphone 7 ios 13.3.1
checkra1n 0.9.8

**Comment by gnlc** [comment]
iPhone X (GSM [A1901]), iOS 13.3.1, checkra1n 0.9.8

Peek-a-View is perfect for demonstrating this problem. Just swipe pictures multiple times and app crashes for using too much memory.
Without Jailbreak or with jailbreak and not having Cydia Substrate (0.9.7101) app crashes and it can be opened normally and crash and repeat and iPhone is working normally.

Install Substrate (0.9.7101), respring and using Peek-a-View and after first crash iPhone won't work properly and will slowly force reboot.
I have tried this multiple times and crash-reboot is 100% with Peek-a-View and Substrate.

**Comment by Siguza** [comment]
Reopened issue #533, so marking this as a dupe.
