### ISSUE TITLE
Restore Error: General

### ISSUE THREAD

**Issue by SBTopZZZ-LG** [checkra1n/BugTracker#937]
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 6s
2. On what version of iOS is it?
iOS 13.3
3. What version of checkra1n are you using? GUI or CLI?
I don’t know which one. It says “Checkra1n loader 1.0.1 (1)”
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-C

**What are the steps to reproduce the issue?**
1. Nothing happens at the beginning after the jailbreak.
2. It arises only after some time, like after I use Cydia for some time.
3. And I need to jailbreak it again, so the restore option is re-usable again.

**What do you expect, and what is happening instead?**
I don’t know.

**Does the issue also occur if you enable Safe Mode?**
I haven’t tried it, as Rebooting the device or Shutting down will remove the Checkra1n app and Cydia becomes unusable.

**Any other info, error logs, screenshots, ...?**
No.

**Comment by ghost** [comment]
re-jailbreak your device and try again and there should not be problems ^^
