### ISSUE TITLE
Home button completely dead after bypass

### ISSUE THREAD

**Issue by prathamchopra12** [checkra1n/BugTracker#938]
I followed all these instructions terminal was unable to find usbmux and i googled it and tried the command with usbmuxd. Everything ahead went good but then the home button stopped working after respring. I tried to power off but it didn’t let me slide to power off or use assistive touch. They appeared but touch wasn’t letting me slide. Assistive touch too opened and closed quickly. I removed battery to restart the device but same problem appeared. Upon reading on the web I restored it with itunes but still home button isn’t working. So now I can’t put it in dfu either to retry this. I am stuck. I am using an iphone 6s on 13.3.1. Please help? I’ve tried restoring via itunes/3u tools/ imazing. I am able to enter recovery with 3u tools but cannot enter dfu. Restoring is not getting the home button back

**Comment by vladaad** [comment]
That's hardware, not software in that case.

**Comment by prathamchopra12** [comment]
But it worked perfectly before bypass trial. Are you sure?

**Comment by prathamchopra12** [comment]
> That's hardware, not software in that case.

But it worked perfectly before bypass trial. Are you sure?

**Comment by vladaad** [comment]
Yes, I'm pretty sure - Thought something similar happened to me when I was beta testing iOS 11 and I thought it was software (later ended up being my home button cable broke - which is sadly unrepairable) but if you can't even force restart (hold down home button + lock button) it's 100% hardware.

**Comment by Siguza** [comment]
It's not possible for software to affect the function of a pre-iPhone-7 home button. Your hardware just broke at an inconvenient time.

**Comment by VincentCATILLON** [comment]
I got exact same thing than @prathamchopra12 , iphone works well (all buttons), and once we did tweeks using usbmuxd, anything works :)
