### ISSUE TITLE
Packix Default Repository

### ISSUE THREAD

**Issue by andrewwiik** [checkra1n/BugTracker#95]
Currently Packix is not a default repository in the Cydia Application bundles with the Checkra1n beta 0.9. This prevents a repository that contains most likely the highest number of tweaks that will be compatible with iOS 13 out of the box from being immediately present to users. This also prevents users from easily downloading their previous purchases on Packix and a lot of users who have devices that are compatible with Checkra1n have purchased 1 or more product on Packix.

The URL needed to include Packix as a default is: https://repo.packix.com/

**Comment by TheNoim** [comment]
I also thought it is a bit weird to not include packix.

**Comment by tomt000** [comment]
Packix hosts a lot of tweaks and dependencies which are essential for any jailbreak users, it's true it should be included as a default repo

**Comment by RexSonic** [comment]
no need

**Comment by Samplasion** [comment]
This is not a bug with the jailbreak, so it should be closed immediately. By making this, you're wasting space for actual bugs

**Comment by andrewwiik** [comment]
> This is not a bug with the jailbreak, so it should be closed immediately. By making this, you're wasting space for actual bugs

As no alternative repository was provided for where to file bugs about the package managers that the jailbreak bundles this is the correct place for the issue.

**Comment by TheNoim** [comment]
@Samplasion the repo is already cluttered enough. However, an issue is not only intended for bugs. You can also use it as feature request. I see this as feature request.

**Comment by Samplasion** [comment]
@TheNoim This repository is literally called "BugTracker"

**Comment by TheNoim** [comment]
@Samplasion Whatever. We can still use it for feature requests. Like andrew said, it is the best way.

**Comment by Samplasion** [comment]
@TheNoim No, you're wasting space for the developers to find and solve actual bugs. Besides, it's like if a sign said "Don't jump off the cliff" but you jumped anyway — «whatever».

**Comment by TheNoim** [comment]
"Waste space". Ok.

**Comment by Samplasion** [comment]
Not "disk space".

**Comment by twnlink** [comment]
You can add the repo yourself if you find it to be necessary, this issue is pointless.

**Comment by DaJakerBoss** [comment]
I second this, this isn’t an issue at all, it’s a feature request at best but honestly it’s more of an advertisement they way you’re presenting it. Packix is not even an essential repo to the jailbreak as it doesn’t host any needed tools for it to run. This is nowhere near an issue at all and honestly less-than professional that you’re even opening something like this in the first place, on a repository literally labeled as a “Bug Tracker”. This isn’t a bug, why are you here

**Comment by Tr1Fecta-7** [comment]
This isn't an issue at all. +1 @Samplasion

**Comment by Bram-Brooks** [comment]
Who t f is down voting this ffs?

**Comment by nullpixel** [comment]
Packix not being included _was_ an oversight. Closing this issue as Sam has spoken to Andy.
