### ISSUE TITLE
MY PHONE WONT TURN ON!!!!!

### ISSUE THREAD

**Issue by clarkson0** [checkra1n/BugTracker#955]
I did all of the steps correct, then when i plugged in my phone and started to install it on my phone it crashed, and now my phone wont boot up, please someone HELP!!!!!

**Comment by clarkson0** [comment]
Doesnt matter ive resolved the problem

**Comment by ann0see** [comment]
How did you resolve it?

I‘d do a hard reset (pressing power and Home for around 10seconds). 
By the way: please close the issue if it’s resolved;-).

**Comment by elkinguerrab** [comment]
How did you resolve it?, my device wonot boot
