### ISSUE TITLE
Jailbreaking my iPad that the home button doesn't work

### ISSUE THREAD

**Issue by isaacwilkey** [checkra1n/BugTracker#959]
For a few months now, I've been working on trying to jail break two of my iPads that I have and I just can't figure it out. very simple yes, but they are both activation locked and I can't bypass them with the jailbreak, well one of them that is. One of my iPads, the home button doesn't work so I can't even try and jailbreak it. I would like to see a new update that I can use the side buttons as the way to jailbreak instead of the home button because mine just doesn't work.

**Comment by ghost** [comment]
You can't use Volume buttons... To enter DFU you must use the home button... It's not a checkra1n issue, it's a hardware one, and it cannot be changed. Apple force you to go in DFU by using Power and home buttons. What about repairing it?

**Comment by Siguza** [comment]
We cannot magically affect how the device enters DFU.  
Also note that we don't support iCloud bypasses.
