### ISSUE TITLE
Checkra1n does not open on my Mac

### ISSUE THREAD

**Issue by iKasprModz** [checkra1n/BugTracker#96]
**What device + iOS version are you on?**
iPhone X 13.2

**What are the steps to reproduce the issue?**
1.Downlod Checkra1n in my mac 
2.show window saying "checkra1n" is an app downloaded from the internet. Are you sure you want to open it? 
3.When I click open the window closes and nothing happens
...

**What do you expect, and what is happening instead?** I have no idea what is happening 

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
Please read the FAQ and drag the checkra1n app to your Applications folder.
