### ISSUE TITLE
Cydia crashes！

### ISSUE THREAD

**Issue by lw404-ai** [checkra1n/BugTracker#965]
iphone7 ios13.3.1 mac  checkra1n0.9.8
Hello, tool maker, I found a bug: My ios13.3.1 iphone7 used to clear jailbreak after jailbreak, now I want to jailbreak again, but after installing checkra1n, after installing cydia, cydia crashes, rebooting jailbreak is useless, I What should I do to open cydia？
Thank you
my email address：liwei-@outlook.com

**Comment by ghost** [comment]
Hi ^^ Try this:

Jailbreak your device
Download "Termius" from the App Store
Open it and add a new host: as hostname type "127.0.0.1", as port type "44", as username type "root", as password type "alpine" and connect
Once in type `rm /var/mobile/Library/Cydia/metadata.cb0`

Now try to open Cydia, and it should be working again ^^

**Comment by Woodman411** [comment]
I have a similar problem, iPhone 7 + ios 13.3.1, mac checkra1n 0.9.8

The jailbreak was successful through the mac, but when Cydia installs on the iPhone through the chekra1n app, the Cydia app opens and says "unable to load (an SSL error has occurred and a secure connection to the server cannot be made.)" I tried Termius and ran the rm, and tried re-installing Cydia through iPhone checkra1n app, but the same thing happens again.

**Comment by Siguza** [comment]
Marking as duplicate of #60.
