### ISSUE TITLE
iPad Mini 2 12.4.5, Failed to upload bootstrap.

### ISSUE THREAD

**Issue by alexkotr1** [checkra1n/BugTracker#966]
Hello, I’m unable to jailbreak my iPad mini 2 because of this error(Error Code: -20). It’s the first time I try to jailbreak so it’s not caused by an incompatible tweak. I’m using a USB-A cable, and I have hackintosh 10.15.1. Also, I’d like to mention that your jailbreak works flawlessly for my iPhone X, same cable, same pc. Thanks!

**Comment by mizaru** [comment]
Try 0.9.6, that works fine for me. Later versions don't work anymore (device gets stuck during boot).

**Comment by alexkotr1** [comment]
Oh damn that worked. Thanks!

**Comment by Siguza** [comment]
Marking as duplicate of #984.
