### ISSUE TITLE
[NOBUG] Thank you for your awesome work!

### ISSUE THREAD

**Issue by MikeeI** [checkra1n/BugTracker#968]
I think you get way too less "thank yous" for your work. 

I'm just so grateful to use it and profit from your dedication. 
It gives my iPad Air 2 so much joy ;-)

Just a thank you. 😊

![200](https://user-images.githubusercontent.com/13944905/75364662-59170c00-58bc-11ea-9692-036688e44aee.gif)

**Comment by Siguza** [comment]
Acknowledged and appreciated. 😊
