### ISSUE TITLE
Checkra1n loader disappeared 

### ISSUE THREAD

**Issue by SarKaa** [checkra1n/BugTracker#969]
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7 Plus
2. On what version of iOS is it? iOS 13.3.1
3. What version of checkra1n are you using? GUI or CLI? Cli I think, on Linux
4. What is your host system (OS version? Hackintosh? VM? etc.)? Linux
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?normal stock apple cable

**What are the steps to reproduce the issue?**
1. Jailbreak
2. There is no loader
3.
...

**What do you expect, and what is happening instead?**
It used to appear after a while after I jailbroke, but now it doesnt

**Does the issue also occur if you enable Safe Mode?**
I can’t access safe mode

**Any other info, error logs, screenshots, ...?**
I still have tweaks, but I want to restore rootfs

**Comment by Siguza** [comment]
What do you mean "can't access safe mode"? There's a checkbox in the checkra1n GUI.
