### ISSUE TITLE
Bootstrap upload failed (-18)

### ISSUE THREAD

**Issue by twaceuh** [checkra1n/BugTracker#97]
**What device + iOS version are you on?**
iPhone 8 Plus (10,5), iOS 13.2

**What are the steps to reproduce the issue?**
1.Plug the device
2.Set to DFU mode
3.Jailbreak
...

**What do you expect, and what is happening instead?**
The iPhone is jailbreaking normally and after it's rebooting without Jailbreak and Checkra1n app

**Any other info, error logs, screenshots, ...?**
- [*] Waiting for DFU devices
- [*] DFU mode device found
- [*] Attempting to perform checkm8 on 8015 11...
- [*] == Checkm8 Preparation stage ==
- [*] Stalled input endpoint
- [*] DFU mode device found
- [*] == Checkm8 Setup stage ==
- [*] Entered initial checkm8 state after 0 steps, issuing DFU abort..
- [*] DFU device disconnected
- [*] DFU mode device found
- [*] == Checkm8 Trigger stage ==
- [*] Checkmate!
- [*] DFU device disconnected
- [*] DFU mode device found
- [*] == Checkm8 Trying to run payload... ==
- [*] If everything went correctly, you should now have code execution.
- [*] DFU device disconnected
- [*] Download mode device found
- [*] Download mode device disconnected
- [*] Uploading bootstrap... 17
- [!] Bootstrap upload failed (Error -18)

**Comment by twaceuh** [comment]
Fixed by updating to iOS 13.2.2 and Checkra1n 0.9.1

**Comment by jvj11219** [comment]
I had the same issue with my 7+

It has the Audio IC issue, and occasionally boot loops for a while before powering on, so I figured that was interfering the jailbreak process.

Thanks for posting your results.

**Comment by yeetmaster2000** [comment]
HELP. I have IOS 13.5 on iPad, and it keeps on giving me this error! PLEASE HELP!!!!!!!!!!

**Comment by yeetmaster2000** [comment]
Its an iPad 2017 (5th generation)
