### ISSUE TITLE
Cant enter dfu from recovery mode when trying to jailbreak iPhone 7+

### ISSUE THREAD

**Issue by leon1995** [checkra1n/BugTracker#979]
**Tell us about your setup:**
1. iPhone 7 Plus (GSM) 
2. IOS  13.3.1
3. GUI Version 0.9.8
4. macOS Catalina Version 10.15.3, 13-inch 2018
5. Connecting via usb-c from the macbook to lightning on the iphone

**What are the steps to reproduce the issue?**
1. Launch checkra1n gui.
2. Follow the gui until you have to enter dfu mode. Phone at this point is in recovery mode through checkra1n.
3. Trying to enter dfu mode failes every time when following checkra1ns steps. It always goes back in recovery mode. I`ve tried several different ways to enter dfu mode but none of them worked.

**What do you expect, and what is happening instead?**
Expecting to enter dfu mode but its always going back to recovery mode.

When trying to enter in dfu the display turns black, then the apple logo appears and its back in recovery mode. Several sources said that when the apple logo appears its to late and I have to restart the process but even when I release the buttons earlier its still going back into recovery mode.

EDIT: I successfully entered DFU mode following this [guide](https://www.youtube.com/watch?v=a70jiFqMGX0&feature=youtu.be&t=138) but checkra1n [requires](https://ibb.co/gy6kC9S) the device being in normal or recovery mode at the start. When using the guide, while being in the "now enter dfu mode"-page in checkra1n and the device is in recovery mode, then checkra1n loses the connection to the device and checkra1n is at the start page.

EDIT 2: Even this [answer](https://github.com/checkra1n/BugTracker/issues/12#issuecomment-552206630) wasnt working. I`ve noticed that the [steps in checkra1n](https://ibb.co/SvW7r59) are different from them shown in the videos

EDIT 3: [This](https://github.com/checkra1n/BugTracker/issues/12#issuecomment-553090777) doesnt work either

**Comment by leon1995** [comment]
Entering dfu mode and jailbreaking via cli on linux worked for me

**Comment by iMonZ** [comment]
Still doesnt work on the latest checkra1n version with my iPhone 7
