### ISSUE TITLE
iPad mini 4 not jailbreaking

### ISSUE THREAD

**Issue by danielyc** [checkra1n/BugTracker#98]
**What device + iOS version are you on?**
iPad mini 4 + 13.2.2

**What are the steps to reproduce the issue?**
1. Try jailbreaking 
2.
3.
...

**What do you expect, and what is happening instead?**
Boots like normal, error -20 after some time

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment]
What tweaks do you gave installed?

**Comment by danielyc** [comment]
> What tweaks do you gave installed?

None. It’s a clean iPad. Tried it on 12.4.1 and 13.2.2.

**Comment by danielyc** [comment]
- [*] == Checkm8 Trigger stage ==
- [*] Checkmate!
- [*] DFU device disconnected
- [*] DFU mode device found
- [*] == Checkm8 Trying to run payload... ==
- [*] If everything went correctly, you should now have code execution.
- [*] DFU device disconnected
- [*] Download mode device found
- [*] Download mode device disconnected
- [!] Timed out waiting for bootstrap upload (Error -20)

**Comment by danielyc** [comment]
It started working after updating mac..
