### ISSUE TITLE
ipad pro 12.9 inch ios 13.3.1 0.9.8 the newest one thru charger, i plug in to my mac start it, i enter dfu mode, the jailbreak starts then it pauses on the white screen with the checkrain logo and all the script, after a while of waiting my ipad re-sets and then ya.

### ISSUE THREAD

**Issue by hydro7657856t** [checkra1n/BugTracker#981]
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using? GUI or CLI?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment]
Please file a new issue and fill out the bug report template instead of smashing everything into the title.
