### ISSUE TITLE
Could not launch devhelper Checkra1n 0.9.8.1

### ISSUE THREAD

**Issue by Shaq234** [checkra1n/BugTracker#998]
**Tell us about your setup:**
1. What iDevice are you using?
-
2. On what version of iOS is it?
-
3. What version of checkra1n are you using? GUI or CLI?
Checkra1n 0.9.8.1 CLI i486
4. What is your host system (OS version? Hackintosh? VM? etc.)?

Lubuntu 18.4

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
-

**What are the steps to reproduce the issue?**
1. -
2. -
3. -
...

**What do you expect, and what is happening instead?**

When I try to run checkra1n app it loads but says “Could not launch devhelper, Exiting” and it closes

**Does the issue also occur if you enable Safe Mode?**
-

**Any other info, error logs, screenshots, ...?**
Screenshot not from me but is the same error: 
![6736C131-2569-4D19-AAC3-F8400B8A3CB3](https://user-images.githubusercontent.com/57270531/76011469-03a9b300-5eeb-11ea-9185-8cfd97cd1858.jpeg)

**Comment by DragRedSim** [comment]
Same error occurs here, ARM build on RasPi 2B+, v1.2.

**Comment by woachk** [comment]
Fixed in 0.9.8.2.
